### ISSUE TITLE
Modal and Formitem Select

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1024]
### Describe the bug
I use Modal to show loading progress:

                <Modal OnCancel="@HandleModalCancel" Title="Loading" Visible="@_waitCursorLoad">
                    <div class="progress-bar">
                        <span class="bar">
                            <span class="progress"></span>
                        </span>
                    </div>
                    <div>@_T_("l_waitMsgLoad")</div>
                </Modal>

After data was loaded, I set variable @_waitCursorLoad to false. So the modal is invisible. Everything is OK.

Now I have created form for saving data and I put it on/in modal:

               <Modal Title="Saving"
                       Visible="@_visibleAdd"
                       OnOk="@HandleOKadd"
                       OkText="Save"
                       OnCancel="@HandleCancelAdd"
                       CancelText="Cancel">
                    <p>Recording Message</p>
                    <Form Model="@data_ToAdd" Context="C_Add">
                        <FormItem Label="Name"><InputText @bind-Value="@C_Add.Name" /></FormItem>
                        <div style="justify-content: space-between;display: flex;">
                            <div>
                                <FormItem Label="@_T_("l_KstSt")">
                                    <Select DataSource="@dataComboBox"
                                            @bind-Value="@C_Add.ListItem"
                                            ValueName="@nameof(C_Add.ListItem)"
                                            LabelName="@nameof(C_Add.ListItem)"
                                            DefaultActiveFirstItem
                                            Style="width: 200px;"
                                            OnSelectedItemChanged="OnSelectedItemChangedComboBox">
                                    </Select>
                                </FormItem>
                            </div>
                            <div>
                                <FormItem Label="Sorter"><AntDesign.InputNumber @bind-Value="@C_Add.sorter" /></FormItem>
                            </div>
                        </div>
                    </Form>
                </Modal>

On the save form is also a formitem SELECT. Now if I click on select field to choos an item, the dropdown list could not be open!?

If I delete the first modal code for showing loadiing-progress, the dropdown list can be open and all items will be showed.

### Further technical details
- AntDesign Nuget Package version 0.5.0-nightly-2012300110
- The IDE Community 2019 Version 16.8.3

**Comment by true-perfect-code** [comment]
...I just see that SELECT is designed so that when you click on SELECT, the list appears as a modal window.
Now probably if you use another modal window somewhere on the page and then set it VISIBLE flag to FALSE, that's why the SELECT modal window with the listing doesn't appear. 

Actually I would have expected that each modal window gets its own (random) ID and that this kind of situation is not possible!

I would like to thank you for the great work. This library is very well done and it is amazing what you can do with it!

Regards

**Comment by mutouzdl** [comment]
It may be fixed by [pr1012](https://github.com/ant-design-blazor/ant-design-blazor/pull/1012)

**Comment by anddrzejb** [comment]
@true-perfect-code I can't say I fully understand what's going on here. Can you provide a repro?

**Comment by true-perfect-code** [comment]
Here how you can reproduce it:
1. create a modal window. It can also be empty (without elements). I used this modal  window for Spiner to show the user that the data is loaded on the form.
2. then create a second modal window (use the code I gave above) and place a list box (SELECT) on it.
3. in the code part of the page (@code{...}) create two bool variables, with which you can show or hide these two windows. for example in the Init-Function, you can show the first modal window, with delay of 5 seconds, then hide it. The second window you can then activate via a extra button.

If you do it exactly the same way, you will see that on the second modal window the select box does not open. The list is not displayed.
But if you deactivate the first modal window (or don't show it at all), then the list will appear in SELECT on the second form.

I would say that SELECT list box is also a modal window and here AntBlazor cannot differentiate between these modal windows and therefore list box is also disabled by AntBlazor.

I hope that you can understand the problem with this.

Thanks

**Comment by anddrzejb** [comment]
I think I did what you requested. But I am confused - I understand from the points (1-3) that 1st modal will open, then close and then I will open the 2nd modal using button. So one after another. But in next paragraph, I understood that both modals have to be open to see the problem. I am confused. This is why I wanted to get the minimal repro. I had to reverse engineer based on what I was guessing you may want. And I have a feeling I did not do it correctly. Anyways, my code is this:
```razor
<Modal  Title="Loading" Visible="@_waitCursorLoad">
    <div class="progress-bar">
        <span class="bar">
            <span class="progress"></span>
            <Spin />
        </span>
    </div>    
</Modal>
<Button OnClick="@ShowModal">Open modal</Button>
<Modal Title="Saving"
                   Visible="@_visibleAdd"
                   OnOk="@HandleOKadd"
                   OnCancel="@HandleCancelAdd">
    <p>Recording Message</p>
    <Form Model="@data_ToAdd" Context="C_Add">
        <FormItem Label="Name">
            <InputText @bind-Value="@C_Add.Name" />
        </FormItem>
        <div style="justify-content: space-between;display: flex;">
            <div>
                <FormItem Label="Some label">
                    <Select DataSource="@dataComboBox"
                            @bind-Value="@C_Add.ListItem"
                            ValueName="@nameof(C_Add.ListItem)"
                            LabelName="@nameof(C_Add.ListItem)"
                            DefaultActiveFirstItem
                            Style="width: 200px;"
                            >
                    </Select>
                </FormItem>
            </div>
            <div>
                <FormItem Label="Sorter"><AntDesign.InputNumber @bind-Value="@C_Add.sorter" /></FormItem>
            </div>
        </div>
    </Form>
</Modal>

@code {
    bool _waitCursorLoad = true;
    bool _visibleAdd = false;
    model data_ToAdd = new model();

    public class model
    {
        public string Name { get; set; }
        public string ListItem { get; set; }
        public int sorter  { get; set; }
    }

    public class datasource {
        public string ListItem { get; set; }
    }

    List<datasource> dataComboBox;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await Task.Delay(5000);
        dataComboBox = new List<datasource>
        {
            new datasource { ListItem = "Fist" },
            new datasource { ListItem = "Second" },
            new datasource { ListItem = "Third" },
        };

        _waitCursorLoad = false;
        
        StateHasChanged();
    }

    private void ShowModal()
    {
        _visibleAdd = true;
    }

    private void HandleOKadd()
    {
        _visibleAdd = false;
    }

    private void HandleCancelAdd()
    {
        _visibleAdd = false;
    }
}
```
Can you check how the above code behaves in your project?
In my current version of `Select` (I am fixing some bugs), this does show the list. 
![1024_working](https://user-images.githubusercontent.com/6518006/106802731-06b5a200-666c-11eb-9e3d-bc86fb8bd478.gif)


If this is not the scenario that you were expecting, please create a repository in your github account with minimal code necessary to present the problem - then share the link here. It will be so so much more helpful.

**Comment by true-perfect-code** [comment]
I got my old code back and everything works as in your example! Without error!

The bug was still in the 0.5 version, now in 0.6 it seems to be fixed.

Is it still possible to check who fixed it and when?

Thanks for your effort anyway!

**Comment by anddrzejb** [comment]
Probably it is possible to check. But the easiest way I can think of is to try incrementally with nightbuilds and see when the problem was solved. Then check PRs from that build and maybe 1-by-1 check every PR (if more than one PR). 

So I guess you can close the issue now?

**Comment by true-perfect-code** [comment]
I asked about this (if you can find out that someone has already fixed the bug) because this can be a big problem in development.

For example, you have now spent a lot of time on something that someone has already fixed.

There is still the note in the post from mutouzdl commented 11 days ago "It may be fixed by pr1012".

I close issue now and thank you again for your support.

**Comment by anddrzejb** [comment]
The problem is that we do not always know that a particular bug/optimization fix is going to fix someone's issue. I am still not sure how now tracking this information could help you or others, but I am curious :smile:. If you are willing to try all the nightbuilds to find out which one actually fixed it, I will be more than happy to analyze the results with you.
Also, glad to be of help.
