### ISSUE TITLE
Select component has build errors

### ISSUE THREAD

**Issue by sjbthfc2** [ant-design-blazor/ant-design-blazor#1028]
I am trying to follow the component samples and when adding the markup to create a Select component in Visual Studio there are lots of errors as shown below. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/3796984/105488564-b91f5980-5ca9-11eb-9ffe-5634f37f183e.png)

Add a Select component bound to a simple list of objects as per the example.

- AntDesign Nuget Package 0.53

**Comment by anddrzejb** [comment]
You have other packages that have the same component name.
Add the namespace before the component to inform the compiler which component you want to use. 
```razor
<AntDesign.Select  Datasource=(...) > 
```

**Comment by sjbthfc2** [comment]
Hi @anddrzejb, thanks for that, that has worked now. The only issue though is that AntDesign is the only NuGet package I added to a brand new .NET 5 Blazor WASM app in Visual Studio with ASP.NET hosting. Is it best to prefix all components with `AntDesign.` to avoid this in the future? Have you had any other issues with AntDesign in a new out of the box Blazor WASM app?

Great components by the way, visually they look fantastic.

**Comment by anddrzejb** [comment]
Your screenshot suggests that you have already a component `Select` most probably in folder `Pages/Select.razor`. Is that correct?

**Comment by sjbthfc2** [comment]
Yes, you are absolutely right, my mistake. Thanks again for your help.
