### ISSUE TITLE
现在的项目引用了OneOf 库,导致在所有项目的TargetFramework 设为 net5.0 时候出现错误

### ISSUE THREAD

**Issue by scugzbc** [ant-design-blazor/ant-design-blazor#1049]
![image](https://user-images.githubusercontent.com/8499347/105844327-0ab24600-6014-11eb-80aa-bcef9d5142a7.png)
因为这个OneOf 依赖NETStandard.Library(1.6.1)

导致编译的时候出现如下的提示
错误	BLAZORSDK1001	The project references the ASP.NET Core shared framework, which is not supported by Blazor WebAssembly apps. Remove the framework reference if directly referenced, or the package reference that adds the framework reference.	

要求我移除这个库的引用....

是我处理得不对,还是不应该引用这个库,做对里我看了一, oneof用到得挺多的.但是这个库只用到了很少的一部分功能.可以直接自定义一个来替换掉. 或者把那个库里的部分代码直接拿出来另写一个文件.

**Comment by ElderJames** [comment]
你好，感谢关注。你的这个错误与OneOf无关，我们的文档都是正常的。
你应该是在BlazorWebAssemly项目引用了Asp.Net Core框架了，请检查一下你的csproj文件，把项目类型改成web。
