### ISSUE TITLE
Select in the Modal width problem.

### ISSUE THREAD

**Issue by mehmetuken** [ant-design-blazor/ant-design-blazor#1050]
Select component in the modal form SelectOption width to small.

<img width="603" alt="Screen Shot 2021-01-23 at 13 35 14" src="https://user-images.githubusercontent.com/9348193/105575868-d7578900-5d7f-11eb-9772-b611002d3781.png">

**Comment by anddrzejb** [comment]
Can you provide the code?

**Comment by anddrzejb** [comment]
@ElderJames I think this can be closed? The demo page does not reproduce this and since there is no code provided that we can use to recreate this issue, I do not see how we can help.
