### ISSUE TITLE
Enable dynamic form  building

### ISSUE THREAD

**Issue by ilijevicdenis** [ant-design-blazor/ant-design-blazor#1064]
I have a quite complex form to build.   I'm using Form componen with Grid system. Simple properties are working but when  I write  following code VS reports errors. 

    @foreach (var item in context.BillItems)
    {
        <Row>
            <Col Span="3">
            <FormItem Label="Price">
                <Input @bind-Value="@item.Price">
                <Suffix>USD</Suffix>
                </Input>
            </FormItem>
            </Col>
        </Row>
        <Row>test</Row>
    }

Errors: 
![image](https://user-images.githubusercontent.com/5293299/106513697-9411be80-64d3-11eb-82cc-2e0f5bd45a14.png)

I'm using Blazor server,  targeting .NET 5.0

**Comment by MutatePat** [comment]
Could you try changing <Col> to <AntDesign.Col>?

**Comment by ilijevicdenis** [comment]
@foreach (var item in context.BillItems)
    {
        <AntDesign.Row Gutter="24" Justify="ceter">
            <AntDesign.Col Span="2">
            <AntDesign.FormItem Label="Price">
                <Input @bind-Value="@item.Price">
                <Suffix>Kn</Suffix>
                </Input>
            </AntDesign.FormItem>
            </AntDesign.Col>
            @*<Col Span="2">
            <FormItem Label="Quantity">
                <Input @bind-Value="@item.Quantity">
                <Suffix>x</Suffix>
                </Input>
            </FormItem>
            </Col>
            <Col Span="2">
            <FormItem Label="Discount">
                <Input @bind-Value="@item.Discount">
                <Suffix>%</Suffix>
                </Input>
            </FormItem>
            </Col>
            <Col Span="2">
            <FormItem Label="Tax rate">
                <Input @bind-Value="@item.TaxRate">
                <Suffix>%</Suffix>
                </Input>
            </FormItem>
            </Col>*@
        </AntDesign.Row>
    }

![image](https://user-images.githubusercontent.com/5293299/106516146-ed2f2180-64d6-11eb-84c9-a0d31bbf70ca.png)

**Comment by ElderJames** [comment]
Hi @ilijevicdenis , what kind of file are you writing this code in? It doesn't look like you're writing `.razor` files.

**Comment by ilijevicdenis** [comment]
Hi, 

I'm using razor files.  
New information in meantime. I put dynamic part in separate file  and foreach loop is working.  I can generate dynamic content.

**Comment by davidesan** [comment]
Hello,
I'm facing the exact same issue but within an if statement.
How can I avoid that ?

`
@if(true)
{
    <h1>BLA</h1>
    <AntDesign.Row>
        <AntDesign.Col Span="6">
            <Button Type="primary" Shape="circle" Icon="caret-left" />
        </AntDesign.Col>
        <AntDesign.Col Span="12">
            @viewData
        </AntDesign.Col>
        <AntDesign.Col Span="6">
            <Button Type="primary" Shape="circle" Icon="caret-right" />
        </AntDesign.Col>
    </AntDesign.Row>
}
`
Is it the wrong way to use this ??

**Comment by anddrzejb** [comment]
@ilijevicdenis A bit late to the party, but in your code you are closing `<Input>` tag. That will make VS complain - `<Input>` tag is of void type, you do not close it. I got exactly the same issue, when I copied your code. But when I remove the closing `</Input>' then it worked. Mind, that VS has this bug that even though it is case sensitive, it still seem to ignore case for tags. So if you type `<Input>` it is going to think `<input>`. If you are planning to use antDesign then fully qualify it. The same problem is with `<col>` and antDesign `<Col>` tag.
So to recap, this will make VS complain:
```razor
<AntDesign.Row Gutter="24" Justify="ceter">
    <AntDesign.Col Span="2">
    <AntDesign.FormItem Label="Price">                
        <Input @bind-Value="@item.Price">
           <Suffix>Kn</Suffix>                
        </Input>
    </AntDesign.FormItem>
    </AntDesign.Col>
</AntDesign.Row>
```
This should work fine:
```razor
<AntDesign.Row Gutter="24" Justify="ceter">
    <AntDesign.Col Span="2">
    <AntDesign.FormItem Label="Price">                
        <AntDesign.Input @bind-Value="@item.Price">
            <Suffix>Kn</Suffix>                
        </AntDesign.Input>
    </AntDesign.FormItem>
    </AntDesign.Col>
</AntDesign.Row>
```
This should work also but it is a regular `<input>`:
```razor
<AntDesign.Row Gutter="24" Justify="ceter">
    <AntDesign.Col Span="2">
    <AntDesign.FormItem Label="Price">                
        <Input @bind-Value="@item.Price">
        <Suffix>Kn</Suffix>                
    </AntDesign.FormItem>
    </AntDesign.Col>
</AntDesign.Row>
```

@davidesan I tried your code but I do not get any error.

But generally, VS keeps complaining when it comes to blazor. At least that is my experience. To be honest, now I do not pay attention that much to what VS is telling me. If it compiles, I am ok. Of course this is not the experience I want to have. But don't let those phantom (at least some of them may be phantom) errors stop you.
