### ISSUE TITLE
Select:  The OnSelectedItemsChanged event is not triggered if the bind-value is not used

### ISSUE THREAD

**Issue by ma-hua** [ant-design-blazor/ant-design-blazor#1065]
The OnSelectedItemsChanged event is not triggered if the bind-value is not used.

I want to know if this is a design or a flaw

### Steps to reproduce 

[https://antblazor.com/zh-CN/components/select](https://antblazor.com/zh-CN/components/select)

SimpleSelect 

### Further technical details
- AntDesign Nuget Package version 0.6.0

**Comment by ma-hua** [comment]
In addition, the SelectedItemsChanged event is triggered when the page is loaded, which was not the case in previous versions

**Comment by anddrzejb** [comment]
Just to be sure - you mean the event `OnSelectedItemsChanged`?

**Comment by ma-hua** [comment]
> Just to be sure - you mean the event `OnSelectedItemsChanged`?
yes, you can go to the link I mentioned above and you will see that the SimpleSelect OnSelectedItemsChanged event is not triggered.

**Comment by anddrzejb** [comment]
Ok, I can see that in the docs and I recreated it in my repo. I will try to fix it in my next PR.
