### ISSUE TITLE
Date Range Picker not working correctly

### ISSUE THREAD

**Issue by benjamin86** [ant-design-blazor/ant-design-blazor#1070]
### Describe the bug
date range picker not working correctly in https://pro.antblazor.com/form/basic-form
![test](https://user-images.githubusercontent.com/7329103/106707077-971fc280-662b-11eb-826c-589d8d26bc39.gif)

correct behaviour in https://ant-design-blazor.gitee.io/en-US/components/overview
![test2](https://user-images.githubusercontent.com/7329103/106707081-9850ef80-662b-11eb-9b62-832e5edc3986.gif)

after the select start date, page not responding.

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`

**Comment by anddrzejb** [comment]
The bug here is that `RangePicker` does not handle a situation when `@bind-value` is null. So in this scenario there is
```razor
<RangePicker Style="width:100%;" TValue="DateTime?[]" @bind-Value="@context.DateRange" />
```
This code fails, because `context.DateRange` (model's property) is `null`. Until this gets fixed, a simple workaround is to actually set a default value of that property
```razor
    public class FormModel
    {
        public DateTime?[] DateRange { get; set; } = new DateTime?[] { null, null };
    }
```
