### ISSUE TITLE
Table树形数据展示时，希望可以通过配置属性来实现展开与收缩。

### ISSUE THREAD

**Issue by JiaoLongYang** [ant-design-blazor/ant-design-blazor#1073]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by ElderJames** [comment]
Fix via #1695
