### ISSUE TITLE
Steps: Current="current", cannot be set via variable

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1083]
### Describe the bug
![image](https://user-images.githubusercontent.com/45635963/106861243-cd118500-66c5-11eb-9639-e6a31d33baad.png)

But if you set Current to a number, than it works:

![image](https://user-images.githubusercontent.com/45635963/106860934-5e342c00-66c5-11eb-9e89-f50d45840c6d.png)

![image](https://user-images.githubusercontent.com/45635963/106861038-815edb80-66c5-11eb-874f-46fc68dc8b92.png)

### Steps to reproduce (please include code)
You can take the example from your website, there it does not work either

### Further technical details
- AntDesign Nuget Package version 0.6
- Community 2019

**Comment by true-perfect-code** [comment]
I played with the component a bit and found out that the problem is the update.

So once you set Current (whether via the variable or as a number), then the step is marked accordingly. But the marking can't be changed anymore, even if the variable is counted up (or down).

**Comment by ElderJames** [comment]
Hi @true-perfect-code , thanks for contacting us.

This issue we have fixed via #1071 , and the documentation site was updated and works well.

![image](https://user-images.githubusercontent.com/7550366/106868944-577bd800-670a-11eb-9acf-b6aabbb5f411.png)

https://ant-design-blazor.gitee.io/en-US/components/steps#components-steps-demo-clickable

Could you update to the lastest 0.7 nightly nuget package?

**Comment by true-perfect-code** [comment]
Workaround:

            <div>
                @if (current == 0)
                {
                    <Steps Current="0">
                        <Step Title="Step 1" Subtitle="sub titel 1" />
                        <Step Title="Step 2" Subtitle="sub titel 2" />
                        <Step Title="Step 3" Subtitle="sub titel 3" />
                        <Step Title="Step 4" Subtitle="sub titel 4" />
                    </Steps>
                }
                @if (current == 1)
                {
                    <Steps Current="1">
                        <Step Title="Step 1" Subtitle="sub titel 1" />
                        <Step Title="Step 2" Subtitle="sub titel 2" />
                        <Step Title="Step 3" Subtitle="sub titel 3" />
                        <Step Title="Step 4" Subtitle="sub titel 4" />
                    </Steps>
                }
                @if (current == 2)
                {
                    <Steps Current="2">
                        <Step Title="Step 1" Subtitle="sub titel 1" />
                        <Step Title="Step 2" Subtitle="sub titel 2" />
                        <Step Title="Step 3" Subtitle="sub titel 3" />
                        <Step Title="Step 4" Subtitle="sub titel 4" />
                    </Steps>
                }
                @if (current == 3)
                {
                    <Steps Current="3">
                        <Step Title="Step 1" Subtitle="sub titel 1" />
                        <Step Title="Step 2" Subtitle="sub titel 2" />
                        <Step Title="Step 3" Subtitle="sub titel 3" />
                        <Step Title="Step 4" Subtitle="sub titel 4" />
                    </Steps>
                }

                <div class="steps-content">
                    @steps[current].Content
                </div>
                <div class="steps-action">
                    @if (current > 0)
                    {
                        <Button Type="primary" OnClick="OnPreClick">Previous</Button>
                    }
                    @if (current < steps.Length - 1)
                    {
                        <Button Type="primary" OnClick="OnNextClick">Next</Button>
                    }
                    @if (current == steps.Length - 1)
                    {
                        <Button Type="primary" OnClick=@(() => message.Success("Processing complete!"))>
                            Done
                        </Button>
                    }

                </div>
            </div>

**Comment by true-perfect-code** [comment]
FROM ANT-BLAZOR TEAM:
This issue we have fixed via #1071 , and the documentation site was updated and works well.
https://ant-design-blazor.gitee.io/en-US/components/steps#components-steps-demo-clickable

Could you update to the lastest 0.7 nightly nuget package?

===================================================

I updated to the lastest 0.7 nightly nuget package and now it works :)

Thanks
