### ISSUE TITLE
TypeError: i.invokeMethodAsync when hover over components (Table header, Input, Auto complete)

### ISSUE THREAD

**Issue by patolax** [ant-design-blazor/ant-design-blazor#1086]
When ever we hover over table header we get TypeError: i.invokeMethodAsync error. It also happens when we hover over inputs, autocomplete and most of other controls. 

This stated to happen when we upgraded to 0.6.0 version. All other versions.
![image](https://user-images.githubusercontent.com/29444156/106872708-b4d25200-6727-11eb-8c3b-6f30192baa4e.png)

![image](https://user-images.githubusercontent.com/29444156/106871759-b2232d00-6726-11eb-9277-1f0bc9901239.png)

**Comment by ElderJames** [comment]
Thank you for contacting us @patolax 

Please try to clear the browser cache.

**Comment by patolax** [comment]
thanks that worked.
