### ISSUE TITLE
A required property SortType property is removed from Table

### ISSUE THREAD

**Issue by adithyauday** [ant-design-blazor/ant-design-blazor#1092]
![CaptureNow](https://user-images.githubusercontent.com/62529998/106963771-33b1a400-6795-11eb-821d-1da02d446725.jpg)

### Describe the bug

Prior versions had a property SortType which would give us the direction (ascending | descending) which is used to call services.
Now it's being replaced by _sortDirection which is inaccessible.
I assume Sort was supposed to get the direction but it is never set.
Please help if their is an alternate way to get the Sort Direction, or if not this could be fixed soon.

Thank you.

**Comment by adithyauday** [comment]
Thank you so much for taking your time for solving the issue. When do you think this will be available on release?

**Comment by ElderJames** [comment]
We would release a patch version next week.
