### ISSUE TITLE
Possibilities of the tables component

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1103]
### Is your feature request related to a problem? Please describe.
In table examples on AntBlazor there is nothing about editing of individual lines.
Out of urgency, I tried to insert the input box and slider into the table and I am very positively surprised that it works.

To be sure that my approach does not cause any trouble, I need a short confirmation from you that this is possible.

If it is possible, it would be good to put some examples on your site, so that people are familiar with this possibility. The possibility to edit the rows directly in the table is great and can bring the work and the usability to a higher level in many projects.

### Describe the solution you'd like
Here is my example:

                                    <Table @ref="table"
                                           TItem="myModel"
                                           DataSource="@data"
                                           @bind-PageIndex="_pageIndex"
                                           @bind-PageSize="_pageSize"
                                           Context="C_">
                                        <Column Width="300" Title="Products" @bind-Field="@C_.ProductName">@C_.ProductName</Column>
                                        <Column Width="200" Title="Costs" Field="@C_.Costs">
                                            <Slider Min="1" Max="1000" TValue="double" @bind-Value="@C_.Costs" />
                                        </Column>
                                        <Column Width="100" Field="@C_.Costs">
                                            <Input Class="column-input-width" @bind-Value="@C_.Costs"/>
                                        </Column>
                                        <Column Field="@C_.Costs">@C_.Costs.ToString("C", CultureInfo.CurrentCulture)</Column>
                                    </Table>

### Additional context

![image](https://user-images.githubusercontent.com/45635963/107030022-41285780-67b0-11eb-9fc0-6c80ad483a3c.png)

AntBlazor 0.7

**Comment by ElderJames** [comment]
Thank you for contacting us @true-perfect-code 

That's right, the data-entry components are work well in table columns.

The only thing should be noticed is the style. Because there is a special style for editable cells.

Could you please submit a PR for the editable cells?

**Comment by true-perfect-code** [comment]
Hi ElderJames

What do you mean by PR ?

**Comment by ElderJames** [comment]
I meant pull request. 
We are very glad if you can submit a pull request for our project.

**Comment by ElderJames** [comment]
Hi @true-perfect-code , we have add the demo via #1152 .
