### ISSUE TITLE
Form support native action attribute

### ISSUE THREAD

**Issue by ycc3000** [ant-design-blazor/ant-design-blazor#1106]
Form组件如何能使用action属性？谢谢。

**Comment by ElderJames** [comment]
Thanks for contacting us @ycc3000 
Currently we haven't support the form sync submit.

**Comment by ycc3000** [comment]
dear @ElderJames ,
It is property on html form attribute only, <form .... action="https://xxx"></form>, not sync submit.

**Comment by ElderJames** [comment]
You are right. But we do not recommend using native Forms for SPA applications.

**Comment by ElderJames** [comment]
Perhaps a way to synchronize form submissions could be implemented. When it is time to submit, dynamically create a form element to submit.
