### ISSUE TITLE
How to customize  ModalService 

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1113]
### Is your feature request related to a problem? Please describe.
ModalService is an excellent way to bring the messages to the user very easily.

However, there are also cases when you want to notify the user about something so that other functions are executed after that ( e.g. you bring the message "All errors will be shown to you in the next window" and then you open a second modal window on which all error messages are listed). 
Now I have seen that ModalService also offers this possibility by using the method in the following way:

                await _modalService.ConfirmAsync(new ConfirmOptions()
                {
                    Title = "Info",
                    Content = "All errors will be shown to you in the next window",
                    OkText = "Close"
                });

Now the question: 
Can you give some examples how to customize the rest of the elements of the modalService? 

For example, in the above example there is no icon displayed. Or I want to have only close button, not also cancel button.

Thanks

### Describe the solution you'd like
                await _modalService.ConfirmAsync(new ConfirmOptions()
                {
                    Title = "Info",
                    Content = "All errors will be shown to you in the next window",
                    OkText = "Close"
                });

### Additional context
Ant-Blazor 0.7
Community 2019

**Comment by MutatePat** [comment]
You could use a proper modal component to achieve such custom actions. I believe the modal service is meant for basic messages. You can find the article relating to the modal component on antblazor.com ( our docs)

**Comment by true-perfect-code** [comment]
I know that, but here the crucial advantage is that you can generate the message in the code behind!

In opposite to your suggestion to do this on page, where you would need a bool variable to show or hide the window, this variant is of course much more elegant.

But I don't find anything in the documentation :(

**Comment by true-perfect-code** [comment]
Yes it is indeed in the documentary :) Thanks

**Comment by michaelcsikos** [comment]
Having the option to hide the `Cancel` button with the `ModalService` would be extremely useful.
