### ISSUE TITLE
localization issue for Form Validator Message

### ISSUE THREAD

**Issue by kennylovecode** [ant-design-blazor/ant-design-blazor#1114]
根据官方文档，进行了中文本地化后，FORM的Validator Message 依然显示英文
如下图，输出了当前本地化的 FormLocal里面的 Required
![image](https://user-images.githubusercontent.com/43694453/107147677-4640fe80-698a-11eb-80e8-067e6df52d95.png)

但是右边的表单还是提示的英文，是否还需配置其他项，亦或这本身是个BUG

这个问题已经困扰了一天，查看源码与官方文档暂时得不到很好的解决，遂问求解！

**Comment by ElderJames** [comment]
你好，From 还不支持本地化。如果没有多语言需求，可以在验证特性中写中文的错误信息。

**Comment by kennylovecode** [comment]
> 你好，From 还不支持本地化。如果没有多语言需求，可以在验证特性中写中文的错误信息。

那么FormLocale这个是起到什么作用的呢？亦或是在多少版本规划内会有本地化的实现。

**Comment by ElderJames** [comment]
0.8 版本可以做

**Comment by kennylovecode** [comment]
> 0.8 版本可以做

好的，感谢解疑

**Comment by ElderJames** [comment]
The Form component have been support localization .
https://antblazor.com/en-US/components/form#components-form-demo-localization
