### ISSUE TITLE
Selected and unselected states are not refreshed when the Tree component node is clicked

### ISSUE THREAD

**Issue by starts2000** [ant-design-blazor/ant-design-blazor#1116]
### Describe the bug

Tree  组件节点点击后， 选中和非选中状态显示不刷新
![image](https://user-images.githubusercontent.com/26303338/107168809-54793400-69f7-11eb-8533-e312c2b02b86.png)

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
你好，看起来react版本的行为也是这样的。
![image](https://user-images.githubusercontent.com/7550366/110427528-db96f600-80e2-11eb-9620-d1841c492b13.png)

**Comment by starts2000** [comment]
[官方示例]( https://ant.design/components/tree-cn/)点击一项后，再点击另外一项，选中状态的项才有背景色，非选中项是没有背景色的
![image](https://user-images.githubusercontent.com/26303338/110428092-bbb40200-80e3-11eb-9795-18089fa28848.png)

**Comment by ElderJames** [comment]
blazor 版本也是这样的。请看现在最新0.7.1版本的文档

**Comment by starts2000** [comment]
我看 [网站](https://antblazor.com/zh-CN/components/tree) 示例是没有有更新的，还是0.7.0， 原来 0.7.1 已经修正了，谢谢！
