### ISSUE TITLE
OnChange in RadioGroup

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1119]
### Describe the bug
Is there an example in the documentation for using OnChange event with radio buttons?

I have tried quite a few things, but always get the message:

The error was: Unable to cast object of type 'Microsoft.AspNetCore.Components.EventCallback`1[Microsoft.AspNetCore.Components.ChangeEventArgs]' to type 'Microsoft.AspNetCore.Components.EventCallback`1[System.Int32]'.

This is probably because the binding is an int (see @bind-Value="@wsID" ) and a parameter of type ChangeEventArgs is expected in the event function (see protected void SelectionChanged).

### Steps to reproduce (please include code)
My code looks like this:

        <RadioGroup @bind-Value="@wsID" Size="small" OnChange="SelectionChanged">
                @foreach(WebclientWorkstationsModel item in data_ClientWorkstations)
                {
                <Radio RadioButton Value="@item.ID">@item.WorkstationsName</Radio>
                }
            </RadioGroup>

Code behind:
        protected void SelectionChanged(ChangeEventArgs e)
        {
            //....
        }

### Exceptions (if any)
Error CS0411 TypeInference.CreateRadioGroup_0<TValue>(RenderTreeBuilder, int, int, string, int, EventCallback<TValue>, int, TValue, int, EventCallback<TValue>, int, Expression<Func<TValue>>, int, RenderFragment)-Methode können nicht per Rückschluss aus der Syntax abgeleitet werden. Geben Sie die Typargumente explizit an.

### Further technical details
- AntDesign Nuget Package version 0.7
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version Community 2019

**Comment by ElderJames** [comment]
Hi, please specific the TValue="int"

**Comment by true-perfect-code** [comment]
Thanks it works now.
