### ISSUE TITLE
I have a page where he contains a drawer page, and the drawer page has a drop-down selector (multi-select) that reports an error when the page is loaded.

### ISSUE THREAD

**Issue by JiaoLongYang** [ant-design-blazor/ant-design-blazor#1120]
### Describe the bug

I have a page where he contains a drawer page, and the drawer page has a drop-down selector (multi-select) that reports an error when the page is loaded.

![image](https://user-images.githubusercontent.com/20771689/107321349-4e5d8300-6add-11eb-82fd-651541ade43c.png)

saPostDropDownList is a List of DropDownRes.
The following figure shows the error message after the page is loaded
![image](https://user-images.githubusercontent.com/20771689/107321511-9da3b380-6add-11eb-8d3c-4489ecebfd51.png)

**Comment by anddrzejb** [comment]
Can you post whole code of the form? This exception is thrown by `FormItem`. Not necessarily directly connected to `Drawer`/`Select`/`Dropdown`.

**Comment by JiaoLongYang** [comment]
我临时给组件的属性bind-value也绑定值，则不会出现这个错误。也许是bind-value与bind-values有冲突。
![image](https://user-images.githubusercontent.com/20771689/107374161-41af4e00-6b22-11eb-94be-a5dc9442aab0.png)
`<Drawer Closable="true" Width="450" Visible="@ShowAddOrEditModal" Title='@("员工"+(DoType==SGP.Shared.ModelEnum.EnumLogDoType.Add?"添加":"编辑"))' OnClose="_=>ShowAddOrEditModal=false">
    <Template style="height:90%">
        <Form Layout="@FormLayout.Horizontal"
              LabelColSpan="6"
              WrapperColSpan="18"
              Model="@WorkerAddOrEdit">
            <FormItem Label="所属单位">
                <Select DataSource="@(DeptDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.DeptId"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="员工姓名">
                <Input @bind-Value="@WorkerAddOrEdit.Name" MaxLength="10" />
            </FormItem>
            <FormItem Label="身份证号">
                <Input Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.IdNo" MaxLength="18" />
            </FormItem>
            <FormItem Label="联系电话">
                <Input Type="tel" Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.PhoneNo" MaxLength="11" />
            </FormItem>
            <FormItem Label="普通岗位">
                <Select Mode="multiple"
                        DataSource="@PostDropDownList"
                        @bind-Value="@tmp.Id"
                        @bind-Values="@WorkerAddOrEdit.Post"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch
                        AllowClear>
                </Select>
            </FormItem>
            <FormItem Label="安管岗位">
                <Select Mode="multiple"
                        DataSource="@SaPostDropDownList"
                        @bind-Value="@tmp.Id"
                        @bind-Values="@WorkerAddOrEdit.SaPost"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch
                        AllowClear>
                </Select>
            </FormItem>
            <FormItem Label="员工性别">
                <Select DataSource="@(SexDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.Sex"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="政治面貌">
                <Select DataSource="@(PoliticalDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.Political"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="员工学历">
                <Select DataSource="@(DegreeDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.Degree"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="邮箱地址">
                <Input Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.Email" MaxLength="30" />
            </FormItem>
            <FormItem Label="联系地址">
                <Input Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.Address" MaxLength="100" />
            </FormItem>
        </Form>
        <div class="drawer-btn-container">
            <Button Type="@ButtonType.Primary" OnClick="a=>ShowAddOrEditModal=false" Danger>取消</Button>
            <Button Type="@ButtonType.Primary" HtmlType="submit" OnClick="DoAddOrEdit" Loading="@LoadingOfAddOrEdit">确定</Button>
        </div>
    </Template>
</Drawer>`

**Comment by JiaoLongYang** [comment]
@anddrzejb
 I temporarily bind values to the component's property bind-value as well, and this error does not occur. Maybe there is a conflict between bind-value and bind-values.
![image](https://user-images.githubusercontent.com/20771689/107377001-77096b00-6b25-11eb-8326-253f39f63219.png)

**Comment by anddrzejb** [comment]
What I would like to see is your form model as well. For one, it will take me much less time to copy what you did instead of trying to guess exactly the way you did it. Can you post the whole thing, this way (just a sample):
```razor
<Form Model="@Model">
    <Validator>
        <DataAnnotationsValidator />
    </Validator>
    <ChildContent>
        <FormItem Label="User Name">
            <Input @bind-Value="@context.UserName" />
        </FormItem>
        <FormItem Label="Password">
            <InputPassword @bind-Value="@context.Password" />
        </FormItem>
        <button type="submit">Save</button>
    </ChildContent>
</Form>
@code {
    LoginModel Model = new LoginModel();

    protected override async Task OnInitializedAsync()
    {
        await Task.Delay(1);
        this.Model = new LoginModel
        {
            UserName = "Tom",
            Password = "123456",
        };
        await base.OnInitializedAsync();
    }

    public class LoginModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}
```
This code should work just by copy-paste without any additional work needed from the reader.

I would like to copy your code and with minimal modification see the issue. And then try to figure out what is the real problem and find the solution.

**Comment by JiaoLongYang** [comment]
@anddrzejb 
Sorry, I didn't describe the problem clearly. Here is my code, I hope this will help to find the problem.

```

public List<DropDownRes> PostDropDownList = new List<DropDownRes>();
public List<DropDownRes> SaPostDropDownList = new List<DropDownRes>();
public WorkerDto WorkerAddOrEdit = new WorkerDto();

public class DropDownRes
    {
        /// <summary>
        /// 编码
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
    }

public class WorkerDto
    {
        public string Id { get; set; }
        /// <summary>
        ///  单位代码
        /// </summary>
        [Required(ErrorMessage = "请选择所属单位")]
        public string DeptId { get; set; }

        /// <summary>
        ///  员工姓名
        /// </summary>
        [Required(ErrorMessage = "请输入员工姓名")]
        [Export(Title = "员工姓名", SortNo = 3)]
        public string Name { get; set; }

        /// <summary>
        ///  身份证号
        /// </summary>
        [Required(ErrorMessage = "请输入身份证号")]
        [MaxLength(18, ErrorMessage = "身份证号格式错误")]
        [Export(Title = "身份证号", SortNo = 4)]
        public string IdNo { get; set; }

        /// <summary>
        ///  联系电话
        /// </summary>
        [Required(ErrorMessage = "请输入联系电话")]
        [MaxLength(11, ErrorMessage = "联系电话格式错误")]
        [Export(Title = "联系电话", SortNo = 5)]
        public string PhoneNo { get; set; }
        /// <summary>
        /// 邮箱地址
        /// </summary>
        [Export(Title = "邮箱", SortNo = 12)]
        public string Email { get; set; }
        /// <summary>
        ///  用户性别
        /// </summary>
        public string Sex { get; set; }
        /// <summary>
        ///  联系地址
        /// </summary>
        [Export(Title = "联系地址", SortNo = 13)]
        public string Address { get; set; }
        /// <summary>
        /// 头像附件编码
        /// </summary>
        public string FileIdOfFace { get; set; }
        /// <summary>
        /// 普通岗位
        /// </summary>
        [Required(ErrorMessage = "请选择普通岗位")]
        public IEnumerable<string> Post { get; set; }
        /// <summary>
        /// 安管岗位
        /// </summary>
        [Required(ErrorMessage = "请选择安管岗位")]
        public IEnumerable<string> SaPost { get; set; }

        /// <summary>
        ///  学历
        /// </summary>
        public string Degree { get; set; }

        /// <summary>
        ///  政治面貌
        /// </summary>
        public string Political { get; set; }
    }

```

```
<Drawer Closable="true" Width="450" Visible="@ShowAddOrEditModal" Title='@("员工"+(DoType==SGP.Shared.ModelEnum.EnumLogDoType.Add?"添加":"编辑"))' OnClose="_=>ShowAddOrEditModal=false">
    <Template style="height:90%">
        <FileTable MaxCount="5" Style="margin:0px 20px 20px 20px;width:410px;height:80px;"></FileTable>
        <Form Layout="@FormLayout.Horizontal"
              LabelColSpan="6"
              WrapperColSpan="18"
              Model="@WorkerAddOrEdit">
            <FormItem Label="所属单位">
                <Select DataSource="@(DeptDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.DeptId"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="员工姓名">
                <Input @bind-Value="@WorkerAddOrEdit.Name" MaxLength="10" />
            </FormItem>
            <FormItem Label="身份证号">
                <Input Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.IdNo" MaxLength="18" />
            </FormItem>
            <FormItem Label="联系电话">
                <Input Type="tel" Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.PhoneNo" MaxLength="11" />
            </FormItem>
            <FormItem Label="普通岗位">
                <Select Mode="multiple"
                        DataSource="@PostDropDownList"
                        @bind-Value="@tmp.Id"
                        @bind-Values="@WorkerAddOrEdit.Post"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch
                        AllowClear>
                </Select>
            </FormItem>
            <FormItem Label="安管岗位">
                <Select Mode="multiple"
                        DataSource="@SaPostDropDownList"
                        @bind-Value="@tmp.Id"
                        @bind-Values="@WorkerAddOrEdit.SaPost"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch
                        AllowClear>
                </Select>
            </FormItem>
            <FormItem Label="员工性别">
                <Select DataSource="@(SexDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.Sex"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="政治面貌">
                <Select DataSource="@(PoliticalDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.Political"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="员工学历">
                <Select DataSource="@(DegreeDropDownList)"
                        @bind-Value="@WorkerAddOrEdit.Degree"
                        LabelName="@nameof(DropDownRes.Name)"
                        ValueName="@nameof(DropDownRes.Id)"
                        Placeholder="请选择"
                        EnableSearch>
                </Select>
            </FormItem>
            <FormItem Label="邮箱地址">
                <Input Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.Email" MaxLength="30" />
            </FormItem>
            <FormItem Label="联系地址">
                <Input Placeholder="请输入" @bind-Value="@WorkerAddOrEdit.Address" MaxLength="100" />
            </FormItem>
        </Form>
        <div class="drawer-btn-container">
            <Button Type="@ButtonType.Primary" OnClick="a=>ShowAddOrEditModal=false" Danger>取消</Button>
            <Button Type="@ButtonType.Primary" HtmlType="submit" OnClick="DoAddOrEdit" Loading="@LoadingOfAddOrEdit">确定</Button>
        </div>
    </Template>
</Drawer>
```

**Comment by anddrzejb** [comment]
Digging deeper, it seems that `Form` does not yet support `IEnumerable` for model binding. @ElderJames , can you concur? I can see in `AntInputComponentBase` missing `ValueExpression` for `IEnumerable`. My quick trial show this is a bit more involved change. If I am right, at the moment @JiaoLongYang you could probably solve this by using `Select`'s `OnSelectedItemsChanged` event and just update your model manually?

**Comment by valentasm1** [comment]
What about workarounds binding values to Select?
Picking up values with OnSelectedItemsChanged could work.

**Comment by anddrzejb** [comment]
As a poor's man workaround I did something like this:
```razor
    <Row class="ant-form-item">
        <AntDesign.Col class="ant-form-item-label" Span="8">
            <label>A label</label>
        </AntDesign.Col>
        <AntDesign.Col class="ant-form-item-control" Span="16">
            <AntDesign.Select 
                                @bind-Values="@_selectedValues"
                                Mode="multiple"
                                DataSource="@dataSource"
                                TItem="Item"
                                TItemValue="int"
                                OnSelectedItemsChanged="@OnItemsChangedHandler"
                                AllowClear>
            </AntDesign.Select>
            @*@_formValidationMessages*@
        </AntDesign.Col>
    </Row>
```
You have to handle your validation messages manually I am afraid...

**Comment by valentasm1** [comment]
@anddrzejb  i could try help creating PR for ValueExpression for IEnumerable , but would be great get some direction. I dont want spend too much time bogling in code

**Comment by anddrzejb** [comment]
@valentasm1 I can try to help as much as I can, but I didn't do much work around the `Form` component, so that's that.
