### ISSUE TITLE
Steps Control Broken

### ISSUE THREAD

**Issue by JosefRousal** [ant-design-blazor/ant-design-blazor#1132]
### Describe the bug

The code used in the demo found here [https://antblazor.com/en-US/components/steps#components-steps-demo-step-next](https://antblazor.com/en-US/components/steps#components-steps-demo-step-next) does not advance the current highlighted step when the next or previous buttons are clicked. 

Tested with version 0.6.0.

### Steps to reproduce (please include code)

- Create new Blazor Project
- Set up AntBlazor (v0.6.0) as per documentation
- Copy and paste code from demo into index component
- Run

### Further technical details
- AntDesign Nuget Package version: 0.6.0

**Comment by samsbase** [comment]
I am currently using 0.6.0-nightly-2102031544 in order to avoid this issue breaking half my application.

**Comment by anddrzejb** [comment]
@samsbase Why aren't you raising any issues? Please, if you find a bug, let us know here.

**Comment by ElderJames** [comment]
Please update to lastest 0.7 nightly.

**Comment by samsbase** [comment]
Updated to nightly 0.7.0-nightly-2102090212 fixed this issue

**Comment by ElderJames** [comment]
That's fine! Thanks.
