### ISSUE TITLE
The type of component 'Select' cannot be inferred based on the values provided

### ISSUE THREAD

**Issue by sapakus** [ant-design-blazor/ant-design-blazor#1135]
### Describe the bug
Getting error when trying to use Select dropdown.

### Steps to reproduce (please include code)

```

@using OneOf;
<Select OnChange="@OnChange">
    @foreach (var item in _items)
    {
        <SelectOption Value="@item">@item</SelectOption>
    }
</Select>

@code
{
    private readonly string[] _items = new[] { "Apples", "Nails", "Bananas", "Helicopters" };

    private void OnChange(OneOf<string, IEnumerable<string>, LabeledValue, IEnumerable<LabeledValue>> value, OneOf<SelectOption, IEnumerable<SelectOption>> option)
    {
        Console.WriteLine($"selected: ${value}");
    }
}

```
### Exceptions (if any)

Error	RZ10001	The type of component 'Select' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'TItemValue', 'TItem'

### Further technical details
- AntDesign Nuget Package version : 0.6.0
- Include the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

```
- Microsoft Visual Studio Community 2019
Version 16.8.4

**Comment by ElderJames** [comment]
Thanks for contacting us @sapakus 
Please clear your browser cache and use the lastest version.
The select should specific the type of TItem and TValue.

**Comment by anddrzejb** [comment]
@sapakus Did you solve your problem? Can this issue be closed?

**Comment by ElderJames** [comment]
The Select component was rewrite few months ago. So we could close this issue first.
If you have any problems on the latest version, just feel free to open a new issue.
