### ISSUE TITLE
Form IsModified is always false

### ISSUE THREAD

**Issue by gregloones** [ant-design-blazor/ant-design-blazor#1139]
### Describe the bug

The form's IsModified property remains false even when the form is modified.

### Steps to reproduce (please include code)
- Go to the demo page https://antblazor.com/en-US/components/form and scroll down to the IForm.IsModified demo
- Fill in the form
- The Submit button remains disabled

### Further technical details
- AntDesign Nuget Package version 0.6.0 and 0.7.0 nightly

**Comment by anddrzejb** [comment]
I think it was broken because of automatic validation being turned off. The docs mention this in validation area (below IForm.IsModified section): 
>(v0.5+) Validation is turned off by default for performance reasons.   

But IForm.IsModified functionality actually needs to have validation on. Add `ValidateOnChange="true" in your form:
```razor
<Form @ref="form"
      ValidateOnChange="@true"
(...)
>
```
@Hona, is it possible for you to update your PR #1131 to include this fix in the docs?

**Comment by Hona** [comment]
Yeah, the PR has a bit more work before it is ready to be merged, so I'll add that to the list

**Comment by gregloones** [comment]
>Add `ValidateOnChange="true" in your form

That did the trick, thanks!

**Comment by mkalinski93** [comment]
Would it be possible to have an additional member to reset the IsModified state?
After submit, the state remains the same.

**Comment by ElderJames** [comment]
Hi @mkalinski93, you can submit a PR for that.

**Comment by sudomabider** [comment]
A presumably related issue is that `OnFieldChanged` only works when  `ValidateOnChange="@true"`. It's a good thing we've updated the docs for `IsModified`. But it is really counter intuitive. And there could be other "side effects". Are we happy with this solution or do we want to perhaps separate the responsibilities a bit more (assuming it's possible)?

**Comment by ElderJames** [comment]
Maybe we also need to add a supplementary note to `OnFieldChanged` in the API section.
