### ISSUE TITLE
Table filters

### ISSUE THREAD

**Issue by YMohd** [ant-design-blazor/ant-design-blazor#1140]
### Describe the bug

Can I know when columns filters will be added to table component? which version will have this change?   
### Further technical details
- AntDesign Nuget Package version v .6
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version VS 2019

**Comment by YMohd** [comment]
Hi,

Thanks for adding the feature ,is there a plan to add more filter options and when? like more than one filter condition per column using and\or ,text search ,date search....,

**Comment by ElderJames** [comment]
@YMohd Hi, we will prioritize the functionality in the React implement. Also, there are not enough contributors to ensure a functional completion deadline. If you are interested, you are welcome to contribute.

**Comment by ElderJames** [comment]
@YMohd Hi, we will prioritize the functionality in the React implement. Also, there are not enough contributors to ensure a functional completion deadline. If you are interested, you are welcome to contribute.

**Comment by ElderJames** [comment]
@YMohd Hi, we will prioritize the functionality in the React implement. Also, there are not enough contributors to ensure a functional completion deadline. If you are interested, you are welcome to contribute.
