### ISSUE TITLE
Badge在layout的header中的显示问题

### ISSUE THREAD

**Issue by dawningzhang** [ant-design-blazor/ant-design-blazor#1147]
Badge徽标在layout的header中使用时如果设置color属性，徽标位置会出现问题,如下图
![image](https://user-images.githubusercontent.com/64716352/108582890-e4f93200-7370-11eb-8c79-6f93c9bc57b3.png)
![image](https://user-images.githubusercontent.com/64716352/108582895-ef1b3080-7370-11eb-9cc9-40918176c30e.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @dawningzhang ,
 Please paste the code here so that we can test it more easily.

**Comment by dawningzhang** [comment]
> Thanks for contacting us @dawningzhang ,
> Please paste the code here so that we can test it more easily.

```
<Layout Style="background:#fff;height:100vh">
    <Header>
        <Badge Count="5" ShowZero Color="green">
            <Button Type="@ButtonType.Default" Style="width:150px">
                <Icon Type="search" Theme="outline" /> 查询
            </Button>
        </Badge>
    </Header>
    <Footer>
        <Badge Count="5" ShowZero Color="green">
            <Button Type="@ButtonType.Default" Style="width:150px">
                <Icon Type="search" Theme="outline" /> 查询
            </Button>
        </Badge>
    </Footer>
    <Layout Style="padding-top:5px;padding-bottom:10px;">
    </Layout>
</Layout>
```

**Comment by ElderJames** [comment]
Hi @dawningzhang , the color property is just for dot mode. please don't use color for counter mode. You can change the color by using style and set the background-color.

按照react的实现，color属性只用于状态点。如果你想改变计数器的颜色，可以使用Style属性设置背景颜色的样式。
