### ISSUE TITLE
Tree, highlighted nodes by multiselection

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1150]
### Is your feature request related to a problem? Please describe.
Is it possible to switch off the multiselection in the tree component, so that when clicking on a node, the clicked node is highlighted in blue and the other are not?

### Describe the solution you'd like
Here we see the example from the Ant-Blazor page. Whenever you click on a node, it is immediately highlighted in blue. 

![image](https://user-images.githubusercontent.com/45635963/108633263-98e2e600-7473-11eb-8673-eb82c3cfa133.png)

It would be expected that when you click on a node, the other nodes lose the blue marking.

![image](https://user-images.githubusercontent.com/45635963/108633356-23c3e080-7474-11eb-8a6f-6736aa0667a4.png)

### Additional context
Ant-Blazor 0.7

**Comment by anddrzejb** [comment]
There seems to be attribute `Multiple` that you should set to `false`, but a quick look at it tells me it does not seem to work as expected. Looks like a bug...

**Comment by zmayor** [comment]
![tree_node_cascading_parameter](https://user-images.githubusercontent.com/18019463/108795730-fb49fc80-75c1-11eb-8ae3-e3cff7c30b22.png)
I find the cascading parameter `SelfNode`  of `TreeNodeTitle` does not sync with the upper `TreeNode`. It lead to the display confusion , but I am wondering how to fix it . Can you give me some suggestions? @anddrzejb @ElderJames

**Comment by zmayor** [comment]
![image](https://user-images.githubusercontent.com/18019463/108797601-84633280-75c6-11eb-9761-bd94ef6df4bc.png)
Changing SelfNode from CascadingParameter to Parameter can fix it. If this change ok?

**Comment by ElderJames** [comment]
You just remove the at `IsFixed` property.
https://github.com/ant-design-blazor/ant-design-blazor/pull/1161/files#diff-c416ead670d620352d5a2b4e12879d24c34e1e64b14bd92baa33a7c213b3479cR7

**Comment by anddrzejb** [comment]
So this will fix the problem, but maybe in the backlog we should open an issue, where we actually change this from the performance perspective. Passing whole `TreeNode` to each `TreeNodeTitle` will cause constant refresh of all tree node titles whenever `TreeNode` changes. We probably should extract the properties that need to be altered/observed by `TreeNodeTitle` and either send them as separate param attributes or pack them into a separate class and cascade it. Or any other solution that will work :smile:.

**Comment by ElderJames** [comment]
@anddrzejb  You are right.
