### ISSUE TITLE
Unintended console output from SetGutterStyle

### ISSUE THREAD

**Issue by superjerry88** [ant-design-blazor/ant-design-blazor#1154]
The `SetGutterStyle()` in `ListItem.razor.cs` appear to have a `Console.WriteLine(bp);` which causes the output to be flooded when resizing or inializing list components.

**Comment by ElderJames** [comment]
Thanks for contacting us @superjerry88 ,

We will fix it later.

**Comment by anddrzejb** [comment]
@superjerry88 Maybe you could create a PR for this?
