### ISSUE TITLE
Select component display duplicate select item

### ISSUE THREAD

**Issue by yorytang** [ant-design-blazor/ant-design-blazor#1160]
I test the Select component in your website: [https://antblazor.com/zh-CN/components/select](url)

If input a word and select which it was not exist in selectitem,  the word will duplicate display both in selectitem top and bottom.

![image](https://user-images.githubusercontent.com/44489768/108797847-300c8280-75c7-11eb-8910-f7371877de70.png)

![image](https://user-images.githubusercontent.com/44489768/108797851-3438a000-75c7-11eb-88ec-693e83f7b335.png)

**Comment by anddrzejb** [comment]
I had a look on the docs. I cannot recreate that...
![select_Duplicated_seemsOk](https://user-images.githubusercontent.com/6518006/108811793-963cd980-75b6-11eb-876c-cb7d9cfa1da3.gif)
What browser are you using? Can you clear your browser's cache?

**Comment by yorytang** [comment]
hi @anddrzejb , after you typed 'abcde' word , pls select it by mouse click, not Enter key, you will see the duplicate display issue.
