### ISSUE TITLE
tree table style problem

### ISSUE THREAD

**Issue by Seanxwy** [ant-design-blazor/ant-design-blazor#1165]
![image](https://user-images.githubusercontent.com/15828095/108942338-c4dbb280-7691-11eb-978f-97033d8fe2a1.png)
tree table line height is too height

**Comment by anddrzejb** [comment]
I compared and they seem identical with react version:
![image](https://user-images.githubusercontent.com/6518006/108982382-695ff380-7696-11eb-9fdf-acc101bf1ed5.png)
After closed inspection the row in AntBlazor is higher by 2px. 
![image](https://user-images.githubusercontent.com/6518006/108982573-9f04dc80-7696-11eb-9127-53b1b6a17bb9.png)

![image](https://user-images.githubusercontent.com/6518006/108982648-b217ac80-7696-11eb-8542-10de997afaad.png)

Source of this larger height is extra class (in comparison to react ver) in the checkbox label:
![image](https://user-images.githubusercontent.com/6518006/108983764-de7ff880-7697-11eb-8ded-c63917e8d21c.png)

However - @Seanxwy were you complaining about the 2 extra pixels or this is a general size issue for you?

**Comment by Seanxwy** [comment]
@anddrzejb It's not the 2 pixels you said, it's the TD style
![image](https://user-images.githubusercontent.com/15828095/109027995-52ec8300-76fc-11eb-97ae-ffd2d1d96811.png)

**Comment by Seanxwy** [comment]
@anddrzejb It's not the 2 pixels you said, it's the TD style
![image](https://user-images.githubusercontent.com/15828095/109027995-52ec8300-76fc-11eb-97ae-ffd2d1d96811.png)

**Comment by Seanxwy** [comment]
@anddrzejb It's not the 2 pixels you said, it's the TD style
![image](https://user-images.githubusercontent.com/15828095/109027995-52ec8300-76fc-11eb-97ae-ffd2d1d96811.png)
