### ISSUE TITLE
Select ,can the width of the selection box be the same as the widest item?

### ISSUE THREAD

**Issue by pengqian089** [ant-design-blazor/ant-design-blazor#1169]
I am working on the log query function, but the fully name of the logger is very long, and the Select must be set wide enough to display it completely.
can the width of the selection box be the same as the widest item?

### Additional context
![image](https://user-images.githubusercontent.com/13491546/108977839-f1102700-76c3-11eb-885d-219d9a9169d4.png)

**Comment by anddrzejb** [comment]
Maybe this could be done. It seems to me that `Autocomplete` behaves in such a way - it will adjust the dropdown to the widest element:
![image](https://user-images.githubusercontent.com/6518006/109793477-5cef1400-7c1d-11eb-8d0a-1a0b8f73978e.png)

@ElderJames should this be considered for future releases?

**Comment by ElderJames** [comment]
I think we can follow the behavior of antd, also can provide a parameter to support this case.

**Comment by anddrzejb** [comment]
I was looking at the parameters of antd earlier and did not notice `dropdownMatchSelectWidth`... Oh well, my bad...

**Comment by ElderJames** [comment]
Hah, so could we add this feature?

**Comment by anddrzejb** [comment]
I guess I will try to do it since the `Select` component is still fresh in my head.
