### ISSUE TITLE
Modal get hangs when Close

### ISSUE THREAD

**Issue by cephaspad** [ant-design-blazor/ant-design-blazor#1170]
### Describe the bug

I have a list of fruits using AntList and a Remove button each list item. When clicking Remove button the modal shown. If I click OK, item will be removed from list and close modal button.

The problem is that when I click OK, the modal don't close but hang all page.

### Steps to reproduce (please include code)
Project: [AntDesignSample-ModalBugs.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/6037278/AntDesignSample-ModalBugs.zip)

1. Click remove button
![Screenshot 2021-02-24 231832](https://user-images.githubusercontent.com/22416212/109030855-c390a100-76f6-11eb-95c0-3e77eee762df.png)

2. Then click OK
![Screenshot 2021-02-24 231851](https://user-images.githubusercontent.com/22416212/109030885-c9868200-76f6-11eb-8f2b-e48f3efc15af.png)

3. The page hangs and I cannot click anything

### Exceptions (if any)

I see no exception

### Further technical details
- AntDesign: 0.6.0
- Include the output of `dotnet --info`

> .NET SDK (reflecting any global.json):
>  Version:   5.0.103
>  Commit:    72dec52dbd
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.103\
> 
> Host (useful for support):
>   Version: 5.0.3
>   Commit:  c636bbdc8a
> 
> .NET SDKs installed:
>   2.2.207 [C:\Program Files\dotnet\sdk]
>   3.1.404 [C:\Program Files\dotnet\sdk]
>   5.0.103 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE: Visual Studio 2019 16.8.559

**Comment by zxyao145** [comment]
Hi @cephaspad 

The reason for this bug is that when ListItem is rerendered (invoke OnFinished in FruitRemovalModalButton.razor), the pop-up Modal Dialog has not been destroyed, but the mounted DOM has changed, and the destroy event cannot be continued.

**In order to solve this problem**, you can choose to execute OnFinished in the AfterClose callback of Modal, or promote Modal to out of AntList.

The code to use AfterClose is similar to the following (Don't forget to remove OnFinished from OnOk):

``` 
<Modal 
       ...

       AfterClose="async ()=>{
            if (OnFinished.HasDelegate)
            {
                await OnFinished.InvokeAsync();
            }
       }"

       >

       ...

</Modal>
```

**Comment by cephaspad** [comment]
Thanks! I will try it.

**Comment by cephaspad** [comment]
reopen for clarification

**Comment by zxyao145** [comment]
Hi @cephaspad,

This solution doesn't work for you, does it?

**Comment by cephaspad** [comment]
Thank @zxyao145  !!! It works like a charm, now.
I am trying study something from it.

Have a nice day, guy !!!
