### ISSUE TITLE
Tree Component OnContextMenu event not firing

### ISSUE THREAD

**Issue by horizon-sk** [ant-design-blazor/ant-design-blazor#1174]
Using Ant Blazor Tree component and its exposed events, I cannot get right click working on any TreeNode. When doing right click on a treenode, browser (Chrome on Windows) always open up its default context menu and event handler is not fired as well. This is how my Tree component usage looks like in a Razor component -

    <Tree class="bg-light" DataSource="TreeDataSource"
          TitleExpression="x => x.DataItem.Title"
          ChildrenExpression="x => x.DataItem.Children"
          IsLeafExpression="CheckIfLeaf"
          OnNodeLoadDelayAsync="OnNodeLoadDelayAsync"
          OnClick="OnNodeClick"
          OnDblClick="OnNodeDblClick"
          OnContextMenu="(e) => { Console.WriteLine(e.Node.Title); } "
          TItem="ObjectTreeData"
          ShowIcon
          Multiple="false"
          IconExpression="x => x.DataItem.Icon">
    </Tree>

My basic requirement is to be able to show a context menu over TreeNode when user does right click over them. 

Do I have to do something special to get it working?

Thanks

**Comment by iLearnFast** [comment]
@ElderJames Can you please confirm if I am doing something wrong here?  Or you need more info about the issue. Thanks

**Comment by ElderJames** [comment]
Hi @iLearnFast , `ContextMenu` is not yet supported. 

If you need it urgently, you can contribute your implementation code first.

**Comment by lxatrhea** [comment]
@AndrewKaninchen I think it's almost fixed now. The method is called, but a preventDefault is missing. I think that's why the browser's default contextmenu handler still executes. Is there a way to work around this issue, or does this need to be fixed by you?

**Comment by AndrewKaninchen** [comment]
> @AndrewKaninchen I think it's almost fixed now. The method is called, but a preventDefault is missing. I think that's why the browser's default contextmenu handler still executes. Is there a way to work around this issue, or does this need to be fixed by you?

Oh, yeah. I forgot this was a thing because I was already accounting for it in the use case that lead me to come fix this bug. The way I do it is adding @oncontextmenu:preventdefault to the wrapper element I have around the Tree component itself. If that's enough for you, you can do it this way. It's an extra element that may have no other use for you, and it also prevents the native context menu from appearing when clicking the empty areas inside the Tree.

About _really fixing_ it in the component by itself, I think it would require adding an extra parameter to it so we don't _assume_ you want the native one gone. OnContextMenuPreventDefault, something like that. It should be a quick fix. I can probably do it later today.

**Comment by lxatrhea** [comment]
> > @AndrewKaninchen I think it's almost fixed now. The method is called, but a preventDefault is missing. I think that's why the browser's default contextmenu handler still executes. Is there a way to work around this issue, or does this need to be fixed by you?
> 
> Oh, yeah. I forgot this was a thing because I was already accounting for it in the use case that lead me to come fix this bug. The way I do it is by adding @oncontextmenu:preventdefault to the wrapper element I have around the Tree component itself. If that's enough for you, you can do it this way. It's an extra element that may have no other use for you, and it also prevents the native context menu from appearing when clicking the empty areas inside the Tree.
> 
> About _really fixing_ it in the component by itself, I think it would require adding an extra parameter to it so we don't _assume_ you want the native one gone. OnContextMenuPreventDefault, something like that. It should be a quick fix. I can probably do it later today.

I indeed added a wrapper that has preventDefault.
The "real" fix would indeed be better, but for now I'm good.
