### ISSUE TITLE
Select Component Problem (Modal Form)

### ISSUE THREAD

**Issue by shirleen1234** [ant-design-blazor/ant-design-blazor#1176]
### Describe the bug

Form submission is triggered when pressing **enter** key to select item in **Select** component.
(Pre-condition: Only **one** Select form item inside the modal form)

![select](https://user-images.githubusercontent.com/47659614/109255321-b37bdd00-782e-11eb-94a9-c2ee99d2c77f.gif)

### Steps to reproduce (please include code)

```
<Modal @ref="ModalRef"
       Title="@Title"
       Visible="Visible"
       Draggable="true"
       OkText="@OkText"
       OnOk="OkButtonOnClick"
       OnCancel="CancelButtonOnClick">

    <Form @ref="FormRef"
          Model="@SampleData"
          ValidateOnChange="true"
          OnFinish="OnFinish"
          OnFinishFailed="OnFinishFailed"
          LabelColSpan="8"
          WrapperColSpan="16">

        <FormItem Label="Name">
            <Select DataSource="@_persons"
                    @bind-Value="@context.Name"
                    LabelName="@nameof(Person.Name)"
                    ValueName="@nameof(Person.Value)"
                    Placeholder="Select a person"
                    DefaultActiveFirstItem="false"
                    EnableSearch>
            </Select>
        </FormItem>
    </Form>
</Modal>

private void OkButtonOnClick(MouseEventArgs e)
{
	FormRef.Submit();
}
```

### Further technical details
- AntDesign Nuget Package 0.6.0

**Comment by anddrzejb** [comment]
@ElderJames So a design question - what about double enter? I mean first enter to accept the value and second enter to submit the form? Or a more general rule - if overlay is visible, then enter does not submit. If overlay is not visible, then submit. Or we could go even further - expose an attribute that would either allow to submit on enter when overlay is not visible or completely disable submit on enter.
At this stage I think I have this fixed to the point when enter does not submit (at all).
