### ISSUE TITLE
DropDown : Close() need 2 click to open

### ISSUE THREAD

**Issue by gloisance** [ant-design-blazor/ant-design-blazor#1177]
Hello,

If i call Close() of Dropdown with TriggerClick, i need to click twice on ChildContent to open Overlay.
If i user SetVisible(false) to replace Close(), i need to click once to open.

thank you.

**Comment by ElderJames** [comment]
Hi @gloisance ,could you please show your code here?

**Comment by gloisance** [comment]
Hello,

I don't have the code anymore because I worked around the problem using SetVisible.

So I have to replace the "Visible" management by the "Open/Close" management.

The DropDown :
                <Dropdown Trigger="new TriggerType[] { TriggerType.Click }" @ref="@GridSettingsDropdown" Class="icdg-settings-dropdown" HiddenMode="true"
                          PopupContainerSelector="@($"#grid-settings-{Name}")" Placement="@PlacementType.BottomRight">
                    <Overlay>
                        <DxFormLayout CssClass="icdg-settings-form">
                            <DxFormLayoutItem CssClass="ic-bold ic-border-bottom" ColSpanSm="10">
                                <Template>
                                    @Translator.GetTranslation("GRID_SETTINGS")
                                </Template>
                            </DxFormLayoutItem>
                            <DxFormLayoutItem CssClass="ic-bold ic-border-bottom ic-ta-end" ColSpanSm="2">
                                <Template>
                                    <div class="icone ic-icon-close ic-size-20-20" style="cursor:pointer; text-align:end;" @onclick="@(() => GridSettingsDropdown.SetVisible(false))"></div>
                                </Template>
                            </DxFormLayoutItem>
                            <DxFormLayoutItem ColSpanSm="12" CssClass="ic-padding-top-6">
                                <Template>
                                    <DxCheckBox @bind-Checked="@ListManager.ShowFilterRow">@Translator.GetTranslation("GRID_SHOW_FILTER_ROW")</DxCheckBox>
                                </Template>
                            </DxFormLayoutItem>
                            <DxFormLayoutItem ColSpanSm="12" CssClass="ic-padding-top-6">
                                <Template>
                                    <DxCheckBox @bind-Checked="@ListManager.ShowGroupPanel">@Translator.GetTranslation("GRID_SHOW_GROUP_PANEL")</DxCheckBox>
                                </Template>
                            </DxFormLayoutItem>
                            @*<DxFormLayoutItem ColSpanSm="12" CssClass="ic-padding-top-6">
                            <Template>
                                <DxCheckBox @bind-Checked="@ListManager.ColumnsFillWidth">@Translator.GetTranslation("GRID_COLUMN_FILL_WITH")</DxCheckBox>
                            </Template>
                        </DxFormLayoutItem>*@
                            <DxFormLayoutItem ColSpanSm="12" CssClass="ic-padding-top-6">
                                <Template>
                                    <DxCheckBox @bind-Checked="@ListManager.DataAutoRefresh">@Translator.GetTranslation("GRID_DATA_AUTO_REFRESH")</DxCheckBox>
                                </Template>
                            </DxFormLayoutItem>
                        </DxFormLayout>
                    </Overlay>
                    <ChildContent>
                        <div id="@($"grid-settings-{Name}")" class="icdg-settings-dropdown">
                            <IcDataGridToolBarAction Action="-2" IconCssClass="ic-icon-settings" Alignment="ToolbarItemAlignment.Right" />
                        </div>
                    </ChildContent>
                </Dropdown>

IcDataGridToolBarAction calls the function below on the click :
                GridSettingsDropdown.SetVisible(!GridSettingsDropdown.Visible);

Have a nice day.

**Comment by ElderJames** [comment]
Hello @gloisance , this issue have been fixed in lastest version. Please try.
