### ISSUE TITLE
How to fill dynamic infos into table without knowing the exact class name

### ISSUE THREAD

**Issue by HSHUNION** [ant-design-blazor/ant-design-blazor#1182]
I have data such as List<dictionary<string,object>> like. And I know the table titles with type of string[], then how to fill them into table? I've tried datasorce but failed. Thanks very much.

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by HSHUNION** [comment]
Add:

For example, I query data from Oracle by dynamic sql (columns not sure), and how i fill them into table of AntDesign. Thanks for any reply.

**Comment by Zonciu** [comment]
Dynamic table is not fully supported yet.

Temporary solution:
```
<Table TItem="Dictionary<string, object>" DataSource="Data">
    <Column Title="Name" TData="object" DataIndex="@("[\"Name\"]")"></Column>
    <Column Title="Age" TData="object" DataIndex="@("[\"Age\"]")"></Column>
</Table>

@code {
    public List<Dictionary<string, object>> Data = new()
    {
        new() {{"Name", "A1"}, {"Age", 55}},
        new() {{"Name", "A2"}, {"Age", 14}},
        new() {{"Name", "A3"}, {"Age", 4}},
    };
}
```
