### ISSUE TITLE
Table component need support service-side sorting.

### ISSUE THREAD

**Issue by scugzbc** [ant-design-blazor/ant-design-blazor#1185]
The current table component only supports client-side sorting, which is not very useful. In fact, the server-side sorting is used more. Based on the existing component, I encapsulate the pagesearchparams class, which is used for the unified transmission of query, filtering, sorting and page turning functions at the front and back ends, and can automatically convert to the corresponding LINQ expression at the same time

But in the practical application, we found that table can only use client sorting, and there is no way to bind the sorting condition to the column name

I don't know if I haven't learned, or if the component doesn't support it. Will there be a plan for this support in the future?

**Comment by ElderJames** [comment]
Thanks for contacting us @scugzbc 

You can use `OnChange` method event to get sort direction and filtered values

**Comment by ElderJames** [comment]
You can fetch data in `OnChange`, and set the new DataSource into Table.
