### ISSUE TITLE
Opacity effect is not working on modals

### ISSUE THREAD

**Issue by eversonabreu** [ant-design-blazor/ant-design-blazor#1192]
Opacity effect is not working on modals. Getting only the background dark but without rendering the contents of the modal. I tried your own website. In my application to resolve, I had to put in index.html the css statement below, however this way the transition animation was lost. I'm using version: 0.7.0-nightly-2102281452 with .NET 5 (5.0.103). I tested in several browsers, and in all occurred this problem.

![modal_error](https://user-images.githubusercontent.com/26327053/109645565-cb58a700-7b35-11eb-9bb1-c5e6e0e95210.png)

![modal_error2](https://user-images.githubusercontent.com/26327053/109645883-37d3a600-7b36-11eb-9c0f-09a1e5012fe8.png)

**Comment by ElderJames** [comment]
Hi @eversonabreu , please try 0.7.0.

**Comment by ElderJames** [comment]
Hi @eversonabreu ,is it work now?

**Comment by eversonabreu** [comment]
Hello @ElderJames, i upgraded to 0.7.0 and it returned to work correctly. Thanks

**Comment by ElderJames** [comment]
That's fine!
