### ISSUE TITLE
Get table QueryModel when parameters(PageSize, PageIndex, Sort, Filter) not changed

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1201]
Currently we can get `QueryModel<T>` from table OnChange event. However, is there any method to get `QueryModel` when nothing changed? For example, we want to just refresh the table to get the latest data from the server.

**Comment by ElderJames** [comment]
That's a good suggestion @anranruye , we'll add this feature soon.
