### ISSUE TITLE
Suggestions for parameter templates of Modal  components and Drawer components

### ISSUE THREAD

**Issue by dawningzhang** [ant-design-blazor/ant-design-blazor#1212]
使用ModalService.CreateModalAsync()、ModalService.CreateConfirmAsync()、DrawerService.CreateAsync等方法打开自定义组件时，为了传递参数，自定义组件需要分别inherits的ConfirmTemplate、ModalTemplate、DrawerTemplate等模板，不利于自定义组件的共享使用，建议涉及统一的Template以传递参数，使组件的使用更加便利

**Comment by zxyao145** [comment]
@dawningzhang 这个重构设计的东西比较多，最近又比较忙，PR可能要等到下周，忘见谅。

**Comment by zxyao145** [comment]
The PR has been merged to the branch "ant-design-blazor:feature", and so closing this down.
