### ISSUE TITLE
 install on existing .net 5 webassembly (Asp core hosed) project

### ISSUE THREAD

**Issue by mrjohnr** [ant-design-blazor/ant-design-blazor#1221]
Hi
I've followed the install instructions for and existing .net 5 webassembly  (Asp core hosed) project 
I've installed ant-design on client project, but seems there is no **_content/AntDesign/js/ant-design-blazor.js** and **_content/AntDesign/css/ant-design-blazor.css**  to add them on index.html

what have I done wrong?
thanks

**Comment by anddrzejb** [comment]
That is very little to go off. Can you provide a minimal repro?

**Comment by mrjohnr** [comment]
Hi,
It was my mistake: I thought <AntContainer /> is optionally
thanks for your quick reply

**Comment by h1nson** [comment]
how do you solve it? i am facing the same problem.

**Comment by ElderJames** [comment]
Hi @h1nson , could you tell me what you did? And please create another issue.

**Comment by mrjohnr** [comment]
> how do you solve it? i am facing the same problem.

you need to add  <AntContainer /> in App.razor   see    [Installation Guide](https://antblazor.com/en-US/docs/introduce)
