### ISSUE TITLE
the modal dialog is under the mask

### ISSUE THREAD

**Issue by scugzbc** [ant-design-blazor/ant-design-blazor#1225]
when i update the nuget  package, i find the bug.
then i try it in the example of doc site.
https://ant-design-blazor.gitee.io/zh-CN/components/modal

click the "Open Modal" button,  you will got it .

**Comment by ElderJames** [comment]
Thanks for contacting us @scugzbc , but it works well on my machine.

**Comment by scugzbc** [comment]
确实有问题.我再截个图给你,你的可能是因为本地css的缓存导致的,因为旧版本是可以的,新版本是有问题的.
我已经找出了问题.

**Comment by scugzbc** [comment]
....就是三分钟前是不行的,现在版本号也变了.应该是在新版本里修复了,
之前是个nightly的版本.现在是 0.7.1了.

**Comment by scugzbc** [comment]
之前有问题的版本是 : 0.7.0-nightly-2102281452

**Comment by ElderJames** [comment]
0.7.0就修复了。

**Comment by ElderJames** [comment]
这个issue先关闭，如果有其他问题，请再创建issue。或者在钉钉群里问一下。
