### ISSUE TITLE
Add Refresh function to Table component with state retention.

### ISSUE THREAD

**Issue by JosefRousal** [ant-design-blazor/ant-design-blazor#1234]
A nice feature for data sourced components is the ability to refresh the data while maintaining the display state of the component. For example, given a nested table with expanded rows a refresh would supply the table with new data but also either keep the expanded rows as they are or re-expand rows after data reload based on some key value.

**Comment by MutatePat** [comment]
Does adding the new rows to datasource directly collapse expanded children?

**Comment by JosefRousal** [comment]
> Does adding the new rows to datasource directly collapse expanded children?

@MutatePat Currently I am setting the data source value each time I get new data from the data store and calling a StateHasChanged to get the new values to show in the table. This is probably what is causing a re-render of the table with collapsed child rows.

**Comment by ElderJames** [comment]
Thanks for contacting us @JosefRousal 
Unfortunately, I don't know how to implement this feature for now. Can you provide some ideas on how to implement it?

**Comment by JosefRousal** [comment]
You could store the current filter/paging state of the table, refresh the data, and the reapply the filter state over the new data.

**Comment by ElderJames** [comment]
We have `QueryModel` to store the state, but it can not be reapply for now.

**Comment by ElderJames** [comment]
This feature have been implemented in current version. Thanks all very much.
