### ISSUE TITLE
Table Filter Pagination

### ISSUE THREAD

**Issue by BadarAljahwari** [ant-design-blazor/ant-design-blazor#1244]
Thank you for the wonderful table filter feature

### Idea:
If the table has more than on page (ex. 3 pages). After filtering, even though the filter result can be displayed in one page the origin number of page in pagination will be showing (3 pages)

If the filter result bind with pages number will be great.

Thanks

**Comment by BadarAljahwari** [comment]
Also if there is a way to get the number of items in filter result it will be good so we can place it anywhere

**Comment by ElderJames** [comment]
You can get the number of filter result by binding the Total parameter.

**Comment by BadarAljahwari** [comment]
> You can get the number of filter result by binding the Total parameter.

Thanks
