### ISSUE TITLE
MenuItem popup not  fluently in ”MenuMode.Vertical“ mode when i update to 0.7.1， in  0.6.0 it works fine

### ISSUE THREAD

**Issue by itmaybetrue** [ant-design-blazor/ant-design-blazor#1246]
My blazor project type is  serverside，i tested this bug with docs sample code just like below:
-----------------

> <Menu OnMenuItemClicked=handleClick Style=" width: 256px" Mode=MenuMode.Vertical>
    <SubMenu Key="sub1" TitleTemplate=@sub1Title>
        <MenuItemGroup Title="Item 1">
            <MenuItem Key="1">Option 1</MenuItem>
            <MenuItem Key="2">Option 2</MenuItem>
        </MenuItemGroup>
        <MenuItemGroup Title="Item 2">
            <MenuItem Key="3">Option 3</MenuItem>
            <MenuItem Key="4">Option 4</MenuItem>
        </MenuItemGroup>
    </SubMenu>
    <SubMenu Key="sub2" TitleTemplate=@sub2Title>
        <MenuItem Key="5">Option 5</MenuItem>
        <MenuItem Key="6">Option 6</MenuItem>
        <SubMenu Key="sub3" Title="Submenu">
            <MenuItem Key="7">Option 7</MenuItem>
            <MenuItem Key="8">Option 8</MenuItem>
        </SubMenu>
    </SubMenu>
    <SubMenu Key="sub4" TitleTemplate=@sub4Title>
        <MenuItem Key="9">Option 9</MenuItem>
        <MenuItem Key="10">Option 10</MenuItem>
        <MenuItem Key="11">Option 11</MenuItem>
        <MenuItem Key="12">Option 12</MenuItem>
    </SubMenu>
</Menu>
@code {

    RenderFragment sub1Title =
    @<span>
        <Icon Type="mail" Theme="outline"></Icon>
        <span>Navigation One</span>
    </span>;

    RenderFragment sub2Title =
    @<span>
        <Icon Type="appstore" Theme="outline"></Icon>
        <span>Navigation Two</span>
    </span>;

    RenderFragment sub4Title =
    @<span>
        <Icon Type="setting" Theme="outline"></Icon>
        <span>Navigation Three</span>
    </span>;

        void handleClick()
        {

        }
    }

**Comment by ElderJames** [comment]
Thanksfor contacting us @itmaybetrue ,
Are you talking about the animation? It would be fixed in 0.7.2

**Comment by itmaybetrue** [comment]
> Thanks for contacting us @itmaybetrue ,
> Are you talking about the animation? It would be fixed in 0.7.2

yes，It’s great!
I'm looking forward to the v0.7.2

**Comment by ElderJames** [comment]
Hi @itmaybetrue , does the latest version work well?

**Comment by itmaybetrue** [comment]
this issue has not been fixed so far,
the docs site still has this bug which what i said
https://ant-design-blazor.gitee.io/en-US/components/menu#components-menu-demo-vertical
