### ISSUE TITLE
ConfirmModal Flickering ServerSide

### ISSUE THREAD

**Issue by rafalpankiewiczgr8soft** [ant-design-blazor/ant-design-blazor#1256]
### Describe the bug

![Bug](https://user-images.githubusercontent.com/80751714/111296507-dc80d800-864c-11eb-9e8a-96043fa47db7.gif)

### Steps to reproduce (please include code)
Often (but not always) when you click button, ConfirmModal (ModalService.ConfirmAsync) starts flashing. Flickering occurs when any button animation is in progress (onkeyup and loading) 

![image](https://user-images.githubusercontent.com/80751714/111299451-3cc54900-8650-11eb-9338-fcd507c12b3e.png)

### Further technical details
- AntDesign 0.6.0
- Include .NET SDK Version 5.0.201 ServerSide
- The IDE (VS) Version 16.9.1

**Comment by zxyao145** [comment]
@rafalpankiewiczgr8soft Thanks a lot!
This problem may be due to the fact that Blazor's events is not "pure event handlers", and I will fix it as soon as possible (it should be this weekend).

And if possible, could you show me the general implementation of RemoveEvent?

**Comment by zxyao145** [comment]
@rafalpankiewiczgr8soft 
Hi, is this a problem after deployment or during debugging? I have debugged the program, the flashing will appear under the default open Chrome of VS if Chrome's dev tools are not open. And if I opend it in the Chrome which intalled by myself, it works.

**Comment by rafalpankiewiczgr8soft** [comment]
@zxyao145 
Hi, I used  for  the tests. This:
`   private async Task RemoveEvent(int eventId)
        {
            await Task.Delay(3000);          
        }`
The default is to call service that delete entity and reload list. This happens regardless of the implementation.
Unfortunately, after deployment, the problem also appears.

**Comment by zxyao145** [comment]
@rafalpankiewiczgr8soft 
Ok, thank you! I'll continue testing again

**Comment by zxyao145** [comment]
@rafalpankiewiczgr8soft 
Hi, could you provide the browser version? And how about try upgrading to the latest browser and AntDesign 0.7.2?

**Comment by rafalpankiewiczgr8soft** [comment]
@zxyao145 
I updated to AntDesign version 0.7.2 and the problem still exists. I have Chrome version 89.0.4389.90.

**Comment by ElderJames** [comment]
Fixed in https://github.com/ant-design-blazor/ant-design-blazor/pull/2561
