### ISSUE TITLE
Feature Request: Display Atrribute for Column in Table

### ISSUE THREAD

**Issue by Garfieldgzhh** [ant-design-blazor/ant-design-blazor#1278]
### Is your feature request related to a problem? Please describe.

I am trying to create a Table and use the "Display" attribute for the name of the columns, but after setting [Display(Name="ColumnName")], the column uses the name of variable as its display name

### Describe the solution you'd like

When I write:
[Display(Name="SomeName")]
public Column column1;

The first row of this column should show "SomeName" instead of column1

### Additional context

I use Ant-Design-Blazor for internal data systems. It would be convenient if I can set the name columns to a string that might contain Chinese characters for localization.

**Comment by anranruye** [comment]
+1
It seems that [DisplayName] attribute is being using for this case(I found this from source code yesterday). But [Display] attribute should also be supported.
