### ISSUE TITLE
Suggestion: FormItem label template

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#1287]
It would be good to have the label template renderfragment so i can customize. e.g. would like to put a prefix star for required field, 'for' attribute etc.

**Comment by ElderJames** [comment]
Thanks for suggestion @ldsenow .  This is pretty good and you can create a PR for it.

**Comment by ldsenow** [comment]
@ElderJames Happy to do a PR

**Comment by ElderJames** [comment]
That's fine, thank you!

**Comment by ldsenow** [comment]
PR has been created, please review and feedback. Thanks
