### ISSUE TITLE
Table - Paging not working with ScrollX set

### ISSUE THREAD

**Issue by mkalinski93** [ant-design-blazor/ant-design-blazor#1288]
### Describe the bug

If ScrollX is activated and the screen width is changed (even though it appears on initial loading, too), the paging does not work.
I have set up a video which was recorded from the component section.

https://user-images.githubusercontent.com/64005967/113122592-138de680-9214-11eb-9ab1-6669933ff3e4.mp4

This bug is hardly to explain as I don´t know what the reason is causing this issue.

### Steps to reproduce (please include code)

- Create a Table
- Set at least 15 different columns
- Create a datasource with 15 properties and minimum 100 items
- Set the ScreenX property incrementally to 600, 800, 1200 (multiple tests)
- Don´t use the 'Width' property of a column (Not necessary)
- Change the pager's current page and shrink & grow browser window and try different desktops.
- If somehow reproduced, the pager will act normally but changing the current page will not make the table display its related data.

### Further technical details
- AntDesign 0.7.3

**Comment by ElderJames** [comment]
Thanks for contacting us @mkalinski93 , this is a real bug, we will fix it soon.
