### ISSUE TITLE
The fixed value of the form is invalid

### ISSUE THREAD

**Issue by unsung189** [ant-design-blazor/ant-design-blazor#1289]
**Describe the bug**

The fixed value of the form is invalid
Col.razor .cs SetHostFlexStyle, but Col.razor didn't use it.
In addition_hostFlexStyle calculated, return $0 s 0 s Flex" should be changed to return $0 s 0 s Flex.value

**Steps to reproduce (please include code)**

```
  private void SetHostFlexStyle()
        {
            if (this.Flex.Value == null)
                return;

            this._hostFlexStyle = this.Flex.Match(str =>
                {
                    if (Regex.Match(str, "^\\d+(\\.\\d+)?(px|em|rem|%)$").Success)
                    {
                        return $"0 0 {Flex}";
                    }

                    return Flex.AsT0;
                },
                num => $"{Flex} {Flex} auto");
        }

<div class="@ClassMapper.Class" style="@GutterStyle @Style" id="@Id" @ref="Ref">
 @ChildContent
</div>
```

**Exceptions (if any)**

**Further technical details**
AntDesign 0.7.3

**Comment by ElderJames** [comment]
Thanks for contacting us @unsung189 .
I have working on the flex style of Col. But what are you meaning the `fixed value of form`?

**Comment by unsung189** [comment]
@ElderJames 
This qr can solve my problem. Originally intended to do their own solution, please ask if there is an official communication group, published QR code failed. I'd love to join you and make a contribution to Ant Blazor.

**Comment by ElderJames** [comment]
Sure, you can join our discord or dingtalk.
