### ISSUE TITLE
I want to make an advanced query form that supports lable left alignment

### ISSUE THREAD

**Issue by unsung189** [ant-design-blazor/ant-design-blazor#1291]
### Is your feature request related to a problem? Please describe.
I want to make an advanced query form that supports lable left alignment

### Describe the solution you'd like
You can do this by adding a LableAlignType to the LabelCol property of the form
### Additional context
![image](https://user-images.githubusercontent.com/52531536/113227807-1ea14f00-92c6-11eb-9338-9286195ced19.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @unsung189 

We would be very happy if you could create a PR to add the 'LabelAlign' property to the form component.
