### ISSUE TITLE
await ModalService.CreateModalAsync doesn't wait for modal to be closed

### ISSUE THREAD

**Issue by mrjohnr** [ant-design-blazor/ant-design-blazor#1299]
Hi
next code doesn't wait for modal to be closed, Console.WriteLine is executed as the modal is shown
  ```
 modalRef = await ModalService.CreateModalAsync<MyComponent, DlgResult>(modalConfig, templateOptions);
    Console.WriteLine("after");
```
tried ModalService.CreateConfirmAsync but the same
is there any alternative?
thanks

**Comment by zxyao145** [comment]
Hi @mrjohnr ,

`ModalService.CreateModalAsync` is not meant to await for closure. If you want to await dialog's closure and judge that the OK or Cancel button has been clicked when closing, please try using `confirmService.Show` or `modalService.ConfirmAsync`.

`confirmService.Show` to show a simple Confirm dialog like MessageBox of Windows, it's different from ModalService. ModalService can only create OK-Cancel Confirm dialog and return ConfirmRef or a bool value, which to indicate whether the OK button has been clicked, but `confirmService.Show` return **ConfirmResult** , which is a enum type, and like ConfirmResult in WinForm.

**Comment by mrjohnr** [comment]
Hi
confirmService.Show or modalService.ConfirmAsync doens't support a component inside
tried ModalService.CreateConfirmAsync but as above not waiting

I need to create waiting modals that reads different values from the user(one for reading a numeric,one for a datetime,etc)

thanks

**Comment by zxyao145** [comment]
Hi,
I think it's more suitable to use Modal dialog, and you can do it in the callback function. In current version, you can use the values in `modalConfig.AfterClose`, just like the [demo](https://antblazor.com/en-US/components/modal#components-modal-demo-modal_service_for_modal): 

```
var templateOptions = new Model();
...
modalConfig.AfterClose = () =>
        {
            value = templateOptions.Username;
            InvokeAsync(StateHasChanged);
            return Task.CompletedTask;
        };

_modalRef = await ModalService
            .CreateModalAsync<ModalTemplateDemo, Form.demo.Basic.Model>
            (modalConfig, templateOptions);
```

And in the future (it has been in the feature branch), you can also use the values in the `modalConfig.OnOk` or `modalConfig.OnCancel` callback function, just like here:
```
var modalRef = await ModalService.CreateModalAsync<ConfirmTemplateDemo, string, string>(modalConfig, value);
// the type of result is TResult in CreateModalAsync, in this case is string.
modalRef.OnOk = (result) =>
        {
            Console.WriteLine($"OnOk:{result}");
            return Task.CompletedTask;
        };

modalRef.OnCancel = (result) =>
        {
            Console.WriteLine($"OnCancel:{result}");
            return Task.CompletedTask;
        };
```

**Comment by mrjohnr** [comment]
from your answer I understand that in future that will be possible(to get result after modal closes)?
in what future version?
thanks

**Comment by zxyao145** [comment]
Hi, @mrjohnr 
I'm sorry for my poor English, it's possible to get result after modal closes using await, but there is no such consideration for the time being. 

In my last reply, I said in the future that you can get results in OnOk's callback or OnCancel's callback function, it may appear in version 0.8 or version 0.7.4.

Now you can use the callback function of AfterClose. I'm Sorry for the bad development experience.

**Comment by mrjohnr** [comment]
Thanks for your answer

**Comment by mrjohnr** [comment]
Hi,version 0.8 is out.is that feature available?
thanks

**Comment by zxyao145** [comment]
Sorry you cannot await ModalService.CreateModalAsync, and you can using as follow:

```c#
var modalRef = await ModalService.CreateModalAsync<ConfirmTemplateDemo, string, string>(modalConfig, value);
// the type of result is TResult in CreateModalAsync, in this case is string.
modalRef.OnOk = (result) =>
        {
            Console.WriteLine($"OnOk:{result}");
            return Task.CompletedTask;
        };

modalRef.OnCancel = (result) =>
        {
            Console.WriteLine($"OnCancel:{result}");
            return Task.CompletedTask;
        };
```

**Comment by mrjohnr** [comment]
Hi.indeed,it doesn't await for result, it is not the expected behavior  :(
It is possible for me to create a separate service to await result?

how to trigger  modalRef.OnOk on custom template/button?

thanks

**Comment by zxyao145** [comment]
Yes, you can create a custom proxy for ModalService as follow:

**1. define a proxy service for ModalService** 
```c#
public class ModalServiceWrapper
{
	private readonly ModalService _modalService;

	public ModalServiceWrapper(ModalService modalService)
	{
		_modalService = modalService;
	}

	public Task CreateModalAsync<TComponent, TComponentOptions>(ModalOptions config,
		TComponentOptions componentOptions) where TComponent : FeedbackComponent<TComponentOptions>
	{
		var tsc = new TaskCompletionSource();
		config.AfterClose = () =>
		{
			tsc.SetResult();
			return Task.CompletedTask;
		};

		_ = _modalService.CreateModalAsync<TComponent, TComponentOptions>(config, componentOptions);
		return tsc.Task;
	}
}
```

**2. Injection service ModalServiceWrapper**
```c#
services.TryAddScoped<ModalServiceWrapper>();
```

**3. Replacing the ModalService with the ModalServiceWrapper**
```c#
@using OneOf;
@inject ModalServiceWrapper ModalService

<AntDesign.Button OnClick="ShowModal">Show parent</AntDesign.Button>

@code {
    async Task ShowModal()
    {
        var modalConfig = new ModalOptions();
        modalConfig.Title = "Basic Form";

        await ModalService.CreateModalAsync<MyComponent, MyOptions>(modalConfig,new MyOptions());
        Console.WriteLine("AfterHide");
    }
}
```


aside:
**MyComponent.razor**
```c#
@inherits FeedbackComponent<MyOptions>

<h3>MyComponent</h3>
```

**MyOptions**
```c#
public class MyOptions
{
}
```
