### ISSUE TITLE
通过代码修改Result组件图标颜色失败(Failed to modify the color of the Result component icon through code)

### ISSUE THREAD

**Issue by JiaChengLuo** [ant-design-blazor/ant-design-blazor#1328]
### Describe the bug

通过代码修改Result组件自定义的图标颜色失败
Failed to modify the custom icon color of the Result component through code

### Steps to reproduce (please include code)
`<Result Icon="smile-outline" Title="This is a title" Status="@status">`
    `<Extra>`
        `<Button OnClick="@(() => status = "error")">Change Status</Button>`
    `</Extra>`
`</Result>`

`@code{
    string status = "info";
}`

### Further technical details
- AntDesign Nuget Package version 0.7.4
- .NET 5.0.102
- VS2019 16.8.4

**Comment by ElderJames** [comment]
Thanks for contacting us @JiaChengLuo 
This is a little bug, would you be interested in helping us repair it?

**Comment by JiaChengLuo** [comment]
@ElderJames I will try to solve it😂

**Comment by ElderJames** [comment]
You just need to add `StateHasChanged` in `Status` setter.

**Comment by JiaChengLuo** [comment]
😥 I encountered some problems when compiling the project, so I couldn’t test it.

**Comment by ElderJames** [comment]
Please install the node.js first

**Comment by JiaChengLuo** [comment]
The problem is solved, I will test it.😁

**Comment by JiaChengLuo** [comment]
I try to add `StateHasChanged` in `Status` setter, but it didn't work.
I found that every time the property value is changed, the `SetClass()` method is called, and `{PrefixCls}-{Status}` is added to the `ClassMapper`, but the page seems to only use the css class added when constructing the component .
So I called `ClassMapper.Clear()` in the `SetClass()` method, and it worked.
The modified `SetClass()` method code is as follows
```
private void SetClass()
        {
            ClassMapper.Clear();
            ClassMapper.Add(PrefixCls)
                .Add($"{PrefixCls}-{Status}");

            IconClassMapper.Clear();
            IconClassMapper.Add($"{PrefixCls}-icon")
                .If($"{PrefixCls}-image", () => IsImage);
        }
```

**Comment by ElderJames** [comment]
please use `Get(()=>$"{PrefixCls}-{Status}")` , and it will update every time.

**Comment by JiaChengLuo** [comment]
I tried `Get(()=>$"{PrefixCls}-{Status}")` but got this exception `System.ArgumentException:“An item with the same key has already been added. Key: System.Func`1[System.String]”`.
Is there any error in my code?
```
ClassMapper.Add(PrefixCls).Get(() => $"{PrefixCls}-{Status}");
```
or
```
ClassMapper.Get(() => $"{PrefixCls}-{Status}");
```
Do I need to call `ClassMapper.Clear()` first?

**Comment by ElderJames** [comment]
don't setup more than one time
