### ISSUE TITLE
RangePicker: unable to clear start date or end date when they have been entered

### ISSUE THREAD

**Issue by vaderr12** [ant-design-blazor/ant-design-blazor#1329]
Hello,
On examples page with range picker:
[https://ant-design-blazor.github.io/en-US/components/datepicker](https://ant-design-blazor.github.io/en-US/components/datepicker)

when I click and select start date (or end date), I cannot clear those values.

**Comment by vaderr12** [comment]
hello, can somebody confirm the issue?

**Comment by ElderJames** [comment]
I'm not sure what you are meaning..

![ant-datepicker](https://user-images.githubusercontent.com/7550366/114377435-3d9ebb80-9bb9-11eb-9071-1d8be555afa5.gif)

**Comment by anddrzejb** [comment]
And my gif that also clears with keyboard.
![dateRange_clear](https://user-images.githubusercontent.com/6518006/114379081-0d432700-9b91-11eb-815d-bd102ee2e4c2.gif)

**Comment by vaderr12** [comment]
Ok, now I understand. In my browser, page looks like this:
![image](https://user-images.githubusercontent.com/783766/114383157-83458f00-9b8d-11eb-8523-c103279414b1.png)
The calendar or cancel icons doesn't shows up.
I'm browsing with :
![image](https://user-images.githubusercontent.com/783766/114383335-b8ea7800-9b8d-11eb-9ec9-bcaa383b50da.png)

**Comment by anddrzejb** [comment]
Same as mine. I would start by clearing cache. If that won't work, start turning off your extensions. Also, have a look at how `datepicker` is rendered on a different browser.

**Comment by ElderJames** [comment]
Icons are missing?

**Comment by vaderr12** [comment]
yea, no icons. **Clearing cache fixed the problem**. I wonder if this glitch could happen on client machines when I update my application :-(.  I don't want to force them to clear the cache.
