### ISSUE TITLE
Where is this ConfirmTemplateDemo Component code?

### ISSUE THREAD

**Issue by shashikantx** [ant-design-blazor/ant-design-blazor#1337]
I tried looking for ConfirmTemplateDemo code, but am not able to find it anywhere. I was trying to create a modal from a component. Any help will be appreciated, thank you.

**Comment by anddrzejb** [comment]
Yeah, when I started I had a problem with that as well. [Here it is](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/site/AntDesign.Docs/Demos/Components/Modal/ConfirmTemplateDemo.razor). We should probably think how this can be included in the docs.

**Comment by shashikantx** [comment]
Thanks a lot, 
@anddrzejb Maybe you can just leave a link there for now, until the thing is figured out.

**Comment by anddrzejb** [comment]
That is up to @ElderJames . I will close this issue, since it is solved.
