### ISSUE TITLE
Input with clear - clicking on "Clear" makes the control to lose the focus

### ISSUE THREAD

**Issue by MihailsKuzmins** [ant-design-blazor/ant-design-blazor#1343]
Hello guys.
Thanks for the awesome Blazor components' library.
Would it be possible to take a look at the issue with the focus of Input after pressing the clear button?

### Describe the bug
When an <Input TValue="String" /> control has a property `AllowCleat="true"` then pressing the clear button makes the input control to lose the focus. Therefore, in order to continue the input the control must be clicked one more time.
It would be nice if clicking on the close button preserved the focus in the input component.

### Steps to reproduce (please include code)
https://antblazor.com/en-US/components/input#components-input-demo-Clear
1) Input some text into the input control with the clear button
2) press the clear button
3) try typing something

the control has lost the focus and typing goes nowhere.
```xml
<Input
    TValue="String"
    AllowClear="true" />
```

### Further technical details
- AntDesign Nuget Package version: 0.7.4
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual studio

```bash
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.1.21103.13
 Commit:    b8a03527b2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\

Host (useful for support):
  Version: 6.0.0-preview.1.21102.12
  Commit:  9b2776d481

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.1.21102.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.1.21103.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by MihailsKuzmins** [comment]
Thanks for the bugfix. `<Input>` works as expected in 0.8.0
However, there was not a `<PasswordInput>` in your list. And in 0.8.0 pressing the 👁️ icon makes the `<PasswordInput>` lose the focus and the caret position.

Could you please look at this problem as well in terms of this issue? Or should I create a new one?

**Comment by ElderJames** [comment]
cc @anddrzejb

**Comment by anddrzejb** [comment]
@MihailsKuzmins I am currently in the middle of something and I wont be able to fix it for the next couple of days. But I think I know where is the problem. Would you be willing to try it by yourself, with a little bit of guidance?

**Comment by MihailsKuzmins** [comment]
> @MihailsKuzmins I am currently in the middle of something and I wont be able to fix it for the next couple of days. But I think I know where is the problem. Would you be willing to try it by yourself, with a little bit of guidance?

@anddrzejb, thank you for the opportunity. I think I could try to fix the problem. I assume it must be something similar to #1342, but please provide some details so that I feel a bit more comfortable 😄

**Comment by anddrzejb** [comment]
Well, for starters you will need to add these lines
```csharp
     IsFocused = true; 
     await this.FocusAsync(Ref);
```
to `InputPasswor.ToggleVisibility(MouseEventArgs args)` method.
Now, I am not sure how cursor is going to behave here. It may appear at the first character. If that is going to happen, then more involved change will be required.

**Comment by MihailsKuzmins** [comment]
@anddrzejb, thanks for the input. It was exactly as I thought. I have prepared a PR #1377.
Due to the fact that `InputPasswor.ToggleVisibility(MouseEventArgs args)` is called in `OnInitialized()` I don't think that writing the focus logic in `OnInitialized()` is a good idea (will interfere with `AutoFocus`).
Therefore, I extended the method "onClick" as it is implemented in *Input.cs* and I think it is a good way to handle it.

**Comment by anddrzejb** [comment]
@MihailsKuzmins sorry, I was preoccupied. But I see you have made the changes! Thanks a lot! I hope to see you contributing more often 🎆

**Comment by MihailsKuzmins** [comment]
> @MihailsKuzmins sorry, I was preoccupied. But I see you have made the changes! Thanks a lot! I hope to see you contributing more often 🎆

@anddrzejb, no problems 😄. It was fun contributing to such a widely used and rapidly growing project. So thank you for this opportunity.
