### ISSUE TITLE
Table: Column Chooser

### ISSUE THREAD

**Issue by mehmetuken** [ant-design-blazor/ant-design-blazor#1346]
Columns Show/Hide functionality.

**Comment by ElderJames** [comment]
Thanks for contacting us @mehmetuken 
You can try to use `@if` expression to hide/show the columns.

**Comment by JosefRousal** [comment]
You might consider adding a visible parameter to columns in the near future. Should allow you to build this feature in at a later time if it's desired.

**Comment by ElderJames** [comment]
Thanks for suggestion @JosefRousal . This is good idea. Would you be interested in helping us implement this feature?

**Comment by ldsenow** [comment]
@ElderJames I am happy to help with this if no one is working on this atm.

**Comment by ElderJames** [comment]
Sure, you can do it. Thank you very much!

**Comment by YMohd** [comment]
Sorry for intervention...
I have question regarding this feature ,will it work with fixed column?

**Comment by ElderJames** [comment]
I think it needs a test 😂
