### ISSUE TITLE
support modal forcerender

### ISSUE THREAD

**Issue by qinhuaihe** [ant-design-blazor/ant-design-blazor#1349]
### Is your feature request related to a problem? Please describe.
Just like the react one, modal should add a parameter `ForceRender`.

**Comment by ElderJames** [comment]
Thanks for contacting us @qinhuaihe .

We will implement it in the future, or you can submit a PR directly if you have time, we will deal with it ASAP!

**Comment by zxyao145** [comment]
Hi @qinhuaihe ,
Can you provide a specific example? Because Blazor itself is similar to forced rendering.

**Comment by anddrzejb** [comment]
I never worked with react (except some tutorials) and I have no clue what is forcerender 🤔
