### ISSUE TITLE
Modal with combination of expandable table get stuck

### ISSUE THREAD

**Issue by jirisykora83** [ant-design-blazor/ant-design-blazor#1363]
### Describe the bug

Modal with combination of expandable table get stuck

### Steps to reproduce (please include code)

Blazor component

```
<Table DataSource="@model.Items"
		HidePagination="true">
	<RowTemplate>
		<AntDesign.Column Title="Text" TData="string">
			<span>@context.Text</span>
		</AntDesign.Column>
	</RowTemplate>
	<ExpandTemplate>
		<Button OnClick="() => visible = true">open</Button>
		<Modal Title="Title.."
				Visible="@visible"
				OnOk="@HandleOk"
				ConfirmLoading="@confirmLoading"
				OnCancel="@HandleCancel">
			<p>
				Test..
			</p>
		</Modal>
	</ExpandTemplate>
</Table>

@code
{
	private bool visible = false;
	private bool confirmLoading = false;

	private TestComponentParam model = new()
	{
		Items = new List<TestComponentParamItem>()
		{
			new()
			{
				Text = "A",
			},
			new()
			{
				Text = "B",
			},
			new()
			{
				Text = "C",
			},
			new()
			{
				Text = "D",
			},
		},
	};

	private async Task HandleOk(MouseEventArgs e)
	{
		confirmLoading = true;

		await Task.Delay(500);

		model.Items = model.Items.Select(x => new TestComponentParamItem
		{
			Text = x.Text + "",
		}).ToList();

		visible = false;
		confirmLoading = false;
	}

	private void HandleCancel(MouseEventArgs e)
	{
		visible = false;
	}
}
```

```
public class TestComponentParam
{
	public List<TestComponentParamItem> Items { get; set; }
}

public class TestComponentParamItem
{
	public string Text { get; set; } 
}
```

![image](https://user-images.githubusercontent.com/7279825/114938557-8798d300-9e3f-11eb-9b40-584f9fe362f0.png)

### Further technical details
- AntDesign Nuget Package version:  0.7.4

.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

**Comment by zxyao145** [comment]
Hi @jirisykora83, 
this is similar to #1170 , when model.Items updating, the table will be re rendered, as a result, the DOM mounted by Modal is lost, so that it cannot be closed when visible is false. 

You can update the model.Items in AfterClose callback, or using the Modal  out of Table as follow:
```c#
<Table DataSource="@model.Items"
       HidePagination="true">
    <RowTemplate>
        <AntDesign.Column Title="Text" TData="string">
            <span>@context.Text</span>
        </AntDesign.Column>
    </RowTemplate>
    <ExpandTemplate>
        <Button OnClick="() => visible = true">open</Button>
    </ExpandTemplate>
</Table>

<Modal Title="Title.."
       Visible="@visible"
       OnOk="@HandleOk"
       ConfirmLoading="@confirmLoading"
       OnCancel="@HandleCancel">
    <p>
        Test..
    </p>
</Modal>
```

Or, you can try `ModalService.CreateModalAsync`. 

Thank you!

**Comment by jirisykora83** [comment]
Hi @zxyao145 thanks for response I use Modal outside table if i have just one in component but in some cases, it starts to be messy. And I still expect that when component was dispose from DOM it will clean the Modal (from DOM). Or it is any way do this in `Dispose` method manually?

I will look at `ModalService.CreateModalAsync` :)

Thanks for fast respose!
