### ISSUE TITLE
Allow to customize pagination more in table component

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#1366]
### Is your feature request related to a problem? Please describe.
It would be good that we can have the full customization of pagination for a table component.

### Describe the solution you'd like
I guess a pagination template (renderfragment) should be enough. So we dont need to expose more props in the table component and also we can do customization.

**Comment by ElderJames** [comment]
Hi @ldsenow , thanks for contacting us.

You can hide the built-in pagination, and add yours below the table.

**Comment by ldsenow** [comment]
@ElderJames I noticed that in the source code of hidepagination prop. However, it means if i need to have top and bottom pagination, i have to copy to both places. If would be good that we have a built-in way and also extend the prop to support Bottom,Top and Both.

This is my 2c opinion.

**Comment by ElderJames** [comment]
Ok, this is make sense. Would you please help to add this feature?

**Comment by ldsenow** [comment]
Sure, happy to contribute :)

**Comment by ElderJames** [comment]
Thank you!
