### ISSUE TITLE
Table: Use Column Field property first when use Field and DataIndex together

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1383]
### The reason to use both Field and DataIndex properties
When only use DataIndex, must specify TData explicitly. If the property type is changed, it's hard to maintain the code. We can use Field property to implicitly specify TData so that we don't need to change any code when the property type is changed.
When only use Field, we can not always use bind-Field(eg. some part is null in the property path), we must use DataIndex to provide FieldName in this case.

### Is your feature request related to a problem? Please describe.
When DataIndex is specified, DataIndex is used first, the Field propterty value is ignored. I think using Field property directly is better if Field is also explicitly specified. Although DataIndex and Field properties should give same result by proper setting, using Field property first may have better performence.

### Describe the solution you'd like
Use Column Field property first when use Field and DataIndex together.

### Additional context
Ant Design Version: v0.8.0

**Comment by Zonciu** [comment]
That's a good idea, so we can split it into two options:
1.  `bind-Field` do all the jobs.
2.  `Field` provides `TData`, `DataIndex` get value.

But option 2 is a bit redundant, perhaps we can add the `DynamicColumn` component, then `Column` only supports `Field`, `DynamicColumn` only supports DataIndex.

**Comment by anranruye** [comment]
@Zonciu 
It's good to use `bind-Field` to do all the jobs. But I don't think `bind-Field` can do all the jobs, due to the limitation of Blazor underlying implementation.
Is it possible to remove TData type parameter and let DataIndex to do all the jobs?

**Comment by Zonciu** [comment]
> Is it possible to remove TData type parameter and let DataIndex to do all the jobs?

We do have a plan to make a `DynamicColumn` component, use `DataIndex` only, so you don't need to provides `TData` anymore.

**Comment by anranruye** [comment]
@Zonciu
good news
