### ISSUE TITLE
Vertical menu on lower resolutions

### ISSUE THREAD

**Issue by marianoronchi** [ant-design-blazor/ant-design-blazor#1396]
When vertical menu fits on screen works ok:
![image](https://user-images.githubusercontent.com/11918861/115388034-ccab6500-a1b1-11eb-81a0-cf1d35511a19.png)

But if you try on lower resolution screen where the menu does not fit it displayes in a very strange way:
![image](https://user-images.githubusercontent.com/11918861/115388332-1f851c80-a1b2-11eb-90e1-21049b020ddc.png)

**Comment by anddrzejb** [comment]
I see several issues in here. 
First - menu should overflow and show scroll-bar. Second - it should not reposition itself. I think the repositioning is coming from PR #1109 or #1274. @mutouzdl can you confirm? 
On top of that, I saw this interesting behaviour of the `Dropdown` (at first I thought that `Menu` uses `Dropdown` but I think I was wrong?). Look at that:
![dropdown_upDown](https://user-images.githubusercontent.com/6518006/115506595-b40b7f80-a283-11eb-90aa-b51380ad25e7.gif)
It interchangeably renders dropdown once above, once below. 

My repro code
```razor
<Menu Mode=MenuMode.Horizontal>
    <SubMenu Title="Menu">@items</SubMenu>
</Menu>
<Dropdown>
    <Overlay>
        <Menu>@items</Menu>
    </Overlay>
    <Unbound>
        <AntDesign.Button Type="@ButtonType.Link" RefBack="@context">
            Dropdown <Icon Type="down" />
        </AntDesign.Button>
    </Unbound>
</Dropdown>
@code
{
    RenderFragment items =
    @<Template>
        @for(int i = 1; i <= 40; i++)
        {
            int value = i;
            <MenuItem Key="@($"setting{value}")">Option @value</MenuItem>    
        }
    </Template>;
}
```

**Comment by ElderJames** [comment]
Please set the `BoundaryAdjustMode= TriggerBoundaryAdjustMode.None` at `Dropdown` for workaround.

**Comment by anddrzejb** [comment]
I don't really need it, just noticed it. I think at some point it should be addressed.

**Comment by mutouzdl** [comment]
@anddrzejb @marianoronchi Thanks for your feedback, I'will fix it
