### ISSUE TITLE
Automatically sort table when property changed

### ISSUE THREAD

**Issue by kedzior-io** [ant-design-blazor/ant-design-blazor#1398]
So let's say I have this table: 

![image](https://user-images.githubusercontent.com/40808369/115469126-56037b80-a234-11eb-8409-aa8e709df0a6.png)

On each action "Up" and "Down" I swap `SortOrder` property between items but I can't find a way to refresh/re-render the table. It always stays the same. 

Tried on every "Up" and "Down" to call this: 

`List = List.OrderBy(x => x.SortOrder).ToList();` 

as well as 

`await InvokeAsync(StateHasChanged)`

Any idea?

**Comment by anranruye** [comment]
But your screenshot shows that the rows are in right order.  Can you post a full reproduce?

**Comment by kedzior-io** [comment]
Thanks @anranruye. 

This table is populated by the user with select input below the list. 

```
List.Add(new Item
{
    Id = item.Id,
    Name = item.Name,
    DurationInDays = item.DurationInDays,
    SortOrder = item.SortOrder
});
```

which means the item gets added as a last row. 

Now by having "Up" and "Down" for each row allows the user to change the `SortOrder` of the row and I want the table to reflect that. 

```
private void SortUp(int id)
{
    var itemToSort = List.Single(x => x.Id == id);
    var itemIndex = List.IndexOf(itemToSort);

    if (itemIndex == 0)
    {
        return;
    }

    var newItemIndex = itemIndex - 1;
    List.SwapSortOrder(itemIndex,newItemIndex);     // this swaps sort order property
    List = List.OrderBy(x => x.SortOrder).ToList();
}
```

Table doesn't change at all but I know for the fact that `SortOrder` property is updated correctly as the list is posted to API and changes are reflected.

My end goal is to create table where user can swap order of the rows either by drag and drop like https://jqueryui.com/sortable/ or "up" and "down" buttons.

**Comment by anddrzejb** [comment]
@kedzior-io Do you think you could provide a self-contained minimal repro of your issue, including table and models you are using? A snippet that a contributor could just paste it, run it and maybe even use it for verification of the changes to AntBlazor.

**Comment by anranruye** [comment]
@kedzior-io Well, this works for me:
```C#
@page "/demo" 
@using AntDesign
@using AntDesign.TableModels

<Table TItem="Data" DataSource="List">
    <Column Title="Name" @bind-Field="context.Name"></Column>
    <Column Title="Duration(Days)" @bind-Field="context.DurationInDays"></Column>
    <Column Title="Sort" @bind-Field="context.SortOrder"></Column>
    <ActionColumn>
        <Space>
            <SpaceItem>
                <Button Type="@ButtonType.Link" OnClick="() => { SortUp(context.Id); }">Up</Button>
            </SpaceItem>
            <SpaceItem>
                <Button Type="@ButtonType.Link" OnClick="() => { SortDown(context.Id); }">Down</Button>
            </SpaceItem>
        </Space>
    </ActionColumn>
</Table>

@code {
    public class Data
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int DurationInDays { get; set; }

        public int SortOrder { get; set; }
    }

    List<Data> List = new List<Data>();

    protected override void OnInitialized()
    {
        List.AddRange(Enumerable.Range(1, 5).Select(x => new Data
        {
            Id = x,
            DurationInDays = x * 2,
            Name = $"Item{x}",
            SortOrder = x
        }));
    }

    private void SortUp(int id)
    {
        var itemToSort = List.Single(x => x.Id == id);
        var itemIndex = List.IndexOf(itemToSort);
        if (itemIndex == 0)
        {
            return;
        }
        var newItemIndex = itemIndex - 1;
        itemToSort.SortOrder--;
        List[newItemIndex].SortOrder++;
        List = List.OrderBy(x => x.SortOrder).ToList();
    }

    private void SortDown(int id)
    {
        var itemToSort = List.Single(x => x.Id == id);
        var itemIndex = List.IndexOf(itemToSort);
        if (itemIndex == List.Count - 1)
        {
            return;
        }
        var newItemIndex = itemIndex + 1;
        itemToSort.SortOrder++;
        List[newItemIndex].SortOrder--;
        List = List.OrderBy(x => x.SortOrder).ToList();
    }
}
```

https://user-images.githubusercontent.com/54608128/115588404-4bfb7e80-a301-11eb-8cc0-8415640bf96b.mp4

**Comment by kedzior-io** [comment]
@anddrzejb and @anranruye thanks!

Actually yes it does work: https://github.com/kedzior-io/blazor-antdesign-table-move-rows-up-and-down 

Overwriting the list does the job as for example using static method: 

  `Items = SwapSortOrders(Items, index, newIndex);`
  
 Doing the same but with an extension method doesn't:
 
 `Items.SwapSortOrders(index, newIndex);`

**Comment by kedzior-io** [comment]
Oh and by the way. Awesome work!
