### ISSUE TITLE
how to custom modal head

### ISSUE THREAD

**Issue by wlq200** [ant-design-blazor/ant-design-blazor#1403]
how to custom modal head

**Comment by ElderJames** [comment]
Hi @wlq200 , you may can use `TitleTemplate`.

**Comment by wlq200** [comment]
我的目的： 定制Modal Head外观例如像标准widow form窗口


我的Modal代码：


1. ModalWrapper.razor


<Modal Style="@Style"
&nbsp; &nbsp; &nbsp; ***@***.***Visible"
&nbsp; &nbsp; &nbsp; &nbsp;Closable="false"
&nbsp; &nbsp; &nbsp; &nbsp;MaskClosable=false
&nbsp; &nbsp; &nbsp; &nbsp;Draggable
&nbsp; &nbsp; &nbsp; &nbsp;DestroyOnClose
&nbsp; &nbsp; &nbsp; &nbsp;Centered
&nbsp; &nbsp; &nbsp; &nbsp;Footer=null&gt;
&nbsp; &nbsp; <TitleTemplate&gt;
&nbsp; &nbsp; &nbsp; &nbsp; @Title
&nbsp; &nbsp; </TitleTemplate&gt;
&nbsp; &nbsp; <ChildContent&gt;
&nbsp; &nbsp; &nbsp; &nbsp; <CascadingValue Value="@((IModalWrapper)this)"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; @ChildContent
&nbsp; &nbsp; &nbsp; &nbsp; </CascadingValue&gt;
&nbsp; &nbsp; </ChildContent&gt;


</Modal&gt;


@code {
&nbsp; &nbsp; [Parameter]
&nbsp; &nbsp; public string Style { get; set; } = "width:800px;";


&nbsp; &nbsp; [Parameter]
&nbsp; &nbsp; public RenderFragment Title { get; set; }


&nbsp; &nbsp; [Parameter]
&nbsp; &nbsp; public bool Visible { get; set; }
&nbsp; &nbsp; [Parameter]
&nbsp; &nbsp; public EventCallback<bool&gt; VisibleChanged { get; set; }


&nbsp; &nbsp; [Parameter]
&nbsp; &nbsp; public RenderFragment ChildContent { get; set; }
}



2. ModalWrapper.razor.cs

public interface IModalWrapper

&nbsp; &nbsp;{

&nbsp; &nbsp; &nbsp; &nbsp; void CloseModal();

&nbsp; &nbsp; }




&nbsp; &nbsp; public partial class ModalWrapper : IModalWrapper

&nbsp; &nbsp; {

&nbsp; &nbsp; &nbsp; &nbsp; public async void CloseModal()

&nbsp; &nbsp; &nbsp; &nbsp; {

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Visible = false;

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await VisibleChanged.InvokeAsync(Visible);

&nbsp; &nbsp; &nbsp; &nbsp; }

&nbsp; &nbsp; }

**Comment by ElderJames** [comment]
Oh, you can override the style.
