### ISSUE TITLE
When "Modal" is turned on, the next floating layer flashes

### ISSUE THREAD

**Issue by BeiYinZhiNian** [ant-design-blazor/ant-design-blazor#1404]
### Describe the bug

If you continue to open other floats after you open Modal, the button will flash when you click

![GIF](https://user-images.githubusercontent.com/25119211/115683687-48133f00-a389-11eb-83d7-6458600706de.gif)

### Steps to reproduce (please include code)

````c#
<Modal Title="@title"
       Visible="@_visible"
       DestroyOnClose="true"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel">
    <Add></Add>
</Modal>
@code{
    string title = "新增";
    bool _visible = false;

    private void HandleOk(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }

    private void HandleCancel(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }
}

********************<Add>**********************************
<Button type="@ButtonType.Primary" OnClick="OpenIconModal">图标库</Button>
        <Popover ContentTemplate="@_content" Title="图标库">
            <Button type="@ButtonType.Primary">气泡图标库</Button>
        </Popover>
<Modal Visible="@_visible"
       OnOk="HandleOk"
       OnCancel="HandleCancel"
       Title="请选择图标">
    <IconPanel></IconPanel>
</Modal>
@code{
    bool _visible = false;
    public void OpenIconModal()
    {
        _visible = true;
    }

    private void HandleOk(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }

    private void HandleCancel(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }

    RenderFragment _content =
    @<IconPanel></IconPanel>;
}

***********************<IconPanel>*************************
<Button Type="button" OnClick="IconClick">书</Button>
@code{
    void IconClick()
    {

    }
}



````

### Further technical details
- AntDesign Nuget Package version:0.80
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:vs2019

**Comment by zxyao145** [comment]
This may be due to the `ant-click-animating-without-extra-node` attribute of Button. If I delete  `ant-click-animating-without-extra-node`  in the Button component, everything looks normal @ElderJames.

![2021-04-23_20-57-14](https://user-images.githubusercontent.com/24973084/115874679-f2b55b80-a476-11eb-8cf6-4aafd17b961c.gif)

And I think this is similar to the issue #1256 .

**Comment by zxyao145** [comment]
This problem is not easy to see on Chrome v89, but it can be seen clearly on Chrome v90.

**Comment by BeiYinZhiNian** [comment]
@zxyao145 @ElderJames 是的，我是Chrome v90以上.这个问题有办法解决吗

**Comment by zxyao145** [comment]
@BeiYinZhiNian 

I'm afraid there are no other solutions except for direct source code references. Please wait  to fix it.

**Comment by BeiYinZhiNian** [comment]
I see. Thank you

**Comment by ElderJames** [comment]
Fxied in https://github.com/ant-design-blazor/ant-design-blazor/pull/2561
