### ISSUE TITLE
If the prop "DestroyOnClose" is false, the Modal Element can never be removed from the HTML document since it was created,only if the browser tab is closed

### ISSUE THREAD

**Issue by ZhengChen666** [ant-design-blazor/ant-design-blazor#1407]
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by anranruye** [comment]
I think this is by design, the only thing you need to do is to set Destroy on close=true.

**Comment by zxyao145** [comment]
Yes, this is designed, and DOM will removed if the url is modified or the tab is closed.

**Comment by ZhengChen666** [comment]
> Yes, this is designed, and DOM will removed if the url is modified or the tab is closed.

the url was modified but the DOM hasn't been removed

**Comment by zxyao145** [comment]
@ZhengChen666 
How do you change the URL? Is it through NavigationManager?

**Comment by ZhengChen666** [comment]
> @ZhengChen666
> How do you change the URL? Is it through NavigationManager?

yes

**Comment by zxyao145** [comment]
@ZhengChen666 Are you using ModalService?
