### ISSUE TITLE
how to use modal ok button Validate   form inside.

### ISSUE THREAD

**Issue by rennner** [ant-design-blazor/ant-design-blazor#1411]
i placed a form in  modal,  how to Validate  the form, when click the modal's   ok   button.
if Validate  failed,  modal not need to close.
thanks.

我在modal对话框内放置一个表单，请问该怎么在点击modal的ok按钮时自动验证表单，如果验证失败就不关闭modal。
另外，是否应该增加一个按钮点击的回调，或关闭前的回调允许不关闭

**Comment by anranruye** [comment]
如果你用的是modal组件的话，这些功能已经有了，文档里面有和你的描述完全一致的例子

**Comment by zxyao145** [comment]
Hi @rennner , 
please try using `ModalService.CreateModalAsync`, the demo is here: [ModalTemplate](https://antblazor.com/en-US/components/modal#components-modal-demo-modal_service_for_modal)

请使用 `ModalService.CreateModalAsync`，用法可以看示例：[Modal模板组件](https://antblazor.com/zh-CN/components/modal#components-modal-demo-modal_service_for_modal)

**Comment by rennner** [comment]
thanks for anranruye,zxyao145:
Demo中的内容我看过，但我不想再form里面放一个button进行表单验证，我的希望是点击modal的右下角ok按钮，自动验证表单，验证通过后在关闭对话框，demo中的例子并没有体现这个功能

**Comment by anranruye** [comment]
@rennner 哦，我想说的是这个例子 https://antblazor.com/zh-CN/components/form#components-form-demo-customized-form-validator 我忘记了这个是在form文档里，不在modal文档里

**Comment by zxyao145** [comment]
@rennner 
有相似的demo，请看 **Use Template With Result** 示例。

![2021-04-24_13-10-53](https://user-images.githubusercontent.com/24973084/115948107-a4e43600-a4fe-11eb-9f16-21c70f2b5171.gif)

**Comment by rennner** [comment]
thanks for anranruye,  zxyao145:
感谢两位提供的解决方案。问题解决。
