### ISSUE TITLE
Modal: sometimes modal is closed by double clicking

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1414]
### Describe the bug

Modal will be closed by double clicking an inner date picker if MaskClosable=true. 
Update: Also reproduce this with `Select` component.
![动画](https://user-images.githubusercontent.com/54608128/115948284-df020780-a4ff-11eb-8e89-b6d34b6bc72c.gif)

### Steps to reproduce (please include code)

```C#
<Button OnClick="()=> { openModal = true; }">Click</Button>

<Modal Title="Modal" DestroyOnClose="true" Visible="openModal" OnCancel="() => { openModal = false; }">
    <div style="height:500px;">
        <DatePicker @bind-Value="dateTime"></DatePicker>
    </div>
</Modal>

@code{
    bool openModal;
    DateTime dateTime = DateTime.Now;
}
```
### Further technical details
- AntDesign Nuget Package version: 0.8.0

**Comment by zxyao145** [comment]
Yes, this is a known problem and you can't double-click in Modal. Please wait for the bug to fix.
