### ISSUE TITLE
Can't render the table when lazily loading it's datasource

### ISSUE THREAD

**Issue by DJedai18** [ant-design-blazor/ant-design-blazor#1416]
Sorry for not following the design rules report.

If the datasource is null or empty, and fetch data in the override method OnInitializedAsync. Then the table can't render, exception "System.NullReferenceException: "Object reference not set to an instance of an object." in /_Host .

```
<Table DataSource="data2">
      <Column DataIndex="@context.id.ToString()" TData="int?" Sortable></Column>
      <Column DataIndex="@context.Vetstation.title" TData="string" Sortable></Column>
      <Column DataIndex="@context.Region.title" TData="string" Sortable></Column>
      <Column DataIndex="@context.Farm.title" TData="string" Sortable></Column>
      <Column DataIndex="@context.id_method_plan.ToString()" TData="int?" Sortable></Column>
      <Column DataIndex="@context.Animal.title" TData="string" Sortable></Column>
      <Column DataIndex="@context.date_enter.ToString()" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
      <Column DataIndex="@context.date_add" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
      <Column DataIndex="@context.amount.ToString()" TData="int?" Sortable></Column>
      <Column DataIndex="@context.id_empl.ToString()" TData="int?" Sortable></Column>
</Table>
```

```
IEnumerable<PathdataDTO> data2;
@code
{
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await InvokeAsync(StateHasChanged);
        data2 = await pathdata.GetAll();
    }
}
```

### Further technical details
- AntDesign Nuget Package version 0.8.0
- The IDE: VS Community 2019

### dotnet --info
Package SDK for.NET (global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ElderJames** [comment]
Thanks for contacting us @DJedai18 
Please invoke the `StateHasChanged` after your async call.

**Comment by anranruye** [comment]
You should use
```
<Table DataSource="data2">
      <Column DataIndex="id" TData="int?" Sortable></Column>
      <Column DataIndex="Vetstation.title" TData="string" Sortable></Column>
      <Column DataIndex="Region.title" TData="string" Sortable></Column>
      <Column DataIndex="Farm.title" TData="string" Sortable></Column>
      <Column DataIndex="id_method_plan" TData="int?" Sortable></Column>
      <Column DataIndex="Animal.title" TData="string" Sortable></Column>
      <Column DataIndex="date_enter" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
      <Column DataIndex="date_add" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
      <Column DataIndex="amount" TData="int?" Sortable></Column>
      <Column DataIndex="id_empl" TData="int?" Sortable></Column>
</Table>
```

**Comment by anranruye** [comment]
You should use
```
<Table DataSource="data2">
      <Column DataIndex="id" TData="int?" Sortable></Column>
      <Column DataIndex="Vetstation.title" TData="string" Sortable></Column>
      <Column DataIndex="Region.title" TData="string" Sortable></Column>
      <Column DataIndex="Farm.title" TData="string" Sortable></Column>
      <Column DataIndex="id_method_plan" TData="int?" Sortable></Column>
      <Column DataIndex="Animal.title" TData="string" Sortable></Column>
      <Column DataIndex="date_enter" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
      <Column DataIndex="date_add" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
      <Column DataIndex="amount" TData="int?" Sortable></Column>
      <Column DataIndex="id_empl" TData="int?" Sortable></Column>
</Table>
```

**Comment by DJedai18** [comment]
> You should use
> 
> ```
> <Table DataSource="data2">
>       <Column DataIndex="id" TData="int?" Sortable></Column>
>       <Column DataIndex="Vetstation.title" TData="string" Sortable></Column>
>       <Column DataIndex="Region.title" TData="string" Sortable></Column>
>       <Column DataIndex="Farm.title" TData="string" Sortable></Column>
>       <Column DataIndex="id_method_plan" TData="int?" Sortable></Column>
>       <Column DataIndex="Animal.title" TData="string" Sortable></Column>
>       <Column DataIndex="date_enter" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
>       <Column DataIndex="date_add" TData="DateTime?" Format="dd-MM-yyyy" Sortable></Column>
>       <Column DataIndex="amount" TData="int?" Sortable></Column>
>       <Column DataIndex="id_empl" TData="int?" Sortable></Column>
> </Table>
> ```

Not work, appear new exception
```
ArgumentException: The type of the provided expression UnaryExpression is not supported, it should be MemberExpression.
AntDesign.Internal.ColumnExpressionHelper.GetReturnMemberInfo(LambdaExpression expression)
```

**Comment by anranruye** [comment]
@DJedai18 update to the latest 0.8.1 nightly-build version(not the 0.9.0 nightly-build), this issue is already fixed.

**Comment by DJedai18** [comment]
@anranruye  Can you send the link, i only have 0.7.0 nightly?

**Comment by ElderJames** [comment]
Please wait for the 0.8.1 release.
