### ISSUE TITLE
(Documentation) Opening code example and navigating to another component doesn't update code example

### ISSUE THREAD

**Issue by ske66** [ant-design-blazor/ant-design-blazor#142]
**Description**

When you open the example code section of a component the code displays as expected. However, if you navigate to another component and look at the code sample, you will see the code for the previously viewed component.

**Steps to reproduce**

This bug only seems to occur in component pages that are part of the same "group". For example, if you first look at a code sample in the Data Entry group, the second component you navigate to must also be part of the Data Entry Group.

Example;
1. navigate to DatePicker and open the code example.
2. navigate to Input and you will see the Datepicker code example still open and attached to the Input code example.
3. Refreshing the page fixes this issue

**Comment by ElderJames** [comment]
Thanks for your reporting, I will take a check and fix it later.
