### ISSUE TITLE
Rich Text Editor Input Component

### ISSUE THREAD

**Issue by Gareth064** [ant-design-blazor/ant-design-blazor#1422]
### Describe the solution you'd like
A rich text editor component is something that I believe most enterprise level apps would like for forms which require more than plain text inputs.

### Additional context
Something similar to https://github.com/Blazored/TextEditor but I'm not sure how much is doable with out using JSInteropt.

**Comment by MutatePat** [comment]
Are you looking for something like this:

https://github.com/ant-design-blazor/ueditor-blazor

Or this?

https://github.com/ant-design-blazor/vditor-blazor

**Comment by Gareth064** [comment]
@MutatePat They look good. Are they in separate projects so they can be fleshed out and demo'd to then  be added to Ant Design Blazor full package at a later date? Or Are they always going to be separate projects?
@ElderJames

**Comment by MutatePat** [comment]
> @MutatePat They look good. Are they in separate projects so they can be fleshed out and demo'd to then be added to Ant Design Blazor full package at a later date? Or Are they always going to be separate projects?
> @ElderJames

Haven't used those libraries myself, but I believe since they are not developed by Ant Design( the original react project), the editors are not "in-scope" for this repo.

**Comment by ElderJames** [comment]
Yes, they are always going to be separate projects.
