### ISSUE TITLE
MenuItem "Class name is not valid at this point" error

### ISSUE THREAD

**Issue by danich93** [ant-design-blazor/ant-design-blazor#1425]
### Describe the bug

Having a MenuItem tag inside of the C# code block tag causes intellisense error "Class name is not valid at this point". Possibly caused by MenuItem being a self closing tag. It doesn't cause compilation error though.

### Steps to reproduce (please include code)

Example code that causes an error:
```
@{
   <MenuItem Key="dashboard" RouterLink="@(Routes.Dashboard.Page)" RouterMatch="@NavLinkMatch.Prefix">
         <Icon Type="group" Theme="outline"/>
         <span>Dashboard</span>
   </MenuItem>
}
```

### Further technical details
- AntDesign Nuget Package version: 0.8.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Rider 2021.1.2

**Comment by ElderJames** [comment]
Hi @danich93 , thanks for contacting us.

But why did you put the razor code in @code block?

**Comment by danich93** [comment]
Hi @ElderJames 
I want to dynamically create a number of menu items by iterating over my collection defined in C# code, which is why I need to envelope the menu item with @{}. For instance:

```
@foreach (var item in collection){
   <MenuItem Key="dashboard" RouterLink="@(Routes.Dashboard.Page)" RouterMatch="@NavLinkMatch.Prefix">
         <Icon Type="group" Theme="outline"/>
         <span>@item.Name</span>
   </MenuItem>
}
```

**Comment by ElderJames** [comment]
Yes, you can do that. But I don't see anything wrong in the code snippet you provided.

**Comment by danich93** [comment]
@ElderJames  Yes, it shouldn't be a problem, and it does compile just fine, but the intellisense still complains about it:

![image](https://user-images.githubusercontent.com/12150837/116436617-db96b500-a84c-11eb-968f-7cb8e08688ed.png)

I had a similar issue with a <Col> tag where it wouldn't even compile, but was able to use <GridCol> tag instead. Not sure how to bypass it here, though. Its really annoying to have this error hang in my project.

**Comment by ElderJames** [comment]
I think it's just a syntax error and not a component problem.

**Comment by danich93** [comment]
Seems to only be an issue with Rider. VS has no such problem. I will take it to Rider forums.

**Comment by seagullcz** [comment]
Hello @danich93 .

Do you have any news about this issue from JetBrains or Ridder forum? I am dealing with this error right now and and it is bloody annoying.

**Comment by danich93** [comment]
@seagullcz I reported it to JB, they are already aware of this issue, but there is no clear indication of when it will be fixed. It is probably a very low priority for them.
