### ISSUE TITLE
column display error when set Filters

### ISSUE THREAD

**Issue by HongSheng-Git** [ant-design-blazor/ant-design-blazor#1427]
when set column filters and do not set sortable ,the table can not display title

**Comment by Zonciu** [comment]
Please provide a reproduction example and the version you are using.

**Comment by HongSheng-Git** [comment]
version：v0.7.4
set Sortable at first, it can display title at table head,the code like this :
<AntDesign.Column @bind-Field="@context.IsConnected" Sortable Filters="_connectFilters"
                                              OnFilter="(value,field)=>ConnectFilte(value,field)" Width="120">
.....
</AntDesign.Column>

but i don't need sort, just need for filter ,But the table can't show title at table head this time, code:
<AntDesign.Column @bind-Field="@context.IsConnected"  Filters="_connectFilters"
                                              OnFilter="(value,field)=>ConnectFilte(value,field)" Width="120">
.....
</AntDesign.Column>


Others:
1.i had try to use V0.8.0, but it doesn't useful
2.V0.8.0  the table Integrated with Pagination，but the attribute of ShowTotal can't be used

**Comment by Zonciu** [comment]
Try version `0.8.1-nightly-2104281524`, it should fix this issue.

**Comment by HongSheng-Git** [comment]
ok thanks, i’ll try(don't find 0.8.1-nightly on  nuget at present );

the others about table  Integrated with component of Pagination，we can't use  the attribute of ShowTotal, Can it appear in the next version？o^~^o^~^o

**Comment by Zonciu** [comment]
Nightly build is in here: https://github.com/ant-design-blazor/ant-design-blazor/blob/master/docs/nightly-build.en-US.md

In `feature` branch, we added `PaginationTemplate` parameter to `Table` component, to allow custom pagination.

**Comment by HongSheng-Git** [comment]
OK，thanks for your help~
