### ISSUE TITLE
DatePicker: The overlay panel closes when click any place

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1431]
### Describe the bug

After update to 0.8.1-nightly-2104280412, the DatePicker overlay panel closes when click any place. If we want to use the header buttons, this causes troubles. 
![image](https://user-images.githubusercontent.com/54608128/116384583-95405680-a84a-11eb-9d79-2881a4a65148.png)

### Further technical details
- AntDesign Nuget Package version: 0.8.1-nightly-2104280412

**Comment by anddrzejb** [comment]
Must be my PR #1389... I will have a look at it.
