### ISSUE TITLE
Table: EndsWith(结尾是) operator for string filter is not working correctly  

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1433]
### Describe the bug

EndsWith operator for string filter is not working correctly due to a wrong spell.
![动画5](https://user-images.githubusercontent.com/54608128/116418642-ec582280-a86e-11eb-808b-11fff575d23d.gif)

### Further technical details
- AntDesign Nuget Package version: 0.8.0

**Comment by ElderJames** [comment]
cc @YMohd
