### ISSUE TITLE
Cascader: in hover mode popup should close when option is selected

### ISSUE THREAD

**Issue by vaderr12** [ant-design-blazor/ant-design-blazor#1438]
Hello,
I think current behavior of cascader is not very intuitive.  Popup with options should close automatically when option is selected (clicked), at least in hover mode.

**Comment by ElderJames** [comment]
Thanks for contacting us @vaderr12 ,
Currently in 0.8.0, cascader already would close automatically when option is selected.

**Comment by vaderr12** [comment]
Hi,
Thanks for info.
Yes, in 0.8.0 cascader closes, but I use it with` ChangeOnSelect="AllowSelectAll"` and `ExpandTrigger="@("hover")"`, and I expect that popup would also close when I select non leaf nodes. This is not happening in 0.8,0.
