### ISSUE TITLE
Calendar Day french translation error

### ISSUE THREAD

**Issue by dust63** [ant-design-blazor/ant-design-blazor#1443]
### Describe the bug

In french the calendar day was not translate. In the mont view day are with 2 english letters like: MO TU WE...
In french should be LU MA ME... (Lundi, Mardi,Mercredi) 
![image](https://user-images.githubusercontent.com/13755387/116615823-22afa380-a93c-11eb-8585-baedc1630341.png)

### Steps to reproduce (please include code)
Pass you browser into french.
-->

### Further technical details
- AntDesign Nuget Package version AntDesign.Pro.Layout Version="0.1.0-*", AntDesign.Charts Version="0.2.0-*"
- Include the output of `dotnet --info`
 Version:   5.0.104
 Commit:    ca6b6acadb

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.104\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
vs code

**Comment by MutatePat** [comment]
@anddrzejb Is the localization of DatePicker part of your PR?

**Comment by anddrzejb** [comment]
The localization file [fr-FR.json](components/locales/fr-FR.json) is missing [this entry](https://github.com/ant-design-blazor/ant-design-blazor/blob/17b279bccabc356a244fb67decdb1241a5b5bd6f/components/locales/en-US.json#L67). @dust63 do you think you could submit a PR for that translation?

**Comment by dust63** [comment]
yep I can do that. Just indicate to me the operations to do to add translation ;)

**Comment by anddrzejb** [comment]
So you can use [this gist](https://gist.github.com/Chaser324/ce0505fbed06b947d962) to find out how to fork and do pull request.
You just need to apply the changes to the file I mentioned in my previous comment. Then push to your forked repo. Then open pull request.
