### ISSUE TITLE
Validation message not showing with InputPassword being part of a child Component, data binding

### ISSUE THREAD

**Issue by quirynen** [ant-design-blazor/ant-design-blazor#1446]
### Describe the bug

I have a parent component using a child component and passing its model  to bind it to the child component using InputPassword. 
The red star showing that a field is required is not displayed, neither is the validation message when the field is empty (after clicking on the button validating the form).

### _Here is the code of the parent component using the child's one :_ 
    <Form Model="@model" class="login__form form" Layout="@model.Layout" @ref="form" Loading="@loading">
       <ChildInputPassword @bind-Password="@context.Password" PlaceHolder="Password"/>
    </Form>

@code {
 public class Model
        {
            public string Layout { get; set; } = FormLayout.Vertical;

            [Required]
            [StringLength(15, ErrorMessage = "Must be between 5 and 15 characters", MinimumLength = 5)]
            [DataType(DataType.Password)] public string Password { get; set; }

        }
}
}

_### And here is the child Component :_ 

<InputPassword @bind-Value="@ChildPassword" Placeholder="@Placeholder"/>

@code{

    [Parameter]
    public string ChildPassword
    {
        get => Password;
        set => PasswordChanged.InvokeAsync(value);
    }
    [Parameter]
    public string Placeholder { get; set; }

    [Parameter]
    public string Password { get; set; }

    [Parameter]
    public EventCallback<string> PasswordChanged { get; set; }

}
}

Any ideas on how to fix that?

### Further technical details
- AntDesign Nuget Package version : 0.8.0

**Comment by anranruye** [comment]
You should follow the documentation to create your custom input component.

**Comment by quirynen** [comment]
You mean from the MS documentation?

**Comment by anranruye** [comment]
from the ant design docs

**Comment by quirynen** [comment]
I did not find any docs in the blazor antDesign on how to create a custom component, if you find some time, could you maybe send me a link please, that would be much appreciated !

**Comment by quirynen** [comment]
Thanks ! I'll give it a try !

**Comment by quirynen** [comment]
Are there any examples given the details in (https://github.com/ant-design-blazor/ant-design-blazor/wiki/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%94%AF%E6%8C%81Form%E8%A1%A8%E5%8D%95%E7%9A%84%E7%BB%84%E4%BB%B6%EF%BC%9F) ? I don't really understand what should I bind to my custom control (value or current-value)?

Here is what I have currently but I still don't see any validation messages: 

@using AntDesign
@inherits AntInputComponentBase<string>

<FormItem labelContent="Password" Style="login__label">
    <InputPassword @bind-Value="@Value" Placeholder="@Placeholder"/>
</FormItem>

@code{
    [Parameter]
    public string Placeholder { get; set; }
}

And here is how I "call" it
<Form Model="@model" class="login__form form" Layout="@model.Layout" @ref="form">
  <CustomInputPassword @bind-CurrentValue="context.Password" PlaceHolder="Password"/>
</Form>
@code{

 public class Model
        {
            public string Layout { get; set; } = FormLayout.Vertical;
            [Required]
            public string Password { get; set; }
        }
}

**Comment by anranruye** [comment]
Here's an example: https://github.com/ant-design-blazor/ant-design-blazor/issues/1453#issuecomment-831004292

**Comment by quirynen** [comment]
Indeed now the password is correctly linked with CurrentValue, but to be able to see the validation message : "Password is Required", I need to add  <ValidationMessage For="@(() => model.Password)" /> in the parent component 
`    <Form Model="@model" class="login__form form" Layout="@model.Layout" @ref="form" Loading="@loading">
   
        <TrasisInputPassword @bind-Value="context.Password" PlaceHolder="Password" Required="true" />
        <ValidationMessage For="@(() => model.Password)" />
     
    </Form>`
, by reading the docs and the examples, it seems unnecessary to add it explicitely, any ideas why it is not correctly displayed ?

**Comment by anranruye** [comment]
Do not put `FormItem` inside the child component, put it outside. Also, add to child component:
```
@using AntDesign.Internal;
<CascadingValue Value="null" Name="FormItem" TValue="IFormItem" IsFixed="@true">
</CascadingValue>
```

**Comment by quirynen** [comment]
It is now working, thanks for the help, do you know if in the future it will be possible to also put the formItem in the child Component ?

**Comment by anranruye** [comment]
try this:
```
@using System.Linq.Expressions

<FormItem Label="Label" Required="@Required" @attributes="AdditionalAttributes">
    <InputPassword ValueExpression="@ValueExpression" Value="@Value" 
                   ValueChanged="value => { if (ValueChanged.HasDelegate) ValueChanged.InvokeAsync(value); }"
                   Placeholder="@Placeholder" />
</FormItem>

@code {
    [Parameter]
    public string Value { get; set; }

    [Parameter]
    public EventCallback<string> ValueChanged { get; set; }

    [Parameter]
    public Expression<Func<string>> ValueExpression { get; set; }

    [Parameter]
    public string Label { get; set; }

    [Parameter]
    public string Placeholder { get; set; }

    [Parameter]
    public bool Required { get; set; }

    [Parameter(CaptureUnmatchedValues = true)]
    public Dictionary<string, object> AdditionalAttributes { get; set; }
}
```

**Comment by quirynen** [comment]
Also working ! Thank you very much for your help, did not expect such dedication from you, highly appreciated ! Have a nice day and I'm closing this issue :)
