### ISSUE TITLE
Mentions Component Demos do not work

### ISSUE THREAD

**Issue by MutatePat** [ant-design-blazor/ant-design-blazor#1456]
### Describe the bug

The mentions component demo does not work( not sure if it doesn't work in prod). Currently the demo just logs user keys in console.

### Steps to reproduce (please include code)

https://antblazor.com/en-US/components/mentions

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Yes, this component does still have problems...

**Comment by MutatePat** [comment]
I'll look into this and submit a PR when ready :)

**Comment by ElderJames** [comment]
Oh, thanks a lot!
