### ISSUE TITLE
Checkbox: bind-Value doesn't render properly when initial value is true

### ISSUE THREAD

**Issue by Zonciu** [ant-design-blazor/ant-design-blazor#1457]
### Describe the bug

When initial value is true, checkbox doesn't render as true.

**Current result:**
![image](https://user-images.githubusercontent.com/10374056/116899178-d204b700-ac69-11eb-97f2-49b140710189.png)

**Should be:**
![image](https://user-images.githubusercontent.com/10374056/116899058-b1d4f800-ac69-11eb-8e23-8b6a0dffedd8.png)

### Steps to reproduce (please include code)
```
<div style="padding: 30px">
    <Form Model="@model">
        <FormItem>
            <Checkbox @bind-Value="context.RememberMe">Remember me</Checkbox>
        </FormItem>
    </Form>


    Remember me: @model.RememberMe
</div>

@code
{
    public class Model
    {
        public bool RememberMe { get; set; } = true;
    }

    private Model model = new Model();

}
```

### Further technical details
- AntDesign Nuget Package version: master branch

**Comment by Zonciu** [comment]
@anddrzejb Maybe this is caused by #1394 .

**Comment by anddrzejb** [comment]
I will have a look. `Checkbox` component has already almost full test coverage, so I will start with tests.

**Comment by Zonciu** [comment]
Looks like [Checkbox.razor.cs#L74](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/checkbox/Checkbox.razor.cs#L74) blocked the value initialization.
