### ISSUE TITLE
Doc: English documentation code blocks are broken

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1461]
### Describe the bug

An example:
![image](https://user-images.githubusercontent.com/54608128/116951733-38fe8c00-acbb-11eb-9a3f-532c3cafc67c.png)
![image](https://user-images.githubusercontent.com/54608128/116951742-43b92100-acbb-11eb-8844-257cb07457bb.png)

Probably caused by:
https://github.com/ant-design-blazor/ant-design-blazor/blob/504e49fd96fec488e0d3657b683adec3d689f510/site/AntDesign.Docs.Build.CLI/Utils/DocParser.cs#L130-L133
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thanks for finding this issue. You can submit a PR for it.
