### ISSUE TITLE
(Feature) Notification - allow closing using code

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/ant-design-blazor#1463]
### Is your feature request related to a problem? Please describe.
My use case is that in certain scenarios I open a notification with `Duration = 0`. This makes the notification visible until the user closes it or refreshes the page. However, I would like to be able to close the notification using code, especially when some of the conditions change.

### Describe the solution you'd like
When calling notification, an interface could be returned that would allow me run `.Close()` or `.Dismiss()` or alike method.

**Comment by MutatePat** [comment]
Should notification/message inherit from IFeedbackRef to allow this?

**Comment by anddrzejb** [comment]
Beats me :smile:. This part of `AntDesign` is still a mystery to me. I imagine not necessarily. I do not really see any use for most of the methods in `IFeedbackRef`. Other possible functionality would be to allow content changes, which does not exist in `IFeedbacRef`. Though we already have this using `Key` property on `NotificationConfig`. It feels clumsy to me, but it is useable. I was actually trying to used the `Key` property to change the `Duration = 0.1` but that did not work. It may be a bug I guess?

**Comment by MutatePat** [comment]
> Beats me 😄. This part of `AntDesign` is still a mystery to me. I imagine not necessarily. I do not really see any use for most of the methods in `IFeedbackRef`. Other possible functionality would be to allow content changes, which does not exist in `IFeedbacRef`. Though we already have this using `Key` property on `NotificationConfig`. It feels clumsy to me, but it is useable. I was actually trying to used the `Key` property to change the `Duration = 0.1` but that did not work. It may be a bug I guess?

Looking over IFeedbackRef, I think that it would be a good base. Since it only contains open/close methods ( and async versions for each) and an internal method. 

Using a Key doesn't seem ideal to me. As in some cases, you wouldn't know the value of the key before the notification is generated. So you using a variable is preferable over a key for "dynamic" notifications.

**Comment by anddrzejb** [comment]
Well, maybe...But I image applying `IFeedbackRef` to notification will be much harder - especially in the area of `OpenAsync` method. It seems to me like in that case a bulk of notification service could be omitted. However I am not qualified enough to actually say anything of value here. As I said before - I haven't touched notification service, so I only speculate here. I imagine either @zxyao145 or @ElderJames would have to comment here on this proposal.

**Comment by zxyao145** [comment]
At present, Notification conponment is originally migrated from Ant Design of React. I think it should have the characteristics of Ant Design Blazor. It should be a good choice to return a Ref object with close, update and other methods. And inherited from IFeedbackref, this seems to be a good choice. The implementation of `OpenAsync` method may be a bit difficult, but it can be done.

**Comment by georgeemr** [comment]
My notification never closes, even if I put a timeout.
This happens when I call the notification from a modal
![image](https://user-images.githubusercontent.com/3822009/120423914-9d4b5480-c328-11eb-93c9-4cb522ab4a4b.png)

**Comment by zxyao145** [comment]
> My notification never closes, even if I put a timeout.
> This happens when I call the notification from a modal
> ![image](https://user-images.githubusercontent.com/3822009/120423914-9d4b5480-c328-11eb-93c9-4cb522ab4a4b.png)

@georgeemr  Hi, how do you use it? Do you have sample code?
