### ISSUE TITLE
Support FocusAsync on "Search" component

### ISSUE THREAD

**Issue by newbe36524** [ant-design-blazor/ant-design-blazor#1471]
### Is your feature request related to a problem? Please describe.

I want to focus a Search input every time when user active a web UI.

### Describe the solution you'd like

I think it should be as below, it is the same as normal input as blazor componenet:

```csharp

input.FocusAsync();

```

I think it should be support to custom what will happen when user invoke FocusAsync(), there should be some options:

1. Keep content and select that all
1. Clean content
1. Keep content and move cursor at the end of input
1. Keep content and move cursor at the head of input

**Comment by anddrzejb** [comment]
@ElderJames If we are going to do this, I think we should be consistent across the board - so same with `Select`, `Autocomplete`, `DatePicker`, etc... Any component that has some kind of manual input.

**Comment by ElderJames** [comment]
I think people can use `Input.Ref.FocusAsync()`. But it also needs to handle the focus style.

**Comment by anddrzejb** [comment]
If we are going to allow proposed focus options, then we need to still expose our own method. Of course people will be able to use `{Component}.Ref.FocusAsync()`.
