### ISSUE TITLE
Select: Click the down arrow causes the dropdown close immediately after open

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1473]
### Describe the bug

Click the down arrow causes the dropdown close immediately after open.
![动画1](https://user-images.githubusercontent.com/54608128/117295365-5479ba80-aea6-11eb-87a3-75f19cdd586d.gif)

### Further technical details
- AntDesign Nuget Package version: 0.8.0

**Comment by anddrzejb** [comment]
@anranruye I agree this bug exists in the docs. But I cannot recreate using the latest commit (I was testing the docs using commit a72d8cb). Can you confirm?

**Comment by anranruye** [comment]
@anddrzejb 
Seems that this is fixed in the latest nightly-build version. Closing this now.
