### ISSUE TITLE
TextArea does not support readonly

### ISSUE THREAD

**Issue by Ben-Pattinson** [ant-design-blazor/ant-design-blazor#1479]
### Describe the bug

TextArea does not allow you to set the html readonly attribute. It actively fights any attempt to work around it using @Attributes. 

### Steps to reproduce (please include code)

We want to do this: 
`<TextArea id="blah-content" @bind-Value="@blah" MinRows="20" MaxRows="20" readonly />`

This works with the Microsoft controls: 
```
<EditForm Model="bogusModel">
<InputTextArea id="blah-content" @bind-Value="@blah" rows="20" cols="20" readonly class="ant-input"/>
</EditForm>
```

It's possible that this also occurs on the input controls.

### Further technical details
- AntDesign Nuget Package version 0.7.3

**Comment by anddrzejb** [comment]
I wonder what would be expected visual behavior. I mean, should it receive focused style? How would a user recognize that this particular element is read only? Or should we treat it exactly the same as a regular textbox?

**Comment by anranruye** [comment]
@anddrzejb Compared with raw html input elements, I think it's ok to just add a readonly attribute to the generated html input elements. The only thing to note is that `AllowClear` should be ignored when `Readonly` is set.

**Comment by anddrzejb** [comment]
Yeah, I was thinking the same thing. My issue is mostly with the equested extra focus arguments.

**Comment by anranruye** [comment]
@anddrzejb I think they should receive focus. Otherwise, `Disabled` and `Readonly` have only style differences

**Comment by anddrzejb** [comment]
They will. I waa talking about the proposal of passing arguments to focus method that will  determin cursor position or clear the input.

**Comment by anranruye** [comment]
@anddrzejb Yes, that should be considered also.
