### ISSUE TITLE
Table Sorters broken on Forked Demo and others

### ISSUE THREAD

**Issue by MutatePat** [ant-design-blazor/ant-design-blazor#1481]
### Describe the bug

On the [default demo](https://antblazor.com/en-US/components/table#components-table-demo-blazor) the sorters are broken on Google Chrome and Edge - until the delete button is pressed. Additionally( will try to update this with code samples), sometimes the sorters break after item deletion - **unless TableRef.ReloadData()** is called after the change. I don't think that calling ReloadData should be done by the end user.

**Comment by MutatePat** [comment]
![sorterror](https://user-images.githubusercontent.com/42546986/117374645-7171b600-aec5-11eb-9758-c9c9b55b2a6b.gif)

**Comment by anranruye** [comment]
Thanks for contacting us @MutatePat .

I can say this is just the normal behavior. If `Total` is larger than the item count of `DataSource`, `Table` component works in "server mode". In this situation, sorting, filtering and paging should all be implemented by the end user. 

In this demo, `Total` is first set to `50`, while the data source contains only `10` items. So `Table` works in "server mode". The sorter doesn't work because `OnChange` method doesn't implement this logic. After clicking the delete button, `Total` is set to the item count of `DataSource`,  the `Table` starts to work in "client mode", then the sorter works.

We should update this demo. But I believe there is no bug in the component library.

**Comment by MutatePat** [comment]
I do not agree. In most deployments, we want sorting to be done by table component - rather than the DataSource. 

Should we add a new parameter to the API? `ForceClientProcessing : bool` 

I could add this if you're busy?

**Comment by anranruye** [comment]
@MutatePat 

I think it's good to add a new paramter to specify the pagination mode. This new paramter should be an enum type which has three values: `Auto`, `Server` and `Client`.

But I'm not sure what should `Table` component do when force it to work in "client" mode but the `Datasource` doesn't have enough items. Consider we set `Total=50 PageSize=10 DataSource=@(GetData(count: 10))`, note that the datasource has only 10 items, then should the 2-5 pages be empty?

**Comment by MutatePat** [comment]
> @MutatePat
> 
> I think it's good to add a new paramter to specify the pagination mode. This new paramter should be an enum type which has three values: `Auto`, `Server` and `Client`.
> 
> But I'm not sure what should `Table` component do when force it to work in "client" mode but the `Datasource` doesn't have enough items. Consider we set `Total=50 PageSize=10 DataSource=@(GetData(count: 10))`, note that the datasource has only 10 items, then should the 2-5 pages be empty?

I was referencing forcing sorters/filters to be handled by the component rather than pagination. However I believe we should not display any empty pages( except page 1 if there's no data), as this could impact UX

**Comment by anranruye** [comment]
@MutatePat 

I don't think it's possible/good to use sorters/filters independently of pagination. Consider how the `Table` works when the `DataSource` has enough items. The table should first apply sorters/filters to the data source items, then get the items in a single page. When the `DataSource` doesn't have enough items, I think table should have the same behavior, then there may be some empty pages.

If you mean you want to get a page first, then use sorters/filters inside this page, you can give your own implementation. Also, there should be another mode to identity this behavior. Honestly, I can't understand this behavior and can't imagine how to achieve this.

**Comment by anranruye** [comment]
@MutatePat  Do you have any new ideas?
