### ISSUE TITLE
Avatar position misplace

### ISSUE THREAD

**Issue by cephaspad** [ant-design-blazor/ant-design-blazor#1483]
### Describe the bug

Avatar position has wrong place. Perhaps, it should be little upper
In my project
![1](https://user-images.githubusercontent.com/22416212/117442390-e34b0d80-af60-11eb-8c22-52c5c9ab2fcf.png)

But, It should be
![2](https://user-images.githubusercontent.com/22416212/117442398-e6de9480-af60-11eb-91ea-96c4fd2ae7eb.png)

### Steps to reproduce (please include code)

[BlazorWebApplication1.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/6441115/BlazorWebApplication1.zip)

### Further technical details
- AntDesign 0.8.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio 2019 Community

**Comment by ElderJames** [comment]
Thanks for contacting us @cephaspad 
Please try to remove your bootstrap style reference, because it conflicts with AntDesign's style.

**Comment by MutatePat** [comment]
> Thanks for contacting us @cephaspad
> Please try to remove your bootstrap style reference, because it conflicts with AntDesign's style.

Should we include this in the [docs](https://antblazor.com/en-US/docs/getting-started)

**Comment by cephaspad** [comment]
It works like a charm. Thanks @ElderJames .

**Comment by TsakiDev** [comment]
@MutatePat Was this included in the docs? 
I searched before opening #1564 and did not find anything.

**Comment by TsakiDev** [comment]
@cephaspad

I added this and I did not have to remove Bootstrap from the project.
The suggested solution [here](https://github.com/ant-design-blazor/ant-design-blazor/issues/1483#issuecomment-834290531_) is not very efficient since many projects pay need a lot of refactoring in order to remove a dependency such as Bootstrap.

```css
.anticon > svg {
    vertical-align: baseline;
}
```
