### ISSUE TITLE
Add Colour Enum or Colour Picker component

### ISSUE THREAD

**Issue by MutatePat** [ant-design-blazor/ant-design-blazor#1508]
### Is your feature request related to a problem? Please describe.
I am trying to build a service which allows users to pick tag colours from a drop down. I need an enum of all available colours in case they change for the Tag component. 

### Describe the solution you'd like
A built in Colour picker or an enum of preset colour types.

**Comment by MutatePat** [comment]
> Thanks for suggestion @MutatePat ,
> 
> I think it is good to adding an Enum of preset color types. And use it as the parameter of Tag.

We would use OneOf or would we have a breaking change

**Comment by ElderJames** [comment]
Breaking change is fine, not very serious, but the benefits are many.

**Comment by MutatePat** [comment]
Please check the PR
