### ISSUE TITLE
Release through tagging

### ISSUE THREAD

**Issue by lindexi** [ant-design-blazor/ant-design-blazor#151]
用推 Tag 打包如何？就是我新建一个 Tag 就会触发 Action 自动构建，自动构建出来的 NuGet 包版本就是 Tag 号

这个方法的优势请看 [dotnet CBB 为什么决定推送 Tag 才能打包](https://blog.lindexi.com/post/dotnet-CBB-%E4%B8%BA%E4%BB%80%E4%B9%88%E5%86%B3%E5%AE%9A%E6%8E%A8%E9%80%81-Tag-%E6%89%8D%E8%83%BD%E6%89%93%E5%8C%85.html )

可以方便海量的开发者考古的时候找到源代码

**Comment by ElderJames** [comment]
cloase via #267 .
