### ISSUE TITLE
Table: filter dropdown menu item can not be selected/unselected by clicking the text area

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1519]
### Describe the bug

![动画237](https://user-images.githubusercontent.com/54608128/117989680-1e897a00-b36f-11eb-9761-1709c33f493b.gif)

**This issue only happens for blazor wasm.**

### Steps to reproduce (please include code)

https://antblazor.com/zh-CN/components/table#components-table-demo-filter
### Further technical details
- AntDesign Nuget Package version: 0.8.0

**Comment by anranruye** [comment]
It seems that this is already fixed

**Comment by ElderJames** [comment]
Fixed.
