### ISSUE TITLE
Setting AntDesign.Input component font color via the Style property is invalid

### ISSUE THREAD

**Issue by dawningzhang** [ant-design-blazor/ant-design-blazor#1525]
当AntDesign.Input 组件设置AddOnBefore后，通过Style属性设置颜色、字体大小等，不发生作用，去除<AddOnBefore>后正常

When the Input component is set `AddOnBefore`, setting the color, font size, etc. through the Style property does not work. But if remove `AddOnBefore`, it works normally.

![image](https://user-images.githubusercontent.com/64716352/118197508-ae1f4d80-b481-11eb-9eda-03e0f7079a79.png)

![image](https://user-images.githubusercontent.com/64716352/118197328-49fc8980-b481-11eb-9a5b-631f30eaa4f6.png)

**Comment by ElderJames** [comment]
Thanks for contacting us, @dawningzhang 

Please tell us that which version are you using?
