### ISSUE TITLE
What is TItem vs TItemValue from Select

### ISSUE THREAD

**Issue by Banyc** [ant-design-blazor/ant-design-blazor#1535]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

I try to change the label of an item without changing the item itself. The label is the property of the item.

```csharp
<Select @bind-Value="@this.SelectedGroup"
    Placeholder="Select a group..."
    Style="width: 240px;"
    TItemValue="RuleGroup" 
    TItem="RuleGroup">
    <SelectOptions>
        @if (this.RuleEngineSettings != null && this.RuleEngineSettings.RuleGroups != null)
        {
            @foreach (var item in this.RuleEngineSettings.RuleGroups)
            {
                <SelectOption TItemValue="RuleGroup" TItem="RuleGroup" Value=@item Label=@item.GroupName />
            }
        }
    </SelectOptions>
</Select>
```

But when the label (`item.GroupName`) changed, the display of `Select` has not been changed, even after `StateHasChanged` fired. I don't find any helpful explanation on what is the difference between "value", "item", and "label" in the doc.

When doing a `foreach` loop, I can set `@key` to enhance performance:

```csharp
<li class="card" @key=person>
```

But what in `Select` is equivalent to `@key`?

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

Clarify `TItem` and `TItemValue` from `Select` in the doc.

### Additional context

currently no.

**Comment by ElderJames** [comment]
Thanks for contacting us @Banyc ,
Please try to add @key at the each `SelectOption`.
