### ISSUE TITLE
Immediately Changing Value after item is modified in Select

### ISSUE THREAD

**Issue by Banyc** [ant-design-blazor/ant-design-blazor#1536]
### Describe the bug

```csharp
RuleGroup ruleGroupToSelect = null;
ruleGroupToSelect = new()
{
    GroupName = this.NewGroupName
};
this.RuleGroups.Add(ruleGroupToSelect);
this.SelectedGroup = ruleGroupToSelect;
```

Where `this.SelectedGroup` has already bound to `Value` of `Select`. `SelectOptions` loop through the list `this.RuleGroups`. After the last assignment, `Select` shows nothing.

### Steps to reproduce (please include code)

Do something as described in the code above.

### Exceptions (if any)

no.

### Further technical details
- AntDesign Nuget Package version - **0.8.0**
- Include the output of `dotnet --info` - **.NET 5.0**
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - **not relevant**.

**Comment by anddrzejb** [comment]
I have added myself, as a reminder. I am away now, so I will have a look at this once I come back.

**Comment by anddrzejb** [comment]
@Banyc Could you possibly post a minimal self-contained repro?

**Comment by Banyc** [comment]
@anddrzejb here is the repo

<https://github.com/Banyc/AntSelectTest/tree/master>

Sorry for the long gap since I was busy several days ago XD.

**Comment by anddrzejb** [comment]
@Banyc Thanks for waiting! 
I haven't really looked deep into this issue, but if you switch this:
```csharp
    private void OnAddItem()
    {
        var newModel = new MyModel()
        {
            Name = this.NewName
        };
        this.Models.Add(newModel);
        // make the select display the new item
        this.SelectedModel = newModel;
    }
```
with this
```csharp
    private async Task OnAddItem()
    {
        var newModel = new MyModel()
        {
            Name = this.NewName
        };
        this.Models.Add(newModel);
        await Task.Yield();
        // make the select display the new item
        this.SelectedModel = newModel;
    }
```

It should start working. Obvious first impression is that there is an async operation pending in-between your synchronous changes. Since async operation has no chance of completing, second operation (assignment of the new value), does not seem to work. I will have a closer look, but if you need it quickly, this is the immediate solution. Mind, this might be final as well, but I will get back to you on this subject.

**Comment by Banyc** [comment]
It seems that the UI thread is a single thread. When calling `await Task.Yield()`, the following code will not run until the tasks with high priority are done.

**Comment by anddrzejb** [comment]
I haven't really started working on this (I am pretty swamped lately), but the behaviour is not really surprising. `Select` is async when it comes to populating its content (the select items). The selected value has to exist in the list of select item. Your original code was synchronous. I am afraid this issue might not be fixable, however I do plan to have a more thorough look.
