### ISSUE TITLE
(Documentation) Issue with component URL Routing

### ISSUE THREAD

**Issue by ske66** [ant-design-blazor/ant-design-blazor#154]
Some components docs don't show up when selected from the side menu. This could be due to the route of the component razor page.

The URL of "broken" components is usually pre-pended with the /components/ route. Clicking on an item with this route will result in no component being shown.

**Steps To Reproduce**
1. Go to the GitHub hosted docs, click on a component from the side menu.
2. If the URL contains "/components" then the component razor template won't be displayed. (e.g. Button)
3. Else the razor template will load.

**Comment by ske66** [comment]
I'm starting to dig more into the project because I really want to help with the documentation side of this. Just trying to work out some of the kinks so I can get a good foothold

**Comment by ElderJames** [comment]
Thank you for your feedback. @ske66 
We are working on the document migration, changing the previous crude example into a document consistent with the official ant design document.
The pages under the `/components` path are all new documents, and we are migrating all the components here.

**Comment by ElderJames** [comment]
Hi! We fixed all the demos! Please check it again.
