### ISSUE TITLE
Add a Boolean to disable InputNumber increment

### ISSUE THREAD

**Issue by MutatePat** [ant-design-blazor/ant-design-blazor#1546]
### Is your feature request related to a problem?
We should add a Boolean to disable the up and down arrows found in the InputNumber component. Sometimes when inputting a number, the number is non sequential ( e.g order numbers), so these arrows are never used.

**Comment by anranruye** [comment]
Maybe the user can use `<Input Type="number" @bind-Value="@number" />` instead?

**Comment by anddrzejb** [comment]
Why don't we expand this and add ability for the consumer to choose to hide:
- up arrow
- down arrow  

On top of that, maybe we could also expose a callback to let the consumer override the step with other than pre-set value if current logic requires it?

**Comment by ElderJames** [comment]
I agree with @anranruye , The `InputNumber` is just two buttons more than `Input`, so you can just use Input if you don't need them.

**Comment by lettuceDestroyer** [comment]
Can we revisit this idea? Since the `InputNumber` has attributes such as `Min` and `Max`, which the `Input` do not have, I think it would make sense to add a boolean to disable/hide the increment arrows.
