### ISSUE TITLE
InputNumber: Should disable invalid characters when not use Formatter

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1548]
### Describe the bug

![image](https://user-images.githubusercontent.com/54608128/118584476-97eaf780-b7c9-11eb-8e87-f3cc772e361b.png)

I think we should forbid the user to input non-number characters when `Formatter` and `Parser` are not used, like the raw html `<input type="number" />` element or Microsoft `InputNumber` component(which use raw html input number).

However, I noticed that the react component has the same behavior. So maybe we should at least provide a parameter to allow the users to decide which behavior they like?

update: We can allow the user to provide a list of acceptable characters so that we can also limit the input characters when `Formatter` and `Parser` are used. Even more, we can implement this feature for the common `Input` component.

### Steps to reproduce (please include code)

https://ant-design-blazor.gitee.io/en-US/components/inputnumber#components-inputnumber-demo-Basic
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Have been fixed in currently version.
