### ISSUE TITLE
Locale DataPicker error

### ISSUE THREAD

**Issue by carrisian** [ant-design-blazor/ant-design-blazor#1551]
Hello. The DatePicker control is not translated correctly. Also, I can't get the first day of the week to set in Monday and in the example doesn't work correctly. The days of the week always are in English. The word "now" is only translated if I don't show the time in another case doesn't work. This control is necessary for many applications. Is there any chance that You can fix it?

Thank you in advance

**Comment by anddrzejb** [comment]
I believe the first day issue was discussed in PR #1054. But this was never addressed again I think. We could probably discuss this again and see if it is going to solve your problem. 
Could you be more specific when you wrote
> The DatePicker control is not translated correctly.

Which controls? A number of controls are actually translated using json files in [here](https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/locales). If there is a translation missing in your language, then you could submit a PR. Use either `en-US` or `zh-CN` for reference (not your desired language, as it may not have all properties).

**Comment by ElderJames** [comment]
Hey @Alexbits , would you be interested in taking a look at this question?
