### ISSUE TITLE
Table - Multiselection (Server Side)

### ISSUE THREAD

**Issue by mkalinski93** [ant-design-blazor/ant-design-blazor#1554]
Hey,

I just wanted to get to know how I can manage server side Multiselection. In my current project, I would have thousands of rows and I don´t want to consume them all at once. The current approach is to use our backend for paging and querying data on demand. We plan to implement filtering by using Query parameters which will be attached to the resource url. The backend can translate these strings as an IQueryable and pulls just demanded data from the datastore and sends them back as a paginated list object.

Let´s say the user queries 100 items in total, which then gets paginated by 25 items per page. The user just receives 25 items plus the information that he has 4 pages in total. Now the user wants to select all 100 items. As we´ve just pulled 25 items for the first page, we just have these 25 items selected instead all 100.

For example, you would like to delete all 100 items you have queried, but actually you have just got 25 keys for page 1. When I submit the deletion to the server, it would just receive 25 keys instead all 100.

Of course, we can say "you can have an extra button and let the server know that you want to delete every item. No keys needed at all." - I would agree to that, but it also eliminates the power of selection. When you have 100 items, but you just want to delete 98 of them, you should be able to select them at first place. Also, deleting page by page can be exhausting when you have plus 20 pages.

I´ve just got 3 options in my mind to help me out with this scenario.

Option 1

I extend my custom PaginatedList Object with an array "Keys" which holds all keys, regardless of paging.
I pull the first page with 25 items and have in total 100 keys in the array.  In my case, my primary keys are guids. This would work but can also produce massive overhead when I ignore all filters and query like 30.000 rows. It would then have 25 items, plus 30.000 guids each time I query the API.

Option 2

When the user checks the "select all" box in the table, an event (OnSelectAll) is triggered and allows to manually retrieve and set the selected keys. This is ideal because it would reduce the overhead and just gets executed on demand.

Option 3

Extend the Table with a property "KeyFunc". This function will be automatically executed when the user checks the "select all" box. The function must return an array of keys (string).
Having this property could help a lot of people dealing with my problem. It gets triggered when the keys need to be retrieved from the datastore and automatically set the selectedkeys property. Also, when the property is null, it behaves like the current implemented behavior. I would check this out on my own and try to PR this feature if it sounds good for the community.

Probably this has been discussed before, but I was not able to find resources on Github.
I am really looking forward for your opinions and ideas. 

thank you in advance.

best regards

**Comment by anranruye** [comment]
It seems that Option 3 will have the same issue as Option 1?

**Comment by mkalinski93** [comment]
I don´t think so. Option 3 is very close to option 2 and as I´ve found out, it is similar to AntDesign itself.
https://ant.design/components/table/#rowSelection

Here we have the rowSelection property which does have a callback "onSelectAll". This is exactly what option 3 should be like.
The difference between 2 & 3 is that you can either have, for instance,  a Func<T,T1> delegate whereas option 3 has an EventCallback you can listening to and handle selection state on your own.

In the end, the main benefit should be that you load the selected keys on demand and not unnecessarily with each call to the Server.

**Comment by anranruye** [comment]
@mkalinski93 Ok, it sounds good to me.

**Comment by mkalinski93** [comment]
I have looked a few things in the table component and will try to PR the option with the Function delegate. This way, we can directly pull keys from the data store and let them be set in the table component. This function should only be called when the selector is a checkbox and we check the box. If an empty collection is returned, the standard behavior should work as a fallback.

**Comment by mkalinski93** [comment]
Bad news :/ 

I have worked on a solution for this scenario but it seems to be more difficult, as I´ve assumed. 
I have implemented the Function and the initial selection (when you check the check all box) just works fine. But paging, filtering etc will purge the selection state entirely. The problem relies on the component itself that it makes use of the local datasource which you can bind directly. For a remote scenario, this datasource will be overwritten over and over againg and purges the state, too. In order to set and persist the state we maybe need to have a local "selectedKeys" store from which the component can rely on. I´ve found a similar implementation in the Table<TItem> implementation "_dataSourceCache", but as I´ve said, this cache will gets cleared under certain conditions. If we would have a selectedKeys store, the component could handle both ways, local and remote. If you check a row, it would add the key to the store. If you check all rows, it will invoke the function and adds the keys to the keystore. If the function is null, it just sets all available keys from the local datasource to the keystore.

**Comment by anranruye** [comment]
@mkalinski93 I think `SelectedKeys` is necessary for this feature. And, there should be a mechanism to identify the key property of the datasource items.

**Comment by ElderJames** [comment]
Hi @mkalinski93 , would you be interested in helping us improve it?

**Comment by mkalinski93** [comment]
Hey,

I would like to, but I can´t promise due to my current time schedule.
What I was thinking about is to have a general discussion about remote datasources, because this is just tackling smaller parts, but it´s not focusing the whole problem at all.

So in order to help out, we need to make sure what features we want, how we implement them, how we reduce the impact of breaking changes and how the table should behave under given circumstances. Currently, the Table works very good with local datasources. Really, I enjoy using it. 

Overall we need to specify the following topics

- Selection
- Filtering
- Paging
- Ordering

Also, I would love to get any feedback or ideas from others, because I think that it´s not a good place to bad practice a lot. In my opinion, a Table becomes most relevant to business solutions and makes it mandatory to work with remote/local datasources. A good Table will also draw attention, too. 

In fact, we can fix them one by one, but as I´ve said, with my current time schedule, I can´t promise to implement it in the near future.

**Comment by ElderJames** [comment]
Hello @mkalinski93 , for now we have fix the selection feature. Please try.

**Comment by mkalinski93** [comment]
thank you for the implementation. I appreciate your work 👍
