### ISSUE TITLE
Where can I ask questions?

### ISSUE THREAD

**Issue by wzxinchen** [ant-design-blazor/ant-design-blazor#156]
社区中将发你的组件的相关提问，你不进来，没人可以回答

**Comment by wzxinchen** [comment]
有你的组件的提问，没人回答，我不care，我只管让更多的用户进来提问

**Comment by ElderJames** [comment]
Thanks for contacting us @wzxinchen .
Our team has been providing community support. Anyone with any questions can feel free to open an issue, or contact us with the ways written in the ["Community Support"](https://github.com/ant-design-blazor/ant-design-blazor#-community-support) section of the README.

**Comment by Epictek** [comment]
The slack link seems to be dead?

**Comment by ElderJames** [comment]
Thank you for contacting us @Epictek .
Try to use this [link](https://antblazor.slack.com/join/shared_invite/zt-etfaf1ww-AEHRU41B5YYKij7SlHqajA#/) please.
