### ISSUE TITLE
Get Table filter criterias

### ISSUE THREAD

**Issue by mkalinski93** [ant-design-blazor/ant-design-blazor#1561]
I wonder if it would be possible to get the specified filter criterias from the table.
Right now, all I have is the QueryModel which contains the Expression and Queryable objects.

For a remote datasource, it would be nice to have the exact filter criterias such as fieldname, criteria (Contains, StartsWith...), conditions (AND, OR) and value.

These filter criterias could be send to the remote datasource and directly be used server side.
Or do you have other ideas how I could set client side filters which gets executed on server side?

best regards

**Comment by anranruye** [comment]
Thank you for contacting us @mkalinski93 .

In fact, these filter criterias exist, but they are internal properties. Currently you can get them by reflection. See https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/table/TableFilter.cs to learn more about the implementation for `TableFilter` class.

We plan to refactor this part and give users the ability to take full control of the filter programmatically in the future.

**Comment by mkalinski93** [comment]
That sounds great! Thank you.

**Comment by emimontesdeoca** [comment]
@anranruye looking forward to it! 

I'm in the same boat as @mkalinski93, I'd like to use the filters in the QueryModel too ☺!

**Comment by mkalinski93** [comment]
> @anranruye looking forward to it! 
> 
> I'm in the same boat as @mkalinski93, I'd like to use the filters in the QueryModel too ☺!

That's nice to hear that other people share the same idea. Can I ask you what type of expression parser you are using? For my backend, I've chose dynamic LINQ. I will translate the user filter to a query string which then gets evaluated at the backend.

**Comment by emimontesdeoca** [comment]
> > @anranruye looking forward to it!
> > I'm in the same boat as @mkalinski93, I'd like to use the filters in the QueryModel too ☺!
> 
> That's nice to hear that other people share the same idea. Can I ask you what type of expression parser you are using? For my backend, I've chose dynamic LINQ. I will translate the user filter to a query string which then gets evaluated at the backend.

Exactly the same one, I'm passing the queryModel to the ServiceLayer, and making the query in there!

Here's an example of a select for all the users

```csharp
/// <summary>
/// Get a list of User
/// </summary>
/// <param name="queryModel">QueryModel object</param>
/// <returns>List<User></returns>
public async Task<List<User>> SelectAllAsync(QueryModel queryModel)
{
    try
    {
        var query = hyphenContext.Users
            .AsNoTracking();

        // Where

        // Sort
        List<string> orderByItems = new List<string>();
        foreach (var item in queryModel.SortModel.Where(x => x.Sort != null).ToList())
        {
            var field = item.FieldName;
            var orderingValue = item.Sort.ToLowerInvariant() == "ascend" ? "ASC" : "DESC";

            orderByItems.Add($"{field} {orderingValue}");
        }

        var orderByString = $"{string.Join(", ", orderByItems)}";

        if (!string.IsNullOrEmpty(orderByString))
        {
            query = query.OrderBy(orderByString);
        }

        // Skip
        query = query.Skip((queryModel.PageIndex - 1) * queryModel.PageSize);

        // Take
        query = query.Take(queryModel.PageSize);

        var result = await query.ToListAsync();

        return result;
    }
    catch (Exception e)
    {
        return new List<User>();
    }
}
```

It's still experimental. I'm trying to find the best possible way in terms of performance.

**Comment by mkalinski93** [comment]
Impressive! It's almost the same implementation as I've done so far. I have created a base controller so my actions just passing an IQueryable to an extension method and return a PaginatedList object that has all important properties. I have also created an issue at the library for StartsWith/EndsWith/IsNull/IsNotNull support. If that's possible, it should fit every criteria antblazor table has to offer. Man I would love to see a  ToQueryString extension method from antblazor for dynamic LINQ 🤣 but it's unlikely this could become a standard.

**Comment by anranruye** [comment]
@mkalinski93 I'm using an OData backend and I have written a `ToQueryString` extension method for OData. I'm not sure whether it's possible to have a `ToQueryString` method for dynamic LINQ. As you said, users may have different backend models.

@emimontesdeoca How do you pass queryModel to the Service? I'm afraid there may be problems for serialization and deserialization.

**Comment by emimontesdeoca** [comment]
@anranruye the service class itself is another class in the Blazor Server application, you can see in the example that I shared  before that it passes the QueryModel directly:

```csharp
/// <summary>
/// Get a list of User
/// </summary>
/// <param name="queryModel">QueryModel object</param>
/// <returns>List<User></returns>
public async Task<List<User>> SelectAllAsync(QueryModel queryModel)
{
        // Code
}
```

It gets called from the razor component that has injected that service:

```csharp
public async Task OnChange(QueryModel<User> query)
{
    // Set table variables
    PageIndex = query.PageIndex;

    // Get data
    Total = await userService.SelectAllCountAsync();
    UsersList = await userService.SelectAllAsync(query);

    // Remove loader
    Loading = false;
    StateHasChanged();
}
```

**Comment by mkalinski93** [comment]
I have used odata at first, but when I want to have an API for my frontend and also as a remote API Service, I felt odata was not a comfortable choice. I've ran into a lot of issues which were not documented, the edm concept sometimes worked but then didn't for no reason. Ahh. I like odata in general but I think it's not polished enough to use it in my scenario. I've also always had the feeling that the odata client is a hungry beast that consumes the very last drop of memory. I will not say odata is bad, it clearly isn't. But with technology like odata you can mess up things pretty fast. That's why I've decided to come up with dynamic linq becauss I can take full control of the query parsing and keep technology overhead to a bare minimum. If my final results turn positive, we still can consider to have a nuget package that has a ToQueryString method and some other helpers.

**Comment by mkalinski93** [comment]
> @anranruye the service class itself is another class in the Blazor Server application, you can see in the example that I shared  before that it passes the QueryModel directly:
> 
> ```csharp
> /// <summary>
> /// Get a list of User
> /// </summary>
> /// <param name="queryModel">QueryModel object</param>
> /// <returns>List<User></returns>
> public async Task<List<User>> SelectAllAsync(QueryModel queryModel)
> {
>         // Code
> }
> ```
> 
> It gets called from the razor component that has injected that service:
> 
> ```csharp
> public async Task OnChange(QueryModel<User> query)
> {
>     // Set table variables
>     PageIndex = query.PageIndex;
> 
>     // Get data
>     Total = await userService.SelectAllCountAsync();
>     UsersList = await userService.SelectAllAsync(query);
> 
>     // Remove loader
>     Loading = false;
>     StateHasChanged();
> }
> ```
> 
> EDIT: @mkalinski93 @anranruye  how do you handle the table loading view? I'd like to have some kind of skeleton for the table, is it possible?

The Table should have a loading property. Maybe not the result you would like to achieve, but it's a good start. My BaseComponents does also have a Loading property which you can bind to the table. That way, data will be shown first when the request is finished.

For such a customized skeleton purpose, a SkeletonTemplate fragment would be nice. But this should be a different issue and not discussed here.

**Comment by anranruye** [comment]
@mkalinski93 The `Table` component does have a `Loading` property. But the loading appearance can not be customized yet. A similar issue is #1533 , but they are not exactly the same。

**Comment by Martin-Pucalka** [comment]
> @anranruye I'm using an OData backend and I have written a `ToQueryString` extension method for OData. I'm not sure whether it's possible to have a `ToQueryString` method for dynamic LINQ. As you said, users may have different backend models.

I like the idea of ToQueryString` extension method for OData. Do you have any sample code of ant-blazor filter criterias to Odata query?
