### ISSUE TITLE
Icons do not appear correctly when adding Bootstrap css to the project.

### ISSUE THREAD

**Issue by TsakiDev** [ant-design-blazor/ant-design-blazor#1564]
There is a conflict with Bootstrap css and AntDesign css.
When adding Bootstrap css to _Host.cshtml the icons go lower.

![image](https://user-images.githubusercontent.com/20267678/119143468-4dc77780-ba50-11eb-8fd6-68faca22056d.png)

It is also replicated in the zipped project.

[WebApplication1.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/6522760/WebApplication1.zip)

**Comment by MutatePat** [comment]
I believe this is a known shippable

**Comment by ElderJames** [comment]
Thanks for contacting us @TsakiDev , please adjust the CSS yourself.

**Comment by TsakiDev** [comment]
Where can I find info on the issue?

**Comment by TsakiDev** [comment]
Btw, I added this and I did not have to remove Bootstrap from the project.
The suggested solution [here](https://github.com/ant-design-blazor/ant-design-blazor/issues/1483#issuecomment-834290531_) is not very efficient since many projects pay need a lot of refactoring in order to remove a dependency such as Bootstrap.

```css
.anticon > svg {
    vertical-align: baseline;
}
```

**Comment by MutatePat** [comment]
> Btw, I added this and I did not have to remove Bootstrap from the project.
> The suggested solution [here](https://github.com/ant-design-blazor/ant-design-blazor/issues/1483#issuecomment-834290531_) is not very efficient since many projects pay need a lot of refactoring in order to remove a dependency such as Bootstrap.
> 
> ```css
> .anticon > svg {
>     vertical-align: baseline;
> }
> ```

I am of the belief that you should stick with either bootstrap or ant design, as they are conflicting standards and could harm your future development trying to support both( as well as dependency size).

I'm glad you found a solution to your problem.

**Comment by anddrzejb** [comment]
I agree with @MutatePat. But I also think we should not completely abandon developers in need. Maybe we should have a wiki page that will (hopefully) gradually grow with some details on how to work with projects that use AntDesign & any other css framework. Without any guarantees of course.

**Comment by TsakiDev** [comment]
@MutatePat  @anddrzejb
I completely agree that since they are conflicting there should be only one.
But, for example in my project I discovered Blazor implementation of Ant Design waaaay later in the development and I want to have a migration period where both libraries co-exist, for now. I know it's not optimal.
