### ISSUE TITLE
ExpandAll table tree data

### ISSUE THREAD

**Issue by Demonell** [ant-design-blazor/ant-design-blazor#1566]
Is there a way to call ExpandAll for table tree data?
It would be best if I had an option to expand all tree on init.

Like show expanded tree data when user first enter page with table.
![Like this](https://i.ibb.co/CVMY5v0/photo-2021-02-04-20-05-38-Copy.jpg)

**Comment by ElderJames** [comment]
Thanks for contacting us @Demonell .

A Parameter `DefaultExpandAllRows`  is need.

**Comment by nikolaykrondev** [comment]
Hi @ElderJames , do you have any ETA for this property or roadmap for the future releases?

**Comment by ElderJames** [comment]
Hello @nikolaykrondev , we're not working on it yet. 
But this is not a difficult feature, so if you are interested, feel free to give a hand!

**Comment by henrikwidlund** [comment]
I will work on this, PR coming soon.

**Comment by ElderJames** [comment]
@henrikwidlund Cool, looking forward that.
