### ISSUE TITLE
Table 'Filters' not loaded with async datasource

### ISSUE THREAD

**Issue by mkalinski93** [ant-design-blazor/ant-design-blazor#1570]
The pre defined Filter options is missing when I load data from a remote datastore
![image](https://user-images.githubusercontent.com/64005967/119515848-8039e300-bd76-11eb-95a6-6e6e4d9b26e0.png)

The issue seems to be that the component receives an empty array of TableFilter<TData> which **later** gets populated. The filter will not appear

![image](https://user-images.githubusercontent.com/64005967/119516167-cd1db980-bd76-11eb-9b76-117b3d659a91.png)

### Steps to reproduce (please include code)

- Create a table component
- Create a remote datasource (such as REST)
- Load data from the REST client in the "OnInitializedAsync" method
- Set TableFilter property from the async loaded collection

The filter will not appear.

How to overcome this error:

I have a "ComponentLoader" component which renders the child content first, when everything is loaded. 
Bascially it´s a wrapper for "if IsLoaded == True then RenderContent()" but this time, the Table will get the TableFilter array with values and the filter appears as it should be. Now here´s the thing, you can´t wrap the whole table into a "IsLoading" condition because you would loose the whole table state when the component is removed from the DOM. Instead, I would suggest to use a FiltersChanged event and have a binding on the Filters property. 

EDIT

I´ve found out that this also solves this problem 

```csharp
private TableFilter<string>[] _categories = new TableFilter<string>[]{new()};
```
The TableFilter should not be null or empty

**Comment by ElderJames** [comment]
Thanks for contacting us @mkalinski93 
So, has this issue been resolved? Or does it need some improvement?

**Comment by mkalinski93** [comment]
Overall I think it just needs a mention in the docs. This issue still can be closed. Thanks :)
