### ISSUE TITLE
Enable AOT in demo site

### ISSUE THREAD

**Issue by newbe36524** [ant-design-blazor/ant-design-blazor#1572]
blazor WebAssembly AOT now is available, please apply it on the demo site of this project.
I will take a few days on this work.

**Comment by MutatePat** [comment]
We should host AOT separately so we can compare

**Comment by newbe36524** [comment]
Now, there is a issue about "There will be a exception when install AOT workload in github action" https://github.com/dotnet/runtime/issues/53409

I think we should try this feature if pre5 published.
