### ISSUE TITLE
NET MAUI support

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1574]
Is a NET MAUI support planned?

Thanks

**Comment by ElderJames** [comment]
Thanks for contacting us @true-perfect-code 

We have no plans for the time being, but are open to discussion. 
Do you have any suggestions, please? For example, what do we need to do to support the MAUI?

**Comment by true-perfect-code** [comment]
Microsoft has some big plans with Blazor. With NET Core 6 it should be possible to create both a desktop and a web application with Blazor (according to Microsoft already possible with Preview 5).
If I understood correctly, this should also work on all other systems (Windows, Mac, iOS and Android) by using the BlazorWebView component. According to Microsoft, the main focus for .NET 6 is on desktop scenarios.

Source: [https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/ ](url)

It would be interesting to see if a desktop Blazor app with Ant integration works on Windows Desktop or macOS. This would require an official description of the Ant community (similar to what is now available for the normal Blazor application on [https://antblazor.com/en-US/docs/introduce](url) ).

Regards

**Comment by mattd73uk** [comment]
I have started using Ant Design Blazor components in a MAUI Blazor app.  Just dropped in a few components and no issues.  To OP, I believe the idea is that, within the MAUI BlazorWebView, things should work as within a Blazor web application.  Can't this issue be closed and any issues with components operating within the MAUI BlazorWebView (if any are identified) be raised & prioritised accordingly?

**Comment by ElderJames** [comment]
@mattd73uk Thank you for trying out this component library in MAUI. 

If you meet any issue, please create a separate issue.
And if you have time, you are welcome to help us with some minor issues in MAUI.

**Comment by ElderJames** [comment]
For mobile, it's more about adapting for smaller screens. This requires, in addition to simple responsive handling, changes to the interaction of components. 

Currently we can only guarantee the responsive experience on large screens. This may not be sufficient for all experiences on smaller screens.

**Comment by true-perfect-code** [comment]
Thanks for the info.

Can you short describe how to use ANT in a Blazor desktop application? 

The opportunity to use Blazor in a Windows desktop application opens up unexpected possibilities. For example, for all future Blazor + ANT projects you can simply have a single code base for both Dektop and the web server application.

regards

**Comment by dennisrahmen** [comment]
@true-perfect-code

For now, you can just follow the [Getting Started](https://antblazor.com/en-US/docs/getting-started) in the docs.
I will add a new section to this for .NET MAUI since I am staring to use this myself with AntBlazor.

**Comment by true-perfect-code** [comment]
Thanks for the info. 

As I said, important would be to show how to integrate Ant component in a Windows desktop (using C# and Core 6 of course). Basically a short tutorial like it already exists for Blazor Server and Blazor WebAssembly.

Once again, it would really be a revolution if you could generate both a Blazor-Ant web project and a desktop Ant desktop project with one code base!

Thanks
perfect-code
