### ISSUE TITLE
Directives column appears in two namespaces.

### ISSUE THREAD

**Issue by Serge-N** [ant-design-blazor/ant-design-blazor#1576]
###  The bug
CS0104	'Column<>' is an ambiguous reference between 'AntDesign.Column<TData>' and 'AntDesign.Charts.Column<TItem>'

This happens when trying use ant-design-charts-blazor and ant-design-charts-blazor in the same project.

### Steps to reproduce 
Create any server Blazor server project that uses both of the above mentioned packages, after this, attempt to use the Table Component with a column property.

### Further technical details
- AntDesign Nuget Package version 0.8.1
- AntDesign.Charts Package version 0.2.1
- Blazor Server.
- Microsoft Visual Studio Community 2019 Version 16.10.0

**Comment by ElderJames** [comment]
Thanks for contacting us @Serge-N 
You can specify the namespace `<AntDesign.Column>`.

**Comment by Serge-N** [comment]
Thanks, <AntDesign.Column> seems to work . (VS 2019 V 16.10.0).

I had tried <AntDesign.Column> earlier and it did not seem to work (VS 2019 16.11.0 Preview 1.0).
