### ISSUE TITLE
Messages do not appear, possible MessageService misconfiguration?

### ISSUE THREAD

**Issue by borkes85** [ant-design-blazor/ant-design-blazor#158]
Hi!
I'm having trouble with messages component, I just created new wasm project from blazor template, added nuget dependency, and this simple code do not work in `Index.razor` page, message do dot raise:

```
@page "/"
@inject MessageService _messageService

<AntButton Type="primary" OnClick="OnClick">
    Display normal message
</AntButton>

@code{
    private void OnClick()
    {
        Console.WriteLine("onclick");
        _messageService.Info("This is a normal message");
    }
}
```
![image](https://user-images.githubusercontent.com/65708071/83035956-c31d8980-a042-11ea-9108-b56753eecae4.png)

Does it lack some configuration?

**Comment by ElderJames** [comment]
Thanks for contacting us @borkes85 .

I'm sorry, but one thing we missed is the need to add a container component named `<AntContainer />` in the `App.razor` component.
We are looking for a way to implement a global pop-up layer by injecting this component more elegantly. 
BTW, we are glad you're using our component library.

**Comment by borkes85** [comment]
thanks, @ElderJames
really great lib!

**Comment by ElderJames** [comment]
Thank you! @borkes85
