### ISSUE TITLE
OnClearSelected event for RangePicker

### ISSUE THREAD

**Issue by BadarAljahwari** [ant-design-blazor/ant-design-blazor#1582]
I am trying to handle the action when range picker cleared(by clicking x sign at end of the control) because I am using it as filter so when its cleared I need to update my records.

Thanks

**Comment by ElderJames** [comment]
Thanks for contacting us @BadarAljahwari 

Did you try to handle the `OnChange` event?

**Comment by BadarAljahwari** [comment]
Yes, Its firing after setting the date but it doesn't firing when cleared.
Other controls has special event for clear: "OnClearSelected"
