### ISSUE TITLE
Support DateOnly, TimeOnly in .NET 6 AntD

### ISSUE THREAD

**Issue by patrykgz** [ant-design-blazor/ant-design-blazor#1589]
### Is your feature request related to a problem? Please describe.

This would be helpful for DatePicker and RangePicker

### Additional context
https://www.stevejgordon.co.uk/using-dateonly-and-timeonly-in-dotnet-6

**Comment by anddrzejb** [comment]
I was thinking to propose the same thing. What I am afraid of, is that this will probably significantly increase the complexity of the components in question, which are already pretty complex. But I think such change will be inevitable.

**Comment by MutatePat** [comment]
> I was thinking to propose the same thing. What I am afraid of, is that this will probably significantly increase the complexity of the components in question, which are already pretty complex. But I think such change will be inevitable.

Wasn't DatePicker/RangePicker due for a re-write due to the performance issues? Or have I made that up?

**Comment by anddrzejb** [comment]
@Zonciu proposed that on discord. I haven't started working on this, I am not aware if he did. If I decide to attempt, I will definitely announce my plans and probably try to put the design idea under discussion.

**Comment by Zonciu** [comment]
I haven't done this yet, I've been very busy with my work this recent period😫
We can create a discussion to discuss the design details.

**Comment by mo3in** [comment]
Table doesn't show any thing when have a Property with type DateOnly.
```csharp
public class InventorySummeryDto
{
	public string Sku { get; set; }
	public int Qty { get; set; }

	public DateOnly? MinExpireDate { get; set; }
	public DateOnly? MaxExpireDate { get; set; }
}
```

**Comment by ElderJames** [comment]
Hi @Alexbits , could we support that?

**Comment by Alexbits** [comment]
> Hi @Alexbits , could we support that?

Hey @ElderJames. Probably. I have to look into this. Also, it would be nice to have DateTimeOffset support and proper time zone handling.

**Comment by ElderJames** [comment]
> Also, it would be nice to have DateTimeOffset support and proper time zone handling.

Strongly agree.

**Comment by ElderJames** [comment]
Hello @Alexbits , are there any progress?

**Comment by Alexbits** [comment]
> Hello @Alexbits , are there any progress?

No progress yet
