### ISSUE TITLE
Documnetation issue with Multi-Language

### ISSUE THREAD

**Issue by Zhuangkh** [ant-design-blazor/ant-design-blazor#159]
I know the project only supports Simplified Chinese and English for now. However, if the browser does not use these two languages by default (e.g. Traditional Chinese), it will return unexpected pages, and some components will get 404 errors.

Does the project plan to support more languages or fix this routing error?😍

**Comment by ElderJames** [comment]
Thank you for reporting this issue! @Zhuangkh 
The correct behavior is to default to English for unsupported languages. I think there's something wrong

**Comment by ElderJames** [comment]
Before fixing this issue, you can fix it by clicking the language switch button in the upper right corner.

**Comment by ElderJames** [comment]
fixed via #470
