### ISSUE TITLE
DatePicker cannot input using keyboard

### ISSUE THREAD

**Issue by shirleen1234** [ant-design-blazor/ant-design-blazor#1590]
### Describe the bug

The date doesn't change when input by using keyboard. but it works by selecting date from the picker using mouse.

### Steps to reproduce (please include code)

```
<FormItem Label="Birth Date">
  <DatePicker @bind-Value="@context.BirthDate" DefaultValue="DateTime.Now" Format="yyyy-MM-dd" />
</FormItem>
```

### Further technical details
- AntDesign Nuget Package version 0.8.1

**Comment by anranruye** [comment]
@shirleen1234  Thanks for contacting us.

Do you meet the same problem described in #1568?

**Comment by shirleen1234** [comment]
I'm using the same format (yyyy-MM-dd) for both displaying and inputting.
I found that @bind-Value might be the problem as `<DatePicker TValue="DateTime?" DefaultValue="new DateTime(2015, 1, 1)" Format="yyyy/MM/dd" />` (from AntDesign docs) does work.

**Comment by anranruye** [comment]
Confirmed this is a bug. @anddrzejb Do you have any idea why this happens?

**Comment by anddrzejb** [comment]
Unfortunately I will be able to have a look at this on Monday. Currently I am away. Sorry...

**Comment by anranruye** [comment]
Also found that this only happens when the DatePicker is inside a Form.
