### ISSUE TITLE
tree checkbox default selection cannot be modified 

### ISSUE THREAD

**Issue by SoaSoftNet** [ant-design-blazor/ant-design-blazor#1599]
After tree is selected by default, users cannot uncheck it in the front-end.

**Comment by ElderJames** [comment]
Hi @SoaSoftNet ，have we fixed these issue you closed？

**Comment by SoaSoftNet** [comment]
![image](https://user-images.githubusercontent.com/30250585/202074555-8b516009-a354-45e8-8999-c210871032b7.png)
