### ISSUE TITLE
It seems two tone color icon is not working

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#1600]
I was trying to set a two tone color for an icon. However, it doesnt seem to apply the twotone color.

`<Icon Type="check-circle" Theme="twotone" TwotoneColor="#3bc45a" />`

**Comment by ElderJames** [comment]
Thanks for contacting us @ldsenow 

We haven't implemented ant design's color scale algorithm yet, so we can't use one color value to generate two colors.

**Comment by ldsenow** [comment]
Anything i could help with this? Or it is already a plan for it?

**Comment by ElderJames** [comment]
No plan yet. Could you please try to implement it with two color parameters? Use `Color` and `SecondColor`.

**Comment by ldsenow** [comment]
Sure. I guess It is a temporary solution for now until u guys get the color scale working.

**Comment by anddrzejb** [comment]
@ldsenow what is your idea of a temporary solution?

**Comment by rqx110** [comment]
this feature is take too long time to implement. and if it not implement yet, why list on the web site? https://ant-design-blazor.gitee.io/zh-CN/components/icon#components-icon-demo-two-tone

👎

**Comment by ElderJames** [comment]
@ldsenow @anddrzejb This issue has been solved !
