### ISSUE TITLE
Is it possible to run AntDesign on Blazor server-side?

### ISSUE THREAD

**Issue by BrunoBlanes** [ant-design-blazor/ant-design-blazor#1604]
I am working on a Blazor WASM application that requires some pages to be on the server side, how can I make those match the UI of the WASM part using AntDesign?

**Comment by ElderJames** [comment]
Thanks for contacting us @BrunoBlanes 

Please follow the readme..

**Comment by BrunoBlanes** [comment]
Hi, I did, but Blazor server-side runs on ASP.NET and uses .cshtml files, I didn't see any of that on your README file.

**Comment by anddrzejb** [comment]
You shouldn't have any issue using the lib on server side. Indeed, `_Hosts` file is a `cshtml`, but that is the only one. The rest you can put in `Pages/` folder and user standard blazor razor components.

Once you manage to have a working solution (with help from AntBlazor community if needed), I'd like to encourage you to help us out fixing our docs, so your issue gets covered.

**Comment by BrunoBlanes** [comment]
I kinda wanted to use AntDesign on ASP.NET Core Identity. Since those are all razor pages, AKA `.cshtml`, they can't run razor components as you would a `.razor` file.
I think I could get Blazor server-side to also accept razor components with some configuration changes, I don't think it would be the smartest thing to do though. In fact, I am looking for some input on this.
Anyway, I'd be glad to help with the docs once I'm more familiar with the project.

**Comment by anddrzejb** [comment]
So you do not really want a blazor server, but you would like to use razor components in an asp.net core mvc application? Please correct me if I am wrong.

**Comment by BrunoBlanes** [comment]
That's correct, I guess.

**Comment by BrunoBlanes** [comment]
I mean, it is Blazor WASM, but server-side.

**Comment by anddrzejb** [comment]
I know about the following deployment models for blazor:
- wasm (you can also incorporate singal-r here to connect to existing server-side or mvc or etc)
- server-side
- hosted

Can you in detail describe what are you trying to achieve? You mentioned identity, but normally, I think, in such instance you could use IdentityServer model or similar (so, identity is treated as kind-of a microservice).

**Comment by BrunoBlanes** [comment]
It is a hosted Blazor WebAssembly project, you can check my repo if you want: https://github.com/BrunoBlanes/Average-CRM

**Comment by BrunoBlanes** [comment]
I am using Identity Server, on the backend and I scaffolded de UI so that I can use my on layout and I wanted to incorporate AntDesign into that.

**Comment by michaelhofer** [comment]
@BrunoBlanes Did you manage to get that to work? We had to embed the AntBlazor components in classic Razor MVC Views too (Blazor Serverside) and this is running very well. If you still require some information, I can show you an example.

**Comment by BrunoBlanes** [comment]
Oh pleeease @michaelhofer, I'm still pulling my hairs off.

**Comment by michaelhofer** [comment]
@BrunoBlanes We managed to integrate blazor components in our MVC views by following these steps (step 1 and 2 is from the AntBlazor readme):

1. Register the AntBlazor services in the `Startup.cs` as follows:

```
services.AddAntDesign();
```

2. Add the static files to `_Layout.cshtml`:
```
<link href="_content/AntDesign/css/ant-design-blazor.css" rel="stylesheet" />
<script src="_content/AntDesign/js/ant-design-blazor.js"></script>
```

3. If you need the `AntContainer` for popups, notifications and so on, you need to add the following container at the bottom of your `_Layout.cshtml`:
```
<component type="typeof(AntContainer)" render-mode="ServerPrerendered"/>
```

4. Create a file called `App.razor` in your project root:
```
<Router AppAssembly="typeof(Program).Assembly" PreferExactMatches="@true">
    <Found Context="routeData">
        <RouteView RouteData="routeData"/>
    </Found>
    <NotFound>
        <h1>Page not found</h1>
        <p>Sorry, but there's nothing here!</p>
    </NotFound>
</Router>
```

5. Declare your imports in a neww file called `_Imports.razor`:
```
@using System.Net.Http
@using System.Net.Http.Json
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Web.Virtualization
@using Microsoft.JSInterop

@using AntDesign
```

**Comment by BrunoBlanes** [comment]
Oh yeah, I'm aware of this method... I was hoping this wasn't the only one.

**Comment by BrunoBlanes** [comment]
Let me ask you something, if I turn my Identity MVC UI pages into an API and do all the layout on the Blazor WebAssembly side, would that impose any risk to my application?
I've been afraid of not use MVC due to it being static files that run server-side versus Blazor Wasm that can be messed with on the browser, but do you think that there's a way to not use MVC and still be secure enough to log a user into my application?
