### ISSUE TITLE
Configprovider doesn't work in webassembly project

### ISSUE THREAD

**Issue by mhamri** [ant-design-blazor/ant-design-blazor#1605]
### Describe the bug

I am trying to make the components RTL, 

this is my app.razor

```razor
<ConfigProvider>
    <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>

</ConfigProvider>
<AntContainer />
```

and this is my **index.razor**

```razor
@page "/"


@Direction
<div class="">
    @*<Input Placeholder="large size" Size="@InputSize.Large" >
        <Prefix>
            <Icon Type="user" />
        </Prefix>
    </Input>*@
    te

</div>

@code{

    [Inject]
    public ConfigProvider ConfigProvider { get; set; }

    public string Direction => this.ConfigProvider.Direction;
}
```

this is a webassembly project, so the program.cs look like this 

```cs
public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");

            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
            builder.Services.AddAntDesign();

            await builder.Build().RunAsync();
        }
    }
```

it's a minimal repo trying to make the rtl works 

https://github.com/mhamri/antRtl-repo

### Exceptions (if any)
I'm getting this error

<pre>
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'ConfigProvider' on type 'TentCode.SheikhBahayi.Client.Pages.Index'. There is no registered service of type 'AntDesign.ConfigProvider'.
System.InvalidOperationException: Cannot provide a value for property 'ConfigProvider' on type 'TentCode.SheikhBahayi.Client.Pages.Index'. There is no registered service of type 'AntDesign.ConfigProvider'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
</pre>

### Further technical details
- AntDesign Nuget Package version
<pre>
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</pre>
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
<pre>
Microsoft Visual Studio Community 2019
Version 16.10.0
VisualStudio.16.Release/16.10.0+31321.278
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.10.525.31942
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.525.31942
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.525.31942
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.525.31942
Azure Functions and Web Jobs Tools

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debug Single Thread   2.0
This Visual Studio extension adds two shortcuts and toolbar buttons to allow developers to easily focus on single threads while debugging multi-threaded applications.

It dramatically reduces the need to manually go into the Threads window to freeze/thaw all threads but the one that needs to be followed, and therefore helps improve productivity.

Features:
- Restrict further execution to the current thread only. Will freeze all other threads. Shortcut: CTRL+T+T or snowflake button.
- Switch to the next single thread (based on ManagedID). Will change current thread and freeze all other threads. Shortcut: CTRL+T+J or Next button.

Dotfuscator Community Edition   6.3.0+8b29d6f4a2
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JetBrains ReSharper 2021.1.3   Build 211.0.20210525.202743
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2021 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.233
2.4.233

PhysicalSolutionFolders   1.0
Allows for association of solution folders with physical folders (relative or absolute). Solution folders are then synchronized to match their physical folder counterparts when the invokes the synchronization command. Folders are associated per solution. Folders can be synchronized en masse or individually.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SoftwareCoPackage Extension   1.0
SoftwareCoPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62105.04180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.10.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VS Diff   2.1.14
Another open source Visual Studio extension that makes file/code comparison more easily.

Word Highlight With Margin Extension   1.0
[VS2017, VS2019] Highlight all occurrences of a selected word and display carets on the enhanced vertical scrollbar at the right margin.

Xamarin   16.10.000.228 (d16-10@1c8354c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.1 (d16-10/22fc2b3)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.1 (fe0e2c518)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</pre>

**Comment by anranruye** [comment]
@mhamri Thanks for contacting us.

You can use `[CascadingParameter] public ConfigProvider ConfigProvider { get; set; }`.

**Comment by mhamri** [comment]
thanks @anranruye, 

yes you are right, but how do we set the RTL in the app start? in app start we only have access to the `ConfigService` but current implementation now is that we have to call `ChangeDirection` on the `ConfigProvider` which is a scoped instance. 

if in the current implementation of `ConfigProvider` the `_direction` could be get its first value from the `ConfigService` then we could set the direction globally and not only in scoped 

https://github.com/ant-design-blazor/ant-design-blazor/blob/4f34a2a83e6a996e5b2d97e8ace8fa6357e9f64b/components/config-provider/ConfigProvider.razor.cs#L11

**Comment by mhamri** [comment]
I would change that line to this, if you are fine with it, I can create a PR

```cs
            get => _direction ?? ConfigService.Direction;
```

**Comment by anranruye** [comment]
@mhamri I don't see `Direction` property in `ConfigService` class.

**Comment by mhamri** [comment]
I mean we can expose it, the problem is at the moment even if you set the `ConfigService.ChangeDirection("rtl")` nothing happens. 

we can refactor whole thing and make the `ConfigProvider` to fallback to `ConfigService` and make `ConfigService` as the single source of truth. atm we have two class that trying to hold the same information

**Comment by anranruye** [comment]
@mhamri Yes, you are right. Feel free to contribute a pr.

**Comment by mhamri** [comment]
A harder refactor is to use `ConfigService` in all the elements other than the `ConfigProvider`. I am not sure why this design is chosen, bcs something like direction won't be needed in a cascade parameter, either the application is RTL

**Comment by anranruye** [comment]
@mhamri I don't know why this design is chosen either. @ElderJames what do you think about this?

**Comment by ElderJames** [comment]
Please try use ConfigProvider component in App.razor:

```
<ConfigProvider Direction="rtl">
    ...
</ConfigProvider>
```
