### ISSUE TITLE
DatePicker and 

### ISSUE THREAD

**Issue by datnguyen89** [ant-design-blazor/ant-design-blazor#1620]
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by anddrzejb** [comment]
@datnguyen89 Is this issue an accident? If yes, can you close it please?

**Comment by datnguyen89** [comment]
Im sorry bro. Just wrong enter :(
