### ISSUE TITLE
Add missing entries to Dutch locale files

### ISSUE THREAD

**Issue by gregloones** [ant-design-blazor/ant-design-blazor#1623]
Hey team,

I was looking to add missing elements to the Dutch locale files (nl-BE and nl-NL), similar to what was done for #1556 , and create a pull request.

However, I'm not sure which one to use as the basis for my comparison. En-GB was most recently changed but en-US has more elements... Which one should I use?

**Comment by anddrzejb** [comment]
Go with en-US. That is the default.

**Comment by gregloones** [comment]
Will do, thanks!
