### ISSUE TITLE
Question: is that possible to prevent OnClick when OnClosing in Tag component?

### ISSUE THREAD

**Issue by newbe36524** [ant-design-blazor/ant-design-blazor#1626]
I have a Tag to support to search link by click the tag and remove the tag by closing it.
However, when I try to close the tag, it fire OnClick and OnClosing at the same time.
I wonder that it is possible to prevent OnClick when OnClosing ?

```csharp
<Tag Closable="true"
     OnClosing="e => OnRemovingTag(bk.Bk, tag)"
     OnClick="e => OnClickTag(bk.Bk, tag)"
     Color="@WebHelper.GetTagColor(tag)">
    @tag
</Tag>
```

![EYh8qwg5aR](https://user-images.githubusercontent.com/7685462/121378837-204a5b80-c976-11eb-9d96-8af9b795ff9e.gif)

**Comment by anddrzejb** [comment]
Seems like missing `stopPropagation`. I think I will be able to fix it easily...

**Comment by anranruye** [comment]
@anddrzejb I'm sorry to interrupt. Do you think use `stopPropagation` is a good pattern? I mean, is it possible to influence user event defined for the parent elements? A few days ago I met a similar situation and finally I decided to use a more complicated solution than just apply `stopPropagation`.

**Comment by anddrzejb** [comment]
I am open to suggestions, but it is not clear to me why `stopPropagation` could be consider a wrong pattern. We do not want the event to bubble up, and as far as I know, `stopPropagation` was made exactly for that purpose. And from my initial tests, it seems to work without any issues here. Mind that it only works on events bound from blazor. If you use jsinterop, it won't work.

**Comment by anranruye** [comment]
@anddrzejb 
> it only works on events bound from blazor

You are right Andrzej. Thank you for telling me this. And fortunately I think I made a right decision because that time I was preventing an event listener created by JsInterop.
