### ISSUE TITLE
Select default value is empty

### ISSUE THREAD

**Issue by mkalinski93** [ant-design-blazor/ant-design-blazor#1629]
I have a problem with the Select component that I can not understand somehow.
I need to select a default Value for the selection. I have a few pricelists which one of them is a "default" pricelist. 
The "_selectedValue" is checked against null and it is set.

```blazor
<Select DataSource="@_priceLists"
        @bind-Value="@_selectedValue"
        LabelName="@nameof(PriceListDto.Name)"
        ValueName="@nameof(PriceListDto.Id)"
        DefaultValue="@_selectedValue"
        Style="@($"{Style} width:{Width};")"
        Class=@Class
        OnSelectedItemChanged=@(async(x)=> await OnSelectedItemChangedHandler(x))>
    <ItemTemplate>
        <div style="text-align: left">
            <FlagIcon Country=@context?.CountryCode></FlagIcon><span class="ml-1">@context?.Name</span>    
        </div>
    </ItemTemplate>
    <LabelTemplate>
        <FlagIcon Country=@context?.CountryCode></FlagIcon><div style="margin-top: 3px;" class="ml-1">@context?.Name</div>
    </LabelTemplate>
</Select>
```

This is how I´ve implemented the Select Component and it worked sometimes, but now the content is just empty.
I´ve also tried to remove "DefaultValue" and tried other variations. 
The Select Component is inside another component. I don´t use Form, too.

The test example somehow worked. 
This data is loaded async from my service and the content will be rendered, when the data is received.

I hope there´s something I miss.

Thank you in advance

**Comment by anranruye** [comment]
@mkalinski93 Thanks for contacting us.
 
Do you think your issue is duplicate of #1587? Or it is something different?

**Comment by mkalinski93** [comment]
Hey @anranruye,

thanks for the advice with the issue. It seems to be something close and I was able to fix this issue with this suggegstion.

I think we can close this one as it is potentially part of #1587 

`@datnguyen89 Until now, another workaround is to do what @anranruye suggested but do not bind to a property in your model. Just attach OnSelectedItemChanged action and set your model's property there.`
