### ISSUE TITLE
CheckBoxGroup Can not used in FormItem

### ISSUE THREAD

**Issue by wcoolly-cloud** [ant-design-blazor/ant-design-blazor#1633]
If I use the CheckboxGroup like this
```
<FormItem Label="Form Size">
   <CheckboxGroup Options="@plainOptions" @bind-Value="@(new[]{"Apple"})" OnChange="OnChange" />
</FormItem>

```
It throw the exceptions like
![image](https://user-images.githubusercontent.com/85785234/121792869-b4dde380-cc2c-11eb-8448-19adf7032146.png)

**Comment by anddrzejb** [comment]
Similar issue was with `Slelct` component. Until fixed, you can use the workaround proposed by @anranruye in #1453.
