### ISSUE TITLE
Display index of row, get all data of row

### ISSUE THREAD

**Issue by datnguyen89** [ant-design-blazor/ant-design-blazor#1638]
Dear team
I'm trying to create a Table to display data and CRUD module, so:
1. How to display index of row at the first Column
2. How to get all data of row (when click edit button I want to pass data to Modal) 
Tks
![2021-06-15_15-50-47](https://user-images.githubusercontent.com/55984933/122023366-532c8f00-cd7c-11eb-9234-494b5be42aa2.png)

**Comment by ElderJames** [comment]
Thanks for contact us @datnguyen89 

1. You can try to add a property for your index column, and add a Column at the first `<Column>@context.Index</Column>`.
2. You can get the data from @context, `<ActionColumn><Button OnClick="openModal(context)" /></ActionColumn>`

**Comment by anranruye** [comment]
@datnguyen89

Do you think your issue is similar with #1455 and #1476?

**Comment by datnguyen89** [comment]
@anranruye I expected something build-in :(. Thanks for your solution
@ElderJames You saved my day bro. There is nothing about ActionColumn in documentation. I didn't know the existence of ActionColumn
![table](https://user-images.githubusercontent.com/55984933/122160787-647da600-ce25-11eb-96ce-ed363239e0df.png)
