### ISSUE TITLE
Funtion Dispose() of  AntComponentBase is not virtual 

### ISSUE THREAD

**Issue by MGODY** [ant-design-blazor/ant-design-blazor#1643]
### description 

I want to use Dispose() in my page whitch inherits FeedbackComponent<>. but it dosen't works

### Describe the solution you'd like

make the  function  Dispose()  of AntComponentBase to be virtual

**Comment by zxyao145** [comment]
@MGODY Hi, please try to set `ModalOptions.DestroyOnClose = true`.
