### ISSUE TITLE
The rederring is not correct when unfolding the Menu after clicking a secondary MenuItem when the Menu is folded

### ISSUE THREAD

**Issue by AsakusaRinne** [ant-design-blazor/ant-design-blazor#1644]
I'm using the version 0.8.1 with the code below:

```
<Layout Style="min-height: 100vh; ">
    <Sider Collapsible Collapsed=@collapsed OnCollapse=@onCollapse>
        <NavMenu></NavMenu>
    </Sider>
    <Layout Class="site-layout">
        <Header Class="site-layout-background" Style=" padding: 0 ;"></Header>
        <Content Style="margin:0 16px;">
            @Body
        </Content>
        <Footer Style="text-align:center ">Ant Design ©2018 Created by Ant UED</Footer>
    </Layout>
</Layout>
```
```
<Menu Theme="MenuTheme.Dark" DefaultSelectedKeys=@(new[]{"1"}) Mode="MenuMode.Inline"
      OpenKeys=this.openKeys
      OnOpenChange=this.onOpenChange>
    <div>
        <span><a class="RepoName" href="">SytSolutions</a></span>
    </div>
    <MenuItem Key="1" Icon="home" RouterLink="/">Home</MenuItem>
    <SubMenu Key="sub1" TitleTemplate=@FoodTitle>
        <MenuItem Key="2" RouterLink="/FoodTableView">View</MenuItem>
        <MenuItem Key="3">Collect</MenuItem>
        <MenuItem Key="4">Statistics</MenuItem>
    </SubMenu>
    <SubMenu Key="sub2" TitleTemplate=@PedestrianTitle>
        <MenuItem Key="5">Control Panel</MenuItem>
        <MenuItem Key="6">Statistics</MenuItem>
    </SubMenu>
    <MenuItem Key="7" Icon="bug">BUG Report</MenuItem>
    <MenuItem Key="8" Icon="api">APIS</MenuItem>
</Menu>a
```

And when I test it, the case below happend:

![40gtq-g8ekq](https://user-images.githubusercontent.com/47343601/122263121-a7fd1080-cf08-11eb-92c8-7f0ab61af3f0.gif)

I'm not sure if this a BUG or I just make a mistake in my code. But the case still exist after my some attempts to change the code.

**Comment by anranruye** [comment]
@AsakusaRinne Thank you for contacting us.

Please try remove bootstrap style

**Comment by AsakusaRinne** [comment]
> @AsakusaRinne Thank you for contacting us.
> 
> Please try remove bootstrap style

Thank you. I removed all the bootstrap style in the mainlayout and the navmenu, but the case still existed.

I wonder if the case is caused by other reasons because I found the example in [Blazor example on gitee](https://ant-design-blazor.gitee.io/zh-CN/components/layout#components-layout-demo-side) also uses bootstrap style in layout but works well.

**Comment by anddrzejb** [comment]
A bit late but just did some work on the menu. First, don't use `Template`. Switch to `<span>`:
```razor
    RenderFragment FoodTitle =
    @<span>
        <Icon Type="setting" Theme="outline"></Icon>
        <span>Food System</span>
    </span>;
```
I don't know why, but `Template` breaks it (at least on my machine). Probably needs more investigation.
There are some other issues with `<Menu>` when in `<Layout>` - for example, the expanded always stays expanded even if collapsed (repro: click on `Food System` to collapse, the collapse the side bar, expand side bar, `Food System` is again expanded) or when collapsing the menu - the popup menu shows which is now incorrect.

**Comment by anddrzejb** [comment]
I just managed to fix the other issues that I noticed in your reproduction.
