### ISSUE TITLE
(Documentation) Language Based Routing resulting in 404 when viewing components

### ISSUE THREAD

**Issue by ske66** [ant-design-blazor/ant-design-blazor#165]
I live in the UK so my language is set to en-GB. The route parameter is set automatically when I go to the docs and in some cases certain components fail to render, returning 404 errors.

`Unhandled exception rendering component: Response status code does not indicate success: 404 (Not Found).`

In order to view the docs properly, I have to change the route language parameter to en-US.

Steps to reproduce;

1. Open the docs
2. Change the url to https://ant-design-blazor.github.io/en-GB/docs/introduce

**Comment by ElderJames** [comment]
Thanks for contacting us.
Yes, someone has reported the issue before #159 , there are problems in the multi-language processing.
