### ISSUE TITLE
The 'Upload' component will treat the 201 (created) HTTP status code as a failure result

### ISSUE THREAD

**Issue by hongyeli620** [ant-design-blazor/ant-design-blazor#1655]
### Describe the bug

The 'Upload' component will treat the 201 (created) HTTP status code as a failure result

#### Page Code:
```xml
<Upload Action="@uploadUrl" Name="files" FileList="_fileList"
        OnSingleCompleted="OnSingleCompletedAsync" BeforeAllUploadAsync="OnBeforeUploadAsync">
    <Button>导入</Button>
</Upload>
```
#### C# Code:
When the HTTP status code returns **201 (created)**, the **fileinfo.File.State** property returns **Uploadstate.Fail**, which makes it impossible to get the actual return result through **fileinfo.File.Response**
```csharp
async Task OnSingleCompletedAsync(UploadInfo fileinfo)
{
    if (fileinfo.File.State == UploadState.Success)
    {
        var jObject = JObject.Parse(fileinfo.File.Response);

        var result = fileinfo.File.GetResponse<UploadResult>();
        await this.ImportAsync(Path.GetFileName(result.StoredFileName));
    }
}
```

To solve this problem, you can only replace the **CreatedResult** with the **JsonResult** in the file save controller
```csharp
[HttpPost]
public async Task<ActionResult<IList<UploadResult>>> PostFile(
            [FromForm] IEnumerable<IFormFile> files)
{
    //...
    //return new CreatedResult(resourcePath, uploadResults);
    return new JsonResult(uploadResults);
}
```

### Further technical details
- AntDesign Nuget Package version: 0.8.1
- Dotnet 5.0
- The IDE : VS 2019
- Blazor Server

**Comment by ElderJames** [comment]
Thanks for contacting us @hongyeli620 

You're right that we have a restriction in our component that only 200 is marked as success, but I think we can support all status codes that indicate success.

https://github.com/ant-design-blazor/ant-design-blazor/blob/2ac444bb241d8a8cbd66c5775a9fc2aa1bb83059/components/core/JsInterop/interop.ts#L128

Would you be interested in helping to revise it?

**Comment by henrikwidlund** [comment]
I can do a PR for this

**Comment by ElderJames** [comment]
@henrikwidlund Cool, thank you!
