### ISSUE TITLE
InputNumber: Continious non-stopping counting.

### ISSUE THREAD

**Issue by JanWiedersum** [ant-design-blazor/ant-design-blazor#1668]
### Describe the bug

![2021-06-23-14-09-17](https://user-images.githubusercontent.com/40599786/123094117-cee9a400-d42c-11eb-8dc9-771b7b57589d.gif)

The InputNumber field keeps counting and it's not possible to stop it through the up or down arrow-buttons.

### Steps to reproduce (please include code)

https://ant-design-blazor.gitee.io/en-US/components/inputnumber#components-inputnumber-demo-Generic
1. Hold the left mouse button for at least 2-3 seconds.
2. Right click.
3. Release the left mouse button.

### Further technical details
- AntDesign Nuget Package version:  0.8.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Hello @JanWiedersum , we have fixed this issue in lastest version, please try.

**Comment by JanWiedersum** [comment]
@ElderJames Thank you it's working now :)

**Comment by ElderJames** [comment]
@JanWiedersum Cool.
