### ISSUE TITLE
DatePicker: The component is not wide enough for default datetime format of some languages

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1676]
### Describe the bug

For example, the format for chinese is "yyyy年[M]M月[d]d日 HH时mm分ss秒":
![动画02](https://user-images.githubusercontent.com/54608128/123531926-13ca4f00-d73b-11eb-9f34-4ff5ad921c5c.gif)

### Steps to reproduce (please include code)

https://ant-design-blazor.gitee.io/zh-CN/components/datepicker#components-datepicker-demo-time

### Further technical details
- AntDesign Nuget Package version 0.8.2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by anddrzejb** [comment]
I think this can be solved with just applying styles to `Style` parameter. The component width is based on react antD.

**Comment by anranruye** [comment]
@anddrzejb Applying styles to `Style` parameter solved this issue.

However, react antD use the same format for all languages, the default width is always enough. Should we use a larger width for `ShowTime=true`?

**Comment by anddrzejb** [comment]
I did not look into that, but as far as I know all of it is baked into the `.less` files. We probably should investigate then if we are not overwriting the settings. Because otherwise, it should look just like react antD.

**Comment by anranruye** [comment]
@anddrzejb Don't worry. Now I understand that react antD uses html size attribute to control the component width, rather than css width attribute. We can easily solve this issue by just calculating the size: `Encoding.UTF8.GetBytes(Format).Length` .
