### ISSUE TITLE
Module:Input Number Onchange is not working when out of focus for the first time

### ISSUE THREAD

**Issue by EmilyGermanotta** [ant-design-blazor/ant-design-blazor#1694]
Hi everyone, my issue is like this
I had the input number component with OnChange like this 
`<AntDesign.InputNumber @bind-Value="@context.Duration"
                                               TValue="int"
                                               Max="99"
                                               OnChange="DurationOnChangeHandler"
                                               Style="width: 200px;">
                        </AntDesign.InputNumber>`

The DurationOnChangeHandler function from code behind is not triggered for the first time when I change the focus to other component. 
The function is triggered when I click on the component again and out of focus for it again
My function from code behind
`private void DurationOnChangeHandler(){ 
InputModel.EndDate = InputModel.StartDate.AddDays(InputModel.Duration);
            StateHasChanged();
        }`
Anyone encountered the same issue like this?

https://user-images.githubusercontent.com/29965379/124731243-a1304f00-df44-11eb-9ef1-e331d1279ad8.mp4

**Comment by ElderJames** [comment]
Thanks for contacting us @EmilyGermanotta 

I'm fix it in #1830, please try the 0.9.2 nightly build, or wait for it release.
