### ISSUE TITLE
Select inside dropdown closing dropdown

### ISSUE THREAD

**Issue by hans-engstad** [ant-design-blazor/ant-design-blazor#1696]
### Describe the bug

When placing a Select component inside a Dropdown component, the Dropdown gets closed when an item is selected from the Select. 

When using TriggerType.Click on the Dropdown, the Dropdown also closes when the Select gets blurred. 

The bug was encountered when using a form inside a Dropdown which contained a Select component. In this situation it is not desirable to close the dropdown when an item is selected. 

### Steps to reproduce (please include code)

[Github Repository](https://github.com/hans-engstad/AntDesignSelectInDropdownBug)

![78a93594-f5f1-48be-9e25-38030ab5e2f5](https://user-images.githubusercontent.com/40248609/124017608-35e7f980-d9e7-11eb-8ba2-5e6134cbd9e0.gif)

This is the code from the repository which is relevant: 

```
<h4>Select in dropdown - Click TriggerType</h4>
<Dropdown Trigger="@(new TriggerType[] { TriggerType.Click })">
    <Overlay>
        <Card>
            <Select DataSource="@_list"
                    @bind-Value="@_selectedValue1"
                    DefaultValue="@("lucy")"
                    ValueName="@nameof(Person.Value)"
                    LabelName="@nameof(Person.Name)"
                    DisabledName="@nameof(Person.IsDisabled)"
                    Style="width:120px">
            </Select>
        </Card>
    </Overlay>
    <ChildContent>
        <a class="ant-dropdown-link" @onclick:preventDefault>
            Click me <Icon Type="down" />
        </a>
    </ChildContent>
</Dropdown>

<h4>Select in dropdown - Default TriggerType (Hover)</h4>
<Dropdown>
    <Overlay>
        <Card>
            <Select DataSource="@_list"
                    @bind-Value="@_selectedValue1"
                    DefaultValue="@("lucy")"
                    ValueName="@nameof(Person.Value)"
                    LabelName="@nameof(Person.Name)"
                    DisabledName="@nameof(Person.IsDisabled)"
                    Style="width:120px">
            </Select>
        </Card>
    </Overlay>
    <ChildContent>
        <a class="ant-dropdown-link" @onclick:preventDefault>
            Click me <Icon Type="down" />
        </a>
    </ChildContent>
</Dropdown>


<h4>Select in dropdown - Click TriggerType (Poor Workaround)</h4>
<Dropdown Trigger="@_triggerTypes" OnVisibleChange="OnDropdownVisibleChanged">
    <Overlay>
        <Card>
            <Select DataSource="@_list"
                    @bind-Value="@_selectedValue1"
                    DefaultValue="@("lucy")"
                    ValueName="@nameof(Person.Value)"
                    LabelName="@nameof(Person.Name)"
                    DisabledName="@nameof(Person.IsDisabled)"
                    Style="width:120px">
            </Select>
        </Card>
    </Overlay>
    <ChildContent>
        <a class="ant-dropdown-link" @onclick:preventDefault>
            Click me <Icon Type="down" />
        </a>
    </ChildContent>
</Dropdown>

@code {

    // Select example from documentation

    List<Person> _list;
    string _selectedValue1, _selectedValue2, _selectedValue3;
    string _selectedValue4 = "lucy";
    class Person
    {
        public string Value { get; set; }
        public string Name { get; set; }
        public bool IsDisabled { get; set; }
    }

    protected override void OnInitialized()
    {
        _list = new List<Person>
        {
            new Person {Value = "jack", Name = "Jack"},
            new Person {Value = "lucy", Name = "Lucy"},
            new Person {Value = "disabled", Name = "Disabled", IsDisabled = true},
            new Person {Value = "yaoming", Name = "YaoMing"}
        };
    }


    // Workaround code 

    private TriggerType[] _triggerTypes = new TriggerType[] { TriggerType.Click };

    private void OnDropdownVisibleChanged(bool visible)
    {
        if (visible)
        {
            _triggerTypes = new TriggerType[] { TriggerType.Hover };
        }
        else
        {
            _triggerTypes = new TriggerType[] { TriggerType.Click };
        }
    }
} 
```

### Further technical details
- AntDesign Nuget Package version: 0.8.2

- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019
Version 16.10.0

**Comment by anranruye** [comment]
@hans-engstad thank you for contacting us.

Please use `PopupContainerSelector` for select component.
```
<h4>Select in dropdown - Default TriggerType (Hover)</h4>
<Dropdown>
    <Overlay>
        <Card>
            <div id="container"></div>
            <Select DataSource="@_list"
                    @bind-Value="@_selectedValue1"
                    DefaultValue="@("lucy")"
                    ValueName="@nameof(Person.Value)"
                    LabelName="@nameof(Person.Name)"
                    DisabledName="@nameof(Person.IsDisabled)"
                    Style="width:120px"
                    PopupContainerSelector="#container">
            </Select>
        </Card>
    </Overlay>
    <ChildContent>
        <a class="ant-dropdown-link" @onclick:preventDefault>
            Click me <Icon Type="down" />
        </a>
    </ChildContent>
</Dropdown>
```

**Comment by hans-engstad** [comment]
Thank you for the fast reply. 

Your solution worked pretty good when using TriggerType.Hover. The Dropdown stayed open when selecting an item and when blurring the select. The Dropdown did however close when selecting an item which is outside of the Dropdown borders (See the gif). 

When using TriggerType.Click, it did however close the Dropdown when selecting and item or when blurring the select. 

![2d34a897-04fb-4fb6-9aee-f85aca543c8d](https://user-images.githubusercontent.com/40248609/124096458-e0e5cb00-da5a-11eb-8860-28c51c8def6a.gif)


Here is the added code which is used in the gif. 
```
<h4>Select in dropdown - Default TriggerType (Suggestion from anranruye)</h4>
<Dropdown>
    <Overlay>
        <div id="container"></div>
        <Card>
            <Select DataSource="@_list"
                    @bind-Value="@_selectedValue1"
                    DefaultValue="@("lucy")"
                    ValueName="@nameof(Person.Value)"
                    LabelName="@nameof(Person.Name)"
                    DisabledName="@nameof(Person.IsDisabled)"
                    Style="width:120px"
                    PopupContainerSelector="#container">
            </Select>
        </Card>
    </Overlay>
    <ChildContent>
        <a class="ant-dropdown-link" @onclick:preventDefault>
            Click me <Icon Type="down" />
        </a>
    </ChildContent>
</Dropdown>


<h4>Select in dropdown - Suggestion from anranruye with Click</h4>
<Dropdown Trigger="@(new TriggerType[] { TriggerType.Click })">
    <Overlay>
        <div id="container2"></div>
        <Card>
            <Select DataSource="@_list"
                    @bind-Value="@_selectedValue1"
                    DefaultValue="@("lucy")"
                    ValueName="@nameof(Person.Value)"
                    LabelName="@nameof(Person.Name)"
                    DisabledName="@nameof(Person.IsDisabled)"
                    Style="width:120px"
                    PopupContainerSelector="#container2">
            </Select>
        </Card>
    </Overlay>
    <ChildContent>
        <a class="ant-dropdown-link" @onclick:preventDefault>
            Click me <Icon Type="down" />
        </a>
    </ChildContent>
</Dropdown>
```

**Comment by anranruye** [comment]
for hover trigger type, this is because when the select dropdown closes, your mouse is outside the trigger/dropdown. If you move your mouse inside quickly after you select an item, the dropdown will not close.

For click trigger type, you can use Visible property to control the dropdown visibility manully. This is what we do for the table filter: https://github.com/ant-design-blazor/ant-design-blazor/blob/ba8dd9f3696e71310ac939c28cd3b86477ce35c0/components/table/Column.razor#L181 . We will continue to research how to solve this issue.

**Comment by ElderJames** [comment]
Have been fixed now.
