### ISSUE TITLE
Select with virtualize

### ISSUE THREAD

**Issue by ardia** [ant-design-blazor/ant-design-blazor#1697]
Example: 
not correct work

<div>Selected @_value?.Label</div>
<div>Count: @_count</div>
<div>Query: @_query</div>
<div>Request StartIndex: @requestCurrent.StartIndex</div>
<div>Request Count: @requestCurrent.Count</div>
Filtered:
<br />
<div style="overflow: scroll; width: 300px;">
    @if (_filtered.Any())
    {
        foreach (var item in _filtered ?? new List<SelectItemDto>())
        {
            @item.Label<span>;</span>
        }
    }
    else
    {
        <span style="font-style: italic;">empty</span>
    }
</div>

<Select @ref="_select"
        @bind-Value="@_value"
        TItem="SelectItemDto"
        TItemValue="SelectItemDto"
        Placeholder=""
        EnableSearch
        Loading="_isLoading"
        AllowClear
        OnBlur="OnBlur"
        OnSearch="@(async (search) => await OnSearchAsync(search))"
        IgnoreItemChanges="false"
        HideNotFoundContent="false"
        DefaultActiveFirstItem="false">

    <SelectOptions>
        <Virtualize @ref="_virtualize" ItemsProvider="@LoadData" Context="item" ItemSize="32">
            <ItemContent>
                <SelectOption TItemValue="SelectItemDto" TItem="SelectItemDto" Value=@item Label=@item.Label />
            </ItemContent>
            <Placeholder>
                Loading...
            </Placeholder>
        </Virtualize>
    </SelectOptions>

</Select>

@code {
    Select<SelectItemDto, SelectItemDto> _select;
    public class SelectItemDto
    {
        public SelectItemDto(string value, string label)
        {
            Value = value;
            Label = label;
        }
        public string Value { get; set; }
        public string Label { get; set; }
    }
    int _count = 0;
    SelectItemDto _value = new SelectItemDto("", "");
    List<SelectItemDto> _options;
    List<SelectItemDto> _filtered = new List<SelectItemDto>();
    IEnumerable<string> _selectedValues = new List<string> { "0a10", "0c12" };
    protected override void OnInitialized()
    {
        const int min = 0;
        const int max = 2000;
        _options = new List<SelectItemDto>();

        for (var i = min; max > i; i++)
        {
            var value = Convert.ToString(i, 16).PadLeft(2, '0') + i.ToString();
            _options.Add(new SelectItemDto(value, value));
        }
    }

    private void OnSelectedItemsChangedHandler(IEnumerable<SelectItemDto> values)
    {
        Console.WriteLine($"selected: ${string.Join(",", values.Select(x => x.Label))}");
    }

    Virtualize<SelectItemDto> _virtualize;
    bool _isLoading = false;
    string _query = "";
    private async Task OnSearchAsync(string value)
    {
        _query = value;
        await _virtualize.RefreshDataAsync();

        StateHasChanged();
        Console.WriteLine($"search: {value}");
    }

    ItemsProviderRequest requestCurrent;
    private async ValueTask<ItemsProviderResult<SelectItemDto>> LoadData(ItemsProviderRequest request)
    {
        _isLoading = true;
        this.requestCurrent = request;

        //Fake get data from api
        _filtered = (string.IsNullOrWhiteSpace(_query) ? _options : _options.Where(w => w.Label.IndexOf(_query, StringComparison.OrdinalIgnoreCase) >= 0)).ToList();
        var list = _filtered.Skip(request.StartIndex).Take(request.Count);
        _count = _filtered.Count();
        _isLoading = false;
        StateHasChanged();

        return new ItemsProviderResult<SelectItemDto>(list, _filtered.Count());
    }

    private void OnBlur()
    {
        _query = "";
    }
}

> Virtualization is currently not implemented.

I would like to know if still under development.

Thanks a lot

**Comment by mkalinski93** [comment]
I was looking for something different, then I came upon your Issue.

I think you are looking for an answer anymore, but here you go: https://antblazor.com/en-US/components/select#components-select-demo-big-data

You can enable virtualization by now.
Probably this can be closed

**Comment by ElderJames** [comment]
We have implement virtualization for select component in #2654 .
