### ISSUE TITLE
NodeJS/Gulp dependency

### ISSUE THREAD

**Issue by m5x** [ant-design-blazor/ant-design-blazor#1700]
### Is your feature request related to a problem? Please describe.
One of the biggest reasons for .NET developers to love Blazor is the fact that they do not have to use Javascript and Javascript tools to create web applications. It is a shame if a Blazor project still requires us to install and use these tools.

### Describe the solution you'd like
Remove dependencies on NodeJS/NPM/Gulp etc., use .NET tools instead.

**Comment by ElderJames** [comment]
Thanks for contacting us @m5x 

You are right, blazor is for . Net developers.
In Ant Design Blazor, we need to synchronize the style (.less) and we can't find a less compiler built with .Net.
But people who use our library don't need to use
Node. So we will remove the node dependency form out pro template.

**Comment by m5x** [comment]
Thank you @ElderJames for looking into it. There are quite a lot of solutions to compile LESS to CSS using .NET/MSBuild. Have you looked for example at this project:

https://github.com/dotless/dotless

?

**Comment by ElderJames** [comment]
Yes, I have an impression of dotless, though I have not studied it in depth. If you know how to use it, feel free to help us compile our less files using dotless.

**Comment by m5x** [comment]
I've looked at dotless a bit more and it would not be a good choice because it is not actively developed anymore. Instead people seem to be using SASS as a more advanced CSS compiler by means of [LibSassHost](https://github.com/Taritsyn/LibSassHost). If you ever decided to switch to SASS I can contribute MsBuild task to compile SASS to CSS using LibSassHost.
