### ISSUE TITLE
When will the table have the effect shown in the figure and the examples?

### ISSUE THREAD

**Issue by OaimIsGnay** [ant-design-blazor/ant-design-blazor#1702]
请问,什么时候表格才会有图中的效果,以及例子? 

![image](https://user-images.githubusercontent.com/58240619/124373556-b3508a00-dcc5-11eb-89f7-b2387ddd503f.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @OaimIsGnay 

We have add a demo for that and it's in the master branch. It will be released as v0.8.3 next week.

**Comment by ElderJames** [comment]
please see https://ant-design-blazor.gitee.io/zh-CN/components/form#components-form-demo-advanced-search
