### ISSUE TITLE
Can't use table component with Build-in Filters NullRefferenceExcepcion

### ISSUE THREAD

**Issue by kuznecovIT** [ant-design-blazor/ant-design-blazor#1707]
### Can't use table component with Build-in Filters

I am trying to use filters on a table component.

When copying the example from the site and running my project, I see an error

The error is shown below in the screenshot

### Links to copied code from ([antblazor table demo filter](https://antblazor.com/en-US/components/table#components-table-demo-filter))
[Index page with copied example (main issue - does not work)](https://github.com/kuznecovIT/antblazorIssue/blob/master/blazor/Pages/Index.razor)
[Program.cs with included antblazor](https://github.com/kuznecovIT/antblazorIssue/blob/master/blazor/Program.cs)
[App.razor with AntContainer](https://github.com/kuznecovIT/antblazorIssue/blob/master/blazor/App.razor)

### Exceptions (if any)
After load page instantly error
![image](https://user-images.githubusercontent.com/62954135/124417133-ea7c7500-dd71-11eb-8081-0e21ad9556f3.png)
On filter click after loaded with errors page
![image](https://user-images.githubusercontent.com/62954135/124418176-53fd8300-dd74-11eb-8b39-53f5b5e3e7fc.png)

### Further technical details
- AntDesign Nuget Package version
0.8.2

- Include the output of `dotnet --info`
SDK .NET:
 Version:   5.0.202
 Commit:    db7cc87d51

 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
JetBrains Rider 2021.1.3
Build #RD-211.7442.29, built on May 26, 2021
Runtime version: 11.0.11+9-b1341.57 amd64

**Comment by anranruye** [comment]
@kuznecovIT Thanks for contacting us.

I can not reproduce this with the same code. Try to rebuild the project and clear your browser cache. Then see if there's any improvement.

**Comment by kuznecovIT** [comment]
> @kuznecovIT Thanks for contacting us.
> 
> I can not reproduce this with the same code. Try to rebuild the project and clear your browser cache. Then see if there's any improvement.

I recently tried doing the same thing on a different PC with a clean project.
I copied the example from the site and it gave an error ...

**Comment by kuznecovIT** [comment]
> @kuznecovIT Thanks for contacting us.
> 
> I can not reproduce this with the same code. Try to rebuild the project and clear your browser cache. Then see if there's any improvement.

btw
When checking, did you download my project or just inserted an example (with which I had problems) into your own ?

**Comment by anranruye** [comment]
I guess this is same with #1556, some nodes are missing in our language resource files.

**Comment by kuznecovIT** [comment]
> I guess this is same with #1556, some nodes are missing in our language resource files.

Yes, you right.

Between language resources files [ru-RU.json](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/locales/ru-RU.json)/[en-US.json](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/locales/en-US.json) at least differ in the number of described lines
148 lines - RU 
234 lines - EN

After set this on code block of my index page
```
protected override void OnInitialized()
{
    LocaleProvider.SetLocale("en-US");
}
```
Works fine. (But with ru-Ru it not working)

I can suggest my help to add localization to the missing lines and maybe after the release everything will work without this unnecessary setlocales?

**Comment by anranruye** [comment]
Yes, everything will work once the missing lines are added. Feel free to open a pr.
