### ISSUE TITLE
CountDown component OnFinish callback causes System.InvalidOperationException

### ISSUE THREAD

**Issue by HexJacaranda** [ant-design-blazor/ant-design-blazor#1712]
Hi,

I used CountDown in Blazor Server application. But when I set OnFinish callback(**even if it's a empty method**), it will always trigger System.InvalidOperationException from render call, saying that **'The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state'**.

```razor
<CountDown Title="Countdown" Value="@deadline" OnFinish="OnFinish" />
@code
{
    //5 seconds
    DateTime deadline = DateTime.Now.AddMilliseconds(5 * 1000);

    void OnFinish()
    {
        Console.WriteLine("finished!");
    }
}
```
To reproduce this, you can create the **sample Blazor Server Application** from Visual Studio and replace code in Counter.razor with this code.

Enviorment:
.Net Runtime : 5.0.301
Ant Design Nuget Package : 0.8.2
IDE: Visual Studio 2019 & 2022

**Comment by ElderJames** [comment]
Thanks for contacting us @HexJacaranda , 

This looks like a minor problem, would you be interested in helping to fix it please?

**Comment by HexJacaranda** [comment]
Sure, I will try to fix it later.
