### ISSUE TITLE
Build-in Filters How to transfer value

### ISSUE THREAD

**Issue by OaimIsGnay** [ant-design-blazor/ant-design-blazor#1713]
Is it foreach?   I don't think so..
Is there a simpler way to know

**Comment by OaimIsGnay** [comment]
有 ant Blazor的QQ群吗?

**Comment by ElderJames** [comment]
Thanks for contacting us @OaimIsGnay ,

Can I ask you what specific problems you are experiencing? Do you have any suggestions?

**Comment by anranruye** [comment]
@OaimIsGnay 技术交流主要在钉钉群

**Comment by anranruye** [comment]
@OaimIsGnay If you still meet this problem or have any other questions, you can always open a new issue. Or you can scan the qr code in the readme page to join the DingTalk(钉钉) group. Now I will close this one since it is not active for a long time.
