### ISSUE TITLE
When CheckboxGroup Options changed，ValueChanged don't work

### ISSUE THREAD

**Issue by rq204** [ant-design-blazor/ant-design-blazor#1716]
### Describe the bug

It works fine when CheckboxGroup Options keep not change。But if I Changed Options in code，ValueChanged don't work。

### Steps to reproduce (please include code)

IF you click button，OnCheckboxChanged

@page "/"

<Button OnClick="@Test">test</Button>
<br />
<AntDesign.CheckboxGroup Options="@_weekOptions" ValueChanged="@OnCheckboxChanged" />
<Text>@TXT</Text>

        private CheckboxOption[] _weekOptions = new CheckboxOption[] {  new CheckboxOption {Label = "one", Value = "1"},
        new CheckboxOption { Label = "two", Value = "2" },

    };

        private string TXT
        {
            get
            {
                return string.Join(",", _ids.ToArray());
            }
        }

        List<int> _ids = new List<int>();
        /// <summary>
        /// 获取选中的日期
        /// </summary>
        /// <param name="weeks"></param>
        private void OnCheckboxChanged(string[] weeks)
        {
            _ids.Clear();
            if (weeks != null)
            {
                foreach (string s in weeks) _ids.Add(int.Parse(s));
            }
        }

        private void Test(Microsoft.AspNetCore.Components.Web.MouseEventArgs e)
        {
            _weekOptions = new CheckboxOption[] {
                new CheckboxOption { Label = "one", Value = "1" },
                new CheckboxOption { Label = "two", Value = "2" },
                new CheckboxOption { Label = "three", Value = "3" },
                new CheckboxOption { Label = "four", Value = "4" }
            };
        }
    }

**Comment by anddrzejb** [comment]
What is the version you are using? I cannot confirm your findings with latest build (tried on both server-side and wasm):
![checkboxGroupValueChanged](https://user-images.githubusercontent.com/6518006/124795054-56b8cd80-df58-11eb-8720-18ca9cf257cc.gif)

**Comment by rq204** [comment]
this is full testcode
[Index.razor.checkbox.txt](https://github.com/ant-design-blazor/ant-design-blazor/files/6781158/Index.razor.checkbox.txt)

**Comment by rq204** [comment]
Hello,
I upload full test code in reply。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design-blazor/ant-design-blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月8日(星期四) 凌晨0:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design-blazor/ant-design-blazor] When CheckboxGroup Options changed，ValueChanged don't work (#1716)





 
What is the version you are using? I cannot confirm your findings with latest build (tried on both server-side and wasm):

**Comment by rq204** [comment]
> What is the version you are using? I cannot confirm your findings with latest build (tried on both server-side and wasm):
> ![checkboxGroupValueChanged](https://user-images.githubusercontent.com/6518006/124795054-56b8cd80-df58-11eb-8720-18ca9cf257cc.gif)

thanks,I upload full code in reply.

**Comment by ElderJames** [comment]
@anddrzejb I think it's cause by the `MixedMode` implement in #1394. The `Options` is changed, but the Options in `GetCurrentValueFunc` didn't.

**Comment by anddrzejb** [comment]
@ElderJames somehow I missed the reply. I will have a look at this once I finish my current work on overlay.
