### ISSUE TITLE
InputPassword style

### ISSUE THREAD

**Issue by BeiYinZhiNian** [ant-design-blazor/ant-design-blazor#1723]
### Describe the bug
![image](https://user-images.githubusercontent.com/25119211/125054605-fc934600-e0d8-11eb-9adc-c9b7fccf34ad.png)

InputPassword Set style = "width: X%", the width does not change, and the position of the icon changes

### Further technical details
- AntDesign Nuget Package version：0.8.2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Hi @BeiYinZhiNian . You can try to fix it yourself 😉

**Comment by anddrzejb** [comment]
I think you should use `WrapperStyle`. This has been discussed in detail issue #876 and PR #1351.

**Comment by anranruye** [comment]
Closing this since it is not active for several months.
