### ISSUE TITLE
Disable the default behaviors of table

### ISSUE THREAD

**Issue by khanhtranchi** [ant-design-blazor/ant-design-blazor#1724]
Hi maintainers,

Now I just want to use the OnChange method with the QueryModel parameters and push to it REST Api to get the return data based on this QueryModel info. Before call the OnChange method, I don't know the table does it process the old data push to it before based on the filter and sort criteria ?. If so, it will waste resource and we could have a setting to disable this process.

Thanks.

**Comment by anranruye** [comment]
@khanhtranchi Thanks for contacting us.

We have done this job which will release in 0.9 version.

**Comment by anranruye** [comment]
@khanhtranchi thanks for contacting us.

Now you can set `RemoteDataSource=@true` to achieve this with the new release 0.9.0 version.

**Comment by ElderJames** [comment]
Hi @khanhtranchi , can you tell me if this solves your problem?

**Comment by anranruye** [comment]
Closing this since it is not active for several months.
