### ISSUE TITLE
CheckboxGroup bug

### ISSUE THREAD

**Issue by 362111880** [ant-design-blazor/ant-design-blazor#1733]
when use two CheckboxGroup,  can not set Optinos  using the same value 

For Example:
`<CheckboxGroup Options="@PermissionOptions" Value="x" OnChange="values => x = values"/>`
`<CheckboxGroup Options="@PermissionOptions" Value="y" OnChange="values => y = values"/>`

if i check one item in the first CheckboxGroup , the second CheckboxGroup item will be checked too.....

**Comment by ElderJames** [comment]
Thanks for contacting us @362111880 

You need to use two different instances for `Options`.
