### ISSUE TITLE
Getting value of a boolean and nullable boolean in select displays wrong value

### ISSUE THREAD

**Issue by mostrowski123** [ant-design-blazor/ant-design-blazor#1735]
### Describe the bug

Getting and displaying the current value of a boolean or nullable boolean in a select does not work. When I set a boolean and nullable boolean in the form model below to true, they show up as "No" and "Select:" respectively instead of both displaying "Yes". Other than displaying the wrong initial value, both selects work correctly when submitting the form. Both boolean and nullable boolean select in the example below worked in 0.8.2 but broke in 0.8.4. I might be misusing the select option and if so, what would be the best way to implement the cases below? A switch does not work in my case because I want to force a user to select either yes or no.

### Steps to reproduce (please include code)
```razor
<Form Layout="@FormLayout.Vertical"
      Model="@form">
    <FormItem Label="This should say 'yes'">
        <Select @bind-Value="@context.Ready" Placeholder="Select:" TItem="bool" TItemValue="bool" Style="width: 100px">
            <SelectOptions>
                <SelectOption TItemValue="bool" TItem="bool" Value="@true" Label="Yes"/>
                <SelectOption TItemValue="bool" TItem="bool" Value="@false" Label="No"/>
            </SelectOptions>
        </Select>
    </FormItem>
    <FormItem Label="This should also say 'yes'">
        <Select @bind-Value="@context.ReadyNullable" Placeholder="Select:" TItem="bool" TItemValue="bool?" Style="width: 100px">
            <SelectOptions>
                <SelectOption TItemValue="bool?" TItem="bool" Value="@true" Label="Yes"/>
                <SelectOption TItemValue="bool?" TItem="bool" Value="@false" Label="No"/>
            </SelectOptions>
        </Select>
    </FormItem>
</Form>

@code {

    private TestForm form { get; set; } = new TestForm {
        Ready = true,
        ReadyNullable = true
    };
    
    private class TestForm {
        public bool Ready { get; set; }
        public bool? ReadyNullable { get; set; }
    }
}
```
### Further technical details
- AntDesign Nuget Package version 0.8.4
- Include the output of `dotnet --info`
```bash
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019 16.10.3

**Comment by anranruye** [comment]
@mostrowski123 thanks for contacting us.

Currently, the only workaround is to use a data source instead of inline SelectOptions. 0.8.x versions still force the TItem type has a property for Value and another property for Label. #1541 removed this limitation, so you can use `List<bool>` or `bool[]` for DataSource directly. To get the new feature introduced by #1541, you can have a try for 0.9 nightly-build version.
