### ISSUE TITLE
No scroll visible when max-height is set on Modal's BodyStyle

### ISSUE THREAD

**Issue by lukblazewicz** [ant-design-blazor/ant-design-blazor#1737]
I'm not sure if it's a bug or a feature request - we need to keep modal no higher than the height of the parent component (so that the footer is always visible). Even if max-height is set on Modal's BodyStyle, there is no scroll, and the body is slipping through the footer. Am I missing something configuration-wise?

**Comment by lukblazewicz** [comment]
Adding `overflow-y: auto` on BodyStyle did the trick. If there is a better way to enforce scrollability inside of Modal, please let me know - if not, feel free to close the issue.

**Comment by zxyao145** [comment]
Hi, 
I don't know what happened, but bodystyle is available locally (v 0.8.4): 

```c#
BodyStyle = "max-height:50px;overflow:auto;"
```
Both ModalService andModal component.

Can you provide the version and code?

**Comment by lukblazewicz** [comment]
In our production code the issue is present both on 0.8.2 and 0.8.4 version (unless I specify overflow on BodyStyle explicitly as in the abovementioned example). I installed the newest version of AntDesign.ProLayout and used the following code in the `Welcome.razor` file:
```
@page "/"

<PageContainer>
    <Modal Visible="true">
        @for(var i = 0; i <= 100; i++)
        {
            <h2>test</h2>
        }
    </Modal>
</PageContainer>

@code {
}
```
It produced the following output: 
![image](https://user-images.githubusercontent.com/39852149/125820237-6da0ee2b-4d29-46b0-a039-705b1bf71f07.png)

**Comment by zxyao145** [comment]
Yes, you have to set the bodystyle manually.

**Comment by lukblazewicz** [comment]
Are we sure that this should be done via Style? Maybe we should expose a dedicated component-level property for the scroll behaviour?

**Comment by zxyao145** [comment]
Yes, I quite agree with you. At present, this is only consistent with Ant Design of React, and we will change it in the future.

**Comment by ElderJames** [comment]
We have `MaxBodyHeight` parameter.
