### ISSUE TITLE
MaxTagCount in Select on 'multiple' mode

### ISSUE THREAD

**Issue by Duster96** [ant-design-blazor/ant-design-blazor#1746]
There is a problem with using `MaxTagCount` property in Select component with mode `multiple`. When I use it, class `ant-select-selection-overflow-item` has 0px value in `height` what cause that none items in select are visible. Also `opacity` is incorrect for me, it is chaning on 0.2. 

I sent screen below:
![AntBlazor_Bug](https://user-images.githubusercontent.com/20935584/126042425-599f2a1e-e33e-4899-9efb-0ff9e22f4c58.png)

**Comment by anddrzejb** [comment]
@Duster96 can you please post a minimal repro (code or repo)?

**Comment by Duster96** [comment]
Yes, no problem. Everything what you need is in Pages/Index.razor:

[Repo](https://github.com/Duster96/BlazorSelectBug)

**Comment by anddrzejb** [comment]
Should be fixed once my latest PR #1776 gets merged. However, you should be aware that AntDesign does not cooperate very well with Bootstrap - there are few known issues with for example icon positioning.

**Comment by Duster96** [comment]
Thank you! And I will be aware about AntDesign and Bootstrap coexistence.

**Comment by ElderJames** [comment]
@dust63 Pleas help to see if this preview for PR #1776  is work correctly https://preview-1776-antblazor.surge.sh/

**Comment by anddrzejb** [comment]
@ElderJames I am not sure if preview will help here, as the use case of the issue is not present in the demo. However, I will try to add the demo covering this scenario.

**Comment by ElderJames** [comment]
@anddrzejb  That's even better 👍

**Comment by anddrzejb** [comment]
@dust63 the preview https://preview-1776-antblazor.surge.sh has now a demo in Components => Select => Changeable maxTagCount where your use case is presented. Can you please check it and confirm it works as you expected?

**Comment by Duster96** [comment]
It works correctly as I expected! :)
