### ISSUE TITLE
Table component layout issue in mobile mode

### ISSUE THREAD

**Issue by sorainnosia** [ant-design-blazor/ant-design-blazor#1748]
### Describe the bug

When the browser switch to mobile mode using Devtools, the Table component layout is off

### Steps to reproduce (please include code)
1. Make a Table component with many columns and fill the row with data
2. Run Devtool or press F12 in browser
3. Click the mobile mode icon in Devtools
..OR..
1. simplest way visit this link https://antblazor.com/en-US/components/table
2. Run Devtool or press F12 in browser
3. Click the mobile mode icon in Devtools
4. The Table user interface becomes messy

### Exceptions (if any)
No Exception is just that the layout is off

### Screenshot
![image](https://user-images.githubusercontent.com/19261780/126044929-6e109014-f7cd-4e4b-82e9-2f4edf551035.png)

### Suggestion
Suggesting to make every column and value into a separate Column Name : Value line during mobile mode and each record is separated by table's border. Other Blazor UI component is doing this instead of using css overflow scroll

**Comment by ElderJames** [comment]
Thanks for contacting us @sorainnosia 

Could you show me what mobile table you are talking about?

**Comment by ElderJames** [comment]
I have do it in feature branch and will ship with 0.10.0.
