### ISSUE TITLE
Input Number: input limit & hide buttons 

### ISSUE THREAD

**Issue by coolmint123** [ant-design-blazor/ant-design-blazor#1753]
I want you to display the numeric keypad including the decimal point when operating from a smartphone.

You can specify the minimum and maximum values in InputNumber and it is limited by the up and down buttons, but please also limit when inputting.

I want to hide the up and down buttons because I accidentally press the InputNumber.  If it is Input, I would like Input to set the numeric keypad of the smartphone, the minimum value, the maximum value limit, and the format.

**Comment by anranruye** [comment]
@coolmint123 thanks for contacting us.

We have noticed some issues about format, validation and value limitation(in pc side). However, ant design is not mainly designed for mobile devices, we can not promise you we can solve all the mobile device compatibility issues soon.

**Comment by anddrzejb** [comment]
InputNumber for smartphones has been solved by PR #1923.

**Comment by anddrzejb** [comment]
@ElderJames I did not close this, because there were some other requests except the one in the title, that as far as I know were not yet met. Maybe it would be better to keep this one open for reference?

**Comment by ElderJames** [comment]
Ok, it maybe need to change the title.

**Comment by ElderJames** [comment]
We have fixed the input limit. As for hidden buttons, since this is by ant design, we won't support them yet. Thank you.
