### ISSUE TITLE
How to get data after sort?

### ISSUE THREAD

**Issue by sannv0012** [ant-design-blazor/ant-design-blazor#1758]
Now I use sort in Table but after sorting, data in the datasource not change by sort
I have reference handle sort: https://github.com/ant-design-blazor/ant-design-blazor/blob/015129c68099ef9b784bc911150dba785a0cc102/components/table/Table.razor.cs#L232
Event OnChange only return queryModel

**Comment by anranruye** [comment]
@sannv0012 thanks for contacting us.

You can not do this in the current version. But we think this feature request is a good suggestion and will implement this feature later.
