### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by boukenka** [ant-design-blazor/ant-design-blazor#1761]
### Is your feature request related to a problem? Please describe.
There is a short list of possible colors for the button.

### Describe the solution you'd like
Could we add more? Or with a dedicated property?

### Additional context
This feature has been requested in https://github.com/ant-design-blazor/ant-design-blazor/issues/1034. The answer at that time was the following:

> In the future, we can add a colour parameter to the component which will do this for you.

Could it be planned? Thank you for any answer.

**Comment by ElderJames** [comment]
Thanks for cotacting us @boukenka 

Maybe you can add it with a PR.

**Comment by boukenka** [comment]
Ok. I will try to see what I can do.

**Comment by ElderJames** [comment]
You can add a `Color` Parameter and put it in the style of button.

**Comment by boukenka** [comment]
Thank you for the merge of the PR.

By the way, in the Button.Razor.cs, no need to check for ```Color.None```. If it is ```Color.None```, the method ```GetBackgroundStyle ``` returns an empty string.

```C#
private void SetButtonColorStyle()
  {
      if (Color != Color.None)
      {
          Style += ColorHelper.GetBackgroundStyle(Color);
      }
  }
```

**Comment by ElderJames** [comment]
Yes, but it would add an empty style attribute in the html and cause the test fails.

Also, I would like to make this color globally available as a tool that users can easily use. Do you have any ideas?

**Comment by boukenka** [comment]
I'm sorry. I don't have any ideas to propose.

**Comment by boukenka** [comment]
Closing the issue.
