### ISSUE TITLE
Confirm Modal keyboard events issue

### ISSUE THREAD

**Issue by shirleen1234** [ant-design-blazor/ant-design-blazor#1762]
### Describe the bug

Confirm modal keep popping up when pressing "Enter" or "Space" key on keyboard.

![confirm-modal](https://user-images.githubusercontent.com/47659614/126734939-17ed3356-8025-4ff3-80fa-3cde453f7576.gif)

### Steps to reproduce (please include code)

Refer to [Ant Design Blazor Docs](https://antblazor.com/en-US/components/modal)

**Comment by zxyao145** [comment]
Hi, this will be fixed in PR #1838. 
And I'm sorry, C# doesn't have undefined in JS, and null is used to set that neither the OK nor Cancel buttons are focused, so you must manually set the AutoFocusButton parameter to take effect.

**Comment by shirleen1234** [comment]
> Hi, this will be fixed in PR #1838.
> And I'm sorry, C# doesn't have undefined in JS, and null is used to set that neither the OK nor Cancel buttons are focused, so you must manually set the AutoFocusButton parameter to take effect.

Noted, thanks a lot.
