### ISSUE TITLE
Table filtering possibilities (Field and DataIndex properties in <Column> at the same time)

### ISSUE THREAD

**Issue by kuznecovIT** [ant-design-blazor/ant-design-blazor#1764]
### Describe the bug (Help request)
_After many attempts, I still have not succeeded in realizing what I am asking about here.
In general, if is there such a possibility, please help!_

### What I trying to realize 
I have a table, in one of the columns I need to display data from the method and be able to sort by this field
Below I presented the table code where I marked the problem field with #### preffix

#### Table
```
<Table @ref="_table"
       TItem="TemplateModel"
       DataSource="TemplateModels"
       Total="TotalTemplates"
       @bind-PageIndex="_pageIndex"
       @bind-PageSize="PageSize"
       OnPageIndexChange="PageIndexChanged">
    
    <Column @bind-Field="@context.Id" Sortable DefaultSortOrder="SortDirection.Ascending" Filterable/>
    <Column TData="DateTime?" @bind-Field="@context.CreationDate" Sortable Filterable />
    <Column TData="DateTime?" @bind-Field="@context.DueDate" Format="dd.MM.yyyy" Sortable Filterable/>
    <Column TData="TemplateStatus" @bind-Field="@context.Status" Sortable Filters="_statusesFilter" OnFilter="(a, b) => a == b"/>
    #### <Column Title="TypeCode" DataIndex="TemplateTypeId" Sortable Filters="_templatesFilter"/>
```
#### How it works now 
Filters works! But numbers are displayed instead of a code name
![image](https://user-images.githubusercontent.com/62954135/126739522-68adec3a-4a4e-4df6-9342-656ec204d842.png)

#### What column type i need instead of marked
`<Column TData="string" Title="TypeCode" Field="@GetTemplateTypeCodeById(@context.TemplateTypeId).Result" DataIndex="TemplateTypeId" Sortable Filters="_templatesFilter"/>`

By `Field="@GetTemplateTypeCodeById(@context.TemplateTypeId)` i tryin to have such a result (with filters like on screenshot which is presented before
![image](https://user-images.githubusercontent.com/62954135/126739236-4be30891-8d2f-439a-80bd-8cc8b3df2600.png)

It works if i have Column like 
`<Column TData="string" Title="Код типа шаблона" Field="@GetTemplateTypeCodeById(@context.TemplateTypeId).Result"  Filterable/>`

But if i click on filter icon the page will freeze and the page will need to be reloaded

#### _templateFilters code
```
List<TableFilter<long?>> _templatesFilter = new List<TableFilter<long?>>();

    void FillTemplatesFilter()
    {
        if (TemplateTypes == null) return;
        foreach (var templateType in TemplateTypes)
        {
            _templatesFilter.Add(new TableFilter<long?>() {Text = templateType.Code, Value = templateType.Id});
        }
    }
```

#### TemplateModel code
```
public class TemplateModel : ITemplate   
{
    public long Id { get; set; }
    
    public long? TemplateTypeId { get; set; }
    
    public DateTime? CreationDate { get; set; }
    
    public DateTime? UpdateDate { get; set; }
    
    public DateTime? DueDate { get; set; }
    
    public TemplateStatus Status { get; set; }
}
```

#### TemplateType code
```
public class TemplateType : ITemplate
{
    public long Id { get; set; }  
    public string Code { get; set; }
    public string Description { get; set; }
}
```

#### Method that provide name of Template Type by Id  
(it is made so awful to be passed to the table as a parameter : ) )
```
public Task<string> GetTemplateTypeCodeByIdTask(long? id) =>
            Task.Run(() => GetTemplateTypeCodeById(id));

public string GetTemplateTypeCodeById(long? id) =>
            TemplateTypes.FirstOrDefault(type => type.Id == id)?.Code;

```

### After all
I am asking for help or hints for the implementation that provide possibility of simultaneously displaying code instead of numbers and working filtering with code names

Unfortunately, I can't post the entire project, because  I don't have a MOCK database to provide you with a working example 
(presently the data is taken from an API to which there is no external access)

**Comment by anranruye** [comment]
@kuznecovIT thanks for contacting us.

I think what you need is 
```
<Column Title="TypeCode" DataIndex="TemplateTypeId" Sortable Filters="_templatesFilter">
    @(GetTemplateTypeCodeById(@context.TemplateTypeId).Result)
</ Column>
```

Then I want to say a few more words. I don't think the way you get the type code `GetTemplateTypeCodeById(@context.TemplateTypeId).Result` is efficient, this will cause perfomence issue when you have a lot of rows or the table component renders frequently. A better solution is to include a `public TemplateType TemplateType { get; set; }` navigation property in `TemplateModel` class, then you can use:
```
<Column Title="TypeCode" DataIndex="TemplateType.Code" Sortable Filters="_templatesFilter">
</ Column>
``` which will use the code to sort and filter directly(you should also modify the filters),
or
```
<Column Title="TypeCode" DataIndex="TemplateTypeId" Sortable Filters="_templatesFilter">
    @context.TemplateType.Code
</ Column>
``` which still use the id to sort and filter, but display the code

**Comment by kuznecovIT** [comment]
Yes, that's exactly what I need!
As usual, everything turned out to be quite simple :)
