### ISSUE TITLE
Clear all table filters with button

### ISSUE THREAD

**Issue by MuffinTheDragon** [ant-design-blazor/ant-design-blazor#1767]
### Describe the solution you'd like
I am trying to have a button that when clicked, clears all the sorters and filters in a table. I know this can be done in Ant Design React by managing the filter and sorter information in the state. In Blazor, you can use the QueryModel to read the current sorters and filters applied, but I can't find a way to be able to clear that information and reset the table

**Comment by anranruye** [comment]
@MuffinTheDragon thanks for contacting us.

It's not difficult for us to provide a method to clear all the filters. But there are more work to do to take full control of filter functions.

**Comment by MuffinTheDragon** [comment]
Ok, that's understandable. I'll keep an eye out for future updates.

One last thing, the table documentation mentions certain properties like "sortOrder" and "defaultFilteredValue" but trying to actually use them in code raises an InvalidOperationException. I was wondering are these properties something that will be updated later as well?

**Comment by anranruye** [comment]
@MuffinTheDragon Of course. You can use them or something alternative once we finish this feature.

**Comment by MuffinTheDragon** [comment]
Ok great. I'll keep an eye out for future updates. Thanks!
