### ISSUE TITLE
[Tree] Incorrect checkbox state on the TreeNode due to an optimization inside UpdateCheckState()

### ISSUE THREAD

**Issue by lukblazewicz** [ant-design-blazor/ant-design-blazor#1770]
https://github.com/ant-design-blazor/ant-design-blazor/blob/cbe94d10d8642a5e4a36ad0e89d42e47ac53042a/components/tree/TreeNode.razor.cs#L343

This line of code results in an incorrect checkbox state in the tree's root node as in the following example:
![image](https://user-images.githubusercontent.com/39852149/126827043-c7859041-7d94-430a-98b9-e85ff2821c1f.png)

Steps to reproduce:
1. Check _root_ to have all the subnodes checked as well.
2. Uncheck one of the nested children inside _child 2_ to get an indeterminate (half-checked) state on  _child 2_ (correct one).
3. Uncheck _child 1_ entirely. This should make _root_ indeterminate (half-checked) but it becomes fully unchecked instead.

My assumption is that the aforementioned `break;` in `UpdateCheckState()` prevents the loop from verifying all the children. Without going through all the child nodes, it concludes there is no checked node among them (as it gives up after the first, unchecked node, stopping on the second, indeterminate one).

**Comment by lukblazewicz** [comment]
Just to confirm - the issue is still present in the 0.9.0 release.

**Comment by ElderJames** [comment]
Thanks for contacting us @lukblazewicz .

If you know how to fix it, just feel free to submit a PR. 
We would like to fix it together.

**Comment by ElderJames** [comment]
Thank you.
