### ISSUE TITLE
In the Tree component, when a selection item changes, it causes the SelectedDataChanged event to be fired twice.

### ISSUE THREAD

**Issue by scugzbc** [ant-design-blazor/ant-design-blazor#1772]
![动画](https://user-images.githubusercontent.com/8499347/126862290-d32073ca-b1a2-4959-9b17-29f2be708f04.gif)
这个是逻辑是这样的：
在点击一个节点时候，异步加速这个节点下对应的值。如果没有选择任何节点，就显示所有的值。
网络请求对应的是：GetEquipmentsByAreaID/ 这个就表示没有参数，对应的就是没有选择任何节点。
                                 【GUID】的对应的就是选中了某个节点。
结果就是每次直接点击切换不同节点时，实际是经过了    取消选中（显示所有节点）--》选中某一个（显示当前节点的）。  这样就会因为两个异步请求的返回时间不同，造成有时候看起来选中了某个节点，但是显示的是没有选中任何节点时的值。
SelectedNodeChanged 事件是一样的，当然直接用@bind-SelectedData 也是一样的。

感觉这是一个程序员角度正确，但是在业务角度是错误的行为。

**Comment by ElderJames** [comment]
Thanks for contacting us @scugzbc 
Which version are you using? We fixed some issues with the tree in the feature branch. Please install the 0.9.0 nightly version to test it out if you wish.

**Comment by ElderJames** [comment]
你好，请帮忙看看0.9.0解决了没有？
Please help to see if there is still this issue in 0.9.0.

**Comment by scugzbc** [comment]
之前是 0.8.3 .
现在升级到0.9.0之后，问题依旧。

**Comment by ElderJames** [comment]
@scugzbc Hi, it has been fixed in 0.9.2.
