### ISSUE TITLE
SearchExpression missing on Tree

### ISSUE THREAD

**Issue by lukblazewicz** [ant-design-blazor/ant-design-blazor#1787]
The new Tree component available since 0.9.0 release has no SearchExpression parameter (which was present on previous versions of this component). 

We use this parameter in our production app for customized filtering - can we bring it back? Or there is another way advanced filtering should be done now?

**Comment by ElderJames** [comment]
Thanks for contacting us @lukblazewicz .

We would bring it back, or you can help?
