### ISSUE TITLE
When using the Upload component in the Dialog popped up by ModalService, clicking on the Upload button will trigger an OnCancel of the Dialog, causing the form to close abnormally.

### ISSUE THREAD

**Issue by scugzbc** [ant-design-blazor/ant-design-blazor#1793]
版本为 0.9.0
在ModalService弹起的Dialog里使用Upload组件时，点击上传按钮，会触发Dialog的OnCancel ,导致窗体非正常关闭。
相关的代码如下：
在主页面上弹出一个Dialog的代码。 注意里面加入了 Console.WriteLine的输出用以测试。

```
 private async Task OpenUpdateDialog(Guid id)
    {

        var result = await AdminUserService.GetDetail(id);
        if (!result.IsSuccess)
        {
            await MessageService.Error($"可能已经删除或无效,请刷新页面后重试,错误原因:{result.ErrorMessage}");
            return;
        }
        ModalOptions options = new ModalOptions();
        options.Title = "修改管理员信息";

        options.AfterClose = async () => { await Init(); StateHasChanged(); };
        options.OnCancel = async (e) => {  await modal.CloseAsync(); Console.WriteLine("Cancel--------");};
        options.OnOk = async (e) => { await modal.CloseAsync(); Console.WriteLine("Ok--------");};
        options.OkText = "确定";
        options.CancelText = "取消";
        modal = await ModalService.CreateModalAsync<EditAdminUser, AdminUserDTO>(options, result.Data);
    }
```
 

Upload就是一个最基本的调用。
效果如图所示：
![upload](https://user-images.githubusercontent.com/8499347/127643440-1484e68e-c04e-4f28-8245-e1f1f36b6058.gif)

**Comment by anddrzejb** [comment]
Can you check if you have any errors in console (either dotnet or browser)? If you do, can you post them?

**Comment by ElderJames** [comment]
May be caused by mask onclick event

**Comment by zxyao145** [comment]
非常抱歉，我无法重现这个bug，请问能提供下demo吗？

Sorry, I can't reproduce this bug. Can you provide a demo?

```

    ModalRef modalRef;
    private async void ShowModal()
    {
        Console.WriteLine("Show modal");

        ModalOptions options = new ModalOptions();
        options.Title = "修改管理员信息";

        options.AfterClose = async () => { StateHasChanged(); };
        options.OnCancel = async (e) => { await modalRef.CloseAsync(); Console.WriteLine("Cancel--------"); };
        options.OnOk = async (e) => { await modalRef.CloseAsync(); Console.WriteLine("Ok--------"); };
        options.OkText = "确定";
        options.CancelText = "取消";
        modalRef = await ModalService.CreateModalAsync<ModalTemplate, string>(options, " result.Data");

    }

```

**Comment by scugzbc** [comment]
[TestUpload.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/6909072/TestUpload.zip)
这里全部采用文档里提到的内容构建了一个demo.
可以重现这个过程。

**Comment by zxyao145** [comment]
Upload组件通过`HTMLElement.click()`打开选择文件对话框，`HTMLElement.click()`方法不会触发mousedown/up事件，因此导致Modal组件错误的关闭。

The Upload component opens the file selection dialog box through 'HtmlElement.Click()'. But The 'HtmlElement. Click()' method will not trigger the mousedown/up event, resulting in the shutdown of the Modal component  error.

**Comment by zxyao145** [comment]
目前最好的做法是讲 `MaskClosable` 参数设置为 false，后面我们将会考虑使用JS解决这个问题，还是使用C#以减少与JS的交互。

At present, the best way is to set the 'MaskClosable' parameter to false. Later, we will consider using JS to solve this problem or improve c# to reduce the interaction with JS.

**Comment by ElderJames** [comment]
Already fixed in master branch, please wait for 0.9.1 release.
