### ISSUE TITLE
The rendering issue with ServerPrerendered mode

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#181]
> When prerendering is enabled, JavaScript interop calls can only be performed during the `OnAfterRenderAsync` lifecycle method.

Currently, setting the `RenderMode` to `Server` in `_Host.cshtml` file can solve this problem. Like this:

```
@(await Html.RenderComponentAsync<App>(RenderMode.Server))
```

**Comment by ozzioma** [comment]
This affects other components like Row, Form,Drawer etc.
Any plan to fix when RenderMode is set to ServerPrerendered?

This might be a show stopper, especially when AntBlazor is used alongside other 3rd party component libaries.

**Comment by ElderJames** [comment]
Thank you for contacting us @ozzioma .

This is a tricky issue, and we need to get a handle on when to use JS to subscribe to the events. 
We plan to test and fix it in the next milestone.

**Comment by ozzioma** [comment]
@ElderJames 

I think the error message offers a clue, have you considered checking for first rendering?
That is the recommended way to detect when a Blazor Server app is pre-rendering.
For example...
```
protected override Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
       //subcribe to JS events
    }
    return Task.CompletedTask;

}.
```

Also check this out

> To delay JavaScript interop calls until after the connection with the browser is established, you can use the OnAfterRenderAsync component lifecycle event. This event is only called after the app is fully rendered and the client connection is established.

**Comment by yuanxiongwei** [comment]
Want to know when it can be used normally

**Comment by yuanxiongwei** [comment]
Please solve as soon as possible.

**Comment by ElderJames** [comment]
Hi @yuanxiongwei ,we will fix it next month, please use server mode first.

**Comment by yuanxiongwei** [comment]
hi @ElderJames ,I'm glad to hear from you and i'm sorry to tell you.  my project uses  server mode。The Form and Grid component  is not working properly。so I'm anxious.

error info:

> InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.


> Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(long asyncHandle, string identifier, string argsJson)
Microsoft.JSInterop.JSRuntime.InvokeAsync<TValue>(string identifier, CancellationToken cancellationToken, object[] args)
Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation<T>(string identifier, object[] args)
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
AntDesign.AntComponentBase.JsInvokeAsync<T>(string code, object[] args)
AntDesign.Row+<>c__DisplayClass33_0+<<SetGutterStyle>b__0>d.MoveNext()
AntDesign.EnumerableExtensions.ForEachAsync<T>(IEnumerable<T> items, Func<T, Task> func)
AntDesign.Row.SetGutterStyle()
AntDesign.Row.OnInitializedAsync()
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)

**Comment by ElderJames** [comment]
Hi, @yuanxiongwei ,please use servrer mode in `_Host.cshtml ` file, like this:

```
        @(await Html.RenderComponentAsync<App>(RenderMode.Server))
```

**Comment by yuanxiongwei** [comment]
@ElderJames The update will run successfully. please update the guidelines for getting started, the guidelines do not mention this
