### ISSUE TITLE
Class parameter not applying for Input and AutoComplete

### ISSUE THREAD

**Issue by quirynen** [ant-design-blazor/ant-design-blazor#1814]
### Describe the bug

While Assigning the Class parameter to an Input or AutoComplete, the class is not applied to the html tag.

### Steps to reproduce (please include code)

```
<Input Bordered="false" TItem="string" @bind-Value="Name" Class="methods__inputNumber" />
<AutoComplete  TItem="string" @bind-Value="Name" Class="methods__inputNumber" Options="options" />
```

The methods__inputNumber css class is not applied to the html tag (input in this case), even after a few forced refreshs, rebuilds, and rebooting computer.

### Further technical details
- AntDesign Nuget Package version : 0.9.0

**Comment by JohnHao421** [comment]
I've fixed this problem because `GetStyle` was called too early in color property and a PR will be committed later

**Comment by ElderJames** [comment]
Thanks for contacing us @quirynen 

Would you be interested in helping to fix this problem?

**Comment by quirynen** [comment]
Hi apparently it was already fixed, I received this in my mail _"I've fixed this problem because GetStyle was called too early in color property and a PR will be committed later"_

**Comment by ElderJames** [comment]
@quirynen This is another issue #1846 .
