### ISSUE TITLE
A table with many columns do not scroll smoothly

### ISSUE THREAD

**Issue by LiuyangRY** [ant-design-blazor/ant-design-blazor#1821]
### Describe the bug

I am refactoring a page contains table with  about 50 columns, I find the table will not scroll smoothly, and the situation get worse and worse with the amount of data increases.
I wonder know how to improve this situation without changing the original table structure.
Thanks a lot!

### Steps to reproduce (please include code)
<!--
We ❤ code! Point us to a minimalistic repro project hosted in a GitHub repo.
For a repro project, create a new ASP.NET Core project using the template of your your choice, apply the minimum required code to result in the issue you're observing.

### Further technical details
- AntDesign 0.9.0
- VS 2019

**Comment by ElderJames** [comment]
Thanks for contacting us @LiuyangRY 

We have built in a lot of functionality to the Column component, which is performance-depleting compared to native html.
So if you want to have so many columns, you necessarily need to use the most primitive way.

Our table can't use cells with simplified functionality for now, so I suggest you use the native html table element.

**Comment by anddrzejb** [comment]
From what I can see in the table & column component, there are at least 2 low hanging fruits in terms of performance optimizations:
1. Avoid using anonymous lambda's that capture variables inside a loop (in tables there are almost always loops, even if not directly) [(source)](https://github.com/dotnet/aspnetcore/issues/18919#issuecomment-815019336)
2. Prefer primitive types in `[Parameter]`.
2a. Often there is no way to provide the same rich functionality with primitive types. But a solution here would be to use a type that has the ability to effortlessly discover if it really was changed and make appropriate adjustment to `SetParameters` life cycle event and/or `ShouldRender` event to prevent unneeded renderings. This is actually pretty complex and time consuming. Especially when it comes to such complex component as `Table`. 

The guys that are often working with `Table`: @anranruye & @ElderJames maybe you could slowly, as you make the fixes, replace the lambdas with methods?

**Comment by anranruye** [comment]
@anddrzejb 

One thing I am confused is: is it reasonable for the components to rerender when scroll? In fact, I'm not sure whether they really rerender or not. 

One possibility is that the components don't need to rerender, but there are too many component objects in the page, which is the real cause of low performance.

And I didn't compare the performance of raw html and table/column component yet. I guess raw html will be fast. But I'm afraid the performance can't be better if we just simpfy the component implement.

**Comment by anddrzejb** [comment]
@anranruye Actually I think you are right. The whole table is probably rendered before scrolling happens. If we ever manage to do virtualization, then scrolling might indeed be a factor, but should not be a factor now.
Nevertheless - I think my points are still valid for performance reasons, even if not for the scrolling. I am curious though what will your raw html tests show.

**Comment by ElderJames** [comment]
I have been avoid the rendering when table scroll.

https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/table/Table.razor.cs#L366

@LiuyangRY Please try 0.9.2

**Comment by LiuyangRY** [comment]
@ElderJames 
I have updated the ant design blazor version from 0.9.0 to 0.9.2, but the browser console shows many errors "'domInfoHelper' was undefined". 
How can I solve the problem? 
Here is the screenshot about the problem:
![Snipaste_2021-08-24_10-36-53](https://user-images.githubusercontent.com/39262714/130547059-67caf2a8-cf35-4dee-98d6-02f1fe7512a5.png)

**Comment by ElderJames** [comment]
@LiuyangRY Maybe you nee to clear the cache of browser.

**Comment by LiuyangRY** [comment]
Now, The vertical scroll is all ready fit my requirement, but the horizontal scroll button will lag a moment when leaving the endpoints( both left and right arrow icon). if the scroll action is not starting from the endpoints, the performance of scroll will be much better.
Maybe the opportunity of rendering during scroll can be changed to improve the performance a lot.

**Comment by LiuyangRY** [comment]
I have also found that the paging component can't work well. The table could not render new data immediately when I click the other page number, I have to wait a few moments although the data have already been fetched from server.
I guess this is also a render problem.

**Comment by ElderJames** [comment]
Yes, we have fixed it at the last change.

**Comment by LiuyangRY** [comment]
Thanks for all replies and help, it do help me a lot, best wishes to all of you.

**Comment by ElderJames** [comment]
@LiuyangRY The pagination issue has been fix in 0.9.3, please have a try.

**Comment by LiuyangRY** [comment]
@ElderJames I have tried the pagination component, it does work better than before. 
The horizontal scroll still lags a moment when the scroll button reaches the left or right endpoint.
![image](https://user-images.githubusercontent.com/39262714/131275737-70de0193-e767-48b5-95e8-6e2875d55d6b.png)

**Comment by ElderJames** [comment]
This is because when the Fixed column style is displayed, the table is refreshed once.

**Comment by LiuyangRY** [comment]
How can I set the table to solve the problem?

**Comment by LiuyangRY** [comment]
This means the problem could not be avoided  if I use the fixed column?

**Comment by LiuyangRY** [comment]
@ElderJames  Is this means the problem could not be avoided if I use the fixed column?

**Comment by ElderJames** [comment]
We could probably put this logic into JS to handle it, which would improve performance
