### ISSUE TITLE
Update table total count when using filters

### ISSUE THREAD

**Issue by MuffinTheDragon** [ant-design-blazor/ant-design-blazor#1832]
Hi, 

I want to get a count of how many rows are in a table after filtering. I've tried using the Total and @bind-Total properties, but they don't seem to update the count at all.  

Is there some other way to accomplish this or could I be using the properties incorrectly?

**Comment by anranruye** [comment]
@MuffinTheDragon thanks for contacting us.

Which version of ant-design-blazor are you using? Could you provide a minimal repro?

**Comment by MuffinTheDragon** [comment]
Hi,

I am using version 0.8.4. Here's a snippet example. The default total is 3, but if I try to filter the table by Tag and say pick "Test", there's only one result that shows up in the table. But the total still says 3. Is there a way for the total to become 1?

```
<AntDesign.Table DataSource="table"
                 TItem="TableInfo"
                 @bind-Total="_total">

    <Column TData="int"
            @bind-Field="context.Id"
            Filterable>

    </Column>

    <Column TData="string"
            @bind-Field="context.Name"
            Filterable>

    </Column>

    <Column TData="string"
            @bind-Field="context.Tag"
            Filters="customFilters"
            Filterable>

    </Column>
</AntDesign.Table>

Total: @_total


@code {

    private int _total = 3;

    class TableInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }

    }

    TableInfo[] table =
    {
            new TableInfo {Id = 1, Name = "Bill", Tag = "Dev"},
            new TableInfo {Id = 2, Name = "Bob", Tag = "Test"},
            new TableInfo {Id = 3, Name = "Jim", Tag = "Dev"}
    };


    public TableFilter<string>[] customFilters = new TableFilter<string>[]
    {
            new TableFilter<string> { Text = "Test", Value = "Test"},
            new TableFilter<string> { Text = "Dev", Value = "Dev"},
    };
}

```

**Comment by anranruye** [comment]
@ MuffinTheDragon You can try the new 0.9 version.

**Comment by anranruye** [comment]
@ MuffinTheDragon You can try the new 0.9 version and use `@bind-Total`.

**Comment by anranruye** [comment]
@ MuffinTheDragon You can try the new 0.9 version and use `@bind-Total`.

**Comment by anranruye** [comment]
@ MuffinTheDragon You can try the new 0.9 version and use `@bind-Total`.

**Comment by anranruye** [comment]
@ MuffinTheDragon You can try the new 0.9 version and use `@bind-Total`.

**Comment by MuffinTheDragon** [comment]
Yup, switching to version 0.9.2 works! Thank you.
