### ISSUE TITLE
TreeNode HasChildNodes is now internal on 0.9

### ISSUE THREAD

**Issue by reescal** [ant-design-blazor/ant-design-blazor#1833]
From 0.8.4 to 0.9 TreeNode's HasChildNodes was changed from public to internal. Line 42 [here](https://github.com/ant-design-blazor/ant-design-blazor/blob/e4e3bf24d5241d66b51ffd2479a2c26ad7e53e61/components/tree/TreeNode.razor.cs)
Was that intentional? If it was, what is the suggested replacement? DataItem.Items.Any()?
Also, if it is brought back in the future, maybe it should use .Any() instead of .Count() as suggested by LINQ for performance?

**Comment by ElderJames** [comment]
Thanks for contacting us @reescal .
You can use `IsLeaf` to determine if the node has children nodes. If `IsLeaf=false` then it has  children nodes.
