### ISSUE TITLE
is the DotNetObjectReference will cause memory leak in DomEventService.cs?

### ISSUE THREAD

**Issue by tonyyip1969** [ant-design-blazor/ant-design-blazor#1834]
Try to understand the code below (extracted from ./components/core/JsInterop/DomEventService.cs from line 42 to 70), is the DotNetObjectReference will cause memory leak? 

As referring to the article here https://www.syncfusion.com/faq/blazor/components/how-can-i-properly-dispose-a-component-in-blazor, the dotNetObject must be dispose to avoid memory leaks.

```
    DotNetObjectReference.Create(new Invoker<T>((p) => { callback(p); }));
```

```
        public virtual void AddEventListener<T>(object dom, string eventName, Action<T> callback, bool exclusive = true, bool preventDefault = false)
        {
            if (exclusive)
            {
                _jsRuntime.InvokeAsync<string>(JSInteropConstants.AddDomEventListener, dom, eventName, preventDefault, DotNetObjectReference.Create(new Invoker<T>((p) =>
                {
                    callback(p);
                })));
            }
            else
            {
                string key = FormatKey(dom, eventName);
                if (!_domEventListeners.ContainsKey(key))
                {
                    _domEventListeners[key] = new List<DomEventSubscription>();

                    _jsRuntime.InvokeAsync<string>(JSInteropConstants.AddDomEventListener, dom, eventName, preventDefault, DotNetObjectReference.Create(new Invoker<string>((p) =>
                    {
                        for (var i = 0; i < _domEventListeners[key].Count; i++)
                        {
                            var subscription = _domEventListeners[key][i];
                            object tP = JsonSerializer.Deserialize(p, subscription.Type);
                            subscription.Delegate.DynamicInvoke(tP);
                        }
                    })));
                }
                _domEventListeners[key].Add(new DomEventSubscription(callback, typeof(T)));
            }
        }
```

**Comment by ElderJames** [comment]
Thanks for contacting us @tonyyip1969 .

I think you are right, it would cause memory leak here.

Because we wanted to implement delegate callbacks, which was not a best practice at the time, this could be attributed to the fact that we hadn't implemented it perfectly in the early days.

Would you be interested in helping us fix it? Feel free to PR!

**Comment by tonyyip1969** [comment]
Hi @ElderJames , I will try to fix it but before that, I not quite understand the logic in the else block, appreciated you can give me some hints.

**Comment by ElderJames** [comment]
Sure.
This method is mainly used to reduce JS interop and reuse js event subscriptions, so that the same event can be subscribed by multiple callback delegates.
