### ISSUE TITLE
Upload component documentation does not reflect implementation

### ISSUE THREAD

**Issue by SapientGuardian** [ant-design-blazor/ant-design-blazor#1852]
### Describe the bug

https://antblazor.com/en-US/components/upload#API

The documentation for the Upload component describes a different API than what is implemented. For example, it says that the http method can be customized with the `method` parameter, but no such parameter exists on the Upload component, and the underlying typescript method (https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/core/JsInterop/modules/components/uploadHelper.ts#L60) has `post` hard-coded.

### Steps to reproduce (please include code)
```
<Upload Action="https://httpbin.org/put"
                            Drag
                            Method="put"
                            OnSingleCompleted="OnUploadCompleted">
                        <p class="ant-upload-drag-icon">
                            <Icon Type="inbox" />
                        </p>
                        <p class="ant-upload-text">Click or drag file to this area to upload</p>                    
                    </Upload>
```

### Exceptions (if any)
`System.InvalidOperationException: Object of type 'AntDesign.Upload' does not have a property matching the name 'Method'.`

### Further technical details
- AntDesign Nuget Package version (0.9.2)

**Comment by ElderJames** [comment]
Thanks for contacting us @SapientGuardian 

Our documentation was originally copied from antd react, so there may be some APIs that have not been implemented.
If you need to use another method, feel free to submit a PR to add this attribute!
