### ISSUE TITLE
Table date filter should just use year, month and day to filter 

### ISSUE THREAD

**Issue by iamSmallY** [ant-design-blazor/ant-design-blazor#1854]
It's a similar problem with #1806 .

I think a filter with time will make it difficult for users to use. Usually the data is filtered at the day level, not accurate to the second. So the time part should be removed here, and the problem in #1806 should be avoided. 

我认为一个带时间的筛选器会让用户使用起来很困难, 通常筛选数据都在日期级别上进行, 而不会精确到秒. 所以此处应该去除时间部分,并避免发生如 #1806 中的问题.

If you agree with this issue, I am glad to try to submit a pull request.

如果你认同这个issue, 我很乐意尝试提交pr.

**Comment by ElderJames** [comment]
Yes, PR is welcome!

**Comment by ElderJames** [comment]
It may be necessary to implement a separate column, `DateColumn` or `TimeColumn`

**Comment by iamSmallY** [comment]
I plan to implement a `DateColumn`, because the existing `Column` does not pay attention to the number of milliseconds in the data when Filtering, resulting in the Equal option not working. This may be a difficult job for me, I will try my best to complete it.
