### ISSUE TITLE
Texarea bug autosize and minrows

### ISSUE THREAD

**Issue by bqhai199x** [ant-design-blazor/ant-design-blazor#1869]
When I using AutoSize and MinRows at once => MinRows not worked

**Comment by anddrzejb** [comment]
@bqhai199x Sorry, I am unable to recreate the issue. I tried on both wasm & server-side:
![textAreaAutosizeMinRows](https://user-images.githubusercontent.com/6518006/132119236-7c8e06fb-6c7f-43af-9892-85dda826b7c8.gif)

What version of AntBlazor are you using? Try clearing browser cache. If the problem persist, can you produce a minimal repro?

**Comment by bqhai199x** [comment]
9.0 AutoSize = false => MinRows not worked

**Comment by anddrzejb** [comment]
From what I can tell, `MinRows`/`MaxRows` are the parameters of AutoSize. So basically you cannot have `MinRows`/`MaxRows` and `Autosize = false`. This probably need to be included in the documentation. Also we should produce a compiler warning when this situation occurs.
Can you explain to me exactly what is you are trying to achive? What kind of behavior you were expecting when `AutoSize = false` & `MinRows = {some integer}`?

**Comment by bqhai199x** [comment]
I think <Texarea MinRows="4"/> same <texarea rows="4"></texarea> but I don't want it auto size

**Comment by anddrzejb** [comment]
I actually started working on adding `Rows` property. But for now a workaround that I think should get you what you want is to put `MinRows = 4` & `MaxRows = 4`.
