### ISSUE TITLE
Table filter and sort does not work

### ISSUE THREAD

**Issue by nikolaykrondev** [ant-design-blazor/ant-design-blazor#1874]
### Describe the bug

After the latest release the table filtering and sorting stopped working.

### Steps to reproduce (please include code)
With latests nuget version `0.9.2` run table example with sorting and filtering -> select filter or sorting on any column -> nothing happens.
[Reproduce on demo site in data index section](https://antblazor.com/en-US/components/table#components-table-demo-data-index)
<img width="544" alt="image" src="https://user-images.githubusercontent.com/5111043/130771281-82e2b4b4-a894-45a6-87da-035ce28a9200.png">

### Exceptions (if any)
N/A

### Further technical details
- AntDesign Nuget Package version `0.9.2`
- Include the output of `dotnet --info` 
```shell
➜ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.403 [/usr/local/share/dotnet/sdk]
  3.1.404 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version `JetBrains Rider 2021.2 Build #RD-212.4746.113`

**Comment by nikolaykrondev** [comment]
Seems like the bug was introduced with the latest modifications in `Table.razor.cs` when you moved to `InternalRender`.

I will prepare a PR that fixes it, is it okey @ElderJames ?

**Comment by ElderJames** [comment]
Thank you, please check this commit https://github.com/ant-design-blazor/ant-design-blazor/commit/e1e6111f35e718236aa441a25d7cb239363b7bd2 whether have fixed this issue. If not, welcome to PR.
