### ISSUE TITLE
Experienced exception while using generic type as TItem in Select component

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#1899]
Hi guys,

I try to bind a list of Option<int?> (`Option<T>` is defined by me and it is a generic type with 2 props Value and Text) to Select as bellow

```
<AntDesign.Select 
TItemValue=@(int?)
TItem=@(Option<int?>)
	@bind-Value=@Model.DocumentType
	DefaultActiveFirstOption=@false
	AllowClear>
	<SelectOptions>
		@foreach (var o in DocumentTypeOptions)
		{
			<AntDesign.SelectOption TItemValue=@(int?)
						TItem=@(Option<int?>) 
Value="@o.Value" 
Label="@o.Text"></AntDesign.SelectOption>
		}
	</SelectOptions>
</AntDesign.Select>
```

I am hitting an exception which is thrown at line 192 bellow

![image](https://user-images.githubusercontent.com/177045/131429143-3cdea301-7639-482c-835e-7b8b3ecf2491.png)

Because TItem is Option<int?> and TItemValue is int?, obviously the TItemValue type cant be converted to the TItem type.

Not sure it is a bug or i set up something wrong? Could you please advise?

**Comment by anranruye** [comment]
@ldsenow thanks for contacting us.

You should use
```
<AntDesign.SelectOption TItemValue=@(int?) TItem=@(int?) Value="@o.Value" Label="@o.Text"></AntDesign.SelectOption>
```

**Comment by ldsenow** [comment]
@anranruye It works after changing the TItem type. However, why do I need to set the DefaultValue? Otherwise, the item is selected on initial load. I thought the bind-Value should do the job

**Comment by ldsenow** [comment]
I figure out why. My DataSource is getting from server side and is set after the Value is set. It is causing the item is not selected.

**Comment by anranruye** [comment]
Then #1906 may fix this.

**Comment by ldsenow** [comment]
@anranruye thanks.

I work around it by checking if the DataSource has been initialized before showing the Select.
The other issue did confirm my assumption. If i followed the issue correctly, the issue is about when DataSource is changed what the behaviors should be.

This is actually quite complex and I think keep a consistent behavior is better than the lib to handle all. 

I am happy if the behavior is set the Value default or DefaultValue if cannot be located in DataSource. Since I know this rule, I will make sure the datasource is initialized before rendering. 

If I intend to change the DataSource e.g. remove certain entries based on other input, I can foresee the selected value will be reset. 

This explains why if I set the DefaultValue, the control will pick up the item. Otherwise, it is null.
