### ISSUE TITLE
The datePicker will extend beyond the edge of the screen

### ISSUE THREAD

**Issue by SmRiley** [ant-design-blazor/ant-design-blazor#1928]
### Describe the bug
The date picker goes beyond the edge of the screen when it is in the extra part of the card
![A5(LS5F0HGVNV7%E7BA$MRC](https://user-images.githubusercontent.com/45205313/132630598-2f503d78-2868-4c9c-b71e-7ecb498b92a5.png)
This should be the normal style-by antd pro:
![(Z{)25T )Q8HNUW%V6QOC{2](https://user-images.githubusercontent.com/45205313/132630621-7a5345ca-6e48-4073-92bd-1302a17eaa5a.png)

- AntDesign Nuget Package version : 0.93

**Comment by anddrzejb** [comment]
This issue will be solved by PR #1848, at least to some degree. In scenarios mentioned in #1789 (mobile device & range picker), we do not have any solution yet. You can test by running the preview in the aforementioned PR.
