### ISSUE TITLE
grid (row) gutter dose not work

### ISSUE THREAD

**Issue by rennner** [ant-design-blazor/ant-design-blazor#1958]
https://ant-design-blazor.gitee.io/zh-CN/components/grid#components-grid-demo-Gutterx

**Comment by ElderJames** [comment]
Thanks for contacting us @rennner 

This is a problem caused by dictionary case, for now workaround using the following:

```
    Dictionary<string, int> gutter = new(StringComparer.OrdinalIgnoreCase)
    {
        ["xs"] = 8,
        ["sm"] = 16,
        ["md"] = 24,
        ["lg"] = 32,
        ["xl"] = 48,
        ["xxl"] = 64
    };
```

**Comment by rennner** [comment]
thank you for @ElderJames
