### ISSUE TITLE
the tree component  can not  using OnClick and SearchValue at the same time?

### ISSUE THREAD

**Issue by rennner** [ant-design-blazor/ant-design-blazor#1959]
using onclick and SearchValue at the same time:
1. Click any node and all nodes will be collapsed
2. The default expansion does not work, and the default is retracted
----------------------------------------------------------------------------------
同时使用OnClick和SearchValue出现异常情况：
1、点击任意node，所有节点会被收起Collapse，期望是点击后该节点被选中即可。
2、默认的展开不起作用，默认都是收起状态。

**Comment by ElderJames** [comment]
Hi, please provide a demo or code snippets to repro the issue.

**Comment by rennner** [comment]
这个demo 可以重现第一个问题，第二个问题这个demo重现不了，后续如果确实是控件的问题再给您反馈。

@page "/treedemo"

<Search Placeholder="检索" @bind-Value="@searchKey"
        DebounceMilliseconds="300" AllowClear="true"
        EnterButton="true" />

<Tree ShowIcon
      BlockNode="false"
      Checkable="false"
      SearchValue="@searchKey"
      MatchedClass="site-tree-search-value"
      TitleExpression="x => x.DataItem.Title"
      ChildrenExpression="x => x.DataItem.Childs"
      IconExpression="x=>x.DataItem.Icon"
      KeyExpression="x => x.DataItem.Key"
      IsLeafExpression="x => x.DataItem.Childs == null"
      DataSource="TreeNodes"
      TItem="DemoNode"
      Style="height: calc(100vh - 200px)"
      ShowExpand="true"
      DefaultExpandAll="false"
      DefaultExpandParent="true"
      DefaultSelectedKeys="@DefaultSelectedKeys"
      DefaultExpandedKeys="@DefaultExpandedKeys"
      ExpandedKeys="@DefaultExpandedKeys"
      AutoExpandParent="true"
      OnClick="SelectNodeChanged"
  >
</Tree>
<style>
    .site-tree-search-value {
        color: #f50;
    }
</style>

@code {
    class DemoNode
    {
        public string Key { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; } = "tag";
        public List<DemoNode> Childs { get; set; }
    }

    string[] DefaultSelectedKeys = new string[] { "0-0-0"};
    string[] DefaultExpandedKeys = new string[] { "0-0" };

    string searchKey="";

    List<DemoNode> TreeNodes = new List<DemoNode>
    {
        new DemoNode{
            Key="0-0",
            Title="node 0-0",
            Childs= new List<DemoNode>
            {
               new DemoNode{Key="0-0-0" ,Title="0-0-0"},
               new DemoNode{Key="0-0-1" ,Title="0-0-1"},
               new DemoNode{Key="0-0-2" ,Title="0-0-2"},
            }
        },
        new DemoNode{
            Key="0-1",
            Title="node 0-1",
            Childs= new List<DemoNode>
            {
               new DemoNode{Key="0-1-0" ,Title="0-1-0"},
               new DemoNode{Key="0-1-1" ,Title="0-1-1"},
               new DemoNode{Key="0-1-2" ,Title="0-1-2"},
            }
        }
    };

    private void SelectNodeChanged(AntDesign.TreeEventArgs<DemoNode> node)
    {
        //nothing to do
    }
}

**Comment by wuzhenda** [comment]
solution？@renner

**Comment by ElderJames** [comment]
It works well currently. 
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/20c4a437-0456-439e-a23a-49ce54d10fe0)
