### ISSUE TITLE
Drag and Drop Upload component content is not centered

### ISSUE THREAD

**Issue by MiroslavKabat** [ant-design-blazor/ant-design-blazor#1969]
Not sure if bug or feature.

### Description
Drag and Drop Upload component content is not centered.

### Reproduce
Open your sample page [Upload Component](https://antblazor.com/en-US/components/upload) zoom out page and look at

![image](https://user-images.githubusercontent.com/34449536/134509129-e2dce117-f8fd-4b17-accd-03f046cd3a1d.png)

### Further technical details
- AntDesign Nuget Package version 0.10.0
- .NET SDK: Version:   5.0.401 | Commit:    4bef5f3dbf

**Comment by ElderJames** [comment]
Thanks for contacting us @MiroslavKabat ,this is a great discovery.

Would you be interested in helping to fix it?

**Comment by anddrzejb** [comment]
Looks like this line
https://github.com/ant-design-blazor/ant-design-blazor/blob/ed5d9449462f473bcad76a1953a219802a679983/components/upload/UploadButton.razor#L5

should be replace with a span so when rendered, it will look like this 
```html
<span tabindex="0" class="ant-upload ant-upload-btn" role="button">
```
At least in the drag&drop scenarios, but this should actually be confirmed with react AntDesign. @MiroslavKabat would you like to create a PR for that?

**Comment by MiroslavKabat** [comment]
I am not good in UI design and frontend in general. That is the reason why I am using AntBlazor. I will be happy if PR will be made by frontend developers. I am sorry for that and thank you for fixing that issue.

**Comment by anddrzejb** [comment]
As you wish. As a word of encouragement - I am a backend dev as well. This project was and continue to be a great learning experience for me. I would like to think that by now I have became a fairly knowledgeable blazor dev thanks to diving into AntBlazor internals. I am not pushing - you will do as you wish. Worst case scenario - this bug will take some time to fix.
