### ISSUE TITLE
The menu of select only display for 1 second then disappear

### ISSUE THREAD

**Issue by dennyling2020** [ant-design-blazor/ant-design-blazor#1976]
When you click the drop-down arrows of select, it displays the menu for only 1 second and it disappears. Howe, if you click the space, it works fine. 

You can repeat this issue on the official page. (https://antblazor.com/zh-CN/components/select)

**Comment by anddrzejb** [comment]
I imagine you refer to this problem:
![chevronFailed](https://user-images.githubusercontent.com/6518006/135033817-ec653e39-c6f1-49dd-bea1-5df854dbd928.gif)
