### ISSUE TITLE
How to implement upload file API

### ISSUE THREAD

**Issue by wf-soft** [ant-design-blazor/ant-design-blazor#1978]
Is there a simple example to receive the files transmitted by the upload component in the API controller or somewhere, and is there a content format to be returned

**Comment by wf-soft** [comment]
I think I already know how to use it. Close this problem

**Comment by wf-soft** [comment]
Sorry

**Comment by anddrzejb** [comment]
Would you be willing to add entry in [Show & Tell](https://github.com/ant-design-blazor/ant-design-blazor/discussions/categories/show-and-tell)?

**Comment by SmRiley** [comment]
> Would you be willing to add entry in [Show & Tell](https://github.com/ant-design-blazor/ant-design-blazor/discussions/categories/show-and-tell)?

https://github.com/ant-design-blazor/ant-design-blazor/discussions/2149
I have added a case, hope it helps others
