### ISSUE TITLE
Paragraph returns a Unicode encoded string when copying Chinese

### ISSUE THREAD

**Issue by fengqiaoyexia** [ant-design-blazor/ant-design-blazor#1981]
Bazlor 代码:
`                
<Paragraph Copyable>[任务号]：@context.Data.TaskNumber</Paragraph>
                <Paragraph Copyable>[第三方任务号]：@context.Data.ThirdPartyTaskNumber</Paragraph>
                <Paragraph Copyable>[起始位置]：@context.Data.StartLocation</Paragraph>
                <Paragraph Copyable>[目标位置]：@context.Data.TargetLocation</Paragraph>
                <Paragraph Copyable>[任务消息]：@context.Data.TaskMessage</Paragraph>
                <Paragraph Copyable>[数据备注]：@context.Data.DataDescribe</Paragraph>
`
点击复制按钮,其中的中文字段会转变为 形如 : &#x63A5;&#x6536;&#x8D85;&#x65F6;&#x65F6;&#x95F4;
的Unicode乱码

**Comment by anranruye** [comment]
现在的实现确实有些问题, 复制的是html, 和用光标选中之后再复制效果是不同的

目前的解决方法是用CopyConfig去自定义要复制的文本 https://ant-design-blazor.gitee.io/zh-CN/components/typography#components-typography-demo-Interactive

但这样复制的是纯文本, 就没有格式了, 复制到记事本等纯文本的场景是没问题的, 想要带着格式复制到word里就不行了
