### ISSUE TITLE
How to use the Upload control to call the Stream API

### ISSUE THREAD

**Issue by SmallChi** [ant-design-blazor/ant-design-blazor#1983]
[Microsoft Demo](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&pivots=server#file-streams-1)

InputFile Control:

```1
    private async void LoadFiles(InputFileChangeEventArgs e)
    {
            using var memoryStream = new MemoryStream();
            Stream fs =e.File.OpenReadStream();
            await fs.CopyToAsync(memoryStream);
            Assembly assembly = Assembly.Load(memoryStream.ToArray());
    }
```
Upload  Control:

```2
    private async void OnSingleCompleted(AntDesign.UploadInfo uploadInfo)
    {
          Stream fs =uploadInfo.File.OpenReadStream();
          await fs.CopyToAsync(memoryStream);
          Assembly assembly = Assembly.Load(memoryStream.ToArray());
    }
```

**Comment by anranruye** [comment]
Thanks for contacting us.

We don't support this feature yet.

**Comment by ElderJames** [comment]
Please use Blazor build-in `InputFile`

**Comment by SmallChi** [comment]
Currently used with built-in `inputfile`,but ugly😂, this Upload control is not intended to support?

**Comment by anranruye** [comment]
@SmallChi you can use a transparent InputFile to do what you need and use Upload to display the ui.

**Comment by SmRiley** [comment]
> Currently used with built-in ,but ugly😂, this Upload control is not intended to support?`inputfile`

maybe u can use that :
`<span class="ant-upload-picture-card-wrapper">
    <label class="avatar-uploader" for="upload">
        <div class="ant-upload ant-upload-select-picture-card ant-upload-select">
            <div tabindex="0" class="ant-upload" style="position:relative;">
                <InputFile id="upload" hidden/>
                <div>
                    <Icon Spin="loading" Type="@(loading?"Loading":"plus")"></Icon>
                    <div className="ant-upload-text">Upload</div>
                </div>
            </div>
        </div>
    </label>
</span>`

**Comment by ElderJames** [comment]
Hello @SmallChi , now we support use built-in InputFile with Upload.

https://antblazor.com/en-US/components/upload#components-upload-demo-input-file
