### ISSUE TITLE
Multiple Submenu Menu Items Highlighted

### ISSUE THREAD

**Issue by Gareth064** [ant-design-blazor/ant-design-blazor#1986]
### Describe the bug

I have a Menu with a Submenu.
When I click on one of the Menu Item's in the Submenu, it is highlighted as expected.
But when I click on another one, both of them are now Highlighted and not just the last of clicked.

![MenuItemsStayHighlighted](https://user-images.githubusercontent.com/22307223/135449425-e690c859-e417-4add-95d3-955dd642e78b.gif)

### Steps to reproduce (please include code)
```html
        <Menu Theme="MenuTheme.Dark" Mode="MenuMode.Horizontal" DefaultSelectedKeys=@(new[]{"1"}) Accordion=true>
            <MenuItem Key="1" RouterLink="/">Home</MenuItem>
            <SubMenu Title="Admin" Key="2">
                <MenuItem Title="Resources" RouterLink="/resources" />
                <MenuItem Title="Activity Types" RouterLink="/activitytypes" />
            </SubMenu>
        </Menu>
```

### Exceptions (if any)
When another menu item (inside a submenu) is clicked, it is the only one highlighted.

**Comment by anddrzejb** [comment]
Could you please post a minimal repro? It seems to me this bug manifests in connection with layout.

**Comment by Gareth064** [comment]
@ElderJames Is this what you mean? If So, then it appears to make it worse by applying the selected style to both menu items at the same time when only one is clicked.

![AntDesignIssue1986](https://user-images.githubusercontent.com/22307223/137580418-fe2b9378-d568-4b10-8c77-1d2388202d90.gif)

**Comment by ElderJames** [comment]
This is because you have used the same RouterLink ` #` for both menu items.

**Comment by Gareth064** [comment]
Ok so leaving one RouteLink as '#' and changing the other to '/' it now works as expected (in the demo repo)
Once I am back to work on Monday, I will update the project there with the RouterMatch code to see if it resolves the issue too.
