### ISSUE TITLE
can not locallize the left sidebar menu by the default full demo

### ISSUE THREAD

**Issue by charleypeng** [ant-design-blazor/ant-design-blazor#2008]
I have created the full demo by using "dotnet new antdesign -ho server --full"
I found the BasicLayout.razor file had a "data/menu.json" path to get the menu data, but where  can I find the file or is it just generated automatically?    How  can I  localize the menubar into a different language?  

thanks for help.

**Comment by ElderJames** [comment]
The file is in wwwroot, and you can change the title to a resouce key, and replace them with StringLocalizer before assingning to MenuItems.
