### ISSUE TITLE
Table: applying a predefined QueryModel to table

### ISSUE THREAD

**Issue by AnaNikolasevic** [ant-design-blazor/ant-design-blazor#2015]
### Ability to apply a saved table configuration - setting QueryModel (PageIndex, PageSize, SortModel, FilterModel)
I would like to offer users to save their table configuration (QueryModel), and later to apply saved filter and configurations. With that feature users would not have to set filters every time. 

For example, I would do json serializing of Query Model and save that string in database and later I would take and deserialize that string. In OnChange method inside table I would set current QueryModel to deserialized one from database. Unfortunatlly deserializing and making new QueryModel is not possible because it's properties are getter-only, so I didn't find way to apply saved configuration. I am open to any suggestions or ideas how it can be implemented!

**Comment by ElderJames** [comment]
That's a good news!

For sorters, you can see what the `DefaultSortOrder` did.
For filters, you can try to set `_hasFilterSelected = true`.

**Comment by AnaNikolasevic** [comment]
Thank you for your help. Feature is done, so I would like to make PR and get your review on it, I am open to improve my code based on your advices. I commited my changes, but when I tried to push branch which I made, I got message that I don't have permission for it. Is there any steps that I should follow to make PR?

**Comment by ElderJames** [comment]
That's great!

You need to fork this repo to your account,then phsh your commits to the repo at your account.
Last, create the PR from the page of your repo.

**Comment by dennisrahmen** [comment]
Does this also include the page size of the table?

**Comment by ElderJames** [comment]
@dennisrahmen I think so.

**Comment by AnaNikolasevic** [comment]
> Does this also include the page size of the table?

Yes, this feature allows you to apply preset sorting, filters, page size and page index.

**Comment by ElderJames** [comment]
@AnaNikolasevic Please check the nightly build.

**Comment by AnaNikolasevic** [comment]
> @AnaNikolasevic Please check the nightly build.

Hello, I checked the nightly build with my solution but unfortunately the table is not displayed at all. I also switched to the `feature `branch and run AntDesign solution but the whole Table component is not rendered and I got this error:
`Unhandled exception rendering component: The type 'AntDesign.Column 1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' declares more than one parameter matching the name 'cellrender'. Parameter names are case-insensitive and must be unique.`

If there is anything else that I should adjust, check or fix, please let me know. Also you can contact me at my email: 23nikolasevic@gmail.com

**Comment by tale80** [comment]
very interesting feature, when it will be released i will try it on my solution and can make feedback (if needed) :)
thanks a lot for your job on this topic @AnaNikolasevic !

**Comment by ElderJames** [comment]
Hi all, this feature has been released in 0.11.0 !
