### ISSUE TITLE
Form and upload components working together

### ISSUE THREAD

**Issue by dazinator** [ant-design-blazor/ant-design-blazor#2051]
### Is your feature request related to a problem? Please describe.
I'm new to ant blazor. I'd like to create a `form` where one of the input's allows a user to also select a file, this file will be submitted when the form is submitted.

I have checked the `form` example on the docs site but it does not show selecting a file as one of the inputs.
I have checked the `upload` exmple, but that seems to upload the file independently and doesn't show submitting the file contents together with form inputs to the server.

Usually the way I see this working is with a multipart request. The form data is submitted in one part, and the file is submitted as a seperate part, on the same request. The server receives one request, and in the case of asp.net core api, is able to retrieve and validate the form data, as well as the file and save it in one transaction / roundtrip.

Is there some example of doing this with ant blazor?
On my form I'd also like to validate that:

- The file to be uploaded / submitted has only a particular file extension
- The file to be uploaded / submitted is < x bytes in size.

### Describe the solution you'd like
I'd like the docs to show some `form` examples where an upload component is being used to allow a file to be submitted with the form, potentially with validation around the file extension selected, and file size.

**Comment by ElderJames** [comment]
The upload component is upload files using xhr, and you can get the file urls from server response, then you can submit your from within these urls.
