### ISSUE TITLE
Click the drop down button to expand the options and then close the options, so it cannot be selected normally

### ISSUE THREAD

**Issue by fan0217** [ant-design-blazor/ant-design-blazor#2058]
Select 选择器点击下拉按钮先展开选项随即又关闭选项，无法正常选择。

`<Select DataSource="@(resultsClasses)" 
                        @bind-Value="@(_resultsClassID)"
                        LabelName="@nameof(Models.BasicData.ResultsClass.ResultsClassName)"
                        ValueName="@nameof(Models.BasicData.ResultsClass.ResultsClassID)"
                        DefaultActiveFirstOption="@(true)"
                        Placeholder="选择成果大类">
                </Select>`

**Comment by anranruye** [comment]
Any progress?
