### ISSUE TITLE
Select component performance

### ISSUE THREAD

**Issue by Henxun** [ant-design-blazor/ant-design-blazor#2080]

**Comment by ldsenow** [comment]
I also experience similar issue in my country list. You can feel the delay for UI to show up the list or select an item.

**Comment by Henxun** [comment]
if you use dotnet 6， try this   https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0

**Comment by ElderJames** [comment]
@Henxun Thank you for the advice, can this solve your problem please?

**Comment by m-khrapunov** [comment]
@ElderJames Please look at #2654. First-time contributors need a maintainer to approve running workflows...
