### ISSUE TITLE
Nullreference on startup of WASM at AlertComponent

### ISSUE THREAD

**Issue by MathieuDR** [ant-design-blazor/ant-design-blazor#2082]
### Describe the bug

Nullreference at AntDesign.Alert.OnAfterRenderAsync on first load starting the debug session. Using WASM host, and not using the Alert funcionality. This is, I think blocking my 'OnInitialized' chain.

### Steps to reproduce (please include code)
https://github.com/MathieuDR/ResourceCalculator/tree/main/ResourceCalculator/Web

Files to note:

- [Program.cs](https://github.com/MathieuDR/ResourceCalculator/blob/main/Web/Program.cs)
- [Index.razor](https://github.com/MathieuDR/ResourceCalculator/blob/main/Web/Pages/Dashboard/Analysis/Index.razor)
- [Index.razor.cs](https://github.com/MathieuDR/ResourceCalculator/blob/main/Web/Pages/Dashboard/Analysis/Index.razor.cs)
- [BasicLayout.razor](https://github.com/MathieuDR/ResourceCalculator/blob/main/Web/Layouts/BasicLayout.razor)

### Exceptions (if any)
```Unhandled exception rendering component: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object. at AntDesign.Alert.OnAfterRenderAsync(Boolean firstRender) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)```

![image](https://user-images.githubusercontent.com/1561671/140445616-9b984d04-ebed-4db3-9c81-1561464b3e9d.png)

### Further technical details
- AntDesign Nuget Package version: 0.10.1
- Rider, latest version

```.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by anddrzejb** [comment]
@MathieuDR What was the solution? I was hoping to have a look at this today.

**Comment by MathieuDR** [comment]
> @MathieuDR What was the solution? I was hoping to have a look at this today.

I could not find a solution. It was something on my end since when i ran the boiler template again the issue was resolved. You can look at the commit history if you would still want to figure this out.
