### ISSUE TITLE
Is it the code to switch languages like this?

### ISSUE THREAD

**Issue by qcjxberin** [ant-design-blazor/ant-design-blazor#2093]
![image](https://user-images.githubusercontent.com/5792218/140695582-750e66b9-5555-44b2-bcaf-6775f35c4db8.png)

**Comment by ElderJames** [comment]
Hi @qcjxberin , you can try.  Maybe it need to call `StateHasChanged` at MainLayout.

**Comment by qcjxberin** [comment]
At present, there is another problem that is returning to the default language of the browser after refreshing. Is there any way to keep the switched language after switching?

**Comment by ElderJames** [comment]
You can persist it to localstorage

**Comment by LeaFrock** [comment]
Sorry for the interruption but... what's the meaning of `switch-case` here? Why not directly use `CultureInfo.xxx = CultureInfo.GetCultureInfo(item.Key)`?

**Comment by qcjxberin** [comment]
@ElderJames The current test found that the refresh will fall back to the current browser language.

**Comment by ElderJames** [comment]
cc @anranruye

**Comment by anranruye** [comment]
You should change CultureInfo.DefaultThreadCurrentUICulture and CultureInfo.CurrentUICulture to switch current language. However, exsisting ant component will not be affacted, only components generated after this switch use the new language. To affact all components in the page, you may need to refresh with the browser(or you can use blazor built-in navigate feature to navigate to another page then navigate back to the current page). To keep the switched language after refresh, as @ElderJames said, you can save your choice to localstorage, and apply this language during app component initializing.

**Comment by knight1219** [comment]
I've created a redirect page that takes a query string parameter of the route to go to. It allows me to cause a "page update" without triggering a full reload of Blazor. This helps when updating global settings (in my instance it was time zone) and needing to effect the change.

I've had great

**Comment by anranruye** [comment]
Closing this since this issue is not active.
