### ISSUE TITLE
Not icon arrow for first SubMenu MenuMode.Horizontal

### ISSUE THREAD

**Issue by ardia** [ant-design-blazor/ant-design-blazor#2100]
![Not icon arrow for first SubMenu](https://user-images.githubusercontent.com/5411424/140876988-5706b8fe-0988-445b-908c-e573cfc97068.png)

**Comment by anddrzejb** [comment]
From what I can tell, it follows the [AntD design](https://ant.design/components/menu/#components-menu-demo-horizontal). We might add it as an enhancement?

**Comment by ElderJames** [comment]
Can using TitleTemplate to add icons by yourself.
