### ISSUE TITLE
Prevent  body element style to add width: calc(100% - 17 px) on show modal?

### ISSUE THREAD

**Issue by mrjohnr** [ant-design-blazor/ant-design-blazor#2102]
Hi,It possible to prevent  body element style to add  width: calc(100% - 17 px);   on show modal?
that is causing some problems to our design in mobile view
thanks

**Comment by mrjohnr** [comment]
Hi,on dektop browser,put it on mobile S,then navigate to [modal example](https://antblazor.com/en-US/components/modal)
open modal and pay attention to  main page,when you open/close modal it will resize
see in image 1  text "Open modal with a" and see it in image 2 after modal is opened is shown more text "Open modal with asy" you can see 'sy'(width is changed)
see in image 1 ModalService.Confirm() text position and see it in image 2 after modal is opened
![1](https://user-images.githubusercontent.com/11148089/145593239-4011cdc2-7cf8-4971-a551-fc59caf5fe71.png)
![2](https://user-images.githubusercontent.com/11148089/145593249-5be87495-fc16-47de-ba29-bb19be26c39d.png)

thanks

**Comment by zxyao145** [comment]
fixed
