### ISSUE TITLE
New component: TableSelect Component

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#2106]
### Discussed in https://github.com/ant-design-blazor/ant-design-blazor/discussions/2101

<div type='discussions-op-text'>

<sup>Originally posted by **theilgaz** November  9, 2021</sup>
Hello everyone!

I would like to start a discussion about my highly-needed component.

|Description|Content|
|--|--|
|Component Name|TableSelect|
|Keywords|Ant design, blazor, dropdown grid, table, select, grid, multiple columns in select component|
|Short Description|A select component with dropdown data grid by using multiple columns.|
|Long Description|It should be an extension for `Select` component which select value from options. Those options can be described with multiple columns in some scenarios. <br> <br> *For Ex.* We have an object named `selectedProject` which contains the data in `Project` entity. <br> <br> Now we have a `TableSelect` which contains `selectedProject` value as an object. That `Project` object can be selected from collection supplied to `Table` located in popup of `TableSelect` component. <br> <br> In that popup view, we can search desired project by project code, name or different columns displayed in that grid. The popup grid should be same as `Table` component.|
|Example Usages|1. We can just bind a simple collection to `TableSelect`. <br> 2. Filtering by all string columns in collection. <br> 3. Multiple selections from popup Table in component. <br> 4. Custom template <br> 5. Virtualization using IQueryable <br> 6. Virtualization using OnDataSourceChanged|
|Real World Example|*For Ex.* <br> We are developing an e-commerce application. In our order page, we should find the customer. We can find our customer in `TableSelect` component filtering by Customer Id, Tax Id, Customer Name, City, Country etc. <br><br> *Here is a simple visual example for component. Grid in picture is copied from AntBlazor docs.* ![SELECT-GRID-PREVIEW](https://user-images.githubusercontent.com/13048645/140935494-ea126501-f8ce-4324-9556-f267abbe8e53.png)|</div>

**Comment by theilgaz** [comment]
Is there a roadmap for this component?
