### ISSUE TITLE
How to selecting a node in the tree using program code

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#2109]
### Describe the bug

When I click on a node in Tree, I can display the details of the node in another list.  Now, when I have updated the details in the second list, I want to reload Tree so that the changes are also displayed in Node.

How can I remind Tree which node was selected? 

I tried @bind-SelectedNode="treeNode" in the component, where I first saving the selected node at OnClickTree:

        protected async Task OnClickTree(TreeEventArgs<tvModel> args)
        {
            treeNode = args.Node;

Unfortunately, this does not work. When tree is regenerated, no node is selected anymore. Therefore, the user cannot see at first view whether his changes have been applied or not in the tree node.

### Steps to reproduce (please include code)
Populate Tree and set selected node:

                        <Tree @ref="tree" ShowIcon DataSource="tv_list"
                              TitleExpression="x => ((tvModel)x.DataItem).Text"
                              ChildrenExpression="x => ((tvModel)x.DataItem).Items"
                              @bind-SelectedNode="treeNode"
                              OnClick='e=>OnClickTree(e)' TItem="tvErfassungVerbrauchModel"></Tree>

In code behind definde treeNode
protected private TreeNode<tvModel> treeNode;

and set it in the on OnClick methode:
        protected async Task OnClickTree(TreeEventArgs<tvModel> args)
        {
            treeNode = args.Node;
        }

Just create button to refresh Tree data and you will see that no Node is selected after Tree is regenerated!
 

### Further technical details
- AntDesign Nuget Package LAST version
- Include the output of `dotnet --info`
- The IDE (VS 2019)

**Comment by ElderJames** [comment]
Hello @true-perfect-code ,I think #3243 may solved this issue.

**Comment by true-perfect-code** [comment]
Thanks @ElderJames

**Comment by true-perfect-code** [comment]
@ElderJames 
Did you receive my email last week? I sent it to your address given here in github.
