### ISSUE TITLE
Mobile website UI needed

### ISSUE THREAD

**Issue by Auzout** [ant-design-blazor/ant-design-blazor#2116]
For a company without budget to develop mobile app but want mobile office, we want blazor UI for mobile website. 
I am also appreciated if there is any open source repository suggest,.

**Comment by ElderJames** [comment]
Thanks for contacting us @gongkui .

We also don't have the budget for mobile components either.

**Comment by knight1219** [comment]
Isn't there a ant-design-mobile project that broke out and adds responsiveness to the core ant-design css? How customized is our implementation of ant design?

**Comment by SmRiley** [comment]
> Isn't there a ant-design-mobile project that broke out and adds responsiveness to the core ant-design css? How customized is our implementation of ant design?

To be honest, the native antd performance is relatively weak on the mobile terminal, but some have been compensated for in Pro. If you have the ability, you can contribute code to Pro Component

**Comment by ElderJames** [comment]
We would add some responsive style to exist components, instead to build a mobile component library.
