### ISSUE TITLE
No animations in menu component

### ISSUE THREAD

**Issue by ZlobnyiSerg** [ant-design-blazor/ant-design-blazor#2123]
### Describe the bug

I'm using horizontal menu with submenus. When moving mouse over menu items - submenu pops up. When mouse leaving - submenu hides with significant delay. Quick mouse move over horisontal menu can cause that all submenus will be visible at the same time. Original ant.design component has quick animation to hide submenus that are not longer hovered.

### Steps to reproduce (please include code)
Create horizontal menu with several items. Each item should have SubMenu.

```xml
<Menu Theme="MenuTheme.Dark" Mode="MenuMode.Horizontal">
  <SubMenu Key="sub1" Title="item1">
         <MenuItem Key="contingent" RouterLink="contingent">
                <span>sub-item 1</span>
         </MenuItem>
         <MenuItem Key="contingent" RouterLink="contingent">
                <span>sub-item 2</span>
         </MenuItem>
   </SubMenu>
   <SubMenu Key="sub2" Title="item2">
         <MenuItem Key="contingent" RouterLink="contingent">
                <span>sub-item 1</span>
         </MenuItem>
         <MenuItem Key="contingent" RouterLink="contingent">
                <span>sub-item 2</span>
         </MenuItem>
   </SubMenu>
   <SubMenu Key="sub3" Title="item3">
         <MenuItem Key="contingent" RouterLink="contingent">
                <span>sub-item 1</span>
         </MenuItem>
         <MenuItem Key="contingent" RouterLink="contingent">
                <span>sub-item 2</span>
         </MenuItem>
   </SubMenu>
</Menu>
```
Move mouse horizontally quickly over menu items

### Further technical details
- AntDesign 10.0.2

**Comment by ElderJames** [comment]
@anddrzejb  Do you have time to look at this issue?

**Comment by ElderJames** [comment]
Hi @ZlobnyiSerg , I'm sorry, we haven't had enough time to deal with this.

If you could help, please find the code here.
https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/core/Component/Overlay
https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/menu/internal

**Comment by ElderJames** [comment]
Have been fixed.
