### ISSUE TITLE
Duplicated API in MessageService.

### ISSUE THREAD

**Issue by noctis0430** [ant-design-blazor/ant-design-blazor#2125]
### Is your feature request related to a problem? Please describe.

Duplicated API in `MessageService`: `MessageService.Warning()` vs `MessageService.Warn()`.

### Describe the solution you'd like
Remove `MessageService.Warn()`.

**Comment by anranruye** [comment]
We describe both apis in the documentation, so this is just by-design.

**Comment by noctis0430** [comment]
Why there's a need for an alias?

**Comment by anranruye** [comment]
this is just following ant design react. of course we can remove one of the two methods, but I myself don't think that's necessary. @ElderJames what's your opinion?
