### ISSUE TITLE
AntDesign.Select<,> will throw an exception when Mode = "tags", and TItem is a complex type.

### ISSUE THREAD

**Issue by bofwind** [ant-design-blazor/ant-design-blazor#2126]
### Describe the bug

When use Select control for a multi-choice feature, follow the sample of (https://ant-design-blazor.gitee.io/zh-CN/components/select) but use a complex type instead the String type of the sample code.

Run the page, input anything in Select control for filter the options.
an exception will be thrown.

if change the Mode to "Default"/"Multiple", it works fine.

**Steps to reproduce**
basically same with the sample code.
```
<Select Mode="tags"
        Placeholder="Please select"
        @bind-Values="@_selectedValues"
        TItemValue="C1"
        TItem="C1"
        OnSelectedItemsChanged="OnSelectedItemsChangedHandler"
        EnableSearch>
    <SelectOptions>
        @foreach (var item in _items)
        {
            <SelectOption TItemValue="C1" TItem="C1" Value=@item Label=@item.Name />
        }
    </SelectOptions>
</Select>
@code
{
    class C1
    {
        public string Name { get; set; }
        public string ID { get; set; }
    }
    List<C1> _items;
    IEnumerable<C1> _selectedValues;

    protected override void OnInitialized()
    {
        const int min = 10;
        const int max = 36;
        _items = new List<C1>();

        for (var i = min; max > i; i++)
        {
            var value = Convert.ToString(i, 16).PadLeft(2, '0') + i.ToString();
            _items.Add(new C1() { ID = i.ToString(), Name = value });
        }

        _selectedValues = new List<C1> { _items.First() };
    }

    private void OnSelectedItemsChangedHandler(IEnumerable<C1> values)
    {

    }
}
```

**We will close this issue if:**
User input for filter shouldn't throw exception when Mode=tags, and TItem is a complex type.

**### Exceptions**
Error: System.NotSupportedException: TypeConverter cannot convert from System.String.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
   at AntDesign.SelectBase`2.<>c.<.ctor>b__189_0(String label)
   at AntDesign.Select`2.FilterTagsOptionItems(String searchValue)
   at AntDesign.Select`2.FilterOptionItems(String searchValue)
   at AntDesign.Select`2.OnInputAsync(ChangeEventArgs e)

**### Further technical details**
- AntDesign 0.10.2
- VS2019 Enterprise/Blazor server side.

**Comment by anranruye** [comment]
You need to use `CustomTagLabelToValue` to generate a value for the tag item.

**Comment by bofwind** [comment]
CustomTagLabelToValue has been tried already. And also tried OnSearch , all no effects for this issue.

**Comment by anranruye** [comment]
this works:
```
<Select Mode="tags"
        Placeholder="Please select"
        DataSource="_items"
        @bind-Values="@_selectedValues"
        LabelName="Name"
        OnSelectedItemsChanged="OnSelectedItemsChangedHandler"
        CustomTagLabelToValue="label => new C1 { Name = label }"
        EnableSearch>
</Select>


@code
{
    class C1
    {
        public string Name { get; set; }
        public string ID { get; set; }
    }
    List<C1> _items;
    IEnumerable<C1> _selectedValues;

    protected override void OnInitialized()
    {
        const int min = 10;
        const int max = 36;
        _items = new List<C1>();

        for (var i = min; max > i; i++)
        {
            var value = "0x" + Convert.ToString(i, 16).PadLeft(2, '0');
            _items.Add(new C1() { ID = i.ToString(), Name = value });
        }

        _selectedValues = new List<C1> { _items.First() };
    }

    private void OnSelectedItemsChangedHandler(IEnumerable<C1> values)
    {

    }
}
```
