### ISSUE TITLE
AntDesign.Select<,> control's layout display incorrect when set PopupContainerMaxHeight="50%"(percentage)

### ISSUE THREAD

**Issue by bofwind** [ant-design-blazor/ant-design-blazor#2127]
### Describe the bug

for anywhere use the Select control, and set PopupContainerMaxHeight="50%" (or other percentage values), the popup options' layout will display incorrectly.

### Steps to reproduce 
<Select 
....
PopupContainerMaxHeight="50%" />

We will close this issue if:
The layout should be correct when use percentage values for PopupContainerMaxHeight

### Further technical details
- AntDesign 0.10.2
- VS2019/Blazor Server side/ Microsoft Edge 95.0.1020.53 x64

**Comment by anranruye** [comment]
I don't think here "50%" makes any sense. What effect do you want to achieve by using a percentage value?

**Comment by anranruye** [comment]
If you intend to get "half of the window height", you can use `50vh` instead.
