### ISSUE TITLE
AntDesign.Steps shows shifts the characters in the circle 

### ISSUE THREAD

**Issue by 3sdoi** [ant-design-blazor/ant-design-blazor#2130]
### Describe the bug

When use Steps, it shows number characters in the circle shift up.
![Step](https://user-images.githubusercontent.com/94950052/143180007-3e5c41fb-1c6b-40b0-817a-6886073c1716.png)

### Steps to reproduce (please include code)

```
    <Steps Current="1">
        <Step Title="Finished" Description="This is a description." />
        <Step Title="In Progress" Subtitle="Left 00:00:08" Description="This is a description." />
        <Step Title="Waiting" Description="This is a description." />
        <Step Title="Waiting" Description="This is a description." />
    </Steps>
```

### Further technical details
- AntDesign Nuget Package version: 0.10.2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio 2022 Version 17.0.1

### Acknowledgments
Thank you for the great software

**Comment by anranruye** [comment]
Obviously we don't have this problem in the documentation page. This may be caused dy a conflict with style of other libraries. The ant design style does have conflicts with other css libraries, such as bootstrap.

**Comment by 3sdoi** [comment]
Thank you for your reply. 
I removed 'bootstrap.min.css' but it didn't change. (No other css)
I tried Visual Studio 2019 and .NET 5, displayed normaly. I think there is couse by files created Visual Studio 2022.

**Comment by anranruye** [comment]
I tried cli+.net5 and cli+.net6, both work fine. Then it seems that vs 2022 is the cause. Do you notice the difference in the files created by vs 2022?

**Comment by 3sdoi** [comment]
Some files created by vs 2022 changed from vs2019, but I couldn't find any differences that seemed to affect.

**Comment by anranruye** [comment]
Well, I can not reproduce this on my own computer with vs2022. Can you try with another machine?

**Comment by 3sdoi** [comment]
I tried two machines. It is occurred on both machines.

**Comment by anranruye** [comment]
Anyway, so far we can know this is caused by some external reason but not antdesign.
