### ISSUE TITLE
ReuseTabs close error

### ISSUE THREAD

**Issue by draculakkk** [ant-design-blazor/ant-design-blazor#2136]
### Describe the bug

When click the close tab, the console will output an error:
![image](https://user-images.githubusercontent.com/13098908/143669704-2eebc4ad-adce-4084-bc38-b7e083eadbaa.png)

### Further technical details
- AntDesign Nuget Package version: 0.10.2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:Visual Studio 2022 Version 17.0.1

**Comment by ElderJames** [comment]
Please post your code here.

**Comment by draculakkk** [comment]
just sample code of ReuseTabs , no changes

**Comment by wxjv99** [comment]
This problem can be reproduced stably using [official examples](https://github.com/ant-design-blazor/demo-reuse-tabs)

![image](https://user-images.githubusercontent.com/48554906/145185735-107dd5ad-6ce8-48b6-998b-c1a53480c4a4.png)

Does this have anything to do with whether I am still using .net5 and not upgrading to .net6?

**Comment by ElderJames** [comment]
duplicate with #2389
