### ISSUE TITLE
ReuseTabsRouteView has no excluded routing features

### ISSUE THREAD

**Issue by shuangbaojun** [ant-design-blazor/ant-design-blazor#2137]
Background:
Jumping from the login page to the home page resulted in an extra Luoyou on the home page tab page：
![Uploading image.png…]()

What about excluding login routes as follows?

**Comment by ElderJames** [comment]
Please use `@attribute [ReuseTabsPage(Ignore=true)]`

**Comment by shuangbaojun** [comment]
Thank you for your answer.
According to the answer you gave, in my local prompt missing reference, please ask me here need to refer to what components?

![image](https://user-images.githubusercontent.com/64063254/143800629-0d3e5421-7c26-48fb-8a2b-f19629031780.png)

**Comment by ElderJames** [comment]
Update the package to 0.10.3

**Comment by shuangbaojun** [comment]
The problem is resolved and should be caused by my local version that is not up-to-date, thank you for your answer.

**Comment by shuangbaojun** [comment]
Thank you, the problem is solved.
