### ISSUE TITLE
typo in docs/introduce.zh-CN.md

### ISSUE THREAD

**Issue by HUGHNew** [ant-design-blazor/ant-design-blazor#2140]
### Locate the typo

[location](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/docs/introduce.zh-CN.md#%E4%BB%8E%E6%A8%A1%E6%9D%BF%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E6%96%B0%E9%A1%B9%E7%9B%AE)

The last item on the head of the form has a typo

It should be "默 认 值" instead of "认 值"(It seems  miswriting "default value" as "fault value" in English ).

**Comment by SmRiley** [comment]
If you have time, you are welcome to revise this in the document. : )

**Comment by HUGHNew** [comment]
OK, I'll help to update the documentation while learning and using.
