### ISSUE TITLE
Is there the other behave for the datepicker control?

### ISSUE THREAD

**Issue by wuyang26** [ant-design-blazor/ant-design-blazor#215]
when click the edit area,don't popup，easy for users to enter dates manually,
just click the right Icon ,then popup for select.
but now click the edit area,immediately popup,this is not good when it comes to small screens.
At the same time,click on the icon unresponsive.

**Comment by Epictek** [comment]
I believe this is out of scope of this project as the aim is to implement the ant design library from react 

https://ant.design/components/date-picker/

**Comment by ElderJames** [comment]
Thank you for contacting us @wuyang26 .
Yes, for now, our goal is to implement all the APIS for ant- design, but after that we will consider adding new features in combination with the benefits of Blazor.
If there are a lot of good people who want this feature, we can consider adding an attribute to make the switch

**Comment by wuyang26** [comment]
Date selection controls that provide manual input and drop-down selection are a common behavior，
Maybe it's not for ant design。
Your pop-up is always down, not judging by location, up or down. Even if it's ant design, I think it's inconvenient.
