### ISSUE TITLE
Cannot copy content of modal

### ISSUE THREAD

**Issue by PrzemyslawJastrowiczHomebook** [ant-design-blazor/ant-design-blazor#2155]
When you use Modal, you can't select its content.

This also occurs on official documentation:
https://antblazor.com/en-US/components/modal#components-modal-demo-basic

Is there a way to enable selecting and coping the content of the modal?

**Comment by anranruye** [comment]
You can use `user-select` css attribute on the `Modal` element or the content you want to select:
```
<Modal Title="@title"
       Visible="@_visible"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel"
       Style="user-select: initial">
    <p style="user-select: text">Some contents...</p>
    <p>Some contents...</p>
    <p>Some contents...</p>
</Modal>
```

**Comment by anranruye** [comment]
Any progress?

**Comment by PrzemyslawJastrowiczHomebook** [comment]
Yes it worked! thank you very much
