### ISSUE TITLE
How is routing permission control implemented?

### ISSUE THREAD

**Issue by shuangbaojun** [ant-design-blazor/ant-design-blazor#2160]
hi，
How does ReuseTabsRouteView control routing permissions?
If you use the AutorizeRouteView collection antb content can't be displayed.

**Comment by anranruye** [comment]
See https://github.com/ant-design-blazor/ant-design-blazor/tree/master/src/AntDesign.Components.Authentication

**Comment by shuangbaojun** [comment]
Thank you for your answer.

Current component library version: AntDesign 0.10.2.
According to the documentation you gave, you added HonorizeReuseTabsRouteView, but it is not indicated that this component does not exist, as shown in the following figure:

![image](https://user-images.githubusercontent.com/64063254/146112012-cedeec4f-22f2-454c-9d62-7b8501549389.png)

**Comment by anranruye** [comment]
This new route view component is not part of `AntDesign` lib. It is in another project and a new nuget package. But the publish of that package failed. You can use the source code directly.

**Comment by ElderJames** [comment]
fixed in https://github.com/ant-design-blazor/ant-design-blazor/issues/2160
