### ISSUE TITLE
Consider replacing Console.WriteLine with ILogger in components

### ISSUE THREAD

**Issue by rodion-m** [ant-design-blazor/ant-design-blazor#2161]
Hey, thank you for a great components! \
But what is that? https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/menu/SubMenu.razor.cs#L90 \
And also I found few Console.WriteLine calls in components: https://github.com/search?q=Console.WriteLine+repo%3Aant-design-blazor%2Fant-design-blazor+path%3A%2Fcomponents&type=Code&ref=advsearch

**Comment by rodion-m** [comment]
If we need just for debug logging purpose, let's replace it with `ILogger<>` dependency and log data using `LogDebug` method. It's just not right to use Console anywhere you want - it's not flexible and it's not supported by all platforms.

**Comment by knight1219** [comment]
I think this is a great idea. Would you want to submit a pull request to update these?

**Comment by jkaddo91** [comment]
Hello, I'm new to OSS. I'd love to work on this.

**Comment by speyck** [comment]
@DevJonie are you still working on this? Otherwise, I'd be happy to fix this.

**Comment by ElderJames** [comment]
Not yet, please.
