### ISSUE TITLE
Input or Textarea components cannot modify values through js

### ISSUE THREAD

**Issue by berkerdong** [ant-design-blazor/ant-design-blazor#2164]
<Input Id="Content"  @bind-Value="@context.Content"/>

When using native js to modify the value of value after positioning through id, the value on the web page UI seems to have changed, but the value of the C# variable bound to the component has not changed synchronously. But this is normal in the native input component, the error only appears in the Input component of Ant

document.getElementById('Content').value=123456;
document.getElementById('Content').dispatchEvent(new Event('change'));

I have tried the following but it doesn’t work
document.getElementById('Content').dispatchEvent(new Event('input'));
document.getElementById('Content').dispatchEvent(new Event('keydown'));
document.getElementById('Content').dispatchEvent(new Event('keyup'));

**Comment by knight1219** [comment]
Can you have your JS method call into a C# function to update the value? That would ensure all of the correct blazor lifecycle methods fire and you don't have to try and do it manually

[Documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#invoke-an-instance-net-method)

**Comment by berkerdong** [comment]
> Can you have your JS method call into a C# function to update the value? That would ensure all of the correct blazor lifecycle methods fire and you don't have to try and do it manually
> 
> [Documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#invoke-an-instance-net-method)

Well, I have used JS to call C# code in my project to solve this problem. I am more curious, why js's .dispatchEvent(new Event('eventName')) method is invalid. The same operation is native to vue and blazor. It's ok on input

**Comment by knight1219** [comment]
I'm going to take a wild guess (without having looked into the internals of blazor to know 100%) and say that blazor has a host of lifecycle events it runs through behind the scenes to get not only the inputs to wire up, but also any coded event handlers, the EditContext (if in a EditForm) and blazor needs these internal lifecycles events to happen in order to update the bounded property in the input AND also the DOM. 

But don't quote me on this.
