### ISSUE TITLE
Table column with TimePicker

### ISSUE THREAD

**Issue by vadimffe** [ant-design-blazor/ant-design-blazor#2165]
I am trying to create a table where I can add rows using a button like in your example. However in my setup one column should include TimePicker item on each row. I did it this way:

```
<Template>
  <Collapse DefaultActiveKey="@(new[] { "1" })"
            OnChange="this.Callback"
            ExpandIconPosition="@this.ExpandIconPosition"
            ExpandIcon="caret-right">
    <Panel Header="Basic information" Key="1">
      <ChildContent>
        <FormItem Label="Record title">
          <Input @bind-Value="@this.Title" />
        </FormItem>
        <FormItem Label="Description">
          <Input @bind-Value="@this.Description" />
        </FormItem>
        <FormItem Label="Content">
          <TextArea Rows="4" @bind-Value="@this.Content" />
        </FormItem>
        <FormItem Label="Date">
          <DatePicker @bind-Value="@this.SelectedDate" ShowTime="@true" OnChange="this.OnDateSelected" />
        </FormItem>
      </ChildContent>
    </Panel>
    <Panel Header="Personell" Key="2">
      <ChildContent>
        <Button OnClick="this.AddNewEmployee" Type="primary" Style="margin-bottom:16px">
          Add person
        </Button>
        <Table DataSource="this.PersonellData" RowClassName="@(_=>"editable-row")" Bordered Size=@TableSize.Small>
          <Column Title="Id" DataIndex="@nameof(context.Id)" TData="int"></Column>
          <Column Title="Name" DataIndex="@nameof(context.Name)" TData="string"></Column>
          <Column Title="From" TData="DateTime" @bind-Field="@context.From">
            <TimePicker TValue="DateTime?" Value="@context.From" />
          </Column>
          <Column Title="Category" DataIndex="@nameof(context.Category)" TData="string">
            <Select DataSource="@this.CategoryList"
                    @bind-Value="@this.selectedCategoryValue"
                    OnSelectedItemChanged="this.OnSelectedItemChangedHandler">
            </Select>
          </Column>
          <ActionColumn Title="Action">
            <Popconfirm Title="Sure to delete?"
                        OnConfirm="()=> this.DeleteEmployee(context.Id)"
                        OkText="Yes"
                        CancelText="No">
              <Button Danger>Delete</Button>
            </Popconfirm>
          </ActionColumn>
        </Table>
      </ChildContent>
    </Panel>
  </Collapse>
</Template>
```

However I am getting an exception in browser console: 

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: Please use @bind-Value (or @bind-Values for selected components) in the control with generic type `System.Nullable`1[System.DateTime]`.
> System.InvalidOperationException: Please use @bind-Value (or @bind-Values for selected components) in the control with generic type `System.Nullable`1[System.DateTime]`.
>    at AntDesign.FormItem.AntDesign.Internal.IFormItem.AddControl[Nullable`1](AntInputComponentBase`1 control)
>    at AntDesign.AntInputComponentBase`1[[System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnInitialized()
>    at AntDesign.DatePickerBase`1[[System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnInitialized()
>    at AntDesign.DatePicker`1[[System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnInitialized()
>    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

on `<TimePicker TValue="DateTime?" Value="@context.From" /> `

I think I have tried all possible solutions like adding @bind-Value="" to  `<TimePicker TValue="DateTime?" @bind-Value="@context.From" /> `, but debugger does not like it either. What is the right solution?

--------------------------------------------------------------------------------------------------------------------

Another issue is how to adjust items in the first section, so that input fields would be inline? I mean this part:

```
    <Panel Header="Basic information" Key="1">
      <ChildContent>
        <FormItem Label="Record title">
          <Input @bind-Value="@this.Title" />
        </FormItem>
        <FormItem Label="Description">
          <Input @bind-Value="@this.Description" />
        </FormItem>
        <FormItem Label="Content">
          <TextArea Rows="4" @bind-Value="@this.Content" />
        </FormItem>
        <FormItem Label="Date">
          <DatePicker @bind-Value="@this.SelectedDate" ShowTime="@true" OnChange="this.OnDateSelected" />
        </FormItem>
      </ChildContent>
    </Panel>
```
    
  I have tried to wrap it inside `<Form>` with   Layout="FormLayout.Horizontal", but it is not allowed?
  
  
![image](https://user-images.githubusercontent.com/72302395/145683686-eb77d06a-2c77-43b4-a3f8-b7074daf29aa.png)

**Comment by knight1219** [comment]
The `Form` component needs a modal set in order to properly create the `EditContext`. That could be part of your issue

Try `<Form Layout="FormLayout.Horizontal" Model="this">` and see it that helps.


Also try not using `@bind-Field` on your `Column`, but `@bind-Value` on the `TimePicker` itself.

**Comment by vadimffe** [comment]
_Also try not using @bind-Field on your Column, but @bind-Value on the TimePicker itself._

I have tried this way and I am not able to run an application, as debugger complains about exceptions.
![image](https://user-images.githubusercontent.com/72302395/145686352-80409d8b-5cf2-4a94-aa8e-014d9f00d87a.png)

_Try <Form Layout="FormLayout.Horizontal" Model="this"> and see it that helps._

Layout is still not aligned:

![image](https://user-images.githubusercontent.com/72302395/145686378-479518a4-879e-4b41-9f46-871e0adfefd8.png)

**Comment by knight1219** [comment]
Can you create a sample repo replicating this issue? I haven't been able to
reproduce.

**Comment by vadimffe** [comment]
Ok, I will create a repo and share the link here

**Comment by vadimffe** [comment]
I may got it completely wrong, but here is an example repo of what I have got so far: https://github.com/vadimffe/BlazorAppAntDemo

Just click "Create new record" on first page and try expanding sections and then "Add person". You will see exception in browser console. I think I have made some other mistakes as well?

**Comment by knight1219** [comment]
I got the error you reported. This is what I did to fix it (your repo wont let me commit)

- Set Personell.From to a DateTime?
- Use @bind-Value on the TimePicker

Once I did that, everything seemed to work. Let me know if that helps!

**Comment by vadimffe** [comment]
Alright, now I got it! Fixed and pushed into my repo. What about layout issue of the Form? How to fix that? 
I have tried your suggestion with `<Form Layout="FormLayout.Horizontal" Model="this">` but this does not seem to work?

**Comment by anranruye** [comment]
Here are the demos which you may need:
https://antblazor.com/en-US/components/form#components-form-demo-layout
https://antblazor.com/en-US/components/form#components-form-demo-complex-form-control
https://antblazor.com/en-US/components/form#components-form-demo-advanced-search

**Comment by anranruye** [comment]
Any progress?

**Comment by vadimffe** [comment]
Not really so far, I may get it working with <Row> and <GridCol> manipulation, but I have not succeeded with <Form> and <FormItem>. I think I have tried all possible solutions described in examples you provided. Maybe someone have some the most efficient solution in his pocket to get nested <FormItem> aligned?

**Comment by vadimffe** [comment]
Does anybody have some ideas? I am pretty stuck here at the moment.

**Comment by vadimffe** [comment]
By changing parent `<FormItem>` into `<div>` it seems to be working. However I think in real world nested `<FormItem>` should be allowed? Is this a bug?

I have to do it this way:
```
    <div>
      <NewRecord Content="@context.Content"
                      Description="@context.Description"
                      SelectedDate="this.SelectedDate"
                      Title="@context.Title" />
    </div>
```
instead of:

```
    <FormItem>
      <NewRecord Content="@context.Content"
                      Description="@context.Description"
                      SelectedDate="this.SelectedDate"
                      Title="@context.Title" />
    </FormItem>
```

**Comment by anranruye** [comment]
As we can see, the demos is working well in the doc page. Do you mean you can't get the same result with the demo code? Or the demo effect is not what you want?

> I may get it working with `<Row>` and `<GridCol>` manipulation

Then just use this approach, it is also recommended. If you don't need validation message, you can use `Row` and `GridCol` only.(`FormItem` uses `Row` and `GridCol` inside)
