### ISSUE TITLE
Question about Ant Design Overlay

### ISSUE THREAD

**Issue by jessielam415** [ant-design-blazor/ant-design-blazor#2168]
I am running into errors when working with ant design overlays, but am unable to pinpoint what the issue is, so I cannot reproduce the error in a demo repo. 

The error I get is "Failed to add overlay to the container", which is in line 333 of your  [overlay code file](https://github.com/ant-design-blazor/ant-design-blazor/blob/3b0e1503d8aa05424d46ea0c2037f0cc23d06bd1/components/core/Component/Overlay/Overlay.razor.cs).
`
                if (_position is null && _recurenceGuard <= 10) //up to 10 attempts`
               ` {`
                   ` Console.WriteLine($"Failed to add overlay to the container. Container: {Trigger.PopupContainerSelector}, trigger: {Trigger.Ref.Id}, overlay: {Ref.Id}. Awaiting and rerunning.");`
                  `  await Task.Delay(10);`
                  `  await AddOverlayToBody(overlayLeft, overlayTop);`
             `   }`

I'd like to understand why you decided to check up to 10 attempts for the position of an overlay and what can potentially trigger this error.

**Comment by anranruye** [comment]
Thanks for contacting us @jessielam415 .

Honestly, I myself don't know much about overlays. I can't tell you the exact reason at once.

I see that `_position` is from a js interop call.

For the retry, the most possible reason is that when this interop excutes, the related html elements are not created yet and we need to wait them be created.

If the return result is still null after 10 attempts. There are many possible causes. We want to know more context about this issue:
.NET runtime version
your browser type and version
blazor app hosting model
...

Besides, overlay is the infrastructure of many components, can you tell us which component you are working with? If you are not working with a built-in component of ant-blazor, which means you are creating your new component based on overlays, we recommend `Dropdown` component instead.

@anddrzejb do you have any ideas?

**Comment by jessielam415** [comment]
Hello, thank you for your quick response!

I am working with .NET 5.0.7. My blazor app hosting model is blazor server. The browser I use is google chrome Version 96.0.4664.110 (Official Build) (64-bit). 

I use the AntDesign dropdown as well as tooltip. Both of which embed the overlay component. I get this error when using both the tooltip and dropdown. 

This error occurs more often when I run the app on release mode and less often on debug mode. The error is also present on the deployed version of my app. 

I usually get this error after I take these steps in order, but it doesn't happen every time I do so

For dropdown
1) click on button that opens a dropdown
2) click on a dropdown option that would retrieve data from database then refresh the page
3) click on the same button that opens the dropdown again (after the page is refreshed)
4) Encounter error 

For tooltip 
1) Click on button that has a tooltip
2) Encounter error 

This is an image of the error message
![image](https://user-images.githubusercontent.com/48389380/146235392-80cf57ca-1ddf-4fa0-9a87-22eec9ea1573.png)

**Comment by anranruye** [comment]
Ok I see. Then this is really tough problem.

Did you also try to change the delay time or attempt times(by modifying the source code) or work with a different environment(another machine, wasm hosting model, .net6 runtime, different browsers, etc)?

**Comment by jessielam415** [comment]
I did try it on Firefox Version 95.0.1 (64-bit) and ran into the same issue. Additionally, my colleagues and I all use different machines but all of us ran into the same issue. 
I haven't tried working with it on .net6 runtime or the wasm hosting model. 
Also, I was not aware that I could modify the Ant Design source code when working on a project that uses Ant Design.  Would you clarify how I can do so?

**Comment by anranruye** [comment]
I mean you can download the whole project source code and build the project locally.

**Comment by jessielam415** [comment]
Hi, I have a workaround for the issue. 

For Ant design dropdown, the issue disappears when I create an empty trigger and instead use the Visible property to control whether the dropdown is visible. 

Overlay Error code:
```
                    <Dropdown Trigger="@(new Trigger[] { Trigger.Click })" Placement=Placement.BottomCenter>
                        <Overlay>
                            <Menu SelectedKeys=@null>
                                <MenuItem>
                                    <CustomMenuComponent1/>
                                </MenuItem>
                                <MenuItem>
                                    <CustomMenuComponent2/>
                                </MenuItem>
                                <MenuItem>
                                    <CustomMenuComponent3/>
                                </MenuItem>
                                <MenuItem>
                                    <CustomMenuComponent4/>
                                </MenuItem>
                            </Menu>
                        </Overlay>

                        <ChildContent>

                            <Button Type="@ButtonType.Text" style="color: white;"> Username <Icon Type="caret-down" Theme="outline"/></Button>

                        </ChildContent>
                    </Dropdown>
```

Fixed code: 
```
                    <Dropdown Trigger="@(new Trigger[] { })" Placement=Placement.BottomCenter OnClick="() => _dropdownVisible = !_dropdownVisible" Visible="_dropdownVisible">
                        <Overlay>
                            <Menu SelectedKeys=@null>
                                <MenuItem>
                                    <CustomMenuComponent1/>
                                </MenuItem>
                                <MenuItem>
                                    <CustomMenuComponent2/>
                                </MenuItem>
                                <MenuItem>
                                    <CustomMenuComponent3/>
                                </MenuItem>
                                <MenuItem>
                                    <CustomMenuComponent4/>
                                </MenuItem>
                            </Menu>
                        </Overlay>

                        <ChildContent>

                            <Button Type="@ButtonType.Text" style="color: white;"> Username <Icon Type="caret-down" Theme="outline"/></Button>

                        </ChildContent>
                    </Dropdown>
@code {
    private bool _dropdownVisible = false;
}
```

**Comment by ElderJames** [comment]
No problem now.
