### ISSUE TITLE
CheckboxGroup Value data is not two-way bound

### ISSUE THREAD

**Issue by Breave-YY** [ant-design-blazor/ant-design-blazor#2169]
```
<CheckboxGroup Class="check-box" ValueChanged="@handleChangeCheckBoxs2" Value="checks">
        @foreach(var item in initData){
         <Checkbox  Label="@item" >@item</Checkbox>
        }
    </CheckboxGroup>
    <button @onclick="handleClear">cleared</button>
@code{
     string[] checks;
    void handleChangeCheckBoxs2(string[] value){
        checks=value;
    }
    string[] initData = { "12", "123" };
    void handleClear()
    {
        checks = new string[0];
    }
}
```
checks After the data is cleared, the checkbox selection remains

**Comment by ElderJames** [comment]
Thanks for contacting us @Breave-YY 

Please try to use `@bind-Value="checks"` to binding data.

**Comment by Breave-YY** [comment]
The same, empty the selected data, the check state is still present

**Comment by Breave-YY** [comment]
After the data is emptied, it seems that the selected data will be cached, and the selected one will select all the previous data

**Comment by ElderJames** [comment]
Fine. I think this is a relatively easy fix, would you be interested in trying to fix it?
