### ISSUE TITLE
How can I filter and/or sort by items in a set (table)?

### ISSUE THREAD

**Issue by marchein** [ant-design-blazor/ant-design-blazor#2172]
Hello, I want to display items from a set in the table component. I want to filter and also sort the column with the set by the elements in the set. 
My main type of the table is a custom class `Event` and inside the table column I also use a custom type `Product`.

Currently I tried it like that:

```
<Table DataSource="Events" OnChange="OnChange" TItem="Event">
    ...
    <Column TData="ISet<Product>"
            @bind-Field="@context.Products"
            Sortable
            Filterable
            Title="Produkt(e)">
        <a>@DataHelpers.DisplayProducts(context, AllProducts)</a>
    </Column>
    ...
</Table>
```

How can I filter by the elements that are inside the set of the products column?

Thanks a lot!

**Comment by anranruye** [comment]
Thanks for contacting us @marchein 

Unfortunately, we do not support this right now with built-in filters. The built-in filters support simple types, such as primitive type and `Guid` . Obviously filtering by a collection(set) is more complicated. The only way is that you do all the jobs in the `OnChange` callback and provide a filtered/sorted datasource to the table.
