### ISSUE TITLE
Question: can we always expect parity with antd (react) stylesheets by design?

### ISSUE THREAD

**Issue by lukblazewicz** [ant-design-blazor/ant-design-blazor#2174]
Hey,

We use Ant Blazor as a foundation of our internal component library. However, to keep the ability to customize styling (colours), we omit the nuget-delivered css and use npm to fetch antd package, extract less file from there and use webpack to process it into the final stylesheet used in the app (in accordance with the following guidance: https://ant.design/docs/react/customize-theme).

So far everything works fine - we're just wondering if Ant Blazor is going to keep parity with antd stylesheets by design. We're afraid that at some point there might be a decision to go in a different direction than the react version which would invalidate our whole customization approach (by making us dependent on the css delivered via nuget).

I feel this question is actually posed towards the entire Ant Blazor community, but let me just call @ElderJames and @anddrzejb to be on the safe side in terms of including major contributors in the discussion.

**Comment by ElderJames** [comment]
Hi, thank you for using AntBlazor. 
We have been syncing the react style files and compiling them to css in nuget package, but as of 4.17.x, our previous compilation scripts are not working and have not yet been resolved. 
If you can fix this script for us, then we can resume synchronisation as soon as possible.

https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/gulpfile.js

**Comment by anranruye** [comment]
Most of the time, it's safe to use antd react styles. However, sometimes the antd react team also adjust the component html tree besides stylesheets. We are syncing the react style automaticlly but the component development work is also behind. The old HTML and the new style may have a conflict(This really happened before). If you meat this situation, you can not use the newest version style but a not so new version.

**Comment by ElderJames** [comment]
Hi @lukblazewicz ,we have solved the complie problem with the latest css of antd. And also support css variables to custom the colors. Thank you.

**Comment by ElderJames** [comment]
Hi @lukblazewicz ,we have solved the complie problem with the latest css of antd. And also support css variables to custom the colors. Thank you.
