### ISSUE TITLE
.NET 6 support？

### ISSUE THREAD

**Issue by zzwind** [ant-design-blazor/ant-design-blazor#2181]
我在NET 6的环境下使用 直接报错了

**Comment by ElderJames** [comment]
Yes, we work well in .NET6.

**Comment by anranruye** [comment]
我们需要更详细的信息

**Comment by zzwind** [comment]
我是用ant-design-pro-blazor这个模板建立的项目，貌似这个模板还没有更新到6.0喔？

**Comment by ElderJames** [comment]
Please modify the target framework to `net6`.

```
<TargetFramework>net6</TargetFramework>
```

**Comment by yang-xiaodong** [comment]
Directly modify framework from `net5` to `net6` is not working, prompting that _Host could not be found

**Comment by anranruye** [comment]
@yang-xiaodong It seems this file is missing in the project template and the target framework is not related.

**Comment by LeaFrock** [comment]
When will the Nuget package upgrade to .NET 6？

![1640225162(1)](https://user-images.githubusercontent.com/20787265/147177032-436dc45a-decd-46c1-928e-068ab46fa4e2.png)

I think specific `.net 5` support is unnecessary now. The package can upgrade support to `.net 6` and keep `.NETStandard 2.1`.

**Comment by ElderJames** [comment]
We will set the target framework to .NET6 in 0.11.0 .

**Comment by ElderJames** [comment]
> Directly modify framework from `net5` to `net6` is not working, prompting that _Host could not be found

Please put the `_Host.cshtml` file to Pages folder.

https://github.com/ant-design-blazor/ant-design-pro-blazor/blob/master/.template.config/templates/server/Pages/_Host.cshtml

**Comment by anranruye** [comment]
@LeaFrock 
> .net 5 support is unnecessary now. The package can upgrade support to .net 6 and keep .NETStandard 2.1.
Generally this suggestion is reasonable. `.net6` is the newest LTS, developers should use it for new apps and migrate their old apps to `.net6`.

However, VS 2019 doesn't support `.net6`, which is preventing people from migrating to `.net6`. 

For some reasons developers don't use VS 2022:
1. they may need to pay for VS 2022
2. VS 2022 is just released, it has many bugs
3. VS 2022 doesn't support Win7

As a result, many developers are still using `.net5`.

So we should still support `.net5` as a traget framework.

**Comment by anranruye** [comment]
@LeaFrock 
> .net 5 support is unnecessary now. The package can upgrade support to .net 6 and keep .NETStandard 2.1.
Generally this suggestion is reasonable. `.net6` is the newest LTS, developers should use it for new apps and migrate their old apps to `.net6`.

However, VS 2019 doesn't support `.net6`, which is preventing people from migrating to `.net6`. 

For some reasons developers don't use VS 2022:
1. they may need to pay for VS 2022
2. VS 2022 is just released, it has many bugs
3. VS 2022 doesn't support Win7

As a result, many developers are still using `.net5`.

So we should still support `.net5` as a traget framework.

**Comment by LeaFrock** [comment]
@anranruye Make sense. But doesn't `netstandard2.1` support `.net 5`? I don't know whether VS 2019 supports the dev environment of it. Any way, thanks for your reply 😄 !

**Comment by anranruye** [comment]
@LeaFrock of course `netstandard2.1` support `.net 5`. Exactly, `.net5` is a superset of `netstandard2.1` and provides more features.

As you can see, the `.net5` project is refering `5.x` packages and `netstandard2.1` is refering `3.x` packages. 
![image](https://user-images.githubusercontent.com/54608128/147224878-0e03922e-ce2c-45b6-a30d-bb6c98eddd83.png)

We are using the `5.x` packages features when the target framework is `.net5`. For example:
![image](https://user-images.githubusercontent.com/54608128/147225132-234b6049-ab34-41bc-8e86-e60562b581cd.png)

**Comment by anranruye** [comment]
@zzwind 现在还有什么问题吗？

**Comment by pszymkowiak** [comment]
do you have any news on this ?

**Comment by anranruye** [comment]
@pszymkowiak No, currently we don't have any features which required .net6.

**Comment by LeaFrock** [comment]
.NET 5 will end up support after `2022-05-28`, so I think our maintainers still need to upgrade VS to `2022` and add `net6` support of this project 😆

**Comment by ElderJames** [comment]
Our documentation site is already running on .NET6. The plan is to update the main library to .NET6 in v0.11.0.

**Comment by nde-agridea** [comment]
No news on this issue in a month ? When is v0.11.0 coming ? The repo does not seem very active lately. We are considering antblazor as our component library for a new long-term project, but the lack of activity is not very reassuring.

**Comment by ElderJames** [comment]
@nde-agridea  Sorry, the project members have been busy lately and we still need more people to get involved. I will be releasing v0.10.4 this weekend. The current version is compatible with .NET 6.
