### ISSUE TITLE
AuthorizeReuseTabsRouteView Nuget?

### ISSUE THREAD

**Issue by mehmetuken** [ant-design-blazor/ant-design-blazor#2185]
I can't find this components packages on Nuget?

**Comment by anranruye** [comment]
This package should have been released but it failed, at this time you can use source code directly.

**Comment by ElderJames** [comment]
It has been published at MyGet Feed. Please follow the guide to install nightly build release.

https://github.com/ant-design-blazor/ant-design-blazor/blob/master/docs/nightly-build.en-US.md

**Comment by mehmetuken** [comment]
Thanks.
