### ISSUE TITLE
Elements of dropdown of a table not entirely clickable

### ISSUE THREAD

**Issue by DrTekno** [ant-design-blazor/ant-design-blazor#2186]
### Describe the bug

Inside a table we can have a column with a build-in filter but only the square on the left of the text and the empty space on the right of the text trigger the selection of the element.
It will be nice if also the click on the text trigger the selection of the element of the dropdown.

### Steps to reproduce

On the ant documentation here:

https://antblazor.com/en-US/components/table#components-table-demo-filter

```
<Column TData="Gender"
            @bind-Field="context.Gender"
            Sortable
            Filterable />
```

If you click on 'Male' or 'Female' doesnt trigger the selection, only the square and also the space on the right of the word trigger the selection.

### Exceptions (if any)

No exceptions

### Further technical details
- AntDesign Nuget Package version 0.10.2

**Comment by anranruye** [comment]
We found this several month ago but have no ideas. And a strange thing is that this only happens for wasm environment.
