### ISSUE TITLE
Add 'select/deselect' all from build-in filters of table

### ISSUE THREAD

**Issue by DrTekno** [ant-design-blazor/ant-design-blazor#2187]
### Is your feature request related to a problem?
From the dropdown of a build-in filter is not possible to select all elements then deselect some because you need almost all of them.

### Describe the solution you'd like
A button somewhere for select/deselect all elements of the dropdown.

Thanks

**Comment by ElderJames** [comment]
Hello @DrTekno , `ITable` has `SelectAll()` and `UnselectAll()` methods now.
