### ISSUE TITLE
Visual Issue with Switch

### ISSUE THREAD

**Issue by SoraDavis** [ant-design-blazor/ant-design-blazor#2195]
### Describe the bug

In one of the more recent updates, `button`  was set to default to a background of `transparent`. Since the Switch component is based on button, developers now have to specifically set background color for when it is toggled on and off.

### Steps to reproduce (please include code)
Switched on (this is on a gray background - the Switch itself is transparent):
![image](https://user-images.githubusercontent.com/37783340/147127984-812df39a-95fd-4432-86b9-2539bc48bd51.png)
Switched off:
![image](https://user-images.githubusercontent.com/37783340/147128026-ac9baa54-7bfb-4ed5-87cd-a1db72768928.png)

When the following is added, the component looks correct again:
```
.ant-switch {
    background-color: (some gray color) !important;
}
.ant-switch-checked {
    background-color: (some blue color) !important
}
```

Switched on:
![image](https://user-images.githubusercontent.com/37783340/147129071-e977bf05-3ed7-40fc-9fc5-9ad6becd7d03.png)
Switched off:
![image](https://user-images.githubusercontent.com/37783340/147129123-6622950c-653a-44ba-ac42-8b5ea1c2830c.png)

### Further technical details
- AntDesign Nuget Package version 0.10.2

**Comment by anranruye** [comment]
Thanks for contacting us @SoraDavis 

As I see, it works well in the doc page:
![动画11](https://user-images.githubusercontent.com/54608128/147131717-01d66593-62bb-4b8a-9c8d-aece8c314f9b.gif)

Do you have other css lib which introduces the transparent background?

**Comment by SoraDavis** [comment]
Hmm.. Looks like our issue might be with Tailwind, not AntDesign.
Thanks @anranruye!
