### ISSUE TITLE
Simple Range picker filter for DateTime and Numeric columns

### ISSUE THREAD

**Issue by warcha** [ant-design-blazor/ant-design-blazor#2196]
Hi, 

I'd like to request a simple range picker filter for DateTime (dates only) and Numeric columns within a table as currently the Build-in filter is very clunky and only allows for a user to build up filters using DateTime values with time only and doesn't support numeric ranges at all.

It would be great if we could just have a Date Range Picker that would allow the selection of a start date and end date and filter for all records between those 2 dates. 

This would also be great for numeric columns, where we could specify a start value and end value and filter for all records between these 2 values.

### Is your feature request related to a problem? Please describe.
Yes, I really only need simple filtering between 2 dates currently and using the build-in filters results in the users having to build a complex filter with time values, when it would be great if they could just open a range picker and select 2 dates

### Describe the solution you'd like
For DateTime and Numeric columns, when enabling filters (Filterable) we could set a property for example RangeFiltering = true.

This would enable either a DateTime? RangeFilter for datetime columns or inputs for a start and end value  for numeric columns.

Filtering would then be applied as:

- If StartDate selected and no EndDate then filter for all rows with Date >= StartDate
- If EndDate selected and no StartDate then filter for all rows with Date <= EndDate
- If StartDate and EndDate selected then filter for all rows with Date >= StartDate && Date <= EndDate

Filtering for numeric values would be applied similarly.

### Additional context
![image](https://user-images.githubusercontent.com/19942084/147169388-6225d936-cda2-4ed8-95a1-64e28c7fd6a8.png)

![image](https://user-images.githubusercontent.com/19942084/147169428-f0dd52ca-2260-41e3-9be3-749a049826ed.png)

**Comment by anranruye** [comment]
Thanks for contacting us @warcha 

So far we have received many feature request about the table built-in filter. They are all good suggestions, but it will make the table component complicated if we implement all of them. I think it's a good idea to add a new template property to allow people design their own filters. Is it satisfactory?

**Comment by warcha** [comment]
Thanks for the quick reply @anranruye 

The template property would be perfect. I'm currently trying to implement a custom solution but its very difficult, in particular because the columns FilterModel isn't exposed. Allowing A template property would be a really good solution.

Do you have any idea on when this would be available?

thanks

**Comment by anranruye** [comment]
Currently we don't have any plan.

**Comment by warcha** [comment]
What is the process to get the filter template feature added to the plan? Is there anything I can do to help around getting this added/fast tracked?

Thanks @anranruye

**Comment by warcha** [comment]
Hi @anranruye, just wanted to check if there was any progress on getting this feature added to the plan? Please let me know if it would help for me to raise a PR to get this done earlier? Thanks

**Comment by ElderJames** [comment]
Yes, it would be more helpful if you create a PR.

**Comment by ElderJames** [comment]
This would be supported in next feature branch. #3283 #3279 #2243

**Comment by manuelelucchi** [comment]
Hi @ElderJames, do you have any idea when the next feature branch will be released in the stable packages? I really need #3283

**Comment by ElderJames** [comment]
Now we can custom the filter input components. Thank you!
