### ISSUE TITLE
Select component ValueChanged calls second time even when the value the same

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#2199]
Hi there,

I want to manually set the value via ValueChanged event.

```
<Select Value=@data ValueChanged=@OnDataChanged ... />

Task OnDataChanged (int value)
{
  data = value; // This is being called twice
  ... //call server side to retrieve some data
}
```
I expect the OnDataChanged only call once. I also notice OnSelectedItemChanged however it is an Action and I dont like to use async void since I need to call StateHasChanged to update the UI every time.

Is it expected behavior?

**Comment by LeaFrock** [comment]
I'm a little bit interested in this issue. 

As I see from [SelectOption.OnClick()](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/select/SelectOption.razor.cs#L253) and [SelectBase.SetValueAsync()](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/select/SelectBase.cs#L671), it seems to be OK here. Are there more clues? What's the mode here? Or does your `OnDataChanged` method take any actions which will invoke `ValueChanged` again?

**Comment by ldsenow** [comment]
@LeaFrock My OnDataChanged handler sets the data prop to the value passed from the control and the data is being used in my remote call to get some entries back to display in a table. The only place I can think of is the data prop sets to the value.

Since I chose to manually set the data prop, i assumed this should not trigger the eventcallback again. Somehow it did.

**Comment by ElderJames** [comment]
Hello @ldsenow , this issue have been fixed.
