### ISSUE TITLE
UseWebAssemblyDebugging is not working

### ISSUE THREAD

**Issue by drawmoon** [ant-design-blazor/ant-design-blazor#2201]
### Describe the bug

I created the project using the template

```
dotnet new antdesign -o MyAntDesignApp -ho hosted
```

After setting Server as the startup project, f5 Launch project, unable to hit the front end breakpoint

![image](https://user-images.githubusercontent.com/41671372/147349876-b1cee32c-4f61-4527-a5cb-fd614c7c91f4.png)

And Microsoft's Blazor WebAssembly App Template can hit the breakpoint

![image](https://user-images.githubusercontent.com/41671372/147349979-2fc8847c-0414-4076-9403-1c18ac4f3606.png)

### Further technical details

**AntDesign Version**

v0.10.31

**.NET Version**

```
.NET SDK (反映任何 global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by vadimffe** [comment]
I think you better use "partial class" approach anyway to separate C#. Debugging should work there. 
Tutorial: https://www.c-sharpcorner.com/article/partial-classes-and-layouts/

**Comment by drawmoon** [comment]
@vadimffe This is a good idea, but it doesn't seem to work for me, the debugger doesn't hit the "partial class" breakpoint, or even the `Program.cs` 😶‍🌫️

**Comment by anranruye** [comment]
Well, it's better to debug with a blazor server project(which shares the same components with the wasm project). There are many limitations for debugging with a wasm project.

说实话我一点也不意外调试wasm项目的时候出问题。调试wasm项目本身是有限制的，很多断点本来就命中不了，比如你说的Program.cs中的断点，具体有什么限制看官方文档。即使你接受了这些限制，也还是经常不好用，限制以外该命中的断点他还是命中不了，至于不好用的原因，搞不清楚，我也是亲身经历过这些的。即使正常工作了，wasm调试界面的监视面板提供的信息也不如blazor server项目详细。

需要注意的是，hosted项目里的客户端项目本身依然是一个wasm项目，我这里说的server项目是指blazor server宿主模型项目，而不是hosted托管项目中的server项目。

**Comment by drawmoon** [comment]
了解了，看来我需要尝试别的方案来解决我的问题
