### ISSUE TITLE
Set max height for modal and add scroll bar into dialog instead of scrolling the whole page

### ISSUE THREAD

**Issue by vadimffe** [ant-design-blazor/ant-design-blazor#2206]
Is there are some way to set scroll bar inside dialog itself and define max-height for it to not exceed certain value. Currently if there are `<Panel>` items inside dialog form, while expanding them dialog exceeds the size of window and there is a scroll-viewer appearing in window. How to make scroll-viewer appearing in dialog window instead? Currently dialog buttons are going too far below that they may be lost by user.

I have tried to define `Style="width:50%; max-height: 50%;"` for Modal but that didn't worked.

![image](https://user-images.githubusercontent.com/72302395/147502868-9cd64242-19c5-4829-82b9-efd957312165.png)

**Comment by lukblazewicz** [comment]
Please try setting the following parameter:
`BodyStyle="height:65vh;overflow-y:auto;"`

**Comment by vadimffe** [comment]
@lukblazewicz might you know some solution for having also bottom buttons stick to the bottom? Now if content exceeds Modal height buttons are going far at the bottom, at the end of scroll content. Is there any solution to fix action buttons to window bottom and apply scrollbar only for content?

![image](https://user-images.githubusercontent.com/72302395/149037765-843dfa51-cfc1-4182-81e7-0de609886212.png)

**Comment by lukblazewicz** [comment]
If I remember correctly, BodyStyle applies to modal's content only (excluding the footer/buttons) - so the solution proposed above should still do the trick.

**Comment by vadimffe** [comment]
@lukblazewicz can't get it working. Basically with this setup layout looks like I am expecting:

```
<Modal Title="Create new record"
       Style="width:80%"
       BodyStyle="height:65vh;overflow-y:auto;"
       Visible="@this.isDialogVisible"
       Draggable="@(true)"
       OnCancel="(e)=>{this.isDialogVisible = false;}">
  <Form Model="this.RecordModel"
        Layout="@FormLayout.Vertical"
        OnFinish="(e) => this.OnCreateNewDiaryRecord()">
    <div>
      <NewRecord Record=this.RecordModel />
    </div>
  </Form>
</Modal>
```

However in this case I am not able to control OK = Submit button. I would like to perform some validation with Submit button, and have ability to custom name it. So I am trying to get this somehow doing the job, but can't figure out how to make footer stick to the bottom.

```
<Modal Title="Create new record"
       Style="width:80%"
       BodyStyle="height:65vh;overflow-y:auto;"
       Visible="@this.isDialogVisible"
       Draggable="@(true)"
       Footer="null"
       OnCancel="(e)=>{this.isDialogVisible = false;}">
  <Form Model="this.RecordModel"
        Layout="@FormLayout.Vertical"
        OnFinish="(e) => this.OnCreateNewDiaryRecord()">
    <div>
      <NewRecord Record=this.RecordModel />
    </div>
    <br />
    <div class="ant-modal-footer">
      <FormItem WrapperColOffset="8" WrapperColSpan="16">
        <Button Type="@ButtonType.Primary" HtmlType="submit">
          Submit
        </Button>
        <Button OnClick="(e)=>{this.isDialogVisible = false;}">Cancel</Button>
      </FormItem>
    </div>
  </Form>
</Modal>
```
