### ISSUE TITLE
When the page does not have any scroll bar, prevent the body from increasing the style of width: calc(100%-17 px) 

### ISSUE THREAD

**Issue by NightSpark75** [ant-design-blazor/ant-design-blazor#2207]
hi there,
I found that when I display Modal, it will force the style of width: calc (100%-17 px) to be added to the body tag.
At the moment, my page does not have a scroll bar, calc(100%-17 px) will cause my page elements to be moved 17 px to the left.
This problem does not exist in version 0.10.2, it only appeared after upgrading to 0.10.3.1.
I checked the code, it should be the updated version after [issue #2102](https://github.com/ant-design-blazor/ant-design-blazor/issues/2102).

**Comment by vadimffe** [comment]
I have noticed this "bug" while opening modal window (if we are talking about same issue):
![06220AB8-D61B-4D5A-B28B-A9F7504ED7D2](https://user-images.githubusercontent.com/72302395/147557294-4ec2bcdd-5a1b-44d4-9e76-7d5616510223.GIF)

**Comment by NightSpark75** [comment]
> I have noticed this "bug" while opening modal window (if we are talking about same issue):
> 
> ![06220AB8-D61B-4D5A-B28B-A9F7504ED7D2](https://user-images.githubusercontent.com/72302395/147557294-4ec2bcdd-5a1b-44d4-9e76-7d5616510223.GIF)
> 
> You can notice that there is a tiny bar appearing on the right while opening Modal window and page content is moving to left as well.

Yes, the problem is as you showed

**Comment by zxyao145** [comment]
this issue will be fixed before 2022.1.2 (sunday)
