### ISSUE TITLE
pointer-events: none not working on a table row

### ISSUE THREAD

**Issue by jcasement** [ant-design-blazor/ant-design-blazor#2215]
Working with `<Table>` and trying to add the pe-none on the row class has no effect.
Following on from your example from Custom Row Styling:
`<Table TItem="Data" DataSource="@data" OnRow="OnRow" RowClassName="@(x => x.Data.RowClass)">`

If I use the pe-none, this should not permit row selection or being able to click the checkbox but rows with this are still selectable.

**Comment by anranruye** [comment]
Thanks for contacting us @jcasement 

This is not something we can control. The only thing we can do is to ensure the class attribute is added to the tr element correctly. Then you custom class and style will work as the browser default behavior.
