### ISSUE TITLE
Display HTML code inside AntList

### ISSUE THREAD

**Issue by vadimffe** [ant-design-blazor/ant-design-blazor#2216]
Is there any possibility to display HTML text inside AntList or any other List like component? It would be nice to have that possibility in case there are some records with rich text formatting.

Example with HTML tag below:

![image](https://user-images.githubusercontent.com/72302395/147704566-84438479-2bd4-4155-9136-4acace15bb8f.png)

**Comment by vadimffe** [comment]
The answer to this is to use:

```
@((MarkupString)Markup)

@code {

    [Parameter]
    public string Markup { get; set; }

}
```

**Comment by LeaFrock** [comment]
WOW，thanks a lot! It saves me 😄 .
