### ISSUE TITLE
Get filtered datas from table

### ISSUE THREAD

**Issue by DrTekno** [ant-design-blazor/ant-design-blazor#2221]
### Problem
While filter a table i need the filtered datas to use it somewhere else.

### Solution
Can we retrieve this datas from the onChange event of the column's table?

### Additional context
I'm using a WASM environment.

**Comment by ElderJames** [comment]
Thanks for contacting us @DrTekno . You can use `ExecuteTableQuery` with QueryModel in OnChange event.

```razor
@using AntDesign.TableModels

<Table TItem="Data" DataSource="_data" OnChange="HandleTableChange" ...>

@code {

    IEnumerable<Data> _data;
    async Task HandleTableChange(QueryModel<Data> queryModel)
    {
          var filteredData = _data.ExecuteTableQuery(queryModel).CurrentPagedRecords(queryModel);
          ...
    }
}
```

**Comment by DrTekno** [comment]
Thank you, i've added .AsQueryable() before .ExecuteTableQuery() and is just perfect.

Best regards
