### ISSUE TITLE
[Modal] Draggable = true throws JSException

### ISSUE THREAD

**Issue by lukblazewicz** [ant-design-blazor/ant-design-blazor#2223]
Settings Draggable property to true on Modal results in the following exception:

`Microsoft.JSInterop.JSException
e.addEventListener is not a function TypeError: e.addEventListener is not a function at c.value (https://localhost:7179/_content/AntDesign/js/ant-design-blazor.js:1:44388) at Object.i.enableDraggable (https://localhost:7179/_content/AntDesign/js/ant-design-blazor.js:1:47190) at https://localhost:7179/_framework/blazor.server.js:1:3501 at new Promise (<anonymous>) at Tt.beginInvokeJSFromDotNet (https://localhost:7179/_framework/blazor.server.js:1:3475) at https://localhost:7179/_framework/blazor.server.js:1:71773 at Array.forEach (<anonymous>) at Tt._invokeClientMethod (https://localhost:7179/_framework/blazor.server.js:1:71759) at Tt._processIncomingData (https://localhost:7179/_framework/blazor.server.js:1:69801) at bt.Tt.connection.onreceive (https://localhost:7179/_framework/blazor.server.js:1:64201)`

**Comment by ElderJames** [comment]
Thanks for contacting us @lukblazewicz , please clear your browser cache.
