### ISSUE TITLE
Can InputNumber support RangeAttribute

### ISSUE THREAD

**Issue by SmRiley** [ant-design-blazor/ant-design-blazor#2225]
### Is your feature request related to a problem? Please describe.

Is it possible to consider RangeAttribute as the Min and Max values of the InputNumber component

[RangeAttribute](https://docs.microsoft.com/zh-cn/dotnet/api/system.componentmodel.dataannotations.rangeattribute.-ctor?view=net-6.0)

**Comment by ElderJames** [comment]
Validation of `RangeAttribute` is currently supported
