### ISSUE TITLE
Table Pagination, Filterable and Selection can not work together

### ISSUE THREAD

**Issue by JustGentle** [ant-design-blazor/ant-design-blazor#2229]
### Describe the bug

When i use Pagination, Filterable and Selection Component together refer to each demo, they can not work correct.
Pagination invalidates the filter, turning the page will clear the selection, and filter will cancel the hiden row too.

### Steps to reproduce (please include code)
``` razor
<h3>Change PageIndex will clear selection</h3>
<h3>Filterable dose'n work</h3>
@($"Selection: {string.Join(",", selection?.Select(x => x.Id) ?? Enumerable.Empty<int>())}")
<Table DataSource="@Items.Skip((PageIndex - 1) * 3).Take(3)"
       Total="@Items.Count" PageSize="3"
       @bind-PageIndex="PageIndex"
       @bind-SelectedRows="@selection">
    <Selection></Selection>
    <Column @bind-Field="@context.Id" Sortable></Column>
    <Column @bind-Field="@context.Name" Sortable Filterable></Column>
</Table>

<h3>Filterable will change selection</h3>
@($"Selection2: {string.Join(",", selection2?.Select(x => x.Id) ?? Enumerable.Empty<int>())}")
<Table DataSource="@Items"
       Total="@Items.Count" PageSize="@Items.Count" HidePagination="true"
       @bind-SelectedRows="@selection2">
    <Selection></Selection>
    <Column @bind-Field="@context.Id" Sortable></Column>
    <Column @bind-Field="@context.Name" Sortable Filterable></Column>
</Table>
@code{
    public int PageIndex { get; set; }
    class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    IEnumerable<Item> selection { get; set; }
    IEnumerable<Item> selection2 { get; set; }
    List<Item> Items { get; set; } = Enumerable.Range(0, 50).Select(x => new Item { Id = x, Name = x.ToString("00") }).ToList();
}
```

### Further technical details
- AntDesign Nuget Package version: 0.10.1
- Include the output of `dotnet --info`: sdk  5.0.103
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: vs2019

**Comment by anranruye** [comment]
1. `DataSource="@Items.Skip((PageIndex - 1) * 3).Take(3)"` => `DataSource="@Items"`
2. this is by-design

**Comment by JustGentle** [comment]
> 1. `DataSource="@Items.Skip((PageIndex - 1) * 3).Take(3)"` => `DataSource="@Items"`
> 2. this is by-design

It work! The documentation example misled me ([Components > Table > Custom Pagination](https://ant-design-blazor.gitee.io/en-US/components/table#components-table-demo-custom-pagination))
Now Pagination and filterable can work together.
but selection problem still there.

**Comment by JustGentle** [comment]
I can understand why  turning the page will clear the selection, but filter doesn't make sense

**Comment by michaelcsikos** [comment]
Turning the page should _not_ clear the selection. This is horrible. And clicking the select all checkbox in the column header only selects all for the current page, so how do you actually select all?

**Comment by ElderJames** [comment]
@michaelcsikos Maybe we can add a eventcallback `OnSelectAll`.

**Comment by aathirakhusi** [comment]
I can see that there is a fix for retaining the selected rows while navigating to different pages within the pagination, however the select all is not working as expected if we check some check box within the table.
Please check this video where I captured the defect.
[https://clipchamp.com/watch/rGKncKD8Ign](url)

**Comment by tabuenam** [comment]
I have seen at the documentation and the first example in the table section is qorking but after trying it in my project every time I change pageIndex is unselecting my rows automatically. Is this problem soöved

**Comment by ElderJames** [comment]
Hello @tabuenam , now we can hold the selection outside the table, and restore the selectedrows before every time to reload the data. We can consider adding a parameter and an internal cache to do this.
