### ISSUE TITLE
The body width is changed unexpectedly when a drawer with left or right placement is visible

### ISSUE THREAD

**Issue by chunliu** [ant-design-blazor/ant-design-blazor#2231]
### Describe the bug

With version 0.10.3 or 0.10.3.1, the body width is changed unexpectedly when a drawer with left or right placement is visible. See below. 

![antbug](https://user-images.githubusercontent.com/2128551/148216353-4a7d56a5-28e9-4e20-b954-282a578b91dc.gif)

The problem was caused by this style `... width: calc(100% - 17px); ...` that was applied on `<body>`  when the drawer became visible. It could be introduced in #2163.

### Steps to reproduce (please include code)

A simple repro can be found here: https://github.com/chunliu/antbug/blob/master/anttest/Shared/MainLayout.razor

### Further technical details
- AntDesign Nuget Package version: 
      0.10.3.1

- Include the output of `dotnet --info`
    .NET SDK (reflecting any global.json):
     Version:   6.0.101
     Commit:    ef49f6213a
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.22000
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\6.0.101\
    
    Host (useful for support):
      Version: 6.0.1
      Commit:  3a25a7f1cc
    
    .NET SDKs installed:
      6.0.100 [C:\Program Files\dotnet\sdk]
      6.0.101 [C:\Program Files\dotnet\sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
      VS 2022 17.1.0 Preview 1.1

**Comment by zxyao145** [comment]
Hi, I think this is a duplicate issue to #2207, and the fixed PR #2212 has been merged, it will be fiexd in next version.
