### ISSUE TITLE
Collapse looks to have an API to Activate a Panel

### ISSUE THREAD

**Issue by jcasement** [ant-design-blazor/ant-design-blazor#2232]
@Hona Is there any example of how to do this?  I'm trying to use the Activate on a Panel based upon a selection from a Table?
In other words, if there is a viable selection from the Table I would like to open the panel and conversely close the Panel with Deactivate API when all selections are removed.  I can't find any examples which use the Panel Activate API.  I must be missing a @using or something else.  Thanks, Jim

**Comment by jcasement** [comment]
I discovered and tried the following:

`Collapse collapse;`

Collapse defined with:

`@ref=collapse`

Tried:
` collapse.Activate(new[] {"1"});`

Nothing appears to happen to the Panel with the key=1

**Comment by ElderJames** [comment]
Hello @jcasement , it works well currectly. Please try.
