### ISSUE TITLE
Table pageindexchanged is before pagesizechanged

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#2236]
My scenario is page size: 10, page index: 50 and total: 500. When i change the page size to 100, the Table control will do a smart calculation to figure out the page index and set it to 5 in this case. It then triggers the PageIndexChanged however, it is before the PageSizeChanged event. 

Since i use remote datasource, I register OnTableChange event and send the request to server based on the query. In this case, the table control will trigger 2 TableChanged events. It means 2 server calls will be sent. I understand why the table control changes the page index. 

Actually my server side already handles this out of bound scenario and so i try my way to work around it by also registering on PageIndexChanged event and set the pageindex back to original pageindex and let the server side to handle this.
However, the PageIndexChanged event doesnt have the intended page size, i cant work out if it is out of bound.

It would be good that we always trigger the pagesizechanged event before the pageindexchanged event if user changes the page size. Also hoping someone has any way to work around this scenario.

**Comment by anranruye** [comment]
there are two approaches
1. use a custom pagination component and handle the page change events yourself
2. do not bind pageSizeChanged and pageIndexChanged events, use OnChange event only. When you see that pageSize and pageIndex are both changed, then you know that pageSize is not the expected page size and you can just ignore it.

**Comment by ldsenow** [comment]
@anranruye I will look at the option one first. However, i dont think option 2 would work. The reason is how do i know it is the page size i expected, I rely on the onchange event to tell me. I wouldnt keep tacking the page size myself if i dont have to. I still believe the pagesizechanged event should be triggered before the pageindexchanged event. This is more incline to the user's intend.

**Comment by anranruye** [comment]
> the pagesizechanged event should be triggered before the pageindexchanged event

I agree but I don't think this really matters. And I will have a look at the option 2.

**Comment by anranruye** [comment]
> the pagesizechanged event should be triggered before the pageindexchanged event

I agree but I don't think this really matters. And I will have a look at the option 2.

**Comment by ldsenow** [comment]
It does matter with this case. If the pageindexchanged trigger after then I can work out whether the current setup is out of bound or not. I then can choose to handle/ignore it myself. Less work to implement a work around.
