### ISSUE TITLE
Submenu does not expand automatically

### ISSUE THREAD

**Issue by BeiYinZhiNian** [ant-design-blazor/ant-design-blazor#2237]
### Describe the bug

Submenu does not automatically expand when navigation is used

![image](https://user-images.githubusercontent.com/25119211/148635236-560716a1-1f42-4712-a330-5c26ccb9bc39.png)

### Steps to reproduce (please include code)

```
NavigationManager.NavigateTo(url)
```

### Exceptions (if any)

Version="0.9.1.1"

It was feasible before this version

### Further technical details
- AntDesign Nuget Package version：0.10.3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Magehernan** [comment]
Hi, i having this problem, there is a work around this?

**Comment by ElderJames** [comment]
@BeiYinZhiNian Please checkout the lastest version if it have been fixed.
