### ISSUE TITLE
【ReuseTabs】it can't show title in tabpane

### ISSUE THREAD

**Issue by YingXiaoMing** [ant-design-blazor/ant-design-blazor#2248]
for example:
![lQLPDhsMYTARnIbMjc0CuLAn2bv2S-LOrgHk9LvWQOAA_696_141](https://user-images.githubusercontent.com/16699795/149089590-83fc66ee-b3f8-4c65-9862-d700947d347b.png)

**Comment by berkerdong** [comment]
![image](https://user-images.githubusercontent.com/36178221/221407850-4c2d8e65-5d50-4d89-8b0a-41f5a3e436cb.png)
This problem has been fixed in the latest version, and the function is normal

**Comment by berkerdong** [comment]
@ElderJames This issue can be closed

**Comment by ElderJames** [comment]
Thank you @berkerdong
