### ISSUE TITLE
GetCaseInsensitiveСomparation is using Cyrillic Capital Letter Es

### ISSUE THREAD

**Issue by paolodm** [ant-design-blazor/ant-design-blazor#2250]
Got the following warning in VSCode:

![image](https://user-images.githubusercontent.com/68116003/149210261-5803120a-c7e4-46b6-86a8-e2f165675553.png)

Apparently, the `C` in Comparation is actually the Cyrillic Capital Letter Es (U+0421). This is getting reported as possible security issue. For example, in Snyk:

![image](https://user-images.githubusercontent.com/68116003/149210856-39d0706a-8ae4-46ab-a00e-53dbaaa8f52c.png)

What is the reason for choosing this odd choice of character?

**Comment by anranruye** [comment]
No reason, just a mistake.
