### ISSUE TITLE
Custom buttons with HtmlType="submit" logic in ModalFooter

### ISSUE THREAD

**Issue by vadimffe** [ant-design-blazor/ant-design-blazor#2254]
I have been trying for couple of days to get this working without success. Also checked Google and can't find any solution. I am trying to make a modal window that would have scroller inside content and there would be Header and Footer. I would like to perform validation as well before closing Modal window.

Here is working solution, but buttons are not in Footer and are scrolled with content, that makes them hard to find as they are not attached to the bottom of dialog all the time.

```
<Modal Title="Create new record"
       Style="width:80%"
       BodyStyle="height:65vh;overflow-y:auto;"
       Visible="@this.isDialogVisible"
       Draggable="@(true)"
       Footer="null"
       OnCancel="(e)=>{this.isDialogVisible = false;}">
  <Form Model="this.RecordModel"
        Layout="@FormLayout.Vertical"
        OnFinish="(e) => this.OnCreateNewDiaryRecord()">
    <div>
      <NewRecord Record=this.RecordModel />
    </div>
    <br />
      <FormItem WrapperColOffset="8" WrapperColSpan="16">
        <Button Type="@ButtonType.Primary" HtmlType="submit">
          Submit
        </Button>
        <Button OnClick="(e)=>{this.isDialogVisible = false;}">Cancel</Button>
      </FormItem>
  </Form>
</Modal>
```

I have tried this:

```
@{
  RenderFragment footer = @<Template>
    <Button Type="@ButtonType.Primary" @key="@( "submit" )" HtmlType="submit" Loading="@_loading">
      Submit
    </Button>
    <Button OnClick="(e)=>{this.isDialogVisible = false;}">Cancel</Button>
  </Template>;
}

<Modal Title="Create new record"
       Style="width:80%"
       BodyStyle="height:65vh;overflow-y:auto;"
       Visible="@this.isDialogVisible"
       Draggable="@(true)"
       Footer="@footer"
       OnCancel="(e)=>{this.isDialogVisible = false;}">
  <Form Model="this.RecordModel"
        Layout="@FormLayout.Vertical"
        OnFinish="(e) => this.OnCreateNewRecord()">
    <div>
      <NewRecord Record=this.RecordModel />
    </div>
    <br />
  </Form>
</Modal>
```

But Submit button does not function in this case correctly = does nothing. However in layout perspective everything looks as expected. So then I have tried this:

```
<Modal Title="Create new record"
       Style="width:80%"
       BodyStyle="height:65vh;overflow-y:auto;"
       Visible="@this.isDialogVisible"
       Draggable="@(true)"
       OnCancel="(e)=>{this.isDialogVisible = false;}">
  <Form Model="this.RecordModel"
        Layout="@FormLayout.Vertical"
        OnFinish="(e) => this.OnCreateNewDiaryRecord()">
    <div>
      <NewRecord Record=this.RecordModel />
    </div>
    <br />
  </Form>
  <ModalFooter>
    <div>
      <Button Type="@ButtonType.Primary" HtmlType="submit">
        Submit
      </Button>
      <Button OnClick="(e)=>{this.isDialogVisible = false;}">Cancel</Button>
    </div>
  </ModalFooter>
</Modal>
```

But I am getting exception about ChildContent = no Footer visible. Is there any way to get Custom buttons with Submit logic into Footer?

This is what I am trying to achieve:

1. Default dialog = modal window with Header, Content and Footer sections
2. Dialog has fixed Height property (either px or %) and scroller appears automatically in content section if after unhiding items in Panel's Height of dialog exceeds set value.
4. OK button changed to `OkText="@("Submit")"` and has `HtmlType="submit"` logic

I ended up with this code, but it does not "validate" on Submit button pressed (does not highlight error inputs in Dialog like default `HtmlType="submit"` does):

```
<Modal Title="Create new record"
       Style="width:80%"
       BodyStyle="height:65vh;overflow-y:auto;"
       Visible="@this.isDialogVisible"
       Draggable="@(true)"
       OkText="@("Submit")"
       ConfirmLoading="@this.confirmationButtonIsLoading"
       OnOk="this.OnSubmitRecord"
       OnCancel="(e)=>{this.isDialogVisible = false;}">
  <Form Model="this.RecordModel"
        ValidateMode="@FormValidateMode.Rules"
        ValidateOnChange="@validateOnChange"
        Layout="@FormLayout.Vertical"
        OnFinish="(e) => this.OnSubmitRecord()"
        OnFinishFailed="(e)=>{this.isDialogVisible = true;}">
    <div>
      <NewRecord Record=this.RecordModel />
    </div>
    <br />
  </Form>
</Modal>
```

![image](https://user-images.githubusercontent.com/72302395/149037830-361546ac-e71a-4690-ba35-c8f0f1197047.png)

**Comment by zxyao145** [comment]
Hi, I will pay attention to this problem and provide solutions.

**Comment by zxyao145** [comment]
Hi, now it's support set max content body height by parameter MaxBodyHeight. 


For automatically setting the height of the Modal content body, the current component logic cannot be satisfied, and many things need to be refactored. But I will continue to pay attention to this problem. 


And for using Modal OK button to submit the Form in the Modal, I provided a new demo. Since the form element of the Form component is an element inside Modal, the OK button cannot be placed inside the form element. To solve this problem, there are two solutions: one is to pass the Form component reference as a parameter to Modal, and the other is to submit it manually through the OK button of Modal component. The scheme 1 will make Modal and Form more coupled. At present, I provide a demo of scheme 2.

If you have better suggestions, please let me know, thank you.

**Comment by vadimffe** [comment]
@zxyao145 thank you for updates! For setting MaxBodyHeight this worked also fine (in terms of functionality)        `BodyStyle="height:65vh;overflow-y:auto;"`. However with dedicated parameter MaxBodyHeight it would be more "natural" way of defining layout settings.

You are mentioning that there is a new demo for validation on Modal window Submit button? Could you please specify where it can be found? I have made an example project where I tried to implement everything mentioned. However validation logic missing while clicking Submit button. Can be found here: https://github.com/vadimffe/BlazorAppAntDemo

**Comment by zxyao145** [comment]
@vadimffe Hi, you can see the demo in [https://preview-2264-antblazor.surge.sh/en-US/components/modal#components-modal-demo-form-in-modal](https://preview-2264-antblazor.surge.sh/en-US/components/modal#components-modal-demo-form-in-modal). This is a preview application which in PR. And he sorce code is in [[.](https://github.com/ant-design-blazor/ant-design-blazor/pull/2264/files#diff-52e89eb194e3338ec8bbf7d3813b5528f66ef75c4fdfc07dcad573ffb2448cd4)](https://github.com/ant-design-blazor/ant-design-blazor/pull/2264/files#diff-52e89eb194e3338ec8bbf7d3813b5528f66ef75c4fdfc07dcad573ffb2448cd4)

Or later, I will submit a PR to a https://github.com/vadimffe/BlazorAppAntDemo.

**Comment by vadimffe** [comment]
@zxyao145 for me it seems to work now as expected. I can probably close this issue
