### ISSUE TITLE
TabPane change Disabled don't change css ant-tabs-tab-disabled

### ISSUE THREAD

**Issue by gloisance** [ant-design-blazor/ant-design-blazor#2258]
Hello,

When i change Disable parameter of TabPane, the style of tab don't change but i chan click on tab.
I see SetClass of TabPane is in OnInitialised function.
In juil 2020, SetClass was in OnParametersSet.

Thanks

**Comment by ElderJames** [comment]
Thanks for contacting us @codeox-he , please update to 0.13.2. We have fixed this via https://github.com/ant-design-blazor/ant-design-blazor/pull/2967 .
