### ISSUE TITLE
The display is not updated when the Value of Select is 0.

### ISSUE THREAD

**Issue by coolmint123** [ant-design-blazor/ant-design-blazor#2263]
Hello. I enjoy using Ant Design.
The display is not updated when the Value of Select is 0.
Item in Items are not displayed when changing from ItemID: 1 to ItemID: 0.
Click Select to select both ItemID: 0 and ItemID: 1.
Is there a workaround?

<AntDesign.Select "
     DataSource = "@ Items"
     Value = "@ ItemID"
     ValueExpression = "@ (() => ItemID)"
     ValueChanged = "@ ( (int item) => ItemID = item)"
     TItem = "Item"
     TItemValue = "int"
     LabelName = "@ nameof (Item.Name)"
     ValueName = "@ nameof (Item.ItemID)">
</ AntDesign.Select>

### Technical details
AntDesignNuget 0.10.3.1
Visual Studio 2022 17.0.4
net6.0

**Comment by LeaFrock** [comment]
`bind-Value` may be a workground.

```html

<AntDesign.Select
    DataSource = "@Items"
    @bind-Value = "@_selectedItemID"
    TItem = "Item"
    TItemValue = "int"
    LabelName = "@nameof (Item.Name)"
    ValueName = "@nameof (Item.ItemID)">
</ AntDesign.Select>

@code{
    private int _selectedItemID;
}
```

**Comment by ElderJames** [comment]
I have tested the code below and it works well.

```
<Select DataSource="@Items"
                  Value="@ItemID"
                  ValueChanged="@((int item) => ItemID = item)"
                  TItem="Item"
                  TItemValue="int"
                  LabelName="@nameof(Item.Name)"
                  ValueName="@nameof(Item.ItemID)">
</Select>

@code {
    private int ItemID;

    public class Item
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
    }

    Item[] Items = new Item[]{
        new(){ItemID=0,Name="0"},
        new(){ItemID=0,Name="1"},
    };
}
```
