### ISSUE TITLE
Image preview behaviour if screen width is less than the width of the image

### ISSUE THREAD

**Issue by izvonar** [ant-design-blazor/ant-design-blazor#2269]
### Describe the bug

Image preview behaviour is not correct if screen/page width is less than the width of the image or when resizing the page.

### Steps to reproduce

https://user-images.githubusercontent.com/7409443/151589473-899fa83a-63a5-4f7a-b0a9-f8d310c8a688.mp4

Issue can be reproduced on the docs page -> https://antblazor.com/en-US/components/image

**Comment by zxyao145** [comment]
This is a interesting bug, I'll fix it at the weekend.
