### ISSUE TITLE
Unable to pan and scroll to zoom in Image Preview

### ISSUE THREAD

**Issue by superjerry88** [ant-design-blazor/ant-design-blazor#2280]
### Describe the bug

Image preview is missing panning and scroll to zoom function.

### Steps to reproduce 

AntBlazor:
https://antblazor.com/en-US/components/image
![Pan2](https://user-images.githubusercontent.com/4265188/153045153-a6ce2495-7223-4eff-84d5-e2efb1c2f2b0.gif)

[Expected Behaviour]
AntDesign:
https://ant.design/components/image/
![Pan1](https://user-images.githubusercontent.com/4265188/153045606-8f7fbad7-3179-418c-b508-21bb9cc18107.gif)

Browser used:  Chrome

**Comment by ElderJames** [comment]
Thanks for contacting us @superjerry88 . And yes, we haven't have this feature yet.
If you are interested, feel free to help implement this feature.

**Comment by ElderJames** [comment]
We have support this feature.
