### ISSUE TITLE
The SetSelection method doesn't work in OnAfterRender method or how select particular row after table rendered?

### ISSUE THREAD

**Issue by DemoS76** [ant-design-blazor/ant-design-blazor#2282]
### Describe the bug

The SetSelection method doesn't work in OnAfterRender method or how select particular row after component rendered?

### Steps to reproduce (please include code)
Index page:
```
@page "/"

<h1>Hello, world!</h1>

<Button Type="primary" OnClick=onBtnClick>Show table</Button>

@if (this.visible)
{
    <TableCmp />
}

@code{
    private bool visible = false;

    private void onBtnClick()
    {
        this.visible = !this.visible;
    }
}

```

Table component (TableCmp ):
```
<Table @ref=table DataSource=tableData ScrollY="240px" PageSize="50" Size=@TableSize.Small @bind-SelectedRows=selectedRows>
    <Selection Key=@context.Id Type="radio" />
    <Column Title="Id" @bind-Field=@context.Id Width="150" />
    <Column Title="Data" @bind-Field=@context.Data Width="150" />
</Table>

<Text>Selected: @selectedRows?.FirstOrDefault()?.ToString()</Text>
<br />
<Button OnClick=OnBtnClick>Select 2nd row</Button>

@code {
    class TableData
    {
        public string Id { get; set; }
        public string Data { get; set; }

        public override string ToString()
        {
            return $"Id: {Id}, Data: {Data} ";
        }
    }

    private ITable table;
    private IEnumerable<TableData> selectedRows;

    private IEnumerable<TableData> tableData = new TableData[] {
        new TableData{ Id = "1", Data = "Data1" },
        new TableData{ Id = "2", Data = "Data2" },
        new TableData{ Id = "3", Data = "Data3" },
    };

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);

        if (firstRender)
        {
            table.SetSelection(new[] { "2" });
        }
    }

    private void OnBtnClick()
    {
        table.SetSelection(new[] { "2" });
    }
}
```
Just rendered view:
![image](https://user-images.githubusercontent.com/39067214/153280074-9c0ddda5-a6b6-4a84-8310-ab2a2630c62e.png)

When "Select 2nd row" button was clicked:
![image](https://user-images.githubusercontent.com/39067214/153280199-b331d1a3-fc0a-4854-b5a2-e7365e080ef6.png)

### Further technical details
- AntDesign Nuget Package version: 0.10.3.1
- Include the output of `dotnet --info`:.net6
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a
 Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS2022

**Comment by true-perfect-code** [comment]
What about this point? 
I tried to set the preselected entries, but it does not work:

`selectedRows = list_selected_data.().ToList(); `

The entries go in, but the Razor page is called several times and the variable is automatically emptied. But this does not happen with other lists, even if Razor page is built several times! Unfortunately you can change the datatype from IEnumerable to List (error message from Ant because of type converting).

**Comment by ElderJames** [comment]
Hello @DemoS76 @true-perfect-code , now you can use SelectedRows to setup the pre-select rows or change the selected rows manually.

Please see these demos on the site:
- https://antblazor.com/en-US/components/table#components-table-demo-row-selection
- https://antblazor.com/en-US/components/table#components-table-demo-on-row-and-on-cell

**Comment by true-perfect-code** [comment]
Thanks @ElderJames
