### ISSUE TITLE
Modal does not append required rtl class when chossing Rtl direction

### ISSUE THREAD

**Issue by hassan-gasemi** [ant-design-blazor/ant-design-blazor#2288]
### Bug
Modal in Rtl Direction does not append ant-modal-wrap-rtl css class to the upper level html tag (element with role="dialog"). This causes ui problems like incorrect title align(title overlaps with close button). I've debugged the source and found out that Rtl variable inside DialogOptions.cs always is false. (File DialogOptions.cs  -- Method GetWrapClassNameExtended()).

![image](https://user-images.githubusercontent.com/4272852/153767326-de190540-2044-4774-9c1b-a105c38142e4.png)

### Steps to reproduce
1- Change Direction to Rtl
2- Add a Modal component to page
3- Open Modal

MainLayout.razor
```
[CascadingParameter] public ConfigProvider ConfigProvider { get; set; } = default!;

protected override void OnInitialized()
{
      ConfigProvider.ChangeDirection("rtl");
}
```

MyList.razor
```
<Modal Title="@("Title")"
       Visible="@visibleModal"
       OnCancel="() => {visibleModal = false;}"
       Closable="true"
       MaskClosable="false"
       DestroyOnClose="true"
       Footer="null">
<CreateUpdateWarehouse Canceled="EditCanceled" ModelUpdated="ModelUpdated" ModelCreated="ModelCreated" WarehouseOriginal="SelectedWarehouse" ModelDeleted="ModelDeleted" />
</Modal>
```

### Further technical details
- AntDesign 0.10.3.1
- dotnet 6.0.101

**Comment by zxyao145** [comment]
I'm sorry that Modal didn't get data from ConfigProvider. This problem will be fixed by the end of this week at the latest.
