### ISSUE TITLE
"Message" is displayed repeatedly

### ISSUE THREAD

**Issue by bestpika** [ant-design-blazor/ant-design-blazor#2311]
### Describe the bug

When using "MessageService", if you switch to another page after displaying a message and then switch back, the same message will be displayed repeatedly if there is a message displayed by the same method.

### Steps to reproduce (please include code)

1. The message is displayed on the first page.
1. The message is displayed once.
1. Switch to any page.
1. Switch back to the first page.
1. Display the next message.
1. The message will be displayed twice (see below).

![image](https://user-images.githubusercontent.com/5698157/156092612-10b21bad-a83e-457b-ad83-93fadcf7315f.png)

```C#
...

@inject MessageService Message

...

private void showInfo(string message)
{
    Message.Info(message);
}
```

### Further technical details

- AntDesign | 0.10.3.1
- .NET | 6 (Blazor PWA)

**Comment by bestpika** [comment]
I just checked the whole process once again and found that there seems to be a strange abnormality in one of the components causing duplicate displays.

**Comment by zxyao145** [comment]
If you have any questions, you can open this issue again. Welcome to communicate again.
