### ISSUE TITLE
MessageService NullReferenceException

### ISSUE THREAD

**Issue by trycatchfinnally** [ant-design-blazor/ant-design-blazor#232]
MessageService 的OnOpening事件保护级别为internal,只有在message组件上才有+=操作,即必须在使用该服务前先调用到message组件的初始化事件而不是像angular版本一样开箱即用

`@page "/Customer/Register"
@using Tkh.Shop.Core.Domain.Customer
@inject Tkh.Shop.Data.Abstract.Customer.ICustomerDbService CustomerDbService
@inject ILogger<Customer> Logger
@inject HttpClientService Http;
@inject MessageService _message
@*<Message></Message>*@
@if (test != null)
{
    <div>@System.Text.Json.JsonSerializer.Serialize(test) </div>
}
<Button Type="primary" OnClick="async ()=>await SubmitAsync()">something</Button>
@code {
    private object test;
    private bool submitting = false;
    private async ValueTask SubmitAsync()
    {
        test = new { Name = "236587978909780" };

        await    this._message.Info(System.Text.Json.JsonSerializer.Serialize(test));
    }

}
`
上述代码会抛出NullReferenceException,只有取消掉<Message></Message>的注释才能正常操作

**Comment by ElderJames** [comment]
Thanks for contating us @trycatchfinnally .
This problem is a design flaw in Blazor and we need a global container.
Please add a component `<AntContainer />` to `App.razor`.

Refer to https://github.com/ant-design-blazor/ant-design-blazor/issues/158#issuecomment-634737972qq

**Comment by trycatchfinnally** [comment]
thanks ,i think it
