### ISSUE TITLE
Table column filterable debounce issue

### ISSUE THREAD

**Issue by MaggiGorengAyam** [ant-design-blazor/ant-design-blazor#2325]
### Describe the bug

Similar to issue #1965 , the textbox in the table column where "Filterable" is enabled, some characters may not be registered, or a lag can be seen.

### Further technical details
- AntDesign Nuget Package version = 0.10.4
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version = Visual Studio 2022 Enterprise 17.0.5

**Comment by ElderJames** [comment]
Hi @MaggiGorengAyam , sorry for reply late. please check if we have fixed this issue in #2275

**Comment by MaggiGorengAyam** [comment]
Yes, I have checked and it does seem to have fixed our issue. Thank you.
