### ISSUE TITLE
刷新浏览器会报异常

### ISSUE THREAD

**Issue by 904617726** [ant-design-blazor/ant-design-blazor#233]
使用https://ant-design-blazor.gitee.io/zh-CN/components/layout 中的案例代码可以显示出来,但只要点击浏览器刷新就会报错:
编译后正常显示:
![image](https://user-images.githubusercontent.com/31062419/84927187-0e393280-b0ff-11ea-9694-eeecc035f764.png)
点击浏览器刷新按钮后:
![image](https://user-images.githubusercontent.com/31062419/84926917-a84cab00-b0fe-11ea-9e71-05274b316ebe.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @904617726 .
Please update the last nightly nuget package, and try again.
