### ISSUE TITLE
Header is not aligned with column contents for right-side fixed column in the Table component

### ISSUE THREAD

**Issue by adrianth** [ant-design-blazor/ant-design-blazor#2334]
### Screenshot
<img width="987" alt="image" src="https://user-images.githubusercontent.com/5209882/158229054-22eab6c2-6d8b-4b5d-9010-05aa681222fb.png">

### Environment
This behavior happens on a **Mac M1 Pro** with **macOS Monterey 12.2.1** in **Chrome 99.0.4844.51** and **Safari 15.3**. **Firefox 97.0.1** works fine.

**Brave 99.0.4844.51** on **Windows 11 Pro for ARM** also works fine. I haven't tested in other browsers.

Please let me know if you need more information.

**Comment by ElderJames** [comment]
Thanks for contacting us @adrianth . Please set the `ScrollBarWidth` parameter of Table.

**Comment by ElderJames** [comment]
@adrianth Please check again.

**Comment by ElderJames** [comment]
This issue have been fixed in #2451
