### ISSUE TITLE
How to sort the data from the data source as DataRow

### ISSUE THREAD

**Issue by bigrice8** [ant-design-blazor/ant-design-blazor#2335]
<Table TItem="DataRow" DataSource="@data?.Select()" Loading="data==null" PageSize="15" ScrollX="@scrollx" OnChange="HandleTableChange">

    @if (columns?.Any() == true)
    {
        @foreach (var col in columns)
        {
            <Column Title="@col.coltext" @bind-Field="@col.colname"  Sortable> @context[col.colname]</Column>
              @*<Column Title="@col.coltext"  Field="@col.colname"  Sortable > @context[col.colname] </Column>*@
        }
        @if (columnbuttons?.Any() == true)
        {
            <ActionColumn Title="操作">
                @foreach (var but in columnbuttons)
                {
                    @if (but.fname == "删除")
                    {
                        <Popconfirm Title="确定要删除吗？" OkText="删除" CancelText="取消" OnConfirm="()=>Event(context,but.fname)">
                            <Button Size="small">删除</Button>
                        </Popconfirm>
                    }
                    else
                    {
                        <Button Size="small" OnClick="()=>Event(context,but.fname)">@but.fname</Button>
                    }

                }
            </ActionColumn>
        }
    }
</Table>

**Comment by bigrice8** [comment]
> 请参阅https://antblazor.com/en-US/components/table#components-table-demo-datatable

I tested, I couldn't sort, and the table added the "onchange" event and didn't get the sorted column

**Comment by bigrice8** [comment]
> Please see https://antblazor.com/en-US/components/table#components-table-demo-datatable

<Table TItem="DataRow" DataSource="@data?.Select()" Loading="data==null" PageSize="15" ScrollX="@scrollx" OnChange="HandleTableChange">

    @if (columns?.Any() == true)
    {
        @foreach (var col in columns)
        {
           @* <Column Title="@col.coltext" @bind-Field="@col.colname"  Sortable> @context[col.colname]</Column>*@
              <Column Title="@col.coltext"  Field="@col.colname"  Sortable > @context[col.colname] </Column>
        }
        @if (columnbuttons?.Any() == true)
        {
            <ActionColumn Title="操作">
                @foreach (var but in columnbuttons)
                {
                    @if (but.fname == "删除")
                    {
                        <Popconfirm Title="确定要删除吗？" OkText="删除" CancelText="取消" OnConfirm="()=>Event(context,but.fname)">
                            <Button Size="small">删除</Button>
                        </Popconfirm>
                    }
                    else
                    {
                        <Button Size="small" OnClick="()=>Event(context,but.fname)">@but.fname</Button>
                    }


                }
            </ActionColumn>
        }
    }
</Table>

**Comment by bigrice8** [comment]
> Please see https://antblazor.com/en-US/components/table#components-table-demo-datatable

<Table TItem="DataRow" DataSource="@data?.Select()" Loading="data==null" PageSize="15" ScrollX="@scrollx" OnChange="HandleTableChange">

    @if (columns?.Any() == true)
    {
        @foreach (var col in columns)
        {
           @* <Column Title="@col.coltext" @bind-Field="@col.colname"  Sortable> @context[col.colname]</Column>*@
              <Column Title="@col.coltext"  Field="@col.colname"  Sortable > @context[col.colname] </Column>
        }

How to implement data binding within @bind-Field="". I tested and I reported errors

**Comment by bigrice8** [comment]
> Please see https://antblazor.com/en-US/components/table#components-table-demo-datatable

<Table TItem="DataRow" DataSource="@data?.Select()" Loading="data==null" PageSize="15" ScrollX="@scrollx" OnChange="HandleTableChange">

**Comment by bigrice8** [comment]
> Please see https://antblazor.com/en-US/components/table#components-table-demo-datatable

Table TItem="DataRow" DataSource="@data?.Select()" Loading="data==null" PageSize="15" ScrollX="@scrollx" OnChange="HandleTableChange">

**Comment by bigrice8** [comment]
> Please see https://antblazor.com/en-US/components/table#components-table-demo-datatable



> Please see https://antblazor.com/en-US/components/table#components-table-demo-datatable

Just learned blazor, trouble under the guidance, really can't find how to solve

**Comment by ElderJames** [comment]
Hello @bigrice8 , please use `DataIndex` to bind Column Name.
