### ISSUE TITLE
Slider does not always fire OnAfterChange

### ISSUE THREAD

**Issue by juergenr** [ant-design-blazor/ant-design-blazor#2336]
### Describe the bug
OnAfterChange does not fire, when the circle of the slider is draged and then droped.
OnAfterChange fires only, when the slider is clicked and the mouse button is immediately released.

### Steps to reproduce (please include code)
```
<Slider Value="@value"  Min="0" Max="100" Step="1"
        TValue="double" OnAfterChange="OnAfterChange"   />
```
```
@code {
    double value = 10;
    void OnAfterChange(double d) {
        Console.WriteLine($"OnAfterChange {d}");
    }
}
```
OnAfterChange is not called, when the mouse is released after the slider was dragged.

### Further technical details
- AntDesign Nuget Package version: 0.10.4
- dotnet: 6.0.201
- Windows 10

**Comment by hypdeb** [comment]
I have the same issue. At least I can use it by clicking now, thanks :)
