### ISSUE TITLE
How to sort the data from the data source as DataRow

### ISSUE THREAD

**Issue by bigrice8** [ant-design-blazor/ant-design-blazor#2339]
Table TItem="DataRow" DataSource="@data?.Select()" Loading="data==null" PageSize="15" ScrollX="@scrollx" OnChange="HandleTableChange">

    @if (columns?.Any() == true)
    {
        @foreach (var col in columns)
        {
            <Column Title="@col.coltext" @bind-Field="@col.colname"  Sortable> @context[col.colname]</Column>
        
        }

**Using @bind-Field="@col.colname" will report an error, I don't know if I wrote the problem or what is going on, can you help see**

**Comment by bigrice8** [comment]
The "OnChange "event also does not get the sorted QueryModel

**Comment by ElderJames** [comment]
Please try to use DataIndex instead of bind-Field

**Comment by ElderJames** [comment]
duplicated with #2335
