### ISSUE TITLE
Include unnecessary less files after published

### ISSUE THREAD

**Issue by yang-xiaodong** [ant-design-blazor/ant-design-blazor#2342]
1.  run publish cli
```
dotnet publish -c Release 
```
2. the less file is output to the release folder.

![image](https://user-images.githubusercontent.com/8205994/158723209-b42bc5b7-cbfa-4746-a204-5ce9d604950a.png)

**Comment by ElderJames** [comment]
Please see this PR https://github.com/ant-design-blazor/ant-design-blazor/pull/457

**Comment by yang-xiaodong** [comment]
I noticed this PR before submitting the issue, it was addressing less variable references during development, but it was meaningless after published

**Comment by ElderJames** [comment]
related https://github.com/ant-design-blazor/ant-design-blazor/issues/2694 , somebody need these files.
