### ISSUE TITLE
Sider is not smooth when collapsed

### ISSUE THREAD

**Issue by bestpika** [ant-design-blazor/ant-design-blazor#2347]
### Describe the bug

As the question, when I make sider can be collapsible, I found that no matter what the environment is, it feels quite not smooth, can it be improved?

### Steps to reproduce (please include code)

I use the custom trigger example code in sider.
<https://antblazor.com/en-US/components/layout/#components-layout-demo-custom-trigger>

### Further technical details

- AntDesign | 0.10.3.1

**Comment by ElderJames** [comment]
fixed
