### ISSUE TITLE
Use the DataTable as the data source, and the official example reports an error

### ISSUE THREAD

**Issue by bigrice8** [ant-design-blazor/ant-design-blazor#2350]
![image](https://user-images.githubusercontent.com/99955123/159213331-1a7c636d-f21e-4d07-a25a-ed08c2ddb551.png)
![image](https://user-images.githubusercontent.com/99955123/159213359-817e144d-416d-446d-89b7-386d1a846b5f.png)

Antdesign has been updated to the latest version

**Comment by ElderJames** [comment]
Thanks for contacting us @bigrice8 . Please provide your demo here.

**Comment by bigrice8** [comment]
> 感谢您与我们联系@bigrice8。请在此处提供您的演示。
![image](https://user-images.githubusercontent.com/99955123/160046864-0be45f67-3198-4cdd-97a5-b388eb079561.png)
The source code of the component document will be reported as an error, so you can try to see it directly

**Comment by ElderJames** [comment]
It works well on the document.

**Comment by bigrice8** [comment]
> 它在文档上运行良好。

How to show you

**Comment by bigrice8** [comment]
> 它在文档上运行良好。

Just started learning, don't know how to show you how to show you on GitHub

**Comment by ElderJames** [comment]
What AntDesign version are you working on?

**Comment by bigrice8** [comment]
> 



> 您正在使用 AntDesign 的哪个版本？

0.2.2

**Comment by bigrice8** [comment]
> What AntDesign version are you working on?

![image](https://user-images.githubusercontent.com/99955123/160060791-972bfdd7-505d-4a40-97fc-eb9606d46ef7.png)

**Comment by ElderJames** [comment]
Please install the latest AntDesign 0.10.5

**Comment by bigrice8** [comment]
> 请安装最新的 AntDesign 0.10.5

Yes, thank you very much for your reply
