### ISSUE TITLE
TextArea Component got error when set MinRows or MaxRows

### ISSUE THREAD

**Issue by kefengwei** [ant-design-blazor/ant-design-blazor#2358]
### When set MinRows or MaxRows at the TextArea, it got a JSInterop Call Exception

![image](https://user-images.githubusercontent.com/4326865/160033321-17fdb8eb-e07b-4eee-80e1-e68cad7fb948.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @kefengwei , please try to clear the browser cache.

**Comment by kefengwei** [comment]
@ElderJames  I still get this exception, after clear the browser cache.

**Comment by ElderJames** [comment]
@kefengwei  Could you please provide a reproducible demo?
