### ISSUE TITLE
Tree组件节点Title不能有“|”符号

### ISSUE THREAD

**Issue by caibo532** [ant-design-blazor/ant-design-blazor#2362]
### Describe the bug
Tree组件节点Title不能有“|”符号如：010|Test
否则搜索时节点会显示“010|Test010|Test”

**Comment by ElderJames** [comment]
![image](https://user-images.githubusercontent.com/7550366/160221216-51322aa9-57c2-44f9-8ec5-58218fb99b92.png)
It seems work well. Could you please provider your code here?

**Comment by caibo532** [comment]
加上一个搜索框，搜索时候出现问题
