### ISSUE TITLE
Demo Get error msg “this browser does not support WebAssembly.” in Edge  V99.0.1150.55 

### ISSUE THREAD

**Issue by eren186** [ant-design-blazor/ant-design-blazor#2365]
Other Wasm site works fine, but the ant demo is not.
![image](https://user-images.githubusercontent.com/48199905/160315401-415ae2fa-19c4-4962-b580-cfeda1b26235.png)

**Comment by ElderJames** [comment]
Hi @eren186 , this is not AntDesign issue, please report this to [aspnetcore](/dotnet/aspnetcore) repo.
