### ISSUE TITLE
blazor.server项目，使用form 组件出错

### ISSUE THREAD

**Issue by yuanxiongwei** [ant-design-blazor/ant-design-blazor#237]
> `InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(long asyncHandle, string identifier, string argsJson)
Microsoft.JSInterop.JSRuntime.InvokeAsync<TValue>(string identifier, CancellationToken cancellationToken, object[] args)
Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation<T>(string identifier, object[] args)
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
AntDesign.AntComponentBase.JsInvokeAsync<T>(string code, object[] args)
AntDesign.Row+<>c__DisplayClass33_0+<<SetGutterStyle>b__0>d.MoveNext()
AntDesign.EnumerableExtensions.ForEachAsync<T>(IEnumerable<T> items, Func<T, Task> func)
AntDesign.Row.SetGutterStyle()
AntDesign.Row.OnInitializedAsync()`

blazor项目是blazor.server ，直接按照文档的示例复制的组件使用代码。无法正常运行。

希望能尽快完善推出，想知道什么时候可以正式在项目中使用。

**Comment by ElderJames** [comment]
Thank you for your contacting @yuanxiongwei .
This is a duplicate issue with #181 .
