### ISSUE TITLE
TabBarStyle is not being used in Tabs control

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#2372]
Hi,

I was trying to assign the style in the tabs. However, it didnt get applied and looked the source code it doesnt seem to put there. Also I wanted to extend the tab bar css class e.g. TabBarClass, if would be good if we can have it as well.

I am happy to do a PR if no one is working on it and also makes sense with my request.

**Comment by ElderJames** [comment]
Hey @ldsenow , could you please to create a PR?

**Comment by ldsenow** [comment]
Sure, i will try my best to work on it during weekend.

**Comment by ldsenow** [comment]
> Hey @ldsenow , could you please to create a PR?

PR has been created, please review it when you have time and let me know if there is anything is missing.
