### ISSUE TITLE
The table style changes after the filter is selected

### ISSUE THREAD

**Issue by bigrice8** [ant-design-blazor/ant-design-blazor#2379]
![image](https://user-images.githubusercontent.com/99955123/161369227-5307b146-d499-4b8c-bbbf-147656577b7d.png)

Table TItem="DataRow" DataSource="@data?.Select()" @bind-PageSize="_pageSize" Loading="_loading" ScrollX="@scrollx" OnChange="OnChange">
    <ChildContent>
        @if (syscolumns?.Any() == true)
        {
            @foreach (var col in syscolumns)
            {
                if (col.isid == 1)
                {
                    <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Hidden TData="string" Sortable>@context[col.columnname]</Column>
                }
                else
                {

                    Type dataType = data.Columns[col.columnname].DataType;
                    switch (dataType.Name)
                    {

                        case "String":
                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="string" Sortable>@context[col.columnname]</Column>
                            break;
                        case "Decimal":
                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="decimal?" Sortable>@context[col.columnname]</Column>
                            break;
                     
                        case "Int32":
                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="int?" Sortable>
                                @{
                                    if (col.displaystyle == "复选框")
                                    {
                                        if ($"{context[col.columnname]}" == "1")
                                        {
                                            <Tag Color="green">是</Tag>
                                        }
                                        else
                                        {
                                            <Tag Color="pink">否</Tag>
                                        }
                                    }
                                }
                            </Column>
                            break;
                        case "DateTime":
                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="DateTime?" Sortable>@context[col.columnname]</Column>
                            break;

                        case "Float":

                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="float?" Sortable>@context[col.columnname]</Column>
                            break;
                        case "Double":

                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="double?" Sortable>@context[col.columnname]</Column>
                            break;
                        case "Byte":

                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="byte?" Sortable>@context[col.columnname]</Column>
                            break;
                        default:
                            <Column Title="@col.columncaption" DataIndex=@($"['{col.columnname}']") Filterable TData="object" Sortable>@context[col.columnname]</Column>
                            break;
                    }
                }

            }

**Comment by bigrice8** [comment]
The filtered table has data and does not show the data out

**Comment by bigrice8** [comment]
![image](https://user-images.githubusercontent.com/99955123/161371235-6a4ba332-3f94-40cb-a274-50e540a9c2ad.png)
![image](https://user-images.githubusercontent.com/99955123/161371346-a6c50bc4-7453-4613-bb3d-e3d8f46d2de0.png)

The value of the row is NULL, and the TData is "string" and the error will be reported, how to deal with this situation

**Comment by ElderJames** [comment]
Don't use `DataIndex`, instead the ChildContent of `<Column>`.
```
<Column TData="object" Title="@column.ColumnName">@context[column.ColumnName]</Column>
```

**Comment by ElderJames** [comment]
@bigrice8 Please set the `TData` as `object`.
