### ISSUE TITLE
How to make a chart with "ant-design-blazor"?

### ISSUE THREAD

**Issue by huazhenhz** [ant-design-blazor/ant-design-blazor#239]
Does "ant-design-blazor" have any existing components to make a Char?
Are there any plans to support it?
Thanks!

**Comment by ElderJames** [comment]
Thank you for contacting us.
We don't have a chart component yet.
But it will be in our later milestones.
We plan to do this using [ant-design-charts](https://charts.ant.design), which comes with Ant Design.

**Comment by huazhenhz** [comment]
Got it, and we'll be looking forward to the new process.
Many thanks for your reply!
