### ISSUE TITLE
Upload module OnRemove involves asynchronous async error

### ISSUE THREAD

**Issue by berkerdong** [ant-design-blazor/ant-design-blazor#2393]
![image](https://user-images.githubusercontent.com/36178221/162604748-f547a9cd-636e-48a0-8901-2e2485ab418b.png)
The delete function on the file upload side, if OnRemove involves asynchronous async, this problem will occur 100%

Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '238'. Perhaps the DotNetObjectReference instance was already disposed. Arg_ParamName_Name, dotNetObjectId

**Comment by tonyyip1969** [comment]
Hi @ElderJames, do you want me to do something on the memory leak issue? or you already resolved it.

**Comment by ElderJames** [comment]
I haven't solved it yet. If you have any ideas, please help to solve this problem. I would really appreciate it.

**Comment by tonyyip1969** [comment]
Hi @ElderJames, I will look into this.

**Comment by ElderJames** [comment]
@tonyyip1969 Thank you!

**Comment by ElderJames** [comment]
fixed.
