### ISSUE TITLE
[Modal]回调问题

### ISSUE THREAD

**Issue by MarvelTiter** [ant-design-blazor/ant-design-blazor#2394]
### Describe the bug

我按照文档上的Demo。（通过 ModalService 创建一个 Modal 对话框，模板代码：ConfirmTemplateDemo.razor）

并没有触发OnOk回调，OnCancel，OnClose都没有。

```
        public async Task OpenDialog(E.Users user)
        {
            var options = new ModalOptions();
            options.Title = "用户信息";
            //var modalRef = await ModalSrv.CreateModalAsync<UserInfo, E.Users, E.Users>(options, user);

            //modalRef.OnOk = async (result) =>
            //{
            //    Debug.WriteLine("on ok");
            //};

            //modalRef.OnCancel = async (result) =>
            //{
            //    Debug.WriteLine("on cancel");
            //};
            var modalRef = await ModalSrv.CreateModalAsync<ConfirmTemplateDemo, string, string>(options, "Hello");
            modalRef.OnOk = result =>
            {
                Debug.WriteLine("on ok");
                return Task.CompletedTask;
            };
        }
```

**Comment by zxyao145** [comment]
@MarvelTiter 请问使用的版本号是多少？

**Comment by zxyao145** [comment]
@MarvelTiter 这是我的代码，可以观察到输出的。项目的配置是按照 https://antblazor.com/zh-CN/docs/introduce 介绍来的，使用的也是0.10.5。通过断点能够进入到 `OnOk`中吗？

``` c#
@page "/"
@inject ModalService ModalSrv

<Button OnClick="@OpenDialog">Open</Button>


@code{
     public async Task OpenDialog()
        {
            var options = new ModalOptions();
            options.Title = "用户信息";

            var modalRef = await ModalSrv.CreateModalAsync<ConfirmTemplateDemo, string, string>(options, "Hello");
            modalRef.OnOk = result =>
            {
                // Debug.WriteLine("on ok");
                Console.WriteLine("on ok"); 
                return Task.CompletedTask;
            };
        }
}
```
![image](https://user-images.githubusercontent.com/24973084/162885971-268d8596-fadb-4932-b6a9-9a3b5abe384d.png)

**Comment by MarvelTiter** [comment]
弹窗功能是正常的，没有异常抛出。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月12日 14:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ant-design-blazor/ant-design-blazor] [Modal]回调问题 (Issue #2394)


@MarvelTiter<https://github.com/MarvelTiter> 弹窗是否正常呢？有什么错误出现吗？

―

**Comment by zxyao145** [comment]
@MarvelTiter 方便远程吗？晚上我可以远程看下

**Comment by zxyao145** [comment]
@MarvelTiter 向日葵？看您用什么方便。如果在群里的话可以加下我微信

**Comment by MarvelTiter** [comment]
没问题，我先加下群
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月12日 15:10
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ant-design-blazor/ant-design-blazor] [Modal]回调问题 (Issue #2394)


@MarvelTiter<https://github.com/MarvelTiter> 向日葵？看您用什么方便。如果在群里的话可以加下我微信

―
