### ISSUE TITLE
nested-table bug

### ISSUE THREAD

**Issue by im-moo** [ant-design-blazor/ant-design-blazor#2417]
Nested sub table
The part beyond PageSize is not displayed or paged.
It is hoped to modify the embedded sub table to embed paging, so that the sub table can display the information of each row of data.
For example, PageSize = 10, the embedded sub table has 40 rows of data. At present, only 10 rows are displayed, and others cannot be displayed.

嵌套子表格
超过 Pagesize 部分不显示也没有分页。
希望修改为内嵌子表内嵌分页，使子表能展示每行数据的信息。
例如Pagesize=10，内嵌子表有40行数据，目前只显示10行，其他的无法显示。

**Comment by ElderJames** [comment]
Thanks for contacting us @im-moo . If you're interested, feel free to implement this feature.

**Comment by ElderJames** [comment]
Hello @im-moo , please try the lastest version, we have fixed this issue.
