### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by yuanxiongwei** [ant-design-blazor/ant-design-blazor#242]
do you have a plan rich text ? froala，element-tiptap， they are all good to learn from

**Comment by ElderJames** [comment]
Thank you for contacting us @yuanxiongwei .

Yes, we have plans to integrate the UEditor. 
While Froala is good, there are licensing issues.

**Comment by Epictek** [comment]
Something similar to [draft.js](https://github.com/facebook/draft-js) would be nice but maybe as a separate library?

Worth noting Blazored already has a [TextEditor](https://github.com/Blazored/TextEditor) based on Quill. Shame there isn't one in pure Blazor code though.

**Comment by yuanxiongwei** [comment]
@ElderJames  like element-tiptap use [prosemirror]( https://github.com/prosemirror) core。I want to support custom plug-ins

**Comment by ElderJames** [comment]
Hi there, I found [vditor](https://github.com/Vanessa219/vditor) is very nice and I want to bring it to blazor.

**Comment by yuanxiongwei** [comment]
vditor is ok

**Comment by ElderJames** [comment]
We have create a project on https://github.com/ant-design-blazor/vditor-blazor. Welcome to contribute.
