### ISSUE TITLE
IconTemplate of MenuItem used in SubMenu

### ISSUE THREAD

**Issue by MarvelTiter** [ant-design-blazor/ant-design-blazor#2426]
### Describe the bug

在`SubMenu`中的`MenuItem`的`IconTemplate`内容不显示
property `IconTemplate` of `MenuItem` does not display while `MenuItem` was wrapped  in `SubMenu`
```
<SubMenu>
	<TitleTemplate>
			<span class="subtitle_template">
				<Icon>
					<Component>
						<SvgIcon IconName="setting"></SvgIcon>
					</Component>
				</Icon>
				<span>@("测试")</span>
			</span>
		</TitleTemplate>
		<ChildContent>
			<MenuItem Title="sub one">
				<IconTemplate>
					<SvgIcon IconName="setting"></SvgIcon>
				</IconTemplate>
			</MenuItem>
		</ChildContent>
</SubMenu>
```
ant-design-blazor version: 0.10.5
visual studio version: Microsoft Visual Studio Community 2022 (64 位) 17.1.6

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thanks for contacting us @MarvelTiter 
We will fix it in this weekend.
