### ISSUE TITLE
Tree Component node check bug

### ISSUE THREAD

**Issue by MarvelTiter** [ant-design-blazor/ant-design-blazor#2444]
### Describe the bug

当一个节点只有一个子节点的时候，选中之后，就不能取消。产生的原因大概是，父节点选中和取消的时候，他的子节点也会选中和取消，但是，当取消的时候，最后的一个子节点依然是选中状态。

while a `TreeNode` that has only one child, you can't uncheck after check the node。The reason is probably that when the parent node is checked and unchecked, its children will also be checked and unchecked, but when unchecked, the last child is still checked.

### Further technical details
- AntDesign Nuget Package version   0.10.5
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
@MarvelTiter 你好，感谢支持。请提供可重现的 代码，我在文档上测试没有这个问题。

**Comment by MarvelTiter** [comment]
解决办法：升级到0.10.6
