### ISSUE TITLE
Loops in cascader search

### ISSUE THREAD

**Issue by fheck** [ant-design-blazor/ant-design-blazor#2445]
### Describe the bug

The search in the cascader produces loops. 
![image](https://user-images.githubusercontent.com/17826649/168282031-fcec7a76-77a2-429a-8091-242193ed9b62.png)

### Steps to reproduce (please include code)

Three-level cascader data. On the first level, only one node, on the second level two nodes, on the third level, two nodes each. 
Problem gets worse, the more "branches" the tree of cascader nodes has.

![image](https://user-images.githubusercontent.com/17826649/168294351-0222674b-6cdc-464c-aefa-3d604193f9c8.png)

### Exceptions (if any)

None

### Further technical details
Source of the error might be using the full _searchlist [here](https://github.com/ant-design-blazor/ant-design-blazor/blob/5bb90f568eb0d55859282a392541a9b024833607/components/cascader/Cascader.razor.cs#L353), instead of only the newly added nodes.

**Comment by ElderJames** [comment]
Hello @fheck , thanks for contacting us. I did not reproduce it. Could you please provide a demo?

**Comment by fheck** [comment]
I don't know what exactly makes the difference, or what I missed in the description but I was able to build a small repro [here](https://github.com/fheck/AntBlazor-Issue2445-repro) based on the code that shows the symptoms in my real app.
