### ISSUE TITLE
how to create custom select class ? inherit from ant select 

### ISSUE THREAD

**Issue by UtGithubs** [ant-design-blazor/ant-design-blazor#2447]
I tried to create following component.But it cannot get  value.

 public class CustomSelect<TItemValue, TItem> : Ant.Design.Select<TItemValue, TItem>, CustomGetInterface
    {
        public CustomSelect()
        {
           Size= "small";
        }
  public object GetValue()
        {
            return Value;
        }
}

**Comment by ElderJames** [comment]
Thanks for contacting us @UtGithubs . Please set the parameters in constructor.  You can refer the [EnumSelect](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/select/EnumSelect.cs).

**Comment by UtGithubs** [comment]
Thank you. I used it and modified.it works.

**Comment by ElderJames** [comment]
That's great! Thank you for using AntBlazor !
