### ISSUE TITLE
TimePicker ok button does not close timepicker dropdown

### ISSUE THREAD

**Issue by quirynen** [ant-design-blazor/ant-design-blazor#2455]
## Describe the bug

When using the timepicker, when I click on the Ok button, the dropdown does not close.
Even when I'm on the example on the website : https://antblazor.com/en-US/components/timepicker#components-timepicker-demo-size.

Is this the intended behaviour?

**Comment by Alexbits** [comment]
From what I see, the Ok is not handled at all in [https://github.com/ant-design-blazor/ant-design-blazor/blob/c3cefdd1259e68b9d5b899b49024ed9b7168f3ed/components/date-picker/internal/DatePickerPanelChooser.razor](url)

TimePicker needs some love 😊

**Comment by ElderJames** [comment]
@Alexbits Can we close this issue?

**Comment by Alexbits** [comment]
> @Alexbits Can we close this issue?

yes, this was fixed a while ago

**Comment by ElderJames** [comment]
Ok, thanks.
