### ISSUE TITLE
Upload 404

### ISSUE THREAD

**Issue by UtGithubs** [ant-design-blazor/ant-design-blazor#2458]
it makes 404 error ( https://localhost:7093/null 404 )  after upload button clicked.  Why did it make ?

-----------------------------------------------
Upload  OnSingleCompleted="OnSingleCompleted"   Name="files" 
    Button Icon="upload">
        <span>Click to Upload</span>
    Button
Upload
  -----------------------------------------------

void OnSingleCompleted(UploadInfo fileinfo)
        {
            if (fileinfo.File.State == UploadState.Success)
            {
                var result = fileinfo.File.GetResponse<FileModel>();
                fileinfo.File.Url = result.url;
                Console.WriteLine("IF");
            }
            else
            {
                Console.WriteLine("Else"); // it makes status =fail 404 
            }
        }

**Comment by ElderJames** [comment]
Thanks for contacting us @UtGithubs , you need to set `Action` as your url.

**Comment by ElderJames** [comment]
Please wait for version 0.11.0, we have fixed this issue in #2443 .
