### ISSUE TITLE
BuildRenderTree  in Form 

### ISSUE THREAD

**Issue by UtGithubs** [ant-design-blazor/ant-design-blazor#2464]
Hello @ElderJames ,

1.How to render BuildRenderTree in Form ?
 or 
2.How to work submit button outside of Form control  ?

    <Form Model="_TemplateTestModel" LabelColSpan="8" WrapperColSpan="16" >
        <FormItem>
            @{
                base.BuildRenderTree(__builder);      //its not rendering.
            }
        </FormItem>

    </Form> 
    
    --------------IN base  class
            protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.OpenComponent<Button>(0);
            builder.AddAttribute(1, "Type", @ButtonType.Primary);
            builder.AddAttribute(2, "Size", "Small");
            builder.AddAttribute(3, "Icon", IconType.Outline.Save);
            builder.AddAttribute(3, "HtmlType", "button");
            builder.AddAttribute(4, "ChildContent", AddContent());
            builder.CloseComponent();      
        }
    
2.  
<Button Type="primary" HtmlType="submit"  Size="large" Block  form="myForm" @onclick="TestClick">Login</Button>
Form Model="_TemplateTestModel" id="myForm"   --start
 Form --end

**Comment by ElderJames** [comment]
Hi @UtGithubs

Q1: maybe you can try RenderFargment.

```cs
RenderFargment formBody = builder => builder.OpenComponent<Button>(0);
```

In razor:
```
 <FormItem>
       @formBody
 </FormItem>
```

Q2:

You can use the Form reference and it's `Submit()` method:

```
<Form @ref="_form">
....
</Form>

<Button OnClick="Submit" >Submit</Button>

@code{ 
    Form _form;

    void Submit(){
        _form?.Submit();
    }

}
```

**Comment by anranruye** [comment]
Also, the `BuildRenderTree` method can work as a `RenderFragment` directly since method can be implictly casted to delegate type.

**Comment by anranruye** [comment]
I'm closing this since the question is answered and this issue is not active. Feel free to reopen this issue or open a new one.
