### ISSUE TITLE
RenderTreebuilder in form ?

### ISSUE THREAD

**Issue by UtGithubs** [ant-design-blazor/ant-design-blazor#2471]
How to create  BuildRenderTree of Form ?
 
 TemplateTestModel _TemplateTestModel = new TemplateTestModel()
 
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
  builder.OpenComponent<Form<TemplateTestModel>>(0);
            builder.OpenComponent<"FormItem">(0);
                        builder.OpenComponent<Input<string>>(0);
                        builder.AddAttribute(1, "Value", _TemplateTestModel .Name);
                        builder.CloseComponent();
            builder.CloseComponent();
    builder.CloseComponent();
}

**Comment by ElderJames** [comment]
duplicate with #2464
