### ISSUE TITLE
DebounceMilliseconds for <Select Mode="tags" EnableSearch>

### ISSUE THREAD

**Issue by frindler** [ant-design-blazor/ant-design-blazor#2473]
I have to set DebounceMilliseconds for `<Input>`'s to, say, 1000, to make the text stop jumping around when I type (I don't exactly know why, but this works...). 

However, I also use `<Select Mode="tags" EnableSearch>` for selections and there is no DebounceMilliseconds for the search <Select>.

Could this be added? (or allow customization of the search field)?

Thanks for the great components!

**Comment by ElderJames** [comment]
I will release it this weekend.

**Comment by ElderJames** [comment]
@tompru @frindler It has been released as 0.11.0

**Comment by tompru** [comment]
Thanks! :D
