### ISSUE TITLE
An Affix bug in documentation

### ISSUE THREAD

**Issue by shur520** [ant-design-blazor/ant-design-blazor#2477]
拉动scrollable-container的滚动条后,再滚动 页面Affix跑出来了
![image](https://user-images.githubusercontent.com/76552883/170402807-cb832833-5272-499d-8710-8bb78e6dddd6.png)

**Comment by ElderJames** [comment]
Hi @shur520 , this is because both scrollbars have moved, and the Affix only listens for the container's scroll.

这是因为两个滚动条都移动了，而这个Affix只监听container的滚动，你这时再滚动一下容器内的滚动条，就会回到容器内。
目前 Affix 不能同时计算两个元素的滚动。如果你觉得这样有问题，可以尝试提交一个特性，让它支持。
