### ISSUE TITLE
Charts issue in server template

### ISSUE THREAD

**Issue by vincejairam** [ant-design-blazor/ant-design-blazor#2478]
I installed the latest template

`dotnet new -i AntDesign.Templates`

I then create a project with Visual Studio 2022 Community Ed, using the "Ant Design Pro Blazor App (AntDesign Blazor Team) template. I chose "full", server and css. Once the project was created, I tried to do a build and was given the following error. I've tried several times and still get the same error, 
`1>C:\test\Test.Portal\Pages\_Host.cshtml(25,61,25,65): error CS0103: The name 'antv' does not exist in the current context`

I'm not sure what I'm doing wrong, does anyone know what this issue is? 

Its coming from this script reference in the _Host.cshtml file

`<script type="text/javascript" src="https://unpkg.com/@antv/g2plot@latest/dist/g2plot.min.js"></script>`

**Comment by kylin30** [comment]
@@antv?

**Comment by vincejairam** [comment]
Yes that was it, it looks like the generated code is only using 1 @ symbol, I changed it two @@ and it was able to build.

**Comment by vincejairam** [comment]
Once I was able to run this in the debugger it threw a NullReferenceException in the SalesCard.razor.cs OnTabChanged method. It looks like _salesChart is never initilized 

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=VMXFulfillment.Portal
  StackTrace:
   at Test.Portal.Pages.Dashboard.Analysis.SalesCard.<OnTabChanged>d__14.MoveNext() in C:\test\Test.Portal\Pages\Dashboard\Analysis\Components\SalesCard.razor.cs:line 63
`

`        private async Task OnTabChanged(string activeKey)
        {
            var data = await ChartService.GetSalesDataAsync();
            if (activeKey == "1")
                await _saleChart.ChangeData(data);
            else
                await _visitChart.ChangeData(data);
        }`

dies on `await _saleChart.ChangeData(data);`  _saleChart is never set `private IChartComponent _saleChart;`

**Comment by CGJ96** [comment]
Is this issue being fixed?

**Comment by ElderJames** [comment]
I think this has been fixed.
