### ISSUE TITLE
Documentation is not rendering

### ISSUE THREAD

**Issue by JamieMair** [ant-design-blazor/ant-design-blazor#248]
None of the documentation at https://ant-design-blazor.gitee.io/en-GB/docs/introduce in the main content loads successfully. The sidebar and footer are loaded correctly. This error is produced in the console:
![image](https://user-images.githubusercontent.com/13971435/85709921-a45ff080-b6dd-11ea-9af8-7be62a0ea360.png)

**Comment by ElderJames** [comment]
Thank you for contacting us @JamieMair .
This is due to issue with localization. #159 
You maybe should turn to English before we fix it.

**Comment by ske66** [comment]
Hi Jamie. I found this issue too because I'm from the UK. If you look in the URL it says /en-GB/docs/introduce. If you change this to en-US the documentation will render for you. I had the same issue too but this is a good temporary fix.

**Comment by ElderJames** [comment]
I am closing this issue, please trace #159 for progression. Thank you.
