### ISSUE TITLE
How to use "Pagination" property in AntList

### ISSUE THREAD

**Issue by DaemonWalker** [ant-design-blazor/ant-design-blazor#2492]
### Describe the bug
I try to set Pagination property to sperate data in list but not work

### Steps to reproduce (please include code)

Here's my code
```razor
@page "/list"
@using Models
<AntList TItem="ListModel" Pagination="opt" DataSource="@list">
    <ChildContent Context="item">
        <ListItem>
            @item.Title
        </ListItem>
    </ChildContent>
</AntList>

@code {
    ListModel[] list = new ListModel[] { new ListModel(), new ListModel() };
    PaginationOptions opt = new PaginationOptions() { PageSize = 1 };
}
```

### Further technical details
- AntDesign Nuget Package version : 0.11.0-beta.1
- Include the output of `dotnet --info`
```
.NET SDK (反映任何 global.json):
 Version:   7.0.100-preview.1.22110.4
 Commit:    129d2465c8

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.1.22110.4\

Host (useful for support):
  Version: 7.0.0-preview.1.22076.8
  Commit:  405337939c

.NET SDKs installed:
  3.1.419 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.1.22110.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.1.22109.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.1.22076.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.1.22077.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Code 1.67.1

By the way, I got confused with the [API document of List](https://ant-design-blazor.gitee.io/en-US/components/list#API)
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/16376560/171198958-79c66c77-1c9c-43e2-8976-541742b3498e.png">
1. It seems we cannot pass a bool value to pagination property
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/16376560/171199183-8928d63a-7f64-4fcc-ae92-5af3037793dd.png">
2. Is renderItem  property only available in React Antd? Because the type of it is ReactNode😂

**Comment by yinyunpan** [comment]
The version of "AntDesign.ProLayout" indirectly depends on "antdesign" is too low. The project directly refers to the latest version of "antdesign", and the attribute definition of the old version of "antdesign", such as 

0.10.6

`[Parameter]
public RenderFragment PaginationTemplate { get; set; }`

the latest version
`[Parameter]
        public RenderFragment<(int PageSize, int PageIndex, int Total, string PaginationClass, EventCallback<PaginationEventArgs> HandlePageChange)> PaginationTemplate { get; set; }`

**Comment by orhanmaden** [comment]
Same issue here. Tried the same and got the same result.

**Comment by ElderJames** [comment]
Sorry @DaemonWalker , @orhanmaden , we have support the built-in pagination. The Pagination component needs to be used separately.
