### ISSUE TITLE
Custom json Localization 

### ISSUE THREAD

**Issue by UtGithubs** [ant-design-blazor/ant-design-blazor#2509]
Hello @ElderJames ,

How to set localization from custom json in Program.cs ? Because I need to change some translation of controls.
I tried to create custom services in program.cs.But it doesnt work .  Please suggest any sample  project related it ?

**Comment by ElderJames** [comment]
Please see https://antblazor.com/docs/i18n

**Comment by UtGithubs** [comment]
@ElderJames  thank you. I found it. 
I have question again.How to change MonthNames  ? this code cant set it.   

 public class CustomLocalization:Locale
    {
                    public CustomLocalization()
                    {
                        LocaleName = "fr-FR";
            
                        CurrentCulture.DateTimeFormat.MonthNames = new string[] { "1-Mois", "2-Mois", "3-Mois", "4-Mois", "5-Mois", "6-Mois", "7-Mois", "8-Mois", "9-Mois", "10-Mois", "11-Mois", "12-Mois", "" };
                        CurrentCulture.DateTimeFormat.AbbreviatedMonthNames = new string[] {"1-Mois", "2-Mois", "3-Mois", "4-Mois", "5-Mois", "6-Mois", "7-Mois", "8-Mois", "9-Mois", "10-Mois", "11-Mois", "12-Mois", "" };
                   }
}
