### ISSUE TITLE
Custom Paginationation doesn't work

### ISSUE THREAD

**Issue by stetskivostap** [ant-design-blazor/ant-design-blazor#2510]
Hi Guys!
### Describe the bug
I'm following your example on https://antblazor.com/en-US/components/table#components-table-demo-custom-pagination .

It doesn't want to see the context.
### Steps to reproduce (please include code)
![no context](https://user-images.githubusercontent.com/43217586/172651148-546af248-aa06-4ec7-995b-736d92712677.png)
![image](https://user-images.githubusercontent.com/43217586/172652702-aa15ceff-8426-4ed8-bc7d-2eaad004aee2.png)
![image](https://user-images.githubusercontent.com/43217586/172652874-293d2522-4655-43da-8e6e-78b5dbcf9832.png)

If i put it without "context.", it will work, but it will not update PageIndex property 

Close this issue if:
- context is found or it updates PageIndex property
- if you are not able to reproduce this, that will be sad:(

### Exceptions (if any)
The name 'context' does not exists in this context.

### Further technical details
- AntDesign Nuget Package 0.10.5
- VS 22, .NET 6.0

**Comment by stetskivostap** [comment]
Thank you for the quick response, buut it remains the same( 
Here is the image
![image](https://user-images.githubusercontent.com/43217586/172664308-8d94b45a-dcaa-4d61-aaf3-57519abada31.png)

**Comment by stetskivostap** [comment]
even so, it doesn't work(

**Comment by yinyunpan** [comment]
The version of "AntDesign.ProLayout" indirectly depends on "antdesign" is too low. The project directly refers to the latest version of "antdesign", and the attribute definition of the old version of "antdesign", such as

0.10.6

`[Parameter] public RenderFragment PaginationTemplate { get; set; }`

the latest version
`[Parameter] public RenderFragment<(int PageSize, int PageIndex, int Total, string PaginationClass, EventCallback<PaginationEventArgs> HandlePageChange)> PaginationTemplate { get; set; }`

**Comment by anranruye** [comment]
> The version of "AntDesign.ProLayout" indirectly depends on "antdesign" is too low. The project directly refers to the latest version of "antdesign", and the attribute definition of the old version of "antdesign", such as
> 
> 0.10.6
> 
> `[Parameter] public RenderFragment PaginationTemplate { get; set; }`
> 
> the latest version `[Parameter] public RenderFragment<(int PageSize, int PageIndex, int Total, string PaginationClass, EventCallback<PaginationEventArgs> HandlePageChange)> PaginationTemplate { get; set; }`

Correct.

@stetskivostap you need to update to the latest version to use this feature.
