### ISSUE TITLE
Bug in Tree Table

### ISSUE THREAD

**Issue by semukov** [ant-design-blazor/ant-design-blazor#2520]
Hi,
When, i need in TreeTable dynamic number of columns and first column(for expand-icon) not dynamic, then Expand-Icon appears in different columns, when i update DataSource with other data, and run StateHasChanged().

For example marcup of data with this problem:

```
<Table DataSource="TreeNodes" TreeChildren="item=>item.Children" ExpandIconColumnIndex="0">
    <Column @bind-Field="context.Name" TData="string" />

    @foreach(var dateValue in AllDates) { 
        
        <Column TData="string" Title='@(dateValue.ToString("dd.MM.yyyy"))' >
        	@context.DateValues?.FirstOrDefault(x => x.Date == dateValue)?.GetStrValue()
        </Column>
    }
</Table>
```

I need expand-icon only in a first column(Name) always. How fix it?

**Comment by ElderJames** [comment]
Hello @semukov, please check the latest version, it works well so far.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/752685fd-b73c-4281-bcbd-7aec07814bbd)
