### ISSUE TITLE
Missing _OnViewInit_ property in Drawer component

### ISSUE THREAD

**Issue by anktsrkr** [ant-design-blazor/ant-design-blazor#2533]
### Describe the bug
As per documentation Drawer component has _OnViewInit_ property. However it seems this property does not exists either in latest and nightly build. 

In case we need to call some function before drawer displayed what are the ways to achieve it. 

### Steps to reproduce (please include code)
![image](https://user-images.githubusercontent.com/5505886/174757084-0e1f178c-5180-4f17-a0a5-8039acc27540.png)

and error shows 
![image](https://user-images.githubusercontent.com/5505886/174757350-8254f748-12da-4fea-868a-fae63151734d.png)

### Further technical details
- AntDesign Nuget Package version:  Currently I'm using 0.11.0 but tested with Nightly build as well
- Include the output of `dotnet --info`  : .NET 6 latest build
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version : VS 22 Community on Win 11

**Comment by zxyao145** [comment]
@anktsrkr Hi, I'm sorry, `OnViewInit` is a docs bug, it is not support.

Could I ask why you need this event? Maybe I can try add this feature this weekend.

**Comment by anktsrkr** [comment]
Hi @zxyao145 sorry for the late reply.

We have a form in the Drawer and I would like to call some function while initializing the Drawer view to reset the form elements.

**Comment by zxyao145** [comment]
> Hi @zxyao145 sorry for the late reply.
> 
> We have a form in the Drawer and I would like to call some function while initializing the Drawer view to reset the form elements.

@anktsrkr OK, I see. A temporary solution uses blazor's lifecycle function. And I will add this feature later, it is expected to be next week.
