### ISSUE TITLE
Model Service OnOk and OnCancel not firing.

### ISSUE THREAD

**Issue by vincejairam** [ant-design-blazor/ant-design-blazor#2534]
I copied the demo code to use a component in the Modal and I'm able to display my component but I don't see the OnOk or OnCancel firing when the buttons are clicked e.g.

`
            var options = new ConfirmOptions()
            {
                Title = $"Component - Details",
                Width = 450,
                OkText = "Update",                
            };

            var confirmRef = await ModalService.CreateConfirmAsync<TestDetails, TestListEntry, TestListEntry>(options, detailRecord);

            confirmRef.OnOpen = () =>
            {
                Console.WriteLine("Open Confirm");
                return Task.CompletedTask;
            };

            confirmRef.OnOk = (result) =>
            {
                Console.WriteLine($"OnOk:{result}");
                return Task.CompletedTask;
            };

            confirmRef.OnCancel = (result) =>
            {
                Console.WriteLine($"OnCancel:{result}");
                return Task.CompletedTask;
            };

`

**Comment by zxyao145** [comment]
@vincejairam Hello, what mode did you use? Wasm or server side

**Comment by vincejairam** [comment]
I'm using Server side.

**Comment by zxyao145** [comment]
@vincejairam Hi, in my local host, it works normally.

Have you override the OnFeedbackOkAsync and OnFeedbackCancelAsync  methods? Because the state of the subclass cannot be obtained in the parent class, you must override these two methods in the subclass to expose the value in the subclass.

![image](https://user-images.githubusercontent.com/24973084/176576977-8c907edd-f8b7-4256-9a2e-b708464b76b8.png)


If you don't care about the value, you could use the options method:

```c#
var options = new ConfirmOptions()
{
	Title = $"Component - Details",
	Width = 450,
	OkText = "Update",
};

// be careful
options.OnOk = (args) =>
{
	Console.WriteLine("options.OnOk");
	return Task.CompletedTask;
};
options.OnCancel = (args) =>
{
	Console.WriteLine("options.OnCancel");
	return Task.CompletedTask;
};
```

Please try the above method.

**Comment by vincejairam** [comment]
Hi @zxyao145 I had copied the code from the ModalService example https://antblazor.com/en-US/components/modal#components-modal-demo-form-in-modal which is the following:

`        var confirmRef = await _modalService.CreateConfirmAsync(options);

        confirmRef.OnOpen = () =>
        {
            Console.WriteLine("Open Modal");
            return Task.CompletedTask;
        };

        confirmRef.OnClose = () =>
        {
            Console.WriteLine("Close Modal");
            return Task.CompletedTask;
        };`


 I eventually got it to work another route where I have a grid and when u click a column it would show the dialog and its details in a form. I made a new details component which incapsulates the Modal component allowing the caller to pass in the flag to show the dialog and its data 

Parent Component
`....
<HospitalDetails 
       ShowDetails="ShowDetails"
       SelectedHospital="_selectedHospital"
/>

....`


HospitalDetails
`
...

<Modal Title="@($"{(string.IsNullOrEmpty(SelectedHospital.Name) ? "" : $"{SelectedHospital.Name}")} - Details")"
       Visible="@ShowDetails"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel">
       <Form Model="@SelectedHospital"
              Layout="@FormLayout.Horizontal"
              LabelColSpan="8"
              WrapperColSpan="16"
              Size="@AntSizeLDSType.Small"
              ValidateOnChange="@true"
              OnFinish="OnFinish"
              OnFinishFailed="OnFinishFailed"
              @ref="@_detailForm">
            <FormItem>
                <Input @bind-Value="@context.Name" />
            </FormItem>
            <FormItem>
                <Input @bind-Value="@context.AddressLine1" />
            </FormItem>
            <FormItem>
                <Input @bind-Value="@context.AddressLine2" />
            </FormItem>
            <FormItem>
                <Input @bind-Value="@context.City" />
            </FormItem>
            <FormItem>
                <Input @bind-Value="@context.PostalCode" />
            </FormItem>
            <FormItem Label="Active">
                <Switch @bind-Value="@context.IsActive" CheckedChildren="Yes" UnCheckedChildren="No" Size="small" />
            </FormItem>
        </Form>
</Modal>
`

The handlers in here were able to be fired correctly

`
...
....

namespace Portal.Pages.Configs.Hospitals
{
    public partial class HospitalDetails : ComponentBase
    {
        #region Properties
        [Inject]
        MessageService MessageService { get; set; }

        [Inject]
        ConfirmService ConfirmService { get; set; }

        [Parameter]
        public bool ShowDetails { get; set; }

        [Parameter]
        public HospitalListEntry SelectedHospital { get; set; }

        private Form<HospitalListEntry> _detailForm;
        #endregion

        /// <summary>
        /// Callback fired when the form submitted is valid
        /// </summary>
        /// <param name="editContext"></param>
        protected void OnFinish(EditContext editContext)
        {
            ShowDetails = false;
            Console.WriteLine("Form valid, save to DB.");
            MessageService.Success("Save to DB : Pending Development");
        }

        /// <summary>
        /// Callback fired when the form submitted is NOT valid
        /// </summary>
        /// <param name="editContext"></param>
        protected void OnFinishFailed(EditContext editContext)
        {
            Console.WriteLine($"Form failed to submit, invalid values: {JsonSerializer.Serialize(SelectedHospital)}...");
        }

        /// <summary>
        /// On modal OK button is click, submit form manually, so form 
        /// validation can be performed.
        /// </summary>
        /// <param name="e"></param>
        protected async Task HandleOk(MouseEventArgs e)
        {
            _detailForm.Submit();
        }

        protected async Task HandleCancel(MouseEventArgs e)
        {
            if (!_detailForm.IsModified)
            {
                ShowDetails = false;
            }
            else
            {
                var confirmResult = await ConfirmService.Show("Hospital has been modified", "Are you sure you wish to Cancel?", ConfirmButtons.YesNo);
                if (confirmResult == ConfirmResult.Yes)
                {
                    ShowDetails = false;
                }
            }
        }
    }
}


`

I figured I would open the issue for others as the sample didn't work for me... If its not reproducible you can close this down.

**Comment by zxyao145** [comment]
@vincejairam Sorry, I can't see your problem clearly, the layout is a little messy. Is there a problem with using modal in table?

Or maybe you can edit it again?

> Hi @zxyao145 I had copied the code from the ModalService example https://antblazor.com/en-US/components/modal#components-modal-demo-form-in-modal which is the following:
> 
> ` var confirmRef = await _modalService.CreateConfirmAsync(options);
> 
> ```
>     confirmRef.OnOpen = () =>
>     {
>         Console.WriteLine("Open Modal");
>         return Task.CompletedTask;
>     };
> 
>     confirmRef.OnClose = () =>
>     {
>         Console.WriteLine("Close Modal");
>         return Task.CompletedTask;
>     };`
> ```
> 
> I eventually got it to work another route where I have a grid and when u click a column it would show the dialog and its details in a form. I made a new details component which incapsulates the Modal component allowing the caller to pass in the flag to show the dialog and its data
> 
> Parent Component `....
> 
> ....`
> 
> HospitalDetails ` ...
> 
> <Modal Title="@(Unable to render expression. $"{(string.IsNullOrEmpty(SelectedHospital.Name) ? "" : $"{SelectedHospital.Name}")} - Details")" Visible="@ShowDetails" OnOk="@HandleOk" OnCancel="@HandleCancel"> <Form Model="@SelectedHospital" Layout="@FormLayout.Horizontal" LabelColSpan="8" WrapperColSpan="16" Size="@AntSizeLDSType.Small" ValidateOnChange="@true" OnFinish="OnFinish" OnFinishFailed="OnFinishFailed" @ref="@_detailForm"> <Input @bind-Value="@context.Name" /> <Input @bind-Value="@context.AddressLine1" /> <Input @bind-Value="@context.AddressLine2" /> <Input @bind-Value="@context.City" /> <Input @bind-Value="@context.PostalCode" /> <Switch @bind-Value="@context.IsActive" CheckedChildren="Yes" UnCheckedChildren="No" Size="small" /> `
> 
> The handlers in here were able to be fired correctly
> 
> ` ... ....
> 
> namespace Portal.Pages.Configs.Hospitals { public partial class HospitalDetails : ComponentBase { #region Properties [Inject] MessageService MessageService { get; set; }
> 
> ```
>     [Inject]
>     ConfirmService ConfirmService { get; set; }
> 
>     [Parameter]
>     public bool ShowDetails { get; set; }
> 
>     [Parameter]
>     public HospitalListEntry SelectedHospital { get; set; }
> 
>     private Form<HospitalListEntry> _detailForm;
>     #endregion
> 
>     /// <summary>
>     /// Callback fired when the form submitted is valid
>     /// </summary>
>     /// <param name="editContext"></param>
>     protected void OnFinish(EditContext editContext)
>     {
>         ShowDetails = false;
>         Console.WriteLine("Form valid, save to DB.");
>         MessageService.Success("Save to DB : Pending Development");
>     }
> 
>     /// <summary>
>     /// Callback fired when the form submitted is NOT valid
>     /// </summary>
>     /// <param name="editContext"></param>
>     protected void OnFinishFailed(EditContext editContext)
>     {
>         Console.WriteLine($"Form failed to submit, invalid values: {JsonSerializer.Serialize(SelectedHospital)}...");
>     }
> 
>     /// <summary>
>     /// On modal OK button is click, submit form manually, so form 
>     /// validation can be performed.
>     /// </summary>
>     /// <param name="e"></param>
>     protected async Task HandleOk(MouseEventArgs e)
>     {
>         _detailForm.Submit();
>     }
> 
>     protected async Task HandleCancel(MouseEventArgs e)
>     {
>         if (!_detailForm.IsModified)
>         {
>             ShowDetails = false;
>         }
>         else
>         {
>             var confirmResult = await ConfirmService.Show("Hospital has been modified", "Are you sure you wish to Cancel?", ConfirmButtons.YesNo);
>             if (confirmResult == ConfirmResult.Yes)
>             {
>                 ShowDetails = false;
>             }
>         }
>     }
> }
> ```
> 
> }
> 
> `
> 
> I figured I would open the issue for others as the sample didn't work for me... If its not reproducible you can close this down.

**Comment by vincejairam** [comment]
Let me see if I can redo this , sorry about that

**Comment by ElderJames** [comment]
Hi @vincejairam , have you solved this issue?

**Comment by vincejairam** [comment]
Hi @ElderJames I'm sorry for the late response, yes please close this out.

**Comment by Obaida00** [comment]
To be honest, I searched for a solve to this issue but couldn't find one and the demos are still not valid, so you my apologies if its already been looked at.

I came across this issue because I recently tried to make a confirm modal with some input elements and I needed to return that input to the parent element.

**the goal.**
is to make a confirmation modal using a custom blazor template that contains an input field, a parent element is going to use `await ModalService.CreateConfirmAsync<PackerConfirmModal, options, string>`* to show the dialog, when "confirm" is clicked, the value from that input field should be returned to the parent element.

**the issue.**
- the OnOk property in the ConfirmOptions is of type `Func<ModalClosingEventArgs,Task>` which does not contain the value
- if we do `confirmRef.OnOk = ResultCallbackFunction`, it will not execute because the `await ModalService.CreateConfirmAsync` awaits for the modal to open and close so when the execution reaches `confirmRef.OnOk = ResultCallbackFunction` the confirmation button is already clicked and its flow is completed
- the solution proposed by @zxyao145 [here](https://github.com/ant-design-blazor/ant-design-blazor/issues/2534#issuecomment-1170668788) also did not work, because in every scenario the OkCancelRefWithResult.OnOk is not set (null)

**my solution.**
its kind of a cheesy way around it, just making an options class like the following:
```
public class ConfirmModalOptions
{
    public Func<string, Task> OnOk { get; set; }
}
```
and passing it through the 'Create' method to the custom template like this:
```
await ModalService.CreateConfirmAsync<CustomConfirmModal, ConfirmModalOptions, string>(
            new ConfirmOptions()
            {
                Title = "Confirm To Start Packing",
                OkText = "Start Packing",
                CancelText = "Cancel",
                Width = 400,
                MaskClosable = true,
            }, new PackerConfirmModalOptions()
            {
                OnOk = value =>
                {
                    // here we have access to the value after the modal 'confirm' button is clicked
                    return Task.CompletedTask;
                }
            });
```

and inside the custom template we access it using the base.Options in the override of the methods `OnFeedbackOkAsync` and `OnFeedbackCancelAsync`:
```
    public override async Task OnFeedbackOkAsync(ModalClosingEventArgs args)
    {
        await this.Options.OnOk.Invoke(value);
        await base.OnFeedbackOkAsync(args);
    }
```

**my proposed solution.**
- a slight change in the `CreateConfirmAsync` method to make it only create the confirm modal and not open it, this way we can access the ConfirmRef and set the OnOk and OnCancel, and then we can do `ConfirmRef.OpenAsync`. I think this solves but I didn't dig extensively in the source code so i dont know the applications of that


\* 'options' here is just a placeholder, because its required and am not passing any options to the modal.

**Comment by ElderJames** [comment]
Thank you @Obaida00 , we have refactor the Closing issue for ConfirmService in https://github.com/ant-design-blazor/ant-design-blazor/pull/4704 . And we will add another feature that return the TResult directly, and will release in v1.5.0 this week.
