### ISSUE TITLE
<Carousel>: CarouselDotPosition.None

### ISSUE THREAD

**Issue by frindler** [ant-design-blazor/ant-design-blazor#2539]
For <Carousel> could we get a CarouselDotPosition.None, where no dots are displayed? (I'm using programmatic control of the slicks)? Thanks!

**Comment by ElderJames** [comment]
Thanks for contacting us @frindler , could you please explain the problem you met?

**Comment by frindler** [comment]
I'm having external "Prev" and "Next" buttons (which work fine) and the Carousel dots are sometimes on top of the content, which doesn't look very nice. So I'm just looking for a way to disable the dots completely. Thanks!

**Comment by ElderJames** [comment]
I think I get it. You're trying to hide the dots. Right?

**Comment by frindler** [comment]
Yes!
