### ISSUE TITLE
ant-design-blazor website

### ISSUE THREAD

**Issue by dld-yi** [ant-design-blazor/ant-design-blazor#2542]
Dual-core browser crashes after a few seconds

**Comment by ElderJames** [comment]
Hi @dld-yi , it works well. Can you give us more information?

**Comment by dld-yi** [comment]
About ten seconds after entering the page, it started crashing








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design-blazor/ant-design-blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月28日(星期二) 晚上6:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design-blazor/ant-design-blazor] ant-design-blazor website (Issue #2542)





 
Hi @dld-yi , it works well. Can you give us more information?

**Comment by ElderJames** [comment]
Yes, there is only a 10 second wait for the first load.

**Comment by dld-yi** [comment]
It takes a few seconds to view components and start crashing. Microsoft Edge is fine, but when you open a page in Chrome, it crashes

**Comment by dld-yi** [comment]
It takes a few seconds to view components and start crashing. Microsoft Edge is fine, but when you open a page in Chrome, it crashes

**Comment by ElderJames** [comment]
Hi @dld-yi , is the document working as expected?

**Comment by dld-yi** [comment]
No problem with the project

**Comment by ElderJames** [comment]
Ok, thanks. I will close this issue first. If you have any problems, please feel free to open another one.
