### ISSUE TITLE
Can't clone the repository

### ISSUE THREAD

**Issue by 0x3ch0** [ant-design-blazor/ant-design-blazor#2546]
Guys I can't even clone the repo by using the tutorial code
`git clone git@github.com:ant-design-blazor/ant-design-blazor.git`

the errors are
`
Please make sure you have the correct access rights
and the repository exists.
`

**Comment by ElderJames** [comment]
Hi @jesorian . Please try `git clone https://github.com/ant-design-blazor/ant-design-blazor.git`.

**Comment by jesorian** [comment]
It is working not thank you
