### ISSUE TITLE
Error trying to integrate AntBlazor to an existing Blazor application

### ISSUE THREAD

**Issue by jesorian** [ant-design-blazor/ant-design-blazor#2550]
### Describe the bug

I have an existing Blazor wasm application and trying to integrate AntBlazor to it. I am following the tutorial here https://github.com/ant-design-blazor/ant-design-blazor#import-ant-design-blazor-into-an-existing-project. The error is right after I executed the first command as instructed `dotnet add package AntDesign`. I am getting the errors:

```
dotnet : Could not find any project in `D:\BlazorAntDesign\`.
At line:1 char:1
+ dotnet add package AntDesign
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Could not find ...zorAntDesign\`.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

### Steps to reproduce (please include code)
Create a new Blazor WASM project powered by ASP.NET Core API and follow the instructions here https://github.com/ant-design-blazor/ant-design-blazor#import-ant-design-blazor-into-an-existing-project

### Exceptions (if any)
```
dotnet : Could not find any project in `D:\BlazorAntDesign\`.
At line:1 char:1
+ dotnet add package AntDesign
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Could not find ...zorAntDesign\`.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

### Further technical details
- VS2022 with .NET 6

**Comment by ElderJames** [comment]
Please run this command in a `csproj` directory
