### ISSUE TITLE
Can not convert lambda expression after upgrade to 0.11.0

### ISSUE THREAD

**Issue by charleypeng** [ant-design-blazor/ant-design-blazor#2554]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type	xx.xx. xxx\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_razor.g.cs	205	Active

**Comment by ElderJames** [comment]
Hi @charleypeng ,cloud you please post your code here?

**Comment by charleypeng** [comment]
> 
I found that I use "DataItemExpression" in TreeSelect but  this property does not available in v0.11

**Comment by charleypeng** [comment]
OK I noticed that the TreeSelect changed some  of its parameters. The Expression is now a TreeNode<T> and must change to delegate node=>node.DataItem.xxx
