### ISSUE TITLE
Texts in Modal cannot be selected

### ISSUE THREAD

**Issue by Abin-Liu** [ant-design-blazor/ant-design-blazor#2558]
### Describe the bug

Any text in a Modal component, including the Modal title itself, cannot be selected(highlighted) by mouse, it's a severe impact in user experience when people want to highlight and copy texts from a Modal dialog..

### Steps to reproduce (please include code)
The demo codes on official site have this bug too: [https://ant-design-blazor.gitee.io/zh-CN/components/modal](https://ant-design-blazor.gitee.io/zh-CN/components/modal)

### Further technical details
- AntDesign Nuget Package version: 0.11
- Browser: Microsoft Edge

**Comment by tompru** [comment]
Hi, you should try to add `user-select: all;` style to selectable content in your modal :)

**Comment by zxyao145** [comment]
This is because the class name of Modal's open animation is not deleted.

Why is there such a limitation, please see the issue of Antd React: https://github.com/ant-design/ant-design/issues/11777.



And This is a temporary solution (thx @tompru):

> Hi, you should try to add `user-select: all;` style to selectable content in your modal :)

**Comment by Abin-Liu** [comment]
> Hi, you should try to add `user-select: all;` style to selectable content in your modal :)

Thanks for the hint, though the way how texts are selected with style `user-select: all;` is just far from friendly...

**Comment by tompru** [comment]
You can also set `user-select: text;` :)
