### ISSUE TITLE
Image preview doesn't work

### ISSUE THREAD

**Issue by RaoHammas** [ant-design-blazor/ant-design-blazor#2564]
### Describe the bug

I'm trying to use ant design `Image` component. It shows the image on page but when i click on image it doesn't open a preview for it.

### Steps to reproduce
This is the code I'm using for image.  

```
            <Image Src="https://i.imgur.com/Idz3qcP.png"
                   PreviewSrc="https://i.imgur.com/Idz3qcP.png"
                   Preview="true" Height="200" Width="200"
                   PreviewVisible="true" ></Image>
```
It shows the image but nothing happens when i click the image.
![image](https://user-images.githubusercontent.com/16499626/178291142-82f3694c-4935-4abb-b67f-4c4253e5a6c5.png)

### Exceptions (if any)
No exception is occurring.
### Further technical details
- using the latest version of ant design for blazor.

**Comment by ElderJames** [comment]
Please add the <AntContainer /> on App.razor

**Comment by RaoHammas** [comment]
> Please add the `<AntContainer />` on App.razor

Hey, thank you. idk how did i miss that :(
