### ISSUE TITLE
Tabindex="-1" ignored inside a Tooltip

### ISSUE THREAD

**Issue by lukblazewicz** [ant-design-blazor/ant-design-blazor#2566]
Currently, when using a Tooltip around any kind of html element, the tabindex set on the child content is ignored.
For the sake of example, this works absolutely fine (the button gets no focus when tabbing via keyboard):
```
<button  tabindex="-1">
  click me
</button>
```
However, wrapping the button with a tooltip results in incorrect behavior - the button catches focus when user jumps through elements with tab key:
```
<HmbkTooltip Title="Some text">
  <button  tabindex="-1">
      click me
  </button>
</HmbkTooltip>

Is there any workaround for that?
```

Is there any solution to enforce `tabindex=-1` (or at least a similar behavior) on a Tooltip's content? 

Bonus question: is there a generic way to achieve such an effect on other components?

**Comment by ElderJames** [comment]
Thanks for your contribution @lukblazewicz

**Comment by lukblazewicz** [comment]
Always happy to help, @ElderJames. 😃 Any timeframe we could expect this change to be released? Not sure if we should wait with our internal release cycle.

**Comment by ElderJames** [comment]
If all goes well, there will be a release by the end of the week.

**Comment by lukblazewicz** [comment]
@ElderJames 
If there is anything we could do to help out with the release, just let me know. 👍
