### ISSUE TITLE
Tree can't selected checkbox by default

### ISSUE THREAD

**Issue by wyjfed24** [ant-design-blazor/ant-design-blazor#2577]
场景：在做角色权限管理时，选中角色加载菜单树，已有权限的菜单需要Checked

目前尝试了三种方法均不能实现。

![image](https://user-images.githubusercontent.com/23160155/179644030-311f3c1b-bfde-4f57-aa99-c4caa81bfae2.png)
![image](https://user-images.githubusercontent.com/23160155/179644282-80d0266a-86d9-4480-a6af-8234daf29639.png)

经过测试，在OnInitialized时加载树时，可以实现默认选中，但是用Button的OnClick或者Tree的OnSelect加载树时，默认选中失效。

希望有大佬可以指点下如何实现。

测试demo

```
<Row>
    <Col Span="6">

    <Button OnClick="Test">加载树</Button>
    </Col>
    <Col Span="6">

    <Tree TItem="RoleMenuNodeModel"
          DataSource="@roleMenuTree"
          Selectable="false"
          Checkable="true"
          DefaultCheckedKeys="@checkedIds"
          KeyExpression="x=>x.DataItem.Id"
          TitleExpression="x => x.DataItem.Name"
          ChildrenExpression="x => x.DataItem.Childs">
    </Tree>
    </Col>
    <Col Span="6">

    <Tree TItem="RoleMenuNodeModel" Checkable DefaultCheckedKeys="@checkedIds">
            @foreach (var item in roleMenuTree)
            {
            <TreeNode Title="@item.Name" Key="@item.Id" TItem="RoleMenuNodeModel">
                    @if (item.Childs != null && item.Childs.Count > 0)
                    {
                        @foreach (var subItem in item.Childs)
                        {
                        <TreeNode Title="@subItem.Name" Key="@subItem.Id" TItem="RoleMenuNodeModel"></TreeNode>
                        }
                    }
            </TreeNode>
            }
    </Tree>
    </Col>
    <Col Span="6">

    <Tree TItem="RoleMenuNodeModel" Checkable>
            @foreach (var item in roleMenuTree)
            {
            <TreeNode Title="@item.Name" Key="@item.Id" TItem="RoleMenuNodeModel" Checked="@item.Checked">
                    @if (item.Childs != null && item.Childs.Count > 0)
                    {
                        @foreach (var subItem in item.Childs)
                        {
                        <TreeNode Title="@subItem.Name" Key="@subItem.Id" TItem="RoleMenuNodeModel" Checked="@item.Checked"></TreeNode>
                        }
                    }
            </TreeNode>
            }
    </Tree>
    </Col>
</Row>
```
```
@code {
    List<RoleMenuNodeModel> roleMenuTree = new List<RoleMenuNodeModel>();
    string[] checkedIds = new[] { "971928e5-3fd9-4ddc-ba89-3a806129f654", "971928e5-3fd9-4ddc-ba89-3a806129f651", "971928e5-3fd9-4ddc-ba89-3a806129f65a", "971928e5-3fd9-4ddc-ba89-3a806129f65b", "971928e5-3fd9-4ddc-ba89-3a806129f65c" };
    public void Test()
    {
        roleMenuTree = new List<RoleMenuNodeModel>() {
            new RoleMenuNodeModel {  Id= "971928e5-3fd9-4ddc-ba89-3a806129f654" , Checked=true, Name="测试1"},
            new RoleMenuNodeModel {  Id= "971928e5-3fd9-4ddc-ba89-3a806129f651" , Checked=true, Name="测试2",Childs=new List<RoleMenuNodeModel>{
                new RoleMenuNodeModel {  Id= "971928e5-3fd9-4ddc-ba89-3a806129f65a" , Checked=true, Name="测试2-1"},
                new RoleMenuNodeModel {  Id= "971928e5-3fd9-4ddc-ba89-3a806129f65b" , Checked=true, Name="测试2-2"},
                new RoleMenuNodeModel {  Id= "971928e5-3fd9-4ddc-ba89-3a806129f65c" , Checked=true, Name="测试2-3"},
                }
            },
            new RoleMenuNodeModel {  Id= "971928e5-3fd9-4ddc-ba89-3a806129f652" , Checked=true, Name="测试3"},
            new RoleMenuNodeModel {  Id= "971928e5-3fd9-4ddc-ba89-3a806129f653" , Checked=true, Name="测试4"},
            };
    }

    public class RoleMenuNodeModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public bool Checked { get; set; }
        public List<RoleMenuNodeModel> Childs { get; set; }
    }
}
```

**Comment by WhyILoveSpringRoll** [comment]
你好，第 2 3种方式绑定数据会有些问题，请这样使用哦。
`<Row>
    <Col Span="6">

    <Button OnClick="Test1">加载树</Button>
    </Col>
    <Col Span="6">

    <Tree TItem="RoleMenuNodeModel"
          DataSource="@roleMenuTree"
          Checkable
          DefaultCheckedKeys="@checkedIds"
          KeyExpression="x=>x.DataItem.Id"
          TitleExpression="x => x.DataItem.Name"
          ChildrenExpression="x => x.DataItem.Childs"
          @bind-CheckedKeys="checkedKeys">
    </Tree>
    </Col>
  
</Row>`

`
@code {
    List<RoleMenuNodeModel> roleMenuTree = new List<RoleMenuNodeModel>();
    string[]? checkedIds = new string[] { };
    string[]? checkedKeys = new string[] { };
    public void Test1()
    {
        roleMenuTree = new List<RoleMenuNodeModel>() {
            new RoleMenuNodeModel {  Id= "测试1" , Name="测试1"},
            new RoleMenuNodeModel {  Id= "测试2" , Name="测试2",Childs=new List<RoleMenuNodeModel>{
                new RoleMenuNodeModel {  Id= "测试2-1" ,  Name="测试2-1"},
                new RoleMenuNodeModel {  Id= "测试2-2" , Name="测试2-2"},
                new RoleMenuNodeModel {  Id= "测试2-3" ,  Name="测试2-3"},
                }
            },
            new RoleMenuNodeModel {  Id= "测试3" ,  Name="测试3"},
            new RoleMenuNodeModel {  Id= "测试4" , Name="测试4"},
            };
           
        checkedIds= new[] { "测试2-1","测试3"};
        checkedKeys = new[] { "测试2-1","测试3"};
    }

    public class RoleMenuNodeModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public bool Checked { get; set; }
        public List<RoleMenuNodeModel> Childs { get; set; }
    }
}
`


p.s.   Selectable="false" Checkable="true"，这两个属性共存会有bug，稍后进行修复

**Comment by wyjfed24** [comment]
> 你好，第 2 3种方式绑定数据会有些问题，请这样使用哦。
> 
> ```
> <Row>
>     <Col Span="6">
>     <Button OnClick="Test1">加载树</Button>
>     </Col>
>     <Col Span="6">
> 
>     <Tree TItem="RoleMenuNodeModel"
>           DataSource="@roleMenuTree"
>           Checkable
>           DefaultCheckedKeys="@checkedIds"
>           KeyExpression="x=>x.DataItem.Id"
>           TitleExpression="x => x.DataItem.Name"
>           ChildrenExpression="x => x.DataItem.Childs"
>           @bind-CheckedKeys="checkedKeys">
>     </Tree>
>     </Col>
> </Row>
> ```
> 
> ```
> @code {
>     List<RoleMenuNodeModel> roleMenuTree = new List<RoleMenuNodeModel>();
>     string[]? checkedIds = new string[] { };
>     string[]? checkedKeys = new string[] { };
>     public void Test1()
>     {
>         roleMenuTree = new List<RoleMenuNodeModel>() {
>             new RoleMenuNodeModel {  Id= "测试1" , Name="测试1"},
>             new RoleMenuNodeModel {  Id= "测试2" , Name="测试2",Childs=new List<RoleMenuNodeModel>{
>                 new RoleMenuNodeModel {  Id= "测试2-1" ,  Name="测试2-1"},
>                 new RoleMenuNodeModel {  Id= "测试2-2" , Name="测试2-2"},
>                 new RoleMenuNodeModel {  Id= "测试2-3" ,  Name="测试2-3"},
>                 }
>             },
>             new RoleMenuNodeModel {  Id= "测试3" ,  Name="测试3"},
>             new RoleMenuNodeModel {  Id= "测试4" , Name="测试4"},
>             };
>            
>         checkedIds= new[] { "测试2-1","测试3"};
>         checkedKeys = new[] { "测试2-1","测试3"};
>     }
> 
>     public class RoleMenuNodeModel
>     {
>         public string Id { get; set; }
>         public string Name { get; set; }
>         public bool Checked { get; set; }
>         public List<RoleMenuNodeModel> Childs { get; set; }
>     }
> }
> ```
> 
> 补充：Selectable="false" Checkable="true"，这两个属性共存会有bug，稍后进行修复





谢谢大佬指点
