### ISSUE TITLE
If you use more than 1 tabPane, you will get an error

### ISSUE THREAD

**Issue by GlodenBoy** [ant-design-blazor/ant-design-blazor#2578]
### Describe the bug

If you use more than 1 tabs tabs, you will get an error

### Steps to reproduce (please include code)

![image](https://user-images.githubusercontent.com/2329528/179660320-efaa2f9a-076d-4cb6-a973-12f0ba33fc61.png)

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/2329528/179660341-e3d75c1c-e45c-4900-b796-97e694248e2b.png)

### Further technical details
- AntDesign Nuget Package version -> 0.11.0
- The IDE -> rider

**Comment by anranruye** [comment]
I can't reproduce this. Can you provide more information?

**Comment by GlodenBoy** [comment]
> I can't reproduce this. Can you provide more information?

I don't know why, since I can't get around this, I have to replace another component
