### ISSUE TITLE
Table "disabled section" work incorrectly

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#2582]
### Discussed in https://github.com/ant-design-blazor/ant-design-blazor/discussions/2580

<div type='discussions-op-text'>

<sup>Originally posted by **Roc-Camera** July 21, 2022</sup>
当表格可勾选项全部为禁用状态时 理论上表格全选应该是空，但实际上却是全选状态。

![UBrYeZXEPU](https://user-images.githubusercontent.com/99702562/180120980-69f5814d-d4dd-40b6-bf01-e37db18882be.jpg)

https://user-images.githubusercontent.com/99702562/180120613-45e95949-a815-414c-a9ce-e921732114ee.mp4

</div>

**Comment by YongQuan-dotnet** [comment]
i can work on it

**Comment by YongQuan-dotnet** [comment]
PR is merged. can we mark it as Done?

**Comment by ElderJames** [comment]
@YongQuan-dotnet  Yes, thank you.
