### ISSUE TITLE
The value of Input/Search keep null when using mouse right button paste.

### ISSUE THREAD

**Issue by sxbyl** [ant-design-blazor/ant-design-blazor#2591]
### Describe the bug

The value of Input/Search keep null when using mouse right button paste, and OnChange not invoked.

### Steps to reproduce (please include code)
```
<Input @ref=inputTest @bind-Value=textTest OnChange="((string text)=>OnTextChange(text))"></Input>
<Button Type=@ButtonType.Primary OnClick="OnOK">OK</Button>

@code {
    private string textTest;
    private AntDesign.Input<string> inputTest;

    private void OnTextChange(string text)
    {
        //not invoked if using mouse right button paste
    }

    private void OnOK()
    {
        //textTest keeps null if using mouse right button paste
    }
}
```

### Further technical details
- AntDesign Nuget Package 0.11.0
- Visual Studio 2022 17.3.0

**Comment by WhyILoveSpringRoll** [comment]
OnTextChange will trigger when Input  blur.

**Comment by WhyILoveSpringRoll** [comment]
https://user-images.githubusercontent.com/14737143/182275299-d057163e-40a4-43e5-8b90-42d1d1e366f7.mp4

**Comment by sxbyl** [comment]
> OnTextChange will trigger when Input blur.

Thanks.
 I have just tried again. OnTextChange will be invoked twice when Input blur, one null and one correct input.
But OnSearch won't invoke for Search component, and OnTextChange did not invoke too.

**Comment by WhyILoveSpringRoll** [comment]
Search component 'OnChange' also invoked twice when blur, I will check it.

**Comment by sxbyl** [comment]
> Search component 'OnChange' also invoked twice when blur, I will check it.

I clicked "Search" button of Search component,  OnTextChange not invoked, and the inpurt value keep null in OnSearch callback, and OnBlur is not invoked.

**Comment by WhyILoveSpringRoll** [comment]
it has two issues
* OnChange will invoke twice when using mouse right button paste data to Input
* when using mouse right button paste data to Input that blur can't invoke

**Comment by ElderJames** [comment]
Have been fixed in latest version.
