### ISSUE TITLE
Cascader Clear Button Does Not Clear Search Field

### ISSUE THREAD

**Issue by cr4shed** [ant-design-blazor/ant-design-blazor#2607]
### Describe the bug

Clicking the clear button in the `Cascader` component when `AllowClear` is `true` does not clear the search term entered into the search field (when `ShowSearch` is `true`). 

It would make sense for the clear button to clear the search term where applicable, or otherwise clear the current selection.

### Steps to reproduce (please include code)
Repro project can be found [in this repo](https://github.com/cr4shed/ant-design-cascader-bug). Alternatively the search example in the [components documentation](https://antblazor.com/en-US/components/cascader) works as well.

1. Run project.
2. Enter a search term into the `Cascader` search field.
3. Attempt to clear the search term using the clear button.

### Further technical details
- Repro project is using AntDesign.ProLayout 0.10.6, also tested with AntDesign 0.11.0.
- Visual Studio 17.1.6
<details>
    <summary>dotnet --info</summary>

    .NET SDK (reflecting any global.json):
     Version:   6.0.202
     Commit:    f8a55617d2
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.18363
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\6.0.202\
    
    Host (useful for support):
      Version: 6.0.4
      Commit:  be98e88c76
    
    .NET SDKs installed:
      6.0.202 [C:\Program Files\dotnet\sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

**Comment by WhyILoveSpringRoll** [comment]
Thanks for reporting, It has been fixed now  and will be update in the next version。
