### ISSUE TITLE
AutoComplete Compoment close animation

### ISSUE THREAD

**Issue by lyj0309** [ant-design-blazor/ant-design-blazor#2611]
很多选择组件在选择的时候会有一个回弹动画，但是 `AutoComplete ` 组件没有

AutoComplete组件
![4](https://user-images.githubusercontent.com/50474995/184089699-404624a8-1834-4eb2-aa3f-5d452c4f4c2b.gif)

Select 组件

![5](https://user-images.githubusercontent.com/50474995/184089778-adaff2c4-3045-4ff0-8f68-4a8350e38fb9.gif)

**Comment by ElderJames** [comment]
It work well now. Thanks.
