### ISSUE TITLE
Button icon error

### ISSUE THREAD

**Issue by Kistelekig98** [ant-design-blazor/ant-design-blazor#2613]
### Describe the bug

In a new project the icon of the AntDesign.Button is not centered vertically:
![image](https://user-images.githubusercontent.com/11194127/184324335-bdd82a90-64a3-42a0-a91b-7f99ae03d835.png)

But in the [documentation](https://antblazor.com/en-US/components/button#ant-blazor-cd124852-aa50-40c8-bf4f-9219ac59481e) the icon is centered vertically:
![image](https://user-images.githubusercontent.com/11194127/184324720-bb11b34e-1457-4153-a63b-17ec922416d0.png)

### Steps to reproduce (please include code)

[Repo](https://github.com/Kistelekig98/BlazorApp1)

I created a Blazor WebAssembly app, added AntDesign nuget and placed a button in the Index.razor like this:
```
<Button Icon="@IconType.Outline.Search">
  Test button
</Button>
```

### Further technical details
- AntDesign Nuget Package version 0.11.0
- the output of `dotnet --info`

> .NET SDK (reflecting any global.json):
>  Version:   6.0.302
>  Commit:    c857713418
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19044
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.302\
> 
> global.json file:
>   Not found
> 
> Host:
>   Version:      6.0.7
>   Architecture: x64
>   Commit:       0ec02c8c96
> 
> .NET SDKs installed:
>   6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]
>   6.0.302 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Download .NET:
>   https://aka.ms/dotnet-download
> 
> Learn about .NET Runtimes and SDKs:
>   https://aka.ms/dotnet/runtimes-sdk-info

- Visual Studio Community 2022 17.2.6

**Comment by tpnest** [comment]
Yes, I have the same problem

**Comment by WhyILoveSpringRoll** [comment]
The style of antd blazor will conflict with bootstrap.You need remove bootstrap  at index.html(wasm) or _Host.cshtml(Server)

**Comment by WhyILoveSpringRoll** [comment]
> Yes, I have the same problem

The style of antd blazor will conflict with bootstrap.You need remove bootstrap at index.html(wasm) or _Host.cshtml(Server)
