### ISSUE TITLE
MessageService interface

### ISSUE THREAD

**Issue by kooliokey** [ant-design-blazor/ant-design-blazor#2631]
### Is your feature request related to a problem? Please describe.
I have tried to unit test that my code displays certain messages, but am unable to since the `MessageService` is not an interface and is a concrete class. 

### Describe the solution you'd like
Create an interface such as `IMessageService` to hold the API of `MessageService`. `MessageService` would be an implementation of that and code would start injecting `IMessageService` which will then allow mocking of the service during testing.

### Additional context
Was this by design or something that we would be open to a PR to change?

**Comment by ElderJames** [comment]
Thanks for contacting us @kooliokey . This is open to PR.

**Comment by ElderJames** [comment]
Hi @kooliokey , would you be interested in helping to increase test coverage of this project? We plan to release the official version when the coverage reaches the desired value > 90%.

**Comment by kooliokey** [comment]
@ElderJames Sure, I can look at where I can add to it. I would have added some for this PR but honestly the implementation confused me a bit and I didn't have time to dig into it :)

**Comment by kooliokey** [comment]
PR for the update is in master now. Closing this issue.

**Comment by ElderJames** [comment]
@kooliokey Thank you! We can open another issue for the unit tests topic.
