### ISSUE TITLE
TimePicker resets to default value after being changed and clicked out of the picker.

### ISSUE THREAD

**Issue by nejckikelj** [ant-design-blazor/ant-design-blazor#2637]
Video describes it better than 100 words... :

https://user-images.githubusercontent.com/108667817/186444042-638ccd28-b4c4-4a4b-b56b-e0e90db8f5d2.MOV

)

**Comment by nejckikelj** [comment]
After some more investigation it seems like OnChange is called apon clicking away from the picker with old (initial) value...

**Comment by nejckikelj** [comment]
The problem seems to be, that pickerStatus.IsNewValueSelected is false  when changing time... is there an easy way to change that, since I don't need an OK button...

**Comment by ElderJames** [comment]
Hi @Alexbits , could you please take a look at this?
