### ISSUE TITLE
Remove/Refactor unusable code in Breadcrumb

### ISSUE THREAD

**Issue by kooliokey** [ant-design-blazor/ant-design-blazor#2649]
### Is your feature request related to a problem? Please describe.
I started looking at writing unit tests for Breadcrumb/BreadcrumbItem and noticed there is code that is not currently able to be used by anyone. The `AutoGenerate` functionality in Breadcrumb will never be used. Even if someone sets that parameter to true, they cannot set the `_breadcrumbs` that would be rendered so it is unusable as-is. 

```
<CascadingValue Value="this" IsFixed="@true">
    <div class="@ClassMapper.Class" style="@Style" id="@Id" @ref="Ref">
        @ChildContent
        @if (AutoGenerate)
        {
            foreach (var breadcrumb in _breadcrumbs)
            {
                <BreadcrumbItem>
                    <a href="@breadcrumb.Url" @onclick="(e)=>Navigate(breadcrumb.Url.ToString())">@breadcrumb.Label</a>
                </BreadcrumbItem>
            }
        }
    </div>
</CascadingValue>
```

I assume this is from porting functionality from the react version? Will this code eventually be used and should stay or should we refactor it or remove it until then?

### Describe the solution you'd like
My vote would be to remove this functionality until it can be used. My guess is it came from the router functionality in the react library. I would also vote this route because the documentation doesn't currently mention that property. If we don't want to remove it, perhaps we should make `_breadcrumbs` a parameter that can be passed and the items autogenerated from that.

### Additional context
Related files:
https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/breadcrumb/Breadcrumb.razor.cs
https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/breadcrumb/Breadcrumb.razor

**Comment by ElderJames** [comment]
We can remove it for a while, but it does make sense to implement it. But we need to get the routing list of the Blazor, which is more difficult.
