### ISSUE TITLE
form 表单OnFinish和OnFinishFailed 无法正常响应

### ISSUE THREAD

**Issue by yuanxiongwei** [ant-design-blazor/ant-design-blazor#266]
form 表单OnFinish和OnFinishFailed 无法正常响应 .Button 设置类型 HtmlType="submit"无法正常触发submit事件，无法输出对应的信息。代码是从示例网站直接复制的。没有弄明白是否是bug。项目是 server mode。是否只支持blazor.webassembly？？

**Comment by mutouzdl** [comment]
server和wasm都支持的，我这边测试是正常，你具体用的是哪个例子的代码，可以贴出来吗？

---------------translate by bing---------------
Server and wasm are supported, my side test is normal, you specifically use which example of the code, can you show it?

**Comment by mutouzdl** [comment]
我想再问一下，你是在控制台查看输出的信息吗？Server模式没法在浏览器的F12里看信息

---------------translate by bing---------------
I'd like to ask again, are you looking at the output in the console? Server mode can't see information in the browser's F12

**Comment by yuanxiongwei** [comment]
@mutouzdl 大佬中英文很贴心，我更新了最新版本正常了。 感谢提醒F12无法看到信息。
