### ISSUE TITLE
The rendering of Tabs without Animation is broken

### ISSUE THREAD

**Issue by chunliu** [ant-design-blazor/ant-design-blazor#2675]
### Describe the bug

With fix #2671, the rendering of animated Tabs works fine, but the rendering of Tabs without animation is broken. See the following screenshot from the doc site:

![image](https://user-images.githubusercontent.com/2128551/188343574-eeabb43d-d083-4e0e-a0da-9642e764fe2b.png)

And it seems the animation also works now when the `TabPosition` is set to left or right, which is good. If the animation direction can be from top or bottom when the `TabPosition` is set to left or right, that will be even better. 

### Steps to reproduce (please include code)

Visit doc site here: https://antblazor.com/en-US/components/tabs

### Further technical details
- AntDesign Nuget Package version: v0.12.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thaks for contacting us @chunliu , this issue have been fixed and will ship today.

For the left or right animation, Antd itself does not support this. We need additional research.
