### ISSUE TITLE
Console output: "Loading failed for the <script> with source..."

### ISSUE THREAD

**Issue by Erol444** [ant-design-blazor/ant-design-blazor#268]
I am using Blazor WASM and I have .NET core 3.1.301 installed. After going through all the installation steps, when loading the page, this gets printed into the console:
`Loading failed for the <script> with source “https://localhost:44340/_content/AntDesign/js/ant-design-blazor.js”.`

It might be the wrong Program.cs code, which is like following:
``` 
public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
            builder.Services.AddAntDesign();

            await builder.Build().RunAsync();
        }
```

Do I have to manually download the script/css and have it in the wwwroot folder? I'm just starting with the blazor so I apologize if I have made some obvious mistake.

Thanks!

**Comment by ElderJames** [comment]
Thank you for contacting us @Erol444 .
Please dont install the rc version, and we will fix it today.

**Comment by ElderJames** [comment]
We have fixed the static files issue. Please install 0.1.0-rc.4 and try again.
