### ISSUE TITLE
Add a status parameter on the modal component.

### ISSUE THREAD

**Issue by DiberySky** [ant-design-blazor/ant-design-blazor#2684]
Please expose the private property of modal component: modalstatus as a parameter.

**Comment by zxyao145** [comment]
> Please expose the private property of modal component: modalstatus as a parameter.

@DiberySky 
Hi, What do you need this parameter for? 
If the `modalstatus` is exposed as a paramter, the status of the Modal will be confused:
If the `modalstatus` is set to ModalStatus.Max in the Modal, the parent component still is ModalStatus.Default, and re-render at this time, then the `modalstatus` will be reset to ModalStatus.Default, this is not as expected.
