### ISSUE TITLE
Tree control collapses automatically when clicked

### ISSUE THREAD

**Issue by shuaqq2004** [ant-design-blazor/ant-design-blazor#2695]
1.Tree控件点击会自动收缩
根据文档：
```
<Tree ShowIcon SelectedNodeChanged="SelectedNodeChanged" TItem="Data" DataSource="xxxx"
```
一旦设置属性： OnClick， SelectedNodeChanged, SelectedDataChanged 这样的点击事件。
当前Tree会全部收缩。

参考代码来自官网文档：
![image](https://user-images.githubusercontent.com/3870105/189089573-2e1892d8-6941-4e84-a4fc-89bdd8f8fb8e.png)

**Comment by ElderJames** [comment]
Hello @shuaqq2004 , this issue have been fixed. Please check out the latest version.
