### ISSUE TITLE
Bugs in Drawer OnClose event and missing ant-design-blazor.js

### ISSUE THREAD

**Issue by ozzioma** [ant-design-blazor/ant-design-blazor#270]
The Drawer component has some bugs that were not there before.

When you initialize show the Drawer, the OnClose event fires properly and closes the Drawer.
When the Drawer is shown a second or third time, the OnClose event does not fire and the Drawer does not close.

Had to start rolling back to previous versions.

Also with the latest 0.1-rc version, the ant-design-blazor.js file is missing and blazor throws a Javascript error related to "Antd windows"

Thanks for the great work anyways.
Would love to submit a PR one of these days.

Please help fix these bugs.

Thanks,
Ozzy

**Comment by ElderJames** [comment]
Thanks for support us @ozzioma ! 
The rc version is a test for our new release ci. There are maybe some issues and I will fix them today.

**Comment by ElderJames** [comment]
We have fixed the static files issue. Please install 0.1.0-rc.4 .

**Comment by ozzioma** [comment]
@ElderJames 
thanks for the quick fix!

However there's still a bug with the Drawer component.
You need to click twice or more on the Close icon for the event to be fired and the Drawer to close.
Maybe the internal handler is not properly bound to the event or a counter is not properly reset?

The MaxClosable event is fired just fine and works well. 
Problem is with the close icon and OnClose event.

Thanks again!

**Comment by ozzioma** [comment]
@ElderJames 

I just noticed the problem might be with the onclick handler for the close icon.
When you click on the upper part of the close icon box, the event is fired.
If you click directly on the close icon itself, or within the body of the icon button the close event is not fired.


```
<button aria-label="Close" class="ant-drawer-close">
--
  <span role="img" class=" anticon anticon-sync" id="ant-blazor-66ec1291-6b99-405e-86ab-2b2c2c16dc4a" __internal_stopPropagation_onclick>
  <?xml version="1.0" standalone="no"?>
  <svg focusable="false" width="1em" height="1em" fill="currentColor" style="transform: rotate(0deg); "   xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 1024 1024">
  <path d="M563.8 512l262.5-312.9c4.4-5.2.7-13.1-6.1-13.1h-79.8c-4.7 0-9.2 2.1-12.3 5.7L511.6 449.8 295.1 191.7c-3-3.6-7.5-5.7-12.3-5.7H203c-6.8 0-10.5 7.9-6.1 13.1L459.4 512 196.9 824.9A7.95 7.95 0 0 0 203 838h79.8c4.7 0 9.2-2.1 12.3-5.7l216.5-258.1 216.5 258.1c3 3.6 7.5 5.7 12.3 5.7h79.8c6.8 0 10.5-7.9 6.1-13.1L563.8 512z"/>
   </svg>
  </span>
  </button>

```

Maybe the onclick event needs to be bound to the entire button and it's inner components?
It appears the click event is not propagated properly.

Thanks again!

**Comment by ElderJames** [comment]
@ozzioma Thank you for your thoughts, I have fixed it. Please check it out.
Please use the latest Preview version(not rc.x).

**Comment by ozzioma** [comment]
@ElderJames 
Thanks for the quick response!

However I cant find the latest preview release after the RC version.
Have you published to Nuget yet? If so can you share the link?
Thanks!
