### ISSUE TITLE
Segmented component binding error

### ISSUE THREAD

**Issue by Kistelekig98** [ant-design-blazor/ant-design-blazor#2704]
### Describe the bug
I try to bind a Segmented component to a boolean property, but it does not work at the first render.

### Steps to reproduce
SegmentedTest.razor:
```
<Segmented @bind-Value="FirstProperty">
  <SegmentedItem Value="true" Label="True" />
  <SegmentedItem Value="false" Label="False" />
</Segmented>

<Segmented @bind-Value="SecondProperty">
  <SegmentedItem Value="true" Label="True" />
  <SegmentedItem Value="false" Label="False" />
</Segmented>

<Divider />

<Checkbox @bind-Checked="FirstProperty" />
<Checkbox @bind-Checked="SecondProperty" />
```
SegmentedTest.razor.cs:
```
public partial class SegmentedTest
{
  public bool FirstProperty { get; set; }
  public bool SecondProperty { get; set; }

  protected override void OnInitialized()
  {
    FirstProperty = false;
    SecondProperty = true;
  }
}
```

You can run my [basic test app](https://github.com/Kistelekig98/BlazorApp1) as well.
Open "Segmented" menu from the NavMenu.
Now the checkboxes are binded properly, but the Segmented components are not. (After you click on them, they start working)

### Further technical details
- AntDesign Nuget Package version: 0.12.2
- output of `dotnet --info`:
> NET SDK (reflecting any global.json):
>
> Version:   6.0.400
>  Commit:    7771abd614
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22000
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.400\
> 
> global.json file:
>   Not found
> 
> Host:
>   Version:      6.0.8
>   Architecture: x64
>   Commit:       55fb7ef977
> 
> .NET SDKs installed:
>   6.0.400 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- IDE: Visual Studio 2022 Community 17.3.2

**Comment by ElderJames** [comment]
Thanks @Kistelekig98 , we would fix this by #2699

**Comment by ElderJames** [comment]
Hello @Kistelekig98 , please check if the v0.12.3 solve this issue.

**Comment by Kistelekig98** [comment]
@ElderJames it is working now, thank you! 🎉
