### ISSUE TITLE
Ant in MAUI Blazor project freezes all controls (only real devices)!

### ISSUE THREAD

**Issue by pc-Justin** [ant-design-blazor/ant-design-blazor#2724]
### Describe the bug

If you include Ant component in a MAUI Blazor application and then run the application on your phone, you will be able to click around a few times, but after a short time the default menu of the MAUI Blazor application freezes like the Ant component you selected (I included the Rate-component  for example).

But if you do the same with Adnroid Emulator in Visual Studio 2022, then everything works fine!

Of course, the problem also exists when you publish APK file and install it on an Android phone!

But if you install APK file on a, in Internet, online emulator, then everything works again! 

### Steps to reproduce (please include code)
- First create a MAUI Blazor project (use template in Visual Studio 2022).
- Include the Ant component in the project (as described in the Ant doc)
- Activate USB on the Android phone and connect it to the computer where the project is open in VS 2022
- Before running the project, select the "Android Local Device" entry from the list and select your phone.
- Now start the project (if problem, see Note)
When the application is running on the phone, you will be able to click around a few times, but after a short time the default menu of the application will freeze like the ant component you selected (for example, I added Rate ).

**Note:** 
Currently there is a release issue with NET MAUI Blazor and Android. The problem is described here:

https://github.com/dotnet/maui/issues/10102

Solution is very simple to get on with the execution:

obj\Debug\net6.0-android\staticwebassets.build.json
Copy
obj\Debug\net6.0-android\android-arm64\staticwebassets.build.json

### Exceptions (if any)
On an Android emulator everything works perfectly
### Further technical details
- AntDesign Nuget Package version 0.12.4
- The IDE VS 2022 Version 17.3.4

**Comment by pc-Justin** [comment]
This is not an Ant problem, but a Google problem with the WebView component. In the meantime, the problem with Google WebView should be fixed with the latest version.

If the old version of 09/05/2022 is still on the phone, then simply uninstall (Android then leaves the factory version of WebView on it with which then everything works).

See also:
https://github.com/dotnet/maui/issues/9882

Justin

**Comment by KieranDevvs** [comment]
Had this problem for the past few days, spent hours trying to debug what was causing it. Thanks for the info.
