### ISSUE TITLE
ReuseTabs Component causes SupplyParameterFromQuery to fail

### ISSUE THREAD

**Issue by berkerdong** [ant-design-blazor/ant-design-blazor#2727]
The ReuseTabs component causes SupplyParameterFromQuery to fail, and the parameters passed in through the url cannot be obtained

ReuseTabs 组件导致 SupplyParameterFromQuery 失效，获取不到通过url 传入的参数

[https://learn.microsoft.com/zh-cn/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-6.0#query-strings](https://learn.microsoft.com/zh-cn/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-6.0#query-strings)

```
    [Parameter]
    [SupplyParameterFromQuery(Name = "name")]
    public string? name { get; set; }
```

**Comment by ElderJames** [comment]
duplicated with #2422

**Comment by ElderJames** [comment]
Would be fixed in .NET 8 https://github.com/dotnet/aspnetcore/pull/49261
