### ISSUE TITLE
DateTimePicker control cannot switch year/month

### ISSUE THREAD

**Issue by shuaqq2004** [ant-design-blazor/ant-design-blazor#2729]
https://antblazor.com/zh-CN/components/datepicker

![image](https://user-images.githubusercontent.com/3870105/191149183-d9e74f7b-c795-4ece-897b-d642f91fcd09.png)

这里点击 年/月  无法切换到对应的年份或月份上
Clicking year/month here cannot switch to the corresponding year or month

**Comment by Alexbits** [comment]
@shuaqq2004 @ElderJames I can't reproduce it. What is the issue exactly here?

**Comment by shuaqq2004** [comment]
> @shuaqq2004 @ElderJames I can't reproduce it. What is the issue exactly here?

step 1:
![image](https://user-images.githubusercontent.com/3870105/192231082-98142ef1-628e-42e7-8ebe-85307a9ead1f.png)

step 2:
Click on the 2020 year:

![image](https://user-images.githubusercontent.com/3870105/192231160-bc5a4b01-7e0e-45cc-838e-39be71d79f0b.png)
![image](https://user-images.githubusercontent.com/3870105/192231245-d502c09c-d381-4783-a25c-497e3c8d71f7.png)

step 3:
正确情况是出现2020年9月的内容并选择。
但是结果还是2022年的9月日期
----------
The correct scenario is to show the September 2020 content and select.
But it still turned out to be a September 2022 date.
![image](https://user-images.githubusercontent.com/3870105/192231392-0e9f4a60-82d5-4b12-9494-b5d768badf5c.png)

**Comment by Alexbits** [comment]
@shuaqq2004 Thanks. I see it now.

**Comment by Alexbits** [comment]
@shuaqq2004 @ElderJames added fix to #2741

**Comment by ElderJames** [comment]
@Alexbits Big thanks!
