### ISSUE TITLE
Unit testing on Row raises an exception

### ISSUE THREAD

**Issue by mkk2cp** [ant-design-blazor/ant-design-blazor#2733]
### Describe the bug

Unit test on `Row` component raises an exception with  `BUnit`.

### Steps to reproduce (please include code)
Create a sample component `SampleRow.razor`.
```
@page "/row"

<Row>
    <p class="my-row">This is inside row.</p>
</Row>
```
Create a unit test with `BUnit`. `TestBase` inherits  `AntDesign.Tests.AntDesignTestBase`.
```
@inherits TestBase

@code {
    [Fact]
    public void TestRow()
    {
        SetUpDI();

        var cut = RenderComponent<SampleRow>();

        Assert.Equal(1, cut.FindAll("p.my-row").Count);

    }
}
```
Run the test in test explorer.

### Exceptions (if any)
Object reference exception in  `Row.AfterRenderAsync`
![image](https://user-images.githubusercontent.com/111335916/191414549-9029e4b2-471d-405e-8c51-2561399d655a.png)

### Further technical details
- AntDesign Nuget Package version = 0.110
- VS 2022

**Comment by ElderJames** [comment]
Hi @mkk2cp , would you please help us to improve the test coverage #2644 ?

**Comment by ElderJames** [comment]
`  JSInterop.Setup` is need to call for register the interop

```
    [Fact]
    public void TestRow()
    {
        JSInterop.Setup<Window>(JSInteropConstants.GetWindow, _ => true);
        var cut = RenderComponent<SampleRow>();
        Assert.Equal(1, cut.FindAll("p.my-row").Count);

    }
```
