### ISSUE TITLE
When using IMessageService to pop up the message box in Modal, 2 messages pop up

### ISSUE THREAD

**Issue by GlodenBoy** [ant-design-blazor/ant-design-blazor#2745]
When using IMessageService to pop up the message box in Modal, 2 messages will pop up, one will pop up on the outside, one on the inside, and when the modal is closed, the internal message will be closed, but the external one will not.

**Comment by zxyao145** [comment]
@GlodenBoy 

Hi, I'm sorry that I can't reproduce this problem locally. Could you provide a demo?

**Comment by GlodenBoy** [comment]
@zxyao145 
Sorry, I found that I can't reproduce it, I don't know what caused it, and I'm sorry for delaying your time.

**Comment by zxyao145** [comment]
@GlodenBoy 
OK. If you have any questions, you are welcome to reopen the issue for communication.
