### ISSUE TITLE
ReuseTabs Bug

### ISSUE THREAD

**Issue by SoaSoftNet** [ant-design-blazor/ant-design-blazor#2746]
![image](https://user-images.githubusercontent.com/30250585/192172928-1fdb5d81-d44b-4396-a2e0-2bb2725f8505.png)
![image](https://user-images.githubusercontent.com/30250585/192172937-8ed46b89-407a-43dd-a76f-af4d2696fd52.png)
Question 1: When opening a multi-tab page, right-click to close all tab pages, and an exception is reported.
![image](https://user-images.githubusercontent.com/30250585/192173025-ec392b9b-968c-4c50-a384-4feb1841e04c.png)
![image](https://user-images.githubusercontent.com/30250585/192173043-f115c935-6033-40ba-aa08-04e571119756.png)
Question 2: In the opened multi-tab page, right-click on one of them and close all of them, then close the other tabs except the current one, and then close the current tab, and an exception is reported.
![image](https://user-images.githubusercontent.com/30250585/192173341-19c5ecb7-e468-4bbb-914d-34985d7d95b3.png)
Question 3: Click the close button directly and report an exception.

**Comment by ElderJames** [comment]
Have been fixed in #2738 , please wait for the 0.12.5 release.
