### ISSUE TITLE
is rtl supported?

### ISSUE THREAD

**Issue by araxis** [ant-design-blazor/ant-design-blazor#275]

**Comment by ElderJames** [comment]
Thank you for contacting us @araxis .
Not yet, we are looking for contributors.

**Comment by araxis** [comment]
but antDesign already support it?
what's the problem?

**Comment by ElderJames** [comment]
we already has the styles from ant design, but we need to add this feature to our blazor components and test them.

**Comment by araxis** [comment]
this feature will be added soon?

**Comment by ElderJames** [comment]
As soon as possible. The main reason is our lack of experience.

**Comment by mhjabreel** [comment]
Hi,

I will help in developing the RTL version.

**Comment by ElderJames** [comment]
That's great @mhjabreel !
Just free feel to create a PR, and discuss in ours discord server.

**Comment by ElderJames** [comment]
Hello @mhjabreel , are you still working on this task?

**Comment by ElderJames** [comment]
RTL will be supported in this month.

**Comment by ElderJames** [comment]
Hi @araxis @mhjabreel We have been add RTL support. It would be published with the 0.8.0 next month.
For now, please pull the `feature` branch and test it if you have time.

**Comment by araxis** [comment]
Thanks a lot.
