### ISSUE TITLE
Input: is this a bug?

### ISSUE THREAD

**Issue by Magehernan** [ant-design-blazor/ant-design-blazor#2763]
Hi, i am having a problem with the input component, it not clear the validation errors.
when you change the value enters on KeyUp event and then get to this code

https://github.com/ant-design-blazor/ant-design-blazor/blob/726f10aa35e16a7f65c0d6c2d66d519e6571ad7b/components/input/Input.cs#L479-L489

it sets de CurrentValue but it do it before called OnChangeAsync

https://github.com/ant-design-blazor/ant-design-blazor/blob/726f10aa35e16a7f65c0d6c2d66d519e6571ad7b/components/input/Input.cs#L338-L348

Because that CurrentValueAsString has the new value but the validation wasn't updated and the error still there.
I add a line on 483 the set CurrentValueAsString too and then i have the correct flow on error.

So i am not sure if the correct way to solve this is by adding the change here or maybe is on other place.

best regards

**Comment by ElderJames** [comment]
Hi @Magehernan , I'm working on this part of the code. Could you please provide a reproducible demo for me to test?

**Comment by Magehernan** [comment]
Hi @ElderJames i am sick, i will make a example when i fill better, maybe tomorrow or friday.

**Comment by ElderJames** [comment]
Sorry, get well soon!

**Comment by Magehernan** [comment]
Hi @ElderJames i leave you a minimal code, paste it on any page and when you input a invalid number it will show it on the field, and when you put a valid number again y will stay in invalid state, when i look at it i found that the setter of CurrentValueAsString is generating the errors for the form and because it is called after the value change it is not excecuted and the erros stays. Hope it helps.

```csharp
<Form Model=model>
	<FormItem Label="Number">
		<Input @bind-Value="context.Number" />
	</FormItem>
</Form>

@code {
	class Model
	{
		public decimal Number{ get; set; }

	}

	private Model model = new();
}
```

**Comment by ElderJames** [comment]
Sorry, I have no idea. What is the error means?

![image](https://user-images.githubusercontent.com/7550366/198821295-00bfd675-3874-475b-a455-bac66a82056d.png)

**Comment by Magehernan** [comment]
ohh sorry i use my project and the error is for validation error, so in my case i type a invalid number and it change to red and appear the invalid text error and when i update de value for a valid number it continue showing error. 
I run it again on the docs page and you need click outside of the input and the error appear, it not change when you type only when you click outside.
And the only way i get to remove the error and restart is delete al content in the input an click outside then it put 0 and reset de value.
![Captura de pantalla 2022-10-29 143156](https://user-images.githubusercontent.com/28603584/198845462-f2ad1f8d-db02-4ad2-ba5b-939ddf51e755.png)
![Captura de pantalla 2022-10-29 143217](https://user-images.githubusercontent.com/28603584/198845464-20d993b9-9fc7-4741-9cb7-2b24984ba3da.png)

**Comment by ElderJames** [comment]
OK，I git It. I will take a look.
