### ISSUE TITLE
Input with Prefix + Icon not setting width correctly

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#2765]
`<Prefix><Icon Type = "user"></Icon></Prefix>`:

![image](https://user-images.githubusercontent.com/21806535/193708243-51e2efa0-99b1-4c24-9268-be6247f03b33.png)

`<AddOnBefore><Icon Type = "user"></Icon></AddOnBefore>`:

![image](https://user-images.githubusercontent.com/21806535/193708261-1c023153-5da0-4587-83bf-efb4d9d1ea1e.png)

**Comment by ElderJames** [comment]
Hello @michaelcsikos , it works now.

```
    <Input DefaultValue="@("readonly input")" ReadOnly WrapperStyle="width:30%;">
		<Prefix> ￥ </Prefix>
		<Suffix>RMB </Suffix>
    </Input>
    <Input @bind-Value="@txtValue" WrapperStyle="width:40%;">
        <Prefix><Icon Type="user"></Icon></Prefix>
    </Input>
    <Input DefaultValue="@("readonly input")" ReadOnly WrapperStyle="width:30%;">
        <Prefix> ￥ </Prefix>
        <Suffix>RMB </Suffix>
    </Input>


@code {
    private string txtValue { get; set; }
}
```

![image](https://user-images.githubusercontent.com/7550366/224466546-fc6b102a-1564-4019-bec2-ab7260f2d06f.png)
