### ISSUE TITLE
InputNumber option to align text right, set decimal places to display

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#2766]
Setting `Style = "align-text: right;"` works for `Input` but not for `InputNumber`. It's often a requirement to align numbers right, particularly when working with currency and a fixed number of decimal places, e.g. `$123.45`. It would be nice to have a property to easily set the alignment.

It would also be nice to have
```cs
[Parameter] public int DecimalPlaces { get; set; }
```
instead of setting `Formatter = "Format"` and declaring a method
```cs
private string Format(double value)
{
    return value.ToString("n2");
}
```

**Comment by YongQuan-dotnet** [comment]
Decimal place will be supported by parameter Precision.
Most of style is actually supported atm, text align is bit tricky though. 
Maybe consider to write some custom css if urgent?

**Comment by michaelcsikos** [comment]
Is `Precision` a new parameter that is planned to be added to `InputNumber`?

How would custom CSS work any differently if `Style = "align-text: right;"` is currently ignored?

**Comment by YongQuan-dotnet** [comment]
Yes @michaelcsikos Precision will be a new parameter applied to InputNumber.
It's not like all styles being ignored. It's just style text-align not taking effect to a Input inside a Div.

**Comment by ElderJames** [comment]
`Precision` added in #2774
