### ISSUE TITLE
ModalService option to hide Cancel button

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#2769]
This would be extremely useful. Sometimes you just want to display a read-only view with `OK` or `Close`.

Setting `Footer = null` is a workable compromise.

**Comment by zxyao145** [comment]
@michaelcsikos 
Hi, this is a good suggestion, but Modal is often used to allow users to make free choices in OK and Cancel. If you only want the user to select Ok or Cancel, you'd better use Confirm.

Or do you have any reason to use Modal this way?

**Comment by michaelcsikos** [comment]
The way to use `Confirm` is very different and requires quite a lot of lines to change. I also can't see how to set the size of `Confirm` and with the `ModalService` it doesn't have to be a blocking modal dialog so the user can click outside to close it.

**Comment by zxyao145** [comment]
> The way to use `Confirm` is very different and requires quite a lot of lines to change. I also can't see how to set the size of `Confirm` and with the `ModalService` it doesn't have to be a blocking modal dialog so the user can click outside to close it.

Yes, Confirm does not support setting size. And we will try to support Footer designs that only have OK or Cancel buttons, maybe this weekend will come to a conclusion.

**Comment by michaelcsikos** [comment]
That would be great. I had tried setting the `Cancel` text to `null` or `string.Empty` hoping that the button would be hidden in this case, but that also didn't work.

**Comment by zxyao145** [comment]
> That would be great. I had tried setting the `Cancel` text to `null` or `string.Empty` hoping that the button would be hidden in this case, but that also didn't work.

You need to customize a Footer, and you can refer to the next https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/modal/modalDialog/ModalFooter.razor, and try to remove the Cancel related code.

**Comment by zxyao145** [comment]
> That would be great. I had tried setting the `Cancel` text to `null` or `string.Empty` hoping that the button would be hidden in this case, but that also didn't work.

a sample:

ModalOkFooter.razor
``` blazor
@{
    var okProps = ModalProps.OkButtonProps ?? new ButtonProps();
    okProps.Type = ModalProps.OkType;
    okProps.Loading = ModalProps.ConfirmLoading;
}

<div>
    <Button OnClick="@HandleOk"
            Loading="@okProps.Loading"
            Type="@okProps.Type"
            Block="@okProps.Block"
            Ghost="@okProps.Ghost"
            Shape="@okProps.Shape"
            Size="@okProps.Size"
            Icon="@okProps.Icon"
            Disabled="@okProps.Disabled"
            Danger="@okProps.IsDanger">
        @{
            if (ModalProps.OkText.IsT0)
            {
                @(ModalProps.OkText.AsT0)
            }
            else
            {
                @(ModalProps.OkText.AsT1)
            }
        }
    </Button>
</div>
```

ModalOkFooter.razor.cs
```c#
public partial class ModalOkFooter
    {
        /// <summary>
        /// 
        /// </summary>
        [CascadingParameter]
        public DialogOptions ModalProps { get; set; }

        private async Task HandleOk(MouseEventArgs e)
        {
            var onOk = ModalProps.OnOk;
            if (onOk != null)
            {
                await onOk.Invoke(e);
            }
        }
    }
```

usage:
```blazor
<Modal Title="@title"
       Visible="@_visible"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel" 
       Footer="@okFooter">
    <p>Some contents...</p>
    <p>Some contents...</p>
    <p>Some contents...</p>
</Modal>
@code{
    RenderFragment okFooter = builder =>
        {
            builder.OpenComponent<ModalOkFooter>(0);
            builder.CloseComponent();
        };
}
```

and result:

![image](https://user-images.githubusercontent.com/24973084/194978499-75e32f9f-a9fa-42d3-8ef6-3a91868fa99b.png)
