### ISSUE TITLE
The close icon does not appear in the upper-right corner of the modal box, but it can actually be turned off

### ISSUE THREAD

**Issue by Jackywxp** [ant-design-blazor/ant-design-blazor#2772]
https://ant-design-blazor.gitee.io/zh-CN/components/modal
模态框右上角未显示关闭图标，但实际仍可以关闭。F12查看，可以看到关闭标签代码。
The close icon does not appear in the upper-right corner of the modal box, but it can actually be turned off 
![modal](https://user-images.githubusercontent.com/30179938/194710452-b508978a-5c78-4615-9ca0-f03872a34cf5.png)

**Comment by zxyao145** [comment]
@Jackywxp 
Hi, the close icon does not appear in the upper-right corner of the modal box is an expected behavior in Confirm dialog, and the event bug will be fixed later.
