### ISSUE TITLE
ModalService doesn't work at blazor server mode

### ISSUE THREAD

**Issue by dswfort** [ant-design-blazor/ant-design-blazor#2781]
### Describe the bug

Create a new `Blazor Server` project by Vusual Studio, copy the sample code from ant-design-blazor.gitee.io.

``` C#
@inject ModalService _modalService

<Space>
    <SpaceItem>
        <Button OnClick="HandleInfo">Info</Button>
    </SpaceItem>
    <SpaceItem>
        <Button OnClick="HandleSuccess">Success</Button>
    </SpaceItem>
    <SpaceItem>
        <Button OnClick="HandleError">Error</Button>
    </SpaceItem>
    <SpaceItem>
        <Button OnClick="HandleWarning">Warning</Button>
    </SpaceItem>
</Space>
@code {
    private void HandleInfo()
    {
        RenderFragment content =@<div>
                <p>some messages...some messages...</p>
                <p>some messages...some messages...</p>
            </div>;
        _modalService.Info(new ConfirmOptions()
        {
            Title = "This is a notification message",
            Content = content
        });
    }

    private void HandleSuccess()
    {
        _modalService.Success(new ConfirmOptions()
        {
            Content = "some messages...some messages..."
        });
    }

    private void HandleError()
    {
        _modalService.Error(new ConfirmOptions()
        {
            Title = "This is an error message",
            Content = "some messages...some messages..."
        });
    }

    private void HandleWarning()
    {
        _modalService.Warning(new ConfirmOptions()
        {
            Title = "This is a warning message",
            Content = "some messages...some messages..."
        });
    }
}
```
Click button and no response...

Is ModalService couldn't work at blazor-server?

### Further technical details
- AntDesign Nuget Package version **0.12.5**
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version is **VS2022**

**Comment by dswfort** [comment]
[BlazorApp1.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/9750484/BlazorApp1.zip)
Here is the demo~

**Comment by ElderJames** [comment]
Hi @dswfort , did you add the `<AntContainer />` component in App.razor ?

**Comment by zxyao145** [comment]
> Hi @dswfort , did you add the `<AntContainer />` component in App.razor ?
> 
> ![image](https://user-images.githubusercontent.com/7550366/194986049-498b2ac1-1fd9-4098-8a6d-9d0c272cf353.png)

Yes, this may be the reason why ModalService is not working. 

I download BlazorApp1.zip and it works fine when I add <AntContainer /> component. Please try adding <AntContainer /> component to App.razor


![image](https://user-images.githubusercontent.com/24973084/194988433-1193ff94-ff28-4285-9891-317283cbe1a6.png)

**Comment by dswfort** [comment]
It works！

Sorry for reading document carelessly...
