### ISSUE TITLE
RangePicker  Unable to close automatically

### ISSUE THREAD

**Issue by GlodenBoy** [ant-design-blazor/ant-design-blazor#2782]
Other issues caused by fixing this issue #2713  @Alexbits 

1. Clicking on other areas does not close automatically, but must be clicked OK, which will cause multiple date windows to appear ,This may not be a bug, but it's tricky to operate

2. If the date is not modified or cannot be closed after clicking OK, this is equivalent to forcing the user to modify the value

I tried the ant.design, which is free to click on other areas to close, save the value if the value changes, and restore the old value if there is no change.

You can follow this logic, I can compare the old and new values to execute the logic

gif 👇
https://recordit.co/dlKjq1E0CR

**Comment by Alexbits** [comment]
@GoldenBoy @ElderJames I'm not sure what's going on yet. I can reproduce this only when referencing the nuget package. It works fine in the latest master branch.

**Comment by GlodenBoy** [comment]
Because I've been using nuget packages, because it's more convenient, it looks like you need to pack it yourself?

**Comment by ElderJames** [comment]
@Alexbits I think I have fix this with #2783 . Please check.

**Comment by Alexbits** [comment]
> @Alexbits I think I have fix this with #2783 . Please check.

@ElderJames Looks fixed 👍

**Comment by ElderJames** [comment]
@GlodenBoy So this will be fixed in the next release.
