### ISSUE TITLE
JSDisconnectedException in Windows Event Viewer because of AntDesign.Table`1.DisposeAsync()

### ISSUE THREAD

**Issue by Kyojuro27** [ant-design-blazor/ant-design-blazor#2794]
Hello everyone,

I would like to point out an issue which occured when the SignalR connection is disconnected. In the company I'm working with, we are actually using Ant-Design-Blazor UI in several applications and it works well. But after a certain amount of time, we noticed in the Windows Event Viewer where our apps and IIS are installed that many Error and Warning are displayed.

Here the details of the Error: 

Category: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer
EventId: 100

Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.

Exception: 
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)
   at AntDesign.Table`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass69_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()

Our apps run in .NET 6.0, with Visual Studio 2022, in Blazor Server and 0.12.5 package version of Ant-Design-Blazor.

For information, it's not an issue you can see in your apps, even our logging error system doesn't see it. It occured when SignalR connection is disconnected. As we can see in the error details, it happened because of the method DisposeAsync() of the component Table. After a quick check, we can see that in this method we can foud in Table.razor.cs, there is a call to a jsInterop method. 

![image](https://user-images.githubusercontent.com/115569637/195296465-1aa4bfaf-c693-4475-bce7-b9c9fdc6ef55.png)

Since .NET 6.0, a JSDisconnectedException appeared when a jsInterop method is called in a Dispose function. I believe the recommended way is to wrap it in a try-catch and catch the JSDisconnectedException as shown below in order to stop windows event viewer to be plained with warning and error. Since event listeners stop existing after a page reload, there are no memory leaks.

I hope I described the issue properly.

**Comment by ElderJames** [comment]
Thank you for clearly describing the issue @Kyojuro27 , it really helped us! 
I see you have found a solution, can you submit a PR by the way?

**Comment by Riatekk** [comment]
I have the same problem, I'm waiting for the next release

**Comment by Kyojuro27** [comment]
Hi @ElderJames,

I made a pull request to adress the issue.

**Comment by ElderJames** [comment]
@Kyojuro27 Thank you very much,it help a lot and I will review it soon.
