### ISSUE TITLE
Select Icon is not displayed

### ISSUE THREAD

**Issue by coolmint123** [ant-design-blazor/ant-design-blazor#2806]
### Occurs when using AntDesign.ProLayout and Select

Select Icon is not displayed when unselected.
Display the item after selection.

### Location
Occurs in Select placed with RightContentRender of AntDesign.ProLayout.

### Technical details
- AntDesign.ProLayout 0.12.4
- VS2022 Version 17.2.6

**Comment by ElderJames** [comment]
Hello @coolmint123 , which icon do you mean?

**Comment by coolmint123** [comment]
Thank you for your comment.

Sorry for lack of explanation.
The icons placed on the left side of Select are not displayed.
I don't know if it's a setting method or a specification.

![select](https://user-images.githubusercontent.com/27341028/196066021-486b99fb-3949-4012-94dd-05d2381c44a6.png)

    <RightContentRender>
        <Space>
            <SpaceItem>
                <AntDesign.Select DataSource="@items" Style="min-width: 100px;"
                                  @bind-Value="id"
                                  LabelName="@nameof(item.name)"
                                  ValueName="@nameof(item.id)"
                                  TItem="item"
                                  TItemValue="int">
                </AntDesign.Select>
            </SpaceItem>
        </Space>
    </RightContentRender>

**Comment by ElderJames** [comment]
Hello @coolmint123 , we can't reproduce the issue.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/5a7ffc90-d593-4138-ba15-9dd582cb1733)
