### ISSUE TITLE
if call JSRuntime.InvokeVoidAsync("open", url,"_blank"); })) and close new tab then cannot press keyboard

### ISSUE THREAD

**Issue by yangpei1010110** [ant-design-blazor/ant-design-blazor#2807]
### Describe the bug

Cannot Press Keyboard

### Steps to reproduce (please include code)

`` 
@inject IJSRuntime JSRuntime
public async Task OnClick() {
   JSRuntime.InvokeVoidAsync("open", anyNewUrl);
}

``

### Exceptions (if any)

Not Display Any Exception

### Further technical details
- AntDesign Version 0.12.0
- dotnet --info
 .NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  3.1.423 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.304 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- IDE Rider 2022.2.3

**Comment by yangpei1010110** [comment]
I need to call a print website , URL is a Rest Api get method, like "http://host:port/PrintHtml/{Id}". website content is multiple <div style="page-break-after: always;"> in body, 
 js code is:
<script type='text/javascript'>
	 window.onload = () => window.print();
</script>

**Comment by yangpei1010110** [comment]
if I use JSRuntime to call this website, return origin website then cannot press any keyboard key.

**Comment by yangpei1010110** [comment]
return origin website need to open modal ready to print new website, but cannot press value to input component in modal.

**Comment by yangpei1010110** [comment]
`

<Modal Visible="@_visible"
       OnOk="@OkPrint"
       OnCancel="@(() => _visible = false)"
       ConfirmLoading="_loading">
    <Input TValue="string?" @bind-value="@OrderLineDto!.OrderType" ReadOnly>
        <Prefix>订单类型:</Prefix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@OrderLineDto!.DocNo" ReadOnly>
        <Prefix>订单号:</Prefix>
        <Suffix>行号:@OrderLineDto!.LineNo</Suffix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@OrderLineDto!.ItemCode" ReadOnly>
        <Prefix>晨翔料号:</Prefix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@InFactoryItemCode">
        <Prefix>厂内料号:</Prefix>
    </Input>
    <br/> <br/>
    <Text>最大可发数量:@(MaxSendQuantity.ToString("0.000")) @OrderLineDto?.UomName</Text>
    <Text>已发数量:@(SentQuantity.ToString("0.000")) @OrderLineDto?.UomName</Text>
    <br/> <br/>
    <Text>发货数量:</Text>
    <AntDesign.InputNumber TValue="decimal" @bind-value="@SendQuantity"/>
    <Text>@OrderLineDto?.UomName</Text>
    <br/> <br/>
    <Text>数量:</Text>
    <AntDesign.InputNumber TValue="decimal" @bind-value="@PerPacketQuantity"/>
    <Text>@OrderLineDto?.UomName</Text>
    @if (PerPacketQuantity > 0 && OrderLineDto?.TradeQuantity != null)
    {
        // 如果选择的数量大于0，且订单行的数量不为空
        <Text>; @((int)(OrderLineDto.TradeQuantity / PerPacketQuantity)) 个 @(PerPacketQuantity.ToString("0.000")) 包装</Text>
        @if (OrderLineDto.TradeQuantity % PerPacketQuantity > 0 && OrderLineDto?.TradeQuantity != null)
        {
            // 如果订单行的数量不能整除包装数量，且订单行的数量不为空
            <Text>与 1个 @((OrderLineDto.TradeQuantity % PerPacketQuantity).Value.ToString("0.000")) 包装</Text>
        }
    }
    <br/> <br/>
    <Text>毛重:</Text>
    <AntDesign.InputNumber TValue="decimal" @bind-value="@PerPacketWeight"/>
    <Text>Kg</Text>
    <br/> <br/>
    <DatePicker TValue="DateTime" @bind-value="@PrintTime"/>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@ActionUser">
        <Prefix>操作员:</Prefix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@QcUser">
        <Prefix>检验员:</Prefix>
    </Input>
</Modal>

@code{
    #region Modal

    // Modal
    bool _visible = false;
    OrderLineDto? OrderLineDto; // 订单信息
    string? InFactoryItemCode = string.Empty; // 内部物料编码
    decimal PerPacketQuantity; // 每包数量
    decimal PerPacketWeight; // 每包重量
    DateTime PrintTime = DateTime.Now; // 打印时间
    string? ActionUser = string.Empty; // 操作人
    string? QcUser = string.Empty; // 质检人
    decimal SentQuantity = 0; // 已发数量
    decimal MaxSendQuantity = 0; // 最大可发数量
    decimal SendQuantity = 0; // 发货数量

    #endregion
}
`

**Comment by yangpei1010110** [comment]
```
<Modal Visible="@_visible"
       OnOk="@OkPrint"
       OnCancel="@(() => _visible = false)"
       ConfirmLoading="_loading">
    <Input TValue="string?" @bind-value="@OrderLineDto!.OrderType" ReadOnly>
        <Prefix>订单类型:</Prefix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@OrderLineDto!.DocNo" ReadOnly>
        <Prefix>订单号:</Prefix>
        <Suffix>行号:@OrderLineDto!.LineNo</Suffix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@OrderLineDto!.ItemCode" ReadOnly>
        <Prefix>晨翔料号:</Prefix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@InFactoryItemCode">
        <Prefix>厂内料号:</Prefix>
    </Input>
    <br/> <br/>
    <Text>最大可发数量:@(MaxSendQuantity.ToString("0.000")) @OrderLineDto?.UomName</Text>
    <Text>已发数量:@(SentQuantity.ToString("0.000")) @OrderLineDto?.UomName</Text>
    <br/> <br/>
    <Text>发货数量:</Text>
    <AntDesign.InputNumber TValue="decimal" @bind-value="@SendQuantity"/>
    <Text>@OrderLineDto?.UomName</Text>
    <br/> <br/>
    <Text>数量:</Text>
    <AntDesign.InputNumber TValue="decimal" @bind-value="@PerPacketQuantity"/>
    <Text>@OrderLineDto?.UomName</Text>
    @if (PerPacketQuantity > 0 && OrderLineDto?.TradeQuantity != null)
    {
        // 如果选择的数量大于0，且订单行的数量不为空
        <Text>; @((int)(OrderLineDto.TradeQuantity / PerPacketQuantity)) 个 @(PerPacketQuantity.ToString("0.000")) 包装</Text>
        @if (OrderLineDto.TradeQuantity % PerPacketQuantity > 0 && OrderLineDto?.TradeQuantity != null)
        {
            // 如果订单行的数量不能整除包装数量，且订单行的数量不为空
            <Text>与 1个 @((OrderLineDto.TradeQuantity % PerPacketQuantity).Value.ToString("0.000")) 包装</Text>
        }
    }
    <br/> <br/>
    <Text>毛重:</Text>
    <AntDesign.InputNumber TValue="decimal" @bind-value="@PerPacketWeight"/>
    <Text>Kg</Text>
    <br/> <br/>
    <DatePicker TValue="DateTime" @bind-value="@PrintTime"/>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@ActionUser">
        <Prefix>操作员:</Prefix>
    </Input>
    <br/> <br/>
    <Input TValue="string?" @bind-value="@QcUser">
        <Prefix>检验员:</Prefix>
    </Input>
</Modal>
@code{
    #region Modal

    // Modal
    bool _visible = false;
    OrderLineDto? OrderLineDto; // 订单信息
    string? InFactoryItemCode = string.Empty; // 内部物料编码
    decimal PerPacketQuantity; // 每包数量
    decimal PerPacketWeight; // 每包重量
    DateTime PrintTime = DateTime.Now; // 打印时间
    string? ActionUser = string.Empty; // 操作人
    string? QcUser = string.Empty; // 质检人
    decimal SentQuantity = 0; // 已发数量
    decimal MaxSendQuantity = 0; // 最大可发数量
    decimal SendQuantity = 0; // 发货数量

    #endregion
}
```

**Comment by yangpei1010110** [comment]
I fix it just call 
```
JS.InvokeVoidAsync("open",newUrl,"_blank","noreferrer");
```
then origin page will be not freeze

**Comment by ElderJames** [comment]
Pleaes add my wechat JamesYeungMVP, and jon our community
