### ISSUE TITLE
TreeSelect strange behaviour when selecting an item on the documentation page

### ISSUE THREAD

**Issue by oladroid** [ant-design-blazor/ant-design-blazor#2820]
I need to use TreeSelect (https://antblazor.com/en-US/components/treeselect) in my project.
Code that I used:
`<TreeSelect 
  AllowClear="true"
  TreeDefaultExpandAll="true"
  TItem="TreeItem"
  OnSelectedItemChanged="PermissionFilterOnSelectedItemChangedAsync"
  Placeholder="Please select"
  ChildrenExpression="x => x.DataItem.Children"
  TitleExpression="x => x.DataItem.Name"
  KeyExpression="x => x.DataItem.Id"
  IsLeafExpression="x => x.DataItem.Children.Count == 0"
  DataSource="@_permissionList"
  Style="width: 300px;"></TreeSelect>`
  But during testing found a strange behaviour when selecting items in the rendered element. So I opened the documentation 
  
![image](https://user-images.githubusercontent.com/8520591/196694937-d147718f-b1c7-488b-8935-b1811558e206.png)

  And here is the same :
  
![tree-select-blazor](https://user-images.githubusercontent.com/8520591/196688572-50886a3d-c15e-4010-9ae1-42c90c77a6b2.gif)

Steps to reproduce:

1. open TreeSelect
2. select **leaf1**
3. open TreeSelect -> **leaf3** is displayed as selected
4. open TreeSelect -> **leaf1** is displayed as selected
5. open TreeSelect -> **leaf3** is displayed as selected
6. ........

**Comment by ElderJames** [comment]
Hello @oladroid , please check the latest version if this issue have been fixed.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/f2820746-5eff-4a3f-80dc-bbc69dd3c5ed)

**Comment by oladroid** [comment]
@ElderJames 
Verified, works perfectly 
Thanks!
