### ISSUE TITLE
Need Cascader Disabled option

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#2825]
It's currently not possible to disable the `Cascader` component like we can with other components such as `Select`.

**Comment by ElderJames** [comment]
Hi @michaelcsikos , do you mean disable the whole component?

**Comment by michaelcsikos** [comment]
@ElderJames Yes, the whole component.

**Comment by wuxinheng** [comment]
@ElderJames @michaelcsikos  Let me try to solve this problem.
