### ISSUE TITLE
Table component Even if a row is marked disabled, it can still be selected by the selector in the header row

### ISSUE THREAD

**Issue by zizaixiuxing** [ant-design-blazor/ant-design-blazor#2827]
Even if a row is marked disabled, it can still be selected by the selector for the header row

### Describe the bug
Table component
Even if a row is marked disabled, it can still be selected by the selector in the header row
like this
![Uploading wt1.png…]()

### Further technical details
- AntDesign Nuget Package 0.12.6

**Comment by ElderJames** [comment]
Hello @zizaixiuxing , this issue have been fixed.
