### ISSUE TITLE
localization not show in MAUI prject

### ISSUE THREAD

**Issue by charleypeng** [ant-design-blazor/ant-design-blazor#2828]
I merged my project(webassembly) to maui, the localization of ConfirmService  did not work, the strings are blank.

**Comment by charleypeng** [comment]
ok  i found why

**Comment by ElderJames** [comment]
Hello @charleypeng , would you please tell us what's the problem?

**Comment by charleypeng** [comment]
> Hello @charleypeng , would you please tell us what's the problem?

It's my own fault to load the resource file in a wrong path

**Comment by ElderJames** [comment]
Please help us to create a MAUI demo with AntDesign

**Comment by charleypeng** [comment]
> Please help us to create a MAUI demo with AntDesign
ok   i did one and i will upload later
