### ISSUE TITLE
About  InputNumber  Bug

### ISSUE THREAD

**Issue by SoaSoftNet** [ant-design-blazor/ant-design-blazor#2829]
Operating steps: 1. Select the drop-down list box to load InputNumber data

2. Clear the drop-down list to select a value, and change the inputnumber value

3. Reselect the value of the drop-down list box

4. The inputnumber value automatically increases. Load once. Continuous automatic adding.

**Comment by SoaSoftNet** [comment]
https://github.com/SoaSoftNet/AntDesign-Blazor-Input  demo

**Comment by ElderJames** [comment]
After testing, I think it's Message, not Select. Please confirm it.
