### ISSUE TITLE
Menu.Sider Collapsed and OnCollapse not working

### ISSUE THREAD

**Issue by NightSpark75** [ant-design-blazor/ant-design-blazor#283]
<Sider Collapsible Collapsed=@collapsed OnCollapse=@onCollapse>
    ...
</Sider>

I found from the source code that there are two attributes:
1. public event Action<bool> OnCollapsed;
2. [Parameter] public EventCallback<bool> OnCollapse { get; set; }

however, OnCollapse was never triggered

**Comment by ElderJames** [comment]
Thank you for contacting us @NightSpark75 .
We have fixed it and try again please.
