### ISSUE TITLE
Suggestion: Change how site docs are generated

### ISSUE THREAD

**Issue by kooliokey** [ant-design-blazor/ant-design-blazor#2832]
### Is your feature request related to a problem? Please describe.
I've noticed there are many instances of documentation missing for public parameters in code and a difference in the documentation on parameters that are documented in code and the site. 

### Describe the solution you'd like
I'm wondering if we should make the site's documentation generated from reading the documentation comments on the code itself so they always match? I've never done it before, but I know tools generate whole sites with the comments so it should be possible to read them and use them how we want.

### Additional context
N/A

# Automation Progress
## Documentation Page Migrated & Checked - English
- [x] Overview
- [x] Button
- [x] Icon
- [x] Typography
- [x] Divider
- [x] Grid
- [x] Layout
- [x] Space
- [x] Affix
- [x] Breadcrumb
- [x] Dropdown
- [x] Menu
- [x] PageHeader
- [x] Pagination
- [x] Steps
- [x] AutoComplete - Base class properties not showing docs
- [x] Cascader - Base class properties not showing docs
- [x] Checkbox - not all properties are documenting. Generic is causing problems.
- [x] DatePicker
- [x] Form
- [x] Input - Docs from generic base class not showing
- [x] InputNumber
- [x] Mentions
- [x] Radio
- [x] Rate
- [x] Select
- [x] Slider
- [x] Switch
- [x] TimePicker
- [x] Transfer
- [x] TreeSelect
- [x] Upload
- [x] Avatar
- [x] Badge
- [x] Calendar
- [x] Card
- [x] Carousel
- [x] Collapse
- [x] Comment
- [x] Descriptions
- [x] Empty
- [x] Image
- [x] List
- [x] Popover
- [x] Segmented
- [x] Statistic - not all properties getting documentation. Prob affected by something in the "issues found" below
- [x] Table - missing a lot of property summaries
- [x] Tabs
- [x] Tag
- [x] Timeline
- [x] Tooltip
- [x] Tree
- [x] Alert
- [x] Drawer
- [x] Message - done except methods docs
- [x] Modal
- [x] Notification
- [x] Popconfirm
- [x] Progress
- [x] Result
- [x] Skeleton
- [x] Spin
- [x] Anchor
- [x] BackTop

## Small Things Found On The Way
- [x] Fix display of OneOf - missing types...just displays OneOf
- [x] Adjust style of methods docs 
- [x] Getting XML documentation of methods is not being easy - the format of generics is different than just doing `.FullName`
- [x] `<inheritdoc />` not inheriting

## Documentation Translated
This will take more investigation work to implement and we may want to split it into a separate effort. We could implement multiple languages for now by linking a file with the translation in the XML with a custom element.
- [X] Decide on way to do it
- [X] Decide how to allow overriding translation if automated is bad
- [x] Implement automated translation w/ way to override 

## Possible Improvements
Some things that may be nice to implement in the future
- Remove inherited parameters from documentation and instead show a message like "Inherits API of SuchAndSuch". It would save space.
- [x] Link `<see cref="AntDesign.RenderMode"/>` to github for file or a page on the site for the file

**Comment by ElderJames** [comment]
Yes, it would be better if we could implement this way, and it would be better if it could be translated into English and Chinese.

**Comment by kooliokey** [comment]
I can look into how it can be done. I'm not too familiar with how the docs are currently built though so it might take a while :D

**Comment by ElderJames** [comment]
Currently just using `AntDesign.Docs.Build.CLI` to render the markdown files and copy the razor code into json.

**Comment by kooliokey** [comment]
If anyone wants to see my idea so far on this, I have a branch going in my fork. I ran into a snag on generating the "Overview" page in the components section though because currently it is generated the same a code components but there is no code to use for the documentation.

https://github.com/kooliokey/ant-design-blazor/tree/feature/documentation-automation

**Comment by ElderJames** [comment]
Hi @kooliokey , I've taken a look at your branch, and I think it's great.

But I don't think the component introduction is very elegant, and too much of it will lead to html. This part of the advice is again taken from the markdown file, and only properties and methods are generated through comments. In addition, you need to consider how Chinese is generated. Use the open translation api or something else?

BTW, this wold fixed #1495 too.

**Comment by ElderJames** [comment]
Also would fixed #2421

**Comment by kooliokey** [comment]
@ElderJames Glad you like where it is going! I was trying to get all the documentation in code so you get the benefit of it showing in VS Intellisense as well as the site. I haven't dug into ways to format it much yet, but if it sticks to paragraphs and lists that can all be done with XML elements in the summary. We could move back to using Markdown for the descriptions if wanted, but we loose the benefit of it all being in one spot.

For Chinese language...I was thinking of using some sort of API in the build to translate it. I haven't looked much into that piece yet though.

**Comment by ElderJames** [comment]
Hey @kooliokey , how is it going on?

**Comment by kooliokey** [comment]
@ElderJames I haven't had much time recently to work on it and I have to send my laptop in for repair so I won't be able to do more until I get that back. I haven't dug much into the translation part yet. Still working on getting the documentation to match the existing as close as I can. I have it combining components onto a single page (like Form and FormItem) but have to make it do it for all of them. There are also some pages that don't have a matching component class that I need to look at (Like the Typography page)

**Comment by ElderJames** [comment]
Ok, that's fine. Let's see how we could continue this work.

**Comment by kooliokey** [comment]
I was thinking of adding a custom XML element for use in the documentation comments for linking a markdown file for the site since you mentioned wanting to keep that way available? The Microsoft documentation says it is acceptable to make your own. I figured something like `<documentation file="/path/to/file.md" />`

**Comment by kooliokey** [comment]
Update: I've received my repaired laptop back so I am able to continue looking at this again. I plan to start more tonight.

**Comment by ElderJames** [comment]
good news 👍 welcome back!

**Comment by kooliokey** [comment]
Update: All English documentation is complete and generating. Will be looking at the translation soon.
