### ISSUE TITLE
Table: Column header alignment mess-up with filters

### ISSUE THREAD

**Issue by Abin-Liu** [ant-design-blazor/ant-design-blazor#2836]
### Describe the bug

Column header alignment not working if the **Filterable** property is set to true, the header text will be aligned to left side regardless of its Align property.

### Steps to reproduce (please include code)
**BEFORE**: column header is aligned to center, as expected

`<Column @bind-Field="@context.UpdateBy" Align="@ColumnAlign.Center" />`

![before](https://user-images.githubusercontent.com/32606124/197723960-da2c26a7-c9fe-49e0-8100-689c1b5bfa17.png)

**AFTER**: with **Filterable** is true, column header is forced to left, the Align property has no effect any more

`<Column @bind-Field="@context.UpdateBy" Align="@ColumnAlign.Center" Filterable />`

![after](https://user-images.githubusercontent.com/32606124/197724419-a177c70b-5f46-42d8-b7e6-3adcfd1b86fc.png)

I would suggest putting the filter icon on far-right, and let the column header stay where they should be.

### Further technical details
- AntDesign Nuget Package version: 0.12.6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS2022 Community

**Comment by Abin-Liu** [comment]
I just checked in 0.13.3, the same problem remains.

**Comment by ElderJames** [comment]
Sorry, I can't reproduce this problem, please give a complete demo again.

**Comment by Abin-Liu** [comment]
I've prepared a simple one-page demo project (VS 2022, Blazor WASM, .NET 6.0) to reproduce the issue, how can I send it to you?

**Comment by ElderJames** [comment]
Just upload here or create a repo and link here.Thank you!

**Comment by Abin-Liu** [comment]
Hi ElderJames, attached demo project shows that, once "Filterable" is set to true, the column header text will be aligned to left even if I set Align="@ColumnAlign.Center".

[BlazorApp1.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/10441017/BlazorApp1.zip)

**Comment by ElderJames** [comment]
Thank you @Abin-Liu , I have fixed the issue.

**Comment by Abin-Liu** [comment]
Thank you ElderJames.
