### ISSUE TITLE
Found two bugs with Datepick when typing

### ISSUE THREAD

**Issue by PCichigo** [ant-design-blazor/ant-design-blazor#2841]
### Describe the bug

Hi, there : )

I just found two bugs with Datepick from recent version, I will separate these two bugs as case A and case B below.

=== CASE A

This bug only occurred typing date in Datepick input. 
For example, start by typing "2022-10-27" in a simple Datepick input box, and then click some where else or using Tab button to make it lose focus (so user can fill the other input next), the value will reverse back to the value before changing. 
This seem to occurred when typing, I found no problem when clicking date on calendar, or using Enter button after typing.

![datebug20221027a](https://user-images.githubusercontent.com/102783349/198283107-7191616c-b03f-4f32-8986-ae3f2caefa57.jpg)

This also happen no matter what the start value of the Datepick is. As you can see from the image below.

![datebug20221027b](https://user-images.githubusercontent.com/102783349/198283880-f5194f82-f006-4919-b0ae-3cb85dca6592.jpg)

=== CASE B

Ok, this one is kinda weird to find. 
First, we start with any value in a simple Datepick input box (or null), then changing the value by typing in the input box, so that the graphic of calendar is changing (this can be done changing year or month, bug will not occurred if changing day only). 
After finish the typing, click on any date in the calendar (including the same day you type), the result value will be wrong (it take the day from the location where before the calendar graphic change).

This seem to only occurred if the calendar graphic change by typing.

![datebug20221027c](https://user-images.githubusercontent.com/102783349/198283285-7ded2a19-a539-49cd-8a96-0c92e3095f0f.jpg)

### Steps to reproduce (please include code)

Both case are using the same basic code from DatePicker tutorial as follow:

`<DatePicker TValue="DateTime?" Picker="@DatePickerType.Date" />`

Step to reproduce, can be found in description and images above.

### Exceptions (if any)

No error exception.

### Further technical details
- AntDesign version 0.12.6
- Blazor Server, C# .net 6
- VS 2022 Community, version 17.3.3

**Comment by ElderJames** [comment]
Thanks for contacting us @PCichigo , If @Alexbits has time, maybe he can help to look into the issue.

**Comment by Alexbits** [comment]
Hey @PCichigo. Thank you for submitting the issue.

Case A is by design. Please check the original [ant.design](https://ant.design/components/date-picker/) behavior as a reference. You should press Enter key to confirm your input.

Case B looks like a bug. I will check it.

**Comment by PCichigo** [comment]
> Hey @PCichigo. Thank you for submitting the issue.
> 
> Case A is by design. Please check the original [ant.design](https://ant.design/components/date-picker/) behavior as a reference. You should press Enter key to confirm your input.
> 
> Case B looks like a bug. I will check it.

Aw, kinda sad for Case A. The behavior in Case A just happen on recently version, it's working fine with Tab and losing focus on version 0.12.4. Guess the user have to adjust their behavior then.

But anyway, thank for your great works!

**Comment by kooliokey** [comment]
@Alexbits I've noticed the same thing with the tab not committing the typed date and referred to Ant Design's demos and it works there by hitting tab. Clicking out does not commit though so that part is the same. Can tab be added?

**Comment by Alexbits** [comment]
> @Alexbits I've noticed the same thing with the tab not committing the typed date and referred to Ant Design's demos and it works there by hitting tab. Clicking out does not commit though so that part is the same. Can tab be added?

Hi @kooliokey. The Tab key support can be added. Thanks for noticing it.
