### ISSUE TITLE
Can not using example Table

### ISSUE THREAD

**Issue by vietanhbui** [ant-design-blazor/ant-design-blazor#2853]
I create new empty project and Import Ant Design Blazor into project.
Try example table and got error: 
![image](https://user-images.githubusercontent.com/43196820/199657706-5c9f9822-a426-4f86-be15-94dbed116716.png)
But try another example, has not error:
![image](https://user-images.githubusercontent.com/43196820/199657853-1e72aba7-18ee-4d87-81fd-aa33b5d53386.png)

**Comment by vietanhbui** [comment]
Blazor properties: 
![image](https://user-images.githubusercontent.com/43196820/199657923-93471e10-4ed2-4dc6-864e-7d7949a331cc.png)

**Comment by ElderJames** [comment]
Hi @vietanhbui ,  our document site is .NET 6

.NET 6
`<ProperyColumn Property="c=>c.Name" />` 

.NET 5:
`<ProperyColumn TItem="Data" Property="c=>c.Name" />`

**Comment by vietanhbui** [comment]
Has document site for .NET 5? Tks

**Comment by ElderJames** [comment]
Sorry not, but most of our features are compatible .NET Core 3.1 ~ 6.0 , otherwise we would have made it clear which features are only available on .NET5 or  .NET6

**Comment by ElderJames** [comment]
Hey @vietanhbui , have you solve this issue?
