### ISSUE TITLE
OnCompleted of upload with InternalServerError couldn't get reponse body

### ISSUE THREAD

**Issue by yosheng** [ant-design-blazor/ant-design-blazor#2857]
### Describe the bug
unable to get error response from Status500InternalServerError 

### Steps to reproduce (please include code)
here is my code

In controller
```cs
        [HttpPost]
        [Route("upload/excel")]
        public IActionResult UploadExcelLogic(IFormFile file)
        {
            return Problem(statusCode: StatusCodes.Status500InternalServerError, detail:"Test error detail!");
        }
```

my razor page
```
<Upload Action="api/Test/upload/excel"
        Name="file"
        Multiple="false"
        ShowUploadList="false"
        OnCompleted="OnCompleted">
    <Button Icon="upload">
        <span>上传</span>
    </Button>
</Upload>

@code {
    
    void OnCompleted(UploadInfo fileinfo)
    {
        var result = fileinfo.File.GetResponse<dynamic>();  // only get {"status": 500}
    }
}
```
![image](https://user-images.githubusercontent.com/15070744/199899043-12f1008c-669c-401f-bf92-106665db5f89.png)

my reponse like the picture
![image](https://user-images.githubusercontent.com/15070744/199899185-9749131e-8cbd-4490-8334-99d1bff6337a.png)

Expect get my reponse

### Further technical details
- AntDesign Nuget Package version 0.12.6

**Comment by ElderJames** [comment]
Thanks for report that @yosheng , maybe we need to add OnError event for fail request. Are you interested?

**Comment by yosheng** [comment]
@ElderJames thanks for your reply, I'm razor newbiee. I don't know how to add add OnError event for fail request. I try to read the code, but still couldn't find the problem. 😥 I couldn't find where is the successful request get raw reponse. Can you tell me?

**Comment by ElderJames** [comment]
I think the key issue is at  [this line](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/core/JsInterop/modules/components/uploadHelper.ts#L75). Please help us to fix it like this.

And help us to test it.

```diff
- instance.invokeMethodAsync(errorMethod, fileId, `{"status": ${req.status}}`);
+ instance.invokeMethodAsync(errorMethod, fileId, req.responseText);
```
