### ISSUE TITLE
Segmented component binding error

### ISSUE THREAD

**Issue by Kistelekig98** [ant-design-blazor/ant-design-blazor#2868]
### Describe the bug

The initial value is not correct when binding a Segmented\<bool\> component.

### Steps to reproduce (please include code)
Here is my simple [Github repo](https://github.com/Kistelekig98/BlazorApp1)
You can launch the app and click "Segmented test" menu item.

So I have a Person class:
```
public class Person
{
  public bool IsFunny { get; set; } = false;
  public bool IsTall { get; set; } = false;
}
```
SegmentedTest.razor.cs:
```
public partial class SegmentedTest
{
  public Person Person { get; set; } = new();

  protected override void OnInitialized()
  {
    Person.IsFunny = true;
    Person.IsTall = true;
  }
}
```
SegmentedTest.razor:
```
IsFunny:
<Segmented @bind-Value="Person.IsFunny">
  <SegmentedItem Value="false" Label="False" />
  <SegmentedItem Value="true" Label="True" />
</Segmented>
<br />
<br />
IsTall:
<Segmented @bind-Value="Person.IsTall">
  <SegmentedItem Value="true" Label="True" />
  <SegmentedItem Value="false" Label="False" />
</Segmented>
```

When I open the SegmentedTest page, I expect both Segmented components to be True, because I set them in the OnInitialized method. But they are False.
(I can call StateHasChanged() but it does not help)
![image](https://user-images.githubusercontent.com/11194127/200551390-502cfd0d-1bf4-49b3-826f-ff158411c8f7.png)

### Further technical details
- AntDesign Nuget Package version: 0.12.7
- Visual Studio Community 2022 17.3.2
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):

>  Version:   6.0.400
>  Commit:    7771abd614
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19044
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.400\
> 
> global.json file:
>   Not found
> 
> Host:
>   Version:      6.0.8
>   Architecture: x64
>   Commit:       55fb7ef977
> 
> .NET SDKs installed:
>   6.0.400 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ElderJames** [comment]
Thanks for contacting us @Kistelekig98 , we will fix this in next release. 

Please try following code for workaround (to specific `TValue="bool?"` ):

```razor
<Segmented TValue="bool?" @bind-Value="Person.IsFunny">
    <SegmentedItem TValue="bool?" Value="false" Label="False" />
    <SegmentedItem TValue="bool?" Value="true" Label="True" />
</Segmented>
```

**Comment by Kistelekig98** [comment]
> Thanks for contacting us @Kistelekig98 , we will fix this in next release.
> 
> Please try following code for workaround (to specific `TValue="bool?"` ):
> 
> ```
> <Segmented TValue="bool?" @bind-Value="Person.IsFunny">
>     <SegmentedItem TValue="bool?" Value="false" Label="False" />
>     <SegmentedItem TValue="bool?" Value="true" Label="True" />
> </Segmented>
> ```

Yes it solves but I must change the Person's properties to "bool?" type as well.

**Comment by ElderJames** [comment]
Yes, I have created a PR to fix this.
