### ISSUE TITLE
Menu Title

### ISSUE THREAD

**Issue by casmatos** [ant-design-blazor/ant-design-blazor#287]
Hello i have try to use inline title in Menu

`<SubMenu Key="menu1">
           <Title>
                <span>Title HTML</span>
           </Title>
            <MenuItem Key="submenu1">
                Option Submenu 1
            </MenuItem>
 </SubMenu>`

He show empty on Title, Only work if i attribute on <SubMenu Title="@("Title HTML")">

I need use a foreach.

**Comment by ElderJames** [comment]
Thank you for contacting us.
You need to first define RenderFargment variables link this:
```
<Menu>

@foreach(var item in subMenus)
{
@{
  RenderFragment title =
        @<span>
            <Icon Type="item.Icon" />
            <span>item.Title</span>
        </span>;
}

 <SubMenu Title="title">
            <MenuItem Key="1">Option 1</MenuItem>
            <MenuItem Key="2">Option 2</MenuItem>
            <MenuItem Key="3">Option 3</MenuItem>
            <MenuItem Key="4">Option 4</MenuItem>
        </SubMenu>
}
</Menu>
```

**Comment by casmatos** [comment]
Hello.
I see in your examples. But i need use Title dynamic inside of foreach.

**Comment by casmatos** [comment]
Thanks
