### ISSUE TITLE
Default value error after TreeSelect component selection

### ISSUE THREAD

**Issue by MiJiuYang** [ant-design-blazor/ant-design-blazor#2878]

**Comment by ElderJames** [comment]
Thanks for contacting us @MiJiuYang , please provide a demo for explain this issue.

**Comment by MiJiuYang** [comment]
https://ant-design-blazor.gitee.io/zh-CN/components/treeselect

**Comment by MiJiuYang** [comment]
In the official example [basic/基本]，Change the default selection of "leaf3" to "leaf1". Click the drop-down box to display "leaf3" again

**Comment by MiJiuYang** [comment]
![image](https://user-images.githubusercontent.com/24215871/202330198-a5eb1e87-1df7-4743-8274-6a5af5b05582.png)

**Comment by MiJiuYang** [comment]
@ElderJames
