### ISSUE TITLE
About Modal Bug

### ISSUE THREAD

**Issue by SoaSoftNet** [ant-design-blazor/ant-design-blazor#2881]
![8fc58454a10da0d3fe1325b6abaeda2](https://user-images.githubusercontent.com/30250585/201871411-06e9dd3c-afe7-46ea-a2b6-30ab6b58cc2f.png)
When Modal is put  ```</PageContainer>```  behind, an exception is reported. Put to  ```</ChildContent>```
```</PageContainer>```  Inside, normal

**Comment by zxyao145** [comment]
@SoaSoftNet 
Hi, where is `</PageContainer>` is defined?

**Comment by SoaSoftNet** [comment]
![image](https://user-images.githubusercontent.com/30250585/202086614-42eeaf1d-3c54-4a90-be80-1720f2b72565.png)

**Comment by SoaSoftNet** [comment]
![image](https://user-images.githubusercontent.com/30250585/202089064-98c24570-8187-45c9-9b9c-0cc0d9f59b57.png)

**Comment by zxyao145** [comment]
@SoaSoftNet Is `</PageContainer>` a component defined by yourself? This component does not exist in ant-design-blazor

**Comment by SoaSoftNet** [comment]
把modal 放到 最外层。使用没有问题，切换页面时报错。可以按这个逻辑测试下

**Comment by ElderJames** [comment]
@zxyao145 It is in pro layout.

**Comment by zxyao145** [comment]
@SoaSoftNet 

Sorry, the problem cannot be reproduced. Here is my test code, and can you provide a demo?
抱歉，问题不能复现。下面是我的测试代码，你能提供一个demo吗？

```
@namespace AntDesign.Pro.Template.Pages.Dashboard.Workplace
@using System.Text.RegularExpressions
@page "/dashboard/workplace"

<PageContainer Title="Workplace">
    <Breadcrumb>
        <Breadcrumb>
            <BreadcrumbItem>Home</BreadcrumbItem>
            <BreadcrumbItem>Dashboard</BreadcrumbItem>
            <BreadcrumbItem>Workplace</BreadcrumbItem>
        </Breadcrumb>
    </Breadcrumb>
    
    
    <ChildContent>
        <Button Type="primary" OnClick="@(()=>{ _visible = true; })">
            Open Modal
        </Button>
        
        <p>@bvalue</p>
    </ChildContent>
</PageContainer>


<Modal Title="@title"
       Visible="@_visible"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel">
    <GridRow >
        <GridCol Span="24">
            <TextArea @bind-Value="@bvalue" Placeholder="@bvalue"></TextArea>
        </GridCol>
    </GridRow>
</Modal>

@code {
    string title = "BasicModal";
    string bvalue = "bvalue";
    bool _visible = false;

    private void HandleOk(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }

    private void HandleCancel(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }
}
```

**Comment by SoaSoftNet** [comment]
我重新创建一个项目后，是正常的。这样我再找下问题，给您反馈。谢谢

**Comment by zxyao145** [comment]
> 我重新创建一个项目后，是正常的。这样我再找下问题，给您反馈。谢谢

OK，有问题再沟通
