### ISSUE TITLE
Is it currently supported NET 7.0, or whether there is plan support NET 7.0

### ISSUE THREAD

**Issue by ZhiMaYiLian** [ant-design-blazor/ant-design-blazor#2882]
Is it currently supported NET 7.0, or whether there is plan support NET 7.0

**Comment by ElderJames** [comment]
Hi @ZhiMaYiLian , we have been support .NET 7 and will be shipped in 0.13.0

**Comment by ElderJames** [comment]
0.13.0 is released. Thank you!
