### ISSUE TITLE
Website error culture

### ISSUE THREAD

**Issue by takorn47** [ant-design-blazor/ant-design-blazor#2884]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/117840045/202119806-7d7f979c-92a1-4f62-a85a-fa3e36e2aa49.png)

When i enter website to read document ant component, loading will freeze at 100% 
my browser language is Thai language 

when i change browser to English language it work correctly.

**Comment by takorn47** [comment]
Thank you.

**Comment by ElderJames** [comment]
Hello @takorn47 , please try the [preview page in the fix PR](https://github.com/ant-design-blazor/ant-design-blazor/pull/2886#issuecomment-1316667788). I have try it in my browser with Thai ant it would turn to en-US correctly.
