### ISSUE TITLE
The docs website crashes with unsupported application's culture when using italian as locale language

### ISSUE THREAD

**Issue by fuji97** [ant-design-blazor/ant-design-blazor#2885]
### Describe the bug

I got a System.AggregateException - Blazor detected a change in the application's culture that is not supported with the current project configuration, when trying to open the website. I think it is caused by just having a locale different from english (I have italian)

### Steps to reproduce (please include code)
- Open https://antblazor.com/en-US/components/overview with italian as locale language

### Exceptions (if any)
```
System.AggregateException: AggregateException_ctor_DefaultMessage (Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.)
 ---> System.InvalidOperationException: Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken , WebAssemblyCultureProvider )
   at AntDesign.Docs.Wasm.Program.Main(String[] args)
   Exception_EndOfInnerExceptionStack
```

### Further technical details
- Latest docs version
- Both Google Chrome 107.0.5304.107 and Firefox 107.0
- Italian as locale language

**Comment by ElderJames** [comment]
Hello @fuji97 , please try the [preview page in the fix PR](https://github.com/ant-design-blazor/ant-design-blazor/pull/2886#issuecomment-1316667788). I have try it in my browser with Italian ant it works well in en-US .
