### ISSUE TITLE
Deserialize QueryModel (table) Problem

### ISSUE THREAD

**Issue by jorislops** [ant-design-blazor/ant-design-blazor#2888]
### Describe the bug

It's not possible to deserialize the QueryModel or QueryModel<T>. Deserialize is a problem because of interface usage (See exception below). This is problematic because I try to send the QueryModel to the backend (asp.net core and deserialize the object), but the back-end is not able to deserialize the object. The code below is what happens when I do serialization/deserialization myself (same problem).

### Steps to reproduce (please include code)

    private async Task OnChange(QueryModel queryModel)
    {
        Console.WriteLine(JsonSerializer.Serialize(queryModel));
        string queryModelJson = JsonSerializer.Serialize(queryModel);
       QueryModel? deserialized = JsonSerializer.Deserialize<QueryModel>(queryModelJson);
    }

### Exceptions (if any)

System.NotSupportedException: Deserialization of interface types is not supported. Type 'AntDesign.TableModels.ITableSortModel'. Path: $.SortModel[0] | LineNumber: 0 | BytePositionInLine: 61.
 ---> System.NotSupportedException: Deserialization of interface types is not supported. Type 'AntDesign.TableModels.ITableSortModel'.
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)

### Further technical details
- AntDesign Nuget Package version 0.12.7
- .NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.403/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
- JetBrains Rider 2022.2.4

**Comment by ElderJames** [comment]
Hello @jorislops , we need to add two JsonConverters for QueryModel Deserialization.

please see https://antblazor.com/en-US/components/table#components-table-demo-restore-query-state

```cs
var settings = new JsonSerializerOptions();
settings.Converters.Add(new SortModelConverter());
settings.Converters.Add(new FilterModelConverter());
QueryModel<Data> queryModel = JsonSerializer.Deserialize<QueryModel<Data>>(SavedQueryModelJson, settings);

Table.ReloadData(queryModel);
```

**Comment by jorislops** [comment]
Hi @ElderJames, Tank's for the quick reply and it works 👍. 
I missed this is the documentation (I looked at different examples).
