### ISSUE TITLE
Create the same menu as Ant-Design of React

### ISSUE THREAD

**Issue by vertonghenb** [ant-design-blazor/ant-design-blazor#29]
Currently the menu is not following the React or Angular Demo pages.
It would be handy if our menu would look the same as theirs and disable the menu item's of the component is not yet implemented.
Example:
![image](https://user-images.githubusercontent.com/10981553/77251178-3a066280-6c4d-11ea-80e6-dd661f4212ce.png)

**Comment by ElderJames** [comment]
Of course, we need to follow them.

**Comment by ElderJames** [comment]
Done #126
