### ISSUE TITLE
DatePicker Can you add a default time for ShowTime?

### ISSUE THREAD

**Issue by Breave-YY** [ant-design-blazor/ant-design-blazor#2909]
DatePicker Can you add a default time for ShowTime?

**Comment by ElderJames** [comment]
Hello @Breave-YY , what do you mean, please?

**Comment by Breave-YY** [comment]
It is to set the default time for hours, minutes and seconds. Now the default time is 00:00:00

**Comment by ElderJames** [comment]
I think it's very well supported so far.

```razor

<DatePicker @bind-Value="value"  ShowTime="@true"  />
<br />
<RangePicker @bind-Value="value2"  ShowTime='@("HH:mm")'  />

@code
{
    DateTime? value = DateTime.Now;
    DateTime?[] value2 = { DateTime.Now, DateTime.Now.AddDays(1) };
}
```

![image](https://user-images.githubusercontent.com/7550366/204956567-463d107a-ec89-4c34-896e-caf18c1a21b8.png)

**Comment by Breave-YY** [comment]
This is not the result I want. What I want is that time is not selected by default. When I select a date and time is not selected, the hour, minute and second of the start time is 00:00:00, and when I select an end time, the hour, minute and second can be 23:59:59

**Comment by ElderJames** [comment]
I don't think this should be done by the component, the user can change the selected time.
