### ISSUE TITLE
Wrong Input behaviour if paired with Select

### ISSUE THREAD

**Issue by manuelelucchi** [ant-design-blazor/ant-design-blazor#2912]
### Describe the bug

If I have a Select paired with an Input and I update the input with a different text with OnSelectionChanged and I click the input to get focus, the text is reset to the default one

### Steps to reproduce (please include code)

An Input with a Select with the previous described interaction should suffice

### Further technical details
This problem is not present in 0.12.7 while it is in 0.13

**Comment by ElderJames** [comment]
Thanks you for cantacting us @manuelelucchi , I have fix this issue in #2906 , I will ship it today.

**Comment by ElderJames** [comment]
@manuelelucchi Please update 0.13.1, thanks.

**Comment by manuelelucchi** [comment]
Thank you, how fast!
