### ISSUE TITLE
sentry.io a datepick error collected

### ISSUE THREAD

**Issue by GlodenBoy** [ant-design-blazor/ant-design-blazor#2915]
version: 0.13.0

I use sentry in the client to collect error logs and have recently received frequent errors for a date fetch component.

Steps to reproduce:
Click on the date display drop-down box and it will appear, strangely, I did not find an error in the console, but it was intercepted by sentry.

<img width="534" alt="6bdf72495ed9cc9be3b41a25c148423" src="https://user-images.githubusercontent.com/2329528/204555439-cdc6ee88-f757-40d6-a812-fa6ee20973be.png">

The messagebox below is the message I intercepted sending an error report

<img width="629" alt="c67ec766724c84d525bb7bff1321a95" src="https://user-images.githubusercontent.com/2329528/204555482-4f838a05-eba0-4962-b86d-548c11c2cd90.png">

at System.Nullable`1.get_Value()
   at AntDesign.Internal.DatePickerDatetimePanel`1.ScrollToSelectedHourAsync(Nullable`1 duration)

**Comment by Alexbits** [comment]
@GlodenBoy Thanks. Fixed.
