### ISSUE TITLE
CountDown  -  format has no effect when publish

### ISSUE THREAD

**Issue by Stardusstt** [ant-design-blazor/ant-design-blazor#2917]
### Describe the bug

CountDown format has no effect when "publish" , but work correct in "start without debugging" and "start debugging".

"start without debugging" and "start debugging"
<img width="341" alt="image" src="https://user-images.githubusercontent.com/40061990/204601970-ac54b9f2-2f4c-4266-8aa5-6901a23c93c2.png">

"publish"
<img width="755" alt="image" src="https://user-images.githubusercontent.com/40061990/204601980-7c59a1f5-d3a2-4f2d-858b-436add60db70.png">

<img width="835" alt="image" src="https://user-images.githubusercontent.com/40061990/204605435-764a2d1b-976f-43fb-b532-8c2313e497da.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/40061990/204605451-2005564d-bb5f-4ba9-a7aa-7432bee71131.png">

```
<Row Gutter="16">
    <Col Span="12">
        <CountDown Title="Countdown" Value="@deadline" OnFinish="OnFinish" />
    </Col>
    <Col Span="12">
        <CountDown Title="Million" Value="@deadline" Format="hh:mm:ss:fff" />
    </Col>
    <Col Span="24">
        <CountDown Title="Day Level" Value="@deadline" Format="dd 天  h 小时 m 分钟 s 秒" />
    </Col>
    <br/>
    <Button OnClick="OnReset">Reset Value</Button>
</Row>

@code
{
    DateTime deadline = DateTime.Now.AddMilliseconds(1000 * 60 * 60 * 24 * 2 + 1000 * 30);

    void OnFinish()
    {
        Console.WriteLine("finished!");
    }

    void OnReset()
    {
        deadline = DateTime.Now.AddMinutes(10);
    }
}
```

### Exceptions (if any)
no

### Further technical details
- AntDesign Nuget Package version : v0.13.1
- Include the output of `dotnet --info`
```
 .NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

執行階段環境:
 OS Name:     Windows
 OS Version:  10.0.22623
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
> Microsoft Visual Studio Community 2022 (64-bit) - Preview
   Version 17.5.0 Preview 1.0

**Comment by ElderJames** [comment]
Thanks for contacting us @Stardusstt , but our site antblazor.com works well. I don't know what the issue is.

**Comment by Stardusstt** [comment]
It seems the problem in _framework .
I try to copy the _framework  folder from release version to publish,  format work again.
@ElderJames what is the IDE or .NET SDK version use for site antblazor.com?

**Comment by ElderJames** [comment]
.NET SDK is 7.0, and we use github action to publish and deploy.

https://github.com/ant-design-blazor/ant-design-blazor/blob/master/.github/workflows/release.yml

**Comment by Stardusstt** [comment]
@ElderJames 
I have no idea,
but I can reproduce it in stable version, Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.2

- use windows sandbox for fresh install
- visual code + live server, for hosting publish folder


<img width="1280" alt="image" src="https://user-images.githubusercontent.com/40061990/205140165-5c8f7be3-84d4-4343-900b-12d8b94dbf4f.png">

**Comment by Stardusstt** [comment]
Find out what cause the problem.
set `<PublishTrimmed>false</PublishTrimmed>` , to disable trimming during publish.
However, I can't find which Assembly cause problem.


https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-7.0
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0

**Comment by ElderJames** [comment]
I think wasm no need to enable the `PublishTrimmed` setting. You can just enable the AOT.

**Comment by Stardusstt** [comment]
> I think wasm no need to enable the `PublishTrimmed` setting. 

that is a default behavior when publish, I think this should be consider a bug?

> Blazor WebAssembly performs Intermediate Language (IL) trimming to reduce the size of the published output. By default, trimming occurs when publishing an app.
https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-7.0

---
>You can just enable the AOT.

I think that will take too long to download to the client, when not need so many runtime performance

For this simple demo 

- 59.2 MB 
- 154 MB  (AOT)

>Although the size difference depends on the app, most AOT-compiled apps are about twice the size of their IL-compiled versions. This means that using AOT compilation trades off load-time performance for runtime performance. 
https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#ahead-of-time-aot-compilation

**Comment by ElderJames** [comment]
OK, let's find where is the problem.
