### ISSUE TITLE
When the datasource of table comes from dataset and AsNoTracking, all selection will be doubled

### ISSUE THREAD

**Issue by SmRiley** [ant-design-blazor/ant-design-blazor#2921]
### Describe the bug

When the datasource of table comes from dataset and AsNoTracking, all selection will be doubled
like this:
![image](https://user-images.githubusercontent.com/45205313/205008505-3778289d-5f5d-447e-97a8-2411ae8ae25f.png)

[demo](https://github.com/SmRiley/BlazorApp1)

**Comment by ElderJames** [comment]
Sorry, the demo link is not available.
