### ISSUE TITLE
System.ArgumentException: There is no tracked object with id '2'. Perhaps the DotNetObjectReference instance was already disposed

### ISSUE THREAD

**Issue by mrjohnr** [ant-design-blazor/ant-design-blazor#2924]
Hi
I'm using AntDesign 0.13.1 in .NET 6

in main component I use AntDesign  DatePicker and Drawer
when I call  `NavigationManager.NavigateTo("/login") ` got in console:

`blazor.webassembly.js:1 Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '2'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')
   at Microsoft.JSInterop.JSRuntime.GetObjectReference(Int64 dotNetObjectId)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime,…fo, String argsJson)
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js:1:3531)
    at Object.Rt [as endInvokeDotNetFromJS] (blazor.webassembly.js:1:60673)
    at Object.St [as invokeJSFromDotNet] (blazor.webassembly.js:1:60156)
    at _mono_wasm_invoke_js_blazor (dotnet.6.0.11.ud4to5be8n.js:1:195300)
    at 00971d3e:0x1a492
    at 00971d3e:0xce60
    at 00971d3e:0xbd73
    at 00971d3e:0xabec4
    at 00971d3e:0x6fc85
    at 00971d3e:0x702f2
endInvokeDotNetFromJS	@	blazor.webassembly.js:1
Rt	@	blazor.webassembly.js:1
St	@	blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor	@	dotnet.6.0.11.ud4to5be8n.js:1
$func219	@	00971d3e:0x1a492
$func167	@	00971d3e:0xce60
$func166	@	00971d3e:0xbd73
$func2815	@	00971d3e:0xabec4
$func1619	@	00971d3e:0x6fc85
$func1623	@	00971d3e:0x702f2
$mono_wasm_invoke_method	@	00971d3e:0x969f
Module._mono_wasm_invoke_method	@	dotnet.6.0.11.ud4to5be8n.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet	@	managed__Microsoft_A…eginInvokeDotNet:19
beginInvokeDotNetFromJS	@	blazor.webassembly.js:1
b	@	blazor.webassembly.js:1
invokeMethodAsync	@	blazor.webassembly.js:1
(anonymous)	@	eventHelper.ts:27
setTimeout (async)		
o	@	eventHelper.ts:27`

I found that error is gone if I remove both DatePicker and Drawer usage
If I remove one of them index object error changes from 2 to 3
thanks

**Comment by SteinLT** [comment]
This also happens for the Select and Dropdown components.

**Comment by csm12s** [comment]
same as this
https://gitee.com/ant-design-blazor/ant-design-blazor/issues/I660W4

**Comment by ElderJames** [comment]
Fixed in #2980 .
