### ISSUE TITLE
In AutoComplete I want to show "No Result Found" option value instant of the empty data while users are trying to search which is not included in the option lists.

### ISSUE THREAD

**Issue by NannSaiKham** [ant-design-blazor/ant-design-blazor#2926]
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
This is not the design of AutoComplete. If there are no result, it won't open the dropdown panel.
