### ISSUE TITLE
PageHeader redundant parameters should be consolidated

### ISSUE THREAD

**Issue by kooliokey** [ant-design-blazor/ant-design-blazor#2936]
### Is your feature request related to a problem? Please describe.
While working on #2832 I found there are some redundant parameters in the PageHeader component that could be consolidated. 

### Describe the solution you'd like
- `TitleTemplate` and `Title` provide the same functionality as `PageHeaderTitle` - either the first two or the last should be kept
- `SubtitleTemplate` and `Subtitle` provide the same functionality as `PageHeaderSubtitle` - either the first two or the last should be kept

**Comment by ElderJames** [comment]
I think we should keep the first two of them.
