### ISSUE TITLE
Table Filters not consistently resetting row count when selected filter changed

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#2950]
In the following example there is one `Standard length (m)` and many `Lineal metre` rows, but when switching to `Lineal metre` only one row is displayed:

![TableFilter](https://user-images.githubusercontent.com/21806535/207988753-fa66e1c7-4545-4140-b76b-781f866cb7f5.gif)

It behaves similarly with `FilterMultiple`. However, when selecting `Each` the row count seems to reset:

![TableFilterMultiple](https://user-images.githubusercontent.com/21806535/207990593-70dc5709-722c-45ea-9b02-eefb934e575f.gif)

This also happens with the default built-in filter.

**Comment by michaelcsikos** [comment]
I don't know what I'm doing different now, but I can't reproduce this bug anymore.

**Comment by ElderJames** [comment]
Hello @michaelcsikos , do you still have this issue?

**Comment by michaelcsikos** [comment]
Hi @ElderJames, the filters have been working fine for me recently. I don't know what I'm doing differently or if anything has changed in the codebase.

**Comment by ElderJames** [comment]
Thank you @michaelcsikos , I'm going to close this issue.
