### ISSUE TITLE
[Table] Fixed parameter in ColumnBase is not work when  Table PropertyColumn is changeable in C# code

### ISSUE THREAD

**Issue by lulianqi** [ant-design-blazor/ant-design-blazor#2954]
### Describe the bug
I dynamically changed the PropertyColumn in the table and set the Fixed at the same time. At this time, Fixed behaves abnormally, and the value of the column that is set to Fixed cannot be fixed in the correct position.

### Steps to reproduce 

Here is the test code for the problem
```
<Table DataSource="@sessionCollection.SessionQueue" TItem="SessionItem" ScrollY="calc(100vh - 100px)" ScrollX="1300" Size="TableSize.Small" HidePagination="@true">
     <PropertyColumn
                    Title = "id"
                    Fixed= "left"
                    Property = "c=>c.Number"
                    Width="100"
                    Sortable
                    Filterable />
    @if(proxySessionConfig?.ItemsDisplayOptions!=null)
    {
        foreach (var displayItem in proxySessionConfig.ItemsDisplayOptions)
        {
            switch(displayItem.Name)
            {
                case "CreateTime":
                {
                    if(!displayItem.IsShow) break;
                     <PropertyColumn
                    Title = "@(displayItem.ShowName)"
                    Property = "c=>c.CreateTime"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Format="HH:mm:ss fff"
                    Sortable
                    Filterable />
                    break;
                }
                case "Method":
                {
                    if(!displayItem.IsShow) break;
                     <PropertyColumn
                    Title = "@(displayItem.ShowName)"
                    Property = "c=>c.HttpClient.Request.Method"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Format="HH:mm:ss fff"
                    Sortable
                    Filterable />
                    break;
                }
                case "Url":
                {
                    if(!displayItem.IsShow) break;
                        <PropertyColumn 
                        Property="c=>c.Url"
                        Width="800"
                        SorterCompare="@((a,b)=> string.Compare(a,b))"
                        SortDirections="new[] { SortDirection.Descending }"
                        Filterable />
                        break;
                }
                default :
                {
                    if(!displayItem.IsShow) break;
                    <PropertyColumn
                    Title = "@(displayItem.ShowName)"
                    Property = "c=>c.Number"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Sortable
                    Filterable />
                    break;
                }
            }    
        }
    }
    <ActionColumn  Width="100" Fixed="right">
        <TitleTemplate>
            <span style="display:flex; width:100%">
                <Space Align="center" Size=@("5")>
                    <SpaceItem>
                        详情
                    </SpaceItem>
                    <SpaceItem>
                        <Tooltip Title=@("是否保存响应内容") style="display:flex;align-items:center">
                            <Switch Size="small"> </Switch>
                        </Tooltip>
                    </SpaceItem>
                </Space>
                <Tooltip MouseEnterDelay=2 Title=@("设置") style="flex: 1; display: flex; align-items: center ;justify-content:flex-end">
                    <Icon Type="setting" Theme="fill" Style="cursor: pointer;float:right ;color:lightblue" OnClick="OpenSetingTemplate" />
                </Tooltip>
            </span>
        </TitleTemplate>
        <ChildContent>
            <Space>
                <SpaceItem><Button Danger>Delete</Button></SpaceItem>
            </Space>
        </ChildContent>
    </ActionColumn>
    
</Table>
```

![image](https://user-images.githubusercontent.com/23115455/208083049-869f9d7d-dab1-4b68-9b95-b58999519541.png)
As shown in the figure above, the value of the fixed column does not appear in the correct position

**Comment by ElderJames** [comment]
Thanks for contacting @lulianqi , please provide a reproduce demo.

I run the following code, which is fine:
```
<Table DataSource="@sessionCollection" TItem="SessionItem" ScrollY="calc(100vh - 100px)" ScrollX="1300" Size="TableSize.Small" HidePagination="@true">
    <PropertyColumn Title="id"
                    Fixed="left"
                    Property="c=>c.Number"
                    Width="100"
                    Sortable
                    Filterable />
    @if (ItemsDisplayOptions != null)
    {
        foreach (var displayItem in ItemsDisplayOptions)
        {
            switch (displayItem.Name)
            {
                case "CreateTime":
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Title="@(displayItem.ShowName)"
                    Property="c=>c.CreateTime"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Format="HH:mm:ss fff"
                    Sortable
                    Filterable />
                        break;
                    }
                case "Method":
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Title="@(displayItem.ShowName)"
                    Property="c=>c.HttpClientRequestMethod"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Format="HH:mm:ss fff"
                    Sortable
                    Filterable />
                        break;
                    }
                case "Url":
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Property="c=>c.Url"
                    Width="800"
                    SorterCompare="@((a,b)=> string.Compare(a,b))"
                    SortDirections="new[] { SortDirection.Descending }"
                    Filterable />
                        break;
                    }
                default:
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Title="@(displayItem.ShowName)"
                    Property="c=>c.Number"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Sortable
                    Filterable />
                        break;
                    }
            }
        }
    }
    <ActionColumn Width="100" Fixed="right">
        <TitleTemplate>
            <span style="display:flex; width:100%">
                <Space Align="center" Size=@("5")>
                    <SpaceItem>
                        详情
                    </SpaceItem>
                    <SpaceItem>
                        <Tooltip Title=@("是否保存响应内容") style="display:flex;align-items:center">
                            <Switch Size="small"> </Switch>
                        </Tooltip>
                    </SpaceItem>
                </Space>
                <Tooltip MouseEnterDelay=2 Title=@("设置") style="flex: 1; display: flex; align-items: center ;justify-content:flex-end">
                    <Icon Type="setting" Theme="fill" Style="cursor: pointer;float:right ;color:lightblue" />
                </Tooltip>
            </span>
        </TitleTemplate>
        <ChildContent>
            <Space>
                <SpaceItem><Button Danger>Delete</Button></SpaceItem>
            </Space>
        </ChildContent>
    </ActionColumn>

</Table>

@code{
    class SessionItem
    {
        public int Number{ get; set; }
        public DateTime CreateTime{ get; set; }
        public string HttpClientRequestMethod{ get; set; }
        public string Url{ get; set; }
    }

    class displayItem
    {
        public  string Name{ get; set; }
        public bool IsShow { get; set; } = true;
        public string ShowName{ get; set; }
        public int ItemWidth { get; set; } = 100;
    }

    IEnumerable<SessionItem> sessionCollection=new SessionItem[]
    {
        new(){Number=1,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
        new(){Number=2,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
        new(){Number=3,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
        new(){Number=4,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
        new(){Number=5,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
    };
    IEnumerable<displayItem> ItemsDisplayOptions = new displayItem[]
    {
        new(){Name="CreateTime",ShowName="CreateItem"},
        new(){Name="Method", ShowName="Method"},
        new(){Name="Url", ShowName="Url"},
        new(){Name="Other", ShowName="Other"}
    };
}
```

![image](https://user-images.githubusercontent.com/7550366/212314751-b7729567-eee5-476b-a00d-cdce24e0534e.png)

**Comment by lulianqi** [comment]
> Thanks for contacting @lulianqi , please provide a reproduce demo.
> 
> I run the following code, which is fine:
> 
> ```
> <Table DataSource="@sessionCollection" TItem="SessionItem" ScrollY="calc(100vh - 100px)" ScrollX="1300" Size="TableSize.Small" HidePagination="@true">
>     <PropertyColumn Title="id"
>                     Fixed="left"
>                     Property="c=>c.Number"
>                     Width="100"
>                     Sortable
>                     Filterable />
>     @if (ItemsDisplayOptions != null)
>     {
>         foreach (var displayItem in ItemsDisplayOptions)
>         {
>             switch (displayItem.Name)
>             {
>                 case "CreateTime":
>                     {
>                         if (!displayItem.IsShow) break;
>                         <PropertyColumn Title="@(displayItem.ShowName)"
>                     Property="c=>c.CreateTime"
>                     Width="@(displayItem.ItemWidth.ToString())"
>                     Format="HH:mm:ss fff"
>                     Sortable
>                     Filterable />
>                         break;
>                     }
>                 case "Method":
>                     {
>                         if (!displayItem.IsShow) break;
>                         <PropertyColumn Title="@(displayItem.ShowName)"
>                     Property="c=>c.HttpClientRequestMethod"
>                     Width="@(displayItem.ItemWidth.ToString())"
>                     Format="HH:mm:ss fff"
>                     Sortable
>                     Filterable />
>                         break;
>                     }
>                 case "Url":
>                     {
>                         if (!displayItem.IsShow) break;
>                         <PropertyColumn Property="c=>c.Url"
>                     Width="800"
>                     SorterCompare="@((a,b)=> string.Compare(a,b))"
>                     SortDirections="new[] { SortDirection.Descending }"
>                     Filterable />
>                         break;
>                     }
>                 default:
>                     {
>                         if (!displayItem.IsShow) break;
>                         <PropertyColumn Title="@(displayItem.ShowName)"
>                     Property="c=>c.Number"
>                     Width="@(displayItem.ItemWidth.ToString())"
>                     Sortable
>                     Filterable />
>                         break;
>                     }
>             }
>         }
>     }
>     <ActionColumn Width="100" Fixed="right">
>         <TitleTemplate>
>             <span style="display:flex; width:100%">
>                 <Space Align="center" Size=@("5")>
>                     <SpaceItem>
>                         详情
>                     </SpaceItem>
>                     <SpaceItem>
>                         <Tooltip Title=@("是否保存响应内容") style="display:flex;align-items:center">
>                             <Switch Size="small"> </Switch>
>                         </Tooltip>
>                     </SpaceItem>
>                 </Space>
>                 <Tooltip MouseEnterDelay=2 Title=@("设置") style="flex: 1; display: flex; align-items: center ;justify-content:flex-end">
>                     <Icon Type="setting" Theme="fill" Style="cursor: pointer;float:right ;color:lightblue" />
>                 </Tooltip>
>             </span>
>         </TitleTemplate>
>         <ChildContent>
>             <Space>
>                 <SpaceItem><Button Danger>Delete</Button></SpaceItem>
>             </Space>
>         </ChildContent>
>     </ActionColumn>
> 
> </Table>
> 
> @code{
>     class SessionItem
>     {
>         public int Number{ get; set; }
>         public DateTime CreateTime{ get; set; }
>         public string HttpClientRequestMethod{ get; set; }
>         public string Url{ get; set; }
>     }
> 
>     class displayItem
>     {
>         public  string Name{ get; set; }
>         public bool IsShow { get; set; } = true;
>         public string ShowName{ get; set; }
>         public int ItemWidth { get; set; } = 100;
>     }
> 
>     IEnumerable<SessionItem> sessionCollection=new SessionItem[]
>     {
>         new(){Number=1,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
>         new(){Number=2,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
>         new(){Number=3,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
>         new(){Number=4,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
>         new(){Number=5,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
>     };
>     IEnumerable<displayItem> ItemsDisplayOptions = new displayItem[]
>     {
>         new(){Name="CreateTime",ShowName="CreateItem"},
>         new(){Name="Method", ShowName="Method"},
>         new(){Name="Url", ShowName="Url"},
>         new(){Name="Other", ShowName="Other"}
>     };
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/7550366/212314751-b7729567-eee5-476b-a00d-cdce24e0534e.png)

@ElderJames Thank you very much for your reply. I looked at the gap between the codes and found the key point. The timing is the key. The value of the ItemsDisplayOptions of the problematic code is determined in OnAfterRenderAsync, which leads to the exception described in the description. Here is an example to reproduce
`<Table DataSource="@sessionCollection" TItem="SessionItem" ScrollY="calc(100vh - 100px)" ScrollX="1300" Size="TableSize.Small" HidePagination="@true">
    <PropertyColumn Title="id"
                    Fixed="left"
                    Property="c=>c.Number"
                    Width="100"
                    Sortable
                    Filterable />
    @if (ItemsDisplayOptions != null)
    {
        foreach (var displayItem in ItemsDisplayOptions)
        {
            switch (displayItem.Name)
            {
                case "CreateTime":
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Title="@(displayItem.ShowName)"
                    Property="c=>c.CreateTime"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Format="HH:mm:ss fff"
                    Sortable
                    Filterable />
                        break;
                    }
                case "Method":
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Title="@(displayItem.ShowName)"
                    Property="c=>c.HttpClientRequestMethod"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Format="HH:mm:ss fff"
                    Sortable
                    Filterable />
                        break;
                    }
                case "Url":
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Property="c=>c.Url"
                    Width="800"
                    SorterCompare="@((a,b)=> string.Compare(a,b))"
                    SortDirections="new[] { SortDirection.Descending }"
                    Filterable />
                        break;
                    }
                default:
                    {
                        if (!displayItem.IsShow) break;
                        <PropertyColumn Title="@(displayItem.ShowName)"
                    Property="c=>c.Number"
                    Width="@(displayItem.ItemWidth.ToString())"
                    Sortable
                    Filterable />
                        break;
                    }
            }
        }
    }
    <ActionColumn Width="100" Fixed="right">
        <TitleTemplate>
            <span style="display:flex; width:100%">
                <Space Align="center" Size=@("5")>
                    <SpaceItem>
                        详情
                    </SpaceItem>
                    <SpaceItem>
                        <Tooltip Title=@("是否保存响应内容") style="display:flex;align-items:center">
                            <Switch Size="small"> </Switch>
                        </Tooltip>
                    </SpaceItem>
                </Space>
                <Tooltip MouseEnterDelay=2 Title=@("设置") style="flex: 1; display: flex; align-items: center ;justify-content:flex-end">
                    <Icon Type="setting" Theme="fill" Style="cursor: pointer;float:right ;color:lightblue" />
                </Tooltip>
            </span>
        </TitleTemplate>
        <ChildContent>
            <Space>
                <SpaceItem><Button Danger>Delete</Button></SpaceItem>
            </Space>
        </ChildContent>
    </ActionColumn>

</Table>

@code {
    class SessionItem
    {
        public int Number { get; set; }
        public DateTime CreateTime { get; set; }
        public string HttpClientRequestMethod { get; set; }
        public string Url { get; set; }
    }

    class displayItem
    {
        public string Name { get; set; }
        public bool IsShow { get; set; } = true;
        public string ShowName { get; set; }
        public int ItemWidth { get; set; } = 100;
    }

    IEnumerable<SessionItem> sessionCollection = new SessionItem[]
          {
            new (){Number=1,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
            new (){Number=2,CreateTime=DateTime.Now,HttpClientRequestMethod="Get",Url="http"},
            new() { Number = 3, CreateTime = DateTime.Now, HttpClientRequestMethod = "Get", Url = "http" },
            new() { Number = 4, CreateTime = DateTime.Now, HttpClientRequestMethod = "Get", Url = "http" },
            new() { Number = 5, CreateTime = DateTime.Now, HttpClientRequestMethod = "Get", Url = "http" },
          };
    IEnumerable<displayItem> ItemsDisplayOptions ;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            ItemsDisplayOptions = new displayItem[]
            {
                new(){Name="CreateTime",ShowName="CreateItem"},
                new(){Name="Method", ShowName="Method"},
                new(){Name="Url", ShowName="Url"},
                new(){Name="Other", ShowName="Other"}
            };
        }
        await base.OnAfterRenderAsync(firstRender);
    }

}
`
![image](https://user-images.githubusercontent.com/23115455/213907632-05c216d4-d467-4818-bf6d-a6f8f28afab9.png)

**Comment by lulianqi** [comment]
I think this should be a small defect, but through the hints of the test code, I found a way to skip this problem. I can set any value for ItemsDisplayOptions in advance (as long as it is not null, any meaningless data is fine, because it will be reset to the correct value later)

```
 IEnumerable<displayItem> ItemsDisplayOptions = new displayItem[] {                 
                new(){Name="Otherx", ShowName="Otherx"}
        };

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            ItemsDisplayOptions = new displayItem[]
            {
                new(){Name="CreateTime",ShowName="CreateItem"},
                new(){Name="Method", ShowName="Method"},
                new(){Name="Url", ShowName="Url"},
                new(){Name="Other", ShowName="Other"}
            };
        }
        await base.OnAfterRenderAsync(firstRender);
    }

```
