### ISSUE TITLE
Select with Mode tags/multiple and SearchDebounceMilliseconds causes input to be hidden

### ISSUE THREAD

**Issue by wss-javeney** [ant-design-blazor/ant-design-blazor#2960]
### Describe the bug

When using a `Select` component with `Mode` set to either `multiple` or `tags` and a value provided to `SearchDebounceMilliseconds` the user typed input will be overlapped and hidden from view as user types. It is more affected by faster typing, but I have noticed it typing one character at a time as well. 

### Steps to reproduce (please include code)

**Default mode** with input "be" (Expected behavior)
![image](https://user-images.githubusercontent.com/119613015/209000241-e44e2208-559c-4e17-88fd-3be563bf9f8c.png)

**Multiple mode** with input "be"
![image](https://user-images.githubusercontent.com/119613015/209000086-ed32105d-e635-47ec-940a-c1c8a799fb04.png)

**Tags mode** with input "oooo"
 Note: This mode will sometimes just lag behind, and then input will update to be visible. 

Other times it will stay hidden like below:
![image](https://user-images.githubusercontent.com/119613015/209000833-7621e670-5ef2-45f2-bca8-e04332d39621.png)

```
<h3>Default mode</h3>
<Select Mode="default"
        Placeholder="Select an Option"
        @bind-Values="@SelectedValues"
        TItemValue="string"
        TItem="string"
        Style="width: 100%; margin-bottom: 8px;"
        EnableSearch
        SearchDebounceMilliseconds="350">
    <SelectOptions>
        @foreach (var option in _selectOptions)
        {
            <SelectOption TItemValue="string" TItem="string" Value=@option Label=@option />
        }
    </SelectOptions>
</Select>

<h3>Multiple mode</h3>
<Select Mode="multiple"
        Placeholder="Select an Option"
        @bind-Values="@SelectedValuesMultiple"
		TItemValue="string"
		TItem="string"
        Style="width: 100%; margin-bottom: 8px;"
        EnableSearch
        SearchDebounceMilliseconds="350">
    <SelectOptions>
        @foreach (var option in _selectOptions)
	{
            <SelectOption TItemValue="string" TItem="string" Value=@option Label=@option />
	}
    </SelectOptions>
</Select>

<h3>Tags mode</h3>
<Select Mode="tags"
        Placeholder="Select an Option"
        @bind-Values="@SelectedValuesTags"
        TItemValue="string"
        TItem="string"
        Style="width: 100%; margin-bottom: 8px;"
        EnableSearch
        SearchDebounceMilliseconds="350">
    <SelectOptions>
        @foreach (var option in _selectOptions)
        {
            <SelectOption TItemValue="string" TItem="string" Value=@option Label=@option />
        }
    </SelectOptions>
</Select>

@code
{
    private List<string> _selectOptions = new List<string>();

    protected IEnumerable<string> SelectedValuesMultiple { get; set; }

    protected IEnumerable<string> SelectedValuesTags { get; set; }

    protected IEnumerable<string> SelectedValues { get; set; }

    protected override void OnInitialized()
    {
        _selectOptions.Add("Dog");
        _selectOptions.Add("Bear");
        _selectOptions.Add("Cat");
        _selectOptions.Add("Llama");
        _selectOptions.Add("Kangaroo");
        _selectOptions.Add("Giraffe");
    }
}
```

**Comment by m-khrapunov** [comment]
@ElderJames An issue still exists for AntBlazor server. I pretty sure input search value have strange display behavior bacause [SetInputWidth()](https://github.com/ant-design-blazor/ant-design-blazor/blob/2ade899b8dda7af508221442e00e5b3825d5d08d/components/select/internal/SelectContent.razor.cs#L279-L305) implementation of dynamic width value in case of **_multiple_** or **_tags_** select modes. Can it be simplified to constant width value?
