### ISSUE TITLE
建议增加：通过注入服务调用 Show 方法弹出Modal简单窗口

### ISSUE THREAD

**Issue by dawningzhang** [ant-design-blazor/ant-design-blazor#297]
通过 Service 调用 Modal 对话框，参数除可以设置 modal 的位置、大小、关闭方式等属性外，展示内容为定义好的组件，实现动态在 modal 里显示组件内容

**Comment by ElderJames** [comment]
Thank you for contacting us @dawningzhang .
`ModalService` is already supported. Please see https://ant-design-blazor.gitee.io/zh-CN/components/modal for more detail.

**Comment by dawningzhang** [comment]
i am sorry
