### ISSUE TITLE
tab in modal bug

### ISSUE THREAD

**Issue by mrjiou** [ant-design-blazor/ant-design-blazor#2974]
### Describe the bug

when use a tabs in modal，open the modal，the only display content is the tabpanel‘s content，the modal and the tabs don’t show.

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thansk for contacting us @mrjiou , please provide your code here.

**Comment by mrjiou** [comment]
the code is very simple：
<Table TItem="ProblemDto" DataSource="_problems" Loading="_loading" Total="_total" @bind-PageSize="QueryModel.PageSize"
    @bind-PageIndex="QueryModel.Page" OnChange="HandleTableChange" RemoteDataSource Size=@TableSize.Small Bordered
    Responsive RowClassName="SetRowClassName">
    <ChildContent>
        <PropertyColumn Align="ColumnAlign.Center" Title="问题来源" Property="c=>c!.Source" />
        <PropertyColumn Align="ColumnAlign.Center" Title="问题类型" Property="c=>c!.Type" />
        <PropertyColumn Align="ColumnAlign.Center" Title="问题标题" Property="c=>c!.Title" />
        <PropertyColumn Align="ColumnAlign.Center" Title="所在河湖" Property="c=>c!.RiverName" />
        <PropertyColumn Align="ColumnAlign.Center" Title="所在区域" Property="c=>c!.RiverRegionName">
            @context.RiverRegionPath@context.RiverRegionName
        </PropertyColumn>
        <PropertyColumn Align="ColumnAlign.Center" Title="处理状态" Property="c=>c!.RiverName" />
        <ActionColumn Align="ColumnAlign.Center" style="width:160px">
            <TitleTemplate>
                <Button Icon="@IconType.Outline.PlusCircle" Type="@ButtonType.Primary" OnClick="Create"
                    style="width: 30px;height:25px;"></Button>
                <Button Icon="@IconType.Outline.CloudDownload" Type="@ButtonType.Primary" OnClick="Export"
                    style="width: 30px;height:25px;" Ghost></Button>
            </TitleTemplate>
            <ChildContent>
                <Row Justify="center">
                    <Button Type="@ButtonType.Link" Size="@ButtonSize.Small" style="color:green;"
                        OnClick="()=> Solve(context)">处理</Button>
                    <Button Type="@ButtonType.Link" Size="@ButtonSize.Small" style="color:#39107B;"
                        OnClick="()=> Assign(context)">交办</Button>
                    <Button Type="@ButtonType.Link" Size="@ButtonSize.Small" Icon="@IconType.Fill.Edit"
                        OnClick="()=> Update(context)" />
                    <Popconfirm Title="确认删除?" Placement="@Placement.Left" OnConfirm="()=> Delete(context)" OkText="确定"
                        CancelText="取消">
                        <Button Type="@ButtonType.Link" Size="@ButtonSize.Small" Danger
                            Icon="@IconType.Outline.Delete" />
                    </Popconfirm>
                </Row>
            </ChildContent>
        </ActionColumn>
    </ChildContent>
    <PaginationTemplate>
        <Row Justify="end" style="padding: 10px 3px;">
            <Pagination ShowTotal="_showTotal" Total="context.Total" PageSize="context.PageSize"
                Current="context.PageIndex" ShowSizeChanger OnChange="context.HandlePageChange" />
        </Row>
    </PaginationTemplate>
</Table>

<Modal Title="问题处理" Visible="@_solveShow" Footer=null Width="850" DestroyOnClose OnCancel="()=>{_solveShow=false;}">
     <Tabs DefaultActiveKey="1" Type="@TabType.Card" Size="@TabSize.Small">
        <TabPane Key="1" Tab="Tab 1">
            Content of Tab Pane 1
        </TabPane>
        <TabPane Key="2" Tab="Tab 2">
            Content of Tab Pane 2
        </TabPane>
        <TabPane Key="3" Tab="Tab 3">
            Content of Tab Pane 3
        </TabPane>
    </Tabs>
    @* <Solve Problem="_selectedProblem" OnChange="ServerReload" /> *@
</Modal>

**Comment by ElderJames** [comment]
Sorry, I can't reproduce the issue, I used the following code:

```
<Button OnClick="()=>_solveShow=true">show modal</Button>

<Modal Title="问题处理" Visible="@_solveShow" Footer=null Width="850" DestroyOnClose OnCancel="()=>{_solveShow=false;}">
     <Tabs DefaultActiveKey="1" Type="@TabType.Card" Size="@TabSize.Small">
        <TabPane Key="1" Tab="Tab 1">
            Content of Tab Pane 1
        </TabPane>
        <TabPane Key="2" Tab="Tab 2">
            Content of Tab Pane 2
        </TabPane>
        <TabPane Key="3" Tab="Tab 3">
            Content of Tab Pane 3
        </TabPane>
    </Tabs>
</Modal>
@code {
    bool _solveShow;
}
```

![image](https://user-images.githubusercontent.com/7550366/210729938-061d312a-777a-46ef-b6d9-509de5b1f655.png)

**Comment by mrjiou** [comment]
when model in a card：
@page "/test"
@layout LoginLayout

@inject IMessageService _message


<Button OnClick="()=>_solveShow=true">show modal</Button>

<Card Size="small" style="padding-top: 15px;">
    @* 河湖页面标题 *@
    <TitleTemplate>
       
    </TitleTemplate>

    <Extra>

    </Extra>


    <Body>
        <Modal Title="问题处理" Visible="@_solveShow" Footer=null Width="850" DestroyOnClose
            OnCancel="()=>{_solveShow=false;}">
            <Tabs DefaultActiveKey="1" Type="@TabType.Card" Size="@TabSize.Small">
                <TabPane Key="1" Tab="Tab 1">
                    Content of Tab Pane 1
                </TabPane>
                <TabPane Key="2" Tab="Tab 2">
                    Content of Tab Pane 2
                </TabPane>
                <TabPane Key="3" Tab="Tab 3">
                    Content of Tab Pane 3
                </TabPane>
            </Tabs>
        </Modal>

    </Body>
</Card>


@code {
    bool _solveShow;
}

**Comment by ElderJames** [comment]
Hello @mrjiou ,please try to put the modal outside. I'll also look at the card.
