### ISSUE TITLE
Upload image file keeps failing status response when uploading big size photos.

### ISSUE THREAD

**Issue by CyberryCJ** [ant-design-blazor/ant-design-blazor#2984]
this was the result when I tried to upload low size image.
![image](https://user-images.githubusercontent.com/36914098/210809418-5d5d7ae6-7810-4415-b828-92639701abcc.png)

but when I tried to upload  200kb size or higher this was the result no preview image.
![image](https://user-images.githubusercontent.com/36914098/210810383-8b04e364-80e2-4bc5-9807-75fc96e0066a.png)
Uploading failed
![image](https://user-images.githubusercontent.com/36914098/210810881-3bae062d-fb80-4081-9457-10da85967a6d.png)

I just follow the code given. but it gives the failed results.. I don't know if I missed something. same results also in the documentation example here https://antblazor.com/en-US/components/upload

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by CyberryCJ** [comment]
based on antblazor documentation these are the results, same image file that I used in my project.
![image](https://user-images.githubusercontent.com/36914098/210905937-27382ebe-206a-4a8d-b548-4af07632d398.png)

**Comment by ElderJames** [comment]
Please try your own server.

**Comment by ElderJames** [comment]
No, this is using mocky.io, would limit the file size. Please change the url.

**Comment by CyberryCJ** [comment]
oh I see. Sorry I need to change the action.. 😅. Thank you! 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 7, 2023 at 11:35 AM, James ***@***.***> wrote:   


No, this is using mocky.io, would limit the file size. Please change the url.
