### ISSUE TITLE
NotificationService in NET MAUI Blazor App (WebView2) does not work!

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#2985]
### Describe the bug

I hope someone from the Ant team can find out why injected services (e.g. NotificationService) do not work under MAUI Blazor App? No error is triggered either. 

I suspect it has something to do with WebView2 Control (which runs a native Blazor app under MAUI)? 

Maybe it's a minor issue and it can be fixed with the next Ant update?

Currently, if you develop a desktop/mobile and web Blazor with Ant, you have to do without NotificationService for desktop/mobile apps, which is a shame. In addition, there is a small discrepancy in the view in comparison with the web app (Blazor Server).

Of course, this problem does not exist with Blazor Server.

**EDIT**

A workaround is to use Javascript ALERT function:

```
function MessageBox(message) {
    alert(message);
}  
```

This can then be used to display a dialogue box both in the native app (MAUI Blazor App) and in Balzor Server.

Note: We are talking about two apps that have a common code base. The special feature here is that Blazor is used and Ant's library can therefore be accessed. The result is a native application that can be run on Windows and Mac desktops, as well as on mobile devices like Android and iPhone, and what is even more important, you also have a web app (Blazor Server). Everything looks the same in the layout because you are using Ant, but the super advantage is that you only have one code base for all OS + web!

Now to underline the problem again: If you use the services of Ant in the first MAUI Blazor App project, they don't seem to work, but no error is triggered! Because the code base is the same for both native and web app, you get a problem that the messages are displayed in the web app, but not in the native environment (desktop, mombile).

### Steps to reproduce (please include code)
- Create NET MAUI Blazor App in Visual Studio 2022
- Try to use NotificationService Service

### Exceptions (if any)
nothing happens, there is no error message either

### Further technical details
- AntDesign Nuget Package version 0.13
- Visual Studio 2022 Version 17.4.2

**Comment by wdcossey** [comment]
I just tried it out in a (new) Blazor Hybrid app, seems to work just fine.

I can understand how this could happen as the [documentation](https://antblazor.com/en-US/docs/introduce) isn't updated to support Blazor Hybrid (some minor things need changing).

---

### Import Ant Design Blazor into an existing project
* Go to the project folder of the application and install the Nuget package reference

```text
$ dotnet add package AntDesign
```

* Register the services

```csharp
builder.Services.AddAntDesign();
```

* Link the static files in `wwwroot/index.html` (for Blazor Hybrid)

```html
<link href="_content/AntDesign/css/ant-design-blazor.css" rel="stylesheet" />
<script src="_content/AntDesign/js/ant-design-blazor.js"></script>
```

* Add namespace in `_Imports.razor`

```razor
@using AntDesign
```

* To display the pop-up component dynamically, you need to add the `<AntContainer />` component in `Main.razor` (for Blazor Hybrid).

```razor
<Router AppAssembly="@typeof(Main).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p role="alert">Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>

<AntContainer />   <-- add this component ✨
```


* Finally, it can be referenced in the `.razor' component!

```razor
@page "/notification"
@inject NotificationService _notice

<Button Type="@ButtonType.Primary" OnClick="@OnClick">
    Open the notification box
</Button>

@code {
    private async Task OnClick()
    {
        await _notice.Open(new NotificationConfig()
            {
                Message = "title",
                Description = "This is the content of the notification. This is the content of the notification. This is the content of the notification."
            });
    }
}
```

![image](https://user-images.githubusercontent.com/1089478/211161370-94d7bf06-d25e-403b-9de5-25e2916facd3.png)

**Comment by ElderJames** [comment]
@wdcossey Thank you for explain this, maybe we need to update the documentation. Would you be interested in helping?

I think we need to split the installation into three pages: Blazor Server, Blazor WebAssembly and Blazor Hybrid.

**Comment by wdcossey** [comment]
@ElderJames 

Sure, I don't mind helping out and updating the docs, it's only a few minor tweaks!

I'll get around to it this weekend and get a PR prepped.

**Comment by true-perfect-code** [comment]
Thank you very much !!!

I missed **< AntContainer / >**, that's why it didn't work!
I have now added **< AntContainer / >** and the message comes up in both the native and web app.

Have a nice day
