### ISSUE TITLE
the dimension of button will be changed automatically when click on it.

### ISSUE THREAD

**Issue by 1002527441** [ant-design-blazor/ant-design-blazor#299]
Here is source code:

<ButtonGroup>
    <Button Type="primary" Danger Icon="edit">
    </Button>
    <Button Type="primary"  Icon="delete">
    </Button>
</ButtonGroup>

**Comment by 1002527441** [comment]
<ButtonGroup>
    <Button Type="primary" Danger Icon="edit">
    </Button>
    <Button Type="primary"  Icon="delete">
    </Button>
</ButtonGroup>

**Comment by ElderJames** [comment]
Fixed via #300
