### ISSUE TITLE
Popconfirm cannot be correctly located in table

### ISSUE THREAD

**Issue by fordenuk** [ant-design-blazor/ant-design-blazor#3000]
When the table displays 100 pieces of data per page, the Popconfirm of the previous pieces of data can be located normally.
![image](https://user-images.githubusercontent.com/34673794/211267533-95545174-82b0-4727-910b-499d1d9a0c6a.png)

When the height exceeds 960px, Popconfirm will not be positioned correctly. When the page slides up and down, Popconfirm will restore correct positioning
![image](https://user-images.githubusercontent.com/34673794/211267770-b6fbefb8-e314-4b13-acb4-cf1af2f40ee2.png)
Code
![image](https://user-images.githubusercontent.com/34673794/211267908-12de9f9a-c2b8-42db-a449-1e15ed7c3b35.png)

**Comment by fordenuk** [comment]
Maybe I found the problem. 
When I clicked the previous part,Popconfirm positioning is correct. 
When clicking the text part, positioning is wrong
![image](https://user-images.githubusercontent.com/34673794/211273054-1ac65c28-93ea-4322-8fda-8ff6d7c41f8f.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @fordenuk . Please try the `Unbound` way to affix `Popconfirm`.

```razor
<Popconfirm Title="Are you sure delete this task?"
            OnConfirm="Confirm"
            OnCancel="Cancel"
            OkText="Yes"
            CancelText="No">
    <Unbound>
        <a @ref="@context.Current">Delete (unbound)</a>
    </Unbound>
</Popconfirm>
```

**Comment by ElderJames** [comment]
Hello @fordenuk , did you solved this issue?
