### ISSUE TITLE
Select component has wrong order when changing DataSource

### ISSUE THREAD

**Issue by tht245806497** [ant-design-blazor/ant-design-blazor#3021]
### Describe the bug

When changing the DataSource of a Select, the display order of options is inconsistent with the data source.

### Steps to reproduce (please include code)

Please see the demo code. 

### Screenshots

The first display is ok:
![image](https://user-images.githubusercontent.com/20590093/212896974-ed11e618-341c-4bb4-a521-3f0613ae00bb.png)

Switch data source, the first two options are in wrong order：
![image](https://user-images.githubusercontent.com/20590093/212897179-7e8911a6-21cc-46df-ae03-71b175a988db.png)

Switch the data source again, the options are displayed in reverse：
![image](https://user-images.githubusercontent.com/20590093/212897406-1e9155e9-7137-4bd3-a663-b39789c56be1.png)
![image](https://user-images.githubusercontent.com/20590093/212899959-4883ac12-8568-4de9-99b6-ea707c08c02f.png)

### Further technical details
- AntDesign Nuget Package version: 0.13.3
- TestDemo: 
[BlazorApp1.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/10434915/BlazorApp1.zip)

**Comment by ElderJames** [comment]
Thanks for contacting us @tht245806497 . We already know about this issue, so please set DataSource to null before switching for workaround.

```
@page "/"

<PageTitle>Index</PageTitle>

<RadioGroup TValue="bool" @bind-Value=isPersons1 ButtonStyle="@RadioButtonStyle.Solid" OnChange="OnChange">
    <Radio RadioButton Value=true>DataSource1</Radio>
    <Radio RadioButton Value=false>DataSource2</Radio>
</RadioGroup>

<Select TItem=Person
        TItemValue=int
        DataSource=dataSource
        LabelName=@nameof(Person.Label)
        ValueName=@nameof(Person.Id)
        Placeholder="Select a person"
        Style="width: 400px">
</Select>

@code
{
    record Person
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public bool NotAvailable { get; set; }
        public string Label => $"{Id}-{Name}";
    }

    List<Person> _persons1 = new List<Person> {
        new Person {Id = 1, Name = "Jack"},
        new Person {Id = 2, Name = "Lucy"},
        new Person {Id = 3, Name = "Yaoming"},
        new Person {Id = 4, Name = "Frieda"},
        new Person {Id = 5, Name = "Kathy", NotAvailable = true},
        new Person {Id = 6, Name = "Kate"},
        new Person {Id = 7, Name = "Eric"}
    };

    List<Person> _persons2 = new List<Person> {
        new Person {Id = 10, Name = "Jake", NotAvailable = true},
        new Person {Id = 11, Name = "Olaf"}
    };

    private bool isPersons1;

    List<Person> dataSource;

    async Task OnChange(bool choice)
    {
        dataSource = null;
        await Task.Yield();
        dataSource = choice ? _persons1 : _persons2;
    }
}


```

**Comment by tht245806497** [comment]
This solution is not 100% guaranteed to solve this problem. Problem sometimes still exists.
