### ISSUE TITLE
Table question - displaying, filtering, sorting and exporting on a server side

### ISSUE THREAD

**Issue by Martin-Pucalka** [ant-design-blazor/ant-design-blazor#3032]
I'd like to use Table component for displaying, filtering, sorting and exporting data from database. I need queries to be executed on a server. I think, exporting to file should be done on the server side as well. Now I see three ways:

1. Expose DbSet from DbContext directly do Table compoment, like it's mentioned here:
https://github.com/YongQuan-dotnet/AntTableSample.
\+ The fastest and simplest way
\- Exposing DbContext directly to views ins't the best practise, but I think, it could be accepted, if it was used only for this purpose.
\- Is the DbContext correctly disposed in that example?
\- How to achieve export? Get generated SQL query somehow and then remove OFFSET and FETCH part of query, to get all data?

2. Use OData. I've created a simple AntTable to OData adapter, which translates Ant QueryModel to OData query. Then the query is executed and the result is converted from JSON and then displayed in the Table.
\+ Not exposing DbContext to view
\- I need OData controller for each table
\- OData result is in JSON, which is a little bit verbose and converting it into csv is not very efficent, especially for large data
\- Limited by supported features in OData queries

3.  Use custom QueryModel to SQL query adapter.
\+ Not exposing DbContext to view
\+ Ability to add some extra features, for example fulltext search, wildcard characters, and so on.
\- Dealing with SQL injection

Could you give me any advice? What is the best approach or which one should I go with?

Thank you for your time.

**Comment by ElderJames** [comment]
Hello @Martin-Pucalka , I prefer to use the first and the third on server side, and use OData on WebAssembly.

If you like EF Core, the best practise is following the [official guide](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-7.0&WT.mc_id=DT-MVP-5003987) 

Or if you like raw SQL, you don't need to worry about sql injection on server side because it's not http request. The SQL is not apply from client side.

**Comment by Martin-Pucalka** [comment]
Thank you.

**Comment by ElderJames** [comment]
@Martin-Pucalka Wuold you like to contribute the OData adapter and SQL query adapter and more? I think that's what some people need.

**Comment by Martin-Pucalka** [comment]
I could contribute the OData adapter, which is already finished, it only needs some tests. I'm not sure if I'll be doing SQL query adapter, when I can use access to DbContext directly (method #1). This reminds me, how to all get rows for export (not only one page), or at least the generated SQL query, which I could modify for getting all rows (using method #1)?

Thanks.

**Comment by ElderJames** [comment]
What you said above is right, just remove the `Skip` and `Take` operators.

**Comment by ElderJames** [comment]
@Martin-Pucalka We also need the exporting, could you have any solutions？
