### ISSUE TITLE
Form fields freeze when inserting text quickly

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3036]
### Describe the bug

I have discovered a strange behavior with the form. If you have several fields and insert the values a little faster (e.g. via Control V), the form freezes and the cursor is trapped in an input field, so that you can't click on anything in the application.
If you insert the values a little slower, then everything works and the described error does not happen.

I can well imagine that there could be a workaround via API, but I have no idea with which form parameters you can eliminate this behavior?

I searched for "freeze" but could not find anything here. Can anyone reproduce this problem? 

Thanks

### Steps to reproduce (please include code)

```
<Form Model="@Data_DBconn" Size="small">
    <div class="calc-form-label">@_T_("k_server")</div>
    <FormItem>
        <Input @bind-Value="@context.DataServer" />
    </FormItem>
    <div class="calc-form-label">@_T_("k_db")</div>
    <FormItem>
        <Input @bind-Value="@context.DataDB" />
    </FormItem>
    <div class="calc-form-label">@_T_("k_dbuser")</div>
    <FormItem>
        <Input @bind-Value="@context.DataUser" />
    </FormItem>
    <div class="calc-form-label">@_T_("k_dbpasswort")</div>
    <FormItem>
        <InputPassword @bind-Value="@context.DataPassword" />
    </FormItem>
    <div class="calc-form-label">@_T_("k_encrypt")</div>
    <FormItem>
        <Switch CheckedChildren="@_T_("k_yes")" UnCheckedChildren="@_T_("k_no")" @bind-Value="@context.DataEncrypt" />
    </FormItem>
    <div class="calc-form-label">@_T_("k_trusted_connection")</div>
    <FormItem>
        <Switch CheckedChildren="@_T_("k_yes")" UnCheckedChildren="@_T_("k_no")" @bind-Value="@context.DataTrustedConnection" />
    </FormItem>

    <FormItem WrapperColOffset="8" WrapperColSpan="16">
        <Button Type="@ButtonType.Primary" OnClick="onClickNewConn">
            @_T_("k_save")
        </Button>
    </FormItem>
</Form>

@code{
    public class JsonConfigModel
    {
        public string DataServer { get; set; } = "";
        public string DataDB { get; set; } = "";
        public string DataUser { get; set; } = "";
        public string DataPassword { get; set; } = "";
        public bool DataEncrypt { get; set; } = false;
        public bool DataTrustedConnection { get; set; } = true;
    }

    JsonConfigModel Data_DBconn = new JsonConfigModel();

    protected void onClickNewConn()
    {

    }

    protected string _T_(string term)
    {
        //return Languages.GetLanguageTerm("de", term);
        return term;
    }
}
```

### Further technical details
- AntDesign Nuget Package version 0.13.2
- NET 7
- MAUI Blazor
- VS Community Version 17.4.4

**Comment by ElderJames** [comment]
Hello @true-perfect-code , could you please try to update AntDesign to 0.14.

**Comment by true-perfect-code** [comment]
Hi @ElderJames

I have tested this in version 14 and the problem still exists.

I describe here again a little more detailed what happens:
If you have several normal input fields (in my example I have 5 input fields plus password input) and you enter the values from one field to the other quickly, so that you click with the mouse on the first field and insert the value with Control V and continue to do this with other fields, then it happens sometimes already at the third input field that the cursor is caught in the field. You can get out of the field only if you use TAB. So you can fill the rest of the fields (RAB and then you enter something) and you can also get to the button (via TAB) and then press it with SPACE. 

However, the mouse can no longer be used in the application. It looks like it is disabled. As I see it, only the mouse is affected here. You can't click with the mouse on anything in the application as if the mouse is trapped in the field. The mouse is still trapped even if you move to other fields with TAB.

**Comment by ElderJames** [comment]
Thank you @true-perfect-code , could you please provide a reproduced demo?

**Comment by true-perfect-code** [comment]
@ElderJames 

I have tested this abnormal behaviour extensively in the last few hours.

I was able to find out that this problem only exists in MAUI. It doesn't necessarily have to do with Ant, because there was a big problem with the WebView component used to display web pages in MAUI (to learn more about WebView, please see https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-7.0&pivots=devices-android ).

I will see where best to report this behaviour by microsoft.

Once again, if you slowly copy the data into the input fields, everything works as expected. However, if you copy (or enter) the values faster, the mouse gets trapped and you can't do anything in the application.

I have created a GitHub project with which you can reproduce this behaviour. See: https://github.com/true-perfect-code/AntBugsMAUI.git

**It should be said that this problem is not present in Blazor Server applications! So everything indicates that it is due to this WebView component of MAUI.**

**Comment by true-perfect-code** [comment]
I am closing this post now because it is very probably a MAUI problem!
