### ISSUE TITLE
Drawer遮罩不随Drawer关闭

### ISSUE THREAD

**Issue by fan0217** [ant-design-blazor/ant-design-blazor#3045]
0.14.0版本： 单击Drawer的遮罩关闭Drawer时，遮罩并不随Drawer关闭，需要二次单击遮罩方可关闭。
`<Drawer Visible="@(_visible)" Placement="@("right")" Title="@("编辑")" OnClose="@(() => { _visible = false; })" Width="600">

</Drawer>

@code
{
    bool _visible = false;
}`

**Comment by mrjohnr** [comment]
same for me, it closes but background of the page revert to default after 2-3 seconds,behavior could be tested [on docs page](https://antblazor.com/en-US/components/drawer)

**Comment by true-perfect-code** [comment]
@ElderJames 
Is a preview version available so that we can install it?

Thanks
