### ISSUE TITLE
Form Post Method with Ant?

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3050]
If you want to make an authetification in Blazor Server (store a auth-cookie on the client), then you have to do it through a form, with which you send the data via method POST. On the other hand, you evaluate the user input via a controller and once you have verified the user credentials (check email and password in database on the server), then you can send an instruction from controller to client to save auth cookie.

In previous projects I used Microsoft template for authetification. The catch is that this is implemented via controller and razor views (.cshtml). 
In current project I want to implement login which is in blazor page. As a result, I want to implement this then with Ant components.

The question:
Is there any Ant component with which you can set the send method of the form data to POST? I have looked at the current form component of Ant, but have not found anything.

Thanks

**Comment by ElderJames** [comment]
Hello @true-perfect-code , do you mean synchronous submit? 

You need to know that  synchronous submit would directs it to an endpoint, not a blazor route, and refreshes the browser. For all blazor routes, it will be directed to _Host.cshtml.

**Comment by true-perfect-code** [comment]
Thanks @ElderJames
