### ISSUE TITLE
Drawer closing delay after 0.14.0 release

### ISSUE THREAD

**Issue by Kyojuro27** [ant-design-blazor/ant-design-blazor#3054]
**Describe the bug**

Hi ! I would like to point out a change of behavior for the Drawer component after the release of the version 0.14.0. You can try it on the demo, when you want to close a drawer, it took a second or two to have access to the initial page, sometimes we have to click on the page again to take back control.

It only works normally if we are using the drawer service.

**Further technical details**
AntDesign Nuget Package version: 0.14.0
Include the output of dotnet: .NET 6.0
The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual studio 2022 on Windows 11

**Comment by ElderJames** [comment]
Thanks for contacting us @Kyojuro27 , we maybe have fixed this issue in #3047. Please try 0.14.1.

**Comment by Kyojuro27** [comment]
Indeed, It works just fine with the release of the version 0.14.1.

Sorry for the disturbance and thank you for your reactivity ^^.

**Comment by ElderJames** [comment]
@Kyojuro27 You're welcome.
