### ISSUE TITLE
Drawer Container does not show HTML checkbox

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3055]
### Describe the bug
If you place an HTML checkbox in Drawer, the checkbox is not displayed. Outside of DRAWER, however, the checkbox is displayed. so, the problem does not come from Blazor, but from the Ant component Drawer.

The HTML elements such as label, inputxo or button work. I have not tested how it looks with other HTML controls.

![image](https://user-images.githubusercontent.com/45635963/216012954-e7eff372-e019-462f-9c92-16f4e5929b34.png)

Note:
The CHECKBOX Ant component, on the other hand, works. But the problem here is that it is a login window and I have to send the login data (user and password) to the server via POST. A controller is then called on the server, which then initiates the instruction to create a cookie on the client (provided the user login has been verified).

Since I also want to give the user the option of saving the cookie permanently (e.g. 30 days), I want to place a "remember me" checkbox on the login window. I was very surprised when this checkbox was not displayed. Of course it took me a long time to understand that this problem comes from the DRAWER component and not from me.

### Steps to reproduce (please include code)
Create Drawer and put HTML Checkbox inside

```
<div>
    <Drawer Closable="true" Visible="true" Placement="right" Title='("Basic Drawer")'>
        <form id="TestForm" action="test" method="post">
            <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
            <label for="vehicle1"> I have a bike</label><br>
            <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
            <label for="vehicle2"> I have a car</label><br>
            <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">
            <label for="vehicle3"> I have a boat</label><br><br>
            <input type="submit" value="Submit">
        </form>
    </Drawer>
</div>
```

### Further technical details
- AntDesign 0.14
- VS Version 17.4.4

**Comment by zxyao145** [comment]
@true-perfect-code  Sorry, the problem cannot be repeated, could you provide a demo?


![image](https://user-images.githubusercontent.com/24973084/216070927-0bb042f4-e949-4c88-944a-7028ebe5fe11.png)

**Comment by true-perfect-code** [comment]
@zxyao145 
That's very funny. In a new Blazor Server project as well as in a new MAUI Blazor project, I get also (like you) the checkboxes.!

In my old project (which I'm currently developing) I get the checkboxes on a new page but not on the page I'm currently using for display. The code is identical, but still the checkboxes are not displayed in the second page!?

I cannot explain this behaviour and will now close this post.
