### ISSUE TITLE
AntDesign.InputNumber @bind-Value to decimal property with Step = "@(1.0m)" crashes

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3066]
If I leave out `Step = "@(1.0m)" it works.

**Comment by ElderJames** [comment]
Hello @michaelcsikos , I can't reproduce the issue with following code.

```
<AntDesign.InputNumber Step="@(1.0m)" Min="-1" Max="5" @bind-Value="myValue" />

@code {
    private decimal myValue { get; set; }
}
```

**Comment by ElderJames** [comment]
Hello @michaelcsikos , could you reproduce this issue?

**Comment by michaelcsikos** [comment]
Hi @ElderJames, I can not reproduce this any more. I have added the `Step` back in to all my `decimal` edit controls.

**Comment by ElderJames** [comment]
That's great!
