### ISSUE TITLE
After dynamically modifying the RadioGroup item, reset the selection value and there is no default selection

### ISSUE THREAD

**Issue by SoaSoftNet** [ant-design-blazor/ant-design-blazor#3091]
After dynamically modifying the RadioGroup item, reset the selection value and there is no default selection

![image](https://user-images.githubusercontent.com/30250585/218303876-b4e8ce72-f244-4cd6-aecc-7ff1b44fe483.png)
save this item,no default selection

  List<string> ProductSpec = new List<string>() { "大杯", "中杯", "小杯" };
        string txtSpec = "中杯";
 int index = ProductSpec.IndexOf(txtSpec);
                ProductSpec[index] = _modelText;
                txtSpec = _modelText;

**Comment by ElderJames** [comment]
Please provide a demo.

**Comment by SoaSoftNet** [comment]
https://github.com/SoaSoftNet/AntBlazor142BugDemo     demo,thanks
