### ISSUE TITLE
Keydown event in Modal component leads to rerender of the whole content

### ISSUE THREAD

**Issue by bzashev** [ant-design-blazor/ant-design-blazor#3097]
### Describe the bug

If you have an <input/> in a <Modal/> component body, each key press / entered value leads to complete modal body rerendering - all child components. 
If the keydown event is tracked for the escape modal close - a quick possible solution is not to add the event listener on Keyboard=false property. Best solution is to prevent rerendering on keystrokes all keystrokes.

### Steps to reproduce (please include code)
Create a <Modal/> and a Custom Component with a single OnRender Console log.
In the modal body put a simple <input/> and your custom component. 

Test by opening the modal and start typing in the input. The Custom component is rerendered on each keystroke.

### Exceptions (if any)
No exceptions.
### Further technical details
- AntDesign Nuget Package version: 0.14.2
- The IDE (VS / VS Code/ VS4Mac):  2022 Window

**Comment by zxyao145** [comment]
@bzashev Hi, do you mean create a custom component like this?

```c# 
@code {
    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        Console.WriteLine("OnAfterRenderAsync");
        return base.OnAfterRenderAsync(firstRender);
    }
}
```

**Comment by bzashev** [comment]
Let me try to emulate it in a blank project

**Comment by bzashev** [comment]
So it is a strange situation so it is not exactly as I initially stated. Here is the setup to simulate:
1. Clone clean project - only ant and blazor there: https://github.com/bzashev/AntModalProblemTest 
2. Two situations -> setup outside of a Modal, setup inside of a modal (comment, uncomment)

What is observed:
-------------------
In the case of the two sibling components being outside of a modal, when I am typing in a simple input the sibling component "Test" is not rerendered (Sibling does not use the input's _test prop

When I have the same 2 component setup in an ant modal, the sibling component is rerendered on each keydown event, which seems without a reason for me as the binding of the input is the default onblur

When reviewed with Chrome Performance Tool - the rerender is presented as caused by an Event Listener for the keydown event. I assume the whole modal is rerendered on this event.

This situation is happening only if the sibling component TEST has a property and this property is an object. If the property is a primitive value, sibling is not rerendered. This also leads to a reference change probability.

Result
-------
In my case, this leads to a very very bad mobile experience for the user, which is improved when I start controlling the ShouldRender method.

Hope this helps

**Comment by zxyao145** [comment]
@bzashev Hi, I have found the reason. The Modal dialog listens to the onkeydown event. In the default configuration of blazer, the entire component will be re-rendered every time an event is triggered. I'll fix it later, thanks a lot!

**Comment by bzashev** [comment]
Thanks a lot!
