### ISSUE TITLE
Add support for quick search in table columns

### ISSUE THREAD

**Issue by LuukGlorie** [ant-design-blazor/ant-design-blazor#3109]
### Is your feature request related to a problem? Please describe.
Table filtering is not very user friendly when you are looking for a particular item, it involves clicking multiple buttons.

### Describe the solution you'd like
I would like the option to add a input field above a column to quickly search for that value. The type of input could be depend on the data type the column has, for example a boolean could be a select box.

![Quick search impression](https://user-images.githubusercontent.com/23555587/219071556-b74ec900-df57-4c80-aa38-a0420dbb57d8.png)

Another option to support this, is to enable for more header customization, for example being able to add two header rows. The current implementation does not make it possible to implement a custom solution for this feature.

**Comment by Abin-Liu** [comment]
Great idea

**Comment by ElderJames** [comment]
Thanks for suggestion @LuukGlorie , we won't implement this directly, but we can add generic features to support it. What problems did you encounter in the implementation?

**Comment by ElderJames** [comment]
@LuukGlorie Now you can use HeaderTemplate and `TableHeader` to customize the header row, please try.

https://antblazor.com/en-US/components/table#components-table-demo-grouping-columns
