### ISSUE TITLE
InputPassword keeps deleting text

### ISSUE THREAD

**Issue by alemoreirac-osf** [ant-design-blazor/ant-design-blazor#312]
Whenever I'm using 

`<InputPassword Placeholder="Senha" Size="@InputSize.Large"  @bind-Value="@usuario.Senha" OnPressEnter="Register" />`

After the third key pressed on the input field, it will delete the last key i typed.

I'm not really sure why, the Input seems normal

**Comment by TimChen44** [comment]
I didn't reproduce the problem you mentioned, can you describe the operation process and problem description in more detail, and tell me the version you are using, thank you
