### ISSUE TITLE
Can I integrate AntDesign into an ASP.NET Core Razor Project?

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [ant-design-blazor/ant-design-blazor#3127]
Hi,
I have an ASP.NET Core Razor project. Is it possible tp integrate AntDesign into this project and if yes, how?
Regards
Andreas

**Comment by ElderJames** [comment]
Thanks for contacting us @andreas-sommer-engenious , I thinks it's able to integrate blazor components by using `component` taghelper, hosted wasm or using blazor custom element. Please follow the documentation:

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0&WT.mc_id=DT-MVP-5003987

**Comment by ElderJames** [comment]
We are also going to fit the full stack blazor in .NET 8.
