### ISSUE TITLE
How pre-select rows automatically after table rendered using @bind-SelectedRows?

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3135]
### Describe the bug

You cannot preselect the rows in the table. This problem was reported last year:
https://github.com/ant-design-blazor/ant-design-blazor/issues/2282 

What is the status?

This selection function is really cool but not useful when preselection is not possible.

### Steps to reproduce (please include code)
Check please:

https://github.com/ant-design-blazor/ant-design-blazor/issues/2282

### Further technical details
- AntDesign Nuget Package version 14.2

**Comment by ElderJames** [comment]
Thank you @true-perfect-code , we have fixed this issue in latest 0.16.0.

**Comment by true-perfect-code** [comment]
Thanks a lot @ElderJames
