### ISSUE TITLE
Code cannot modify the value of the Input binding.

### ISSUE THREAD

**Issue by lsx1994** [ant-design-blazor/ant-design-blazor#3148]
code:
```
<div>
    <Input Style="width:150px" TValue="string"  @bind-value="@textInfo" />
    <Button OnClick="changeText">changeText</Button>
</div>

@code{
    string textInfo { get; set; } = "default";
    void changeText()
    {
        textInfo = "new data";
    }
}
```
After clicking the button, Input changes. 
But after I click Input , textInfo will be restored to "default".

**Comment by ElderJames** [comment]
Thanks for contacting us @lsx1994 , I test the code you provided in the lastest version, but it works well. May I ask which version you are using?

**Comment by lsx1994** [comment]
> Thanks for contacting us @lsx1994 , I test the code you provided in the lastest version, but it works well. May I ask which version you are using?

I also worked fine after updating to 0.13.1, which seemed to be the default version of the template before.
