### ISSUE TITLE
The closing animation effect of the drawer is lost in the latest version

### ISSUE THREAD

**Issue by SmRiley** [ant-design-blazor/ant-design-blazor#3149]
In the latest version, the closing animation effect of the drawer is lost, but it exists in the old version, and this problem exists in the current document

**Comment by zxyao145** [comment]
This is a known problem. The latest implementation method of antd-react animation has been adjusted, but the implementation of animation in blazor is not friendly, the style of antd-blazor drawer component and antd-reat are not completely synchronized, resulting in the loss of the antd-blazor drawer's animation.

**Comment by zxyao145** [comment]
Related to PR #3059
