### ISSUE TITLE
Table not supporting Dropdowns inside since 0.14

### ISSUE THREAD

**Issue by acpt** [ant-design-blazor/ant-design-blazor#3150]
Table not supporting Dropdowns inside since 0.14, dropdown gets transparent  and footer overlaps. Using 0.13 to avoid this problem

**Comment by ElderJames** [comment]
Thanks for contacting us @acpt , could you please provide a reproduced demo?

**Comment by ElderJames** [comment]
It’s fine currectly.
![image](https://github.com/user-attachments/assets/9aa521a5-649c-4db1-8224-9b797abe5e01)
