### ISSUE TITLE
Call the Button OnClick method generically?

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3155]
Is it possible to call the Button OnClick method generically?
I have tried the following, unfortunately nothing has worked:

`<Button Type="primary" OnClick="() => OnClick_Reload<CustomerModel>()" />`

`<Button Type="primary" OnClick="OnClick_Reload<CustomerModel>" />`

Thanks

**Comment by ElderJames** [comment]
Hello @true-perfect-code , I think this is an issue with the razor template, not with the Button component

**Comment by true-perfect-code** [comment]
Thanks @ElderJames
