### ISSUE TITLE
Tabs open animation causes Content to be lost

### ISSUE THREAD

**Issue by SmRiley** [ant-design-blazor/ant-design-blazor#3174]
### Describe the bug
In the current version, if the animation effect(Animated) is enabled on the tab, only the first item will be displayed, and the remaining items will not be visible after switching,There is this problem in the documentation:https://antblazor.com/zh-CN/components/tabs
![image](https://user-images.githubusercontent.com/45205313/224543702-cdfd7a18-0479-453b-9e4a-36c9a2546bc5.png)
![image](https://user-images.githubusercontent.com/45205313/224543710-e2690419-b3b5-4494-a01a-1e87a1d3c817.png)

**Comment by ElderJames** [comment]
@SmRiley I have noticed this issue, but we need a little time to fix the animation.
