### ISSUE TITLE
[Slider]: Tooltip position messed up in a Modal

### ISSUE THREAD

**Issue by Abin-Liu** [ant-design-blazor/ant-design-blazor#3176]
### Describe the bug

Tooltip position of a Slider will get messed up if the Slider is inside a Modal dialog.

### Steps to reproduce (please include code)
```
<Button OnClick="_ => _modalVisible = true">Show Modal</Button>

<Modal Title="Test Modal" Visible="_modalVisible" OnCancel="_ => _modalVisible = false">
    Position of Slider tooltip is messed up in a Modal.
    
    <div style="padding: 48px 20px">
        <Slider TValue="double" @bind-Value="_value" Min="0" Max="100" TooltipVisible />
    </div>    
</Modal>

@code {
    bool _modalVisible = false;
    double _value = 35;
}
```
![Slider_Tooltip](https://user-images.githubusercontent.com/32606124/225198006-7f81075e-f657-4d86-aedf-8b29564d7e7a.png)

### Further technical details
- AntDesign Nuget Package version: 0.14.4
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual studio 2022 Community

**Comment by Abin-Liu** [comment]
So, it seems like I'm the only one who ever got this problem?

**Comment by ElderJames** [comment]
Ok now.
![image](https://github.com/user-attachments/assets/7710ff22-29aa-4130-b87a-fe2595a8c26a)
