### ISSUE TITLE
AutoComplete Selected bind value not displayed. 

### ISSUE THREAD

**Issue by CyberryCJ** [ant-design-blazor/ant-design-blazor#3183]
I also tried on antblazor documentation, selected value not displayed in bind-value field. its working in previous version 14.3
![image](https://user-images.githubusercontent.com/36914098/225656466-b009d350-2293-4539-a933-5295202e34aa.png)

**Comment by michaelcsikos** [comment]
'AutoComplete' is broken. You can type into the input and it will correctly filter and match the item in the drop-down, but you can not click an item in the drop-down to select it. The drop-down remembers what you clicked but it doesn't bind to the input. See the following gif:
![Autocomplete](https://user-images.githubusercontent.com/21806535/236585250-c8047858-4746-4e48-ad1f-15632f33d369.gif)

**Comment by michaelcsikos** [comment]
@ElderJames Could you release this fix via NuGet, please?

**Comment by ElderJames** [comment]
hello @michaelcsikos, there are the latest pre-release on Nuget, and we will public the general release soon.
