### ISSUE TITLE
Slider does not work when page change!

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3184]
### Describe the bug

I have discovered a slider problem by coincidence and would be very thankful if someone could confirm it. I have also created a GitHub project about it:

Here is the explanation of the problem:
I created a new Blazor Server project and added Ant sliders to the index page. Now when I switch between pages (Index, Counter and Fetch data), the slider doesn't work anymore (the slider is frozen).

I first thinking it's a WebView2 issue again (recently fixed almost 4 month long bug in WebView2), but adding other Ant components under Slider on Index page, they still work without any problem when switching between pages.

So it may just be an Ant slider issue, but I would be very happy if someone could confirm this (see also my GitHub project).

Thanks

### Steps to reproduce (please include code)
Use github Project on: 
https://github.com/true-perfect-code/BlazorApp_AntSlider_Problem.git

### Further technical details
- AntDesign Nuget Package 14.4
- VS 2022 Version 17.5.2

**Comment by Abin-Liu** [comment]
I confirm this bug.

**Comment by CodeBloger** [comment]
I observe a similar problem, the slider does not work after switching to another page and back, or after dynamically deleting the block in which the slider was and re-displaying the block.

**Comment by true-perfect-code** [comment]
What about the slider? When can we expect the fix? Thanks

**Comment by true-perfect-code** [comment]
Thanks @ElderJames
