### ISSUE TITLE
 table ActionColumn Show/Hidden Bug

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design-blazor/ant-design-blazor#3192]
![ceff641e9751a0959b850390371ceda](https://user-images.githubusercontent.com/30250585/226839690-a17a41c5-aa2f-4ed6-a981-c55f9e3b338a.png)
![image](https://user-images.githubusercontent.com/30250585/226839895-62763507-cecc-446f-8f79-562c7787f1fd.png)
<ActionColumn Title="操作" Width="170" Hidden="txtShow"></ActionColumn>  txtShow Variable

**Comment by ElderJames** [comment]
track #4093
