### ISSUE TITLE
InputNumber up/down button click stuck in continuous loop

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3195]
We have noticed sometimes a single click on the up or down button for `InputNumber` can get stuck in a loop and it continues to increment the value. Moving the mouse away from the button sometimes stops, but in some cases it continues and there's no way to stop it. In our case, there is an `async` process happening in the background which can be triggered by the number value being changed.

The runaway behaviour is such a bad experience for the user that I would prefer to hide the up/down controls until the bug can be reproduced and fixed. Is there a way to hide the up/down?

**Comment by ElderJames** [comment]
Thanks for contacting us @michaelcsikos . I think we need to add a parameter to hide the button, or just use `Input` instead.

**Comment by true-perfect-code** [comment]
If InputNumber is on a drawer and you click on Down of InpoutNumber, the entire InputNumber control disappears from the drawer.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/45635963/fd174094-d745-4cfc-8f8d-1b64728f2771)

Regards
pc

**Comment by ElderJames** [comment]
It's fine.

![image](https://github.com/user-attachments/assets/50adc1f6-ca24-4d13-873f-7ee7f89ec715)

**Comment by michaelcsikos** [comment]
I would still like to be able to hide the up/down buttons.

**Comment by michaelcsikos** [comment]
Here is a sample project which reproduces the problem, and a screen recording.

[AntInputNumberTest.zip](https://github.com/user-attachments/files/20496221/AntInputNumberTest.zip)

https://github.com/user-attachments/assets/2b04831e-c904-4222-b3cc-2524630f8d7b
