### ISSUE TITLE
Switch don't turn gray when it's in "Close" location since version of 0.14

### ISSUE THREAD

**Issue by seanyu1** [ant-design-blazor/ant-design-blazor#3218]
### Describe the bug

After upgrade to 0.14, I found the Switch don't turn gray when it's in "OFF" position.

### Steps to reproduce (please include code)
.net version: 6.0

![image](https://user-images.githubusercontent.com/51482049/229975397-ef61fe5f-8df6-4b47-ac2d-81285610b98d.png)

code:
`
<Switch Style="background-color: #52c41a" @bind-Checked="isAuto" OnChange="(e) => ChangeAuto()" />
`

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thanks for contacting us @seanyu1 , this is because your style cover the backgound color both on checked & unchecked.

You can just cover the checked style like this:

```
<Switch @bind-Checked="isAuto" OnChange="(e) => ChangeAuto()" />

<style>
.ant-switch-checked {
    background-color: #52c41a
}
</style>
```
