### ISSUE TITLE
Both sites don't work correctly

### ISSUE THREAD

**Issue by PeskovV** [ant-design-blazor/ant-design-blazor#322]
Error on https://ant-design-blazor.github.io/ru-RU/docs/introduce : 

> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: Response status code does not indicate success: 404 (Not Found).
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
>   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () <0x255bbd0 + 0x00052> in <filename unknown>:0 
>   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T] (System.Threading.Tasks.Task`1[TResult] taskResponse, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x23d55f8 + 0x0012a> in <filename unknown>:0 
>   at AntDesign.Docs.Pages.Docs.SetDocUrl () <0x23d4050 + 0x00184> in <filename unknown>:0 
>   at AntDesign.Docs.Pages.Docs.OnInitializedAsync () <0x23c8c08 + 0x000c4> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x21889f0 + 0x00154> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x23479c8 + 0x000ca> in <filename unknown>:0 blazor.webassembly.js:1:37761

https://ant-design-blazor.github.io/ru-RU/docs/introduce has same error .
There is no way to see example
Browser: FireFox

**Comment by ElderJames** [comment]
Thank you for contacting us @PeskovV ,
We already know that there is a problem with documentation #159 
Please try: https://ant-design-blazor.github.io/en-US/docs/introduce first.

**Comment by PeskovV** [comment]
Hi, @ElderJames !
I updated issue and writed local, which has problem (ru-RU)

You're right, with en-US local there is no problem!
Thank you!

**Comment by ElderJames** [comment]
We apologize for the inconvenience, and will fix the problem as soon as possible.
You can track #159 to see progress.
