### ISSUE TITLE
When the Table component is reloaded (flipping or filtering), it is hoped that the previously selected rows can be retained (SelectedRows)

### ISSUE THREAD

**Issue by netty2019** [ant-design-blazor/ant-design-blazor#3220]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
When the Table component is reloaded (flipping or filtering), it is hoped that the previously selected rows can be retained (SelectedRows)

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

### Additional context
I tried to restore the selected row in the OnChange event, but it didn't work.
![image](https://user-images.githubusercontent.com/47128297/230274559-ff8cb1e3-2380-47d5-a589-774172cbdc05.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @netty2019 . This is a good suggestion. If you are interested, feel free to send a PR.😊

**Comment by ElderJames** [comment]
Hello @netty2019 ,after v0.16.0 you can restore the SelectedRows after reload.
