### ISSUE TITLE
How many developers are currently using the Ant-Blazor component?

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3222]
Does anyone from the Ant-Blazor team know how many developers are currently using the Ant-Blazor component for their own or professional app development?

Thanks

**Comment by ElderJames** [comment]
Hello @true-perfect-code . To be honest, it's hard to count the number of developers and company, we can only count the number of users from nuget downloads.

https://www.nuget.org/packages/AntDesign

**Comment by true-perfect-code** [comment]
Thanks @ElderJames, it never occurred to me to look there at Nuget Download.

Unfortunately, I have to say something here and I hope that no one will have trouble because of it.

I have the impression that Ant-Project loses some power and have the feeling that many questions remain unanswered (and mostly it's only you who writes something here).

For those who use Ant library for hobby projects it doesn't matter, but if you want to use Ant library in a professional project, you will slowly think twice before doing that (at least that's how I feel). Why? Simply because you need support, i.e. if my customer finds a bug in Ant, then I need a quick fix from Ant team!

If there are already so many downloads of the Ant component, then you could try to find out if there are still developers who have the same opinion (like me)?  If that should be the case, then it would be already at the time that Ant team thinks whether one could offer also a professional version beside the current Ant library!
This professional version should differ from the comnuity version in that the corrections and enhancements flow in preferentially. 

For the hobby developers, the community version would actually be the same as professional version or not, if you estimate that this would prevent the other developers from paying for the professional version (because they would ever get it for free via community version).

**For us professional developers it makes sense to pay something annually for the Ant component, because this would ensure the long-term life of the Ant library.**

If there is a fundamental request for an upgrade to a more payable version (for support purposes), then you could look at what people are willing to pay for it. My personal opinion is that 100 $ / year might be sufficient for the time being to organize a good team of 5-10 Ant programmers (assuming one would have between 1,000 and 2,000 users).

I would be very interested to know what others think about this (Ant-Team but also developers, who use Ant like me)?

Thanks

**Comment by Martin-Pucalka** [comment]
I agree with you. It's always better to have a project backed up by a team rather than a single developer, especially for professional usage. But making a paid version would bring it to competition with Radzen and other competitors.

**Comment by true-perfect-code** [comment]
Perhaps I have not explained it clearly. I don't mean that ANT should be turned into a paid version, but that it should be possible to guarantee support in the long term.

But this is only possible if there are people who are willing to commit their time to the project in the long term. And that is only possible if the time is paid for.

I also don't have the impression that ANT is only being developed by one programmer. On the other hand, I have the impression that the people who contribute come and go, and that is negative for the use of the ant component in a professional project.
