### ISSUE TITLE
Table: Whole dataset required to loaded when using virtual scrolling (EnableVirtualization)

### ISSUE THREAD

**Issue by JZO001** [ant-design-blazor/ant-design-blazor#3229]
Our team is using Table component to perform CRUD operations on a database table, which have more than 100.000 rows.

The following properties binded and used:
- Total
- ScrollY
- RemoteDataSource
- EnableVirtualization
- HidePagination
- bind-PageSize

OnChange event handler implemented to read the necessary content from the database.
The first event handler method (OnChange) call requires zero items, but needed the total number of items.
Than we should set the Total and PageSize values
Component fires a second call to the event handler (OnChange), its describes all the row required from the database table.

We tried many scenarios to feed the component with data, but if we do not load the whole DB table and provide it to the component, the component itself never try to read additional data.

We tried to decrease the PageSize property, the component renders the specified number of components, but when we scroll to the end, it does not display additional data and do not read more from database.

Looks like the virtual scrolling only works, if we allow for the control to read the whole DB table. Also we tried the examples from the documentation portal, but did not help. We do not like manual paging, the expected behavior is to load a set of data from database, for example 50 rows and than display this rows virtualized in the DOM. If we reach the end of the list, component read more data from the database and display it, but remove the previous entries from the DOM to avoid overloading it. Same as when we scroll up.

Any idea?

**Comment by ElderJames** [comment]
Thank you for contacting us @JZO001 , we'll add support for `ItemsProvider`.
