### ISSUE TITLE
Setting the ScrollBarWidth property on the Table component may cause header misalignment on Firefox browser

### ISSUE THREAD

**Issue by netty2019** [ant-design-blazor/ant-design-blazor#3236]
Setting the ScrollBarWidth property on the Table component may cause header misalignment on Firefox browser

![image](https://user-images.githubusercontent.com/47128297/233765096-e015482f-1d57-49c2-9833-d9571a411907.png)

![image](https://user-images.githubusercontent.com/47128297/233765123-d0f8f45f-fd95-485f-879f-b4ed1e8d2ada.png)

**Comment by ElderJames** [comment]
Thank you for contacting us @netty2019 , for now only Chrome/Edge support changing style of the scroll bar.

**Comment by ElderJames** [comment]
I will try adding `scrollbar-width` to the css and see if it works.
