### ISSUE TITLE
InputNumber  Max Value Input limit

### ISSUE THREAD

**Issue by SoaSoftNet** [ant-design-blazor/ant-design-blazor#3244]
![11cf4993660e8682adb0148de9e7a8a](https://user-images.githubusercontent.com/30250585/235280084-ce2909e9-292e-45ca-8d3c-bea4703ca4be.png)
The maximum value of InputNumber is 1, and I can just fill in a value greater than 1, so the maximum setting feels meaningless. This logic needs to be optimized

**Comment by berkerdong** [comment]
`<AntDesign.InputNumber Max="1"></AntDesign.InputNumber>`

你好 @SoaSoftNet ，我创建了一个空白页面用如上代码做了测试，并未重现你反馈的问题，输入大于 1的数字后，输入框失去焦点之后会立即重置为最大值 1

**Comment by SoaSoftNet** [comment]
我是把<AntDesign.InputNumber Max="1"></AntDesign.InputNumber> 放到Table 里的，要不你试下，如果还测试不出来。我来做个demo

**Comment by ElderJames** [comment]
@berkerdong 我测试过，在第一次是好的，第二次就不会重置为最大值。

**Comment by ElderJames** [comment]
I tried again, but I didn't find the issue.

**Comment by SoaSoftNet** [comment]
it‘s my fault
