### ISSUE TITLE
TreeSelect OnSelectedItemsChanged does not fire on deleting last element

### ISSUE THREAD

**Issue by SongPing** [ant-design-blazor/ant-design-blazor#3249]
The event handler OnSelectedItemsChanged from TreeSelect does not fire when the last element was deleted.
The event handler OnClearSelected is also only firing, when the delete-button was clicked.
So there is no possibility to detect, when there is no input.

**Comment by SongPing** [comment]
Any thoughts about this issue?

**Comment by ElderJames** [comment]
Hello @SongPing , we haven't check it out yet.
