### ISSUE TITLE
Mentions: Dynamic List Based On Entered Text

### ISSUE THREAD

**Issue by kooliokey** [ant-design-blazor/ant-design-blazor#3261]
### Is your feature request related to a problem? Please describe.
I am trying to use the mentions component to allow our users to search for another user by their name, show matching users, and mention them by selecting their name which would insert it into the text field. The dynamic part of this that shows users based on the entered text doesn't currently seem possible from what I can tell. I tried to use change events and re-renders to do this, but the component never re-renders the list.

### Describe the solution you'd like
Ideally it would behave like Select can with a datasource that our components can change to control the list displayed. In the short term I'd be open to just giving hooks and allowing the component to be re-rendered. 

### Additional context
I attempted to implement something similar to what Select has with its datasource, but there is a lot of code in Select that get confusing. Perhaps someone with more background in that component could implement it easier than I could.

**Comment by ElderJames** [comment]
Thank you @kooliokey , I think it's best to achieve the mentions independently. select has a lot of features of its own.

**Comment by kooliokey** [comment]
> Thank you @kooliokey , I think it's best to achieve the mentions independently. select has a lot of features of its own.

Ah yes I wasn't suggesting the select component should be used for it. I was only suggesting that similar functionality for dynamically setting the list exists there already.

**Comment by ElderJames** [comment]
Hello @kooliokey , would you like to send a PR for that?
