### ISSUE TITLE
Modal set class , Id

### ISSUE THREAD

**Issue by Temuujin89Smart** [ant-design-blazor/ant-design-blazor#3263]
Hello,
Why is the modal id and class not set? for example: Id is "MyModal1" and  class is "DD"

    <Modal Title="@("Modal1")"
       Visible="@IsShowButton1"
       Class="DD"
       Id="MyModal1"
       Width="800"
       Draggable="true"
       Centered="true"
       Footer="null"
       Maximizable="true"
       OnCancel="@ModalCancel">
        <ModalForm1></ModalForm1>
    </Modal>
}

**Comment by zxyao145** [comment]
@Temuujin89Smart hi, Can WrapClassName meet your needs? At the beginning of Modal design, AntDomComponentBase did not yet have a class and id paramter.
