### ISSUE TITLE
Dropdown does not close automatically after clicking

### ISSUE THREAD

**Issue by XueDee123** [ant-design-blazor/ant-design-blazor#3267]
### Describe the bug

我需要通过Dropdown下拉菜单里的按钮触发Drawer，我在使用0.14.4版本时发现，当第一次点击Dropdown里的按钮1时，Drawer正常显示Dropdown也在意料之中自动关闭，这时我继续点击Dropdown里的按钮1时，Drawer正常显示但是Dropdown并没有自动消失，需要移动鼠标出Dropdown范围之外后才自动消失。我尝试设置Dropdown里menu的Selectable为false后，不论是第一次还是第二次点击，在Drawer显示后Dropdown在不移动鼠标的情况下是不会自动消失的。我尝试把antblazor版本更新为0.15.0-alpha.3，在Dropdown里menu的Selectable为true时，Dropdown可以在点击按钮后自动消失，但是如果我设置Dropdown里menu的Selectable为false后，问题依然存在

### Steps to reproduce (please include code)

<Dropdown Placement="@Placement.Bottom">
    <Overlay>
        <Menu Selectable="false">
            <MenuItem >
                <span style="color:rgb(24,144,255);">
                    <Icon Style="font-size:16px;" Type="user-switch"></Icon>
                    <span> 分配角色</span>
                </span>
            </MenuItem>
            <MenuItem OnClick="()=>_drawer=true">
                <span style="color:rgb(24,144,255);">
                    <Icon Style="font-size:16px;" Type="edit"></Icon>
                    <span>修改</span>
                </span>
            </MenuItem>
            <MenuItem >
                <span style="color:rgb(255,77,79);">
                    <Icon Style="font-size:16px;" Type="delete" />
                    <span>删除</span>
                </span>
            </MenuItem>
        </Menu>
    </Overlay>
    <ChildContent>
        <div Class="d-flex justify-center align-center">
            <div style="color:rgb(24,144,255);">更多</div>
            <div style="padding-left:10px;color:rgb(24,144,255)"><Icon Type="down" /></div>
        </div>
    </ChildContent>
</Dropdown>

<Drawer Visible="@_drawer" Placement="right" Closable="false" MaskClosable="false" Width="250">
    <Template Style="height:90%">
        <GridRow>
            <GridCol Span="12" Class="d-flex justify-center">
                <Button Type="primary">修改</Button>
            </GridCol>
            <GridCol Span="12" Class="d-flex justify-center">
                <Button Type="default" OnClick="()=>_drawer=false">返回</Button>
            </GridCol>
        </GridRow>
    </Template>
</Drawer>

### Further technical details
- AntDesign 0.14.4  Blazor版本Net7

**Comment by ElderJames** [comment]
Thanks for contecting us, please peovide a reproduce demo?
