### ISSUE TITLE
table empty data loading style show not good

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design-blazor/ant-design-blazor#3273]
![8decaf47e5b03b55058ca275ec86b87](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/8b15839e-431e-4008-bcce-e71d8e566084)
When the empty data is loaded, the table empty data picture and text are displayed on the far left and then in the middle.
video: https://github.com/SoaSoftNet/BugFiles/blob/main/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B6%202023-05-25%20143859.mp4

**Comment by Nadellz** [comment]
Same here , ant design table's default empty component is displayed in a column 
<img width="668" alt="Capture" src="https://github.com/ant-design-blazor/ant-design-blazor/assets/76868678/61f204b4-3aca-4d1b-a687-d0c6158f27e0">
