### ISSUE TITLE
FilterDropdown property like the React version

### ISSUE THREAD

**Issue by manuelelucchi** [ant-design-blazor/ant-design-blazor#3283]
The react version has a FilterDropdown option for customizability in the Column header for the table (like [here](https://ant.design/components/table#components-table-demo-custom-filter-panel))
It's a feature that has been requested multiple times (Eg #3019) and it's available on the React version, plus it should be fairly easy to implement

**Comment by ElderJames** [comment]
Thanks for contacing us @manuelelucchi , this is a great feature. If you are interested, feel free to send a PR.😊
