### ISSUE TITLE
 The HashCode of DataSource has not changed whenselecting and deleting all

### ISSUE THREAD

**Issue by XueDee123** [ant-design-blazor/ant-design-blazor#3284]
### Describe the bug

我在使用table时，当我全选数据后，执行删除操作，我将通过对话框的方式确认数据是否删除，当点击对话框的确认按钮后，数据是真实的删除了，但是神奇的是table居然没有变化（我在执行完删除操作后进行了查询处理）

### 复现代码
```
@page "/"
@using AntDesign.TableModels;

<div>
    <Button OnClick="Delete">删除</Button>
    <Button OnClick="Delete1">删除1</Button>
    <Button OnClick="Add">新增</Button>

    <Table 
           TItem="Column"
           DataSource="@_vmTableModel.Source"
           @bind-SelectedRows="_vmTableModel.Selected"
           RenderMode="RenderMode.ParametersHashCodeChanged"
           OnChange="@OnDataChange"
           Loading=@(_vmTableModel.Source==null)
           Size="TableSize.Small"
           HidePagination
           EnableVirtualization
           ScrollY="calc(100vh-200px)"
           ScrollX="1200"
           Bordered>
        <Selection Key="@context.Name"  />
        <PropertyColumn Property="c=>c.Name">
            <a>@context.Name</a>
        </PropertyColumn>
        <PropertyColumn Property="c=>c.Age" />
        <PropertyColumn Property="c=>c.Address" />
    </Table>
</div>

<Modal Title="@("删除提示")"
       Draggable="true"
       Visible="@_delModal.Visible"
       OnOk="@DeleteHandleOk"
       OnCancel="@CloseModal"
       ConfirmLoading="@_delModal.Loading">
    <p>是否删除选中的数据</p>
</Modal>
@code {
    public class ModalModel
    {
        public bool Visible { get; set; }
        public bool Loading { get; set; }
    }
    private ModalModel _delModal = new ModalModel();
    private TableModel<Column> _vmTableModel = new(null, null);
    protected void CloseModal(MouseEventArgs e)
    {
        _delModal.Visible = false;
    }
    protected async Task DeleteHandleOk(MouseEventArgs e)
    {
        _delModal.Loading = true;
        var keys = _vmTableModel.Selected.Select(b => b.Name).ToList();
        data.Where(b => keys.Contains(b.Name)).ToList().ForEach(b => data.Remove(b));
        _vmTableModel.Source = null;
        _vmTableModel.Source = data;
        _delModal.Visible = false;
        _delModal.Loading = false;

    }
    ITable table;
    public class TableModel<T>
    {
        public TableModel(List<T>? source, IEnumerable<T>? selected)
        {
            Source = source;
            Selected = selected;
        }

        public List<T>? Source { get; set; }

        public IEnumerable<T>? Selected { get; set; }
    }
    class Column
    {

        public string Name { get; set; }

        public int Age { get; set; }

        public string Address { get; set; }
    }

    public void Delete()
    {
        _delModal.Visible = true;
    }
    public void Delete1()
    {
        var keys = _vmTableModel.Selected.Select(b => b.Name).ToList();
        data.Where(b => keys.Contains(b.Name)).ToList().ForEach(b => data.Remove(b));
        _vmTableModel.Source = null;
        _vmTableModel.Source = data;
    }
    public void Add()
    {
        _vmTableModel.Source = null;
        data.Add(new Column
            {
                Name = Guid.NewGuid().ToString(),
                Age = 1
            });
        _vmTableModel.Source = data;
    }
    List<Column> data =new()
    {
        new Column()
        {
            Name = "John Brown",
            Age = 32,
            Address = "New York No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Jim Green",
            Age = 42,
            Address = "London No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Joe Black",
            Age = 32,
            Address = "Sidney No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Disabled User",
            Age = 99,
            Address = "Sidney No. 1 Lake Park",
        }
    };

    string selectionType = "checkbox";
    void OnDataChange(QueryModel<Column> query)
    {
        _vmTableModel.Source = data;
    }
   
}

```

### Further technical details
- AntDesign 版本0.15.0

**Comment by zxyao145** [comment]
@XueDee123 Hi, is `DeleteHandleOk` triggered after clicking the OK button? and please confirm `_vmTableModel.Source` has been updated.

**Comment by XueDee123** [comment]
> @XueDee123 Hi, is `DeleteHandleOk` triggered after clicking the OK button? and please confirm `_vmTableModel.Source` has been updated.

Hi, I have prepared two delete buttons in the above demo, respectively delete operation after pop-up prompt and delete operation directly. The delete operation itself is no problem, and the data source is also correct. When calling pop-up delete, if not all are selected, the table display is ok, but if you select all and then call pop-up delete, then the data source is cleared. The table does not refresh.

**Comment by zxyao145** [comment]
@XueDee123 
hi, I debugged the program and found that it is very interesting that this issue only occurs when selecting and deleting all,  then I found that the Table has rewritten 'ShouldRender', and you set `RenderMode='RenderMode. ParametersHashCodeChanged'`, but the HashCode of `DataSource` has not changed, so the Table's re-rendering is blocked.

The **solution** to this problem is set `RenderMode='RenderMode.Always'`. Perhaps there are other better solutions, but I haven't found them.


@ElderJames 
In principle, resetting `_ VmTableModel=new (data, null)` each timewill also cause the hash to change, but it's not, please pay attention to this issue.

**Comment by XueDee123** [comment]
> @XueDee123 hi, I debugged the program and found that it is very interesting that this issue only occurs when selecting and deleting all, then I found that the Table has rewritten 'ShouldRender', and you set `RenderMode='RenderMode. ParametersHashCodeChanged'`, but the HashCode of `DataSource` has not changed, so the Table's re-rendering is blocked.
> 
> The **solution** to this problem is set `RenderMode='RenderMode.Always'`. Perhaps there are other better solutions, but I haven't found them.
> 
> @ElderJames In principle, resetting `_ VmTableModel=new (data, null)` each time will also cause the hash to change, but it's not, please pay attention to this issue.

Setting `RenderMode=' rendermode. Always'` causes other problems when there are too many columns or when ScrollX is set to make the page very stuck, I tried many ways but none set `RenderMode = 'RenderMode. ParametersHashCodeChanged'` effect is good, it makes me very uncomfortable

**Comment by zxyao145** [comment]
> > @XueDee123 hi, I debugged the program and found that it is very interesting that this issue only occurs when selecting and deleting all, then I found that the Table has rewritten 'ShouldRender', and you set `RenderMode='RenderMode. ParametersHashCodeChanged'`, but the HashCode of `DataSource` has not changed, so the Table's re-rendering is blocked. 你好，我调试了程序，发现这个问题很有意思，只有全选和全部删除的时候才会出现这个问题，然后发现Table改写了'ShouldRender'，而你设置的是 `RenderMode='RenderMode. ParametersHashCodeChanged'` ，但是 `DataSource` 的HashCode没有改变，所以 Table 的重新渲染被阻止了。
> > The **solution** to this problem is set `RenderMode='RenderMode.Always'`. Perhaps there are other better solutions, but I haven't found them.这个问题的解决方案是设置 `RenderMode='RenderMode.Always'` 。也许还有其他更好的解决方案，但我还没有找到。
> > @ElderJames In principle, resetting `_ VmTableModel=new (data, null)` each time will also cause the hash to change, but it's not, please pay attention to this issue. 原则上每次重新设置 `_ VmTableModel=new (data, null)` 也会导致hash改变，其实不然，请注意这个问题。
> 
> Setting `RenderMode=' rendermode. Always'` causes other problems when there are too many columns or when ScrollX is set to make the page very stuck, I tried many ways but none set `RenderMode = 'RenderMode. ParametersHashCodeChanged'` effect is good, it makes me very uncomfortable设置 `RenderMode=' rendermode. Always'` 会导致其他问题，当列数太多或者设置ScrollX时页面很卡，我试了很多办法都没有设置 `RenderMode = 'RenderMode. ParametersHashCodeChanged'` 效果好，让我很不舒服

@ElderJames  Table has an internal method 'Refresh', perhaps a similar public 'ForceRender' method should be added for all components, and this allows developers to force component re-rendering.

**Comment by ElderJames** [comment]
@XueDee123 For now, please call `_table.ReloadData` for workaround.

```diff
    protected async Task DeleteHandleOk(MouseEventArgs e)
    {
        _delModal.Loading = true;
        var keys = _vmTableModel.Selected.Select(b => b.Name).ToList();
        data.Where(b => keys.Contains(b.Name)).ToList().ForEach(b => data.Remove(b));
        _vmTableModel.Source = null;
        _vmTableModel.Source = data;
        _delModal.Visible = false;
        _delModal.Loading = false;
+       _table.ReloadData();
    }
```
