### ISSUE TITLE
Cannot read properties of null (reading 'offsetHeight') on Dropdown

### ISSUE THREAD

**Issue by PaulEsprit** [ant-design-blazor/ant-design-blazor#3294]
I got error using Dropdown with menu items. If I click on dropdown icon i gets error Cannot read properties of null (reading 'offsetHeight') on this code 
{
            key: "calculateScrollBarSizes",
            value: function() {
                this.isContainerBody ? this.scrollbarSize = {
                    horizontalHeight: window.innerHeight - document.documentElement.clientHeight,
                    verticalWidth: window.innerWidth - document.documentElement.clientWidth
                } : this.scrollbarSize = {
                    horizontalHeight: this.container.offsetHeight - this.container.clientHeight,
                    verticalWidth: this.container.offsetWidth - this.container.clientWidth
                }
            }
I use Trigger="@(new Trigger[] { Trigger.Click })"

**Comment by ElderJames** [comment]
Thanks for contracing us @PaulEsprit , are you meaning the dropdown of SubMenu or add a dropdown at Menu of your own?

**Comment by PaulEsprit** [comment]
Its happened in my Menu code which is like that. In other  places its worked but in one place its throw error.
<Dropdown @ref="@contactsActionsDropdown" Trigger="@(new Trigger[] { Trigger.Click })" PopupContainerSelector="@("#id"+ContactsList.IndexOf(context))" Placement="@Placement.BottomLeft">
                                        <Overlay>
                                            <Menu Selectable=false AutoCloseDropdown="@true">
                                            <MenuItem OnClick=@(() => { CloseDropdownAferClick(contactsActionDropdownList); EditContact(context); })>
                                                    <RadzenImage Path="icons/edit.svg" class="menu-icon" />
                                                    Edit
                                            </MenuItem>

**Comment by ElderJames** [comment]
Hello @PaulEsprit , please submit the complete code so that we can reproduce your issue.

**Comment by ElderJames** [comment]
Hello @PaulEsprit , I find that this is because the element spectific with `PopupContainerSelector` wasn't found. Please make sure you are setting a correct selecter.
