### ISSUE TITLE
ModalService, component return Value ?

### ISSUE THREAD

**Issue by Temuujin89Smart** [ant-design-blazor/ant-design-blazor#3296]
i want to get ReturnValue  from ModalFormTest1 component? Do I have to use ref ? give me available sample

  ====>1 1.TestListForm
  <Button OnClick="@OpenModal1">Open Modal1</Button>
@code{
    string TestName ="OnoosonNer";
    private async void OpenModal1()
    {
          var modalConfig1 = new ModalOptions
                    {
                        Title = "Test",
                        OkText = "Ok",
                        CancelText = "Cancel",
                        //OnCancel = OnCancelMethod1,
                       // AfterClose = () => AfterCloseMethod1(myReturnValue),
                  Content = @<ModalFormTest1 Name="@TestName " ></ModalFormTest1>
            };

        await _modalService.CreateModalAsync(modalConfig1);
    }
}

====>2.ModalFormTest1 component.
    <h3>ModalFormTest</h3>
<h1>My Name is:</h1>@Name

@code {

    [Parameter]
    public string Name { get; set; }
    public string ReturnValue { get; set; } = "OKAy";
}

**Comment by ElderJames** [comment]
Thanks for contacting us @Temuujin89Smart Please see the Confirm demo.
https://antblazor.com/components/modal#components-modal-demo-modal_service_for_confirm
