### ISSUE TITLE
The Search input is out of scope on the right side of the PageHeader

### ISSUE THREAD

**Issue by junjian-yuan** [ant-design-blazor/ant-design-blazor#3304]
The Search input is out of scope on the right side of the PageHeader.
The Search is in PageHeaderExtra.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/10084420/f19b0993-ce36-440f-9eda-d30d77032f2d)

TestLayout.razor
```
@inherits LayoutComponentBase

@Body
```

Test.razor
```
@page "/Test"
@layout TestLayout

<PageHeader BackIcon="@false" Ghost="false">
    <PageHeaderTitle>Tenants</PageHeaderTitle>
    <PageHeaderExtra >
        <Search Placeholder="input search text" Size="@InputSize.Large" EnterButton="@("Search")" />
        <Button Type="primary">
            AddNew
        </Button>
    </PageHeaderExtra>
</PageHeader>
```

VSCODE / VS2022
```
<PackageReference` Include="AntDesign" Version="0.15.0" />
```

Browser: Chrome 114.0.5735.110

**Comment by ElderJames** [comment]
Thanks for contacting us @junjian-yuan , I think this is an style issue and you can fixed it by change the css. What are your expectations?

**Comment by junjian-yuan** [comment]
I wish the two components could be used together without extra processing.  
I'm not very good at css and tried several ways to solve the problem.  Can CSS provide a solution?

 Thank you!
