### ISSUE TITLE
Drawer: Class ant-scrolling-effect Problem with overflow: hidden;

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3315]
If you place a button on the drawer that calls up any page (e.g. via **NavigationManager.NavigateTo("MyPage");** )
then the body of the calling HTML page loses the scroll bar. This happens by using the class **ant-scrolling-effect** in Drawer and property **overflow: hidden,** which is then no longer reset after closing Drawer.

The workaround is to reload the page, for example, with the call:
`NavigationManager.NavigateTo("MyPage", true); `

The problem is, that all session variables are lost by using this workaround (e.g. if you have defined them via **builder.Services.AddScoped** Service.

Regards
perfect-code

**Comment by zxyao145** [comment]
@true-perfect-code hi, I'm sorry for this issue, but a temporary solution is as follows, call `JSInteropConstants.enableBodyScroll` yourself

```c#
[Inject]
private NavigationManager NavigationManager { get; set; }

protected override void OnInitialized()
{
	NavigationManager.LocationChanged += NavigationManager_LocationChanged;
}


private async void NavigationManager_LocationChanged(object sender, Microsoft.AspNetCore.Components.Routing.LocationChangedEventArgs e)
{
	Console.WriteLine("NavigationManager_LocationChanged");
	await JsInvokeAsync(JSInteropConstants.EnableBodyScroll);
}
```

**Comment by true-perfect-code** [comment]
@zxyao145 Thanks for temporary solution.

**Comment by true-perfect-code** [comment]
@ElderJames 
Has this update been released? I have installed the latest version 16.1, but I still have the problem.

I use Drawer as a component and the link calls CallBack function

Thanks
pc

**Comment by ElderJames** [comment]
Maybe the NavigationManager still not be disposed in time.

**Comment by true-perfect-code** [comment]
In the case that someone has a component on the drawer with the button that navigates to another page, for example:

Component
```
<Button OnClick="_OnClick_Page">Go to page</Button>

    private void _OnClick_Page()
    {
        OnClick_Page.InvokeAsync();
    }
```

Then it may be that the scroll bar "disappears" (as already described in the article).

**My workaround is the following:**
I eliminated component and moved it to the drawer. This eliminated the button an my problem with scrollbar. 
I still had links to other pages in the component, but these are solved via standard HTML links and seem to work without any problems.
