### ISSUE TITLE
The InputReadOnly attribute of the <DatePicker> component does not work. 

### ISSUE THREAD

**Issue by 22140505** [ant-design-blazor/ant-design-blazor#3317]
The InputReadOnly attribute of the <DatePicker> component does not work. Also, I don't understand what the document means by "avoid opening the virtual keyboard on mobile devices". Isn't this component not supported on mobile devices?

**Comment by ElderJames** [comment]
Thank you for contacting us @22140505 , the parameter `InputReadOnly` works well. This parameter is used to make the input box of DatePicker readonly, and user can't input the date string by the keyboard. This does not mean that mobile devices are not supported, but rather that adaptations are made for mobile devices.
