### ISSUE TITLE
When i use Tabs in a Card, TabPosition is not work

### ISSUE THREAD

**Issue by muxveliu** [ant-design-blazor/ant-design-blazor#3325]
When i use Tabs in a Card, TabPosition is not work,this is my code,the tabposition is always at the bottom

<Card Title="basics">
    <Tabs TabPosition="@TabPosition.Top">
        <TabPane Tab="Tab 1" Key="1">
            Content of Tab Pane 1
        </TabPane>
        <TabPane Tab="Tab 2" Key="2">
            Content of Tab Pane 2
        </TabPane>
        <TabPane Tab="Tab 3" Key="3">
            Content of Tab Pane 3
        </TabPane>
    </Tabs>
</Card>

**Comment by muxveliu** [comment]
<Card Title="basics">
    <Tabs TabPosition="@TabPosition.Top">
        <TabPane Tab="Tab 1" Key="1">
            Content of Tab Pane 1
        </TabPane>
        <TabPane Tab="Tab 2" Key="2">
            Content of Tab Pane 2
        </TabPane>
        <TabPane Tab="Tab 3" Key="3">
            Content of Tab Pane 3
        </TabPane>
    </Tabs>
</Card>

**Comment by muxveliu** [comment]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/39698382/0ec379c1-37c2-48c8-ad34-6cf486515e1a)

**Comment by ElderJames** [comment]
Thanks for contacting us @muxveliu , are you using the card with tabs?
https://antblazor.com/en-US/components/card#components-card-demo-Tabs1

**Comment by rstreit** [comment]
How to use a TabPane inside a Body Card?
This is not working:

```
 <Card Title=@("Card title")>
   <Extra>
      <a>More</a>
   </Extra>
   <Body>
      <p>Some content, like a form</p>
      <Tabs>
         <TabPane Tab="Tab 1" Key="1">
            Content of Tab Pane 1
         </TabPane>
         <TabPane Tab="Tab 2" Key="2">
            Content of Tab Pane 2
         </TabPane>
         <TabPane Tab="Tab 3" Key="3">
            Content of Tab Pane 3
         </TabPane>
      </Tabs>
      <p>More content like form buttons</p>
   </Body>
</Card>
```

**Comment by ElderJames** [comment]
Thanks for contacting us  @rstreit ,please try to use CardTabs render fargment.
