### ISSUE TITLE
Why ICONs are not vertically aligned with text?

### ISSUE THREAD

**Issue by SilverLight1980** [ant-design-blazor/ant-design-blazor#3346]
### Describe the bug

I have a question : I have copied the **Breadcrumb** sample code from https://antblazor.com/en-US/components/breadcrumb in VS, but in contrast to original sample code and its visual appearance, **the ICONs in breadcrumb are not vertically aligned with the text in VS**. 
I also have have the same problem (**ICON is not vertically aligned with Text**) with other components like Menu in my code in VS.**(although I don't see this problem in online sample codes)**
Please help me what I should do to overcome the problem? (whats's wrong with my code or what should I add to my code?)
### Steps to reproduce (please include code)

**Original Code from your site and its result (Icon is vertically aligned with Text):**
```
<Breadcrumb>
	<BreadcrumbItem Href="">
		<Icon Type="home" />
	</BreadcrumbItem>
	<BreadcrumbItem Href="">
		<Icon Type="user" />
		<span>Application List</span>
	</BreadcrumbItem>
	<BreadcrumbItem>
		Application
	</BreadcrumbItem>
</Breadcrumb>
```
![breadcrumb-ok](https://github.com/ant-design-blazor/ant-design-blazor/assets/138711070/6a1052ed-52f5-466f-ac22-4b17bd534672)

**The Result from the same code in VS :**
![breadcrumb-Nok](https://github.com/ant-design-blazor/ant-design-blazor/assets/138711070/7d9d5bee-a06d-483c-b258-ccfca1fd989e)

### Further technical details
- AntDesign Nuget Package version : 0.15.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thanks for contacting us @SilverLight1980 , are you using bootstarp? The icon style would be conver by bootstrap.

**Comment by SilverLight1980** [comment]
Thank you for your kind and quick reply.
yes, the problem stems from **Bootstrap** : __I removed the Bootstarp from my code and the problem was solved__.
but **does it mean that I can not use your Components and Bootstrap styles (like btn-danger , alert-info  and etc ...) together?**
(I mean is there any way to have Bootstrap and your Product(Components) in the same project without problems like one mentioned above?)
Thank you.

**Comment by ElderJames** [comment]
Of course you can use them at the same time, but you need to solve the style conflict.

**Comment by SilverLight1980** [comment]
In fact I couldn't find the root cause of **Conflict between Bootstrap and AntDesignBlazor ICON** (**ICON component is not aligned with TEXT inside Breadcrumb**). moreover there was no result from Google search.
I would be gratefull if you could tell me about a solution or workaround about this problem.

**Comment by ElderJames** [comment]
Sure, now you have found the problem, just feel free to send a PR.
