### ISSUE TITLE
🎉Who is using Ant Design Blazor in production? 👩🏻‍💻

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#335]
We appreciate your support if you or your organization is using Ant Design Blazor. You are welcome to leave replies about your product and organization here, which could became the confidence of maintiners, communication and undecided watchers.

Recommended reply format:

```
- Product：
- Company or Organization: (if any)
- Link: (if any)
- Screenshot: (if any)
```

**Comment by StardustDL** [comment]
I'm writing a blog system based on Blazor these days, have tried some component libraries, and finally selected Ant Design Blazor.

- Product: [AcBlog](https://github.com/acblog/acblog)
- Online demo: 
  - [GitHub](https://acblog.github.io/)
  - [Gitee](https://acblog.gitee.io/)

Thank you for maintaining this project. Looking forward to the final release.

**Comment by yuanxiongwei** [comment]
starup Company , e-commerce proejct. use ant design blazor. blazor server side coding
Product: mall manage project 
Screenshot: coming soon

**Comment by ske66** [comment]
Product: Aviagen Data Manager
Company: Aviagen Ltd
Link: unfortunately not available past the VPN
![DataManager](https://user-images.githubusercontent.com/26600892/87009357-f6fcda80-c1bc-11ea-87ad-c27720d9cef2.png)

**Comment by aaasoft** [comment]
Product：Data collect gateway
Company or Organization: 弈力科技
Link: http://www.willservice.net/
Screenshot: 
![QQ截图20200710111917](https://user-images.githubusercontent.com/1552027/87112758-3f8cc480-c29f-11ea-9089-c046019eaa7a.png)
![QQ截图20200710112103](https://user-images.githubusercontent.com/1552027/87112843-782c9e00-c29f-11ea-9e4a-13759427f27d.png)

**Comment by 1002527441** [comment]
Product: EM Services
Company: Wurth Electronic (shenzhen) Ltd (www.we-online.com)
Link:  using for internal.

**Comment by 136888** [comment]
- Product：Test system, using ant design blazor+EFCore
- Link: (if any)using for internal
- Screenshot: 
![Snipaste_2020-07-17_09-38-25](https://user-images.githubusercontent.com/23148983/87739045-71f37000-c811-11ea-8565-03b2dc862877.png)
![Snipaste_2020-07-17_09-38-59](https://user-images.githubusercontent.com/23148983/87739050-761f8d80-c811-11ea-8066-9f7a07b730cd.png)
![Snipaste_2020-07-17_09-39-15](https://user-images.githubusercontent.com/23148983/87739055-7881e780-c811-11ea-95b1-7a604280eb8f.png)
![Snipaste_2020-07-17_09-41-06](https://user-images.githubusercontent.com/23148983/87739120-aa934980-c811-11ea-9c92-e541297d9c15.png)


Ant Blazor is an excellent framework
Thanks for James

**Comment by imhmao** [comment]
Product：SCM

**Comment by wcoolly** [comment]
- Product：SoftPortal
- Company or Organization: Qingdao Corill Electronic Ltd
- Link: http://www.corill.com

**Comment by pearl2201** [comment]
- Product: Book Store Dashboard
- Company: Kyx Studio JSC

![Annotation 2020-07-27 104128](https://user-images.githubusercontent.com/5409440/88501635-3a957800-cff6-11ea-9d15-e331f5ba9c52.png)
![Annotation 2020-07-27 104301](https://user-images.githubusercontent.com/5409440/88501650-42edb300-cff6-11ea-8c29-29377044d98a.png)
![Annotation 2020-07-27 104153](https://user-images.githubusercontent.com/5409440/88501654-4719d080-cff6-11ea-9237-106b003dc05f.png)
![Annotation 2020-07-27 104214](https://user-images.githubusercontent.com/5409440/88501720-72042480-cff6-11ea-8de2-b7b70a141fc1.png)

**Comment by itmaybetrue** [comment]
Product：AI-WMS
Company: amtxts Ltd
![微信截图_20200930172254](https://user-images.githubusercontent.com/33754438/94667636-a4f1ce00-0341-11eb-8be4-9ffbcbc66ec4.png)

**Comment by TimChen44** [comment]
- Product：组织绩效数据管理平台
- Company：Chint
- Link: http://www.chint.net/zh/index.php/about/index.html
![screencapture-10-10-14-70-2023-AchievementMgr-AchievementSearch-2020-09-30-14_06_13](https://user-images.githubusercontent.com/7581981/95337122-20282680-08e4-11eb-9a99-3d1e66486b54.png)
![screencapture-10-10-14-70-2023-IndexMgr-IndexSearch-2020-09-30-14_13_01](https://user-images.githubusercontent.com/7581981/95337132-21595380-08e4-11eb-88ef-293f74852d71.png)

**Comment by justmine66** [comment]
Thanks
Product: CMS
Company: 际客国际
Link: using for internal.
![image](https://user-images.githubusercontent.com/23122801/100435290-b274cb80-30d8-11eb-86ba-b2913c6644bb.png)
![image](https://user-images.githubusercontent.com/23122801/100435406-da642f00-30d8-11eb-84e1-fc21129947a5.png)
![image](https://user-images.githubusercontent.com/23122801/100435478-f36ce000-30d8-11eb-9c4c-e63bee2f70dc.png)

**Comment by CSharpXu** [comment]
既要用ASP.NET Core Blazor，又要符合UI设计要求，最终选择了Ant Design Blazor，谢谢James，谢谢团队！当我们遇到问题及时作出反馈。

**Comment by jingxi0109** [comment]
Product: Review System
Company: Ai Win Sales
Link: aiwinsales.com
![屏幕截图 2020-11-27 183018](https://user-images.githubusercontent.com/18211444/100439539-a3911780-30de-11eb-8eb7-846feb41a168.png)

**Comment by fan0217** [comment]
- Product：Financial Management System
- Company or Organization: XFly
- Link: 
- Screenshot: 
 
![Blazor](https://user-images.githubusercontent.com/13997023/103061958-bb798f80-45e7-11eb-9957-02459184a496.png)

**Comment by guanshuqing** [comment]
产品：冠新内控系统
公司：冠新软件
链接：无（公司内部系统不对外）

**Comment by akinix** [comment]
@fan0217 你的UI比较简洁 是自定义的么?

**Comment by richerp** [comment]
产品：企业Erp系统
公司：RichErp
链接：www.richerp.com

**Comment by anddrzejb** [comment]
Product: Fare Montior system
Company: Intercity Cyprus
No link, internal app
Shameless ripoff of Pro template 😏

**Comment by bryanrcarlson** [comment]
- Product：[Midden: Research Data Catalog](https://github.com/CafIncubator/Midden)
- Online example: [Cook Agronomy Farm Metadata](https://meta.cafltar.org)
- Screenshot: 
  - ![Insights dashboard](https://github.com/CafIncubator/Midden/raw/main/media/ss-insights.jpg)
  - ![Dataset details](https://github.com/CafIncubator/Midden/raw/main/media/ss-dataset-view.jpg)

**Comment by newbe36524** [comment]
- Product：Amazing-Favorites
- Link:  https://github.com/newbe36524/Amazing-Favorites
- Screenshot: 

![image](https://user-images.githubusercontent.com/7685462/116783833-8fa17580-aac3-11eb-9a71-5c1df0e4c513.png)
![image](https://user-images.githubusercontent.com/7685462/116783833-8fa17580-aac3-11eb-9a71-5c1df0e4c513.png)

**Comment by dudghks117** [comment]
product : order system
company : none
![antdesign](https://user-images.githubusercontent.com/42609006/116979564-1f336800-ad00-11eb-9937-d5b946c19a8e.PNG)

**Comment by Alexandre789010** [comment]
Hi, I use AntBlazor in production. (Internal software)
Cannot share the repo unfortunately - but here are some pictures:

![image](https://user-images.githubusercontent.com/60594505/123912511-78e2a680-d9c0-11eb-892d-b71757c4004c.png)

![image](https://user-images.githubusercontent.com/60594505/123912600-9879cf00-d9c0-11eb-9d17-1c762f97ff58.png)

![image](https://user-images.githubusercontent.com/60594505/123912666-ad566280-d9c0-11eb-85cd-1125b0a0303e.png)

![image](https://user-images.githubusercontent.com/60594505/123912980-06be9180-d9c1-11eb-9cd9-c872ed5df906.png)

![image](https://user-images.githubusercontent.com/60594505/123913133-353c6c80-d9c1-11eb-9701-746e1c9ff947.png)

![image](https://user-images.githubusercontent.com/60594505/123912808-d840b680-d9c0-11eb-9d7a-4f511f1da90c.png)


Thank you to all the contributors. Amazing job! 👍

**Comment by JiaoLongYang** [comment]
- Product：运输企业安全生产信息管理平台
- Screenshot: 
![image](https://user-images.githubusercontent.com/20771689/123913297-9d368700-d9b0-11eb-88fa-12abff6fb8b4.png)
![image](https://user-images.githubusercontent.com/20771689/123913484-da027e00-d9b0-11eb-8073-b0f841b7f229.png)
![image](https://user-images.githubusercontent.com/20771689/123914092-99efcb00-d9b1-11eb-8d90-ec02fb2f5a49.png)
![image](https://user-images.githubusercontent.com/20771689/123916383-2bf8d300-d9b4-11eb-92cf-a4ba74f9f1e2.png)

**Comment by BeiYinZhiNian** [comment]
- Product：Caviar   (It's still under development)
- Link: https://gitee.com/Cherryblossoms/caviar
           https://github.com/BeiYinZhiNian/Caviar
- Screenshot: 
![image](https://user-images.githubusercontent.com/25119211/123916583-66627000-d9b4-11eb-97f8-0f10c41be10a.png)
![image](https://user-images.githubusercontent.com/25119211/123916970-d7098c80-d9b4-11eb-96e9-e34cb05a8080.png)
![image](https://user-images.githubusercontent.com/25119211/123917049-edafe380-d9b4-11eb-81b8-532d813568c8.png)
![image](https://user-images.githubusercontent.com/25119211/123917210-1df78200-d9b5-11eb-83c7-e6f53dca2dab.png)
![image](https://user-images.githubusercontent.com/25119211/123917233-23ed6300-d9b5-11eb-8327-f18bf2c6e2c3.png)
![image](https://user-images.githubusercontent.com/25119211/123917267-2e0f6180-d9b5-11eb-9a89-7d66d3a009d0.png)
