### ISSUE TITLE
Filter Dropdown list is not persistent on clicking dropdown arrow icon

### ISSUE THREAD

**Issue by anu4shka** [ant-design-blazor/ant-design-blazor#3353]
While using Filterable in table, the dropdown that opens is not persistent on clicking the bottom arrow. Dropdown stays open only on clicking on the text or anywhere inside the box.

### Steps to reproduce
https://antblazor.com/en-US/components/table#components-table-demo-filter
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/67831924/90434a03-4adc-4166-9a69-67c511c7aaf2)

### Further technical details
-AntDesign Nuget Package version: 0.15.1
-Microsoft Visual Studio Professional 2022, Version 17.6.4

**Comment by ElderJames** [comment]
Thanks for contacting us @anu4shka , I checked and found that only wasm had this issue. we need more time to find out what the problem is.

**Comment by ElderJames** [comment]
We have fixed this issue in version 0.17.0.
