### ISSUE TITLE
bind-Value for Select Component for Reference Types

### ISSUE THREAD

**Issue by hamiddd1980** [ant-design-blazor/ant-design-blazor#3369]
Currently in **Select** component the **@bind-Value** works only if it is assigned a value from **Select DataSource** .  It works based on **Reference Comparison**, not Value Comparison. 
I mean if you set **@bind-Value** to new object (new foo()), the binding won't work.
This is especially a problem when you retrieve the data from Server in JSON format including a model like below 
:
```
public class modelDTO
{
   IList<Person> people = new List<Person>();
   Person? selectedParson=new Person();
} 
```
Because `selectedParson` is not from `people` list (**Select Datasource**, although its properties values match one of the Select Datasource), so the binding doesn't work.
let say we have a model named Person:
```
public class Person
{
    public string Name { get; set; }
    public string LastName { get; set; }
}
```
and this is my Razor Page :
```
<Select TItem="Person" TItemValue="Person"
        DataSource="@people"
        @bind-Value="@selectedParson"
        LabelName="@nameof(Person.LastName)">
        </Select>


@code 
{
   IList<Person> people = new List<Person>();
   Person? selectedParson=new Person();
   protected override Task OnInitializedAsync()
   {
          people = new List<Person>()
          {
              new Person{Name="David",LastName="Anderson"},
              new Person{Name="Sara",LastName="Baker"},
              new Person{Name="Jack",LastName="Wilson"},
              new Person{Name="Smith",LastName="Johnson"},
              new Person{Name="Sina",LastName="Martin"},
              new Person{Name="Suzan",LastName="Jones"},
          };

        selectedParson = new Person { Name = "Jack", LastName = "Wilson" }; // it doesn't work
      //selectedParson = people [3];//it works
   }
}
```
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
Please enable `@bind-Value` based on the Value of bound model .For example if **ID** of the `selectedPerson `matches one of the **Select Datasource** items, it must be displayed as  Selected item.

**Comment by ElderJames** [comment]
Thanks for contacting us @hamiddd1980 

For now we only support bingding value types, like this:

```
<Select TItem="Person" TItemValue="string"
        DataSource="@people"
        @bind-Value="@selectedParson"
        LabelName="@nameof(Person.LastName)"
        ValueName="@nameof(Person.LastName)">
        </Select>

@code
{
    IList<Person> people = new List<Person>();
    string selectedParson;

    public class Person
    {
        public string Name { get; set; }
        public string LastName { get; set; }

    }
 
    protected override async Task OnInitializedAsync()
    {
        people = new List<Person>()
          {
              new Person{Name="David",LastName="Anderson"},
              new Person{Name="Sara",LastName="Baker"},
              new Person{Name="Jack",LastName="Wilson"},
              new Person{Name="Smith",LastName="Johnson"},
              new Person{Name="Sina",LastName="Martin"},
              new Person{Name="Suzan",LastName="Jones"},
          };


        selectedParson = "Wilson";                                                      
    }
}

```

**Comment by hamiddd1980** [comment]
Thank you for reply. your answer helped me to address the problem :
I think I should define a unique property on my model (like **Id**), and bind the value to it :
`@bind-Value =@myModel.Id`
and
`TItem="myModel"`
Thank you.
