### ISSUE TITLE
bug of Drawer

### ISSUE THREAD

**Issue by MiniTor** [ant-design-blazor/ant-design-blazor#337]
I have a issues of  Drawer when Customize the style of the scroll bar

![image](https://user-images.githubusercontent.com/24976720/86998983-2246f000-c1e4-11ea-8e48-3f536878745e.png)

Why did the style of the body changed

**Comment by zxyao145** [comment]
Because the style and class of body will be changed when the drawer is opened and closed, we will fix it soon. Thanks lot.

**Comment by StardustDL** [comment]
Yes, I also find that the style of the body will be changed when opening/closing a modal.

**Comment by zxyao145** [comment]
Now an alternative is to use class.
