### ISSUE TITLE
DatePicker - Require Input Masking

### ISSUE THREAD

**Issue by SumitAngra** [ant-design-blazor/ant-design-blazor#3381]
Currently there is no restriction on the date which can be typed into the control. Do we have something similar to a mask property by which we can restrict the entered date to a specific format ?
For example - restricting the user to type the date only in format of 'dd/mm/yyyy'

**Comment by ElderJames** [comment]
Thanks for contacing us @SumitAngra 

I think this PR https://github.com/ant-design-blazor/ant-design-blazor/pull/3120 is what you meant. Could you please help review it?

**Comment by SumitAngra** [comment]
Thanks @ElderJames for a quick response.
By the initial looks of it, I can see the PR is for allowing multiple date formats in the datepicker. 
What I mentioned is restricting the typing of anything else except the specified mask format in the input datepicker.

Please correct me if I am wrong.

**Comment by ElderJames** [comment]
Ok, I get it. Could you help find an example of blazor implementing masking?

**Comment by SumitAngra** [comment]
@ElderJames I hope I have answered your question above.
Please do let me know if this is something which is going to be implemented soon ?

**Comment by ElderJames** [comment]
@ElderJames I'll need to do some research, but don't promise this feature will be available anytime soon.

**Comment by ElderJames** [comment]
Thank you, it looks like implementation is pretty complicated

**Comment by ElderJames** [comment]
@SumitAngra Please help to  review #3120 and  see if it fits your scenario?

**Comment by ElderJames** [comment]
Hello @SumitAngra , this feature have been shipped in the lastest 0.16.0 release. Enjoy!

**Comment by SumitAngra** [comment]
Thank you @ElderJames! The feature looks awesome :)
I can see a couple of minor bugs which I will raise separately.
