### ISSUE TITLE
Modal closing issue

### ISSUE THREAD

**Issue by quirynen** [ant-design-blazor/ant-design-blazor#3384]
### Describe the bug

If I have a modal displayed on my current page & an event is triggered in my application causing a redirection to another page, the modal is still displayed even though the _visible boolean is set to false & DestroyOnClose is set to modal, the dispose method is correctly called & boolean is correctly set to false.
Small example is provided below.

### Steps to reproduce (please include code)

Modal.razor : 
```
@implements IDisposable


<Modal DestroyOnClose Style="width:50%;" Visible="_showPasswordModal" OnCancel="()=>_showPasswordModal=false" >
                <TitleTemplate>
                    <h3 >test</h3>
                </TitleTemplate>
 </Modal >

   
@code{
public override void Dispose(){
    _showPasswordModal=false;
     base.Dispose();
}
} 
```

App.razor

   ```
 private Timer? _timerRedirect;
 protected async override Task OnInitializedAsync()
    {
     
        _timerRedirect = new Timer( 2000 );
        _timerRedirect.Elapsed += UpdateTimerRedirect;
      
        _timerRedirect.AutoReset = false;
    
        await base.OnInitializedAsync();

    }
        
 private async void UpdateTimerRedirect( Object? source, ElapsedEventArgs e )
    {

                Navigation.NavigateTo( "/");

    }
```
### Exceptions (if any)

None

### Further technical details
- AntDesign Nuget Package version 15.4
- Include the output of `dotnet --info` .net 6/7

**Comment by zxyao145** [comment]
@quirynen Sorry, I did not reproduce it.  I am using wasm mode, here is my code, please provide more information。

Index.razor
```razor
@page "/"
@implements IDisposable 

<Modal DestroyOnClose Style="width:50%;" Visible="_showPasswordModal" OnCancel="()=>_showPasswordModal=false">
    <TitleTemplate>
        <h3>test</h3>
    </TitleTemplate>
</Modal>

@code {
    bool _showPasswordModal = true;

    public void Dispose()
    {
        _showPasswordModal=false;
    }
}
```

App.razor
```razor
@using System.Timers
@inject NavigationManager Navigation
<Router AppAssembly="@typeof(App).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <PageTitle>Not found</PageTitle>
        <LayoutView Layout="@typeof(MainLayout)">
            <p role="alert">Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>

<AntContainer /> 


@code
{
    private System.Timers.Timer _timerRedirect;
    protected override async Task OnInitializedAsync()
    {
        _timerRedirect = new Timer(2000);
        _timerRedirect.Elapsed += UpdateTimerRedirect;
        _timerRedirect.AutoReset = false;
        _timerRedirect.Enabled = true;
        await base.OnInitializedAsync();
    }

    private void UpdateTimerRedirect(Object source, ElapsedEventArgs e)
    {
        Navigation.NavigateTo("/counter");
    }
}
```

**Comment by ElderJames** [comment]
Thanks @zxyao145 , I find another issue that if you add an `a` element on the content of Modal, and link to other page, the Modal doesn't close while you click the link and the current page was also disposed.

**Comment by quirynen** [comment]
Sorry I did not fully test my code, actually it's like @ElderJames except I have         <ChildContent>
 renderfragment inside my modal, and when I click on the goback page on chrome, tue modal is not closed, but it can also be reproduced by a redirect like you did

**Comment by zxyao145** [comment]
@ElderJames I did not reproduce using the following code. Can you provide a demo?

```razor
@page "/"
@implements IDisposable 

<Modal DestroyOnClose Style="width:50%;" Visible="_showPasswordModal" OnCancel="()=>_showPasswordModal=false">
    <TitleTemplate>
        <h3>test</h3>
    </TitleTemplate>
    <ChildContent>
        <a href="/counter">link</a>
    </ChildContent>
</Modal>

@code {
    bool _showPasswordModal = true;

    public void Dispose()
    {
        _showPasswordModal=false;
    }
}
```

**Comment by zxyao145** [comment]
> @ElderJames I did not reproduce using the following code. Can you provide a demo? 我没有使用下面的代码进行复制。你能提供一个demo吗？
> 
> ```
> @page "/"
> @implements IDisposable 
> 
> <Modal DestroyOnClose Style="width:50%;" Visible="_showPasswordModal" OnCancel="()=>_showPasswordModal=false">
>     <TitleTemplate>
>         <h3>test</h3>
>     </TitleTemplate>
>     <ChildContent>
>         <a href="/counter">link</a>
>     </ChildContent>
> </Modal>
> 
> @code {
>     bool _showPasswordModal = true;
> 
>     public void Dispose()
>     {
>         _showPasswordModal=false;
>     }
> }
> ```

@quirynen The back button still works for me,  can you provide a demo?


https://github.com/ant-design-blazor/ant-design-blazor/assets/24973084/fe898cfb-e4b9-438a-b5c0-79d8c3a16ea8

**Comment by quirynen** [comment]
Found it, if you put your modal inside a <div style="display:flex; flex:auto;">
then you will be able to reproduce the bug

**Comment by zxyao145** [comment]
@quirynen Get it, Modal cannot be wrapped by HTML native elements, because the lifecycle of HTML native elements is not managed by Blazor.

If you have a `Div.razor` component below (no need to implement IDisposable):

```razor
@ChildContent

@code
{
    [Parameter]
    public RenderFragment? ChildContent { get; set; }
}
```
This will work well:

```razor
<Div>
    <Modal DestroyOnClose Style="width:50%;" Visible="_showPasswordModal" OnCancel="()=>_showPasswordModal=false">
        <TitleTemplate>
            <h3>test</h3>
        </TitleTemplate>
        <ChildContent>
            <a href="/counter">link</a>
        </ChildContent>
    </Modal>
</Div>
```


In fact, wrapping Modal with `div` is meaningless, because Modal will be extracted into the body after being rendered.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/24973084/68f1a362-2cf6-4d5b-bb0a-c9cd7d78f8f4)

Next, I will try to improve this issue. Before that, please do not use the native HTML native wrapping Modal component.

**Comment by quirynen** [comment]
Ok thanks for the feedback, maybe it'd be a good idea to mention it in the documentation if someone encountered this issue in the future

**Comment by zxyao145** [comment]
@quirynen No updates.  Antblazor docs is automatically generated, and the generation strategy needs to be modified
