### ISSUE TITLE
No Row Grouping available for Table? are we need to use Expandable rows to achive row grouping?

### ISSUE THREAD

**Issue by Aamirkhan10218** [ant-design-blazor/ant-design-blazor#3386]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by ElderJames** [comment]
Thanks for contacting us @Aamirkhan10218 , for now you can use following features to achive row grouping:
 
- [row template](https://antblazor.com/zh-CN/components/table#components-table-demo-row-template)
- [Expand rows](https://antblazor.com/zh-CN/components/table#components-table-demo-expand)
- [Tree Data](https://antblazor.com/zh-CN/components/table#components-table-demo-tree-data)
- [Nested table](https://antblazor.com/zh-CN/components/table#components-table-demo-nested-table)

**Comment by ElderJames** [comment]
We are already have row grouping  https://antblazor.com/zh-CN/components/table#components-table-demo-grouping-rows
