### ISSUE TITLE
AutoFocus by Input

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3392]
In a login form (user email + password) I try to use autofocus property on the input field, but it does not work. 

```
            <FormItem>
                <Input @bind-Value="@connection.Email" AutoFocus />
            </FormItem>
```

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/45635963/f2413592-776c-4918-adeb-07f959ee7296)

Form is in a modal component of Ant. What am I doing wrong?

Thanks
perfect-code

**Comment by zxyao145** [comment]
@true-perfect-code Modal will respond to tab key events and must have its own focus strategy. Input is a sub element of Modal, and its focus setting is earlier than Modal, so the final policy that takes effect is Modal. This issue also exists with Antd of React.

One solution is to manually call the `FocusAsync` method after setting the modal:
```razor
 ...
        <FormItem>
            <Input 
+                @ref="Input" 
                @bind-Value="@connection.Email" AutoFocus />
        </FormItem>
 ...
@code {
    private Input<string> _input;
    private Input<string> Input
    {
        get => _input;

        set
        {
            _input = value;
           // The Modal display animation is 300ms, and the waiting time should preferably be greater than 350ms
            Task.Delay(350) 
                .ContinueWith(async (t) =>
                {
                    await _input.Ref.FocusAsync();
                });
        }
    }
}
```

**Comment by true-perfect-code** [comment]
@zxyao145 Thanks a lot it works!

But the delay time had to be set high. I set it to 1 second. I ralso emoved **AutoFocus** from the form (Focus now goes over the method FocusAsync()). It also requires the use of Microsoft.AspNetCore.Components for the code. behind.

Your code will look a bit different if you use the MVVM/Codebehind pattern:

**Form:**
```
            <FormItem>
                <Input @ref="ref_Input" @bind-Value="@connection.Email" />
            </FormItem>
```

**Codebehind:**
```
using Microsoft.AspNetCore.Components;
.
.
        private AntDesign.Input<string> _input;
        protected AntDesign.Input<string> ref_Input
        {
            get => _input;

            set
            {
                _input = value;
                // The Modal display animation is 300ms, and the waiting time should preferably be greater than 350ms
                Task.Delay(1000)
                    .ContinueWith(async (t) =>
                    {
                        await _input.Ref.FocusAsync();
                    });
            }
        }
.
.
```

I will close the topic..

perfect-code

**Comment by NgMeiYann** [comment]
@zxyao145 , how about to set focus on select component in a modal form as below?
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/4e470281-a210-4c5e-86d2-2d9e48e13963)

**Comment by true-perfect-code** [comment]
To set input, I do it like this:

1. define the ID for your input field (e.g. 
`<AntDesign.Input Id="InputClass"...`
2.  call it when the form is loaded.
```
                await Task.Delay(500);
                try
                {
                    await js.InvokeVoidAsync("eval", $"document.getElementById('InputClass').focus()");
                }
                catch { }
```
Maybe you can use this in a similar way to set the list as well?

Regards
pc

**Comment by zxyao145** [comment]
@

> To set input, I do it like this:
> 
> 1. define the ID for your input field (e.g.
>    `<AntDesign.Input Id="InputClass"...`
> 2. call it when the form is loaded.
> 
> ```
>                 await Task.Delay(500);
>                 try
>                 {
>                     await js.InvokeVoidAsync("eval", $"document.getElementById('InputClass').focus()");
>                 }
>                 catch { }
> ```
> 
> Maybe you can use this in a similar way to set the list as well?
> 
> Regards pc

@ElderJames Please confirm the usage of Select

**Comment by ElderJames** [comment]
I'm sorry that for select there are no public API to focus programmatically. For auto focus at first rendering, you can set AutoFocus.

**Comment by NgMeiYann** [comment]
> @NgMeiYann Hi, perhaps what you need is to automatically open the options panel, please try setting the `Open` property for Select
> 
> https://antblazor.com/zh-CN/components/select#API

@zxyao145 adding `open = "true"` in select component is not working as well as the form inside modal and the modal dialog will only visible after a button clicked

**Comment by NgMeiYann** [comment]
> I'm sorry that for select there are no public API to focus programmatically. For auto focus at first rendering, you can set AutoFocus.

@ElderJames , how about my select component is under a modal dialog and only will be set to visible when click on a button

**Comment by NgMeiYann** [comment]
> To set input, I do it like this:
> 
> 1. define the ID for your input field (e.g.
>    `<AntDesign.Input Id="InputClass"...`
> 2. call it when the form is loaded.
> 
> ```
>                 await Task.Delay(500);
>                 try
>                 {
>                     await js.InvokeVoidAsync("eval", $"document.getElementById('InputClass').focus()");
>                 }
>                 catch { }
> ```
> 
> Maybe you can use this in a similar way to set the list as well?
> 
> Regards pc

@true-perfect-code , it is not working as well and having error as below.
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/4589562f-fce3-42a8-96df-662dbf6e4e92)

**Comment by true-perfect-code** [comment]
@NgMeiYann 
In WebAssembly Blazor, the DOM is rendered on the client and it may take some time until the DOM is fully rendered and all elements are available. Therefore, the JavaScript you call may not yet be able to find the element because it has not been rendered.

To ensure that the element is available before you access it, you can call the **StateHasChanged()** method to trigger a new rendering and then call the JavaScript.

```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        StateHasChanged();
        await js.InvokeVoidAsync("eval", $"document.getElementById('InputClass').focus()");
    }
}
```

Regards
pc
