### ISSUE TITLE
Create Modal using backend code

### ISSUE THREAD

**Issue by NgMeiYann** [ant-design-blazor/ant-design-blazor#3399]
https://github.com/ant-design-blazor/ant-design-blazor/blob/b5df6d5ce51c787165c05751e1fd4aff4f09634f/components/modal/modalDialog/ModalServiceForModal.cs#L39

https://github.com/ant-design-blazor/ant-design-blazor/blob/b5df6d5ce51c787165c05751e1fd4aff4f09634f/components/modal/modalDialog/ModalServiceForModal.cs#L53

Is this method will destroy all my modal DOM?
After close the modal dialog created using this method and navigate the side menu, open a new modal dialog will get this error
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/653114df-e84d-4485-bfe6-b601125f8383)

**Comment by zxyao145** [comment]
@NgMeiYann `NavigationManager_LocationChanged` will destroy all modal DOM. If don't do this, the DOM created through ModalService will always exist in the HTML, and it will also be the same after switching routes, which will cause chaos in the DOM.

For the following issue, I can't reproduce it, could you provide a demo?

**Comment by NgMeiYann** [comment]
https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/470de9ec-2ef8-42ec-927b-9c70c707877d

1. close this backend code created modal
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/1d19367e-277e-47ae-b82c-9bcb1c6a9d0a)
2. navigate to other side menu, then open the other front-end modal dialog
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/f6708238-0095-4201-960a-bc99020cc6f2)
after click this icon should show the modal dialog but nothing shown, click f12 then shown the above error

**Comment by zxyao145** [comment]
@NgMeiYann Are you using it with ReuseTab?

**Comment by NgMeiYann** [comment]
@zxyao145 whic is reusetab? The select icon is under pro layout right content render

**Comment by zxyao145** [comment]
@NgMeiYann I think your code may look like this:
```razor
<Button OnClick="OpenModel">Model</Button>
<ChildContent>
    @Body
</ChildContent>
@code
{
    ModalRef r = null;
    private async Task OpenModel()
    {
        if (r == null)
        {
            var o = new ModalOptions()
            {
                Title = "tt",
                Draggable = true,
                Content = @<div>Content</div>
            };
            r = await ModalService.CreateModalAsync(o);
        }
        {
            await r!.OpenAsync();
        }
    }
}
```

Because the Modal is not in @Body, you cannot reuse ModalRef. Please modify it to the following example:

``` c#
private async Task OpenModel()
{
    var o = new ModalOptions()
    {
        Title = "tt",
        Draggable = true,
        Content = @<div>Content</div>
    };
    await r!.OpenAsync();
}
```

**or** inject `NavigationManager` service:

```razor
@inject NavigationManager NavigationManager

// ....

@code
{
    protected override void OnInitialized()
    {
        NavigationManager.LocationChanged += (sender, args) =>
        {
            r = null;
        };
    }
}
```

**Comment by NgMeiYann** [comment]
@zxyao145 , this is my code, but is under a service, while the ProcessingResult is the component, i have added MarkupContent to add the <div></div> but still the same error
```
public async Task<ModalRef> CreateModalAsync(string title, bool isRefreshNeeded, List<string> errorMsgs, Func<Task> onOk)
{
    RenderFragment dialog = builder =>
    {
        builder.AddMarkupContent(0, "<div>");
        builder.OpenComponent<ProcessingResult>(1);
        builder.AddAttribute(2, "Title", title);
        builder.AddAttribute(3, "IsRefreshNeeded", isRefreshNeeded);
        builder.AddAttribute(4, "ErrorMsgs", `errorMsgs);`
        builder.AddAttribute(5, "OnOkButtonClicked", EventCallback.Factory.Create<MouseEventArgs>(this, onOk));
        builder.AddMarkupContent(6, "</div>");
        builder.CloseComponent();
    };

    return await _modalService.CreateModalAsync(new ModalOptions()
    {
        Title = title,
        Draggable = true,
        MaskClosable = false,
        Closable = false,
        Keyboard = false,
        Footer = null,
        Content = dialog,
        DestroyOnClose = false
    });
}
```

**Comment by NgMeiYann** [comment]
> @NgMeiYann `NavigationManager_LocationChanged` will destroy all modal DOM. If don't do this, the DOM created through ModalService will always exist in the HTML, and it will also be the same after switching routes, which will cause chaos in the DOM.
> 
> For the following issue, I can't reproduce it, could you provide a demo?

I suspect is destroy this causing my other modal dialog also become null, and it unable to instantiate again due to it located on the top left content navigation bar

**Comment by zxyao145** [comment]
@NgMeiYann 

> > @zxyao145  `NavigationManager_LocationChanged` will destroy all modal DOM. If don't do this, the DOM created through ModalService will always exist in the HTML, and it will also be the same after switching routes, which will cause chaos in the DOM. `NavigationManager_LocationChanged` 将摧毁所有模态 DOM。如果不这样做，通过 ModalService 创建的 DOM 将始终存在于 HTML 中，切换路由后也会相同，这将导致 DOM 中的混乱。
> > For the following issue, I can't reproduce it, could you provide a demo?对于以下问题，我无法重现它，你能提供一个演示吗？
> 
> I suspect is destroy this causing my other modal dialog also become null, and it unable to instantiate again due to it located on the top left content navigation bar我怀疑是破坏这导致我的其他模态对话框也变为空，并且由于它位于左上角的内容导航栏上，它无法再次实例化

Yes, you are right, however, the destroy behavior cannot be removed.

**Comment by NgMeiYann** [comment]
@zxyao145, any suggestion on how to solve this?

**Comment by zxyao145** [comment]
@NgMeiYann Hi, could provide a demo like #3401? Otherwise, I'm not sure how to provide you with a solution.

**Comment by NgMeiYann** [comment]
@zxyao145  below link is the demo I uploaded previously,
https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/085a563c-7a22-480f-ac2e-62d0e5d0257c

**Comment by zxyao145** [comment]
@NgMeiYann Can you provide a code demo? I don't know how it was did through video alone

**Comment by NgMeiYann** [comment]
@zxyao145 
attached with demo video and code.
[demo video](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/0ead2f68-92ec-4f3c-b0b2-77bf2e426a86)
[demo code](https://github.com/NgMeiYann/AntDesignDemoApp)

**Comment by zxyao145** [comment]
@NgMeiYann Modal will cache the DOM state by default. Please modify it as follows:

```razor

<Modal Title="@("Select an item")"
       Visible="@_visible"
       Draggable="true"
       OnCancel="OnCancelClick"
+       DestroyOnClose="true"
       >
// ...
</Modal>
```

**Comment by NgMeiYann** [comment]
@zxyao145 Thank you so much. Now the display dialog able to open after added `DestroyOnClose="true"`.
I have added this previously in the ProcessingResult dialog but still same, turn out to be need added to the display dialog.
But since it will destroy everything after navigate to other route, why need to add this manually?
````
private Task<ModalRef> CreateModalAsync(string title)
{
    RenderFragment dialog = builder =>
    {
        builder.OpenComponent<ProcessingResult>(0);
        builder.AddAttribute(1, "Title", title);
        builder.AddAttribute(2, "OnOkButtonClicked", EventCallback.Factory.Create<MouseEventArgs>(this, CloseModal));
        builder.CloseComponent();
    };

    return ModalService.CreateModalAsync(new ModalOptions()
    {
        Title = title,
        MaskClosable = false,
        Keyboard = false,
        Content = dialog,
        Footer = null
    });
}
````

**Comment by zxyao145** [comment]
> @zxyao145 Thank you so much. Now the display dialog able to open after added `DestroyOnClose="true"`.非常感谢。现在，添加 `DestroyOnClose="true"` 后显示对话框可以打开。 I have added this previously in the ProcessingResult dialog but still same, turn out to be need added to the display dialog.我之前在“处理结果”对话框中添加了它，但仍然相同，结果需要添加到显示对话框中。 But since it will destroy everything after navigate to other route, why need to add this manually?但是由于它会在导航到其他路线后破坏所有内容，为什么需要手动添加呢？
> 
> ```
> private Task<ModalRef> CreateModalAsync(string title)
> {
>     RenderFragment dialog = builder =>
>     {
>         builder.OpenComponent<ProcessingResult>(0);
>         builder.AddAttribute(1, "Title", title);
>         builder.AddAttribute(2, "OnOkButtonClicked", EventCallback.Factory.Create<MouseEventArgs>(this, CloseModal));
>         builder.CloseComponent();
>     };
> 
>     return ModalService.CreateModalAsync(new ModalOptions()
>     {
>         Title = title,
>         MaskClosable = false,
>         Keyboard = false,
>         Content = dialog,
>         Footer = null
>     });
> }
> ```

This strategy is consistent with antd of react, and this way, when Modal is opened in the future, it will display the state of the last time it was closed

**Comment by NgMeiYann** [comment]
@zxyao145 so this is due to `ModalService.CreateModalAsync()` destroy DOM after navigation changed and `DisplayModalDialog` still caching the state?

**Comment by zxyao145** [comment]
> @zxyao145 so this is due to `ModalService.CreateModalAsync()` destroy DOM after navigation changed and `DisplayModalDialog` still caching the state?

yes
