### ISSUE TITLE
Problem with Modal maximization

### ISSUE THREAD

**Issue by skl-hyf** [ant-design-blazor/ant-design-blazor#3401]
### Describe the bug

When Centered and Maximizable are set at the same time, the Modal will not be full screen, but will be offset to the bottom right.

### Steps to reproduce (please include code)

https://github.com/skl-hyf/MyAntDesignApp

Clone this repo, run, click button 'Open a Modal', then click the maximize button. Now you can get it like bellow.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/76997845/0760166d-16e5-4db8-89a5-986e18affed3)

### Further technical details
- AntDesign Nuget Package version 
- 0.15.4
- Include the output of `dotnet --info`
- .NET SDK : 7.0.400
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
- VS 17.7.2

**Comment by zxyao145** [comment]
@skl-hyf Hi, this is confirmed as a bug: 
Centered will create a pseudo-element through `ant-modal-centered::before`, it will affect the Maximizable style.

This will be fixed as soon as possible.
