### ISSUE TITLE
Table RowClassName is not applied on Fixed columns

### ISSUE THREAD

**Issue by PrincessLunaOfficial** [ant-design-blazor/ant-design-blazor#3407]
Row class name is not applied on cells of fixed columns.

### Steps to reproduce

1. Add table
2. Add any fixed columns to the table
3. Set RowClassName property on the table

As you can see on example, first and last columns are fixed. Background color on RowClass is set to yellow. It is not applied on fixed column cells.

![Screenshot 2023-08-29 144710](https://github.com/ant-design-blazor/ant-design-blazor/assets/88183054/c1985981-26d4-4185-b849-df2bfba92b5d)

**Comment by ElderJames** [comment]
Yhanks for contacting us @PrincessLunaOfficial . For fixed columns, you also need to style the `td` elements.

```
    .custom, .custom > td {
        background-color: #ffccc7 !important;
    }
        .custom:hover, .custom:hover > td {
            background-color: #ffa39e !important;
        }
```
