### ISSUE TITLE
Button set loading still can click

### ISSUE THREAD

**Issue by elitesw** [ant-design-blazor/ant-design-blazor#3408]
#### When the button loading is set to true, it can still be clicked. For example, in the modal dialog,  Quick click twice OK  button. 
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/54815375/85bef928-4dac-476d-97f3-8bcfbc982fd3)

**Comment by ElderJames** [comment]
Thanks for contacting us @elitesw, would you be interested in helping fix it?
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/dadd42f0-2537-4524-8877-8405e42f1876)
