### ISSUE TITLE
DropDown Selectable Attribute

### ISSUE THREAD

**Issue by Yz274419** [ant-design-blazor/ant-design-blazor#3424]
### Describe the bug

DropDown in Ant Blazor seems to have the select property enabled by default. How do we decide when to set this property ourselves
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/88315735/254da9e5-d011-4cf7-89c2-181deab3baa4)

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thanks for contacting us @Yz274419 , please set `Selectable=false` to Menu.

```
<Dropdown>
    <Overlay>
        <Menu Selectable=false>
            <MenuItem>
                1st menu item
            </MenuItem>
            <MenuItem>
                2nd menu item
            </MenuItem>
            <MenuItem>
                3rd menu item
            </MenuItem>
        </Menu>
    </Overlay>
    <ChildContent>
        <a class="ant-dropdown-link" @onclick:preventDefault>
            Hover me <Icon Type="down" />
        </a>
    </ChildContent>
</Dropdown>
```
