### ISSUE TITLE
Select drop down datasource not filtered when datasource was changed

### ISSUE THREAD

**Issue by NgMeiYann** [ant-design-blazor/ant-design-blazor#3438]
Select drop down datasource was not populate in ordered.
UI shown ordering is mess out
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/224a764a-cf4c-44f8-a35b-bd4ed506248d)

inspect console was able to writeline in ordered
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/6a75b77a-f6e7-422c-8e84-71c44c22989f)

**Comment by NgMeiYann** [comment]
@ElderJames , any updates on this?

**Comment by NgMeiYann** [comment]
@ElderJames, attached here my demo repo, and demo video for further information.
Appreciate if you could help on this.

https://github.com/ant-design-blazor/ant-design-blazor/assets/86877735/aecb7543-1475-44f1-8463-bea79908985c

 here is my repo, [AntDesignDemoApp](https://github.com/NgMeiYann/AntDesignDemoApp)

**Comment by ElderJames** [comment]
Thanks for contacting us @NgMeiYann ,we will look into this issue.

**Comment by NgMeiYann** [comment]
will need to add below property into select component.
`SortByLabel="SortDirection.Ascending"`
