### ISSUE TITLE
bug of Select

### ISSUE THREAD

**Issue by MiniTor** [ant-design-blazor/ant-design-blazor#344]
![image](https://user-images.githubusercontent.com/24976720/87121932-791cfa00-c2b6-11ea-8a75-0c62bea5214a.png)
![image](https://user-images.githubusercontent.com/24976720/87122059-b08ba680-c2b6-11ea-975d-40b378bc2b94.png)
Please support the for loop

**Comment by ElderJames** [comment]
Thankyou for contacting us @MiniTor 
Please add the `@key="i"` property at `SelectOption`.

**Comment by HQDragon** [comment]
seems a reference issue, var i will equal 10 at last.   and component will ref i.
var x=i will set a x instance in every loop.

**Comment by ElderJames** [comment]
Exactly, thank you @HQDragon .
