### ISSUE TITLE
InputNumber doesn't have attribute for maxlength

### ISSUE THREAD

**Issue by chazikaifa** [ant-design-blazor/ant-design-blazor#3454]
The project I'm working on has a requirement that all the input components should have max length limits. However, `InputNumber` doesn't have attribute for `maxlength`. 

Although I can control the value using `Min` and `Max` , say from 0 to 10, users can still input very long string like '5.555555...' .  My temporary solution is using JS to add `maxlength` to the `<input>` or check in the `OnInput` EventCallback, which will cause unnecessarily overhead.

So, I believe it should be an enhancement if `InputNumber` can support `maxlength` attribute.

**Comment by ElderJames** [comment]
Thanks for contacting us @chazikaifa , if you are interested, please feel free to submit a PR.
