### ISSUE TITLE
Setting the HidePagination parameter to true for Table does not take effect

### ISSUE THREAD

**Issue by HongChenLuYuan** [ant-design-blazor/ant-design-blazor#3456]
如题：Table设置HidePagination属性为true不生效，依然要设置PageSize为总记录数才行，不然只显示10条记录。

**Comment by ElderJames** [comment]
Thanks for contacting us @HongChenLuYuan , could you please post your code here? Currently it work as expect.

**Comment by ElderJames** [comment]
Please update to new version, it works well.
