### ISSUE TITLE
Select Virtualization Bug

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design-blazor/ant-design-blazor#3460]
![70469c1903a8051fbb5142ebb1e5eb7](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/52514ba7-1dba-44d5-ba68-2fa9f1010ee0)
![3bc01a60dc0e9339335388f8847be0c](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/cdc26967-893b-4912-8e82-cc5ae656a5fe)
When I add the drop-down list to allow virtualization, the search appears in blank space, and when the scroll bar is dragged to the bottom, the content is automatically displayed. When virtualization is removed, the search is correct.

**Comment by HuaFangYun** [comment]
![8f762dbee9347fc3c2dee46ddf73256](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/99699eb6-d0cd-42b6-82c1-6d26b944e2c8)
When searching for content, select half of the text to display

**Comment by Magehernan** [comment]
I see the an issue with this, in my case when you have a select with EnableVirtualization and EnableSearch the search dosn't work.

This is the code that use virtualization or not

https://github.com/ant-design-blazor/ant-design-blazor/blob/5d02b0b53e4aefae328812a589a8044f2d8048bc/components/select/Select.razor#L137-L155

In here it receive the collection to display but receive always all the items.
When you search it not filters the items, it mark the item IsHidden to true that makes the SelectOption to set a css to display:none.

So de problem is that the virtualize don't know of this internal beheaviour. It want the items to be displayed and it will base on the amount, show what is needed.

I try doing this in the template and it seems to work.

```csharp
var data = ctx.selectOptionItems.Where(t=>!t.IsHidden && !t.IsSelected).ToList();
```

in wasm work fine using 1300 items... but i think is needed to make a more deep change using cache for not recaculate this every time it draws.

I will submit a pull request with some changes

**Comment by ElderJames** [comment]
Thank you @Magehernan , looking forward your PR.

**Comment by Magehernan** [comment]
hi @ElderJames  i send the pull request trying to change the minimum code to make it work kepping an eye on performace but select has a lot of options so maybe i miss some case.
