### ISSUE TITLE
Need help using .NET8

### ISSUE THREAD

**Issue by Snowlights2022** [ant-design-blazor/ant-design-blazor#3469]
### Describe the bug

现有的快速入门和在旧项目中引入antdesign blazor的方法对于.NET 8不适用。而且目前没有文档能够帮助解决交互性丢失（比如使用antdesign blazor的按钮替代ms提供的模板项目按钮后没有反馈）的问题。

Existing quickstarts and methods of introducing AntDesign Blazor in older projects do not work for .NET 8. And there is currently no document that can help solve the problem of loss of interactivity (for example, there is no feedback after using the button of antdesign blazor to replace the template project button provided by Microsoft).

### Steps to reproduce (please include code)

无。这是一个关于如何使用的教学（指导）
请求。

none. This is a tutorial on how to use ask.

### Exceptions (if any)

无。

None. 

### Further technical details
- AntDesign Nuget Package version
尝试使用的是0.16.0

Tried using 0.16.0

- Include the output of `dotnet --info`
无报错产生。

No errors. 

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS2022 17.8 preview4

**Comment by ElderJames** [comment]
Thanks for contacting us @Snowlights2022 , currently we don't support server-side rendering for .NET 8 WebApp yet, only Server and Wasm are supported. Normally, blazor components lose interactivity with SSR.

**Comment by Snowlights2022** [comment]
Thanks. If convenient, what time will be possible that you officially support server-side rending of .NET8?

**Comment by ElderJames** [comment]
@Snowlights2022 The near future. However, we will only support components that can render content during the initialization phase, and will not provide the ability to interact with server-side rendering

**Comment by xulovexin** [comment]
I tried to configure AntDesign in .NET 8 WebApp mode today and encountered issues with references, and I couldn't find any relevant information online. Are there any tutorials available for this?

**Comment by xulovexin** [comment]
In the component, I cannot reference the Ant functions, but when adding in program.cs and _Imports.razor, the IntelliSense suggestions do appear.

**Comment by ElderJames** [comment]
Thanks for contacting us @xulovexin , are you meaning @ref for reference?

**Comment by ElderJames** [comment]
@Snowlights2022 We have update our documentation and readme for Auto render mode.

**Comment by Snowlights2022** [comment]
> @Snowlights2022 We have update our documentation and readme for Auto render mode.

Thanks a lot. I will have a try with this wonderful package!
