### ISSUE TITLE
正式版本0.1.0nuget包无法下载css和js文件

### ISSUE THREAD

**Issue by Glepooek** [ant-design-blazor/ant-design-blazor#347]
我在使用0.1.0正式版本，nuget包无法下载css和js文件？

**Comment by ElderJames** [comment]
Thank you for contacting us @Glepooek .
Static files only appear in `wwwroot` after your app was published.

**Comment by Glepooek** [comment]
有考虑过在后续版本中，下载安装nuget包时，将css和js文件一起下载下来？这样方便，一步到位不是更好吗？

**Comment by ElderJames** [comment]
This is the internal mechanism of Razor Class Labraries (RCL). You can see the details in documentation here:
[Create reusable UI using the Razor class library project in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#publish)
