### ISSUE TITLE
Table sorter and pager tooltips

### ISSUE THREAD

**Issue by binbsr** [ant-design-blazor/ant-design-blazor#348]
While using table component, I found that default tooltips for sorter and pager are hardcoded in Chinese not English.
![image](https://user-images.githubusercontent.com/1488017/87229063-e919a600-c3c4-11ea-8925-e7d8f46f707f.png)

I can't find any API to set that either in English language. There is API to turn off sorter tooltip (didn't find for pager), but I want to show the tooltip in English language. To me, English default makes more sense leaving localization configuration up to the programmer. Any workaround for this @ElderJames ?

**Comment by ElderJames** [comment]
Thank you for your interest in this project @binbsr !
We apologize for the inconvenience. We are very much in any position to have this project support localization.
This is a newly added feature, and we will add localization configuration soon.
