### ISSUE TITLE
Select all in Table is not working properly when there is more than 1 page

### ISSUE THREAD

**Issue by dzima1** [ant-design-blazor/ant-design-blazor#3485]
### Describe the bug

Select all in Table is not working properly when there is more than 1 page.

https://s5.gifyu.com/images/S8FK6.gif
https://s5.gifyu.com/images/S8FKF.gif

### Steps to reproduce (please include code)
Code taken from documentation: https://antblazor.com/en-US/components/table#components-table-demo-row-selection 
Only modification: add more elements to collection to have more than one page.

It's also not working on table in documentation: https://antblazor.com/en-US/components/table#components-table-demo-blazor

### Further technical details
- AntDesign Nuget Package version: 0.16.1

**Comment by ElderJames** [comment]
Thanks for contacting us @dzima1 , we will look into it.

Hello @rhodon-jargon ,  could you please help to see if this problem is related to  #3282 ?
