### ISSUE TITLE
Exception in AntDesign.Filters.DefaultFieldFilterTypeResolver.Resolve[T]()

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3489]
In version `0.16.1` I'm now getting the following exception:
```
System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=AntDesign
  StackTrace:
   at AntDesign.Filters.DefaultFieldFilterTypeResolver.Resolve[T]()
   at AntDesign.Column`1.OnParametersSet()
```
I have rolled back to `0.15.5` for now.

**Comment by ElderJames** [comment]
Thanks for contacting us @michaelcsikos , which Type did you set to the column `TData`?

**Comment by michaelcsikos** [comment]
It's my own class which helps sort strings as natural numbers. The following solves it for me:

```cs
protected override void OnParametersSet()
{
    if (Filterable)
        Filterable = false;

    base.OnParametersSet();
}
```

**Comment by ElderJames** [comment]
Did you mean you created your own Column, and the TData is string?

**Comment by michaelcsikos** [comment]
It was my own `TData` type and inherited `Column` to handle it. I realised I have come across [problems like this before](https://github.com/ant-design-blazor/ant-design-blazor/issues/2949) and shouldn't be using that approach.

**Comment by ElderJames** [comment]
Hello @michaelcsikos ,  can the custom filter sovle this issue?
