### ISSUE TITLE
How to force Select to rebind value?

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3490]
I have a list of components which can be ordered by the user. On the component there is a `Select` but the selected value is not being updated to the correct value from the object's property. How can I force the `Select` to re-read the bind value? `StateHasChanged` doesn't fix it. I have also tried forcing the `Value` but that also doesn't work.

**Comment by ElderJames** [comment]
Hello @michaelcsikos , could you please provide a reproduce demo to explain this issue?

**Comment by ElderJames** [comment]
Is this the same issue as https://github.com/ant-design-blazor/ant-design-blazor/issues/3438 ?

**Comment by michaelcsikos** [comment]
Hi @ElderJames I've tried to make a demo to reproduce it, but it's working fine in the demo.

In my main project, when it happens it looks like this:
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/21806535/57a5d49b-c74c-4a10-a705-b811ab70b142)

The correct value is `File`, displayed above the `Select` in this example. The `Select` is showing `Engineering` but when you click on the drop-down, it shows the correct value `File` highlighted as well as the incorrect value `Engineering`. However, the `Mode = "default"`. I'm completely stumped.

**Comment by ElderJames** [comment]
Sorry, I can't reprocude the issue.
