### ISSUE TITLE
How to hide "Page style setting" drawer button in published app?

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3497]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/21806535/1d431504-051e-4409-b65d-576d5c08ed5f)

I thought this was supposed to be on the developer's PC only, but it is being published.

**Comment by ElderJames** [comment]
Hello @michaelcsikos , you can remove the `<SettingDrawer />` here:

https://github.com/ant-design-blazor/ant-design-pro-blazor/blob/master/src/AntDesign.Pro/Layouts/BasicLayout.razor#L17

**Comment by michaelcsikos** [comment]
Thank you, that's the one.
