### ISSUE TITLE
Input component with AddOnBefore/Prefix do not work with @if {}

### ISSUE THREAD

**Issue by Zou-Jia** [ant-design-blazor/ant-design-blazor#3509]
### Describe the bug

Input component with AddOnBefore do not work with @if

### Steps to reproduce (please include code)
Create a new project as describe in Getting startted page.
replace the Index.razor with following:
```
@page "/"

<PageTitle>Index</PageTitle>
@if (isTest)
{
<h1>Hello, world!</h1>
<Input TValue="string">
	<AddOnBefore><Icon Type="qrcode"></Icon></AddOnBefore>
</Input>
<Button Type="primary">Primary</Button>
<SurveyPrompt Title="How is Blazor working for you?" />
}
@code{
	public bool isTest = false;
}
```

### Exceptions (if any)
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/14681050/1c585ed0-51d7-4f4b-a113-914612b02642)
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/14681050/320152ea-ae2a-4177-9440-73d7568c79c9)

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Zou-Jia** [comment]
I found a workaround, for any one who face the same issue, pass the RenderFragment to the input's parameter causes no error.
```
@if (isTest) 
{ 
	<Input TValue="string" AddOnBefore="@_prefix" />
}

@code{
	public bool isTest = true;
	RenderFragment _prefix =@<Icon Type="qrcode"></Icon>;
}
```
closing...

**Comment by ksrajath7** [comment]
@Zou-Jia The code you have provided is well enough for simple elements, however if the error occurs for more complex elements try this

In this example I have a select box for selecting country code as add on before the input element
  @if (!otpHasSent)
  {
      <Input Prefix="_overlayMenu" Style="width:100%" Placeholder="txtValue" @bind-Value="@txtValue">

      </Input>
  }


 @code {
public bool otpHasSent;
    public class CountryCode
    {
        public string Country { get; set; }
        public string Code { get; set; }
    }
    public string _selectedValue1 { get; set; } = "";
    public List<CountryCode> _list = new List<CountryCode>
        {
            new CountryCode {Code = "+91", Country = "India"},
            new CountryCode {Code = "+1", Country = "US"},
        };
    public RenderFragment _overlayMenu;

    protected override void OnInitialized()
    {
        _overlayMenu = @<Select DataSource=_list
            Placeholder="Select"
            ValueProperty="(c)=>c.Code"
            @bind-Value=_selectedValue1
            Bordered="false"
            Style="border:none;padding:0px"
            LabelProperty="c=>c.Country">
    </Select>;
        base.OnInitialized();
    }


}
