### ISSUE TITLE
When using the Template and Tree functions in the Table component, the expanded icons are misaligned.

### ISSUE THREAD

**Issue by codeox-he** [ant-design-blazor/ant-design-blazor#3513]
As shown in the following figure
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/57785609/c59ecf09-5c93-4b6b-a28e-1bcdce1ed2e4)
Attached is the code file that reproduces this flaw. Join the Blazor Server project and run it.
https://github.com/codeox-he/antd-test/blob/main/Pages/Tree1.razor

**Comment by ElderJames** [comment]
Thank for contacting us @codeox-he, this is beacuse the ColumnIndex can't be reset while the columns changed. We will fix this in #3321

**Comment by ElderJames** [comment]
track #4093
