### ISSUE TITLE
TreeSelect error style 

### ISSUE THREAD

**Issue by MoDao1990217** [ant-design-blazor/ant-design-blazor#3518]
### Describe the bug

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/148607947/bc966efd-7d70-4299-b4a5-27383b3a2129)
use TreeSelect ,element

There are many nodes in the tree, and style errors may be encountered

**Comment by ElderJames** [comment]
Thanks for contacting us @MoDao1990217 , please make the width of the select larger.

**Comment by MoDao1990217** [comment]
> Thanks for contacting us @MoDao1990217 , please make the width of the select larger.

Ok , Let me try
