### ISSUE TITLE
Blazor Web App and NET 8: Controls do not work

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3522]
I updated VS 2022 today and created a new **Blazor Web App** project in NET 8. Then I also installed Ant Nuget and when I start the app, the control element from Ant is also displayed (in my example Switch):

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/45635963/6645ca49-9b39-4b86-bea3-0c74fd6b163e)

However, when I try to click Switch, Control only moves a little, but does not switch and remains FALSE. The same applies to sliders, they are displayed, but you can't move them back and forward!

Did I forget to set something (because it is no longer **Blazor Server App** project but **Blazor Web App**)?

Regards
pc

**EDIT**

It seems to me that JavaScript is not found. I have set the path in the **App.razor** (because **_Host.cshtml** no longer exists in the **Blazor Web App** project!).

**App.razor**
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="web.styles.css" />
    <link rel="icon" type="image/png" href="favicon.png" />

    @* Ant *@
    <link href="_content/AntDesign/css/ant-design-blazor.css" rel="stylesheet" />
    
    <HeadOutlet />
</head>

<body>
    <Routes />
    <script src="_framework/blazor.web.js"></script>

    @* Ant *@
    <script src="_content/AntDesign/js/ant-design-blazor.js"></script>

</body>

</html>
```

**Comment by ElderJames** [comment]
Hello @true-perfect-code , you are right, most of the components need to run at Interactive render modes. So you need to specific a render mode for the component.

**Comment by true-perfect-code** [comment]
Currently I have

```
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
```

Is this right?

**Comment by true-perfect-code** [comment]
I got it to work!

Apparently you now have to specify the render mode for every page:

`@rendermode InteractiveServer`

**I would be very helpful if someone can confirm this.** This website from Microsoft helped me:

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0

Here is an example of my home page using Ant:

```
@page "/"
@rendermode InteractiveServer

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<br />
<br />

<Button Type="primary" OnClick="@ShowModal">
    Open Modal with customized footer
</Button>
@{
    RenderFragment footer = @<Template>
        <Button OnClick="@HandleOk" @key="@( "submit" )"
                Type="primary"
                Loading="@_loading">
            Submit
        </Button>
        <Button OnClick="@HandleCancel" @key="@( "back" )">Return</Button>
    </Template>;
}
<Modal Title="@("Title")"
       Visible="@_visible"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel"
       Footer="@footer">
    <p>Some contents...</p>
    <p>Some contents...</p>
    <p>Some contents...</p>
    <p>Some contents...</p>
    <p>Some contents...</p>
</Modal>

<div>
    <Switch @bind-Checked="switchValue"/>
</div>


@code {
    bool _visible = false;
    bool _loading = false;
    bool switchValue { get; set; }

    private void ShowModal()
    {
        _visible = true;
    }


    private async Task HandleOk(MouseEventArgs e)
    {
        _loading = true;
        await Task.Delay(3000);
        _visible = false;
        _loading = false;
    }

    private void HandleCancel(MouseEventArgs e)
    {
        _visible = false;
    }
}
```

**Comment by ElderJames** [comment]
You can also set rendermode for root component
```
   <Routes  @rendermode="RenderMode.InteractiveAuto" />
```

**Comment by true-perfect-code** [comment]
Hi @ElderJames 

I would like that better, because then I can skip the line **@rendermode InteractiveServer** in every page. Now if I do it this way, I get an error message

**A component of type 'Microsoft.AspNetCore.Components.Routing.Router' has render mode 'InteractiveAutoRenderMode', but the required endpoints are not mapped on the server. When calling 'MapRazorComponents', add a call to 'AddInteractiveWebAssemblyRenderMode'. For example, 'builder.MapRazorComponents<...>.AddInteractiveWebAssemblyRenderMode()'**

If I change it to **@rendermode="RenderMode.InteractiveServer"** I get following error:

**Cannot pass RenderFragment<T> parameter 'Found' to component 'Router' with rendermode 'InteractiveServerRenderMode'. Templated content can't be passed across a rendermode boundary, because it is arbitrary code and cannot be serialized.**

I put changes in file

**Routes.razor**

```
<Router AppAssembly="@typeof(Program).Assembly" @rendermode="RenderMode.InteractiveAuto">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
</Router>

<AntContainer />
```

**Comment by true-perfect-code** [comment]
I got it working. The customisation you specified is not to be made in the **Routes.razor** file (as I did), but in the **App.razor** file. 

**App.razor**
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="web.styles.css" />
    <link rel="icon" type="image/png" href="favicon.png" />

    @* Ant *@
    <link href="_content/AntDesign/css/ant-design-blazor.css" rel="stylesheet" />
    
    @* <HeadOutlet @rendermode="new InteractiveServerRenderMode(prerender: true)" /> *@
    <HeadOutlet />
</head>

<body>
    @* <Routes /> *@
    <Routes @rendermode="RenderMode.InteractiveServer" />

    <script src="_framework/blazor.web.js"></script>

    @* Ant *@
    <script src="_content/AntDesign/js/ant-design-blazor.js"></script>

</body>

</html>
```

I am closing this issue, everything has been clarified and there is enough information to help someone who has the same problem. 

_Just a short note: I have selected Server Mode here, but if you want to support WebAssembly and Server, then you have to add what EdlerJames has specified, but you also have to adapt mapping in Programm.cs according to this._

Thanks @ElderJames  for your suggestion.

pc

**Comment by ElderJames** [comment]
You are welcome @true-perfect-code , I found that a lot of people are asking this question these days, can you help me create a document to introduce AntDesign into Blazor WebApp to explain?

**Comment by true-perfect-code** [comment]
How exactly can I help you? Is there a template of what the documentation should look like or is it enough if I send you a Word/Pdf file where everything is summarised?

MAUI Blazor is still open. I can't find the same settings there as with Blazor Web App. Actually, I have a feeling that MAUI Blazor will continue to use Blazor Server, but that would be almost impossible! Unfortunately I haven't found any suitable documentation yet and I'm still searching.

Regards
pc

**Comment by ElderJames** [comment]
I think we could update the readme and the site about setup antblazor on Blazor WebApp.

MAUI Blazor still stay the same that using blazor hybird mode (blazor.webview.js).

**Comment by true-perfect-code** [comment]
Well, I'll take over, because a few things have changed in Blazor and the installation instructions currently lead a beginner to a dead end.

**Comment by true-perfect-code** [comment]
@ElderJames 
Hi ElderJames, I updated the readme on github. Please check it and let me know if it's okay? Thanks

**Comment by ElderJames** [comment]
Thanks @true-perfect-code , but where is your updated?

**Comment by true-perfect-code** [comment]
Sorry, I forgot to create a pull request. Now you should be able to see it in GitHub.
