### ISSUE TITLE
The OnKeyUpAsync and OnKeyDownAsync events of Select related components will throw a null reference exception.

### ISSUE THREAD

**Issue by codeox-he** [ant-design-blazor/ant-design-blazor#3523]
When the browser has enabled the function of saving login username and password.

The OnKeyUpAsync and OnKeyDownAsync events of the Select related components placed within the Drawer component will throw a null reference exception.

This is caused by the browser's automatic fill function

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/57785609/38084ca0-fa28-44ff-8ab2-6b6c50cfca3f)

For example, in the following figure, 'yunwei' is the login username saved by the browser, which is automatically populated into this Select component. An empty reference exception will be thrown.
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/57785609/313d96ff-9440-4b9e-8834-2788f43dc54b)

**Comment by ElderJames** [comment]
Thanks for @codeox-he , please feel free to send a PR for that.
