### ISSUE TITLE
Change Hover Style and Color for TABLE Rows

### ISSUE THREAD

**Issue by hamiddd1980** [ant-design-blazor/ant-design-blazor#3531]
I would like to know whether is there any way to change **Hover Style and Color** for Table Rows?
If this capability is not implemented, so please add something like **RowClassName** to customize **Hover Style and Color** in **TABLE** Component.
This is especially a problem when you set Row text color to White width dark background.

### Describe the solution you'd like
please add some functionality to Table Component to **customize HOVER Style and Color** (something like **RowClassName**  in **TABLE** Component)

**Comment by ElderJames** [comment]
Hello @hamiddd1980 , yes you can use RowClassName to change the hover styles. Or just change the original class with the selector `ant-table-row:hover`.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/32abcc29-a2e0-40c5-8105-d42d3fcfa5a2)

**Comment by Tayyabsami1** [comment]
Thanks alot Brother
