### ISSUE TITLE
IMessageService cannot work on .Net 8 Blazor Web App

### ISSUE THREAD

**Issue by sxbyl** [ant-design-blazor/ant-design-blazor#3533]
### Describe the bug

MessageService notify cannot close automatically or can't display.

### Steps to reproduce (please include code)
1. Create a new .net 8 Blazor Web App and set the interactive render mode to server.
2. Configure AntDesign Blazor related code
3. Edit Home.razor as below code
```

@page "/"
@inject IMessageService messageService
@rendermode InteractiveServer
<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

@code {
    protected override void OnInitialized()
    {
        var _ = messageService.Info("Test 1");
    }
    protected override void OnAfterRender(bool firstRender)
    {
        var _ = messageService.Info("Test 2");
    }
}
```

4. Run the project

After the web is launched, the page shows notify “Test 1” correctly, but it does not close automatically. “Test 2” notify does not show.

### Further technical details
- AntDesign 0.16.2

**Comment by ElderJames** [comment]
Thanks for contacting us @sxbyl , you need to set the rendermode for `<AntContainer @rendermode="@InteractiveServer" />`.

**Comment by sxbyl** [comment]
> Thanks for contacting us @sxbyl , you need to set the rendermode for `<AntContainer @rendermode="@InteractiveServer" />`.

Thank you so much! It works!

**Comment by ogix** [comment]
BTW, what is the correct location now to put <AntContainer/> in .NET 8 WebApp?

**Comment by ElderJames** [comment]
Hello @ogix , same as before, in `App.razor`.
