### ISSUE TITLE
希望Modal对话框可以去除模态模式,让弹窗时可以点击到原本页面上的内容

### ISSUE THREAD

**Issue by shur520** [ant-design-blazor/ant-design-blazor#3548]
Mask="false" 只是把遮罩层去掉了,但是Modal本身就占满了全屏,导致无法操作页面上的内容

![QQ图片20231202173419](https://github.com/ant-design-blazor/ant-design-blazor/assets/76552883/7acef836-0081-484f-9633-e8e7db54a43e)

希望能弄一个非模态的窗口,弹出时页面可以正常操作,需求场景如下:
1:弹出框是要回复信息,信息内容在页面上,需要去复制页面信息来回复
2.弹出框是个参考信息,需要回到页面上去查询,又不想关闭弹出框

**Comment by zxyao145** [comment]
@shur520 很理解这个需求，但是很抱歉，Modal 无法实现这个功能。

1. AntDesign Blazor 是 AntDesign 的 blazor 实现，为了复用 Antd 的样式，所有的 DOM 结构都需要和原生的 React 是保持一致的。
2. 为了实现 Modal 在页面内能够居中，必须要有一个 DIV 填充 viewport，当然这个 DIV 的另一个作用，也是用来**确保用户想要对对话框以外的内容进行操作时，必须先对该对话框进行响应** ，这个是模态框本身应该具有特性。

就我所了解的 Blazo 组件库（MASA、Mud、FluentUI），没有哪个的 Modal/Dialog 具备这个能力。

对于该需求，我建议以下建议：
1. 保持现状，设置 Modal 的 DestroyOnClose 为false（默认实现），关闭后再打开，之前的状态会被保留。
3. 可以在打开 Modal 的时候，将要复制的内容填充到 Modal 中的对应位置。
4. 使用 Drawer，并且设置 Mask 为 false。
5. 使用其他组件，或者自定义实现。

**Comment by zxyao145** [comment]
@ElderJames 是的，但是 dialog 不等于 modal。

@shur520 我看了 TDesign 的实现，只需要加一行 css 代码即可。

```css
.ant-modal-wrap {
    pointer-events: none;
}
```

**Comment by shur520** [comment]
@zxyao145 太感谢了,解决了困扰我很久的一个大问题,我全站都需要这种不带遮罩的弹窗,希望这个设置可以加到Modal参数里
