### ISSUE TITLE
ReusbTabs did not load the page

### ISSUE THREAD

**Issue by elitesw** [ant-design-blazor/ant-design-blazor#3563]
## When using ReuseTables, it will not be displayed when the home page (@ page "/") attribute Pin=true, and clicking on the menu navigation will allow it to be displayed.  Without setting the Pin property, it can be displayed

# Razor Page Code
![q2_01](https://github.com/ant-design-blazor/ant-design-blazor/assets/54815375/058fcb43-1590-4df9-9141-934685f3c64c)

# Open or refresh the page
![q2_02](https://github.com/ant-design-blazor/ant-design-blazor/assets/54815375/9e186600-ed53-4fc4-b359-a348f70607bc)

# After clicking on the navigation menu
![q2_03](https://github.com/ant-design-blazor/ant-design-blazor/assets/54815375/d6d85010-437f-4d1c-982a-df5dc41df80c)

**Comment by ElderJames** [comment]
Thanks for contacting us @elitesw , which AntDesign version you are using? 
You can try call the `TabService.ReloadPage();` for workaround.

**Comment by elitesw** [comment]
# Issue versions: 0.16.0, 0.16.3

# No effect. It didn't enter the CS file code, strangely enough, it can execute the code GetPageTitle() in Razor. In addition, executing ReloadPage() in OnInitializedAsync will cause duplicate refreshes.

#Razor Code
![q2_04](https://github.com/ant-design-blazor/ant-design-blazor/assets/54815375/8cf7c563-ddc6-4375-a861-05d5ac61217d)

# CS Code
![q2_05](https://github.com/ant-design-blazor/ant-design-blazor/assets/54815375/00722798-302c-46db-921c-c0afcc289320)
