### ISSUE TITLE
TreeSelect OnSelectedItemChanged Bug

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design-blazor/ant-design-blazor#3567]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/d8b6398f-c175-4730-91e8-d747e9112b86)
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/8dcd0eb3-a283-4096-aac4-c7766df48a2c)

In the OnProductSelectedItemChangedAsync method, the received parameter key is always empty

**Comment by ElderJames** [comment]
Thanks for contacting us @HuaFangYun , the `OnSelectedItemChanged` only work for `DataSource` mode. If you want to subscribe the value change, you can bind `ValueChanged` evnet.

**Comment by HuaFangYun** [comment]
thanks
