### ISSUE TITLE
In WebAssembly Error~

### ISSUE THREAD

**Issue by wf-soft** [ant-design-blazor/ant-design-blazor#357]
Unhandled exception. Mono.Linker.OutputException: Failed to write 'obj\Release\netstandard2.1\blazor\linker/Oracle.ManagedDataAccess.dll

**Comment by wf-soft** [comment]
Sorry! It seems that the exception was caused by another DLL

**Comment by ElderJames** [comment]
Fine.
BTW, thank you for using our project @wf-soft .
