### ISSUE TITLE
The column filter in the table component does not support the date format.

### ISSUE THREAD

**Issue by weifan999** [ant-design-blazor/ant-design-blazor#3582]
look the down:

 <PropertyColumn Width="5%" Title="签约日期" Property="c=>c.CardDate" Ellipsis Filterable>@context.CardDate?.ToShortDateString()</PropertyColumn>

![QQ图片20231222161331](https://github.com/ant-design-blazor/ant-design-blazor/assets/154586551/f8cdcde5-1de5-4fcb-875c-66ba157c35f2)

**Comment by weifan999** [comment]
the razor write this: <PropertyColumn Width="5%" Title="签约日期" Property="c=>c.CardDate" Ellipsis Filterable>@context.CardDate?.ToShortDateString()</PropertyColumn>

but in the browser press F12 happen this error like the up image。
how to solve this question?

**Comment by ElderJames** [comment]
We will support getting format from column definition by default .
