### ISSUE TITLE
EnumRadioGroup

### ISSUE THREAD

**Issue by 925934787** [ant-design-blazor/ant-design-blazor#3588]
Can the RadioButton property be placed in a RadioGroup, or can it be displayed as a RadioButton when using EnumRadioGroup?

**Comment by ElderJames** [comment]
Thanks for contacting us @925934787 , this is a good idea. we will add this in next release.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/e283ae6c-63f3-4cfa-9518-aaf296ed024e)
