### ISSUE TITLE
Select show placeholder when select value

### ISSUE THREAD

**Issue by YingXiaoMing** [ant-design-blazor/ant-design-blazor#3601]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/16699795/14538fbc-cbe8-4b95-9283-ae8a0994bcb0)

**Comment by YingXiaoMing** [comment]
i solve it by css. but it not real clean the placeholder
`
.ant-select-show-search .ant-select-selector .ant-select-selection-search {
    color: transparent;
}
`
`
.ant-select-focused .ant-select-selector .ant-select-selection-search {
    color: #333;
}
`
`
.ant-select-focused .ant-select-selector .ant-select-selection-item {
    color: transparent !important;
}
`

**Comment by notsonormal** [comment]
I can confirm that I have the same problem when using Search on the Select component. 

You can even see this issue on the documentation page in the Select component. Go to the section for "Select with search field" and enter "om" and select "Tom". The result will match the screenshot in the YingXiaoMing's post above.

https://antblazor.com/en-US/components/select#ant-blazor-8e429b98-0dcb-4632-aa70-06518bf89469

In .NET 7 this starts happening in 0.17.0, 0.16.3 seems fine. Oddly, in .NET 8 this seems to happen older versions of the Nuget package.

**Comment by ElderJames** [comment]
Thanks for contacting us @YingXiaoMing @notsonormal , we will fix this later.
