### ISSUE TITLE
The Tabs Components `s API:Type , Can`t work fluently in Blazor!

### ISSUE THREAD

**Issue by Diserry** [ant-design-blazor/ant-design-blazor#3603]
I used the Component Tabs in Blazor just now , And I want the "Tabs" show "Card" in its face , but it seems that the Blazor Can`t recognize the parameter "Card" in Component Tabs , Blazor only think that just a type in Ant Design . but I see in the document that the API Type just need a "string", And even I never just use string as a parameter in Type , I used  Card as the Type`s parameter ,  the Blazor can`t compile the code also , the Error reporting like blow picture.
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/93862715/a1955176-6d23-418b-ace0-296352b15f8a)
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/93862715/52e5791b-4ce9-4267-ad20-10a9352621f3)
So this is the last Solution of mine , but I think the experience was terrible.Hope you can solve this problem , Tank you!
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/93862715/080cb2ce-07b3-4cfb-96a9-b2cfd0de4124)
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/93862715/f8a34462-efda-48e5-8fc0-f4ec306dca4d)

**Comment by ElderJames** [comment]
Thanks for contacting us @Diserry ，do you mean this is an documentation issue, right?

**Comment by ElderJames** [comment]
You need to assign the TabType.Card to the parameter.

`<Card Type="TabType.Card"> ...`
