### ISSUE TITLE
Menu inlinemode InlineCollected Conflict

### ISSUE THREAD

**Issue by bxjg1987** [ant-design-blazor/ant-design-blazor#3604]
### Describe the bug
Menu inlinemode InlineCollected Conflict

### Steps to reproduce (please include code)
<Menu Mode=MenuMode.Inline InlineCollapsed=true>

### Exceptions (if any)
```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Menu in the inline mode cannot be InlineCollapsed
      System.ArgumentException: Menu in the inline mode cannot be InlineCollapsed
         at AntDesign.Menu.OnInitialized()
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

### Further technical details
.net8 antblazor0.17.1 vs2022 17.8.3

**Comment by ElderJames** [comment]
Thanks for contacting us @bxjg1987 ,are you using static ssr?

**Comment by bxjg1987** [comment]
> Thanks for contacting us @bxjg1987 ,are you using static ssr?

yes. 

and i tested.   @rendermode="new  InteractiveAutoRenderMode(false)"  ,it same issue
