### ISSUE TITLE
onConfigLoaded() failed DOMException

### ISSUE THREAD

**Issue by jirisykora83** [ant-design-blazor/ant-design-blazor#3606]
### Describe the bug

After upgrading to the last version i got an error which seems to be related to this project.

`dotnet.js?v=29f560df8b1fd7117419d59d5044d55f34affd97:3 MONO_WASM: onConfigLoaded() failed DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at loadScriptAndStyle (-omit-/_content/AntDesign/AntDesign.lib.module.js:22:23)
    at beforeStart (-omit-/_content/AntDesign/AntDesign.lib.module.js:9:4)`

dotnet.js?v=29f560df8b1fd7117419d59d5044d55f34affd97:3 MONO_WASM: Failed to load config file ./blazor.boot.json NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at loadScriptAndStyle (-omit-/_content/AntDesign/AntDesign.lib.module.js:22:23)
    at beforeStart (-omit-/_content/AntDesign/AntDesign.lib.module.js:9:4)

Is there any change from 0.16.3 which could cause this?

**Comment by jirisykora83** [comment]
ok sorry i read change log and i need to adjust js/css first

**Comment by jirisykora83** [comment]
is there example if site was hosted on `/admin/...` for example

**Comment by jirisykora83** [comment]
This do not take in account if it includes `asp-append-version="true"`
```
 if (!document.querySelector('[src="_content/AntDesign/js/ant-design-blazor.js"]')) {
        var customScript = document.createElement('script');
        customScript.setAttribute('src', '_content/AntDesign/js/ant-design-blazor.js');
        document.body.insertBefore(customScript, document.querySelector('[antblazor-js]') || document.querySelector('script'));
    }
```

Also, in case it is hosted in subpath as `/sub-path` it may not work (depending on how the host page looks).

And also, whole `insertBefore `seems to be tricky should be better to insert before `</body>`?

**Comment by ElderJames** [comment]
Thanks for contacting us @jirisykora83, in this version, you need to put all the scripts in the body, and the next version will fix this. Or you can import this file manually
`<script src="_content/AntDesign/js/ant-design-blazor.js"></script>`
