### ISSUE TITLE
Opt-Out - Javascript initializers

### ISSUE THREAD

**Issue by mkalinski93** [ant-design-blazor/ant-design-blazor#3607]
Hello there,

is it possible to opt-out the javascript initailizers for the style/script auto-import feature?
Reason for that is, that if you want to use the dark theme
```html
<link href="_content/AntDesign/css/ant-design-blazor.dark.css" rel="stylesheet">
```

  the regular theme will be inserted as well.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/64005967/fba5e11c-076b-4bc0-8b9c-2f0882ce1b22)

**Comment by ElderJames** [comment]
Thanks for contacting us @mkalinski93 , we will add a flag to disable them.
