### ISSUE TITLE
Modal dialog becomes unusable after browser back button is clicked

### ISSUE THREAD

**Issue by dimmik** [ant-design-blazor/ant-design-blazor#3613]
### Describe the bug

Modal dialog becomes unusable after browser back button is clicked

### Steps to reproduce (please include code)
1. Go to https://antblazor.com/en-US/components/overview
2. (from there, not directly) Go to **Modal** component (https://antblazor.com/en-US/components/modal)
3. Open Modal dialog (First example, "Examples" -> **Open Modal**)
4. Click "back" browser button
5. Voila, Modal is open, _OK_, _Cancel_ and "close" (x on top-right) are not functioning.

### Exceptions (if any)
N/A (reproducible on official component description page)

### Further technical details
N/A (reproducible on official component description page)

**Comment by zxyao145** [comment]
When the URL changed, the Modal will be cleaned up, but the dom has not been cleaned up yet.

**Comment by ElderJames** [comment]
Hello @dimmik , this issue have been fixed in 0.17.3.1.

**Comment by dimmik** [comment]
> Hello @dimmik , this issue have been fixed in 0.17.3.1.

yes, already checked it and I am happy now ;)

**Comment by ElderJames** [comment]
@dimmik  Good to see you happy.😊

**Comment by dimmik** [comment]
I have a side question.
Recently I noticed messages like "NavigationManager_LocationChanged 1" and "NavigationManager_LocationChanged 2" in console.
I looked through all my code (I also tried to do something to fix the issue, subscribed to nav manager, and theoretically could have commited something alike), but found nothing.

Are the messages part of this fix? Just need confirmation to stop worrying
