### ISSUE TITLE
ModalService-created Modal Form does not trigger immediate table data update in Blazor WebAssembly

### ISSUE THREAD

**Issue by ujkk858** [ant-design-blazor/ant-design-blazor#3619]
I am currently using ModalService to create a modal form in my Blazor WebAssembly project. Upon clicking "Save" and returning, I intend to refresh the data table. The code to refresh the data table is executing correctly, but the new data is not promptly rendering in my table.

I am using Blazor WebAssembly mode, Ant Design Blazor version 0.17.1.3. If I add a new button to call the table refresh code _table.ReloadData(), there is no issue. The problem only occurs when executing it upon closing the modal. I have tried changing it to an asynchronous mode or calling StateHasChanged(), but neither seems to have any effect.

Below is my code, and I would appreciate guidance on how to correctly trigger the rendering:
`
public partial class Index
{
    private DeviceOutput[] _items = [];
    private int _total;
    private bool _loading;
    private ModalRef _modalRef;
    private ITable _table;
    
    [Inject] protected IDeviceService DeviceService { get; set; }
    [Inject] protected ModalService ModalService { get; set; }

    private async Task QueryData(QueryModel<DeviceOutput> queryModel)
    {
        _loading = true;
        var result = await DeviceService.GetList(new PagedResultRequestDto
        {
            SkipCount = (queryModel.PageIndex - 1) * queryModel.PageSize,
            MaxResultCount = queryModel.PageSize,
        });
        _items = result.Items.ToArray();
        _total = (int)result.TotalCount;
        _loading = false;
    }

    private async Task EditDeviceName(long id,string deviceName)
    {
        _modalRef=await ModalService.CreateModalAsync<EditDeviceName, EditDeviceInput>(new ModalOptions
        {
            Title = "编辑设备名称",
            MaskClosable = false,
        }, new EditDeviceInput
        {
            Id = id,
            DeviceName = deviceName,
        });
        _modalRef.OnOk = () =>
        {
            _table.ReloadData();
            StateHasChanged();
            return Task.CompletedTask;
        };

    }

    private void ReLoad(MouseEventArgs arg)
    {
        _table.ReloadData();
    }
}

`

Environment:
Net 8.0
Ant Design Blazor Version: 0.17.1.3
Blazor WebAssembly

**Comment by ElderJames** [comment]
Thanks for contacting us @ujkk858 ,please provide the razor template. We need to debug locally.

**Comment by ujkk858** [comment]
[antsimp.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/13931519/antsimp.zip)
After debugging, I found that this issue only occurs after initiating an HTTP request. If it is local static data, the issue does not exist.    @ElderJames

**Comment by ElderJames** [comment]
@ujkk858 please try the latest version.

**Comment by ujkk858** [comment]
@ElderJames  Thank you, we have upgraded to the latest version and the issue has been resolved
