### ISSUE TITLE
Wrong path of AntDesign.lib.module.js in blazor.boot.json in 0.17.x

### ISSUE THREAD

**Issue by hu-xd** [ant-design-blazor/ant-design-blazor#3622]
### Describe the bug

I have a (hosted) .NET 8.0 Blazor Wasm app that worked fine before with AntBlazor 0.16.x, but its now broken with AntBlazor 0.17.x, from 0.17.0 to 0.17.2
the problems a 404 error of this script file: AntDesign.lib.module.js

my BlazorWasm app is not hosted in the root of my ASP.NET app, its path is /admin/
so I have this tag in index.html:
`    <base href="/admin/" />`
and this in .csproj:
`    <StaticWebAssetBasePath>admin</StaticWebAssetBasePath>`
and other corresponding settings in the Server app program.cs like:
`  app.UseBlazorFrameworkFiles("/admin");`
etc.

the correct file path of AntDesign.lib.module.js should be 
`/_content/AntDesign/AntDesign.lib.module.js`
but now its loading from
`/admin/_content/AntDesign/AntDesign.lib.module.js`
which caused 404 error.

I noticed this part of blazor.boot.json

```
        "libraryInitializers": {
            "_content/AntDesign/AntDesign.lib.module.js": "sha256-Y7oJ7/rOncGnhfBrDAPc045cW9bF4cp1INbpZClDsxM="
        },
        "modulesAfterConfigLoaded": {
            "../_content/AntDesign/AntDesign.lib.module.js": "sha256-Y7oJ7/rOncGnhfBrDAPc045cW9bF4cp1INbpZClDsxM="
        }
```
it looks like the libraryInitializers is wrong, but the modulesAfterConfigLoaded is (likely?) correct.

not sure if/how I can fix it ? or is it a bug ?

**Comment by ElderJames** [comment]
Thanks for contacting us @hu-xd , this is correct. Beacuse you changed the base path, you need to publish all the static file base on the base path,including the blazor publish directionay.

**Comment by hu-xd** [comment]
but how can I fix it ? any sample/guide ?

**Comment by hu-xd** [comment]
>

**Comment by hu-xd** [comment]
but how can I fix it ? any sample/guide ?

**Comment by hu-xd** [comment]
well, currently I can workaround the problem with this change:

in server side Program.cs, change from:
`app.UseStaticFiles()`
to:
```
app.UseStaticFiles();
app.UseStaticFiles("/admin");
```
so all the static assets can be accessed from both of the two base urls. it works but its feels like a hack.

**Comment by hu-xd** [comment]
all right, after more research now I think this is some quirky thing of Blazor itself, not a bug in AntDesign, so I'm closing this issue :-)
