### ISSUE TITLE
PathExtensions not available in 0.17.2

### ISSUE THREAD

**Issue by 707wk** [ant-design-blazor/ant-design-blazor#3623]
When 0.16.3 update to 0.17.2, PathExtensions not available.

![图片](https://github.com/ant-design-blazor/ant-design-blazor/assets/11644507/8c00ceea-be11-4539-826d-b38c79c94046)
0.16.3

![图片](https://github.com/ant-design-blazor/ant-design-blazor/assets/11644507/43630667-8c21-4b94-b6ff-6676baf6e5ce)
0.17.2

**Comment by ElderJames** [comment]
Thanks for contacting us @707wk , we will release a new API in next version.

**Comment by ElderJames** [comment]
Please use PathHelper
