### ISSUE TITLE
Create modal API have errros with   fluentValidation

### ISSUE THREAD

**Issue by Hunglmc** [ant-design-blazor/ant-design-blazor#3633]
Create modal API have errros with   fluentValidation

 Hi  Team.

I have initialized the model from the server with the code below. In the templete view if I use the variable "Validated" it will cause an error. Please let me know where I am wrong or if there is a problem with the code
```
 private async Task<ModalRef> InvokeModal(string id = null)
 {
     RenderFragment dialog = builder =>
     {
         builder.OpenComponent<RoleModal>(0);
         if (id != null)
         {
             _role = _roleList.FirstOrDefault(c => c.Id == id);
             if (_role != null)
             {
                 builder.AddAttribute(1, nameof(RoleModal.RoleModel), new RoleRequest
                 {
                     Id = _role.Id,
                     Name = _role.Name,
                     Description = _role.Description
                 });
             }
         }
         builder.CloseComponent();
     };

     modalRef = await _modalService.CreateModalAsync(new ModalOptions()
     {
         Title = null,
         MaskClosable = false,

         Keyboard = false,
         Content = dialog,
         Footer = null,
         DestroyOnClose = true,
     });
     return modalRef;
 }
```

**Comment by zxyao145** [comment]
@Hunglmc Hi, could you provide a more complete demo?

**Comment by Hunglmc** [comment]
> @Hunglmc Hi, could you provide a more complete demo?

@zxyao145  Sorry I can't give you a complete demo but I will describe the order as follows with code:
  First, you create a "RoleModal" then in it you will have the following code:
<EditForm Model="@RoleModel" OnValidSubmit="SaveAsync">
     <FluentValidationValidator @ref="_fluentValidationValidator" />
     <div>
         <div class="p-5 text-center">
             @{
                 if (RoleModel?.Id == null)
                 {
                     <div class="text-2xl mt-5">Add new permission group</div>
                 }
                 else. else
                 {
                     <div class="text-2xl mt-5">Update permission group</div>
                 }
             }
         </div>
         <div class="modal-body p-0">
             <div class="validate-form">
                 <div class="input-form mb-4">
                     <label class="form-label w-full flex flex-col sm:flex-row">
                         Permission group name
                         <ValidationMessage class="text-danger sm:ml-auto mt-1 sm:mt-0 text-xs text-slate-500" For="@(() => RoleModel.Name)" />

                     </label>
                     <Input Style="border-radius: 5px;" @bind-Value="RoleModel.Name" type="text" name="name" class="form-control" placeholder="Administrator" minlength="2">
                 </div>
                 
                 <div class="input-form mt-3">
                     <label class="form-label w-full flex flex-col sm:flex-row">
                         Describe
                         <ValidationMessage For="@(() => RoleModel.Description)" class="sm:ml-auto mt-1 sm:mt-0 text-xs text-slate-500"></ValidationMessage>
                     </label>
                     <InputTextArea @bind-Value="RoleModel.Description" rows="3" id="validation-form-5" name="description" class="form-control" placeholder="Enter description: User can delete, update , ...">
                     </InputTextArea>
                 </div>
             </div>

         </div>
         <div class=" pb-8 text-center w-full">
             <button type="button" class="btn btn-outline-secondary mt-2 w-full mr-1" @onclick="OnCancelButtonClick">Exit</button>
           @{
             if (RoleModel?.Id == null)
             {
             <button type="button" Disabled="@(!Validated || loading )" class="btn w-full @(Validated?"btn-outline-secondary":"btn-primary")">@(loading ? "The request is being processed..." : "Add new role")</button>
             }
             else. else
             {
             <button type="button" class="btn @(Validated?"btn-outline-secondary":"btn-primary") w-full">Update permission group</button>
             }
             }
         </div>
     </div>
</EditForm>
  and next you create a partial RoleModal class

   contains the following code
         private FluentValidationValidator _fluentValidationValidator;
         private bool Validated => _fluentValidationValidator.Validate(options => { options.IncludeAllRuleSets(); });

Then you create a table view with the onlick action and make a call to the function as I provided.
You will see related error messages

**Comment by Hunglmc** [comment]
@zxyao145  nếu tôi  tôi bỏ comment đoạn code này thì lỗi,  bất cứ biến gì được khai báo trong partail mà không truyền từ  ngoài vào đều gây lỗi.`<div class=" pb-8 text-center w-full">
         <button type="button" class="btn btn-outline-secondary mt-2 w-full mr-1" @onclick="OnCancelButtonClick">Exit</button>
       @{
         if (RoleModel?.Id == null)
         {
         <button type="button" Disabled="@(!Validated || loading )" class="btn w-full @(Validated?"btn-outline-secondary":"btn-primary")">@(loading ? "The request is being processed..." : "Add new role")</button>
         }
         else. else
         {
         <button type="button" class="btn @(Validated?"btn-outline-secondary":"btn-primary") w-full">Update permission group</button>
         }
         }
     </div>`

**Comment by zxyao145** [comment]
@Hunglmc Hi, are you using this library in conjunction with https://github.com/Blazored/FluentValidation? I need to spend some time investigating.

**Comment by Hunglmc** [comment]
> @Hunglmc Hi, are you using this library in conjunction with https://github.com/Blazored/FluentValidation? I need to spend some time investigating.

@zxyao145 Just like you said, I'm using this library, and above all, it seems that every variable declared in the templete partail component without passing it in from outside causes an error.

**Comment by zxyao145** [comment]
@Hunglmc Have you encountered this error: `Object reference not set to an instance of an object.`?

**Comment by Hunglmc** [comment]
@zxyao145  Yes. But with fluentValidation it have errors with validator

**Comment by zxyao145** [comment]
@Hunglmc I think this is in line with expectations. 

The browser will first render the parent component and then render the child components. When rendering `RoleModal`, `FluentValidation` has not yet been rendered, so `_fluentValidationValidator` is null.

Try to modify it in the following way:

```c#
private bool Validated => _fluentValidationValidator?.Validate(options => { options.IncludeAllRuleSets(); }) ?? false;

```

**Comment by Hunglmc** [comment]
@zxyao145 Thank you for your explanation. By the way, I would like to ask if the blazor library does not have onPopupScroll in the select section? I need it to be able to load when scrolling to a limit of one point with select

**Comment by zxyao145** [comment]
> @zxyao145 Thank you for your explanation. By the way, I would like to ask if the blazor library does not have onPopupScroll in the select section? I need it to be able to load when scrolling to a limit of one point with select

Perhaps @ElderJames  is needed to answer?

**Comment by ElderJames** [comment]
@Hunglmc Not yet. PR is welcome.

**Comment by Hunglmc** [comment]
@zxyao145  @Hunglmc I think this is in line with expectations.

The browser will first render the parent component and then render the child components. When rendering RoleModal, FluentValidation has not yet been rendered, so _fluentValidationValidator is null.

Try to modify it in the following way:

**private bool Validated => _fluentValidationValidator?.Validate(options => { options.IncludeAllRuleSets(); }) ?? false;**
This method solves the problem, but causes an error message to be displayed without clicking

**Comment by zxyao145** [comment]
@Hunglmc Hi, this is just an example, telling you how to solve the problem of referencing before `_fluentValidationValidator` is initialized. 

You should judge whether there has been clicked or use an enum with three states: `NotClicked`, `Invalid`, and `Valid`, I think this may solve your problem. 

I'm sorry that I can't provide you with a better solution, because I haven't used FluentValidation library yet

**Comment by ElderJames** [comment]
> @zxyao145 @Hunglmc I think this is in line with expectations.
> 
> The browser will first render the parent component and then render the child components. When rendering RoleModal, FluentValidation has not yet been rendered, so _fluentValidationValidator is null.
> 
> Try to modify it in the following way:
> 
> **private bool Validated => _fluentValidationValidator?.Validate(options => { options.IncludeAllRuleSets(); }) ?? false;** This method solves the problem, but causes an error message to be displayed without clicking

This is because the Validated property would call Validate by its getter. So you need to Validate the form when you click the confirm button, and assign the validate status to Validated property.
