### ISSUE TITLE
Big issue with drawers/modals using .NET 8

### ISSUE THREAD

**Issue by manuelelucchi** [ant-design-blazor/ant-design-blazor#3638]
### Describe the bug

After I updated to .NET 8, after a random number of interations with Drawers and Modals, the browser gives this error 

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/17146198/d8f7c677-66de-44fb-9467-e93358907472)

I followed the stacktrace and found the error in 

```js
o.onLocationChanged = function() {
            s.manipulationHelper.enableBodyScroll(!0),
            r.modalHelper.destroyAllDialog(),
            document.querySelectorAll(".ant-drawer").forEach(function(t) {
                return document.body.removeChild(t) //<--- Here
            })
        }
```

in antdesign.blazor.js

After this error appears, most of the ant design components becomes unresponsive or half broken (for example the Segmented invokes the switches but doesn't switch the selected UI, while the menu component works fine), I guess it's because the js part of antdesign is not working anymore. I'm sorry but at the current state I can't provide any other informations as I'm struggling myself on this, I can just say this doesn't happen on .NET 7, maybe something AOT related? I already tried disabling it without differences

### Further technical details
- AntDesign Nuget Package version
17.3
- Include the output of `dotnet --info`
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.f64b8c85

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

Carichi di lavoro .NET installati:
 Workload version: 8.0.100-manifests.f64b8c85
 [ios]
   Origine dell'installazione: VS 17.8.34408.163
   Versioni del manifesto:    17.0.8490/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8490\WorkloadManifest.json
   Tipo di installazione:              Msi

 [android]
   Origine dell'installazione: VS 17.8.34408.163
   Versioni del manifesto:    34.0.52/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maui-windows]
   Origine dell'installazione: VS 17.8.34408.163
   Versioni del manifesto:    8.0.3/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maccatalyst]
   Origine dell'installazione: VS 17.8.34408.163
   Versioni del manifesto:    17.0.8490/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8490\WorkloadManifest.json
   Tipo di installazione:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2022 Latest Stable

**Comment by ElderJames** [comment]
Thanks for contacting us @manuelelucchi , we have known this issue and fixed it in #3634. I will release a beta versin later.

**Comment by manuelelucchi** [comment]
Thank you @ElderJames, nice to see you are so fast!

**Comment by ElderJames** [comment]
@manuelelucchi Please try the last version.

**Comment by manuelelucchi** [comment]
I've done some little testing with 17.3.1 and it seems to be fixed, so I'll close the issue, thank you!
