### ISSUE TITLE
[Feature Request] [PageHeader] Add conditional onBack method

### ISSUE THREAD

**Issue by ske66** [ant-design-blazor/ant-design-blazor#364]
would be great if the Page Header component allowed you to show and hide the back button. For example, my main page uses the Page Header but user's shouldn't be able to go back on root.

API Changes

```
<PageHeader Class="site-page-header" onBack=@onBackMethodCallback>  //default == true
    content...
</PageHeader>
```

**Comment by ElderJames** [comment]
Thank you for contacting us @ske66 
We will follow ant-design's implementation and I am adding a feature via ant-design/ant-design/pull/25664
