### ISSUE TITLE
inherits Table<> , StateHasChanged has no effect and first reload get  disposed exception 

### ISSUE THREAD

**Issue by ZetRe** [ant-design-blazor/ant-design-blazor#3643]
### Describe the bug

I inherited the table component, and after loading the data, the component statehaschanged  has no effect.

If the statehaschanged method passed into the page can change the state.

Loading=true is effect, but Loading=false  no effect.

And when I request data through WebApiclientCore, I get an exception (Cannot access a disposed object.
Object name: 'IServiceProvider') the first time I refresh the page. I will not report errors if I do not use the Table.

### Steps to reproduce (please include code)

```
#if NET6_0_OR_GREATER
    [CascadingTypeParameter(nameof(TItem))]
    [CascadingTypeParameter(nameof(TPrameter))]

#endif
    public partial class CasPageTable<TPrameter, TItem> : Table<TItem>
    {
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            // 调用父组件的渲染逻辑
            //base.BuildRenderTree(builder);
         
        }
 

        protected override Task OnInitializedAsync()
        {
             base.OnInitializedAsync();

            PaginationTemplate ??= BuildPaginationTemplate;
            PaginationPosition = "bottomRight";
            OnChange = EventCallback.Factory.Create<QueryModel<TItem>>(this, HandleTableChange);
            return Task.CompletedTask;
        }


        private RenderFragment<(int PageSize, int PageIndex, int Total, string PaginationClass, EventCallback<PaginationEventArgs> HandlePageChange)> BuildPaginationTemplate =>
        page => builder =>
        {

            builder.OpenComponent<BasicPagination>(0);
            builder.AddAttribute(1, nameof(Pagination.PageSize), page.PageSize);
            builder.AddAttribute(2, nameof(Pagination.Total), page.Total);
            builder.AddAttribute(3, nameof(Pagination.Current), page.PageIndex);
            builder.AddAttribute(4, nameof(Class), page.PaginationClass);
            builder.AddAttribute(5, nameof(Pagination.OnChange), page.HandlePageChange);
            builder.AddAttribute(6, nameof(Pagination.ShowQuickJumper), true);
            builder.AddAttribute(7, nameof(Pagination.ShowSizeChanger), true);
            builder.CloseComponent();
            builder.OpenElement(8, "div");
            builder.AddContent(9, page.PaginationClass);
            builder.CloseComponent();
        };


        [Parameter]
        public Func<PageRequest<TPrameter>, Task<DataResult<PageResult<TItem>>>> ApiAsync { get; set; }

        public async Task HandleTableChange(QueryModel<TItem> queryModel)
        {
            try
            {
                Loading = true;
                var pageRequest = new PageRequest<TPrameter>()
                {
                    PageSize = PageSize,
                    CurrentPage = PageIndex
                };
                var data = await ApiAsync(pageRequest);

                Loading = false;


                DataSource = data.Data.Items;
                Total = data.Data.TotalCount;
            }
            catch (Exception ex)
            {

            }
            finally
            {
                Loading = false;
                StateHasChanged();

            }
        }
    }



<CasPageTable @rendermode="RenderMode.InteractiveWebAssembly" TItem="SysUserQueryResult" TPrameter="SysUserQueryParam" 
              ApiAsync="GetPageList">

    <PropertyColumn Property="c=>c.Account"  />
    <PropertyColumn Property="c=>c.Phone"  />
    <PropertyColumn Property="c=>c.IsEnabled"  />
    <PropertyColumn Property="c=>c.Remark"  />

</CasPageTable>
 @code {
    [Inject]
    public ISysUserApi SysUserApi { get; set; }

    public async Task<DataResult<PageResult<SysUserQueryResult>>> GetPageList(PageRequest<SysUserQueryParam> request)
    {
        var result= await SysUserApi.GetPageListAsync(request).ConfigureAwait(false);
        return result;
    }
 }
```

### Further technical details
- AntDesign Nuget Package  0.17.3.1
- .NET 8
- VS2022 17.8.5

**Comment by ElderJames** [comment]
Thanks for contacting us @ZetRe , would you please provide a demo for debuging?

**Comment by ZetRe** [comment]
I think it's a pre-render problem.

page load is rendered twice, triggering two OnChange events for the table.

After the first page is pre-rendered, IServiceProvider is dispose and the request API is broken.

The second was rendered by WebAssembly. 

The following is my solution, I do not know if there is any better way for ant to adapt to the new version in the future
`      

       private bool isConnected;

       protected override Task OnAfterRenderAsync(bool firstRender)
       {
           if (firstRender)
           {
               isConnected = true;
               ReloadData();
               return Task.CompletedTask;
           }
           return base.OnAfterRenderAsync(firstRender);
       }      

      public async Task HandleTableChange(QueryModel<TItem> queryModel)
       {
           try
           {
               Loading = true;
               if (!isConnected)
               {
                   return;
               }

               var request = ConvertRequest(queryModel);

               var data = await ApiAsync(request);

               var result = ConvertResult(data);

               DataSource = result.DataSource;
               Total = result.Total;
           }
           catch (Exception ex)
           {
               DataSource = null; Total = 0;
           }
           finally
           {
               Loading = false;
               Refresh();

           }
       }`

**Comment by ElderJames** [comment]
Yes, this would be a issue about connection. But I can't reproduce your problem, please provide a project that can be debugged
