### ISSUE TITLE
When the browser F5 refreshes, how can ReuseTabs retain or initialize previously open tabs?

### ISSUE THREAD

**Issue by jxcproject** [ant-design-blazor/ant-design-blazor#3660]
Can ReuseTabsService add open tabs for method initialization?

**Comment by ElderJames** [comment]
Thanks for contacting us @jxcproject . This is a good idea. Are you interested in implementing this feature? 
You can add a method like the `(AddReuseTabsPageItem)(https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/tabs/Reuse/ReuseTabsService.cs#L166)`.

**Comment by jxcproject** [comment]
Ok, I'll try to implement it.

**Comment by jxcproject** [comment]
@ElderJames Hello, I added a method to the PR
https://github.com/ant-design-blazor/ant-design-blazor/pull/3671

**Comment by ElderJames** [comment]
@jxcproject Awesome!
