### ISSUE TITLE
After version 0.2.0-nightly-200713151818 I'm unable to login

### ISSUE THREAD

**Issue by nelsonbatista** [ant-design-blazor/ant-design-blazor#367]
Hello,

I'm implementing a solution with login with IdentityServer 4.
Starting with version 0.2.0-nightly-200713151818 the login does not complete.

The process is:
1. In a certain page, call the authentication/login 
2. The user is redirected to the IdentityServer. In here user log in and is redirected to the authentication/login-callback
3. The login is completed and redirected to the calling page.

Starting with version 0.2.0-nightly-200713151818, step 3 never executes. The RemoteAuthenticatorView CompletingLoggingIn event is called, but does not go from there. The browser freezes and some times it gives an error:
```
Stacktrace: 
Error
    at 640908 (https://localhost:44312/_framework/wasm/dotnet.3.2.0.js:1:19012)
    at _emscripten_asm_const_iii (https://localhost:44312/_framework/wasm/dotnet.3.2.0.js:1:19197)
    at wasm_logger (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[3126]:0x9ab09)
    at eglib_log_adapter (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[6030]:0x10e78d)
    at monoeg_g_logstr (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[4574]:0xc99e6)
    at monoeg_g_logv_nofree (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[2192]:0x60c59)
    at monoeg_g_log (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[132]:0x2ffc)
    at monoeg_malloc (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[161]:0x3c89)
    at stack_frag_new (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[2019]:0x59758)
    at add_frag (https://localhost:44312/_framework/wasm/dotnet.wasm:wasm-function[1430]:0x3ccf2)
Could not allocate 4096 bytes
undefined
undefined
Uncaught RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.Uncaught RuntimeError: abort(undefined).
```

Some times the step 2 freezes and the user is not redirected to the IdentityServer.

If I go back to version 0.2.0-nightly-200713124218 it works OK with a fast login.

Best regards,

**Comment by Ratomir** [comment]
Same here. I am not sure what was happened, I am still using 0.2.0-nightly-200713124218. 
I think that we should concentrate our attention to fix this.

**Comment by ElderJames** [comment]
Thank you for contacting us @nelsonbatista @Ratomir . 
We need more information for that. Can you provide a reproducible demo?

Sorry for the inconvenience.

**Comment by ElderJames** [comment]
I find out the related commit 22d991d29fdcac42dc8895579efb6fb00f4145c5 .

**Comment by ElderJames** [comment]
Did you use the avatar component @nelsonbatista @Ratomir ?  Please try to remove them. 
If this is its fault, I will try to fix it.

**Comment by nelsonbatista** [comment]
Hello ElderJames,

I have removed the Avatar and is working. I've tried the last version 0.2.0-nightly-200716103127.
Ratomir can you test it?

ElderJames, if you still want a test demo I can try to make one and send it.

Best regards,

**Comment by Ratomir** [comment]
@ElderJames  @nelsonbatista  I can reproduce the bug. Please, give a half-hour, I will try to create a project with Blazor start template. But, my assumption is moved to the Card component because I am using it at the index page, and the Card component at the moment has the issue on the demo site.

**Comment by ElderJames** [comment]
Good, I will try to fix the avatar component first, maybe until tomorrow in utc+8.

**Comment by Ratomir** [comment]
Here is my repo with the latest version of the package. https://github.com/Ratomir/367-20200713broken-build 
You can see if we add a wrapper with AuthorizeView around a Card component or inside of the component, the issue will arise. The bellow screenshot is related to the Index page in the repository. 
![image](https://user-images.githubusercontent.com/8688494/87699993-f2748b00-c795-11ea-92dd-43930ef09676.png)

Here is a code example.

` <Card Class="flex-fill" Hoverable Style="width: 18rem;" Title="@title">\n
    <Body>
        <p>Body text</p>
        <AuthorizeView>
            <Button Icon="book">Read</Button>
        </AuthorizeView>
    </Body>
</Card> `

Index [page](https://github.com/Ratomir/367-20200713broken-build/blob/master/StoNeRadi/Pages/Index.razor)

I will test it with the avatar component, as well.

**Comment by Ratomir** [comment]
The Avatar component has the same behavior. 
[Avatar page](https://github.com/Ratomir/367-20200713broken-build/blob/master/StoNeRadi/Pages/AvatarPage.razor)

**Comment by Brian-Ding** [comment]
@Ratomir I tried to downgrade the version of AntDesign in your demo repo to 0.1.0, or remove AntDesign completely, the same exception will pop up as in your screenshot.

So I suppose this is a Blazor issue not AntDesign, could you please try downgrade or remove AntDesign and share your result?

**Comment by ElderJames** [comment]
Hi, we have fixed the avatar issue, please try the last build and give us your feedback.

**Comment by nelsonbatista** [comment]
Hi ElderJames,

I've upgraded and added the avatar again and it is working.
Thank you very much for your help.

**Comment by Ratomir** [comment]
Hi, sorry, I forgot to include a script in the index page for the authentication service.  Never mind, I fixed that and upgrade the Ant-Design on the latest version and it works as expected on my demo repository. Also, It works now in my project, which is good.

We don't need to roll back into the past and looking differences between builds of 13th and 14th July. It would be hard to match that.

You can close the issue. 

Kind regards,

**Comment by ElderJames** [comment]
Thank you @nelsonbatista @Ratomir .
Enjoy it.😉
