### ISSUE TITLE
Can't programmatically add sorting to an existing column

### ISSUE THREAD

**Issue by LukasMendez** [ant-design-blazor/ant-design-blazor#3674]
### Describe the bug

I'm trying to implement router-based filtering and sorting. Right now I'm having issues with sorting. 
I have an "OrderBy" query parameter, which indicates the column that I would like to sort. Based on that I'm trying to create a new QueryModel, which includes the SortModel and then reload the table (this.table.ReloadData(queryModel)) 

So basically I just want to trigger sorting on the table programatically without having to actually click on the column, and without having to keep a previous state in memory. But I'm not sure if that's possible. 

### Steps to reproduce (please include code)

Here's the code that I'm using: 

```
        private QueryModel LoadQueryModelFromQueryParams()
        {
            if (this.table == null)
            {
                throw new NullReferenceException(nameof(this.table));
            }

            QueryModel currentTableState = this.table.GetQueryModel();
            IList<ITableSortModel> modifiedSortModels = new List<ITableSortModel>();

            string dateColumnName = "Date";
            if (OrderBy == dateColumnName.ToLower())
            {
                modifiedSortModels.Add(
                    new SortModel<DateTimeOffset>(
                        1,
                        0,
                        dateColumnName,
                        OrderBy?.ToLower() == dateColumnName.ToLower()
                            ? AntTableHelper.GetSortingDirectionBy(OrderDescending)
                            : null // Only set order direction if this column is actually marked for sorting
                    )
                );
            }

            QueryModel newTableState = new QueryModel(
                PageNo,
                PageSize,
                currentTableState.StartIndex,
                modifiedSortModels,
                currentTableState.FilterModel
            );

            return newTableState;
        }
```

The SortModel gets added to the collection, but then fails here when calling ReloadData(queryModel):  

```
            QueryModel queryModel = LoadQueryModelFromQueryParams();
            this.table!.ReloadData(queryModel);
```

I've tried to compare the SortModel created manually and the one generated by the table itself when clicking on the header to sort. 

And the only difference I could see is: 

__getFieldExpression_

### Exceptions (if any)
Unhandled exception rendering component: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1[[AntDesign.IColumn, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
   at AntDesign.Table`1[[BE.OM.IncidentLog.UI.Blazor.Shared.EventOverviewDto, BE.OM.IncidentLog.UI.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReloadData(QueryModel queryModel)
   at BE.OM.IncidentLog.UI.Blazor.Client.Pages.Event.Components.EventOverview`1[[BE.OM.IncidentLog.UI.Blazor.Shared.IncidentOverviewDto, BE.OM.IncidentLog.UI.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].LoadQueryParametersIntoView() in C:\Projekter\O&M Incident Log\Git Repository\src\BE.OM.IncidentLog\BE.OM.IncidentLog.UI.Blazor\Client\Pages\Event\Components\EventOverview.razor.cs:line 158
   at BE.OM.IncidentLog.UI.Blazor.Client.Pages.Event.Components.EventOverview`1.<OnInitializedAsync>d__104[[BE.OM.IncidentLog.UI.Blazor.Shared.IncidentOverviewDto, BE.OM.IncidentLog.UI.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\Projekter\O&M Incident Log\Git Repository\src\BE.OM.IncidentLog\BE.OM.IncidentLog.UI.Blazor\Client\Pages\Event\Components\EventOverview.razor.cs:line 145
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### Further technical details
AntDesign.ProLayout 0.16.2
.NET SDK:
Version: 7.0.400
Commit: 73bf45718d
Runtime Environment:
OS Name: Windows
OS Version: 10.0.19045
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\7.0.400\

Host:
Version: 7.0.14
Architecture: x64
Commit: 808851b07a

.NET SDKs installed:
7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
x86 [C:\Program Files (x86)\dotnet]
registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
Not set

global.json file:
Not found

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.7.1

**Comment by ElderJames** [comment]
Thanks for contacting us @LukasMendez , this is because in SortModels you need to replace the existing sormodel of the specfic culumn which you want to sort.

**Comment by LukasMendez** [comment]
@ElderJames 

Thank you for the example. Problem is that there's nothing to remove. 

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/43059840/fb0e6e4f-3a61-4bfd-b2a0-b487128d21a9)

As you can see from the image, the Count is 0 for SortModel. So query.SortModel.RemoveAt(0) would not remove anything. 

But visually you can see the column here: 

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/43059840/7894fabb-eade-4b29-a0ad-3a2a82624fbe)

My table is configured like this: 

```
            <Table
                   RemoteDataSource
                   RowKey="@(@event => @event.Id)"
                   Total="Total"
                   @ref="this.table"
                   Class="small-table-row-padding"
                   DataSource="@Events"
                   ScrollX="2500"
                   Loading="this.isTableLoading"
                   OnChange="@(EventCallback.Factory.Create<QueryModel<EventOverviewDto>>(this, async queryModel => await OnTableChangeAsync(queryModel)))"
                   Responsive>
                <ChildContent>
                    <PropertyColumn OnCell="OnCell" Width="90" Title="Date" Property="@(@event => @event.Date)" Sortable>
                        @context.Date.LocalDateTime.ToString("dd-MM-yyyy")
                     </PropertyColumn>
                     ......
                     ......
                 </ChildContent>
           </Table>
```

What am I missing here?

**Comment by ElderJames** [comment]
Please provide a demo for reproduce.

**Comment by ElderJames** [comment]
> Thank you for the example. Problem is that there's nothing to remove.

I will check this again.

**Comment by ElderJames** [comment]
Hello @LukasMendez , I can't reproduce your issue. Here I can get SortModels from queryModel

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/6bcb2d1b-413f-4348-b08a-6b956cf38ed4)

**Comment by ElderJames** [comment]
This work well

```
    void SetSorter()
    {
        var queryModel = Table.GetQueryModel() as QueryModel<Data>;
        queryModel.SortModel.Add(new SortModel<int>(0, 0, "Number", "ascend"));
        Table.ReloadData(queryModel);
    }
```
