### ISSUE TITLE
How to ignore time for built-in Date filter?

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3676]
For something like a `DateCreated` or `DateUpdated` field we often show just the date component in a `Table`. The built-in filter always wants a time selected as well. What we really want is just anything on a particular day.

**Comment by ElderJames** [comment]
After https://github.com/ant-design-blazor/ant-design-blazor/pull/3897 was merged, we can use `InputAttributes` to change the default properties of built-in filters.

```cs
    DateTimeFieldFilterType dateTimeFieldFilterType = new() { InputAttributes = new() { ["ShowTime"] = (OneOf.OneOf<bool, string>)false } };
```

```razor
<PropertyColumn Property="c=>c.BirthDate"
                Format="yyyy/MM/dd"
                FieldFilterType="dateTimeFieldFilterType"
                Filterable />
```
