### ISSUE TITLE
Column<DateTime> built-in filter: how to type year 0001 or 9999?

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3677]
Until the `Column<DateTime?>` filter is fixed, I am trying to use either `DateTime.MinValue` or `DateTime.MaxValue` instead of `null` with `Column<DateTime>`. The filter will not accept a year of 0001 or 9999.

**Comment by michaelcsikos** [comment]
Oh, you must also type the hours, minutes and seconds. That's really annoying.

**Comment by ElderJames** [comment]
Hello @michaelcsikos , how did you use DateTime.MinValue and DateTime.MaxValue?

**Comment by michaelcsikos** [comment]
Instead of using `DateTime?` for the property in my model, I converted any `null` value to `DateTime.MaxValue`. I was only doing this because the `Column<DateTime?>` filter crashes. When it's fixed, I'll use `DateTime?` again. But what I found is you can't just enter a date into the filter; you must enter the time in hours, minutes and seconds. It would be extremely rare for a user to want to filter by a specific second in time. Usually, you can want to set a date range.

**Comment by ElderJames** [comment]
Thank you for explanation, I think we need to add the ability to set more properties to the built-in filter component.
