### ISSUE TITLE
Regex pattern form validation bug by asterisk

### ISSUE THREAD

**Issue by rammsteini** [ant-design-blazor/ant-design-blazor#3679]
A leading asterisk or two or more asterisks in a row as the valdiated string breaks the reg ex validation.

The following  razor page has a form with a password field which is validated by the regex pattern ```^.{6,}$```  

The passwords \*11111111 or 11111111\*\* are not working correctly

![8nkLkwj2iD](https://github.com/ant-design-blazor/ant-design-blazor/assets/4928907/a1be7d4a-ae6b-4ca8-a993-41d0dc1842a4)
![E13Q5T6HM5](https://github.com/ant-design-blazor/ant-design-blazor/assets/4928907/d1192cca-b63a-44dc-9494-4111ac6f7449)
![F7LfmdTh80](https://github.com/ant-design-blazor/ant-design-blazor/assets/4928907/5a7b2f54-197b-4bfa-a133-dbf1c58d9b5e)

```
@page "/test"

<Form LabelColSpan="3"
      WrapperColSpan="6"
      Model="@passwordModel"
      ValidateOnChange="true"
      ValidateMode="@FormValidateMode.Rules">

    <FormItem Label="Password" Rules=@(PasswordRules)>
        <InputPassword @bind-Value="@context.Password" />
    </FormItem>

    <FormItem WrapperColOffset="3" WrapperColSpan="6">
        <Button Type="@ButtonType.Primary" HtmlType="submit">
            Save
        </Button>
    </FormItem>

</Form>

@code
{
    PasswordModel passwordModel = new();

    public FormValidationRule[] PasswordRules
    {
        get
        {
            return new FormValidationRule[]
            {
                    new FormValidationRule
                    {
                        Type = FormFieldType.Regexp,
                        Pattern = @"^.{6,}$",
                        Message = "Passwords must be at least 6 characters long"
                    }
            };
        }
    }

    public class PasswordModel
    {
        public string Password { get; set; }
    }
}
```

**Comment by ElderJames** [comment]
This is because the Type of FormValidationRule would validate the type format of the input value. And if it's `Regexp`, the form would validate if it is a valid regexp patern. So you need to assign String instead, then it works well.

```
 new FormValidationRule
 {
     Type = FormFieldType.String,
     Pattern = @"^.{6,}$",
     Message = "Passwords must be at least 6 characters long"
 }
```
