### ISSUE TITLE
Funny value is displayed for title in Select component

### ISSUE THREAD

**Issue by y-somada** [ant-design-blazor/ant-design-blazor#3681]
### Describe the bug

Funny value for title in Select component.
This also occurs on the sample page.

https://antblazor.com/en-US/components/select#components-select-demo-simple-select

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/94443896/b3ba369a-261c-44ef-be1e-64afdd7d95e2)

https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/select/internal/SelectContent.razor#L67-L72
Is it because the getLabel return is a RenderFragment?

**Comment by ElderJames** [comment]
Thanks for contacting us @y-somada , this issue have been fixed via #3695 . Please wait for next release.
