### ISSUE TITLE
Table keeps loading when DataSource is empty

### ISSUE THREAD

**Issue by lmd-be** [ant-design-blazor/ant-design-blazor#3682]
### Describe the bug

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/142570317/c0c5e569-9f6f-4bdd-867d-7e5318821bcb)

I'm using the Table component to display data from my API. 
I've never had any issues as the API would always return data, but now I'm experiencing a problem when the collection is empty. 
The table will continue to spin forever and it completely ignore the value provided in the Loading parameter. 

### Steps to reproduce (please include code)

1. I'm using the following table: 

```
<Table     
           RemoteDataSource
           RowKey="@(@event => @event.Id)"
           Total="Total"
           @ref="this.table"
           Class="small-table-row-padding"
           DataSource="@Events"
           ScrollX="2000"
           Loading="@this.isTableLoading"
           OnChange="@(EventCallback.Factory.Create<QueryModel<EventOverviewDto>>(this, async queryModel => await OnTableChangeAsync(queryModel)))"
         Responsive>
...
</Table> 
```

2. I'm calling `this.table?.ReloadData()` which triggers `OnTableChangeAsync()` which then calls `LoadDataAsync()` 

```
        private async Task LoadDataAsync()
        {
            this.isTableLoading = true;

            EventRequestDto eventRequest =
                new()
                {
                    EventFilters = SelectedFilters,
                    SearchQuery = SearchQuery,
                    Sorting =
                        OrderBy == null
                            ? default
                            : new SortingCriteria(OrderBy, OrderDescending.GetValueOrDefault()),
                    Paging = new PageParameters(PageNo, PageSize)
                };

            string json = JsonConvert.SerializeObject(eventRequest);

            RestResponse<PagedResult<TEvent>> eventResponse = await RestClient!.GetAsync<
                PagedResult<TEvent>
            >(
                $"{this.urlPrefix}/{GetEventsEndpoint}",
                null,
                new Dictionary<string, string>() { { "eventRequestJson", json } }
            );

            if (!eventResponse.IsSuccessful || eventResponse.Data == null)
            {
                await NotificationService!.Error(
                    new()
                    {
                        Message = "Could not retreive events",
                        Description = eventResponse.ErrorMessage
                    }
                );
                return;
            }

            Events = eventResponse.Data?.Results?.ToList() ?? new() {  };
            Total = eventResponse.Data?.RowCount ?? 0;

            StateHasChanged();

            this.isTableLoading = false;
        }
```

I want you to look at this last part: 

```
            Events = eventResponse.Data?.Results?.ToList() ?? new() {  };
            Total = eventResponse.Data?.RowCount ?? 0;

            StateHasChanged();

            this.isTableLoading = false;
```

When the data result is not empty. The table will load without issue. But when its empty, it will just go on forever. 
Once the table has received some data that is not empty, then it is suddenly capably of displaying empty data, which I find pretty weird. 

### Exceptions (if any)

No exceptions whatsover, and result code is 200 as well 

### Further technical details
- AntDesign Nuget Package version: 0.17.3.1
- Include the output of `dotnet --info`
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.30fce108

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.30fce108
 [maui-windows]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    34.0.43/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net6]
   Installation Source: VS 17.8.34525.116
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.1\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio 2022 Professional

**Comment by lmd-be** [comment]
Right now the only workaround is this: 

```
window.antBlazorHelpers = {
    HideSpinners: function (elementId) {
        // Find the parent element
        var parentElement = document.getElementById(elementId);

        if (parentElement) {
            // Find child elements with class "ant-spin ant-spin-spinning"
            var spinners = parentElement.querySelectorAll('.ant-spin.ant-spin-spinning');
            spinners.forEach(function (spinner) {
                // Hide the spinner element
                spinner.style.display = 'none';
            });

            // Find child elements with class "ant-spin-blur"
            var blurElements = parentElement.querySelectorAll('.ant-spin-blur');
            blurElements.forEach(function (blurElement) {
                // Remove the "ant-spin-blur" class
                blurElement.classList.remove('ant-spin-blur');
            });
        }
    }
};
```

Which I then use like this, whenever the datasource is empty. 

```
        private async Task HideSpinnerAsync()
        {
            // Invokes a JS function that will hide the HTML elements related to the spinner
            await JSRuntime!.InvokeVoidAsync("antBlazorHelpers.HideSpinners", "event-table-wrapper");
        }
```

Maybe its also worth mentioning that I'm using a type parameter on my datasource (List<TEvent>), so the type is not directly specific, but I guess it would be nice if this was supported as well.

**Comment by ElderJames** [comment]
Thanks for contacting us @lmd-be , is this issue caused only when the DataSource is abstract class type?

**Comment by lmd-be** [comment]
@ElderJames  Yes or actually its just a typeparam provided
