### ISSUE TITLE
【Bug】Using the watermark component will cause the breadcrumb component style to display incorrectly

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design-blazor/ant-design-blazor#3685]
Error
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/907161ef-2bc3-43f5-9140-19146efb4373)
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/431a4d0b-2ec4-4617-97a0-1621a5f4c928)
Correct
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/30250585/f5f6a1c0-3e5b-41d0-82f2-e0a6ea16cad2)

**Comment by ElderJames** [comment]
Where is your breadcrumb?

**Comment by HuaFangYun** [comment]
Breadcrumb is on the content page
`<PageContainer>
    <Breadcrumb>
        <Breadcrumb>
            <BreadcrumbItem>设备管理</BreadcrumbItem>
        </Breadcrumb>
    </Breadcrumb>
</PageContainer>`

**Comment by ElderJames** [comment]
Related with prolayout
