### ISSUE TITLE
Visual bug of  Radio Component in RadioGroup

### ISSUE THREAD

**Issue by AlexeyKrasuk** [ant-design-blazor/ant-design-blazor#3692]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/5476099/4a11d443-10b1-477c-9bb1-dec9274ad37e)

If you click another radio component value, the previous value still remains selected.

This bug is reproducible on demo components page
https://antblazor.com/en-US/components/radio

**Comment by ElderJames** [comment]
Thanks for contacting us @AlexeyKrasuk ,we will fix it later.

**Comment by thirking** [comment]
I find that there is no problem clicking on the text, but there will be an error when clicking on the circle.

**Comment by rabberbock** [comment]
@ElderJames Do you have an idea when there will be a new version released with this fix? Is there a nightly build we can use in the interim?

Thanks either way!

**Comment by ElderJames** [comment]
@rabberbock The nightly build ci was broken, I will fix it later. The new version will be released after the recent PRs wss merged.
