### ISSUE TITLE
【BUG】ReuseTabsPage Pin =true call MainLayout=>OnInitialized more than once

### ISSUE THREAD

**Issue by dashiell-zhang** [ant-design-blazor/ant-design-blazor#3699]
```
@page "/"
@attribute [ReuseTabsPage(Title = "最新公告", Pin =true, Closable = false)]

<Layout Style="padding-top:30px;">
    <Content Class="site-layout-background">

    </Content>
</Layout>
```
https://github.com/ant-design-blazor/ant-design-blazor/assets/36178221/cd894c09-6cab-46fd-a79d-59e704e7ece1

当采用 Pin =true 的配置时会造成视频中多次重定向 login 页面的情况，在多次重定向之后虽然最后可以正常呈现 login 页面，但是过程中的多次调用应该不正确的，经过调试发现是因为多次执行了 **MainLayout** 中 **OnInitialized** 函数。

When the Pin =true configuration is used, the login page will be redirected multiple times in the video. Although the login page can be rendered normally after multiple redirects, the multiple calls in the process should be incorrect. After debugging, it was found It's because the **OnInitialized** function in **MainLayout** has been executed multiple times.

```
@page "/"
@attribute [ReuseTabsPage(Title = "最新公告", PinUrl = "/", Closable = false)]

<Layout Style="padding-top:30px;">
    <Content Class="site-layout-background">

    </Content>
</Layout>
```

使用 PinUrl = "/" 的方式，则不会触发上面的 bug
Using PinUrl = "/" will not trigger the above bug

https://github.com/ant-design-blazor/ant-design-blazor/assets/36178221/328506b1-dea6-4eb6-affc-37db7849af1d

**Comment by ElderJames** [comment]
Please provide a reproduce demo.

**Comment by dashiell-zhang** [comment]
在截至目前 2024-08-08 的最新版 0.20.0 中这个 Bug 似乎不存在了，无法重现了，算是已解决吧

In the latest version 0.20.0 as of 2024-08-08, this bug seems to no longer exist and cannot be reproduced, so it is considered to have been resolved.
