### ISSUE TITLE
Form input name for static forms

### ISSUE THREAD

**Issue by GoldSucc** [ant-design-blazor/ant-design-blazor#3709]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
I'm trying to create form with validation in static Blazor page using Ant Form. After addition of Form Name it almost works out of the box except it doesn't. The missing part is the name attribute of resulting <input> html element, preventing correct model binding. I'm using SupplyParameterFromForm attribute to bind form model to property. I found a solution:         `<Input AdditionalAttributes="@W.NameOf("Input.Email")" @bind-Value="Input.Email"/>`. W is WebHelper I created and this NameOf function basically creates a Dictionary
```
    public static Dictionary<string, object> NameOf(string name)
    {
        return new Dictionary<string, object> { { "name", name } };
    }
```
    and it works because now Blazor can properly bind model and then Ant form validation etc. works as expected

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
Would be good to have Name attribute for ant Input component or may be use Name cascading element of formItem to populate "name" of html input, this syntax would be much cleaner than dictionary creation.

**Comment by ElderJames** [comment]
@GoldSucc Please check the latest version 0.18.1.

**Comment by GoldSucc** [comment]
@ElderJames Hello! I checked, it works but when using FormItem localised Display name attribute is not used. Would be good to have label created automatically if displayattribute name is set. Not sure if it is possible in static content

**Comment by ElderJames** [comment]
@GoldSucc You are right, the DisplayAttribute generating still not support in static SSR.
