### ISSUE TITLE
Table Filter function: Select entry

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#3719]
Dear Ant team,

We have found that it is not possible to select the filter entry in an ant table with a double-click (e.g. to replace the entry with a new value using "Past", which is faster). 

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/45635963/f8c23044-f26f-4eaa-8b0f-630287894dbf)

Instead, you have to use the reset function to delete the existing entry first.

Is this behaviour in Ant intentional or is it a bug in Ant (perhaps also in the WebView2 component from Microsoft)?

Regards
pc

**Comment by ElderJames** [comment]
Hello @true-perfect-code , did you mean select the text of the input box?

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/7550366/a800123a-2d23-47d6-9148-f0195f7c29ad)

**Comment by ElderJames** [comment]
Hello @true-perfect-code ， do you still meet this issue?

**Comment by true-perfect-code** [comment]
@ElderJames : This has already been fixed. Sorry for not closing the request.
