### ISSUE TITLE
the datasource of table

### ISSUE THREAD

**Issue by Jason190** [ant-design-blazor/ant-design-blazor#3720]
I have updated the dataSource of Table. But the table still empty. Is there anything I don't know to updated the dataSource?

Follow the example, I think the data binding + update the binding value should be work. But it is not. Is there anyone who can help, please!

**Comment by ElderJames** [comment]
Thanks for contacting us @Jason190 , could you please post your code here to reproduce?

**Comment by Jason190** [comment]
Hi, @ElderJames . Thx for your reply.
```
<Table TItem="TableData" DataSource="@ServiceTableData.Datas" Size=@TableSize.Small ScrollY="412px" EnableVirtualization HidePagination>

    <GenerateColumns Range="1.." Definitions=definitions />

    <ActionColumn Title="Action">
        <Space Size=@("middle")>
            <SpaceItem>
                <a>Invite @context.ID</a>
            </SpaceItem>
        </Space>
    </ActionColumn>
</Table>
```
As you see. I bind the DataSource to Datas which belong to ServiceTableData. 
```
public class ServiceTableData : IServiceTableData
{
    public TableData[]? Datas { get; set; } 


    public event Action<TableData[]> OnChange;

    public void Update(TableData[] datas)
    {
        Datas = datas;
        OnChange?.Invoke(datas);
    }
}
```
This is ServiceTableData class above. 
```
foreach (double[] item in objArray)
{
    TableData oneline = new TableData()
    {
        Key = keyNum++.ToString(),
        ID = item[0].ToString(),
        ObjectID = item[1].ToString(),
        Area_size = item[2]
    };
    datas = datas.Concat(new TableData[] {oneline}).ToArray();
}

ServiceTableData.Update(datas);
```
This is in another class which is actual assignment to DataSource. Perhaps I'm missing some conceptual details, please let me know.
Thanks a lot.

**Comment by GoldSucc** [comment]
@Jason190 Are you using Interactive rendering? By the way, you can generate columns with for loop and PropertyColumn, for example,  I used it for my dynamic schedule table:
`  @for (int i = 0; i < _weeks; i++)
        {
            var weekIndex = i + _startWeek;
            var title = $"Week {weekIndex}";
            var weekDays = i == 0 ? _firstWeekDays : i == _weeks - 1 ? _lastWeekDays : 7;
            var width = weekDays * 15;
            var index = i;
            <PropertyColumn Width="@width.ToString()" Class="schedule-column" Property="e => e.weekDataList" Title="@title">

                @{
                    if (context.weekDataList.Length != _weeks)
                    {
                        index = -1;
                    }

                    var week = index >= 0 ? context.weekDataList[index] : new WeekData();
                    var segments = week.segments;
                }
                <ScheduleFragment Segments="@segments"/>
            </PropertyColumn>
        }`
        comparing length is actually required because it  re renders with previous context and new data (it updates data, rerenders and only then updates column definitions then rerenders again and so we need to not access data before new column definition re-render) and causes index out of bounds.

**Comment by Jason190** [comment]
Getting the instance of the table via the ref method, I find that the datasource is empty in the instance. But I have just assigned the value. Why is this?

**Comment by GoldSucc** [comment]
@Jason190 Can you share your code? It may depend on lifecycle usage. Which render mode are you using?

**Comment by GoldSucc** [comment]
@Jason190 also most of the times you don't have to use ref to assign, you can bind value by using <Table DataSource="_myList"
have you checked that value you are assigning is not null?

**Comment by Jason190** [comment]
@GoldSucc I'm completely dizzy already. Could you write an example of this part for me?

**Comment by GoldSucc** [comment]
@Jason190 can create complete example for you after work day. busy for now. also you can send me your code and may be I will be able to help you fixing

**Comment by Jason190** [comment]
@GoldSucc Would you tell me your email address?

**Comment by GoldSucc** [comment]
@Jason190 olebugro@gmail.com, goldsucc@gmail.com

**Comment by ElderJames** [comment]
Hello @Jason190 @GoldSucc , have you solved the issue?
