### ISSUE TITLE
Message 全局提示 无法自动关闭，项目中有些可以关闭，有些不可以

### ISSUE THREAD

**Issue by wangfei9999** [ant-design-blazor/ant-design-blazor#3724]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/73685882/59229617-3aed-4031-b8ce-7000db8f1f30)
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/73685882/c0dd366f-31da-4660-9f91-6dbffcc667b2)

**Comment by wangfei9999** [comment]
我发现，只有我将“  var loginResult = await AccountService.LoginAsync(_model);” 移除后，可以自动关闭提示，请问这个是什么原因造成的呢？

**Comment by ElderJames** [comment]
Thanksk for contacting us @wangfei9999 , please don't use await while you don't want to wait the message

**Comment by wangfei9999** [comment]
您好，没有理解您的回复，请问我该如何正常的将Message关闭呢？上述代码问题在于哪里，方便帮我指出吗？谢谢！

**Comment by wangfei9999** [comment]
您好，问题我已经找到了，感谢
