### ISSUE TITLE
exception rendering component: Cannot read properties of undefined (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by wangfei9999** [ant-design-blazor/ant-design-blazor#3725]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/73685882/cf728eab-5a63-4053-8793-1f1160a9fa24)
使用框架版本：
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/73685882/b86cac02-e304-4932-bb68-e4fd1a30aa1c)

**Comment by ElderJames** [comment]
@wangfei9999 Please update to 0.18.1
