### ISSUE TITLE
eventHelper.ts There is a circular referencing problem with JSON serialization

### ISSUE THREAD

**Issue by jxcproject** [ant-design-blazor/ant-design-blazor#3737]
When I use LogicFlow (https://site.logic-flow.cn/docs/#/), the browser reports after dragging the LogicFlow element with the mouse

eventHelper.ts:21 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'MouseEvent'
    --- property 'nativeEvent' closes the circle
    at JSON.stringify (<anonymous>)
    at HTMLDocument.o [as e_mouseup-2] 
	
The exception code is
 `
const json = JSON.stringify(obj, (k, v) => {
        if (v instanceof Node) return 'Node';
        if (v instanceof Window) return 'Window';
        return v;
      }, ' ');
`

 
### Further technical details
- AntDesign 0.18.0

**Comment by ElderJames** [comment]
Thanks for contacting us @jxcproject , how did you use AntBlazor wtih the LogicFlow?

**Comment by jxcproject** [comment]
@ElderJames 
I use LogicFlow for logical orchestration and AntBlazor for the property configuration of LogicFlow elements.
Blazor is only used as a div container, rendering and interaction are native JS code, and data is synchronized by calling [JSInvokable] code. The interface looks like the following, but dragging the element will report an exception above.

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/8786702/f6554ea8-1575-48b4-a416-05be58de0faa)

**Comment by ElderJames** [comment]
Are you using eventHelper?

**Comment by jxcproject** [comment]
`
const cache = new Set();
const json = JSON.stringify(obj, (k, v) => { 
	if (typeof v === 'object' && v !== null) {
      if (cache.has(v)) {
        return; // 移除循环引用
      }
      cache.add(v);
    }
	if (v instanceof Node) return 'Node'; 
	if (v instanceof Window) return 'Window'; 
	return v; 
}, ' ');
`
Does changing the exception code like this fix the problem?

**Comment by ElderJames** [comment]
Yes, please send a PR for that.

**Comment by jxcproject** [comment]
> Yes, please send a PR for that.

I'll submit it in the evening
