### ISSUE TITLE
BUG: input of Search

### ISSUE THREAD

**Issue by MiniTor** [ant-design-blazor/ant-design-blazor#374]
![image](https://user-images.githubusercontent.com/24976720/87648330-4ffedc80-c782-11ea-8811-a75859b1a5b2.png)
OnSearch回调函数有问题：每次点击光标没有移除，导致不能执行函数，需要点击两次才有反应

**Comment by ElderJames** [comment]
Thanks for contacting us @MiniTor .
We will deal with it as soon as possible.
