### ISSUE TITLE
Button with Icon component is larger than Button with Icon property

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#3742]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/21806535/9646e759-4c42-43d9-8ac8-b19250bf7e81)

```razor
<Button Icon = "@IconType.Outline.Home" />

<Button>
    <Icon Component = "..." />
</Button>
```

How do I make them always the same size?

**Comment by ElderJames** [comment]
Hi @michaelcsikos , you can add a class `ant-btn-icon-only` for workaround.
```
       <Button Class="ant-btn-icon-only" >
           <Icon Type="@IconType.Outline.Search" />
       </Button>
```

**Comment by ElderJames** [comment]
Use the `NoSpanWrap` also work.
```
 <Button NoSpanWrap >
     <Icon Type="@IconType.Outline.Search" />
 </Button>
```

**Comment by michaelcsikos** [comment]
Hi @ElderJames 

The `ant-btn-icon-only` fixes the size but it is affecting the vertical alignment:
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/21806535/1f102bb3-5806-4d3c-a4c0-f3497d10c841)

The `NoSpanWrap` doesn't seem to work at all:
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/21806535/a809faee-f36c-4fb5-91cd-81d4187f8f5d)

These buttons are in the `PageHeaderExtra` and wrapped in a `Tooltip` as well.

**Comment by michaelcsikos** [comment]
Thank you, that works.
