### ISSUE TITLE
[Parameter] public EventCallback<int> OnChange { get; set; }

### ISSUE THREAD

**Issue by icetech233** [ant-design-blazor/ant-design-blazor#3748]
OnChange 怎么绑定 C#的代码， Onclick可以的

**Comment by ElderJames** [comment]
Thanks for contacting us @icetech233 , which component are you using?

**Comment by icetech233** [comment]
> Thanks for contacting us @icetech233 , which component are you using?

RadioGroup 的  OnChange事件怎么写，一直报错


普通button的onclick事件是可以的， 我看定义是差不多的

**Comment by ElderJames** [comment]
需要指定泛型类型 TValue="int"

**Comment by icetech233** [comment]
> 需要指定泛型类型 TValue="int"

还真的有个这个 TValue

**Comment by icetech233** [comment]
https://antblazor.com/zh-CN/components/radio

我觉得还是文档改一下， 都没有看到这个东西

**Comment by icetech233** [comment]
示例代码也没有提到这个  TValue
