### ISSUE TITLE
Demo page is out of response

### ISSUE THREAD

**Issue by mutouzdl** [ant-design-blazor/ant-design-blazor#375]
部分demo无法打开，如drawer、pageheader，我不确定是不是我浏览器问题？
我试了New Edge和Chrome，都是一样的情况。

---------------------------------------------------

Some demos can't be opened, such as drawer, pageheader
I'm not sure if it's my browser problem?
I tried New Edge and Chrome, and it's the same.

---------------------------------------------------

![image](https://user-images.githubusercontent.com/3509249/87668808-623b4380-c79f-11ea-9ead-aa102b7f5a04.png)

**Comment by Ratomir** [comment]
The same thing with the Card page.

**Comment by ElderJames** [comment]
This could be due to a problem with the avatar component #367
