### ISSUE TITLE
0.16.2正常，升级最新的会无法打包编译，wasm会报错, 定位到obj bin缓存

### ISSUE THREAD

**Issue by icetech233** [ant-design-blazor/ant-design-blazor#3753]
代码完全一样，就是nuget 升级了一下版本号，

blazor.webassembly.js:1  Error: AggregateException_ctor_DefaultMessage (Method not found: void Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<!0>(Microsoft.Extensions.DependencyInjection.IServiceCollection))
    at Jn (dotnet.runtime.8.0.0.14kkjimq5k.js:3:31614)
    at Ul (dotnet.runtime.8.0.0.14kkjimq5k.js:3:181904)
    at 00a6fa7e:0x18852
    at 00a6fa7e:0x14d44
    at 00a6fa7e:0x816a
    at 00a6fa7e:0x17571
    at 00a6fa7e:0x17d62
    at 00a6fa7e:0x1de1a5
    at 00a6fa7e:0x3f31b
    at e.<computed> (dotnet.runtime.8.0.0.14kkjimq5k.js:3:214976)

**Comment by icetech233** [comment]
主要是dotnet模板里面的 是 0.16.2

**Comment by ElderJames** [comment]
Thanks for contacting us @icetech233 , please update your dotnet template

```
dotnet new update 
```

**Comment by icetech233** [comment]
> Thanks for contacting us @icetech233 , please update your dotnet template
> 
> ```
> dotnet new update 
> ```

dotnet publish  debug  is ok， but  publish  release  is  error

**Comment by icetech233** [comment]
i do not kown how to debug wasm

**Comment by icetech233** [comment]
你们的新模板 也是不行， 我不知道 
0.16.2到0.17.3改动了啥， 导致release 会报错
blazor.webassembly.js:1 Error: AggregateException_ctor_DefaultMessage (Method not found: void Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<!0>(Microsoft.Extensions.DependencyInjection.IServiceCollection))
    at Jn (dotnet.runtime.8.0.0…kkjimq5k.js:3:31614)
    at Ul (dotnet.runtime.8.0.0…kjimq5k.js:3:181904)
    at dotnet.native.wasm:0x18852
    at dotnet.native.wasm:0x14d44
    at dotnet.native.wasm:0x816a
    at dotnet.native.wasm:0x17571
    at dotnet.native.wasm:0x17d62
    at dotnet.native.wasm:0x1de1a5
    at dotnet.native.wasm:0x3f31b
    at e.<computed> (dotnet.runtime.8.0.0…kjimq5k.js:3:214976)
﻿

**Comment by ElderJames** [comment]
Our site is also release as WebAssembly and works fine.

**Comment by icetech233** [comment]
> Our site is also release as WebAssembly and works fine.

[0.16.2 was fine，，，but  0.17.3  error

**Comment by icetech233** [comment]
del  obj 文件可以了， 是不是 obj 和bin 有缓存啊
