### ISSUE TITLE
Modal removeChild log

### ISSUE THREAD

**Issue by GoldSucc** [ant-design-blazor/ant-design-blazor#3760]
In logs navigating out when using modal sometimes produces:
`Microsoft.JSInterop.JSException: Argument 1 ('child') to Node.removeChild must be an instance of Node
removeChild@[native code]
@http://localhost:5082/_content/AntDesign/js/ant-design-blazor.js:1:51887
@http://localhost:5082/_framework/blazor.web.js:1:3244
Promise@[native code]
beginInvokeJSFromDotNet@http://localhost:5082/_framework/blazor.web.js:1:3212
@http://localhost:5082/_framework/blazor.web.js:1:62919
_invokeClientMethod@http://localhost:5082/_framework/blazor.web.js:1:63726
_processIncomingData@http://localhost:5082/_framework/blazor.web.js:1:60408
@http://localhost:5082/_framework/blazor.web.js:1:82184
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)
`
it looks like js code tries to remove modal even if it is not present in dom. good news is that it does not produce any exceptions and don't hang an app but still it is undocumented behaviour. because it happens when navigating away, it probably happens in dispose method of modal. may be js code state does not reflect modal removed from Dom by c# code idk. I haven't checked source code but may be before doing js dispose logic better to send Visible state to js code to update state (not sure if it actually makes sense, depends on how modal is implemented)

**Comment by zxyao145** [comment]
@ElderJames I'm very sorry that I don't have time to fix this issue recently.

I think the best solution is to use `Element.remove()` instead of this line of code, please evaluate it

https://github.com/ant-design-blazor/ant-design-blazor/blob/11605334cba4b73837e1e905261948b2bc37163d/components/core/JsInterop/modules/dom/manipulationHelper.ts#L35
