### ISSUE TITLE
Make CheckboxGroup more generic

### ISSUE THREAD

**Issue by Phoenixkaze** [ant-design-blazor/ant-design-blazor#3764]
CheckboxGroup is currently not generic.

We even have Label and Value on CheckboxOption then why confine the type of Value to string?

Say I have a enum marked as Flags. I would like to use a CheckboxGroup to let the user combine different enum variants. I can't get the enum values directly through the Value property. Of course I know there are always workarounds.

**Comment by ElderJames** [comment]
Thanks for contacting us @Phoenixkaze , we have created a PR for this feature.

**Comment by ElderJames** [comment]
Hello @Phoenixkaze , the feature would release in 0.19.0.
