### ISSUE TITLE
The TreeSelect control will automatically collapse when a child node is clicked and cannot be selected

### ISSUE THREAD

**Issue by codeox-he** [ant-design-blazor/ant-design-blazor#3767]
The TreeSelect control will automatically collapse when a child node is clicked and cannot be selected.
The official example also has the same problem:
https://antblazor.com/zh-CN/components/treeselect
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/57785609/2bf51088-0e42-486e-a822-958a7263135e)
Moreover, the same phenomenon occurs when Grid controls display tree data.

**Comment by ElderJames** [comment]
Thanks for contacting us @codeox-he ,we will fix this later. And please create another issue for the table.
