### ISSUE TITLE
Upload - ShowUploadList wrong and missing documentation

### ISSUE THREAD

**Issue by OrihuelaConde** [ant-design-blazor/ant-design-blazor#3775]
The documentation of the Upload component on ShowUploadList is wrong since it quote examples from React. There is no an actual example on how to use "removeIcon" and "downloadIcon" individually (by file) or the other features.

https://antblazor.com/en-US/components/upload#API

**Comment by ElderJames** [comment]
Thanks for contacting us @OrihuelaConde , and yes we only implement the `ShowUploadList` but haven't implement other flag to handle the icons.
