### ISSUE TITLE
Can it be used in webview2?

### ISSUE THREAD

**Issue by MoDao1990217** [ant-design-blazor/ant-design-blazor#3782]
I recently need to develop a function of the desktop system, want to use winfroms loading webview2 to achieve, please support? How to configure this.

**Comment by ElderJames** [comment]
Thanks for contacting us @MoDao1990217 , we support blazor hybird. 

Please follow the official guide for Blazor Hybird. Note that you need to register the AntDesign services to ServiceCollection.

```
using Microsoft.AspNetCore.Components.WebView.WindowsForms;
using Microsoft.Extensions.DependencyInjection;

namespace WinFormsBlazor;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var services = new ServiceCollection();
        services.AddWindowsFormsBlazorWebView();
        services.AddAntDesign();  <-- register AntDesign services
        blazorWebView1.HostPage = "wwwroot\\index.html";
        blazorWebView1.Services = services.BuildServiceProvider();
        blazorWebView1.RootComponents.Add<Counter>("#app");

    }
}
```

**Comment by MoDao1990217** [comment]
> Thanks for contacting us @MoDao1990217 , we support blazor hybird https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-8.0.
> 
> Please follow the official guide for Blazor Hybird. Note that you need to register the AntDesign services to ServiceCollection.
> 
> ```
> using Microsoft.AspNetCore.Components.WebView.WindowsForms;
> using Microsoft.Extensions.DependencyInjection;
> 
> namespace WinFormsBlazor;
> 
> public partial class Form1 : Form
> {
>     public Form1()
>     {
>         InitializeComponent();
> 
>         var services = new ServiceCollection();
>         services.AddWindowsFormsBlazorWebView();
>         services.AddAntDesign();  <-- register AntDesign services
>         blazorWebView1.HostPage = "wwwroot\\index.html";
>         blazorWebView1.Services = services.BuildServiceProvider();
>         blazorWebView1.RootComponents.Add<Counter>("#app");
> 
>     }
> }
> ```

Thank you very much for your help, I will try one
