### ISSUE TITLE
Seems a bug in Dictionary Support in Form

### ISSUE THREAD

**Issue by tiansfather** [ant-design-blazor/ant-design-blazor#3784]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/16606743/57aba690-da13-498a-aebc-66dee9ef6051)

and if my dictionary has no data, it will throw an error of  'key not present in the dictionary', what about making a default value instead of an error ?

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/16606743/f7ce5562-bca0-44d0-a067-418a164eda2a)

**Comment by ElderJames** [comment]
Thanks for contacting us @tiansfather , how did you use the Form component? Please post your reprpoduce code here.

**Comment by tiansfather** [comment]
`
<Form Model="model">
    <FormItem Name="id">
        <Input Value="1" />
    </FormItem>
</Form>


@code {
    private Dictionary<string, object> model = new Dictionary<string, object>() { ["id"] = 1 };
}
`

and you will get an error like "id is not a member of type dictionary".
it should be  **if (typeof(IDictionary).IsAssignableFrom(type))**   not **if (type.IsAssignableFrom(typeof(IDictionary)))**  
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/16606743/72e5f87f-5e1c-4a07-a4de-96367b101d56)

**Comment by ElderJames** [comment]
Thank you, would you please send a PR to fix this?

**Comment by tiansfather** [comment]
I will try it later
and another question, validation can not work when use dictionary as form model 
for example 
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/16606743/3749e132-608a-4690-be26-6b8dca56a94f)

**Comment by ElderJames** [comment]
> I will try it later and another question, validation can not work when use dictionary as form model for example ![image](https://private-user-images.githubusercontent.com/16606743/320694624-3749e132-608a-4690-be26-6b8dca56a94f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjkxNzMsIm5iZiI6MTcxMjYyODg3MywicGF0aCI6Ii8xNjYwNjc0My8zMjA2OTQ2MjQtMzc0OWUxMzItNjA4YS00NjkwLWJlMjYtNmI4ZGNhNTZhOTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAyMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MjJkZWFkMjUxMWRiMGU3ZjVhZDgyODAzYzkxMjY2YTQwMzk1N2NjOTBkNjgzNGZjMDRmMTMwYjQyMTY0YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwvqy_N_ixBYxzsAfh9ycYWsjkl17d8Av-c3_p35wks)

That should be work unless there are some bugs.
