### ISSUE TITLE
Issue of InputNumber component

### ISSUE THREAD

**Issue by liangjinnian** [ant-design-blazor/ant-design-blazor#3789]
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/166481170/703bdcd3-a3fb-4177-b6c4-a552acf377ad)

If the initial value of MyValue is 0, then enter -0 in the InputNumber component and submit the form. The displayed value on the page is 0.
If the initial value of MyValue is 1, then enter -0 in the InputNumber component and submit the form. The result displayed on the page is -0. What if you want to input -0 and get 0 regardless of the initial value of MyValue?

**Comment by ElderJames** [comment]
Thanks for contacting us @liangjinnian, this is because -0 and 0 in both double and float is two value. So you can handle the format by your self.

```
@(MyValue==0.0d?0.0d:MyValue );
```

**Comment by liangjinnian** [comment]
Hello @ElderJames , I don't quite understand. I used it this way in the project, but it didn't achieve the desired effect
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/166481170/2552d071-9acb-49d8-ab10-3ebda80dd52f)

**Comment by ElderJames** [comment]
What is your  desired effect?
