### ISSUE TITLE
Please suspend support for.NET versions below 7.0

### ISSUE THREAD

**Issue by Seanxwy** [ant-design-blazor/ant-design-blazor#3805]
It is recommended to drop support for versions below 7.0. Reduce compatibility code and potential risks. Optimize and improve performance accordingly

**Comment by manuelelucchi** [comment]
While .NET 7 support drops in a few weeks, .NET 6 is LTS and has support until november

**Comment by ElderJames** [comment]
We will continue to support . NET Core 3.1 to. NET 8 and later in version 1.0.  And v2.0 will probably only be supported starting with NET8.
