### ISSUE TITLE
The treeselect component AllowClear is invalid

### ISSUE THREAD

**Issue by 499105097** [ant-design-blazor/ant-design-blazor#3807]
`<TreeSelect TItem="Data"
            Style="width:100%;"
            DataSource="treeData"
            @bind-Value="@value"
            Placeholder="Please select"
            AllowClear
            Multiple
            TreeDefaultExpandAll
            ChildrenExpression="node=>node.DataItem.Children"
            TitleExpression="node=>node.DataItem.Title"
            KeyExpression="node=>node.DataItem.Key"
            IsLeafExpression="node=>node.DataItem.Children==null">
</TreeSelect>`   
This demo has **AllowClear** invalid

**Comment by 499105097** [comment]
`@bind-Value="@value"`    **value** The selected value cannot be obtained

**Comment by ElderJames** [comment]
cc @pankey888

**Comment by pankey888** [comment]
> `@bind-Value="@value"` **value** The selected value cannot be obtained

If you want to bind value rather than values, you should set "Multiple=false". 
There is another issue related to bind-Value, I will fix it right now.
