### ISSUE TITLE
As long as in the asynchronous code, _table. ReloadData(); Why doesn't it take effect?

### ISSUE THREAD

**Issue by icetech233** [ant-design-blazor/ant-design-blazor#3809]
```
	<Modal Keyboard=false MaskClosable=false
       @bind-Visible=@ModalVisible Footer=@null AfterClose=@AfterCloseHandle>
    <TitleTemplate>
	

@ref=_table

    private async void OnFinishHandle(EditContext editContext)
    {
        ModalVisible = false;
        await PostAuditAsync();
    }


        private async Task PostAuditAsync()
        {
            try
            {
                BaseResp resp = await BizSrv.AuditStockInAsync(auditModel);
                if (resp.Code == 200)
                {
                    _message.Success("操作成功", 3);
                    await Task.Run(async () => 
                    {
                        StockInListResp stockInResp = await BizSrv.GetStockInListAsync();
                        stockInList = stockInResp.Data.OrderByDescending(a => a.StockInID).ToList();
                        _table.ReloadData();
                    });
                }
                else
                {
                    _message.Error("操作失败:" + resp.Msg, 3);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
```

**Comment by icetech233** [comment]
_table.ReloadData();  加了 也没有用， 强制刷新是用哪个函数

**Comment by icetech233** [comment]
完整代码，
https://github.com/icetech233/wms/blob/frontend/fontend/MyAntDesignApp2/Pages/StockIn/RequestForm/RequestFormList.razor

https://github.com/icetech233/wms/blob/frontend/fontend/MyAntDesignApp2/Pages/StockIn/RequestForm/RequestFormList.razor.cs

**Comment by stfei** [comment]
是不是表格没有OnChange事件刷新不了吧？

**Comment by icetech233** [comment]
> 是不是表格没有OnChange事件刷新不了吧？刷新会触发这个事件 参考https://antblazor.com/zh-CN/components/table#components-table-demo-ajax

函数，单独执行是可以的，只要不是和modal 混在 一起就没有任何问题， modal visiable 改变 和table 不知道哪里冲突了，

**Comment by icetech233** [comment]
我的猜测是 modal 影藏的阻塞了， table的刷新， 元素是变了， 但是UI不刷新

**Comment by ElderJames** [comment]
Hello @icetech233 , please provide the complete duplicate code.

**Comment by icetech233** [comment]
> Hello @icetech233 , please provide the complete duplicate code.

完整代码，
https://github.com/icetech233/wms/blob/frontend/fontend/MyAntDesignApp2/Pages/StockIn/RequestForm/RequestFormList.razor

https://github.com/icetech233/wms/blob/frontend/fontend/MyAntDesignApp2/Pages/StockIn/RequestForm/RequestFormList.razor.cs

**Comment by stfei** [comment]
w

> > 是不是表格没有OnChange事件刷新不了吧？刷新会触发这个事件 参考 https://antblazor.com/zh-CN/components/table#components-table-demo-ajax
> 
> 函数，单独执行是可以的，只要不是和模态混在 一起就没有任何问题， modal visiable 改变 和table 不知道哪里冲突了，

我一般就是加入了OnChange实现函数中调用StateHasChanged();就可以

**Comment by icetech233** [comment]
> w
> 
> > > 是不是表格没有OnChange事件刷新不了吧？刷新会触发这个事件 参考 https://antblazor.com/zh-CN/components/table#components-table-demo-ajax
> > 
> > 
> > 函数，单独执行是可以的，只要不是和模态混在 一起就没有任何问题， modal visiable 改变 和table 不知道哪里冲突了，
> 
> 我一般就是加入了OnChange实现函数中调用StateHasChanged();就可以

数据有刷新，不生效而已

**Comment by GoldSucc** [comment]
@icetech233 You should use Interactive mode for interactive pages, otherwise it will not be changed

**Comment by ElderJames** [comment]
Hello @icetech233, have you solved the question?
