### ISSUE TITLE
Multilingual localization of form validation

### ISSUE THREAD

**Issue by 499105097** [ant-design-blazor/ant-design-blazor#3819]
Is there a solution for multilingual localization of form validation? When I was using form validation, I couldn't do multiple languages inside the model

**Comment by ElderJames** [comment]
Thanks for contacting us @499105097 , you can use the DataAnnotations localization:

```
<Form Model="@model"
      OnFinish="OnFinish"
      OnFinishFailed="OnFinishFailed"
      LabelColSpan="8"
      WrapperColSpan="16">
    <FormItem>
        <Input @bind-Value="@context.Username" />
    </FormItem>
    <FormItem>
        <InputPassword @bind-Value="@context.Password" />
    </FormItem>
    <FormItem WrapperColOffset="8" WrapperColSpan="16">
        <Checkbox @bind-Value="context.RememberMe">Remember me</Checkbox>
    </FormItem>
    <FormItem WrapperColOffset="8" WrapperColSpan="16">
        <Button Type="@ButtonType.Primary" HtmlType="submit">
            Submit
        </Button>
    </FormItem>
</Form>


@code
{
    public class Model
    {
        [Required(ErrorMessageResourceName = nameof(Resources.App.UserNameValidation), ErrorMessageResourceType = typeof(Resources.App))]
        [Display(Name = nameof(Resources.App.UserName), ResourceType = typeof(Resources.App))]
        public string Username { get; set; }

        [Required(ErrorMessageResourceName = nameof(Resources.App.PasswordValidation), ErrorMessageResourceType = typeof(Resources.App))]
        [Display(Name = nameof(Resources.App.Password), ResourceType = typeof(Resources.App))]
        public string Password { get; set; }

        public bool RememberMe { get; set; } = true;
    }

    private Model model = new Model();

    private void OnFinish(EditContext editContext)
    {
        Console.WriteLine($"Success:{JsonSerializer.Serialize(model)}");
    }

    private void OnFinishFailed(EditContext editContext)
    {
        Console.WriteLine($"Failed:{JsonSerializer.Serialize(model)}");
    }
}
```

**Comment by 499105097** [comment]
> Reference in
First of all, thank you for your answer. I have a few more questions. **Resources.App** Is this **the.resx** file under the corresponding Resources folder? If yes, the **.resx** file is not able to write references directly inside the code, do you need to create a virtual class with the same name, and then here **Resources.App** is actually pointing to the virtual class?

**Comment by 499105097** [comment]
> Thanks for contacting us @499105097 , you can use the DataAnnotations localization:
> 
> ```
> <Form Model="@model"
>       OnFinish="OnFinish"
>       OnFinishFailed="OnFinishFailed"
>       LabelColSpan="8"
>       WrapperColSpan="16">
>     <FormItem>
>         <Input @bind-Value="@context.Username" />
>     </FormItem>
>     <FormItem>
>         <InputPassword @bind-Value="@context.Password" />
>     </FormItem>
>     <FormItem WrapperColOffset="8" WrapperColSpan="16">
>         <Checkbox @bind-Value="context.RememberMe">Remember me</Checkbox>
>     </FormItem>
>     <FormItem WrapperColOffset="8" WrapperColSpan="16">
>         <Button Type="@ButtonType.Primary" HtmlType="submit">
>             Submit
>         </Button>
>     </FormItem>
> </Form>
> 
> 
> @code
> {
>     public class Model
>     {
>         [Required(ErrorMessageResourceName = nameof(Resources.App.UserNameValidation), ErrorMessageResourceType = typeof(Resources.App))]
>         [Display(Name = nameof(Resources.App.UserName), ResourceType = typeof(Resources.App))]
>         public string Username { get; set; }
> 
>         [Required(ErrorMessageResourceName = nameof(Resources.App.PasswordValidation), ErrorMessageResourceType = typeof(Resources.App))]
>         [Display(Name = nameof(Resources.App.Password), ResourceType = typeof(Resources.App))]
>         public string Password { get; set; }
> 
>         public bool RememberMe { get; set; } = true;
>     }
> 
>     private Model model = new Model();
> 
>     private void OnFinish(EditContext editContext)
>     {
>         Console.WriteLine($"Success:{JsonSerializer.Serialize(model)}");
>     }
> 
>     private void OnFinishFailed(EditContext editContext)
>     {
>         Console.WriteLine($"Failed:{JsonSerializer.Serialize(model)}");
>     }
> }
> ```

Function implemented, thank you
