### ISSUE TITLE
AutoComplete do not show options panel when loading page

### ISSUE THREAD

**Issue by chrcao** [ant-design-blazor/ant-design-blazor#3822]
when loading page, will get data from server and insert into AutoComplete options data.
this action is not triggered by user, and it is not necessary show options panel.

**Comment by ElderJames** [comment]
Thanks for conacting us @chrcao , how did you use the component? Please post your code here.

**Comment by ElderJames** [comment]
Hello @chrcao , we have updated the AutoComplete, please check if this issue have been fixed.
