### ISSUE TITLE
Unable to style DatePicker due to OverlayTrigger div

### ISSUE THREAD

**Issue by Epictek** [ant-design-blazor/ant-design-blazor#383]
Using the following blazor code:

```HTML
<RangePicker TValue="DateTime?" ClassName="col-span-7"/>
```

Results in the following HTML:

```HTML
<div class="" style="display: inline-flex; " id="ant-blazor-4e752cb7-5b21-44ae-87aa-4fb22f9d3aa3" _bl_2dbe0536-9d98-42bf-a788-09db05be7761="">
<div class="ant-picker ant-picker-default col-span-7 ant-picker-range" id="ant-blazor-bd2ecd23-a441-4cc7-89bb-efbd2e5d84b5" _bl_5155abb8-1947-4c6c-ad49-07ff1a7933a7="">
---
</div
</div>
```

it seems the `display: inline-flex` div is being created by OverlayTrigger. Is it possible to remove the `div` from OverlayTrigger or less ideally pass the class parameter through to it?

**Comment by anddrzejb** [comment]
It seems this is what I am trying to discuss in #898. Glad to see I am not the only one that sees this as a potential issue.
