### ISSUE TITLE
InputNumber: unable to invoke event-callback "OnChange"

### ISSUE THREAD

**Issue by Abin-Liu** [ant-design-blazor/ant-design-blazor#3849]
### Describe the bug

I'm using the InputNumber component in a project and want to be notified when the user changed its value, I tried to use the OnChange event-callback and got no luck.

Here's the demo code:
![code](https://github.com/ant-design-blazor/ant-design-blazor/assets/32606124/023dc4cc-4788-4cd4-8385-1b62ad55a9e7)

This is the error:
![error](https://github.com/ant-design-blazor/ant-design-blazor/assets/32606124/031bdca1-3790-4958-9573-a2f7a137df63)

I also tried to use "ValueChanged" got same error, and there seems no other events can serve this purpose.

**Comment by ElderJames** [comment]
Thanks for contacting us @Abin-Liu , please specific the TValue="int"

**Comment by Abin-Liu** [comment]
> Thanks for contacting us @Abin-Liu , please specific the TValue="int"

Did that already, no luck.

**Comment by Abin-Liu** [comment]
> Thanks for contacting us @Abin-Liu , please specific the TValue="int"

Oops, I must missed something before, I specified TValue as you said and it worked this time, so it's my bad, sorry about the trouble.

**Comment by GoldSucc** [comment]
@Abin-Liu by the way, I see you use @bind-Value="@MyValue". please check official blazor docs, you should use @bind-Value="MyValue" without second @.  I would recommend this article - https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0

**Comment by ElderJames** [comment]
Thank you @GoldSucc .
