### ISSUE TITLE
Table filter icon is not highlighted when Filter Dropdown with Search is active

### ISSUE THREAD

**Issue by PrincessLunaOfficial** [ant-design-blazor/ant-design-blazor#3851]
If the filter in the table has custom FilterDropdown with Search as a child element, filter icon in the table header will not be highlighted if you fill the searchbox. Overall it makes it impossible to see if current filter is active.

### Steps to reproduce
```
<Table @ref="_table" DataSource="dataSource" OnChange="OnChange" TItem="Data">
    <ColumnDefinitions>
        <PropertyColumn Property="c=>c.Name"
                        SorterCompare="@((a,b)=> a.Length - b.Length)"
                        SortDirections="new[] { SortDirection.Descending }" >
            <FilterDropdown>
                <Search Placeholder="Search Name" WrapperStyle="padding:20px;" @bind-Value="searchString" OnSearch="()=>_table?.ReloadData()" />
            </FilterDropdown>
        </PropertyColumn>
    </ColumnDefinitions>
</Table>
```
### Further technical details
Official demo
https://antblazor.com/en-US/components/table#components-table-demo-custom-filter-panel

**Comment by ElderJames** [comment]
Thanks for contacting us @PrincessLunaOfficial , this is beacuse you didn't update the filter state. 

https://antblazor.com/en-US/components/table#components-table-demo-restore-query-state

**Comment by PrincessLunaOfficial** [comment]
> Thanks for contacting us @PrincessLunaOfficial , this is beacuse you didn't update the filter state.

Thanks for reply, you are right. I hope that query state is not updated on the example page intentionally.

**Comment by ElderJames** [comment]
Maybe we can add a parameter `Filtered` or `Filtering` for marking the column is active.
