### ISSUE TITLE
EnumSelect: Exception when binding to nullable enums

### ISSUE THREAD

**Issue by tjdaniel** [ant-design-blazor/ant-design-blazor#3858]
Hi, there is an issue with EnumSelect after improvements of Version 0.19.0

If I use a nullable Enum as the bound value, e. g.:

```razor
<EnumSelect TEnum="Visibility?" Placeholder="Please select visibility" @bind-Value="@model.VisibilityNullable" />

@code {
  private Model model = new();
  public enum Visibility
  {
      Private,
      Public
  }
  
  public class Model
  {
      public Visibility? VisibilityNullable { get; set; }
  }
}
```

an exception is thrown while initialize/render:

 The type initializer for 'AntDesign.EnumHelper`1' threw an exception.
       ---> System.ArgumentException: Method 'Boolean HasFlag(System.Enum)' declared on type 'System.Enum' cannot be called with instance of type 'System.Nullable`1[antdesigntest.Models.Visibility]'

**Comment by ElderJames** [comment]
Thanks for contacting us @tjdaniel , we have fixed this issue in #3859 and will release in next path version.
