### ISSUE TITLE
The modal component Maximizable does not have a full-screen problem.

### ISSUE THREAD

**Issue by jxcproject** [ant-design-blazor/ant-design-blazor#3872]
### Describe the bug

When the component is set to Resizable to true, modal does not have full screen when resize and then maximize it.

![screenshots](https://github.com/ant-design-blazor/ant-design-blazor/assets/8786702/188bca0d-b028-4b34-a21a-9d3f273610d5)

### Steps to reproduce (please include code)
```

 <Button Icon="@IconType.Outline.Search" OnClick="@(()=>{ this._modalVisible=true;})" />

 <Modal Title="选择"
        Resizable="@true"
        Draggable="@true"
        Maximizable = "@true"
        BodyStyle="text-align: center;"
        Visible="@this._modalVisible"
        OnOk="@this.HandleModalOk"
        OnCancel="@this.HandleModalCancel">
        TEST
 </Modal>
 
@code
{
    private bool _modalVisible = false;
    private void HandleModalOk()
    {
        this._modalVisible = false;
    }
    private void HandleModalCancel()
    {
        this._modalVisible = false;
    }
}
```
 

### Further technical details
- AntDesign Nuget Package version 0.19.0

**Comment by ElderJames** [comment]
This is because the style of modal-content got width after resize. And it keep this width when it is Maximized.

![image](https://github.com/user-attachments/assets/78f693f9-8e81-4a0d-9ff3-754b02046222)
