### ISSUE TITLE
Suspected incidents bubble up

### ISSUE THREAD

**Issue by 499105097** [ant-design-blazor/ant-design-blazor#3874]
<Search @bind-Value="keywords" OnSearch="OnSearch" OnPressEnter="OnSearch" AllowClear Loading="@loading" />
Why do I call the OnSearch method twice when I press enter?

**Comment by ElderJames** [comment]
Thanks for contacting us @499105097 , you just need to set one of `OnSearch` and `OnPressEnter`

**Comment by 499105097** [comment]
> Thanks for contacting us @499105097 , you just need to set one of `OnSearch` and `OnPressEnter`

Thanks.
