### ISSUE TITLE
Environmental problem

### ISSUE THREAD

**Issue by 499105097** [ant-design-blazor/ant-design-blazor#3876]
"environmentVariables": {
   "ASPNETCORE_ENVIRONMENT": "production"
 } 
After my environment variable is set to non-development, the project starts, and all the static files required by the page can not be found. What is the reason?
![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/22740155/3d602e0e-9ef0-4a79-8609-5262c77253bc)

**Comment by ElderJames** [comment]
This is not the issue of this project. Please check the server and port.
