### ISSUE TITLE
Is Tabs Draggable broken?

### ISSUE THREAD

**Issue by Zou-Jia** [ant-design-blazor/ant-design-blazor#3887]
### Describe the bug

See the screen recording. I cannot drag and drop to re-order tabs from https://antblazor.com/zh-CN/components/tabs#components-tabs-demo-custom-tab-bar-node

https://github.com/ant-design-blazor/ant-design-blazor/assets/14681050/4030a5a4-f09d-4fbe-bfaa-4b28e052a1b8

### Steps to reproduce (please include code)
Use sample component from https://antblazor.com/zh-CN/components/tabs#components-tabs-demo-custom-tab-bar-node
drag the tabs around and see that result does not change

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thank you for contacing us @Zou-Jia , it did break.
