### ISSUE TITLE
About the value change of AntDesign.Select

### ISSUE THREAD

**Issue by coolmint123** [ant-design-blazor/ant-design-blazor#3888]
### Describe the bug

Dear Developers,
When I change the value of AntDesign.InputNumber from 1 to 0, AntDesign.Select does not become a.
Is there a workaround?

### Steps to reproduce (please include code)
```
    <AntDesign.InputNumber TValue="int" Min="0" Max="9999" Value=@Code Style="width:100px"
                           ValueChanged="@(e =>{ Code = e; StateHasChanged(); })">
    </AntDesign.InputNumber>
    <AntDesign.Select DataSource="@Items" Style="width:100px"
                      Value="@Code"
                      LabelName="@nameof(Item.Name)"
                      ValueName="@nameof(Item.Code)"
                      OnSelectedItemChanged="@((Item e) => {Code = e.Code; StateHasChanged(); })">
    </AntDesign.Select>

@code {
    public class Item
    {
        public int Code { get; set; }
        public string? Name { get; set; }
    }
    public List<Item> Items { get; set; } = new();
    public int Code { get; set; }

    protected override void OnInitialized()
    {
        Items = new List<Item> { new() { Code = 0, Name = "a" }, new() { Code = 1, Name = "b" } };
    }
}
```

![1](https://github.com/ant-design-blazor/ant-design-blazor/assets/27341028/45310d0b-e054-4e2a-9775-9b42e4672af6)
![0](https://github.com/ant-design-blazor/ant-design-blazor/assets/27341028/390fcb46-e45f-457a-8064-0f779ae9f6f5)

### Further technical details
- AntDesign Nuget Package version 0.19.0
- Include the output of `dotnet --info`
.NET SDK:
 Version:           8.0.102
 Commit:            64f1bc458e
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows

**Comment by ElderJames** [comment]
fixed.
