### ISSUE TITLE
Drawer and Modal components do not reset body height to 100% after closure

### ISSUE THREAD

**Issue by ozzioma** [ant-design-blazor/ant-design-blazor#393]
Hi,

I think there's a bug with the Drawer and Modal components.
Previously when you close either component, the page/body height gets reset normal or 100%.
This restores the vertical scroll bars up and down the page.

Now, the scroll bars are not restored and this affected every other page.
Yes, even after you navigate away from the page container either the Drawer or Modal component,
the vertical scroll bars are not enabled,as the body height has been reset to auto.

Kindly fix asap.

Thanks for the great work!

**Comment by zxyao145** [comment]
Hi, what version do you use? And could you provide a simple example?

Thanks a lot!

**Comment by ozzioma** [comment]
hi @zxyao145 

I'm using the latest bits.
I've tested over 10 version between https://www.nuget.org/packages/AntDesign/0.2.0-nightly-200720162348
and https://www.nuget.org/packages/AntDesign/0.2.0-nightly-200710162728.

As for the example, see below

I have this drawer in page that opens a form,

```
<Drawer @ref="@createDrawer" Closable="true" Visible="showCreateDrawer" Title='("Add New Code")'
        OnClose="onCreateDone">

    <CreateFormGlobalCodes @ref="@createForm" @bind-Model="@CreateModel" @bind-ShowModal="@showCreateDrawer"></CreateFormGlobalCodes>

</Drawer>
```

The above drawer opens the CreateFormGlobalCodes form which contains the Modal below

```
<Modal Title="@("Notification")" Visible="@showPopup" DestroyOnClose="true"
       OnOk="OnOkPopup" OkText="@("Ok")"
       OnCancel="OnCancelPopup" CancelText="@("Add new")">
    <p>@_modalText</p>
</Modal>

```

When this modal is closed, the page height or overflow CSS property is set to "none".
That means that particular page can't scroll, not just that but all other pages can't scroll too.

What could be the cause?

Thanks!

**Comment by zxyao145** [comment]
> hi @zxyao145
> 
> I'm using the latest bits.
> I've tested over 10 version between https://www.nuget.org/packages/AntDesign/0.2.0-nightly-200720162348
> and https://www.nuget.org/packages/AntDesign/0.2.0-nightly-200710162728.
> 
> As for the example, see below
> 
> I have this drawer in page that opens a form,
> 
> ```
> <Drawer @ref="@createDrawer" Closable="true" Visible="showCreateDrawer" Title='("Add New Code")'
>         OnClose="onCreateDone">
> 
>     <CreateFormGlobalCodes @ref="@createForm" @bind-Model="@CreateModel" @bind-ShowModal="@showCreateDrawer"></CreateFormGlobalCodes>
> 
> </Drawer>
> ```
> 
> The above drawer opens the CreateFormGlobalCodes form which contains the Modal below
> 
> ```
> <Modal Title="@("Notification")" Visible="@showPopup" DestroyOnClose="true"
>        OnOk="OnOkPopup" OkText="@("Ok")"
>        OnCancel="OnCancelPopup" CancelText="@("Add new")">
>     <p>@_modalText</p>
> </Modal>
> ```
> 
> When this modal is closed, the page height or overflow CSS property is set to "none".
> That means that particular page can't scroll, not just that but all other pages can't scroll too.
> 
> What could be the cause?
> 
> Thanks!



Thank you very much!
 
Because modal and drawer disable scrollbars when they are opening, but they are not reset correctly when they are closed. We will fix it as soon as possible.
