### ISSUE TITLE
AutoComplete do not show options panel when mouse first click

### ISSUE THREAD

**Issue by 707wk** [ant-design-blazor/ant-design-blazor#3950]
where 0.19.1 update to 0.19.3, the options panel not show when mouse first click

**Comment by ElderJames** [comment]
Thanks for contacting us @707wk , this is by design. If you want to show options when click the input box, you can use select and enable searching.

**Comment by 707wk** [comment]
@ElderJames but ant-design's AutoComplete can show options panel when mouse first click, and have a defaultOpen property to disabled the function

**Comment by 707wk** [comment]
@ElderJames  I want input new value or quick select old value
