### ISSUE TITLE
table component group title style

### ISSUE THREAD

**Issue by moumousoup** [ant-design-blazor/ant-design-blazor#3955]
Grouping of table component How to style the group title I want to add an action button
![cc](https://github.com/ant-design-blazor/ant-design-blazor/assets/131156503/146e2c84-47eb-418f-a9c0-67429e3397b7)

**Comment by ElderJames** [comment]
Thanks for contacting us @moumousoup , please help us for that feature. You can add a RenderFargment parameter to achieve that.
