### ISSUE TITLE
issue with cascader

### ISSUE THREAD

**Issue by Mussnicht** [ant-design-blazor/ant-design-blazor#396]
在ant-design官网上点击级联选择，选中到最后，控制台会出现错误：There is no event handler associated with this event. EventId:xx。但不影响业务，onchange有效，系统正常运行。

**Comment by yaolunmao** [comment]
> 在ant-design官网上点击级联选择，选中到最后，控制台会出现错误：There is no event handler associated with this event. EventId:xx。但不影响业务，onchange有效，系统正常运行。

我也遇到了这个问题 请问您解决了吗

**Comment by anddrzejb** [comment]
@Mussnicht @yaolunmao I was unable to recreate this. Can you provide a repro?

**Comment by ElderJames** [comment]
#1112  已修复了。
