### ISSUE TITLE
When using Reusetabs, there is no response to open a new page

### ISSUE THREAD

**Issue by Duyongzhe123** [ant-design-blazor/ant-design-blazor#3972]
I create a project from template and I made some changes. Now I found that there is no response to open a new page when use ReuseTabs .
![image](https://github.com/user-attachments/assets/bb8a2ac0-24c4-411b-8ce0-fce13d3a382d)

But  if i disable Reusetabs  and use @body it Become normal.so I want to know if there have some configuration that I missed.
![image](https://github.com/user-attachments/assets/10d4176c-73d7-4288-a716-48c9f0344b4b)
![3QYG@J$8I RO6P`75PBL H0](https://github.com/user-attachments/assets/575f2166-0152-4965-88f1-ccb8887eb1b7)

**Comment by Duyongzhe123** [comment]
[TMS.zip](https://github.com/user-attachments/files/16202336/TMS.zip)
This is the code.

**Comment by ElderJames** [comment]
Please remove this line.

![O~MH%06O$B%G44)JL6T0S6J](https://github.com/user-attachments/assets/f7d8c286-9ad4-4576-a3ac-d7f672911b3e)

**Comment by ElderJames** [comment]
update to latest version can solve the issue.
