### ISSUE TITLE
Discussion of the tab header for the component [ReuseTabs].

### ISSUE THREAD

**Issue by Ashhhhhh520** [ant-design-blazor/ant-design-blazor#3977]
In experiments with the component ReuseTabs, I suggest that the title of the TabPane is bound to a MenuItem.Name instead of a Url when the [ReuseTabsPage] attribute is not used

![image](https://github.com/user-attachments/assets/02e5a2ac-20ea-486d-8542-aeb6f6321e13)

![image](https://github.com/user-attachments/assets/b8be9c36-8f57-4b9a-9ef7-b6ee9a35beca)

In ReuseTabsService.cs
![image](https://github.com/user-attachments/assets/c62b0405-7530-4988-af43-5e7ee79e4be4)

Property: Title is a RenderFragment  when generating a menu list, it is not easy to convert from json to RenderFragment，
may be add a new property like Name would be more effective
![image](https://github.com/user-attachments/assets/40a2eecc-76e9-49a5-90d2-1e541042a718)

**Comment by ElderJames** [comment]
Thanks for contacting us @Ashhhhhh520 ,we have implement this feature in #3960 and will release it in 0.20.0
