### ISSUE TITLE
Tree.CheckedKeysChanged always gives empty array

### ISSUE THREAD

**Issue by frindler** [ant-design-blazor/ant-design-blazor#3983]
### Describe the bug

From 0.19.1 to 0.19.2 the `CheckedKeysChanged` event (or `@bind-CheckedKeys`) in `Tree` is broken: In 0.19.2+ the array of strings passed to `CheckedKeysChanged` is always empty!

Maybe this is related to https://github.com/ant-design-blazor/ant-design-blazor/pull/3899

### Steps to reproduce (please include code)

```
<Tree
      TItem="XElement"
      Checkable
      DefaultExpandAll
      DataSource="@(_tree is {} e ? [e] : [])"
      DefaultCheckedKeys="@_selected"
      @bind-CheckedKeys="@_selected"
      TitleTemplate="@TreeNodeTemplate"
      ChildrenExpression="@(x => x.DataItem.Elements())"
      IconExpression="@null"
      IsLeafExpression="@(x => x.DataItem.Name == "file")"
      KeyExpression="@(x => x.DataItem.Attribute("path")?.Value ?? "")">
</Tree>
```

`_selected` remains empty even after ticking items.

### Further technical details
- Tested this with 0.19.2 - .5 (it works on 0.19.1)
- .NET 8.0.303

**Comment by pankey888** [comment]
I'm sorry, because you haven't provided the full code, I'm unable to locate the issue you mentioned through your code. I have created a similar demo based on your code , but I haven't found what the problem is. If your issue still exists, please upload a full demo so that I can pinpoint the problem. Thank you!
```
@using System.Text.Json
<div>
    <Tree ShowIcon Checkable DefaultExpandAll
          DefaultCheckedKeys="@_selected"
          @bind-CheckedKeys="@_selected"
          DataSource="datas"
          KeyExpression="x=>x.DataItem.Id"
          TitleExpression="x => x.DataItem.Title"
          ChildrenExpression="x => x.DataItem.Children">
    </Tree>
</div>
@JsonSerializer.Serialize(_selected)

@code {
    string[] _selected;

    List<Data> datas = new List<Data>()
    {
        new("0-0","0-0")
        {
            Children = new()
            {
                new("0-0-0", "0-0-0")
                {
                    Children = new()
                    {
                        new("0-0-0-0", "0-0-0-0"),
                        new("0-0-0-1", "0-0-0-1"),
                        new("0-0-0-2", "0-0-0-2"),
                    }
                },
                new("0-0-1","0-0-1")
                {
                    Children = new()
                    {
                        new("0-0-1-0", "0-0-1-0"),
                        new("0-0-1-1", "0-0-1-1"),
                        new("0-0-1-2", "0-0-1-2"),
                    }
                },
                new("0-0-2","0-0-2"),
            }
        },
        new("0-1","0-1")
        {
            Children = new()
            {
                new("0-1-0", "0-1-0")
                {
                    Children = new()
                    {
                        new("0-1-0-0","0-1-0-0"),
                        new("0-1-0-1","0-1-0-1"),
                        new("0-1-0-2","0-1-0-2"),
                    },
                },
                new ("0-1-1","0-1-1")
                {
                    Children = new()
                    {
                        new("0-1-1-0","0-1-1-0"),
                        new("0-1-1-1","0-1-1-1"),
                        new("0-1-1-2","0-1-1-2"),
                    },
                },
                new("0-1-2","0-1-2"),
            }
        },
        new("0-2","0-2"),
    };

    private record Data(string Id, string Title)
    {
        public List<Data> Children { get; set; } = new List<Data>();
    }
}
```

![20240716093347](https://github.com/user-attachments/assets/93c64c6e-950b-45a6-b102-dcadfc5e5317)

**Comment by frindler** [comment]
Thanks for the quick reaction! At this point I can't get anything to select... See https://github.com/frindler/AntTreeTest With .NET 8.0.303 and AntDesign Blazor 0.19.5.1 I cannot check anything and no OnCheck events are fired. This is just the standard Blazor server template. Strangely, it works if I try it on WASM.

**Comment by frindler** [comment]
Even for WASM the checking does not seem to be working correctly: In https://github.com/frindler/AntTreeTestWASM if you check file1 it works OK, but then check dir1 and then again file1 and it does not seem to be updating the checked keys.

**Comment by pankey888** [comment]
> Thanks for the quick reaction! At this point I can't get anything to select... See https://github.com/frindler/AntTreeTest With .NET 8.0.303 and AntDesign Blazor 0.19.5.1 I cannot check anything and no OnCheck events are fired. This is just the standard Blazor server template. Strangely, it works if I try it on WASM.

I have tried your code, and even after downgrading AntDesign to version 0.18.3 and unbinding CheckedKeys, the entire tree is still uncheckable. Perhaps this is not an issue with the tree itself, but rather a compatibility issue with AntDesign in a Blazor Web App targeting .NET 8.
Maybe you can try the Ant Design Pro Blazor App template.

**Comment by pankey888** [comment]
> Even for WASM the checking does not seem to be working correctly: In https://github.com/frindler/AntTreeTestWASM if you check file1 it works OK, but then check dir1 and then again file1 and it does not seem to be updating the checked keys.

Try change the type of _tree to List<XElement>:
```
@page "/"
@using System.Text.Json
@using System.Xml.Linq

<PageTitle>Home</PageTitle>

<Tree
      TItem="XElement"
      Checkable
      DefaultExpandAll
      DataSource="@_tree"
      DefaultCheckedKeys="@_selectedItems"
      @bind-CheckedKeys="@_selectedItems"
      ChildrenExpression="@(x => x.DataItem.Elements())"
      IconExpression="@null"
      TitleExpression="@(x => x.DataItem.Attribute("title")?.Value ?? "")"
      IsLeafExpression="@(x => x.DataItem.Name == "file")"
      KeyExpression="@(x => x.DataItem.Attribute("path")?.Value ?? "")">
</Tree>
@JsonSerializer.Serialize(_selectedItems)



@code
{
    string[] _selectedItems = new string[0];

    List<XElement> _tree = new() {
        new XElement("dir",
                     new XAttribute("title", "/"),
                     new XAttribute("path", "/"),
                     new XElement("dir",
                                  new XAttribute("title", "dir1"),
                                  new XAttribute("path", "/dir1/"),
                                  new XElement("file",
                                               new XAttribute("title", "file1"),
                                               new XAttribute("path", "/dir1/file1")),
                                  new XElement("file",
                                               new XAttribute("title", "file2"),
                                               new XAttribute("path", "/dir1/file2"))
                     ),
                     new XElement("dir",
                                  new XAttribute("title", "dir2"),
                                  new XAttribute("path", "/dir2/"),
                                  new XElement("file",
                                               new XAttribute("title", "file3"),
                                               new XAttribute("path", "/dir1/file3")),
                                  new XElement("file",
                                               new XAttribute("title", "file4"),
                                               new XAttribute("path", "/dir1/file4"))
                     )
        ) };
}
```

**Comment by frindler** [comment]
OK - I can confirm it works in the WASM project but not in the Blazor Server project. This is a bit strange since the original problem occurred in a Blazor Server project. There, it would let me check elements, but it would not notify about the changes. The template I'm using is just the default .NET 8 Blazor Server one. I agree it looks like some form of incompatibility.

**Comment by frindler** [comment]
I just discovered that the Tree works in the .NET 8 Blazor app if I add `@rendermode InteractiveServer` to the top of the Home page (see the latest commit in the repo https://github.com/frindler/AntTreeTest). There was a change in Blazor rendering models in 8.0 and maybe there is some incompatibility there (I haven't updated my app to the new rendering model even though I'm using .NET 8).

**Comment by pankey888** [comment]
> I just discovered that the Tree works in the .NET 8 Blazor app if I add `@rendermode InteractiveServer` to the top of the Home page (see the latest commit in the repo https://github.com/frindler/AntTreeTest). There was a change in Blazor rendering models in 8.0 and maybe there is some incompatibility there (I haven't updated my app to the new rendering model even though I'm using .NET 8).

Yes, for Blazor WebApp, you need to specify render mode for interactivity,  you can also add it to `<Routes />`:
```
<Routes @rendermode="InteractiveServer" />
<AntContainer @rendermode="InteractiveServer" />
```
See [https://antblazor.com/en-US/docs/introduce](https://antblazor.com/en-US/docs/introduce)

**Comment by frindler** [comment]
OK, so I was able to transition my app to the .NET 8 Blazor rendering model and make the `_tree` variable of type `List<...>`. This made it work. There may be an incompatibility with running the old .NET 7 Blazor model under .NET 8 (which is still supported), but it's probably not worth investing many resources into investigating this. Thanks for your help!

**Comment by frindler** [comment]
OK, so I was able to transition my app to the .NET 8 Blazor rendering model and make the `_tree` variable of type `List<...>`. This made it work. There may be an incompatibility with running the old .NET 7 Blazor model under .NET 8 (which is still supported), but it's probably not worth investing many resources into investigating this. Thanks for your help!
