### ISSUE TITLE
After updating to version 0.19.5.1, the OnFeedbackOkAsync method in the Modal cannot be called.

### ISSUE THREAD

**Issue by stfei** [ant-design-blazor/ant-design-blazor#3984]
0.19.5.1 After updating, the ModalService.CreateConfirmAsync method was used to create a dialog box.

In the component that inherits from FeedbackComponent,
public override async Task OnFeedbackOkAsync(ModalClosingEventArgs args)

The OK button click event does not trigger this method as expected. This issue might be resolved in version 0.19.4, behaving as intended.

**Comment by zhaoyangguang** [comment]
俺也一样
