### ISSUE TITLE
Regarding Tables Enhanced features of QueryModel Filter

### ISSUE THREAD

**Issue by Ashhhhhh520** [ant-design-blazor/ant-design-blazor#3987]
Adding an additional filter function to the QueryModel with a return value of Expression<Func<TItem, bool>> is easier to extend than the existing IQueryable <TItem> ExecuteQuery

In QueryModel.cs
![image](https://github.com/user-attachments/assets/f908cf4c-74d5-40db-874c-f1af02541c41)

In FilterModel.cs 

![image](https://github.com/user-attachments/assets/ff68df37-0885-4cee-9bc1-045e6abf203d)

**Comment by ElderJames** [comment]
Thanks for contacting us @Ashhhhhh520 , you just feel free to send a PR for this.
