### ISSUE TITLE
SimpleSelect render incorrect data

### ISSUE THREAD

**Issue by li-zheng-hao** [ant-design-blazor/ant-design-blazor#3989]
### Describe the bug

after SimpleSelect datasource updated, the ui rendered incorrect data

![9a20326cb2c912121d648bc86dba913](https://github.com/user-attachments/assets/6090bb21-f46a-4b07-93d3-836a480d3f15)

![6d4e4d866eec80a8d74e05fa5c2c4cb](https://github.com/user-attachments/assets/83d4cd91-b7ad-4d94-b716-f97bccef5d26)

### Steps to reproduce (please include code)

create a new blazor server project and replace the contents of the Home.razor  with the following code:

```c#
@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>
<div>
    <SimpleSelect ValueChanged="Callback">
        <SelectOptions>
            @foreach (var item in FirstList)
            {
                <SimpleSelectOption Value="@item" Label="@item"></SimpleSelectOption>
            }
        </SelectOptions>
    </SimpleSelect>

    <SimpleSelect>
        <SelectOptions>
            @foreach (var item in SecondList)
            {
                Console.WriteLine(item);
            <SimpleSelectOption Value="@item" Label="@item"></SimpleSelectOption>
            }
        </SelectOptions>
    </SimpleSelect>
</div>
@code{

    List<string> FirstList = new() { "1", "2" };
    List<string> SecondList = new(){"1","2"};

    private void Callback(string newValue)
    {
        SecondList = FirstList.Where(it => it == newValue).ToList();
    }

}
```

run project and select `2` in first select control, you will see the second select control's options will change to only 1, which should be 2

![image](https://github.com/user-attachments/assets/20db6b03-63e1-4ea3-b289-39b54e9cf589)

### Exceptions (if any)

no exception

### Further technical details
- AntDesign Nuget Package version : 0.19.5.1
- Include the output of `dotnet --info` : dotnet 8
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version : Rider 2024.1.2

**Comment by ElderJames** [comment]
Thanks for contacting us @li-zheng-hao , this is not the bug from AntDesign, but is by the design of blazor. You need to assign the @key for the foreach loop items.

```

<h1>Hello, world!</h1>
<div>
    <SimpleSelect ValueChanged="Callback">
        <SelectOptions>
            @foreach (var item in FirstList)
            {
                <SimpleSelectOption Value="@item" Label="@item" @key="item"></SimpleSelectOption>
            }
        </SelectOptions>
    </SimpleSelect>

    <SimpleSelect>
        <SelectOptions>
            @foreach (var item in SecondList)
            {
                Console.WriteLine(item);
            <SimpleSelectOption Value="@item" Label="@item" @key="item"></SimpleSelectOption>
            }
        </SelectOptions>
    </SimpleSelect>
</div>
@code{

    List<string> FirstList = new() { "1", "2" };
    List<string> SecondList = new(){"1","2"};

    private void Callback(string newValue)
    {
        SecondList = FirstList.Where(it => it == newValue).ToList();
    }

}
```

**Comment by li-zheng-hao** [comment]
thanks for your reply.
