### ISSUE TITLE
Changing a RangePicker value by a PresetRange does not call onChange

### ISSUE THREAD

**Issue by ernstjoss** [ant-design-blazor/ant-design-blazor#3996]
### Describe the bug

Having a `RangePicker` with some `Presets` defined. If selecting a `presetRange`, the `RangePicker` visually applies the dates of the `presetRange`, but does not call `onChange` method. This was working on version 0.14.2 and is now broken on current newest 0.19.5.1 version.

### Further technical details
- AntDesign Nuget Package version: 0.19.5.1
- Include the output of `dotnet --info`
```
 .NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.5638171e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
 [wasm-tools]
   Installation Source: VS 17.9.34616.47
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.2\WorkloadManifest.json
   Install Type:              Msi
```

**Comment by ElderJames** [comment]
Thank you for contacting us @ernstjoss , we will fix this issue in next release.
