### ISSUE TITLE
Cascader: OnChange is not called when "ClearAllSelected" is executed (Clear button pressed)

### ISSUE THREAD

**Issue by vaderr12** [ant-design-blazor/ant-design-blazor#400]
OnChange is not called when "ClearAllSelected" is executed (Clear button pressed)

**Comment by ElderJames** [comment]
Thank you for contacting us @vaderr12 .
Please pin your code here. We will check and fix it soon.

**Comment by ElderJames** [comment]
Hi @vaderr12 , could you please try 0.7.1?
