### ISSUE TITLE
Exception When ImagePreview Closed

### ISSUE THREAD

**Issue by skl-hyf** [ant-design-blazor/ant-design-blazor#4007]
### Describe the bug

When ImagePreview is closed, an exception is thrown in the console. Versions 0.19.5 and 0.19.6 both have this issue, but 0.19.4 is running well.

### Steps to reproduce (please include code)

Any [example ](https://antblazor.com/en-US/components/image)can be reproduced.

### Exceptions (if any)

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'removeChild')
TypeError: Cannot read properties of null (reading 'removeChild')
![image](https://github.com/user-attachments/assets/fbc0ff06-89b1-454a-92f1-60b26c8920a3)

### Further technical details
- AntDesign Nuget Package version 
 0.19.5 or 0.19.6
- Include the output of `dotnet --info`
 .NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.34944930
 MSBuild version:   17.10.4+10fbfbf2e
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS2022 17.10.4

**Comment by Kand-wang** [comment]
When Modal is closed, an exception is thrown in the console too.
