### ISSUE TITLE
Slider Not Working

### ISSUE THREAD

**Issue by samfoust** [ant-design-blazor/ant-design-blazor#403]
https://ant-design-blazor.github.io/en-US/components/slider#API

Slider components are not sliding, they also appear to break when using TValue<int>

**Comment by ElderJames** [comment]
Thanks for contacting us @samfoust .
Could you  please pin your code here?

**Comment by samfoust** [comment]
` <Slider TValue="double" DefaultValue="35" Disabled="@Diabled"  />`
Same code as in the documentation. The slider in the [documentation ](https://ant-design-blazor.github.io/en-US/components/slider) is not working as well. Also when setting `TValue="int"` an exception is thrown as the code is looking for `double`

**Comment by Brian-Ding** [comment]
The exception is thrown on purpose if users try to set the TValue as int, please use double for now
But we will support int in the future.

**Comment by samfoust** [comment]
@Brian-Ding Thanks! Looks like #415 fixed the other issue as well.
