### ISSUE TITLE
Modal.Confirm will be inject 'ant-scrolling-effect' class

### ISSUE THREAD

**Issue by NightSpark75** [ant-design-blazor/ant-design-blazor#404]
開啟Modal.Confirm時
會在Body標籤裡插入ant-scrolling-effect
該class有width: calc(100% - 17px);的style
無論我原本的畫面有沒有scroll bar

**Comment by zxyao145** [comment]
> 開啟Modal.Confirm時
> 會在Body標籤裡插入ant-scrolling-effect
> 該class有width: calc(100% - 17px);的style
> 無論我原本的畫面有沒有scroll bar

非常感謝！我確定這是一個bug，我們將會儘快修復它，最遲將在今晚。
