### ISSUE TITLE
Prerender and render results do not match

### ISSUE THREAD

**Issue by freeman888** [ant-design-blazor/ant-design-blazor#4055]
### Server mode prerender does not match render result

My Blazor project uses the ssr and uses components of Antd. 
The first time I enter the page or refresh the page, there will be a moment of unstyled documents, and then the style will be rendered, resulting in a flash. It is more obvious when the network is poor. How to render the style well and then display it.

#### Firstly the page will show without style
![Before](https://github.com/user-attachments/assets/775b23c3-9a27-4dbe-ba2c-98c6d6bf265f)
#### Then the page will render correctly
![After](https://github.com/user-attachments/assets/862426a5-5c7f-403b-bb64-3ccaf7f125ec)

### Steps to reproduce 
The page is easy and the prerende is set to true.

<img width="949" alt="截屏2024-08-02 02 05 12" src="https://github.com/user-attachments/assets/e4bb21cf-0221-4a9b-ac5a-6701e9c0d273">
<img width="800" alt="截屏2024-08-02 02 05 55" src="https://github.com/user-attachments/assets/149cee9d-a15f-499c-ab15-b2d4564cef40">

### Further technical details
- AntDesign Nuget Package Version: 0.19.6.2
- Dotnet 8
- Rider

**Comment by ElderJames** [comment]
Thanks for contacting us @freeman888 , please add the css link in App.razor.

<link href="_content/AntDesign/css/ant-design-blazor.css" rel="stylesheet">

**Comment by freeman888** [comment]
> Thanks for contacting us @freeman888 , please add the css link in App.razor.
> 
> ```
> <link href="_content/AntDesign/css/ant-design-blazor.css" rel="stylesheet">
> ```

It works, thank u.
