### ISSUE TITLE
[Feature Request] Raw html support for Tooltip Title

### ISSUE THREAD

**Issue by zxyao145** [ant-design-blazor/ant-design-blazor#406]
Tootip的Title可不可以支持对Html字符串的渲染？

**Comment by StardustDL** [comment]
Tooltip 的 Title 支持 RenderFragment, 所以应该是支持 HTML 渲染的。把字符串放到一个 RenderFragment 里

```razor
@<Template>@((MarkupString)rawContent)</Template>
```

这里有个具体的例子（不过使用的是 Comment 的 Content 属性）

https://github.com/acblog/acblog/blob/master/src/client/AcBlog.Client.WebAssembly/Components/CommentListItem.razor

**Comment by zxyao145** [comment]
> Tooltip 的 Title 支持 RenderFragment, 所以应该是支持 HTML 渲染的。把字符串放到一个 RenderFragment 里
> 
> ```
> @<Template>@((MarkupString)rawContent)</Template>
> ```
> 
> 这里有个具体的例子（不过使用的是 Comment 的 Content 属性）
> 
> https://github.com/acblog/acblog/blob/master/src/client/AcBlog.Client.WebAssembly/Components/CommentListItem.razor

确实可以这样子实现，但是我想知道的是，在 Tooltip 内部使用 MarkupString 会不会更好些？

**Comment by ElderJames** [comment]
@zxyao145 没问题，欢迎pr

**Comment by zxyao145** [comment]
@ElderJames 其实我想知道，无论是否是html字符串，都使用 MarkupString，有没性能的损耗 😅

**Comment by ElderJames** [comment]
我建议是加一个markupstring类型，让用户选择是否渲染html

**Comment by zxyao145** [comment]
> 我建议是加一个markupstring类型，让用户选择是否渲染html

是的，这样可能比较好
