### ISSUE TITLE
Select All Rows of a Table

### ISSUE THREAD

**Issue by adamdriscoll** [ant-design-blazor/ant-design-blazor#4111]
This may just be a question, but I can't seem to find the answer. I have a table with more than one page of rows. I have selection enabled. I would expect that selecting all items would select rows beyond the first page, but it only selects rows on the displayed page. Is there a setting that I can enable that selects all rows or a workaround for me to do so? 

If not, could I ask for a feature similar to what is described above?

**Comment by ElderJames** [comment]
Thanks for contacting us @adamdriscoll , the default behavior of the header checkbox is only check the current page. Because most cases are server-side data, the user only loads the data for the current page.

But you can add a button somewhere, and assign all data to the SelectedRows parameter when user click it. I will add a `SelectAll` event callback in next release.

```
<Button OnClick="SelectAll"> Select All </Button>
<Table @ref="table" DataSource="@data" @bind-SelectedRows="selectedRows" RowKey="x=>x.Name">
    <Selection />
    <PropertyColumn Property="c=>c.Name">
        <a>@context.Name</a>
    </PropertyColumn>
    <PropertyColumn Property="c=>c.Age" />
    <PropertyColumn Property="c=>c.Address" />
</Table>


@code {

    ITable table;
    IEnumerable<Column> selectedRows;

    void SelectAll()
    {
        selectedRows = data;
    }

    class Column
    {
        public string Name { get; set; }

        public int Age { get; set; }

        public string Address { get; set; }
    }

    Column[] data =
    {
        new Column()
        {
            Name = "John Brown",
            Age = 32,
            Address = "New York No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Jim Green",
            Age = 42,
            Address = "London No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Joe Black",
            Age = 32,
            Address = "Sidney No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Disabled User",
            Age = 99,
            Address = "Sidney No. 1 Lake Park",
        }
    };
}
```

**Comment by adamdriscoll** [comment]
Thanks!! I'll implement the button and thanks for adding the callback. That'll be helpful.
