### ISSUE TITLE
The _editContext variable of the form may be null

### ISSUE THREAD

**Issue by shibox** [ant-design-blazor/ant-design-blazor#4115]
The _editContext variable of the form may be null in some cases, leading to null pointer exceptions，like this：
![066fdc6f56f9579b081c30806b7ea64](https://github.com/user-attachments/assets/0c650a35-d501-4d5e-8df6-5d933821c253)
It's better to add a check：
if (UseRulesValidator && _editContext != null)
{
    _editContext.OnFieldChanged += RulesModeOnFieldChanged;
    _editContext.OnValidationRequested += RulesModeOnValidationRequested;
}

**Comment by ElderJames** [comment]
Thank you @shibox , just feel free to ceate a PR.
