### ISSUE TITLE
抽屉关闭存在bug，有报错

### ISSUE THREAD

**Issue by pookokok** [ant-design-blazor/ant-design-blazor#413]
![image](https://user-images.githubusercontent.com/6156925/88254871-38c37000-cce9-11ea-958b-7dad02f5af2d.png)

使用DrawerService 做抽屉时，使用按钮触发关闭事件时，功能是都没问题的，就是最后会出现一个报错。麻烦大佬们看看，是啥问题呀。

**Comment by zxyao145** [comment]
@pookokok 

你好，提示对象引用为空，请问在 Form 进行提交验证的时候，有没有什么对象为空呢？

![image](https://user-images.githubusercontent.com/24973084/88258334-7e386b00-ccf2-11ea-8230-88c8697d9abc.png)

**Comment by pookokok** [comment]
更新到最新版本就正常了，多谢啦。。

**Comment by zxyao145** [comment]
@pookokok 好的，有问题请继续提issue。
