### ISSUE TITLE
[TreeSelect] Make it possible to prevent non leaf nodes to be selected

### ISSUE THREAD

**Issue by LuukGlorie** [ant-design-blazor/ant-design-blazor#4141]
### Describe the solution you'd like
Extra parameter on TreeSelect to either supply a predicate to determine if a node is selectable or a boolean to make non leaf nodes unable to be selected.

### Additional context
I used a workaround by deselecting a node if it wasn't a leaf node, but this work around doesn't work anymore.

**Comment by pankey888** [comment]
@LuukGlorie May be the node's `Checkable` is a good choice:
![image](https://github.com/user-attachments/assets/016718f9-46be-4588-aaea-9a2529fb2bf1)
