### ISSUE TITLE
0.20.3 Restricting many base classes with 'internal' limits makes it inconvenient to override components.

### ISSUE THREAD

**Issue by stfei** [ant-design-blazor/ant-design-blazor#4155]
0.20.3 Restricting many base classes with 'internal' limits makes it inconvenient to override components.
在0.20.3中用“internal”来限制基类方法会使重写组件变得不方便。

如:我在外部重新做了上传组件,逻辑继承了AntDomComponentBase,但是现在无法@ref="Ref",这个Ref被internal限制了.
另外:RangePicker.close() 也被限制了,诸如此类.

**Comment by ElderJames** [comment]
Thanks for contacting us @stfei 

We are considering expose the APIs of library, and if you have any requests you are welcome to ask. `Ref` can be replaced by `RefBack`, `Ref` is for internal use of the component, `RefBack` is provided for external reference.
