### ISSUE TITLE
Select duplicates classes

### ISSUE THREAD

**Issue by Velociraptor45** [ant-design-blazor/ant-design-blazor#4169]
### Describe the bug

When passing in class names via the `Class` property in a Select, the classes get duplicated in the HTML. This might not be a problem for general styling, but if you define padding/margin, this is an issue.

Here you can see two Selects (left & right) and a InputNumber (middle). All three have an mt-1 (=4px from top) margin, but because the classes for the Select get duplicated, the Selects basically have an mt-2 margin.
![grafik](https://github.com/user-attachments/assets/626907f8-f6a4-466b-8579-be5435532335)

### Steps to reproduce (please include code)
Create a Select, e.g.
![grafik](https://github.com/user-attachments/assets/40b459f8-a217-495c-a5fc-6826b3dd9a3b)

Check the generated HTML:
![grafik](https://github.com/user-attachments/assets/23e220af-d96a-4e8a-bf32-2a635a88faec)

### Further technical details
- AntDesign v0.20.3

**Comment by ElderJames** [comment]
Thanks for contacting us @Velociraptor45 , we will fix it later.
