### ISSUE TITLE
[Feature Request] Enable select and radio to support enumerated values

### ISSUE THREAD

**Issue by RisenJ** [ant-design-blazor/ant-design-blazor#417]

**Comment by ElderJames** [comment]
Thank you for contacting us @RisenJ .
This seems like an interesting and useful feature. We will add it after perfecting the basic features.

**Comment by ElderJames** [comment]
We have EnumSelect in 0.9.0 now. And the ratio group and checkbox group for enum are  on the way.

**Comment by dennisrahmen** [comment]
@ElderJames I don't know if it is a bug or just not a feature currently but the EnumSelect does support `Mode="multiple"` but I can't figure out how to get the selected values.
