### ISSUE TITLE
The OnSelectedItemsChanged event of the TreeSelect component has issues.

### ISSUE THREAD

**Issue by lyjcooi** [ant-design-blazor/ant-design-blazor#4198]
When I use this event in the TreeSelect component,
 it prompts an error:
 "Cannot convert from 'method group' to 'Microsoft.AspNetCore.Components.EventCallback'." 
 I encountered the same error message using the official example, and I haven't set the TItem property. The Select component works fine after setting the TItem property, but the TreeSelect does not have this property.

**Comment by lyjcooi** [comment]
Sorry, I tried again and it worked. I need to set both TItem and TItemValue together

**Comment by ElderJames** [comment]
Thanks for contacting us @lyjcooi , this is a well-known issue of blazor.
