### ISSUE TITLE
Modals/drawers are intermittently breaking page scrolling

### ISSUE THREAD

**Issue by jstafford5380** [ant-design-blazor/ant-design-blazor#4226]
### Describe the bug

It appears that modals are breaking page scrolling. If I have a page that is longer than my window height, I can scroll. If I open a modal and then close it, the page scroller goes away. Mouse wheel doesn't work and I can do a text pull select to force the scroll down. This problem persists if I navigate to other pages. I've observed this with modal windows and drawers. Refreshing the page typically resets everything to a working state. I have only tried this with the modal service because that's mostly what I use. I'm not sure if it happens when the modal markup is in the active view itself.

![modals-break-scrolling](https://github.com/user-attachments/assets/1a737656-63dd-4b7f-b05f-6e1ea3fa65d7)

Also this problem is intermittent. I experience it often, but it will also go away for a while and then come back. I do notice that with drawers specifically, probably 9 out of 10 times it happens, the page is shifted; it looks like the drawer didn't close all the way and wasn't destroyed.
![image](https://github.com/user-attachments/assets/09854825-812f-406f-b285-eb82e791b51d)

I wonder if maybe the css transitions between show/hide modal isn't switching reliably? I don't recall this happening a couple versions back but I can't downgrade to test without having to refactor a lot because of the recent breaking changes (changing things like int width to string width)

### Steps to reproduce (please include code)

1. Have a long page and confirm the page is scrolling up and down
2. Open a modal using a modal or drawer service.
3. Close the modal
4. Confirm the page is no longer scrollable

### Further technical details
- Blazor .NET 8, server-interactive
- AntDesign Nuget Package version 0.20.4.2
- Include the output of `dotnet --info`
- IDE N/A (happens both locally and when deployed)

**Comment by ElderJames** [comment]
Thanks for contacting us @jstafford5380 , please try the RC 1 version.
