### ISSUE TITLE
Set search input in Select manually in code

### ISSUE THREAD

**Issue by Velociraptor45** [ant-design-blazor/ant-design-blazor#4231]
### Is your feature request related to a problem? Please describe.
I need to manage the search input of a Select (Search enabled) in a variable outside the Select component (just like e.g. "Value" is able to set the value from outside).

### Describe the solution you'd like
I'd like to have a property (SearchInput) on the Select that sets the internal search input & executes the search if the new value is different from the old value (in case search is enabled).

If you're ok with that proposal, I'd try to implement it myself and create a PR?

**Comment by ElderJames** [comment]
Thanks for contacting us @Velociraptor45 , sure you can create a PR for this 😁.
