### ISSUE TITLE
当我使用“Ant Design Pro Blazor App 0.20.2.2” 模块创建一个wasm 项目并且进行调试时提示报错

### ISSUE THREAD

**Issue by wangfei9999** [ant-design-blazor/ant-design-blazor#4244]
![image](https://github.com/user-attachments/assets/a5caf9ca-d269-4131-a008-0291a6b9e727)

**Comment by ElderJames** [comment]
Thanks for contacting us @wangfei9999 , this is a bug of VS Preview and has no effect on functionality。
