### ISSUE TITLE
Mousedown on the modal content and mouseup on the mask will sometimes close the modal

### ISSUE THREAD

**Issue by chazikaifa** [ant-design-blazor/ant-design-blazor#4272]
### Describe the bug
When using `Modal` and set `MaskClosable`, mousedown on the modal content and then mouseup on the mask will sometimes close the modal.   

### Steps to reproduce (please include code)

**The problem will be easier reproduced on low-performance machine.**

All the `Modal` With `Form` can reproduce. So just use the code in  #3494.

### Exceptions (if any)
None

### Further technical details
- AntDesign Nuget Package version
 `0.20.4.2`
- Include the output of `dotnet --info`  
None.
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
`Rider 2024.2.6 `
- .Net
`8.0`

**Comment by ElderJames** [comment]
Thanks for contacting us @chazikaifa , would you please create a PR for this?

**Comment by chazikaifa** [comment]
> Thanks for contacting us @chazikaifa , would you please create a PR for this?

Due to the company's network security policy, I can NOT push code to GitHub in my office. In my home, however, pulling code from github without VPN usually fails. 😂 So, It's a little troublesome for me. 

I can try to pull codes on weekends, but if anyone of you can fixed it would be better.

**Comment by ElderJames** [comment]
Hello @chazikaifa , are you working on it?

**Comment by chazikaifa** [comment]
> Hello @chazikaifa , are you working on it?

Yes. the changes are simple. But I can not reproduce the problem in my home. So I'm not sure whether it's solved.

However, I'm too busy to verify today. I should be able to spare some time tmr.
