### ISSUE TITLE
Updating the order of the `TabPane` does not take effect

### ISSUE THREAD

**Issue by chazikaifa** [ant-design-blazor/ant-design-blazor#4280]
### Describe the bug
Updating the order of the `TabPane` does not take effect. Adding `Tabpane` will always append to the end of the list.

### Steps to reproduce (please include code)
We use `Tabs` as follows:
```
<Tabs>
    @foreach(item in itemList) {
        <TabPane @key="item.Id" Key="item.Id" Tab="item.Name">
            ...
        </TabPane>
    }
</Tabs>
``` 
We will update `itemList` including the order of the items. Although the title will update correctly, the order of the Tabs will not update. Besides, all the new items will be added to the end of the tab list.

For example, the `itemList`  is initialized as `[1,2,3,4,5]`. After some operations, it is updated to `[1,3,2,6,4,5]`. And what's actually rendered is `[1,2,3,4,5,6]`. 

### Exceptions (if any)
None.

### Further technical details
- AntDesign Nuget Package version
 `0.20.4.2`
- Include the output of `dotnet --info`  
None.
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
`Rider 2024.2.6 `
- .Net
`8.0`

**Comment by chazikaifa** [comment]
Our temporary solution is to force the `TabPane` rendered again when its order changed.

```
<Tabs>
    @{
        var count = 0;
        foreach(item in itemList) {
            count++;
            <TabPane @key="@($"{item.Id}-{count})" Key="item.Id" Tab="item.Name">
                ...
            </TabPane>
        }
    }
</Tabs>
```

However, the layout inside the `<TabPane>` will also be rendered again, which is unnecessary. What we want is to only update the order of the tabList.

**Comment by ElderJames** [comment]
Thanks for contacting us @chazikaifa , we have fixed this issue, please wait for next release in these days.

**Comment by ElderJames** [comment]
Hello @chazikaifa , please check out the 1.0 rc3.
