### ISSUE TITLE
[Feature Request] Make tree component support HTML

### ISSUE THREAD

**Issue by pookokok** [ant-design-blazor/ant-design-blazor#429]
Tree 树形控件，Text是否可以支持html格式，目前好像只能放string太单调了。

**Comment by ElderJames** [comment]
Thanks for contacting us @pookokok .
This is a good idea, we will support it in the next milestone.
You can also create a PR directly if you wish.

**Comment by kefengwei** [comment]
现在其实是可以在新建TreeNode的时候，直接赋值NodeTemplate，也是可以实现的。
