### ISSUE TITLE
When a Select component is bound to a dictionary, Will throw an exception

### ISSUE THREAD

**Issue by zl-aric** [ant-design-blazor/ant-design-blazor#4327]
### Describe the bug

When a Select component is bound to a dictionary, then delete more than one of the dictionary's keys, Will throw an exception : The object reference is null
**If only one key is deleted, it is normal**

### Steps to reproduce (please include code)

![3FII3P7(J1QX9IO5IG }1OA](https://github.com/user-attachments/assets/72be4d27-3fc7-4dab-bef0-954b8990a063)
![QEV{3%IH$GD%PBN963X_GFN](https://github.com/user-attachments/assets/ad519619-3e1a-4774-9038-f10deab71e91)

### Exceptions

![I (VK6EYUOG2}17UFY``2D](https://github.com/user-attachments/assets/da8e3cb1-bb1f-4a4d-b28b-155d957c73fc)

### Further technical details
- AntDesign : 1.0.0
- Include the output of `dotnet --info`
`.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e99c892e
 MSBuild version:   17.11.9+a69bbaaf5

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\`

**Comment by ElderJames** [comment]
Thanks for contacting us @zl-aric , please post your reproduce code here.

**Comment by ElderJames** [comment]
Hello @zl-aric , how did you solve the issue?
