### ISSUE TITLE
An exception occurred executing JS interop at AntDesign.Tabs.OnAfterRenderAsync

### ISSUE THREAD

**Issue by lamdieujdo** [ant-design-blazor/ant-design-blazor#4339]
I have been used AntDesign last version 1.0.1, but I saw this error:

[ERR] Unhandled exception in circuit '0MNwYGyd-fh483db0j8Qhj5uqY5rDFmoLtb8HJLXF4k'.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Decimal. Path: $.ant-blazor-5537b476-049a-463b-b2b8-aa9cfadf8f0b-nav-list.marginTop | LineNumber: 0 | BytePositionInLine: 315.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Decimal. Path: $.ant-blazor-5537b476-049a-463b-b2b8-aa9cfadf8f0b-nav-list.marginTop | LineNumber: 0 | BytePositionInLine: 315.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
   at AntDesign.Tabs.ResetSizes()
   at AntDesign.Tabs.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   
   Please help me a solution for it. Thanks!

**Comment by ElderJames** [comment]
Thanks for contacting us @lamdieujdo , could you please post your code here?

**Comment by lamdieujdo** [comment]
> Thanks for contacting us @lamdieujdo , could you please post your code here?

Thanks your reply, I can't pinpoint exactly where the error is coming from while integrating AntDesign.

**Comment by ElderJames** [comment]
How did you use the Tabs in your page?

**Comment by lamdieujdo** [comment]
> How did you use the Tabs in your page?

**Notice.razor page**
@inherits AntDomComponentBase

<TabPane Key="@TabKey" Tab="@($"{Title} {Data?.Count ?? 0}")">
    @if (Data == null || Data.Count <= 0)

    {
        <div class="notFound" style="min-width: 336px;">
            <img src="images/template/notice.svg" alt="not found" />
            <div>@EmptyText</div>
        </div>
        @if (IsAlwayShowViewMore)

        {
            <div class="bottomBar">
                <div @onclick="HandleViewMore">
                    @ViewMoreText
                </div>
            </div>
        }
    }

    else

    {
        <div style="min-width: 336px;">
            <AntList TItem="NoticeIconData"
                     Class="list"
                     DataSource="@Data"
                     ItemLayout="ListItemLayout.Horizontal">
                <ListItem OnClick="@(()=> HandleItemClick(context.Key))">
                    @if (string.IsNullOrEmpty(context.Avatar))

                    {
                        <ListItemMeta Avatar="" Description="@context.Description" Class="item">
                            <TitleTemplate>
                                <div class="title">
                                    @context.Title
                                    <div class="extra">@context.Extra</div>
                                </div>
                            </TitleTemplate>
                        </ListItemMeta>
                    }

                    else

                    {
                        <ListItemMeta Description="@context.Description" Class="item">
                            <AvatarTemplate>
                                <Avatar Class="avatar" Src="@context.Avatar" />
                            </AvatarTemplate>
                            <TitleTemplate>
                                <div class="title">
                                    @context.Title
                                    <div class="extra">@context.Extra</div>
                                </div>
                            </TitleTemplate>
                        </ListItemMeta>
                    }
                </ListItem>
            </AntList>
            <div class="bottomBar">
                @if (ShowClear)

                {
                    <div @onclick="HandleClear">
                        @ClearText 
                    </div>
                }

                @if (ShowViewMore || IsAlwayShowViewMore)

                {
                    <div @onclick="HandleViewMore">
                        @ViewMoreText
                    </div>
                }
            </div>
        </div>
    }
    </TabPane>
    
    **Notice.razor.cs**
    public partial class Notice : AntDomComponentBase
{
    private string _clearText;
    private string _viewMoreText;
    [Parameter] public string TabKey { get; set; }
    [Parameter] public string EmptyText { get; set; }
    [Parameter] public ICollection<NoticeIconData> Data { get; set; }
    [Parameter] public bool ShowClear { get; set; } = true;
    [Parameter] public bool ShowViewMore { get; set; }
    [Parameter] public bool IsAlwayShowViewMore { get; set; }
    [Parameter] public EventCallback OnClear { get; set; }
    [Parameter] public EventCallback OnViewMore { get; set; }
    [Parameter] public EventCallback<string> OnItemClick { get; set; }

    [Parameter] public string Title { get; set; }

    [CascadingParameter] public ItdNoticeIcon NoticeIcon { get; set; }

    [Parameter]
    public string ClearText
    {
        get => _clearText ?? NoticeIcon.ClearText ?? "";
        set => _clearText = value;
    }

    [Parameter]
    public string ViewMoreText
    {
        get => _viewMoreText ?? NoticeIcon.ViewMoreText ?? "";
        set => _viewMoreText = value;
    }

    public async Task HandleClear()
    {
        if (string.IsNullOrWhiteSpace(TabKey))
            return;

        if (OnClear.HasDelegate)
            await OnClear.InvokeAsync(TabKey);

        if (NoticeIcon.OnClear.HasDelegate) await NoticeIcon.OnClear.InvokeAsync(TabKey);
    }

    public async Task HandleViewMore()
    {
        if (string.IsNullOrWhiteSpace(TabKey))
            return;

        if (OnViewMore.HasDelegate)
            await OnViewMore.InvokeAsync(TabKey);

        if (NoticeIcon.OnViewMore.HasDelegate) await NoticeIcon.OnViewMore.InvokeAsync(TabKey);
    }

    public async Task HandleItemClick(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
            return;

        if (OnItemClick.HasDelegate)
        {
            await OnItemClick.InvokeAsync(key);
        }
    }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        SetClassMap();
    }

    protected void SetClassMap()
    {
        ClassMapper.Clear();
    }
}

**Comment by ElderJames** [comment]
Please don't use TabPane in your own components, and use it with the Tabs directly.

```
<Tabs>
  <TabPane>
    < Notice ></Notice>
  </TabPane>
</Tabs>
```

**Comment by lamdieujdo** [comment]
> Please don't use TabPane in your own components, and use it with the Tabs directly.
> 
> ```
> <Tabs>
>   <TabPane>
>     < Notice ></Notice>
>   </TabPane>
> </Tabs>
> ```

I used it (Tabs) but I got errors above 
@inherits AntDomComponentBase

<Dropdown 
    Placement="@Placement.BottomRight"
    OverlayClassName="container popover"
    Trigger="_trigger"
    Visible="Visible">
    <Overlay>
        <Tabs Class="tabs">
            <CascadingValue Value="this">
                @ChildContent
            </CascadingValue>
        </Tabs>
    </Overlay>
    <Unbound>
        <span @ref="@context.Current" class="@ClassMapper.Class">
            <Badge Count="Count" Style="box-shadow: none;" Class="badge">
                @if(NoticeType==ItdNoticeIconType.Transaction)
                {
                    <img src="images/template/car.png" class="responsive-img-noti-icon-page" />
                }
                else if(NoticeType==ItdNoticeIconType.DeviceMonitor)
                {
                    <img src="images/template/monitoring_64.png" class="responsive-img-noti-icon-page" />
                }
                else if(NoticeType==ItdNoticeIconType.Warning)
                {
                    <img src="images/template/bell_64_3.png" class="responsive-img-noti-icon-page" />
                }
                else 
                {
                    <img src="images/template/bell_64_3.png" class="responsive-img-noti-icon-page" />
                }                
            </Badge>
        </span>
    </Unbound>
</Dropdown>

With @ChildContent has TabPane

**Comment by lamdieujdo** [comment]
This is issue of line <TabPane Key="@TabKey" Tab="@($"{Title} {**Data?.Count** ?? 0}")">

Tab is string which it is not a string with number.
Ex: "Topic" vs "Topic 1" 

It's ok -> <TabPane Key="@TabKey" Tab="@($"{Title}")">
