### ISSUE TITLE
Export AntBlazor Table to CSV or Excel

### ISSUE THREAD

**Issue by zandiarash** [ant-design-blazor/ant-design-blazor#4362]
Is there a way to export AntBlazor Table to CSV or Excel file ?

**Comment by LeaFrock** [comment]
That's not the area of this library but the other specific libraries like CSVHelper(CSV) or ClosedXML(Excel). The table component might integrate such functionality(upon 3rd lib) one day in order to ease the usage, but now you can combine CSV/Excel libraries with it by yourself which won't take you much efforts.

Which mode are you using, Blazor Server or Blazor WASM? If you're using the latter, I can show you a code demo next week.

**Comment by LeaFrock** [comment]
The following is the guidance on Blazor WASM. Take the library `CsvHelper` which generates `.csv` files for example.

All you need to do is two steps: firstly convert your table rows to `Stream` in memory, then create a `<a>` tag dynamically and invoke a click event with a JS interop, which tells the browser to download the file in memory.

### Encapsulate JS interop

Add the [script from Microsoft Learn website](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads#download-from-a-stream) to your `index.html` body,

```js
<script>
  window.downloadFileFromStream = async (fileName, contentStreamReference) => {
    const arrayBuffer = await contentStreamReference.arrayBuffer();
    const blob = new Blob([arrayBuffer]);
    const url = URL.createObjectURL(blob);
    const anchorElement = document.createElement('a');
    anchorElement.href = url;
    anchorElement.download = fileName ?? '';
    anchorElement.click();
    anchorElement.remove();
    URL.revokeObjectURL(url);
  }
</script>
```

The JS script creates a temp `<a>` tag and click it to trigger a browser download action.

Then we can encapsulate it into csharp,

```csharp
        public static async Task<bool> ExportFromStreamAsync(this IJSRuntime js, Stream stream, string fullFilename)
        {
            try
            {
                using var streamRef = new DotNetStreamReference(stream);
                await js.InvokeVoidAsync("downloadFileFromStream", fullFilename, streamRef);
            }
            catch (Exception ex)
            {
                // Console.WriteLine(ex.Message);
                return false;
            }
            return true;
        }
```

### Encapsulate CSVHelper

Encapsulate a method which is based on `CSVHelper` APIs,

```csharp
        public static async Task<bool> ExportAsCsvAsync<TRow, TRowMap>(this IJSRuntime js, IEnumerable<TRow> rows, string filename)
            where TRowMap : ClassMap<TRow>
        {
            using var stream = new MemoryStream();
            using var sw = new StreamWriter(stream, Encoding.UTF8);
            using (var csv = new CsvWriter(sw, culture: CultureInfo.InvariantCulture, leaveOpen: true))
            {
                csv.Context.RegisterClassMap<TRowMap>();
                csv.WriteHeader<TRow>();
                csv.NextRecord();
                await csv.WriteRecordsAsync(rows);
            }
            stream.Seek(0, SeekOrigin.Begin);
            var result = await js.ExportFromStreamAsync(stream, $"{filename}.csv");
            return result;
        }
```

Therefore, we can use the method like,

```csharp

        private async Task ExportAsync()
        {
            var exported = await Js.ExportAsCsvAsync<MyRow, MyRowMap>(items, "demo");
            if (!exported)
            { 
                // Show a error message or log something wrong
            }
        }


        // See CSVHelper docs for details.
        public sealed class MyRowMap : ClassMap<MyRow>
        {
            public MyRowMap()
            {
                Map(m => m.Id).Index(0).Name("ID");
                Map(m => m.Name).Index(1).Name("XXX Name");
            }
        }
```

**Comment by LeaFrock** [comment]
If you want to export the table rows in memory, normally the count won't be very big so the above solution will work very well.

If you want to export the backend data or your client runs on a memory limited environment, you'd better generate the file on the backend.

If the your expected file will be very large, you should look for a backend solution and download it by (CDN) url.

**Comment by ElderJames** [comment]
Maybe ww can add a Api for table to expose the culumn names and rows.

**Comment by zandiarash** [comment]
I appreciate the time you spent with answering my question, absolutely I try your solution.
Thank you again.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zandiarash** [comment]
> The following is the guidance on Blazor WASM. Take the library `CsvHelper` which generates `.csv` files for example.
> 
> All you need to do is two steps: firstly convert your table rows to `Stream` in memory, then create a `<a>` tag dynamically and invoke a click event with a JS interop, which tells the browser to download the file in memory.
> 
> ### Encapsulate JS interop
> 
> Add the [script from Microsoft Learn website](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads#download-from-a-stream) to your `index.html` body,
> 
> ```js
> <script>
>   window.downloadFileFromStream = async (fileName, contentStreamReference) => {
>     const arrayBuffer = await contentStreamReference.arrayBuffer();
>     const blob = new Blob([arrayBuffer]);
>     const url = URL.createObjectURL(blob);
>     const anchorElement = document.createElement('a');
>     anchorElement.href = url;
>     anchorElement.download = fileName ?? '';
>     anchorElement.click();
>     anchorElement.remove();
>     URL.revokeObjectURL(url);
>   }
> </script>
> ```
> 
> The JS script creates a temp `<a>` tag and click it to trigger a browser download action.
> 
> Then we can encapsulate it into csharp,
> 
> ```csharp
>         public static async Task<bool> ExportFromStreamAsync(this IJSRuntime js, Stream stream, string fullFilename)
>         {
>             try
>             {
>                 using var streamRef = new DotNetStreamReference(stream);
>                 await js.InvokeVoidAsync("downloadFileFromStream", fullFilename, streamRef);
>             }
>             catch (Exception ex)
>             {
>                 // Console.WriteLine(ex.Message);
>                 return false;
>             }
>             return true;
>         }
> ```
> 
> ### Encapsulate CSVHelper
> 
> Encapsulate a method which is based on `CSVHelper` APIs,
> 
> ```csharp
>         public static async Task<bool> ExportAsCsvAsync<TRow, TRowMap>(this IJSRuntime js, IEnumerable<TRow> rows, string filename)
>             where TRowMap : ClassMap<TRow>
>         {
>             using var stream = new MemoryStream();
>             using var sw = new StreamWriter(stream, Encoding.UTF8);
>             using (var csv = new CsvWriter(sw, culture: CultureInfo.InvariantCulture, leaveOpen: true))
>             {
>                 csv.Context.RegisterClassMap<TRowMap>();
>                 csv.WriteHeader<TRow>();
>                 csv.NextRecord();
>                 await csv.WriteRecordsAsync(rows);
>             }
>             stream.Seek(0, SeekOrigin.Begin);
>             var result = await js.ExportFromStreamAsync(stream, $"{filename}.csv");
>             return result;
>         }
> ```
> 
> Therefore, we can use the method like,
> 
> ```csharp
> 
>         private async Task ExportAsync()
>         {
>             var exported = await Js.ExportAsCsvAsync<MyRow, MyRowMap>(items, "demo");
>             if (!exported)
>             { 
>                 // Show a error message or log something wrong
>             }
>         }
> 
> 
>         // See CSVHelper docs for details.
>         public sealed class MyRowMap : ClassMap<MyRow>
>         {
>             public MyRowMap()
>             {
>                 Map(m => m.Id).Index(0).Name("ID");
>                 Map(m => m.Name).Index(1).Name("XXX Name");
>             }
>         }
> ```

I appreciate the time you spent with answering my question, absolutely I try your solution.
Thank you again.

**Comment by LeaFrock** [comment]
> Maybe we can add a Api for table to expose the culumn names and rows.

Not bad. An appropriate abstraction which the community can provide a series of extending Nuget packages(`AntBlazor.TableExporter.CsvHelper`, `AntBlazor.TableExporter.ClosedXML` for examples) may be better. All our uses can build their own ecosystem and share them based on our components.

**Comment by LeaFrock** [comment]
@zandiarash It's nothing.  Remember to close the issue if your problem is solved.

**Comment by knox007** [comment]
Is there an export method suitable for the server mode? @LeaFrock

**Comment by LeaFrock** [comment]
@knox007 I don't use the server mode but I guess it is a little bit similar. The difference is that the file stream is generated from the server rather than the browser memory.

Just take a try. If you find a way, you can share it here.

**Comment by knox007** [comment]
Thank you. You're right. The operations of the two modes are similar. @LeaFrock
