### ISSUE TITLE
[sync 4.5.1] step progress

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#447]
https://ant.design/components/steps#components-steps-demo-progress

**Comment by Epictek** [comment]
Think you meant to link to https://ant.design/components/steps#components-steps-demo-progress

**Comment by ElderJames** [comment]
Thank you @Epictek 😊

**Comment by Epictek** [comment]
Have a working demo on my branch but need to clean up the commit a bit before making a PR, will do that tommorow https://github.com/Epictek/ant-design-blazor/commit/7836fe04434c83490af5409b16449f317ddad7d6

**Comment by ElderJames** [comment]
That's great, thanks a lot.

**Comment by ElderJames** [comment]
There is another issue with steps #331 , could you fix it by the way?
