### ISSUE TITLE
Button多点击几次OnClick的HasDelegate为false导致没有回调

### ISSUE THREAD

**Issue by srxqds** [ant-design-blazor/ant-design-blazor#453]
### Describe the bug
Button多点击几次OnClick的HasDelegate为false导致没有回调

### To Reproduce

代码其实很简单，就是在header放两个buton，然后来回点击，发现
<Layout>
            <Header>
                <Button><Icon Type="home" OnClick=@(args => OnNavItemClicked("/"))></Icon></Button>
                <Button Type="@ButtonType.Link" OnClick=@(args => OnNavItemClicked("/console"))>终端</Button>
                <section><span>Hello, @context.User.Identity.Name</span></section>
            </Header>
            <Content>@Body</Content>
        </Layout>
@code {
private void OnNavItemClicked(string link)
    {
        this.navigationManager.NavigateTo(link);
    }
}

回调会不正确，我打印了HasDelegate返回false
![image](https://user-images.githubusercontent.com/5187024/89154381-5a4e1280-d599-11ea-9d63-49413325a67f.png)

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by lindexi** [comment]
好像没复现，求 demo 项目，我觉得我没理解你的意思

**Comment by ElderJames** [comment]
你好 @srxqds ，请尝试不调用跳转，看看还会不会发生。

**Comment by srxqds** [comment]
应该是aspcore的bug?
我先关闭吧，我没用这个了

**Comment by ElderJames** [comment]
@srxqds 那用了哪个？

**Comment by srxqds** [comment]
> @srxqds 那用了哪个？

用Menu了，请教下，你们有计划实现拖拽对话框吗？

**Comment by ElderJames** [comment]
可以考虑，请另外提个issue吧！
