### ISSUE TITLE
Layout的Sider中使用的Menu有SubMenu时会与Sider的OnCollapse事件冲突

### ISSUE THREAD

**Issue by qq23771284** [ant-design-blazor/ant-design-blazor#475]
### Layout的Sider中使用的Menu有SubMenu时会与Sider的OnCollapse事件冲突
[MainLayout.txt](https://github.com/ant-design-blazor/ant-design-blazor/files/5045107/MainLayout.txt)
[Error.txt](https://github.com/ant-design-blazor/ant-design-blazor/files/5045108/Error.txt)

**Comment by ElderJames** [comment]
你好 @qq23771284 ，感谢反馈，已经修复，请更新到最新的nightly版本。
