### ISSUE TITLE
Row 组件在 server端报错

### ISSUE THREAD

**Issue by ibcla** [ant-design-blazor/ant-design-blazor#500]
ant-design版本:0.2.0
`
<AntDesign.Row >
            <AntDesign.Col >
            </AntDesign.Col>
        </AntDesign.Row>
`
报错信息:
InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

**Comment by ElderJames** [comment]
Thank you for contacting us @ibcla 
We are going to work on this issue. Please trace another issue #181 .
