### ISSUE TITLE
Buttons working when used with style float

### ISSUE THREAD

**Issue by momentum-tunis** [ant-design-blazor/ant-design-blazor#511]
I'm unable to click on a button (and it loses the hover effect) if it has a float css style.

To Reproduce:
<style type="text/css">
    .add-button {
        float: right;
    }
</style>

    <Button Type="primary" OnClick="OnAdd" class="add-button">
        Add
    </Button>

- AntDesign Nuget Package version: 0.3.0-nightly-2008131541

**Comment by ElderJames** [comment]
Thank you for contacting us @momentum-tunis ,
But it works well in document project.
![image](https://user-images.githubusercontent.com/7550366/90408025-d6884000-e0d9-11ea-8bcb-675bff30a39a.png)

**Comment by momentum-tunis** [comment]
Hi, I just figured out that the problem is because I have a data table following the button, I think it is just some z-index issue.

The exact code to reproduce is:

<style>
    .add-button {
        float: right;
    }
</style>

<Button Type="primary" OnClick="() => i++" class="add-button">
    Add @i
</Button>
<Table DataSource="@testSource">
    <Column @bind-Field="@context.A"   />
</Table>

@code {
    public class Model { public int A;  }
    public List<Model> testSource;
}

Now I just used a parent container for the button with left alignment style (instead of floating) and it is working fine.

Thanks a lot.

Mehdi
