### ISSUE TITLE
Adapted grid

### ISSUE THREAD

**Issue by hw72869951** [ant-design-blazor/ant-design-blazor#521]
我要用删格在一行里面平均分为两列，并且要铺满整个屏幕，我每个里面就写了个span=12,当缩放屏幕的时候发现是两列，但是并没有铺满屏幕，没法自适应

What I want is two columns in one row with same width and this row uses the full width of screen. So I added `span=12`, but when I  scaling the screen, there are two columns still which is right, but this row couldn't use the full width of screen.

**Comment by ElderJames** [comment]
Hi, @hw72869951 , 
I cannot reproduce, please provide the code.
