### ISSUE TITLE
说明文档错误

### ISSUE THREAD

**Issue by wayneowang** [ant-design-blazor/ant-design-blazor#531]
code页下面说明文档中：
在 wwwroot/index.html(WebAssembly) 或 Pages/_Host.razor(Server) 中引入静态文件:
这句话有错误，微软建的项目没有_Host.razor文件,只有_Host.cshtml文件

**Comment by ElderJames** [comment]
Thank you for the mistake you raised with us @wayneowang ,

You just feel free to create a PR to fix it if you like.
