### ISSUE TITLE
[Transfer]UI couldn't refresh after changing data source

### ISSUE THREAD

**Issue by 136888** [ant-design-blazor/ant-design-blazor#534]
### Describe the bug

![图片](https://user-images.githubusercontent.com/23148983/91277893-09a39100-e7b6-11ea-968e-c9352e38783e.png)
![图片](https://user-images.githubusercontent.com/23148983/91277922-10320880-e7b6-11ea-9569-d04a54d27265.png)

第一次绑定数据时正常

当我重新绑定数据的时候

发现datasource已经改变了，但是穿梭框里面的显示的值却没有改变，依然是第一次的结果

It works fine when I first binding data, but after I change the data source, the content won't change.

**Comment by 904617726** [comment]
修复好慢啊

**Comment by ElderJames** [comment]
@904617726 Feel free to contribution. 😉

**Comment by YingXiaoMing** [comment]
0.8版本这个问题还是存在
