### ISSUE TITLE
Statistics 控件计算整数的Bug

### ISSUE THREAD

**Issue by charset** [ant-design-blazor/ant-design-blazor#536]
### Describe the bug 描述这个八阿哥
Sometime when Value less than 1, the Integer Part will be 1, but remain Fractional Part no change.
当Value值小于1的时候，有时候会在整数部分计算为1，但是小数部分还是不变。

### To Reproduce 再现

> ant-design-blazor/components/statistic/Statistic.razor.cs
Line 20, to calculate the Integer Part.
第20行，计算整数部分使用的
```csharp
Convert.ToDecimal(Value).ToString($"###{GroupSeparator}###");
```
when Value >= 0.5 && Value < 1, the Integer Part will be 1;
when Value >=0 && Value < 0.5, the Integer Part will be empty.
当Value小于1而大于等于0.5时，整数部分计算为1，大于0而小于0.5时，整数部分计算为空。

### Exceptions (if any) 例外（如果有）
没有。//None

### Further technical details 更多技术细节
环境是Dotnetcore 3.1.401，IDE为VS 2019 社区版。
Using ,netcore 3.1.401, VS 2019 Community Edition.

**Comment by charset** [comment]
```csharp
Math.Floor(Convert.ToDecimal(Value)).ToString($"###{GroupSeparator}###");
```
should be ok.

**Comment by ElderJames** [comment]
Thank you @charset ,

I have fixed it via #538 , please try again.
