### ISSUE TITLE
有demo项目的源码嘛

### ISSUE THREAD

**Issue by 188867052** [ant-design-blazor/ant-design-blazor#541]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by ElderJames** [comment]
你好，不知道你是指哪个demo？
文档里的都有源码

**Comment by 188867052** [comment]
就是类似于
https://github.com/ant-design-blazor/ant-design-blazor/issues/335
这里面项目的源码，一个demo就行，想看看使用中有没有什么问题，可以的话就采用这个

**Comment by ElderJames** [comment]
这个issue 是其他用户的项目，可以看看有没有开源的。
我们还做了Ant Design Pro模板，虽然还没完成，但是可以直接使用。

**Comment by 188867052** [comment]
好的 多谢 我看看

**Comment by 188867052** [comment]
你好我看AntDesign.Pro项目编译的时候还需要运行npm，能解除对npm的依赖嘛

**Comment by ElderJames** [comment]
以来npm主要有两个原因：
1. Pro中less文件依赖 ant design 的less文件（引用了变量），所以要安装antd的源码包。
2. less的编译，目前windows上可以用WebCompiler，但需要把源码包下载下来。

解决方案可能是把组件库中的less文件打包到nuget包中，并使用WebCompiler编译。
如果你可以帮忙解决，欢迎PR！
