### ISSUE TITLE
Error occurs while handling business logic and without changing model in OnChange event of Cascader element

### ISSUE THREAD

**Issue by Seanxwy** [ant-design-blazor/ant-design-blazor#555]
Cascader 组件 OnChange事件。
OnChange event of Cascader element.

```     
private void OnSearchRegionChange(List<CascaderNode> keys, string key, string label)
    {
        text = Newtonsoft.Json.JsonConvert.SerializeObject(keys);
        //regionText = Newtonsoft.Json.JsonConvert.SerializeObject(regionNodes.ToArray());
        var code = key.ToInt();
        var c = Regions.SingleOrDefault(p => p.Code == code);
        //var a = Regions.Where(p => p.Code == c.ParentCode).SingleOrDefault();

        //var b = Regions.Where(p => p.Code == a.ParentCode).SingleOrDefault();


        areaText =$"{c.Name}-{c.Code}" +  Newtonsoft.Json.JsonConvert.SerializeObject(c);


    }
```

如果把代码修改成 areaText =Newtonsoft.Json.JsonConvert.SerializeObject(c); 就能正常运行。否则就报错。
Error occurs, but it could work properly if I modify the code to `areaText =Newtonsoft.Json.JsonConvert.SerializeObject(c);`.

错误提示
Stack trace

01T02:58:30.061Z] Error: System.InvalidOperationException: Unable to set property 'Value' on object of type 'AntDesign.Cascader'. The error was: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

本代码示例是地区数据。还会出现选择第二级数据后，只展示第一级和第三级数据，第二级不见了。选择第三级数据后，组件框内，只显示最后一级数据，而不是文档中完整路径。
It's area data in the code I provided.
And also another issue after selecting second value, it will lose only left the first and third value; after selecting third value, only the third value can be shown instead of the full path which is different with official document.

**Comment by ElderJames** [comment]
@Seanxwy 最新版还有这个问题吗？

**Comment by ElderJames** [comment]
请提供可重现的代码，由于太久远，先关闭这个issue了。
