### ISSUE TITLE
使用Carousel组件导致浏览器撑爆了

### ISSUE THREAD

**Issue by BigHeadDev** [ant-design-blazor/ant-design-blazor#556]
### Describe the bug
Carousel组件会把浏览器页面扩充至无限大，影响其他内容的显示。
走马灯组件对于主页网站显示比较重要，希望得知修复计划的时间节点。
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
请提供一下重现代码

**Comment by ElderJames** [comment]
Hi @BigHeadDev ,

Please update to the last nightly version and try again. 

Thank you!
