### ISSUE TITLE
[select] AllowClear option only clear content not value

### ISSUE THREAD

**Issue by Yuanxw612** [ant-design-blazor/ant-design-blazor#557]
[select] 设置 AllowClear 只清除了内容，没有清除值。正确的效果应该是清除显示的内容，以及对应的对象值。

For [Select] control, `AllowClear` only clears the content but the value is still there. The correct result is to clear both the content and the value of the object.

**Comment by yuanxiongwei** [comment]
经过反复研究发现allowclear 是可以清空值，但是 @bind-value无效，需要在onchange 中进行处理。
