### ISSUE TITLE
Table/Column/Formatter getting strange display between win-iis and linux

### ISSUE THREAD

**Issue by charset** [ant-design-blazor/ant-design-blazor#571]
### Describe the bug 形容这个八阿哥
when float value displays in table/column, I add ```<Column @bind-Field="@context.someValue" Format="N02"></Column>``` in a ```<Table>```.
It works perfect when debugging in IIS on windows, but strange things happen when I publish to a linux environment.
The table column displays as Format Value. e.g. when ```someValue = 1.32111F```, on windows, it displays '1.32', but just 'N02' in publishing linux environment.
当我需要在一个表格的列中使用Format来展现一个浮点数（float）的时候，我用N02。在windows里面的IIS调试情况下，工作的很好；但是我把他将发布在我的Linux Server服务器上的时候，比如1.32111F这个浮点数，会变成N02在表单里面。

### To Reproduce
I checked ant-design-blazor source file. ```Formatter<float>```.Format works fine in both windows and linux.
I guess when ```Formatter<string>``` will display as 'N02' (just formmat value).
But I did sure ```@context.someValue``` **IS** float.
我将adb的源码中Formatter<T>的方法Format测试过，在两个环境中均可得到正确的结果。
我猜想，当```Formatter<string>```的情况下才会出现上述现象。但是我确保这个值是float类型的。

### Exceptions (if any)
None.

### Further technical details
- AntDesign Nuget Package version = latest.
- Include the output of `dotnet --info` 3.1.302 (linux) 3.1.401 (windows)
- VS Community 2019 letest.

**Comment by ElderJames** [comment]
Thank you for your feedback @charset ,
You just feel free to create a PR to help us to fix it. 😉

非常感觉你的反馈，你可以创建一个PR来帮我们修复它。

**Comment by diegofrata** [comment]
@charset It does not look like it's a AntDesign bug on a first look. Could you try the format "N2" instead of "N02"?

**Comment by charset** [comment]
> @charset It does not look like it's a AntDesign bug on a first look. Could you try the format "N2" instead of "N02"?

I tried N,N2,#.00 etc. it works fine in debug mode but when published it just displayed as Format code.

**Comment by ElderJames** [comment]
Hi @changfeng1800 , did you use blazor server?

**Comment by ElderJames** [comment]
Hi @changfeng1800 , 
I've added some tests. Please give us more information.
