### ISSUE TITLE
Tag demo elements losing while deleting

### ISSUE THREAD

**Issue by Seanxwy** [ant-design-blazor/ant-design-blazor#574]
当动态循环输出多个标签后，随意删除标签，会出现标签丢失。文档中心可以很容易重新该问题。
数据没有问题，只是标签少了。如果替换成其他标签来循环展示，如果 button就完全没有问题。

Tag elements lost after deleting, nothing wrong with the data, only tags.
It can be Reproduced on official document.
This issue won't occur with other elements like Button.

**Comment by ElderJames** [comment]
请问是哪个demo？
