### ISSUE TITLE
Table sorting is broken

### ISSUE THREAD

**Issue by diegofrata** [ant-design-blazor/ant-design-blazor#585]
### Describe the bug
Sorting by clicking on a Sortable column is broken. 

### To Reproduce
Clicking changes the icons but does not sort the data, cna be reproduced from the docs project.

### Further technical details
- AntDesign Nuget Package version 0.3.0-nightly-2009090339

**Comment by ElderJames** [comment]
Hi, @diegofrata 
You can try the last build, I have fixed it via #582 .

**Comment by diegofrata** [comment]
Weird! I had just tested it and it didn't work. I think I needed to hard refresh.
