### ISSUE TITLE
changes introduced in 0.3.0-nightly-2009091418 to select component produce 15sec long init for select with 150 options (big data :-) )

### ISSUE THREAD

**Issue by vaderr12** [ant-design-blazor/ant-design-blazor#594]
### Describe the bug
Hi,
My code makes some async calls inside OnParametersSetAsync of my component showing modal dialog.
When I updated to newest 0.4.0-nightly-2009110751 I discovered that page is unresposive for more than 30 seconds, and then dialog refresh.
Edge performance tabs shows that "timer fired" intiated by _schedule_background_exec@dotnet.3.2.0.js:1 took for example 34.05s

When I'm using packages older than 0.3.0-nightly-2009091418, page is refreshed after short time.

### To Reproduce
Update AntDesign to package 0.3.0-nightly-2009091418 or newer

### Further technical details
- AntDesign 0.3.0-nightly-2009091418 or newer

**Comment by Epictek** [comment]
Could you include some code to help reproduce?

**Comment by vaderr12** [comment]
ok, I've narrowed the issue: the **select** component.
My dialog has 2 selects, about 150 options each. Changes to select introduced in 0.3.0-nightly-2009091418 caused 15 seconds stall for every select.
Bellow is small test, which show serious performance degradation after 0.3.0-nightly-2009091418 update.
```
@page "/SelectTest"
<AntDesign.Select Style="min-width:200px" Options=@options />
@code {
	AntDesign.LabeledValue[] options;
	protected override void OnInitialized()
	{
		const int arraySize = 150;
		options = new AntDesign.LabeledValue[arraySize];
		foreach(var i in Enumerable.Range(0, arraySize))
		{
			options[i] = new AntDesign.LabeledValue(i.ToString(), i);
		}
	}
}

```

**Comment by vaderr12** [comment]
hi, do you plan to work on my issue, or is this no fix?

**Comment by flamecrow** [comment]
> hi, do you plan to work on my issue, or is this no fix?

@vaderr12 Have you found a workaround for this?

**Comment by ElderJames** [comment]
Please try the new select in 0.5.x

**Comment by vaderr12** [comment]
hey, 0.5 works much faster, thanks!!!

**Comment by ElderJames** [comment]
It's 0.7 now 😀
