### ISSUE TITLE
Drawer: Handling Cancel event broken in update 0.3

### ISSUE THREAD

**Issue by momentum-tunis** [ant-design-blazor/ant-design-blazor#597]
The cancelling of the drawer is not working in the the last stable version 0.3 which include the merge of the OnClose and OnCancel events.

If you try with Drawer demo, "Use Component" button, you will find that there is no "Close Drawer" text in the console when you use the X button to close the drawer, or if you click on the mask area. It was working well in version 0.2 with the OnCancel event defined in the options

**Comment by zxyao145** [comment]
@momentum-tunis 
Yes, I know the problem. When using DrawerService, the OnClose event is triggered only when the DrawerRef is called to close the drawer. 

I'm working on how to fix it, but I'm sorry I didn't have enough time to do it this month, it may wait until October. If you are interested, you are welcome to repair it. 

Thanks a lot!

**Comment by yuanxiongwei** [comment]
add Opened Event

**Comment by momentum-tunis** [comment]
Thanks @zxyao145. I can help to fix some issues when I will have time. I did a quick look in the code and I didn't see anything wrong, so it will need some debugging. My workaround to bypass this is to add a callback funtion in the parameters that I send to the drawer component and to call it when I need to update things.

**Comment by zxyao145** [comment]
Thanks @momentum-tunis , there are two versions of DrawerRef, one is normal and the other is generic, each of them has its own CloseAsync function, maybe merging two OnClose is a better choice.
