### ISSUE TITLE
Drawer open / close animation is not reversible.

### ISSUE THREAD

**Issue by random-yang** [ant-design-blazor/ant-design-blazor#60]
The **drawer component's** open and close animation is not reversible. Especially close animation.

link: https://ant-design-blazor.gitee.io/zh-CN/drawer

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/25839518/77987854-82a8d480-734d-11ea-8c1c-d109877263c4.png">

**Comment by ElderJames** [comment]
Thank you for contacting us.

This problem was recognized during development. But at the moment Blazor is not good enough at animation. We need to deal with it in the following time.

We would appreciate it if you could submit PR to help

**Comment by ElderJames** [comment]
We have fixed it #177 .
