### ISSUE TITLE
Bordered Does Not Work On Card

### ISSUE THREAD

**Issue by Spottigus** [ant-design-blazor/ant-design-blazor#600]
```
    <Card Style="width:300px;" Bordered Cover="coverTemplate" Actions="new[] { actionSetting, actionEdit, actionEllipsis }">
        <CardMeta Avatar="avatarTemplate">
            <Title>Meta Card</Title>
            <Description>This is the description</Description>
        </CardMeta>
    </Card>
```

Does not result in a bordered card.

When looking at https://ant-design-blazor.github.io/ on both Chrome and Edge, the card example is not bordered as well. Tried clearing all chache and  reloading.

![image](https://user-images.githubusercontent.com/71304298/93160825-cf535280-f6d6-11ea-84c4-e944d8707193.png)

**Comment by ElderJames** [comment]
Thank you for contacting us @Spottigus .

The border in your screenshot is normal. And the following is no border:

![image](https://user-images.githubusercontent.com/7550366/93162641-c2227c00-f747-11ea-95d6-cce471db27d5.png)

But I should mack Bordered property default to `true` for following the ant design offical.

**Comment by Spottigus** [comment]
@ElderJames thanks for the quick response. I think this was a resolution / screen issue on my end. After changing resolution, the border seems to have re-appeared. I can no longer replicate.
