### ISSUE TITLE
[antlist] The layout seems wrong after updating to version 17

### ISSUE THREAD

**Issue by Seanxwy** [ant-design-blazor/ant-design-blazor#616]
[antlist] 更新17版本后 排版错乱了
在 listitem中的多个row不生效了。全部都变成一行了。

The multiple rows of the listitem now are placed in one row after updating v17.

**Comment by Yuanxw612** [comment]
使用listitem noflex属性可以暂时搞定

**Comment by ElderJames** [comment]
现在还有问题吗？
