### ISSUE TITLE
[select, autocomplete] There is a catton in use, click Invalid bug

### ISSUE THREAD

**Issue by Yuanxw612** [ant-design-blazor/ant-design-blazor#631]
select 点击展开option 会卡顿，选中后也会卡住，不会自动隐藏 ，需要点击其他地方，或者等待比较长的时间才会因此关闭。
autocomplete 选项无法正常点击，不论内容长短，点击选项文本或者内容行空白，经常出现异常无法选中，点击A不行，点击其他的又可以。点击不行的这个选项反复操作点击都不行，但是等待一会再来选中，又可以点击上。

select 和autocomplete选项反应比较迟缓，容易卡顿或者卡住。

以上情况是page 中 foreach循环中使用出现的。不太清楚modal 弹层中是否也有这种情况。

**Comment by TimChen44** [comment]
已于 #647 进行修复
