### ISSUE TITLE
Setting a status of a badge wrapping an avatar causes multiple badges to render

### ISSUE THREAD

**Issue by Epictek** [ant-design-blazor/ant-design-blazor#640]
### Describe the bug

Setting status of badge whilst it wraps an avatar causes multiple badges to be rendered

![Screenshot from 2020-09-22 10-08-14](https://user-images.githubusercontent.com/1466270/93863705-bdb41100-fcbb-11ea-8401-b3c4145d2c05.png)

### Steps to reproduce (please include code)
```
        <Badge Dot Status="warning">
            <Avatar Size="50" Shape="square" src="https://placekitten.com/200/200"/>
        </Badge>
```

### Further technical details
- AntDesign Nuget Package version:  0.4.0-nightly-2009220233

**Comment by ElderJames** [comment]
Thank you @Epictek , I'll fix it later.
