### ISSUE TITLE
Transfer Search Placeholder is hardcoded

### ISSUE THREAD

**Issue by dansiegel** [ant-design-blazor/ant-design-blazor#645]
### Describe the bug

When enabling the Search on the Transfer component, the search placeholder is hardcoded `请输入搜索内容`. This really should be null or an empty string by default, and there should be parameter to set the placeholder value of the search input.

### Steps to reproduce (please include code)

```xml
<Transfer ShowSearch="true"></Transfer>
```

You can also see this in the docs site where the transfer is shown with a search box. 

![image](https://user-images.githubusercontent.com/3860573/94097231-fac2f500-fdda-11ea-84ad-cfa8443cfb91.png)

### Exceptions (if any)

none

### Further technical details
- AntDesign Nuget Package version: latest 0.4.0-nightly
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thanks for reporting @dansiegel ,
I wil add the localization for transfer later.

**Comment by dansiegel** [comment]
@ElderJames there are actually a few issues with the Transfer component. If you want I can open issues for each or we can just add them here... 

- No space between items and the title
- Not sure if there's a way to actually customize the column text so it would just say `0 {left column title}` and `1 {right column title}` instead of forcing you to see `0 items {left column title}` and `1 items {right column title}`
- When no elements are in either the left or right column the No Data text is duplicated and there is a broken image asset.

![image](https://user-images.githubusercontent.com/3860573/94098570-c13fb900-fddd-11ea-9462-95f8e6712f55.png)

**Comment by ElDiddi** [comment]
Hello everyone,

at the moment I am fixing some bugs in this module. I will send a pull request this evening in which the above mentioned bugs are fixed.
