### ISSUE TITLE
Slider not working on the Components Libraries

### ISSUE THREAD

**Issue by MarioGK** [ant-design-blazor/ant-design-blazor#646]
### Describe the bug
The slider is not sliding in [official component library](https://ant-design-blazor.github.io/en-US/components/slider)

### Steps to reproduce (please include code)
Just go to https://ant-design-blazor.github.io/en-US/components/slider and try sliding any of them.
[Video](https://streamable.com/bdujno)

### Exceptions (if any)
Nothing on the console.

### Further technical details
- Google Chrome 85.0.4183.12

**Comment by Epictek** [comment]
Also have this issue with wasm locally as well, can anyone confirm if they work with Server blazor?

**Comment by ElderJames** [comment]
Thank you for feedback @MarioGK ,
@Brian-Ding will fix it.
