### ISSUE TITLE
input control utf8 data binding bug

### ISSUE THREAD

**Issue by libu1129** [ant-design-blazor/ant-design-blazor#667]
### Describe the bug
Entering UTF8 characters in the AntDesign.Input control (Korean)
Data binding works if the Input control loses focus, but data binding does not work if you move on to other actions, such as clicking a button immediately after writing a character.

I take measures

<Input TValue="string" @bind-Value="@FilterText" style="width:120px;" OnInput="@(p => FilterText = p.Value?.ToString())" />

I am using it by solving that problem in a way.

### Further technical details
nuget 0.3.0

**Comment by ElderJames** [comment]
Thank you for cantacting us @libu1129 .

Could you please update the nuget package to 0.4.1 or later?  Maybe we have fixed it.
