### ISSUE TITLE
Improve perfomance of loading icons

### ISSUE THREAD

**Issue by Epictek** [ant-design-blazor/ant-design-blazor#668]
The current implementation of the Icons requires uses HttpClient to retrieve the icons when requested, this makes the icons slow to load compared to other assets on the page.

I would propose bundling the icon svgs as individual components using a gulp file similar to the ant-design icons repos.

This would increase the bundle size but with [compression](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#compression) shouldn't be a big deal. initial testing I got it down to 116kb which is pretty good considering there a JS date libaries bigger than that... and with some linker magic it might be possible to make it smaller?

![](https://user-images.githubusercontent.com/1466270/95122283-2b464f80-0748-11eb-80b1-628748577ad1.png)

**Comment by ElderJames** [comment]
It seems to make sense, and we can try it later. Thanks for the researching, @Epictek .

**Comment by gabrielfreire** [comment]
Icon loading is terribly slow indeed

**Comment by zxyao145** [comment]
Can some commonly used icons be written directly into the Blazor as string, instead of being loaded through Ajax?
