### ISSUE TITLE
Ability to create Modal component from code

### ISSUE THREAD

**Issue by Epictek** [ant-design-blazor/ant-design-blazor#669]
We are creating Modal with code using the templated components (ModalService.CreateAsync) but there is no way to set a custom footer or other options for the modal.

**Comment by zxyao145** [comment]
`ModalService.CreateAsync` method is only suitable for creating Confirm dialog. Confirm dialog does not support setting footers, which is consistent with Ant Design of React. If you want to use a dialog with a footer, please use the modal component. 

Thanks very much!

**Comment by zxyao145** [comment]
@Epictek I'm very sorry that it's not supported to display a Modal dialog component from code similar to `ModalService.CreateAsync`. 

To be consistent with the official usages of andt, I also use the name `ModalService` here, which may bring you some confusion. 

Maybe adding a new method to the modal service, such as `ModalService.CreateModalAsync`, is an optional solution.

**Comment by Epictek** [comment]
https://github.com/Blazored/Modal seems to be close to what I need, guess I'll use it until this libary has something close to it

**Comment by TimChen44** [comment]
@Epictek 
His usage is similar to our Drawer component, but he has made some optimizations on the parameters and feedback values. Our usage code is as follows
```
        var options = new DrawerOptions()
        {
            Title = "Component",
            Width = 350,
        };

        var result = await DrawerService.CreateDialogAsync<DrawerTemplateDemo, string, string>(options, value);

        if (result != null)
         {
               //do some thing
         }
```
Is this the effect you want to achieve?

**Comment by Epictek** [comment]
Yeah having a similar API for modals would be perfect, only makes sense if the drawer component already has such API
