### ISSUE TITLE
AntDesign Blazor WASM 3.2 Missing Pages

### ISSUE THREAD

**Issue by svrebelo001** [ant-design-blazor/ant-design-blazor#670]
Hello!

I'm new to AntDesign and I was trying to create the template with the full pages.

When I start my project it shows like this:

![image](https://user-images.githubusercontent.com/64233891/95148776-072f4200-0739-11eb-8353-a75686f4545b.png)

I don't have the pages that are related to the header / side Menu.

What am I missing?

Thanks in advance

**Comment by ElderJames** [comment]
Thank for contacting us @svrebelo001 .
If you create the templated project with full pages, the pages is in the `Pages` directory.

**Comment by ElderJames** [comment]
The `Layout` component what you said ` header / side Menu` is from another project named `pro-layout`, and was used in the [`BasicLayout`](https://github.com/ant-design-blazor/ant-design-pro-blazor/blob/master/src/AntDesign.Pro/Layouts/BasicLayout.razor#L2).

**Comment by svrebelo001** [comment]
Thank you @ElderJames . I'll check this

Have a great week!

**Comment by svrebelo001** [comment]
@ElderJames I forgot to ask. Is it normal to have the page like this? In chinese characters and english? I've noticed the locale change but it's not working
