### ISSUE TITLE
Table selectedRows item on table clean when back previous page.

### ISSUE THREAD

**Issue by nhathuynh77** [ant-design-blazor/ant-design-blazor#671]
### Describe the bug
![image](https://user-images.githubusercontent.com/10446177/95159834-41e0bb00-07c9-11eb-8d69-b13c6df84881.png)
![image](https://user-images.githubusercontent.com/10446177/95159877-5d4bc600-07c9-11eb-8e00-5c89faff2ebb.png)
![image](https://user-images.githubusercontent.com/10446177/95159925-78b6d100-07c9-11eb-8e00-eb53196469c1.png)

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Thank you for contacting us @nhathuynh77 .
Did you set the `Key` parameter for the `<Selection >` ? 
Like ` <Selection Key="@(context.Id.ToString())" />`.
