### ISSUE TITLE
关于 select 的问题

### ISSUE THREAD

**Issue by lyjcooi** [ant-design-blazor/ant-design-blazor#695]
我在使用 select 组件的时候，我把官方文档的里面的代码复制上去，放在页面中，项目启动起来的时候就会提示“JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.” 异常，我想知道这是什么原因

**Comment by mutouzdl** [comment]
@ElderJames render-mode改为ServerPrerendered后，还是没法重现

`    <app>
        <component type="typeof(App)" render-mode="ServerPrerendered" />
    </app>
`
