### ISSUE TITLE
Modal box randomly closed when multiple mouse click performed within it

### ISSUE THREAD

**Issue by JitenPatoliya** [ant-design-blazor/ant-design-blazor#696]
I am using modal box with few controls in it for entering values by user.
But when I double click (Or more frequent mouse clicks) on Input ( Randomly happens on Cascader/DatePicker etc...) it closes it self.

I investigated further and found mouse clicks triggers cancel event with argument cominag as null (this should not be triggered)
`private void HandleCancel(MouseEventArgs e) // -----  value of e is coming null
{
  Console.WriteLine(e);
  _visible = false;
}`

This can be experienced on 
https://ant-design-blazor.github.io/en-US/components/modal 

Open Modal "Other components"
Randomly perform frequent mouse click on DatePicker ( try couple of times by closing and reopening modal )

### Further technical details
- AntDesign Nuget Package version - Link is in the description
- Include the output of `dotnet --info` - NA
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - NA

**Comment by zxyao145** [comment]
@JitenPatoliya Thanks a lot!

If you click too fast - twice or more times in 50ms, this problem will indeed occur. This is a defect in my design and I will try to find some better solutions to solve it.
