### ISSUE TITLE
Select on Modal with Form not working

### ISSUE THREAD

**Issue by JitenPatoliya** [ant-design-blazor/ant-design-blazor#698]
I have a Modal with Form and multiple Input
When I tried to add module: Select as one of the control its not working as expected (Not getting Drodown values (select options).

### Code that Reproduce issue - Start ####

<Button Type="primary" OnClick="@(()=>{ _visible = true; })">
    Open Modal
</Button>
<Modal Title="@title"
       Visible="@_visible"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel">
    <b>Select:</b><br />

    <Form Model="_formModal">
        <FormItem>

            <Select @bind-Value="@context.Name" 
                    DefaultValue=@("099") 
                    Options="@_options"
                    Style="width:120px" AllowClear>
            </Select>

            <Select @bind-Value="@context.Name" DefaultValue=@("lucy") Style="width:120px" AllowClear>
                <SelectOption Value="lucy">Lucy</SelectOption>
                <SelectOption Value="lucy1">Lucy 1</SelectOption>
                <SelectOption Value="lucy2">Lucy 2</SelectOption>
                <SelectOption Value="lucy3">Lucy 3</SelectOption>
            </Select>

        </FormItem>
    </Form>

</Modal>

@code{
    class FormModal
    {
        public string Name { get; set; } = "099";
    }

    string title = "BasicModal";
    bool _visible = false;
    List<LabeledValue> _options = new List<LabeledValue>();

    private FormModal _formModal = new FormModal();

    protected override void OnInitialized()
    {
        const int min = 0;
        const int max = 36;
        //_options = new LabeledValue[max - min];

        for (var i = min; max > i; i++)
        {
            var disabled = i == 10;
            var value = Convert.ToString(i, 16).PadLeft(2, '0') + i.ToString();
            //_options[i] = new LabeledValue(value, value);
            var lval = new LabeledValue(value, value);
            _options.Add(lval);
        }
    }

    private void HandleOk(MouseEventArgs e)
    {
        if (e == null) return;
        Console.WriteLine(e);
        _visible = false;
    }

    private void HandleCancel(MouseEventArgs e)
    {
        if (e == null) return;

        Console.WriteLine(e);
        _visible = false;
    }
}

### Further technical details
- AntDesign Nuget Package version - v0.3
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version -  vs 2019 - 16.7.5

**Comment by ElDiddi** [comment]
Hi JitenPatoliya,

unfortunately I cannot reproduce the bug in the latest build. Here is a code example.

```
<Button Type="primary" OnClick="@(()=>{ _visible = true; })">
    Open Modal
</Button>

<Modal Title="@title"
       Visible="@_visible"
       OnOk="@HandleOk"
       OnCancel="@HandleCancel">
    <Form Model="_formModal"
          LabelCol="new ColLayoutParam { Span = 4 }"
          WrapperCol="new ColLayoutParam { Span = 12 }"
          >
        <FormItem Label="Basic Select">
            <Select @bind-Value="@context.BasicValue" 
                     DefaultValue="@("lucy")" 
                     Style="width:120px" 
                     OnChange="@(OnChange)">
                <SelectOption Value="jack">Jack</SelectOption>
                <SelectOption Value="lucy">Lucy</SelectOption>
                <SelectOption Value="disabled" Disabled>Disabled</SelectOption>
                <SelectOption Value="yaoming">YaoMing</SelectOption>
            </Select>
        </FormItem>
        <FormItem Label="Tags">
            <Select Mode="tags"
                    @bind-Value="@context.TagValues"
                    Style="width: 100%"
                    Placeholder="Tags Mode"
                    AllowClear
                    OnChange="@(OnChange)">
                @foreach (var item in _items)
                {
                    <SelectOption Value="@item">@item</SelectOption>
                }
            </Select>
        </FormItem>
        <FormItem Label="Multiple">
            <Select Mode="multiple"
                    @bind-Value="@context.MultipleValues"
                    Style="width: 100%"
                    Placeholder="Please select"
                    AllowClear
                    DefaultValue="@(new[] { "0a10", "1420" })"
                    Options="@_options"
                    OnChange="@(OnChange)">
            </Select>
        </FormItem>
    </Form>
</Modal>

@using OneOf;
@code{
    class FormModal
    {
        public string BasicValue { get; set; }
        public string TagValues { get; set; }
        public string MultipleValues { get; set; }
    }

    string title = "BasicModal";
    bool _visible = false;
    private FormModal _formModal = new FormModal();
    private string[] _items;
    private LabeledValue[] _options;

    protected override void OnInitialized()
    {
        var min = 10;
        var max = 36;
        _items = new string[max - min];
        _options = new LabeledValue[max - min];

        for (var i = min; max > i; i++)
        {
            var disabled = i == 10;
            var value = Convert.ToString(i, 16).PadLeft(2, '0') + i.ToString();
            
            _items[i - min] = value;
            _options[i - min] = new LabeledValue(value, value);
        }
    }

    private void HandleOk(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }

    private void HandleCancel(MouseEventArgs e)
    {
        Console.WriteLine(e);
        _visible = false;
    }

    private void OnChange(OneOf<string, IEnumerable<string>, LabeledValue, IEnumerable<LabeledValue>> value, OneOf<SelectOption, IEnumerable<SelectOption>> option)
    {
        Console.WriteLine($"basic select: ${_formModal.BasicValue}");
        Console.WriteLine($"tags: ${_formModal.TagValues}");
        Console.WriteLine($"multiple: ${_formModal.MultipleValues}");
    }
}
```
