### ISSUE TITLE
Error: Cannot provide a value for property 'NotificationService' on type 'AntDesign.Notification'

### ISSUE THREAD

**Issue by ajitgoel** [ant-design-blazor/ant-design-blazor#704]
I am following the instructions provided in "Import Ant Design Blazor into an existing project" at https://github.com/ant-design-blazor/ant-design-blazor. When I run the application, I get the following error

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'NotificationService' on type 'AntDesign.Notification'. There is no registered service of type 'AntDesign.NotificationService'.
System.InvalidOperationException: Cannot provide a value for property 'NotificationService' on type 'AntDesign.Notification'. There is no registered service of type 'AntDesign.NotificationService'.
```
Based on the information provided [here](https://blog.csdn.net/qq_38436796/article/details/106938733), I need to define the "Register the services" in the program.cs instead of the startup.cs. Can you please advise?

**Comment by ElderJames** [comment]
Thank you for contacting us @ajitgoel ,
You should make sure that the service is registered to the corresponding host.
And use `services.AddAntDesign()` to register the services into MSDI.

**Comment by ajitgoel** [comment]
Hopefully this is a stupid question but how do I "the service is registered to the corresponding host"?. I followed the instructions documented here(https://github.com/ant-design-blazor/ant-design-blazor) to the T.

**Comment by ElderJames** [comment]
Sorry for my confusion.
I think this is the problem about dependency injection, you can see the [MS docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)

**Comment by ajitgoel** [comment]
I was able to get this working by installing the library in the client project and adding the line `builder.Services.AddAntDesign();` in the client project. 
I am assuming that the getting started portion of the ant-design-blazor needs to be updated.

**Comment by ElderJames** [comment]
Thank you for your advice @ajitgoel .
You also can help us to improve the document and PR is always welcome.
