### ISSUE TITLE
bug(module: select): Custom tags are not unchecked if they are cleared in the input field with the clear button

### ISSUE THREAD

**Issue by ElDiddi** [ant-design-blazor/ant-design-blazor#726]
### Describe the bug
If a `select` is `Mode="tags"` and the `AllowClear` option is used, the clear button clears the input field, but custom tags are not unchecked.

@ElderJames 
I have a design question. Should the custom tags still appear in the selection list or should they be deleted like in the React implementation?

### Further technical details
- AntDesign Nuget 0.3.0

**Comment by ElderJames** [comment]
We can delete them by default and allow user to save them in the options is they want.
