### ISSUE TITLE
The AntList does not appear to be used in a way that does not match the document description.

### ISSUE THREAD

**Issue by BigHeadDev** [ant-design-blazor/ant-design-blazor#729]
### Describe the bug
`
<AntList Bordered DataSource="@data">  
    <Header>Header</Header>  
    <ChildContent Context="item">  
        <ListItem>  
            <span><Text Mark>[ITEM]</Text></span>@item  
        </ListItem>  
    </ChildContent>  
    <Footer>Footer</Footer>  
</AntList>
`

The document doesn't seem to have been updated for too long. This makes it easy to lose dev users.
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Hi @BigHeadDev , you should clear the cache of browser and refresh forcedly. 
For now, still waiting for #731 is fixed.
