### ISSUE TITLE
CSS isolation not working for Ant Design Blazor components

### ISSUE THREAD

**Issue by dennisrahmen** [ant-design-blazor/ant-design-blazor#732]
### Describe the bug
CSS Isolation, which is new in .NET 5, does not work with Ant Design Blazor Components.
Styles which are defined in the Component with "<style></style>" are working but if they are defined in the *.razor.css file of the Component the styles does not get applied.

### Steps to reproduce
Create a new razor component "Test.razor" and copy the code below in that file. Now when you navigate to "/test" the layout is shown correctly.
Now add "Test.razor.css" file and cut the contents with in the "<style></style>" brackets and paste it in the just created CSS file. Now the styles are not applied when navigating to "/test".

```
@page "/test"

<Layout Class="layout">
    <Header>
        <div class="logo" />
        <Menu Theme="MenuTheme.Dark" Mode="MenuMode.Horizontal" DefaultSelectedKeys=@(new[]{"2"})>
            <MenuItem Key="1">nav 1</MenuItem>
            <MenuItem Key="2">nav 2</MenuItem>
            <MenuItem Key="3">nav 3</MenuItem>
        </Menu>
    </Header>
    <Content Style="padding: 0 50px;">
        <Breadcrumb Style="margin: 16px 0;">
            <BreadcrumbItem>Home</BreadcrumbItem>
            <BreadcrumbItem>List</BreadcrumbItem>
            <BreadcrumbItem>App</BreadcrumbItem>
        </Breadcrumb>
        <div class="site-layout-content">Content</div>
    </Content>
    <Footer Style="text-align: center; ">Ant Design ©2018 Created by Ant UED</Footer>
</Layout>

<style>
    .site-layout-content {
        background: #fff;
        padding: 24px;
        min-height: 280px;
    }
    #components-layout-demo-top .logo {
        width: 120px;
        height: 31px;
        background: rgba(255, 255, 255, 0.2);
        margin: 16px 24px 16px 0;
        float: left;
    }
</style>
```

### Further technical details
- 0.4.0-nightly-2010251512
- Visual Studio Community 2019 Preview (16.8.0 Preview 5.0)
- Output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by ElderJames** [comment]
Thank you for contacting us @4nTrax,

In the app, reference the bundled file by inspecting the reference inside the <head> tag of the generated HTML:
```
<link href="MyProjectName.styles.css" rel="stylesheet">
```

see https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#css-isolation-bundling

**Comment by 4nTrax** [comment]
Yeah, already have that referenced and it works on normal HTML elements.
Just not on the Ant Design components.

**Comment by brooklynDev** [comment]
Any update on this? Having to override the ant classes within a `<style>` tag isn't a deal breaker, but it would be nice to have it working within the `.css` files as well.

**Comment by 4nTrax** [comment]
Now running .NET 5.0 release and still the same issue:
- AntDesign 0.4.1
- Visual Studio Community 2019 Preview (16.8.1)

**Comment by ElderJames** [comment]
Hi friends, I have no idea on it. 

Do you know how to make a Razor Class Library support css isolation? Just create a same-name css file for every components?

**Comment by 4nTrax** [comment]
I made a minimal repo to show the issue: https://github.com/4nTrax/test-repo

On the Index page the styles are applied to the normal HTML, the buttons, the first button with a Class and the layout.

On the "Counter" page the styles are in the "Counter.razor.css" file and only applied to the normal HTML and the layout.

On the "FetchData" page are no styles.

**Comment by szmalec** [comment]
@4nTrax Have you tried to wrap all markup content in one root div element and then use [::deep modifier](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support) in css styles?

```
@page "/counter"
<div> <!-- root div wrapper -->
   <!-- markup -->
</div>
```

```
/*...*/
::deep .site-layout-content {
    background: #fff;
    padding: 24px;
    min-height: 280px;
}
/*...*/
```
In result blazor will render one root div in form similar to:

```
<div b-r4pn4kxzo2>
  <!-- content -->
</div>
```
and in BlazorApp1.Client.styles.css:

```
[b-r4pn4kxzo2] .site-layout-content {
    background: #8e0707;
    padding: 24px;
    min-height: 280px;
}
```

**Comment by Zonciu** [comment]
For now CSS isolation is not work well in blazor, it only add scope property to native html elements. If your component's root element is a custom component but not native element like `<div>`, the scope property won't add, thus the `::deep` modifier will not work as expected.

Conclusion: 
1. For native element, write css in {ComponentName}.razor.css
2. To applay css in child component, parent component needs to add a native element to wrap it self.

### Example:

* Test.razor
```
@page "/test"
<div>
    <Layout Class="layout">
        <Header>
            <div class="logo" />
            <Menu Theme="MenuTheme.Dark" Mode="MenuMode.Horizontal" DefaultSelectedKeys=@(new[]{"2"})>
                <MenuItem Key="1">nav 1</MenuItem>
                <MenuItem Key="2">nav 2</MenuItem>
                <MenuItem Key="3">nav 3</MenuItem>
            </Menu>
        </Header>
        <Content Style="padding: 0 50px;">
            <Breadcrumb Style="margin: 16px 0;">
                <BreadcrumbItem>Home</BreadcrumbItem>
                <BreadcrumbItem>List</BreadcrumbItem>
                <BreadcrumbItem>App</BreadcrumbItem>
            </Breadcrumb>
            <div class="site-layout-content">Content</div>
        </Content>
        <Footer Style="text-align: center; ">Ant Design ©2018 Created by Ant UED</Footer>
    </Layout>
</div>
```

* Test.razor.css

```
::deep .site-layout-content {
    background: #fff;
    padding: 24px;
    min-height: 280px;
    color: red;
    font-size: 36px;
}
::deep .ant-layout-footer {
    background-color: #2f54eb;
}
```

* In `Pages/_Host.cshtml`, add `<link href="{PROJECT NAME}.styles.css" rel="stylesheet">`, the placeholder {PROJECT NAME} is the referenced package or product name., like: `<link href="BlazorTest.styles.css" rel="stylesheet">`


### Result
![image](https://user-images.githubusercontent.com/10374056/101234170-1eb68700-36f8-11eb-964a-2bef4ea6da50.png)

**Comment by ElderJames** [comment]
@Zonciu Exactly, thank you for figuring that out.
@dennisrahmen  @brooklynDev  you can also learn more in the [official document](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0&WT.mc_id=DT-MVP-5003987#child-component-support)

**Comment by speyck** [comment]
Is there any solution to this Issue? It's really ugly to have the CSS in `<style>` tags in the HTML. Nothing mentioned in this post resolves the problem for me.

**Comment by Zonciu** [comment]
@speyck See my previous comment.

**Comment by dennisrahmen** [comment]
@speyck Keep in mind that you have to put the `<div>` in all of your components and layouts that you want to use with CSS isolation.

Just enclosing the `@Body` in your Layout does not work.

**Comment by speyck** [comment]
Thanks for the answer. I don't quite understand how this should work.

First of all, if I put `::deep` into my isolated CSS file, I get the following error:

> "::deep" is not a valid pseudo-element.	

Then I don't know how exactly how the solution should work. The example you have above doesn't actually contain any CSS that edits a AntDesign component. The only change you make with CSS is to this line: `<div class="site-layout-content">Content</div>` which is no custom component (the div contains no component at all). Could you perhaps show me another example?

I may just be too dumb to understand it, sorry if that's the case.

**Comment by dennisrahmen** [comment]
https://github.com/ant-design-blazor/ant-design-blazor/issues/732#issuecomment-739125806
```
@page "/test" <--- Blazor
<div> <--- HTML
    <Layout Class="layout"> <--- AntDesign
[...]
```
As you can see, the `<div>` is enclosing the `<Layout Class="layout">` wich is an AntDesign component.

---

Now you can create a ".razor.css" file for that page and add your css for the "layout" class of the Layout AntDesign component:
```
::deep .layout {
    background: #fff;
    padding: 24px;
    min-height: 280px;
    color: red;
    font-size: 36px;
}

```

**Comment by speyck** [comment]
Thanks a bunch for the answer. I get it now.

But now I have a problem with the CSS file. I can't use `::deep`. For some reason it gives me the following error:

> "::deep" is not a valid pseudo-element.

Do you have any idea what the problem could be?
Maybe I am on the wrong version or something.

**Comment by dennisrahmen** [comment]
You need .NET 5 to use CSS isolation in Blazor.

Could you share a minimal repo with that error?

**Comment by Zonciu** [comment]
Just ignore this error, `::deep` is used to modify the css of internal components.
If you only modify your own element's css, you don't need this.
If you need to modify an ant-blazor component's internal css, you need to add this.

## Example:

### Without `::deep`
![image](https://user-images.githubusercontent.com/10374056/127620337-14a844c5-84c1-4a03-9093-dd540481b7d4.png)

------------------------------------

### With `::deep`
![image](https://user-images.githubusercontent.com/10374056/127620453-d80a0359-50b3-4949-a262-268907514855.png)

**Comment by speyck** [comment]
@Zonciu thank you very much for elaborating.

@dennisrahmen I made a repo with my sample project: https://github.com/speyck/blazor-antdesign-test

**Comment by dennisrahmen** [comment]
@speyck Your repo does not include any of our previous suggestions. Also there is no content in the ".razor.css" files.
Please apply the changes @Zonciu mentioned in his comments!

If you have further problems with CSS isolation file a new issue here: https://github.com/dotnet/aspnetcore/issues

**Comment by speyck** [comment]
@dennisrahmen the repo is now updated.

I moved all the CSS in the .RAZOR files into their dedicated .CSS files and added `::deep` and a `div` wherever it's needed.

You will see that on every line `::deep` appears, the compiler gives the warning `"::deep" is not a valid pseudo-element.`

**Comment by dennisrahmen** [comment]
@speyck Thanks.

Replace:
`<link href="blazor_antdesign_test.styles.css" rel="stylesheet" />`
with:
`<link href="blazor-antdesign-test.styles.css" rel="stylesheet" />`

That way it works, since your project name is also written with "-".
Can´t find any issues with the `::deep`.

**Comment by speyck** [comment]
@dennisrahmen thank you.

Unfortunately, the warning still pops up. 
But I guess it's a problem with my machine and not the project itself, as you stated 

> Can´t find any issues with the `::deep`.

above.

**Comment by Zonciu** [comment]
> @dennisrahmen thank you.
> 
> Unfortunately, the warning still pops up.
> But I guess it's a problem with my machine and not the project itself, as you stated
> 
> > Can´t find any issues with the `::deep`.
> 
> above.

`::deep` is not a standard css grammar, it is a mark for the Blazor css processor, just ignore the IDE warning.
See document: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support

**Comment by speyck** [comment]
Will this be fixed anytime soon or is this no priority?

**Comment by Zonciu** [comment]
> Will this be fixed anytime soon or is this no priority?

I think you have misunderstood something. This is a problem with the IDE, not a problem with this project. You should ask the Visual Studio development team.

**Comment by speyck** [comment]
I have no problem with the warning that pops up when using `::deep`.

But the extra `div` that I have to place before all of my components messes with the whole CSS of my page. But I guess the extra `div` is a problem of Blazor itself and not this project?

**Comment by Zonciu** [comment]
The issue is here: https://github.com/dotnet/aspnetcore/issues/28443
Not sure when will fix this.
