### ISSUE TITLE
Infinite loop of Menu

### ISSUE THREAD

**Issue by houliren** [ant-design-blazor/ant-design-blazor#737]
当多个MenuItem 的RouterLink 设置同一个url时，整个menu会出现无限循环。代码 如下：
 <MenuItem RouterLink="@child.WebUrlOrArgs" RouterMatch="NavLinkMatch.All" Key="@child.Id.ToString()">@child.Name</MenuItem>
当两个menuitem的child.WebUrlOrArgs是同一个的时候，menu会进入到无限循环的渲染中。虽然这种业务需求可能不多，但是一旦配置的时候错误了，整个页面会进入的死循环的假死状态，无限未响应。

When the `RouterLink` property of multiple `MenuItem`s are set up as the same url, the whole Menu control would have infinite loop. The code is as below:
```
<MenuItem RouterLink="@child.WebUrlOrArgs" RouterMatch="NavLinkMatch.All" Key="@child.Id.ToString()">@child.Name</MenuItem>
```
If we set up the `child.WebUrlOrArgs` of two `MenuItem`s as the same value, the `Menu` control also gets an infinite loop so the page will be freezing as well.

**Comment by jrhodnik** [comment]
I just encountered this bug as well. `MenuItem`s with `RouterLink`s that start the same cause an infinite loop freeze, so long as the page URLs are routable. 

Example: Click one of the "Zero" entries and it'll freeze. The pages must be routable to prevent page refresh though.
```razor
<Menu>
    <MenuItem Key="2" RouterLink="zero">Zero</MenuItem>
    <MenuItem Key="3" RouterLink="zero/something">Zero Again</MenuItem>
    <MenuItem Key="4" RouterLink="one/something">One</MenuItem>
    <MenuItem Key="5" RouterLink="two/something">Two</MenuItem>
</Menu>
```
