### ISSUE TITLE
在生成解决方案的时候出现以下错误

### ISSUE THREAD

**Issue by wuyongfu** [ant-design-blazor/ant-design-blazor#739]
![image](https://user-images.githubusercontent.com/25544739/97514155-0d77ad80-19c9-11eb-82b3-b6aabd9f65c1.png)
本地vs版本是16.7.6
netCore版本是3.1.403
net版本是5.0.100-rc.2.20479.15
![image](https://user-images.githubusercontent.com/25544739/97514315-5a5b8400-19c9-11eb-9983-85a5549ba79b.png)

**Comment by ElderJames** [comment]
你好 @wuyongfu ，感谢关注 。

VS编译.NET 5需要preview版
