### ISSUE TITLE
Modal组件关闭之后无法自动销毁，必须手动设置DestroyOnClose

### ISSUE THREAD

**Issue by ma-hua** [ant-design-blazor/ant-design-blazor#745]
如果没有在OnOk回调函数中将Modal组件的Visible置为false, 而是执行一次NavigationManager.NavigateTo，或是执行了一个Task，
这常常会引发页面滚动条消失，或是AntDesign.DatePicker组件无法弹出等一些样式问题。
将DestroyOnClose设为True可以解决，
可不可以让DestroyOnClose默认为Ture呢，或是做一些其他的优化

**Comment by ma-hua** [comment]
有时候点击蒙层关闭，同样会引起一些样式问题

**Comment by zxyao145** [comment]
@ma-hua 
您好，感谢您的提问与建议！请问您所使用的版本是多少？如果使用<Modal />组件，是必须要在 OnOk 和 OnClose中设置Visible=false的，或者您可以看下 ModalService的用法。
DestroyOnClose 设置 ture，每次关闭 Modal 时会将 Modal 组件进行销毁，对于浏览器来说，性能可能会比 DestroyOnClose 设置 false 时更差。
