### ISSUE TITLE
Switch Loading图标偏移

### ISSUE THREAD

**Issue by lungchito** [ant-design-blazor/ant-design-blazor#762]
v0.3
Microsoft Edge

异常
[https://ant-design-blazor.gitee.io/zh-CN/components/switch#components-switch-demo-Disable](https://ant-design-blazor.gitee.io/zh-CN/components/switch#components-switch-demo-Disable)

![QQ拼音截图20201104182007](https://user-images.githubusercontent.com/32699569/98099426-83e54580-1eca-11eb-95d1-614442cc87a9.png)

正常
[https://ant.design/components/switch-cn/#components-switch-demo-loading](https://ant.design/components/switch-cn/#components-switch-demo-loading)

**Comment by 1002527441** [comment]
<span role="img" class="ant-switch-loading-icon anticon anticon-loading anticon-spin" id="ant-blazor-09606107-3aa6-4656-8907-60f79472f62d">
<svg  width="1em" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" class="anticon-spin" focusable="false" data-icon="loading" aria-hidden="true" height="1em">
  <path d="M988 548c-19.9 0-36-16.1-36-36 0-59.4-11.6-117-34.6-171.3a440.45 440.45 0 00-94.3-139.9 437.71 437.71 0 00-139.9-94.3C629 83.6 571.4 72 512 72c-19.9 0-36-16.1-36-36s16.1-36 36-36c69.1 0 136.2 13.5 199.3 40.3C772.3 66 827 103 874 150c47 47 83.9 101.8 109.7 162.7 26.7 63.1 40.2 130.2 40.2 199.3.1 19.9-16 36-35.9 36z"></path>
</svg>
</span>

remove the class of antIcon-spin from <span>, add it on svg.

**Comment by LOMO19** [comment]
antd 4.2 switch 按钮 loading 状态还是有偏移, 如何解决这个问题?
![image](https://user-images.githubusercontent.com/48351397/236591051-01e87b73-7ce3-41c1-a377-32fbd240671b.png)
