### ISSUE TITLE
bugs in tree component 

### ISSUE THREAD

**Issue by 1002527441** [ant-design-blazor/ant-design-blazor#765]
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Tree控件bugs, 当search后，相应的节点不能展开和拆叠。
![image](https://user-images.githubusercontent.com/53967483/98348347-950d8e00-2053-11eb-9951-e00523cb665c.png)

**Comment by TimChen44** [comment]
在search时，所有节点默认展开，因为我觉得搜索的目的就是找到需要的节点，那么折叠就没有意义了，折叠后不知道里面是否有自己需要的。

**Comment by 1002527441** [comment]
在search后，如果每一个节点下上百条数据，而这样的节点有多个， 在这种情况下就有一定的意义了。因为这样，查看数据更加容易。
