### ISSUE TITLE
From 表单异步问题

### ISSUE THREAD

**Issue by lyjcooi** [ant-design-blazor/ant-design-blazor#773]
### Describe the bug
from表单里面异步赋值的问题

### Steps to reproduce (please include code)
 model = await assignmengCategoryAdminAppService.GetAsync(id.ToLong());
当我赋值时候用调用异步方法后，修改任何表单里的值都会提示值为空，点击提交按钮会进
OnFinishFailed(EditContext editContext) 方法， 里面的 editContext的 model 里面所有的属性都是null 
而程序中我声明的 model  是有值的，而且页面上也能加载出来
### Exceptions (if any)
但是我将  model = assignmengCategoryAdminAppService.Get(id.ToLong()) model调用的方法改为同步，就没有任何问题了
### Further technical details 
- AntDesign Nuget Package version  0.4.0-nightly-2011091423
- Microsoft Visual Studio Community 2019版本 16.7.6

**Comment by mutouzdl** [comment]
据我了解，目前model只能赋值一次，也就是说，model第一次赋值后，再给它赋值就不会生效。
采用异步赋值，相当于初始值是null，所以就出现这个问题了。

**Comment by wangjunjx8868** [comment]
> 据我了解，目前model只能赋值一次，也就是说，model第一次赋值后，再给它赋值就不会生效。
> 采用异步赋值，相当于初始值是null，所以就出现这个问题了。

我同步赋值 还是空的，不过你说“model只能赋值一次” 应该是这个问题，目前这个问题不知道怎么解决。

**Comment by mutouzdl** [comment]
> > 据我了解，目前model只能赋值一次，也就是说，model第一次赋值后，再给它赋值就不会生效。
> > 采用异步赋值，相当于初始值是null，所以就出现这个问题了。
> 
> 我同步赋值 还是空的，不过你说“model只能赋值一次” 应该是这个问题，目前这个问题不知道怎么解决。

目前可以这么做，在获取到model值之前，不渲染Form表单：
if(model != null) {
    <Form>...</Form>
}

**Comment by wangjunjx8868** [comment]
> 目前可以这么做，在获取到model值之前，不渲染Form表单：
> if(model != null) {
> ...
> }
```c#
  List<DailyAnswer.Domain.Scenic> datas = new List<DailyAnswer.Domain.Scenic>();
//打开弹窗，显示要编辑的实体
        public void showEditDrawer(int id)
        {
            modelEdit = datas.FirstOrDefault(q => q.Id == id);
            this.editVisible = true;//这个值为true  弹窗就显示出来？
        }
```
怎么再赋值后强制渲染呢？而没赋值之前 不去渲染？

**Comment by mutouzdl** [comment]
> > 目前可以这么做，在获取到model值之前，不渲染Form表单：
> > if(model != null) {
> > ...
> > }
> 
> ```cs
>   List<Scenic> datas = new List<Scenic>();
> //打开弹窗，显示要编辑的实体
>         public void showEditDrawer(int id)
>         {
>             modelEdit = datas.FirstOrDefault(q => q.Id == id);
>             this.editVisible = true;//这个值为true  弹窗就显示出来？
>         }
> ```
> 
> 怎么再赋值后强制渲染呢？而没赋值之前 不去渲染？

比如你要给Form的Model绑定的是modelEdit变量，那就这么判断：
```
if(modelEdit != null) {
    <Form model={modelEdit}></Form>
}
```
modelEdit初始值是null。

**Comment by wangjunjx8868** [comment]
> > > 目前可以这么做，在获取到model值之前，不渲染Form表单：
> > > if(model != null) {
> > > ...
> > > }
> > 
> > 
> > ```cs
> >   List<Scenic> datas = new List<Scenic>();
> > //打开弹窗，显示要编辑的实体
> >         public void showEditDrawer(int id)
> >         {
> >             modelEdit = datas.FirstOrDefault(q => q.Id == id);
> >             this.editVisible = true;//这个值为true  弹窗就显示出来？
> >         }
> > ```
> > 
> > 
> > 怎么再赋值后强制渲染呢？而没赋值之前 不去渲染？
> 
> 比如你要给Form的Model绑定的是modelEdit变量，那就这么判断：
> 
> ```
> if(modelEdit != null) {
>     <Form model={modelEdit}></Form>
> }
> ```
> 
> modelEdit初始值是null。

```c#
   List<Scenic> datas = new List<Scenic>();
        public Scenic modelEdit = new Scenic();
        public void showEditDrawer(int id)
        {
            Scenic mymodel = datas.FirstOrDefault(q => q.Id == id);
            if (mymodel != null) 
            {
                modelEdit = mymodel;
                this.editVisible = true;
            }
        }
```
这样吗？不行的

**Comment by mutouzdl** [comment]
@wangjunjx8868 
这样：
 ```
   @if (model == null)
    {
        <p><em>Loading...</em></p>
    }
    else
    {
        <Form Model="@model"
              LabelCol="new ColLayoutParam { Span = 8 }"
              WrapperCol="new ColLayoutParam { Span = 16 }"
              OnFinish="OnFinish">
            <FormItem Label="Username">
                <Input @bind-Value="@context.Title" />
            </FormItem>
            <FormItem WrapperCol="new ColLayoutParam{ Offset = 8, Span = 16 }">
                <Button Type="@ButtonType.Primary" HtmlType="submit">
                    Submit
                </Button>
            </FormItem>
        </Form>
    }
```

**Comment by wangjunjx8868** [comment]
> @wangjunjx8868
> 这样：
> 
> ```
>   @if (model == null)
>    {
>        <p><em>Loading...</em></p>
>    }
>    else
>    {
>        <Form Model="@model"
>              LabelCol="new ColLayoutParam { Span = 8 }"
>              WrapperCol="new ColLayoutParam { Span = 16 }"
>              OnFinish="OnFinish">
>            <FormItem Label="Username">
>                <Input @bind-Value="@context.Title" />
>            </FormItem>
>            <FormItem WrapperCol="new ColLayoutParam{ Offset = 8, Span = 16 }">
>                <Button Type="@ButtonType.Primary" HtmlType="submit">
>                    Submit
>                </Button>
>            </FormItem>
>        </Form>
>    }
> ```

可以了，谢谢，不过还得多注意一下，如果某一条数据修改成功了，还得把对象再次初始化成空，否则还是出问题。再次感谢你。

**Comment by ElderJames** [comment]
大家好，这个issue应该在 PR#1035 修复了，请更新最新的0.6.0 nightly 测试一下。
