### ISSUE TITLE
nuget package v0.4.1 Cascader DefaultValue is error

### ISSUE THREAD

**Issue by lungchito** [ant-design-blazor/ant-design-blazor#775]
nuget package v0.4.1
Microsoft Edge

The expected value should be “湖北/武汉/洪山区”

![QQ拼音截图20201110173422](https://user-images.githubusercontent.com/32699569/98656231-69541600-237b-11eb-9e53-0d2428e7bc21.png)

![QQ拼音截图20201110173532](https://user-images.githubusercontent.com/32699569/98656257-707b2400-237b-11eb-9e3a-eb7c897a40b5.png)

![QQ拼音截图20201110173513](https://user-images.githubusercontent.com/32699569/98656348-87217b00-237b-11eb-975d-59a9653a4e01.png)

**Comment by lungchito** [comment]
The nuget package had updated to version 0.5.0-nightly-2011300301
The problem is still exist.

**Comment by ElderJames** [comment]
Hi @lungchito. please try 0.6.0.
