### ISSUE TITLE
关于Antd Layout 组件隔离 css 的问题

### ISSUE THREAD

**Issue by Jess-Qiu** [ant-design-blazor/ant-design-blazor#795]
在 razor 组件中使用隔离 css ，Antd 组件通过 Class 引用隔离 css 的类名时运行项目样式并没生效，对比了 html 的标签，Antd 标签并没有携带类似的 <h1 **b-xxxxxxx**>  标识。这个有办法解决么？

**Comment by ww156** [comment]
这个问题怎么解决的呀

**Comment by ElderJames** [comment]
You need to warp the components with a div or spam.
