### ISSUE TITLE
[Modal]无法在Modal中使用具有下拉或弹出功能的组件

### ISSUE THREAD

**Issue by Asio-O** [ant-design-blazor/ant-design-blazor#797]
nuget package v0.4.1
Microsoft Edge

无法在Modal中使用具有下拉或弹出功能的组件。
组件演示页面的这部分功能也无法正常工作。
https://ant-design-blazor.gitee.io/zh-CN/components/modal

**Comment by zxyao145** [comment]
@Asio-O 您好，您能具体描述下问题是什么吗？请问是切换页面后 下拉或弹出功能组件 无法再次使用吗？是与 #757 相同吗？

**Comment by Asio-O** [comment]
@zxyao145   您好，经过测试，发现问题与 #757 相同
在https://ant-design-blazor.gitee.io/zh-CN/components/modal页面中可复现
1、点击最后一个Open Modal按钮，在对话框打开后关闭它
![image](https://user-images.githubusercontent.com/20653356/99473034-bf7d1680-2984-11eb-970d-631d87a1b6cf.png)
2、通过点击页面左侧的菜单跳转至其他页面再跳转回来
![image](https://user-images.githubusercontent.com/20653356/99473391-724d7480-2985-11eb-8261-aaf2b09665a4.png)
3、再次点击最后一个Open Modal按钮打开对话框后，其中具有下拉和弹出功能的组件无法正常使用

**Comment by zxyao145** [comment]
@Asio-O 非常感谢您，目前这个bug正在修复中，请您持续关注，谢谢！
