### ISSUE TITLE
nuget package v0.4.1 Table Checkbox多选行没有同时选中背景色

### ISSUE THREAD

**Issue by lungchito** [ant-design-blazor/ant-design-blazor#801]
nuget package v0.4.1
Microsoft Edge

当前呈现：
[https://ant-design-blazor.gitee.io/zh-CN/components/table#components-table-demo-row-selection](https://ant-design-blazor.gitee.io/zh-CN/components/table#components-table-demo-row-selection)
![QQ拼音截图20201118081712](https://user-images.githubusercontent.com/32699569/99466498-7a061c80-2977-11eb-841f-547f0e502d24.png)

期待呈现：
[https://ant.design/components/table-cn/#components-table-demo-row-selection](https://ant.design/components/table-cn/#components-table-demo-row-selection)
![QQ拼音截图20201118081937](https://user-images.githubusercontent.com/32699569/99466788-fa2c8200-2977-11eb-9b44-04fe42cc23bd.png)

**Comment by ElderJames** [comment]
Thanks for contacting us @ lungchito.
I can't reproduce it here, please submit the reproducible code.

你好 @lungchito 
我这边不能重现，请提交一下可重现代码。

**Comment by lungchito** [comment]
version: 0.5.0-nightly-2011270850
Microsoft Edge

可重现代码:
@page "/Table/BackgroundColorBug"
@layout TableLayout

><div>
    <Table DataSource="@data">
        <Selection Key="@context.Name" Type="checkbox"></Selection>
        <Column @bind-Field="@context.Name">
            <a>@context.Name</a>
        </Column>
        <Column @bind-Field="@context.Age"></Column>
        <Column @bind-Field="@context.Address"></Column>
    </Table>
</div>

@code {
    public class Column
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
    }

    Column[] data =
    {
        new Column()
        {
            Name = "John Brown",
            Age = 32,
            Address = "New York No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Jim Green",
            Age = 42,
            Address = "London No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Joe Black",
            Age = 32,
            Address = "Sidney No. 1 Lake Park",
        },
        new Column()
        {
            Name = "Disabled User",
            Age = 99,
            Address = "Sidney No. 1 Lake Park",
        }
    };
}

**Comment by ElderJames** [comment]
@lungchito Please update to 0.8.4.

您好，已经修复了。我在 0.8.4 中运行没有问题。
