### ISSUE TITLE
popover cant't close

### ISSUE THREAD

**Issue by mutouzdl** [ant-design-blazor/ant-design-blazor#817]
### Describe the bug

popover弹出来之后就关不了了

-------------translate------------

popover cant't close

### Steps to reproduce (please include code)

打开【从浮层内关闭】的demo

-------------translate------------

open the demo doc in Controlling the close of the dialog

![image](https://user-images.githubusercontent.com/3509249/99920807-fd04e980-2d60-11eb-8413-8d4d168159af.png)

### Further technical details
- AntDesign Nuget Package version: 0.4.1

**Comment by ZaferGokhan** [comment]
> ### Describe the bug
> popover弹出来之后就关不了了
> 
> -------------translate------------
> 
> popover cant't close
> 
> ### Steps to reproduce (please include code)
> 打开【从浮层内关闭】的demo
> 
> -------------translate------------
> 
> open the demo doc in Controlling the close of the dialog
> 
> ![image](https://user-images.githubusercontent.com/3509249/99920807-fd04e980-2d60-11eb-8413-8d4d168159af.png)
> 
> ### Exceptions (if any)
> ### Further technical details
> * AntDesign Nuget Package version: 0.4.1

Try this, it works for me. OnMaskClick="MaskClick"


   public void  MaskClick()
{
       PopoverVisible = false;
}
