### ISSUE TITLE
Is Ant design blazor support RTL or NOT?

### ISSUE THREAD

**Issue by khaledalmolaa** [ant-design-blazor/ant-design-blazor#824]

**Comment by ElderJames** [comment]
Thank you for contacting us @khaledalmolaa .

We haven't supported RTL yet. But the styles are supported because they are sync from ant-design.
So if you can help us implement this feature, we'd really appreciate it.
If you have any ideas, just feel free to create a PR.

**Comment by Epictek** [comment]
Duplicate of #275
