### ISSUE TITLE
Select component for enums

### ISSUE THREAD

**Issue by Mann-im-Mond** [ant-design-blazor/ant-design-blazor#825]
### Problem
When creating a `<Select>`-field for to select values of an enumeration, I manually need to add the possible options again and add an onchange-function to then change the value in an `<EditForm>`.

### Sugested solution
It would be greate to have one `<SelectEnum>`-field that takes over all the work as it was done [here](https://www.meziantou.net/creating-a-inputselect-component-for-enumerations-in-blazor.htm) - but of course in ant design!

**Comment by Epictek** [comment]
Would casting the Enum to a list of string and passing it to DataSource work?

**Comment by ElderJames** [comment]
@Epictek @ElDiddi I think We can support it in the new select. Enable user only pass the enum type as the generic type.

**Comment by mreinfurt** [comment]
@ElderJames Any update on this? Is the currently suggested way to use string values instead of the enum directly?

I could also try and implement a <SelectEnum> and then create a merge request here. Do you have any design thoughts / requirements on it?

**Comment by ElderJames** [comment]
We haven't started working on it yet. It would be nice if you could help.
The general requirement is not to affect performance, and you can use static caching to store the reflected results of enum types.

**Comment by dennisrahmen** [comment]
@mreinfurt It would be nice to have some form of localisation support or some way to define a display value.

I have seen something like that :
```
public enum Gender
{
    [Description("Not set")]
    notset,
    [Description("Male")]
    male,
    [Description("Female")]
    female,
    [Description("Other")]
    other
}
```
That way you can give the select component the enum and it will display the display value.

**Comment by mreinfurt** [comment]
@dennisrahmen Sounds good! My use case needs localisation as well. I'll see what I can do.

**Comment by dennisrahmen** [comment]
@mreinfurt If I can assist you with anything, I´m happy to help.

**Comment by ElderJames** [comment]
This issue is also duplicated with #417

**Comment by ElderJames** [comment]
Hi all, we create the EnumSelect in 0.9.0!!
