### ISSUE TITLE
nuget package 0.5.0-nightly-2012011145 Tag Mode 拼写错误 closeable -> closable

### ISSUE THREAD

**Issue by lungchito** [ant-design-blazor/ant-design-blazor#845]
nuget package AntDesign 0.5.0-nightly-2012011145
Microsoft Edge

Tag Mode 拼写错误 closeable -> closable

`<Tag Mode="closeable">Tag 1</Tag>`

**Comment by ElderJames** [comment]
你好 @lungchito ，感谢关注我们！
请问是tag组件吗？如果方便的话，你可以帮忙提交一个PR。

**Comment by lungchito** [comment]
@ElderJames 
已经放了范例代码。
刚开始接触开源项目，我现在只是基于nuget package进行验证，暂时没有debug源代码。
因为我还没用过git， @ @

个人感觉，这个项目还不是很活跃哦。
提交的issue挺久没人回应的。

**Comment by ElderJames** [comment]
是的😁很多人只提issue不提PR

**Comment by lungchito** [comment]
你是在说我嘛，o(╥﹏╥)o

**Comment by ElderJames** [comment]
很多人都是呢，你可以尝试一下，Github贡献操作我们会协助你。有问题在这问就行😁

**Comment by lungchito** [comment]
好的，有机会我试一下。
不懂的地方，请教你们哦。
