### ISSUE TITLE
Modal needs updating to TitleTemplate api

### ISSUE THREAD

**Issue by Epictek** [ant-design-blazor/ant-design-blazor#846]
Currently it's still using OneOf, it should be updated to separate params for string/renderfragment so that it is consistent with the rest of the API and so that it supports razor templating

**Comment by ElderJames** [comment]
Yes, could you do that? 😊

**Comment by Epictek** [comment]
will do after I've clocked out of work in a few hours :)

**Comment by ElderJames** [comment]
Done in #914 .
