### ISSUE TITLE
Is source code not utf-8?

### ISSUE THREAD

**Issue by Eliot00** [ant-design-blazor/ant-design-blazor#858]
https://github.com/ant-design-blazor/ant-design-blazor/blob/2a3d171205db070fc8fe534c8f5ed73d620218ba/components/table/Column.razor#L50-L51

I use Vim and I typed this command:

```
:set fileencoding
```

and I get result is `latin1`

**Comment by ElderJames** [comment]
Thank you for pointing this out.

I have fix it. Do you know how to fix all files in UTF8?

**Comment by Eliot00** [comment]
> Thank you for pointing this out.
> 
> I have fix it. Do you know how to fix all files in UTF8?

I know a cli tool in linux named enca, maybe I can create a pull request to fix this

**Comment by Eliot00** [comment]
This seems to be a Windows-specific problem. I don’t know if direct modification will cause other errors.

**Comment by ElderJames** [comment]
Since the file has been fixed, close the issue first. Thank you.
