### ISSUE TITLE
Double-edged slider will lock on left edge only after first usage.

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/ant-design-blazor#859]
### Describe the bug
Cannot move right edge once left edge was moved. 

### Steps to reproduce (please include code)
```csharp
<Slider TValue="(double, double)" , Min="@_testMin" Max="@_testMax" DefaultValue="(_start, _end)" />
@code {
    private double _testMin = 0;
    private double _testMax = 60;
    private double _start = 10;
    private double _end = 30;
}
```
And gif:
![slider_right_broken](https://user-images.githubusercontent.com/6518006/101265311-0c673800-374e-11eb-8919-9d06286d67d9.gif)
I was also able to  recreate it using the [documentation for slider](https://antblazor.com/en-US/components/slider).

### Further technical details
- AntDesign commit 58d29af (Dec 5, 2020)
- Running net5.0
- Visual Studio 16.8.2

### My analysis
First, I thought that the problem is in ```Slider.razor.cs``` in the usage of ```bool _right = true``` field. It seemed to me that this field is used for evaluation of which edge is being changed. But later on I figured that this is just to start-off a calculation that is assuming the change applies to the same edge as the last change, and actualy during the calculation in ```CalculateValueAsync``` it is really evaluated there which edge needs to be updated (although favours current scenario ```_right```). It seems to me that the problem there is that it deals with numbers and comparisons that unfortunatelly are too absolute for user experience. So in my example:
- Min: 0, Max: 100
- Start : 10, End: 30  

1. If I change end by as small margin (let's say to 29) and ```_right = true``` then what is evaluated is this ``` 29 < 10 //new value < current start```. If ```true``` then assumes that start edge is being changed, otherwise, end edge is being changed.
2. If now I try to do a similar change to start (let's say to 9) with ```_right = true``` then again the same evaluation is done ``` 9 < 10 //new value < current start```. This time it is ```true``` so ```_right``` is set to ```false``` and left/start edge is update with the new value. From now on the left edge scenario will be favoured.
3. If now I try to change again the end (let's say to 28) and ```_right = false``` then new evaluation is run (according to the left edge scenario) ``` 28 > 29 //new value > current end```. This evaluates to ```false```, so slider assumes that actually left edge had changed (which is wrong, because end/right edge had been changed). 

The more I look at the ranged slider, the more it seems to me conceptually it is closer to date range picker. For this issue, I think it would be better to have separate mouse events for each edge, so maybe the evaluation based on calculation could be avoided. I only now started to go through the code and I am far away from understanding how everything is wired here, however I will probably try to do that. Especially that I will likely need to expand on the slider idea a bit.

**Comment by anddrzejb** [comment]
After playing a bit longer with this I obviously noticed that my approach as a noob user made the problem stand out. I by default try clicking and dragging the edges. If I try to apply that logic, then there is a problem. I understand the locking logic. We click on one of the edges, it locks (first time) on that edge. The problem is that once we lock on the left edge, the only way to lock on the right edge is to click to further to the right in respect to the right edge (click after the right edge). Clicking on the right edge will likely move the left edge to the same position as the right edge (what is shown in the gif). That is of course not an impossible scenario (we may want to have left and right edges in the same position), but it is also likely that a user would like to switch the focus on the right edge. Again, this problem could possibly be fixed by separate mouse events for each edge (at least for pinpointing if edge is clicked, to change the method focus on either left or right edge).

**Comment by anddrzejb** [comment]
So I tried to fix it today according to the idea I mentioned earlier by adding extra ```onmousedown``` event handler to ```Slider.razor.cs```:
```csharp
        private void OnMouseDownEdge(MouseEventArgs args, bool right)
        {
            _right = right;
        }
```
and using that handler in ```Slider.razor```
```razor
    @if (Range)
    {
        <div tabindex="0" class="ant-slider-handle ant-slider-handle-1" role="slider" aria-disabled="@Disabled.ToString()" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="@_leftHandleStyle" @ref="_leftHandle" 
@*new event*@
@onmousedown="(e)=>OnMouseDownEdge(e,  false)">
        </div>
        <div tabindex="0" class="ant-slider-handle ant-slider-handle-2" role="slider" aria-disabled="@Disabled.ToString()" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="@_rightHandleStyle" @ref="_rightHandle" 
@*new event*@
@onmousedown="(e)=>OnMouseDownEdge(e,  true)">
        </div>
    }
```
That was not enough, I was getting ```NullArgumentException``` in ```CalculateValueAsync``` for ```_right=false``` scenario, that ```_rightHandleDom``` was not initialized. So I added to the method the following lines (basically copied form ```_right=true``` scenario):
```csharp
                if (_rightHandleDom == null)
                {
                    _rightHandleDom = await JsInvokeAsync<Element>(JSInteropConstants.GetDomInfo, _rightHandle);
                }
```
That did the trick. After my changes I got this result
![slider_focus_cheat](https://user-images.githubusercontent.com/6518006/101293052-ec9e4580-381b-11eb-8ffe-58e7e99b6dd2.gif)


Well...I lied here in this gif a bit. This look very good at first glance, but after a bit of playing around, I found out that just clicking on an edge sometimes would cause it to move:
![slider_focus_click_move](https://user-images.githubusercontent.com/6518006/101293060-f031cc80-381b-11eb-9971-b86e734cf35b.gif)


This has all to do with the fact that edge has a defined area and sometimes clicking within edge's div's area will actually equal to a step move. So I figured I could maybe register a click on an edge and detect if this is only a click or a movement. It took me some time to do it without heavy changes to the design. I had to introduce new event handler and a few changes to existing event handlers. First, new event in ```Slider.razor```
```razor
    @if (Range)
    {
        <div tabindex="0" class="ant-slider-handle ant-slider-handle-1" role="slider" aria-disabled="@Disabled.ToString()" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="@_leftHandleStyle" @ref="_leftHandle" 
	@*new events*@
	@onmousedown="(e)=>OnMouseDownEdge(e,  false)" 
	@onmouseup="(e)=>OnMouseUpEdge(e)">
        </div>
        <div tabindex="0" class="ant-slider-handle ant-slider-handle-2" role="slider" aria-disabled="@Disabled.ToString()" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="@_rightHandleStyle" @ref="_rightHandle" 
	@*new events*@
	@onmousedown="(e)=>OnMouseDownEdge(e,  true)" 
	@onmouseup="(e)=>OnMouseUpEdge(e)">
        </div>
    }

```
and of course event handlers in ```Slider.razor.cs``` with some accompaning changes
```csharp
	//Set in OnMouseDownEdge and used by OnMouseUpEdge to evaluate if there was no movement of mouse 
	//between the events. If no movement was registered, then it was just as click on the edge in question.
        private MouseEventArgs _edgeClickArgs; 
	//A flag that is set in OnMouseUpEdge - means that the edge was only clicked.
        private bool _edgeClicked;

        private void OnMouseDownEdge(MouseEventArgs args, bool right)
        {
            _right = right;
            _edgeClickArgs = args;
        }

        private void OnMouseUpEdge(MouseEventArgs args)
        {
	    //Evaluates if there was any mouse movement; this is probably not a full-proof, may need more 
	    //investigation. Omitted .ScreenX, .ScreenY, .OffsetX, and .OffsetY as they are only
	    //present in net5.0
            if (_edgeClickArgs.ClientX == args.ClientX
             && _edgeClickArgs.ClientY == args.ClientY
             && _edgeClickArgs.CtrlKey == args.CtrlKey
             && _edgeClickArgs.Detail == args.Detail
             && _edgeClickArgs.MetaKey == args.MetaKey
             && _edgeClickArgs.ShiftKey == args.ShiftKey)
            {
                _edgeClicked = true;
            }
        }

        private async void OnMouseMove(JsonElement jsonElement)
        {
	    //If this is only click on the edge, there is no need to do any recalculation
            if (_mouseDown && !_edgeClicked)
            {
                _mouseMove = true;
                await CalculateValueAsync(Vertical ? jsonElement.GetProperty("pageY").GetDouble() : jsonElement.GetProperty("pageX").GetDouble());

                OnChange?.Invoke(CurrentValue);
            }
        }

        private async void OnMouseUp(JsonElement jsonElement)
        {
            if (_mouseDown)
            {
                _mouseDown = false;
		//evaluation moved here, so _mouseDown is reset, otherwise slider gets locked and 
		//the edge will be following mouse cursor 
                if (!_edgeClicked)
                {
                    await CalculateValueAsync(Vertical ? jsonElement.GetProperty("pageY").GetDouble() : jsonElement.GetProperty("pageX").GetDouble());
                    OnAfterChange?.Invoke(CurrentValue);
                }
            }
	    //reset flag so another edge click can be monitored
            if (_edgeClicked)
            {
                _edgeClicked = false;
            }
        }
```
These changes resulted in this behaviour:
![slider_focus_edge_ok](https://user-images.githubusercontent.com/6518006/101293069-faec6180-381b-11eb-8d3f-43319af58719.gif)


It seems to be working. What I am worried about is the order of events being fired. Because the events are different - the ones I added are the ones that are built in to blazor. The ones I changed - I am not sure, I guess they are js events marshalled to C#, but did not have much time to dwell on that. So I am not sure what is going to happen if the order of events will be different on other machines. I would love any discussion here.

**Comment by ElderJames** [comment]
Hey @anddrzejb , thank you for your great works! 👍

You could just feel free to submit a PR :)

**Comment by anddrzejb** [comment]
Ok, I will try to do that. I found some more bugs/performance issues with the slider. Shall I all include that in single PR? Shall I also open issues (and then try to close them in PR) regarding those other bugs/performance issues? Sorry for those questions, this will be my first PR.

**Comment by ElderJames** [comment]
@anddrzejb Sure, that is more helpful if you could link the issues which you have fixe in ypur PR.
