### ISSUE TITLE
Range Slider: reversing order of values given in the tuple renders both edges in the same position

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/ant-design-blazor#867]
### Describe the bug
I am not sure if this is by design or it is a bug. But the issue I am reporting on appears
when a new set of values are provided, that are in reversed the order. So for example if I supply ```Value="(30, 11)"```.

### Steps to reproduce (please include code)
On a new component add this code:
```razor
<Slider TValue="(double, double)" , Min="@_testMin" Max="@_testMax" DefaultValue="(_start, _end)" />
<Slider TValue="(double, double)" , Min="@_testMin" Max="@_testMax" DefaultValue="(_end, _start)" />
<Button OnClick="Reverse">Reverse </Button>
@code {
    private double _testMin = 0;
    private double _testMax = 60;
    private double _start = 10;
    private double _end = 30;

    private void Reverse()
    {
        var t = _start;
        _start = _end;
        _end = t;
    }
}
```
Notice that in the second slider first value provided is _end and then _start. That causes slider to be rendered as a single point:
![slider_reversed_order_err](https://user-images.githubusercontent.com/6518006/101369946-8d8b1000-38b1-11eb-9efb-f8bc2425778d.gif)

If this is an intended design, then please close the issue. Although I imagine if the values can be served by an API, this scenario is not impossible and this may not be an expected result.

### Further technical details
- AntDesign commit 58d29af (Dec 5, 2020)
- Running net5.0
- Visual Studio 16.8.2

**Comment by ElderJames** [comment]
I think this is by design. After all, the left side can't be greater than the right side.

**Comment by anddrzejb** [comment]
I just had a look at the original [ant.design](https://ant.design/components/slider/) and at the code sandbox, and if you supply values in reverse, it actually puts them in the right order. Does that change the design?

**Comment by ElderJames** [comment]
Ok, we should following the behavior of ant design.
