### ISSUE TITLE
Allow interact with page when Modal without Mask is displayed

### ISSUE THREAD

**Issue by szmalec** [ant-design-blazor/ant-design-blazor#870]
I would like to use the Modal component to display something like a tool panel:

```
<Modal Title="@("Test tool panel")"
       Visible="@Visible"
       OnOk="OnCloseClick"
       OnCancel="OnCloseClick"
       Footer="null"
       Mask="false"
       MaskClosable="false"
       Draggable>
    <!-- tools panel content -->
</Modal>
```
Unfortunately, the problem is that despite setting the `Mask=false` property, it is not possible to interact with the page content in the background of this panel. I assume this is not a bug - just the property `Mask=false` is only used to disable the dimmed area. However, I would like to ask if it would be possible to add an parameter that allows interaction (page scrolling, clicking, entering text into input fields) with the content over which such a panel is displayed? Or maybe something like `Mask=null` to disable  Mask (ant-modal-wrap) completly?

**Comment by szmalec** [comment]
For those interested - as a temporary workaround I used:
```
<div role="document" class="ant-modal zoom-enter zoom-enter-active" style="position: fixed; z-index: 1000; width: 420px; top: 62px; right: 10px;">
	<div class="ant-modal-content">
		<button type="button" aria-label="Close" class="ant-modal-close" @onclick="@OnCloseClick">
			<span class="ant-modal-close-x">
				<span role="img" aria-label="close" class="anticon anticon-close ant-modal-close-icon">
					<Icon Type="close" Theme="outline" />
				</span>
			</span>
		</button>
		<div class="ant-modal-header">
			<div class="ant-modal-title" id="rcDialogTitle0">Tools panel</div>
		</div>
		<div class="ant-modal-body">
			Tools panel content
		</div>
	</div>
</div>
```
Nevertheless, it would be ideal if there was no need to use AntDesign's internal styles and generally use your own custom solutions since we have such a nice component as `AntDesign.Modal` ;)
I noticed this way of using the Modal component by accident on the [MDBootstrap page](https://mdbootstrap.com/docs/jquery/modals/generator/) - they use this solution to display cookies consent non blocking panel displayed at the bottom of page...

**Comment by zxyao145** [comment]
Hi, I'm sorry, this may not be the use of Modal, and you can try to use Drawer. And we will try our best to realize this requirement

**Comment by ElderJames** [comment]
support in #4040
