### ISSUE TITLE
Alert does not render description from ChildContent

### ISSUE THREAD

**Issue by szmalec** [ant-design-blazor/ant-design-blazor#875]
### Describe the bug
An Alert component with a description in ChildContent does not display this description.

### Steps to reproduce (please include code)
```
<Alert ShowIcon Type="@AlertType.Info" Message="Alert msg">
    Child content text used as alert description
</Alert>
```
but this works OK:
```
<Alert ShowIcon Type="@AlertType.Info" Message="Alert msg" Class="ant-alert-with-description">
    Child content text used as alert description
</Alert>
```

### Further technical details
I am using: 0.5.0-nightly-2012081156

**Comment by ElderJames** [comment]
Thank you @szmalec
