### ISSUE TITLE
Error when use <Select> component in a <Modal> component

### ISSUE THREAD

**Issue by MEAZ-S3** [ant-design-blazor/ant-design-blazor#882]
When use "Select" component in a "Modal" component and mouse click for show options of select, raise the error:
"Could not find 'AntDesign.interop.elementScrollIntoView' ('elementScrollIntoView' was undefined)"

**Comment by MutatePat** [comment]
This issue is related to the .js file provided by Ant Blazor being out of date. To solve this, please Ctrl-F5 of use a JS CDN to get the ant Blazor js file. I believe this issue can be closed, as it's related to the user rather than this project.

**Comment by ElderJames** [comment]
Thank you @MutatePat 😊

**Comment by BadarAljahwari** [comment]
Thank you @MutatePat
