### ISSUE TITLE
[select] in the form the selected content is slow to respond

### ISSUE THREAD

**Issue by Seanxwy** [ant-design-blazor/ant-design-blazor#886]
The selected content is slow and particularly slow to respond.
If it's not in the Form, it's a little faster to select it

@ElDiddi In the new Select use, do you have this situation

**Comment by ElderJames** [comment]
Please help us to check whether 0.8 still has this problem.

**Comment by albustan** [comment]
I'm running it on Blazor server-side, in my machine it works fine but when I deploy to azure the select last almost 3 seconds to show the options after I click it.
