### ISSUE TITLE
Calendar visual bug

### ISSUE THREAD

**Issue by Hona** [ant-design-blazor/ant-design-blazor#890]
First cell that is selected:
![image](https://user-images.githubusercontent.com/10430890/102158729-cf2d4380-3ecd-11eb-9209-11286bda6050.png)

Selecting another cell:
The dark blue line stays on the first selected cell. It should move with the selection
![image](https://user-images.githubusercontent.com/10430890/102158752-dce2c900-3ecd-11eb-824a-bdb9cb2f608d.png)

**Comment by anddrzejb** [comment]
@Hona I think this is ok. The dark blue line indicates current date. This is exactly the behaviour of the react ant-design. And I can see you added this on 15th of the month and that is the date that is marked. Unless I missed something here?
