### ISSUE TITLE
Can't render the treenode of Table when lazily loading it's datasource.

### ISSUE THREAD

**Issue by dblleaf** [ant-design-blazor/ant-design-blazor#891]
### Can't render the treenode of Table when lazily loading it's datasource.
 If the datasource is null or empty, and fetch data in the override method `OnInitializedAsync`. Then the table can't render the treenode.

For the example https://ant-design-blazor.gitee.io/zh-CN/components/table#components-table-demo-tree-data, if the code like this
```
...
<Table DataSource="data" TreeChildren="item=>item.Children">
    <Selection CheckStrictly />
    <Column @bind-Field="@context.Name" />
    <Column @bind-Field="@context.Age" Width="12%"/>
    <Column @bind-Field="@context.Address" Width="30%"/>
</Table>
...
@code{
  Data[] data = null;
  protected override async Task OnInitializedAsync()
  {
    await Task.Delay(1);
    data = ....; 
    // or data = await something();
    await base.OnInitializedAsync();
  }
}
```
I think this code https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/table/Table.razor.cs#L198 should be:
```
            if (TreeChildren != null)
            {
                _treeMode = true;
            }
```
When I set `TreeChildren` delegate it should be tree table, instead of whether the children have data.

**Comment by mat-kul** [comment]
I've discovered similar issue, all repro steps are done in `OnInitializedAsync`:
1. Add rows without children to table
2. Make async operation
3. Add children to existing rows
Result: The table shows rows without tree nodes

The view:
```
<Table DataSource="Nodes" TreeChildren="item=>item.Children">
    <Selection Disabled />
    <Column @bind-Field="@context.Name" />
    <ActionColumn Title="Action">
    </ActionColumn>
</Table>
```

Code behind:
```
public class Node
    {
        public Node(string name)
        {
            Name = name;
            Children = new List<Node>();
        }

        public string Name { get; set; }
        public List<Node> Children { get; set; }
    }

    public partial class TableTest
    {
        private List<Node> Nodes { get; set; } = new List<Node>();

        protected override async Task OnInitializedAsync()
        {
            var nodeNames = new List<string> { "First", "Second" };

            foreach (var nodeName in nodeNames) 
                Nodes.Add(new Node(nodeName));

            // represents some async operation, eg. get data from API
            await Task.Delay(100);

            // nothing happened after this line
            foreach (var node in Nodes) 
                node.Children.Add(new Node("test"));
        }
    }
```

**Comment by dblleaf** [comment]
> I've discovered similar issue, all repro steps are done in `OnInitializedAsync`:
> 
> 1. Add rows without children to table
> 2. Make async operation
> 3. Add children to existing rows
>    Result: The table shows rows without tree nodes
> 
> The view:
> 
> ```
> <Table DataSource="Nodes" TreeChildren="item=>item.Children">
>     <Selection Disabled />
>     <Column @bind-Field="@context.Name" />
>     <ActionColumn Title="Action">
>     </ActionColumn>
> </Table>
> ```
> 
> Code behind:
> 
> ```
> public class Node
>     {
>         public Node(string name)
>         {
>             Name = name;
>             Children = new List<Node>();
>         }
> 
>         public string Name { get; set; }
>         public List<Node> Children { get; set; }
>     }
> 
>     public partial class TableTest
>     {
>         private List<Node> Nodes { get; set; } = new List<Node>();
> 
>         protected override async Task OnInitializedAsync()
>         {
>             var nodeNames = new List<string> { "First", "Second" };
> 
>             foreach (var nodeName in nodeNames) 
>                 Nodes.Add(new Node(nodeName));
> 
>             // represents some async operation, eg. get data from API
>             await Task.Delay(100);
> 
>             // nothing happened after this line
>             foreach (var node in Nodes) 
>                 node.Children.Add(new Node("test"));
>         }
>     }
> ```

Good idea.

**Comment by ElderJames** [comment]
Hi there. Thanks for finding this issue.
Does anyone want to submit PR to repair it?

**Comment by hunterdq** [comment]
<Table DataSource="ProductCategories" TreeChildren="item => item.Children">
    <Selection CheckStrictly />
    <Column @bind-Field="@context.Name" />
    <Column @bind-Field="@context.ParentId" />
    <ActionColumn Title="Action">
    </ActionColumn>
@code {
    ProductCategory[] ProductCategories
    ={
        new(){
            Name="办公用品",
            ParentId = 0,
            ID = 1,
            Children = new ProductCategory[]{
            new(){Name="A4打印纸",   ParentId = 1, ID = 2},
            new(){Name="B5打印纸", ParentId=1, ID =3}
        }},
        new() { Name = "固定资产", ParentId = 0, ID = 4 },
    };

   // 其它查询修改 ProductCategories，可以正常使用，如果ProductCategories不初始化，则查询结果不能显示Children子项
   
}
// 如果按照如下初始化：
    ProductCategory[] ProductCategories
    ={
       new() { Name = "固定资产", ParentId = 0, ID = 4 }, };
    页面加载显示null exception，查询到的数据Children子项也不能正常显示

**Comment by ElderJames** [comment]
目前不初始化的话，是识别不了是children。需要指定children的话请另外创建一个issue。
