### ISSUE TITLE
(Discussion needed) Should the wrapping div be removed from components using Overlay (like Tooltip)?

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/ant-design-blazor#898]
### Is your feature request related to a problem? Please describe.
I was working on improving slider experience. I tried adding a tooltip to the edge(s) and I found out, that when wrapping an edge in a tooltip, the edge was being wrapped by a ```div ``` element. That was causing visual displacement of the edge (was falling our of the slider line) like in this image: 
![image](https://user-images.githubusercontent.com/6518006/102345003-61544b00-3fa5-11eb-888e-0d0bb6d1bfbb.png)

The reason was because the wrapping ```div``` has a hard coded style ```display: inline-block``` in tooltip. Removing it fixes the issue, but also breaks other demos (for example tooltip demo). Or another solution is to add to the tooltip's style attributes something like this: ```Style="display: inline;"```, which in turn renders to this weird sequence:
![image](https://user-images.githubusercontent.com/6518006/102345284-cdcf4a00-3fa5-11eb-9beb-dd0d1f0128c5.png)

but it fixes the displacement issue.
That sent me on a research trip - how does react ant-design addresses this problem? I found out, that it does not wrap into additional ```div```.

### Describe the solution you'd like
So I started wandering how can this be achieved in blazor. That was a challenge, because the parent (tooltip) does not keep any reference of the child (for example slider egde) nor it has any simple access to it. After a lot of research and experiments, I found out the project already has ForwardRef inside (I guess from [this blog entry](https://www.samprof.com/2019/06/03/blazor-forwardref)) - a kind of solution on how to get a reference to a child from a parent. With that, I was able to make appropriate changes to the tooltip and I manage to get rid of the ```div``` and keep the functionality of the tooltip. There are still some other challenges there (like attaching context event), but I do not want to purse a solution that will never be used.
My problem is that this kind of change requires also changes to ```OverlayTrigger``` component which in turn effects a number of other components. Also, that kind of change would be a breaking change - anyone using the components that rely on ```OverlayTrigger``` would have to alter their code to include ```ForwardRef``` in their calls. For example, my new trigger code looks like that (notice extra ```@ref``` in the ```span``` element):
```razor
<Tooltip Title="@("prompt text")" Visible="true">
    <span @ref="@context.Current">Tooltip will show on mouse enter.</span>
</Tooltip>
```

My question is this - should we be interested in getting rid of the extra ```div```? If yes, does anyone have a better suggestion on how to get reference to the child in the parent? Can such reference be extracted from ```RenderFragment```?

**Comment by ElderJames** [comment]
Personally, I think the use of `ForwardRef` is a bit strange, this is different from the general usage.

**Comment by anddrzejb** [comment]
I agree it looks a bit cumbersome. But at least at this stage it seems the only way to get any sensible reference to child component in a parent component. Or is there any other way? 
I mean, maybe this is a futile exercise in making ant-design-blazor as close to its react original and I get that. But if the div is going to stay - should't it be completely transparent, without affecting the layout? Can this be done?

**Comment by ElderJames** [comment]
You are right. There is no other way at present reference to child component in a parent component.
I think it's ok to keep the two options and let the user choose between them.

**Comment by anddrzejb** [comment]
I am not sure if two options are actually achievable. The problem is with the ```RenderFragment ChildContent``` that is used by components like ```Tooltip```, ```Dropdown```, ```Popover``` etc. That ```RenderFragment``` is a property that sits in the ```OverlayTrigger``` (these components inherit from ```OverlayTrigger```). For the ```ForwardRef``` solution to work, we need a ```RenderFragment<ForwardRef> ChildContent``` property type (for the ```ForwardRef``` availability as context during child declaration). The problem is that we cannot have 2 properties with ```ChildContent``` name (I tried, compiler is complaining, including making it virtual or newing in inheriting component). Maybe this could be somehow achieved with new C#9 covariant returns, but I do not think it applies to properties and I do not know if we can actually decorate a method with ```[Parameter]``` and use it as such...

**Comment by ElderJames** [comment]
Is it ok to use one `RenderFragment<ForwardRef> ChildContent` property?

**Comment by anddrzejb** [comment]
I my tests this is what I used. But as I mentioned before, it actually is a breaking change for everyone who is using components that rely on ```OverlayTrigger```, because the component has to receive the reference to child element through context, just like in the example I gave in my first post:
```razor
<Tooltip Title="@("prompt text")" Visible="true">
    <span @ref="@context.Current">Tooltip will show on mouse enter.</span>
</Tooltip>
```
That is why I tried to discuss this. If there will be a decision to depart from current extra ```div``` wrapper (extra in comparison to react ant-design), then the change will be a breaking change for anyone currently using the components in question. There are other changes related to the ```div``` wrapper removal (for instance, the events that are attached to that ```div``` would have to be moved to js) that may (and probably will) introduce even further deeper changes. So this does seem like a substantial work. Is the community up to that?

**Comment by dblleaf** [comment]
The Dopdown component has the same problem.

**Comment by anddrzejb** [comment]
Yes, indeed. I already submitted a draft PR #937 to fix this problem (and actually already applied it in my tests to the dropdown with very promising outcome). It certainly needs more tests and discussion, but I think there is potential.
