### ISSUE TITLE
Table  tree

### ISSUE THREAD

**Issue by hunterdq** [ant-design-blazor/ant-design-blazor#902]
初始化包含Children项可以生成展开行，动态生成Children项不能生成展开行。

**Comment by TimChen44** [comment]
@hunterdq 能提供代码示例吗？

**Comment by hunterdq** [comment]
类：
public class ProductCategory
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int ParentId { get; set; }
        public ProductCategory[] Children { get; set; } //nav. prop to children
    }
razor页面：
<Table DataSource="ProductCategories"  TreeChildren="item => item.Children">
    <Selection CheckStrictly />
    <Column @bind-Field="@context.Name" />
</Table>
razor  code部分：
public ProductCategory[] ProductCategories;
    //    = new ProductCategory[]
    //{
    //            new ProductCategory{Name="办公用品", ParentId = 0, ID = 1, Children = new ProductCategory[]{
    //            new ProductCategory{Name="A4打印纸",   ParentId = 1, ID = 2},
    //            new ProductCategory{Name="B5打印纸", ParentId=1, ID =3}} },

    //            new ProductCategory { Name = "固定资产", ParentId = 0, ID = 4 }
    //        };
上面这样直接初始化可以。
private async Task<ProductCategory> HandleFormSubmit()
{
ProductCategories = await httpClient.GetFromJsonAsync<ProductCategory[]>("api/productcategories/0");
在这一部分不使用api获取数据，按照上面对ProductCategories 赋值，同样children部分不显示
}
这样通过api获取不行；

下面是响应载荷：
[{"id":1,"name":"办公用品","parentId":0,"children":[{"id":2,"name":"A4打印纸","parentId":1,"children":null},{"id":3,"name":"B5打印纸","parentId":1,"children":null}]},{"id":4,"name":"固定资产","parentId":0,"children":null}]

**Comment by hunterdq** [comment]
上面的响应载荷表格只显示："办公用品"和"固定资产"。"办公用品"实际包含的子项："A4打印纸"与"B5打印纸"不能显示。

**Comment by dblleaf** [comment]
可以参考这个
https://github.com/ant-design-blazor/ant-design-blazor/issues/891
