### ISSUE TITLE
Timeline component doesn't track inner items

### ISSUE THREAD

**Issue by CAPCHIK** [ant-design-blazor/ant-design-blazor#904]
### Describe the bug
`Timeline` component doesn't track changes in ChildContent

`TimeLine` doesn't work with the following code
```razor
<Timeline>
    <TimelineItem>Item 1</TimelineItem>
    <TimelineItem>Item 2</TimelineItem>
    <TimelineItem>Item 3</TimelineItem>
    @if (showLast)
    {
        <TimelineItem>By condigtion</TimelineItem>
    }
</Timeline>
<Switch @bind-Value="showLast"></Switch>

@code{
    private bool showLast;
}
```
![ezgif com-gif-maker](https://user-images.githubusercontent.com/12235437/102701124-c38ea380-4264-11eb-94e8-013402fd2a85.gif)

`TimelineItem`s refreshed only in `SetItems` method https://github.com/ant-design-blazor/ant-design-blazor/blob/3f8a5a786fe144c52d46a7150998e48e45cdd34e/components/timeline/Timeline.razor.cs#L107-L111

And invoked from `OnAfterRender` only if `_waitingItemUpdate` is `true` https://github.com/ant-design-blazor/ant-design-blazor/blob/3f8a5a786fe144c52d46a7150998e48e45cdd34e/components/timeline/Timeline.razor.cs#L113-L122

### Steps to reproduce
So for rerender you need to force change one of `Mode` `Reverse` `Pending` to set `_waitingItemUpdate` to `true`
https://github.com/ant-design-blazor/ant-design-blazor/blob/3f8a5a786fe144c52d46a7150998e48e45cdd34e/components/timeline/Timeline.razor.cs#L15-L26

The next code shows that calling `set property` helps

```razor
<Timeline @ref="line">
    <TimelineItem>Item 1</TimelineItem>
    <TimelineItem>Item 2</TimelineItem>
    <TimelineItem>Item 3</TimelineItem>
    @if (showLast)
    {
        <TimelineItem>By condigtion</TimelineItem>
    }
</Timeline>
<Switch @bind-Value="showLast"></Switch>
<Button @onclick="() => { line.Reverse = !line.Reverse; line.Reverse = !line.Reverse; }">Rerender</Button>

@code{
    private Timeline line;
    private bool showLast;
}
```
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/12235437/102701175-60514100-4265-11eb-96c6-b2a9cfdc2123.gif)

### Further technical details
- AntDesign Nuget Package version `0.5.0-nightly-2012180814`
- ` dotnet info`
```bash
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- VS 2019 Enterprise 16.8.3

**Comment by ElderJames** [comment]
Yes, it's a problem. We need to force to refresh at add/remove items.
