### ISSUE TITLE
@ref on Table not referenced to ITable myVariable

### ISSUE THREAD

**Issue by andkur57** [ant-design-blazor/ant-design-blazor#910]
I intensively use Tables in any form, but:
@ref on Table not referenced to ITable myVariable, so myVariable.SetSelection(string[] { ..... }) is inaccesible, also trying to set selectedRows variable (@bind-SelectedRows="....Ienumerable<T> Variable...."  not sucessed with visual selected row/rows.

**Comment by ElderJames** [comment]
Hi @andkur57 , could you please show your code?

**Comment by ElderJames** [comment]
To manipulate component references after the component has finished rendering, use the OnAfterRender or OnAfterRenderAsync methods. See the doc:
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0&WT.mc_id=DT-MVP-5003987#capture-references-to-components
