### ISSUE TITLE
Bug report: The value of overlay.clientWidth will be 0 After showing the overlay for the first time

### ISSUE THREAD

**Issue by Bintel** [ant-design-blazor/ant-design-blazor#922]
### Describe the bug
The value of **_overlay.clientWidth_** will be **_0_** After showing the overlay for the first time. It will cause the calculation of **_left_** to get an incorrect value (See [https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/core/Component/overlay/Overlay.razor.cs#L339-L360](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/core/Component/overlay/Overlay.razor.cs#L339-L360)), and the position of overlay will be wrong after the first show.

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by mutouzdl** [comment]
目前在Show函数里是有针对第一次显示时做处理的：[Overlay.razor.cs#L164](https://github.com/ant-design-blazor/ant-design-blazor/blob/8763fda680d9942a3812480ff17e451fac989465/components/core/Component/overlay/Overlay.razor.cs#L164)
你是在什么情况下触发这个问题的，可以展示一下代码吗？

-------------------------------
There is currently a process in the Show function for the first display: [Overlay.razor.cs#L164](https://github.com/ant-design-blazor/ant-design-blazor/blob/8763fda680d9942a3812480ff17e451fac989465/components/core/Component/overlay/Overlay.razor.cs#L164)
Under what circumstances did you reproduce this issue, could you show the code?

**Comment by Bintel** [comment]
Thanks for your reply @mutouzdl 

当我应用 [这次 commit](https://github.com/ant-design-blazor/ant-design-blazor/pull/921/commits/32273a82cb92feefe02a4fbcb445e795f28d4809) 的修改暴露出 Placement 参数之后，如果我把 Placement 的值修改为 BottomRight 或者 BottomCenter，就会发现这个问题。经过调试，我发现 overlay.clientWidth 的值在第二次展示下拉列表开始就一直为 0，导致 left 的计算值偏高（因为是减 overlay.clientWidth），下拉列表会向右偏移。因此我推测是这个问题。
- - -
After I apply [this commit](https://github.com/ant-design-blazor/ant-design-blazor/pull/921/commits/32273a82cb92feefe02a4fbcb445e795f28d4809) to expose the parameter of Placement, I found this issue if I set Placement to the BottomRight or BottomCenter. I found that the value of overlay.clientWidth will be 0 since the second show, it will cause the left to become a higher value (because it is the calculation of subtract), and the overlay will shift to the right. So I speculate that this is the problem.
- - -
```
<SubMenu Title="@($"Hello, {context.User.Identity.Name}")" Placement="PlacementType.BottomRight">
    <MenuItem>
        <a href="/user/profile">Profile</a>
    </MenuItem>
    <MenuItem>
        <a class="nav-link" @onclick="BeginSignOut">SignOut</a>
    </MenuItem>
</SubMenu>
```
