### ISSUE TITLE
[modal] An exception appears when switching pages

### ISSUE THREAD

**Issue by Yuanxw612** [ant-design-blazor/ant-design-blazor#926]
![image](https://user-images.githubusercontent.com/15828095/103080058-0a3b1f80-4610-11eb-9ee2-1d09811c37b8.png)

blazor wasm project

Page A uses modal, click cancel to quit modal, switch to page B will appear this exception

**Comment by zxyao145** [comment]
已经定位到bug的原因了，对于 DestroyOnClose=false 的组件，AntDesign会操作其DOM，是由于使用组件式创建的Modal的生命周期由Blazor进行管理，不能通过js来进行DOM的操作，否则当页面变化时Blazor将会找不到这个DOM。

目前的解决方案是：
- 将 DestroyOnClose 设置为 true
- 使用 ModalService 创建 Modal

我将会在本周日前修复它，感谢您的反馈！
