### ISSUE TITLE
The child node of tree is not render of the 'Ant Design of Blazor' demo web site

### ISSUE THREAD

**Issue by powerumc** [ant-design-blazor/ant-design-blazor#934]
### Describe the bug
I visit demo web site today, https://ant-design-blazor.github.io

The child node of the `Tree` is not render in the `Tree` section demo.
And `Add son node` not working.
https://ant-design-blazor.github.io/en-US/components/tree

![image](https://user-images.githubusercontent.com/1943755/103275308-3f2be580-4a07-11eb-96dc-8131e1bac425.png)

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by powerumc** [comment]
That problem is show the Chrome, Firefox on Mac OS.

**Comment by ElderJames** [comment]
Thanks for contacting us @powerumc 
It may be fixed via #941 ,please check again.

**Comment by powerumc** [comment]
Good!
Thanks.
