### ISSUE TITLE
Search Input not centred, and grey underline on button

### ISSUE THREAD

**Issue by Hona** [ant-design-blazor/ant-design-blazor#940]
Search Icon for search input is not centred in the button.

![image](https://user-images.githubusercontent.com/10430890/103325124-0e46c180-4a96-11eb-9f3d-aff89b237cb9.png)

There is also a grey underline on the search button.

**Comment by andrewpbaer** [comment]
We ran into this issue as well. For us, it ended up being caused by css conflicts. Specifically, bootstrap was being included in our index.html. When we removed bootstrap, the icon was centered correctly. I hope this helps.

**Comment by ElderJames** [comment]
Did you import other styles that made the style conflict?

**Comment by Hona** [comment]
Yeah it ended up being bootstrap
