### ISSUE TITLE
RangePicker: range visualization for quarterly and weekly ranges are not correct

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/ant-design-blazor#945]
For range picker ```DatePickerType.Quarter``` and ```DatePickerType.Week``` the visual cue of the range does not seem to work properly.

What we have now:
![image](https://user-images.githubusercontent.com/6518006/103621203-82bdac80-4f3d-11eb-873e-7547bd0c0b0c.png)

What is expected:
![image](https://user-images.githubusercontent.com/6518006/103621406-d03a1980-4f3d-11eb-8c2d-cc4d3fdfbda5.png)

*screenshots based on the docs page for [ant-design-blazor](https://antblazor.com/en-US/components/datepicker) and [ant-design](https://ant.design/components/date-picker/)*

I believe similar problem is with week, however it seems that react ant-design has the same issue. After a bit of digging I found the [issue #27984](https://github.com/ant-design/ant-design/issues/27984), where it seems that for week it is by design. However I can also see people being confused by the inconsistency of the range picker behaviour.

**Comment by Alexander3** [comment]
This is still a problem, why this issue is closed? I guess we should continue discussion here: https://github.com/ant-design/ant-design/issues/27984

**Comment by Alexbits** [comment]
@ElderJames @Alexander3 From what I see, the `DatePickerType.Quarter` looks good in the latest version. The `DatePickerType.Week` is not showing the selected range. Correct me if I'm wrong.

**Comment by Alexbits** [comment]
@ElderJames @Alexander3 #2892  adds range visualization to the `DatePickerType.Week`. It makes the week picker more consistent with other pickers in terms of how the selected range looks. But it has its downsides, too (see screenshots).

<img width="418" alt="image" src="https://user-images.githubusercontent.com/3949302/202917791-7e374a70-5c6e-4f39-8526-0edbe301e5e6.png">

As a downside, selecting the week that exists on both panels looks a bit cramped.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/3949302/202917897-803223f9-06f1-4962-ad7c-406a0e6e990d.png">
