### ISSUE TITLE
Some string attributes such as type, icon and sharp in the space are suggested to be modified into enumeration

### ISSUE THREAD

**Issue by itxiaoqiu** [ant-design-blazor/ant-design-blazor#964]
Some string attributes such as type, icon and sharp in the space are suggested to be modified into enumeration。

For example: Type="primary" can be modified to Type="@ButtonType.Primary", which is more standardized than the string, and there can be hints, so it is not easy to make mistakes.

**Comment by ElderJames** [comment]
Thanks for your suggestion @itxiaoqiu .
There is already a PR #835 on this job, and we will review it and merge it in the next release.
