### ISSUE TITLE
SelectOption razor and cs in different namespace

### ISSUE THREAD

**Issue by Magehernan** [ant-design-blazor/ant-design-blazor#968]
### Describe the bug
The class SelectOption Razor is in @using AntDesign.Select.Internal and SelectOption cs is namespace AntDesign

### Further technical details
Commit Tag 0.5.2

**Comment by ElderJames** [comment]
Thank you for contacting us  @Magehernan ,

I think they are the same
![image](https://user-images.githubusercontent.com/7550366/104198228-ef1a3d80-5460-11eb-8075-9f6a91f2fe40.png)

**Comment by Magehernan** [comment]
jajaja sorry... i am trying to use the SelectOption in my project so it isnt working and i look fast... sorry but i cant use select option... i will try if i am doing something wrong... best regards!
