### ISSUE TITLE
Upload控件FileList布局错乱

### ISSUE THREAD

**Issue by wyy272176594** [ant-design-blazor/ant-design-blazor#976]
Upload控件FileList布局错乱。
之前使用0.4.1版本是正常的。但版本更新后发现Upload控件FileList布局错乱。

**官网文档中的Upload控件布局也是错乱的，如下图：**

![image](https://user-images.githubusercontent.com/11676739/104313047-6e1b7e80-5512-11eb-8bab-5d5ba52f59cd.png)

**检查元素发现元素class渲染成了"(", 如下图：**

![image](https://user-images.githubusercontent.com/11676739/104313377-e5e9a900-5512-11eb-9935-bd713d2689b7.png)

希望可改进，谢谢。

**Comment by ElderJames** [comment]
你好，感谢提醒 @wyy272176594 
既然你找到了原因，欢迎提交PR~
