### ISSUE TITLE
AntInputComponentBase<TValue> not working with IEnumerable<T>

### ISSUE THREAD

**Issue by charsville** [ant-design-blazor/ant-design-blazor#978]
I am trying to build my own component that inherits from the AntInputComponentBase. The input component I am building will have a value that is an IEnumerable<T>.

My custom component has an OnChange event which fires fine. In that event I am trying to update AntInputComponentBase Value, so that I can use @bind-Value in my form. 
Example of custom component below:
```
@inherits AntInputComponentBase<IEnumerable<T>>
@typeparam T

...
...

private async Task OnChange(OnChangeArgs args)
    {
        // Get latest value after change
        IEnumerable<T> newValue = args.value;
        
        // Update Ant base input Value property
        Value = newValue;
        
        // Fire the Ant base input ValueChanged callback with the new value
        await ValueChanged.InvokeAsync(Value);
    }
```

and then I use my custom component within an ant-design-blazor Form and FormItem component (See below):

```
<Form Model="@_model">
   <FormItem>
      <CustomComponent T="Person" @bind-Value="@_model.SelectedPersons" /> 
   </FormItem>
</Form>

@code {
    public class Model {
         public IEnumerable<Person> SelectedPersons { get; set; }
    }
    
    public class Person {
       public string name { get; set; }
    }
   
    public Model _model = new Model();
}
```

When I run this code and use my component SelectedPersons is updating with the correct values and the component appears to work. However, it is still throwing an error, if I look at the console logs I get the following error:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Please use @bind-Value in the control with generic type `System.String`.
System.InvalidOperationException: Please use @bind-Value in the control with generic type `System.String`.
  at AntDesign.FormItem.AntDesign.Internal.IFormItem.AddControl[TValue] (AntDesign.AntInputComponentBase`1[TValue] control) <0x34f1090 + 0x0006a> in <filename unknown>:0 
  at AntDesign.AntInputComponentBase`1[TValue].OnInitialized () <0x34f0c98 + 0x00022> in <filename unknown>:0 
  at AntDesign.Input`1[TValue].OnInitialized () <0x34f0ac0 + 0x00004> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2ea4340 + 0x00030> in <filename unknown>:0 
```

This error ONLY occurs when I put my CustomComponent within the ant-design-blazor Forms.

After digging through the code, it seems that when the control is being added to the Form, it uses the IFormItem.AddControl<TValue> method, which explains why it only happens when inside a Form. However in the error it says that TValue is a System.String. Which is not true, because at the top of my CustomComponent I define TValue as an IEnumerable<T>.

**Comment by ElderJames** [comment]
Thank you for contacting us @charsville 

We'll look at how easy it is to let users customize their own components with form.

**Comment by anddrzejb** [comment]
I think #1120 is a connected issue.

**Comment by ElderJames** [comment]
Hi @charsville , we support the `bind-Values` now, see #1460.
