### ISSUE TITLE
Table Column nested class binding

### ISSUE THREAD

**Issue by BadarAljahwari** [ant-design-blazor/ant-design-blazor#986]
I have class that contain navigation properties of other class. 
When trying to bind property of child class I got exception.

Ex, by modifying official sample: 
`public class MyChildClass { public string  Name { get; set; } }`
`public class WeatherForecast
    {
        public int Id { get; set; }
        public MyChildClass User { get; set; }
    }`
<Column @bind-Field="@context.User.Name" Sortable /> will though exception.

Could you please help on this.

**Comment by ElderJames** [comment]
Thank you for contacting us @BadarAljahwari 

We will try to solve this issue. For now, you can use a auto property for workaround.

```
public class ParentClass
{
       public MyChildClass User { get; set; }

      public string MyChildClassName 
      { 
              get => User.Name;
              set => User.Name = value;
      } 
}
```

**Comment by BadarAljahwari** [comment]
Thank you for your response & the workaround.

**Comment by BadarAljahwari** [comment]
Thank you for your response and workaround.
The auto property not worked with me, don't know why.
However I fill it manually after getting the list
` listProjectMembers.ForEach(a => a.MemberFullNameAux = a.ProjectMemberUser.FullName);`

**Comment by ElderJames** [comment]
Hi @BadarAljahwari , 

we have support the `DataIndex` feature in #999  , and have been support the nested class binding.
Please update the package to the last 0.6.0 nightly verion.

**Comment by BadarAljahwari** [comment]
Actually, I am still got exception: Object reference not set to an instance of an object.
Don't know if its related to my code or the table control.

**Comment by ElderJames** [comment]
Please debug your code again, whether If the user is null?

**Comment by BadarAljahwari** [comment]
> Please debug your code again, whether If the user is null?

Sorry for delay
I test it with official examples and the issue still exist.. will keep update.
below is my test sample:

```
public class Data
    {
        [DisplayName("Key")]
        public string Key { get; set; }
        [DisplayName("Name")]
        public string Name { get; set; }
        public Child child { get; set; }
    }

    public class Child
    {
        public string MyProperty_Child { get; set; }
    }

List<Data> data = new List<Data>
{
        new()
        {
            Key = "1",
            Name = "John Brown",
            Age = 32,
            Address = "New York No. 1 Lake Park",
            Tags = new[] {"nice", "developer"},
            child=new Child(){MyProperty_Child="Test1" }
    },
```

`  <Column @bind-Field="@context.child.MyProperty_Child"></Column>`

**Comment by ElderJames** [comment]
Please use `DataIndex`:  `<Column DataIndex="child.MyProperty_Child"></Column>`

**Comment by BadarAljahwari** [comment]
<Column TData="string" DataIndex="@context.childData.ChildProperty"></Column>

Also through exception

Regards

**Comment by bodzilla** [comment]
> Please use `DataIndex`: `<Column DataIndex="child.MyProperty_Child"></Column>`

How would one use this, could you give a real life example please?

**Comment by anranruye** [comment]
@BadarAljahwari  @bodzilla 
try this:
```C#
@code{
    public class MyChildClass 
    { 
        public string Name { get; set; } 
    }
    public class WeatherForecast 
    { 
        public int Id { get; set; } 
        public MyChildClass User { get; set; } 
    }
}
<Table ...>
    <Column Title="UserName" Field="@context.User?.Name" DataIndex="User.Name" Sortable>@context.User?.Name</Column>
</Table>
```

**Comment by anranruye** [comment]
> Please debug your code again, whether If the user is null?

@ElderJames  I guess the user is null for the header cell, where the row data is not provided by the component user.

**Comment by DrTekno** [comment]
> @BadarAljahwari @bodzilla try this:
> 
> ```cs
> @code{
>     public class MyChildClass 
>     { 
>         public string Name { get; set; } 
>     }
>     public class WeatherForecast 
>     { 
>         public int Id { get; set; } 
>         public MyChildClass User { get; set; } 
>     }
> }
> <Table ...>
>     <Column Title="UserName" Field="@context.User?.Name" DataIndex="User.Name" Sortable>@context.User?.Name</Column>
> </Table>
> ```

Filter and sort are working fine, but table's onChange not triggered when filter or sort are fired from this column.

**Comment by vadimffe** [comment]
I am wondering, can you make some knowledge base somewhere? There are so much information to know, that is not on your official documentation website. The only way is to Google and find it from GitHub issues.

**Comment by ElderJames** [comment]
Hi there, I have fix this issue finally in https://github.com/ant-design-blazor/ant-design-blazor/pull/2624 . Thanks all !
