### ISSUE TITLE
Col Tag is tagged as self-closing throwing compiler warning

### ISSUE THREAD

**Issue by Konstantin-tr** [ant-design-blazor/ant-design-blazor#995]
### Describe the bug
The <Col> tag is described as self-closing, meaning it should be written as "<Col />" meaning it has no content, however, the basic functionality of the Col tag makes it obvious that it should have content like 90% of the time. Having content in the tag will then give a compiler warning.

### Steps to reproduce (please include code)
To reproduce, simply but anything inside a <Col> tag.

```
<Col Span="12">
<p>This is some content.</p>
</Col>
```

This will already give a compiler warning.

### Further technical details
- AntDesign 0.5.3
- Microsoft.AspNetCore.App 5.0.1
- Found in Visual Studio 2019 Enterprise Edition

**Comment by ElderJames** [comment]
Thanks for contacting us @Konstantin-tr 

This is the VS issue. You can use `AntDesign.Col` or `GridCol`

**Comment by bezysoftware** [comment]
While this might be a VS issue, your doc samples are broken because of it. It's plain confusing to copy-paste something from official documentation and have compilation fail.

**Comment by anddrzejb** [comment]
@bezysoftware you are correct. There is so much to do in the project and not enough contributors. I understand this can be extremely frustrating when something that should work does not and the answer is buried deep in a closed issue. Do you think you could help us with improving the docs?
