### ISSUE TITLE
Link to contribution guide is broken

### ISSUE THREAD

**Issue by mat-kul** [ant-design-blazor/ant-design-blazor#996]
### Describe the bug
A link to contribution guide is broken (not found)

### Steps to reproduce
[https://github.com/ant-design-blazor/ant-design-blazor/blob/master/.github/CONTRIBUTING.md](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/.github/CONTRIBUTING.md)

**Comment by ElderJames** [comment]
Thank you @mat-kul 
The link is https://antblazor.com/en-US/docs/contributing
