### ISSUE TITLE
Bug when binding an nullable enumeration to the Select

### ISSUE THREAD

**Issue by itxiaoqiu** [ant-design-blazor/ant-design-blazor#998]
1、Select控件对枚举类型支持绑定支持不太友好，建议直接增加枚举类型的绑定选择，这样更加方便。
Select component is not very friendly to the enumeration type support binding support, it is recommended to add the enumeration type binding selection directly, which is more convenient.

2、使用自定义将枚举转换成list集合进行绑定后，出现了BUG，具体如下：
After using custom to convert the enumeration into a list collection for binding, a bug appeared, as follows:

2.1、代码：
![image](https://user-images.githubusercontent.com/65268639/104921554-75400200-59d4-11eb-8fc2-32087f88d6e2.png)

2.2、EnumHelper是自定的扩展方法，可以枚举转换成List集合进而进行绑定，但是Bind-Value中LeadSource是一个Nullable<LeadSources>的枚举类型，及可为空的，这样用来不选择则是空值进行绑定，但是实际出现选择任何选项时，Select在前端不会显示选中的内容，但是Bind-Value的LeadSource却是有刚选择的值。
![image](https://user-images.githubusercontent.com/65268639/104921515-635e5f00-59d4-11eb-9215-9aaa17d6ec36.png)
其实上图已经选择了一个枚举项，并且后台LeadSource也是有值的，就是前端不显示选中的内容的BUG。

**Comment by ElderJames** [comment]
Hi @itxiaoqiu ,this issue is duplicated with #825

**Comment by anddrzejb** [comment]
This is tightly connected to localization. I think we can start working on it once we figure out the localization approach.
